### ISSUE TITLE
Memory leak and concurrency issue in 'EventHandlerServlet'

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1000]
IMHO there is a huge memory leak and beside that a concurrency issue in the newly added `EventHandlerServlet`.

There is only a single queue for buffering events. This queue is unbounded and if no web session reads those events, then the queue will fill up until all memory is used up.

Beside that events which have been sent to one user won't be sent to others.

**Comment by amitjoy** [comment]
Yes, it has been kept unbounded intentionally. The events fired by WireEmitter instances are maintained here. There also exists consumer threads which consumes the data from this queue. So, we can make sure that for every data produced by the queue, there will be enough number of consumers to consume this data at the same time. There cannot be data producers without consumers or vice versa. And that's why the queue is unbounded.

**Comment by ctron** [comment]
The only consumer of this queue is the `doGet` method of the servlet.

So when Wire applications are running (in the background) they are producing events. Filling up the queue. So as long as no one keeps a Web UI open, Kura will OOM at some point. Is that the intention?

Beside that only one Web UI session will receive events. So the Web UI may only be used by a single user. Is that also intentionally.

**Comment by amitjoy** [comment]
The size of the `ConcurrentLinkedQueue` is unbounded and if producers are producing values faster than the consumers, it can indeed end up with OOM. It is definitely better to switch to bounded blocking queues to prevent OOM. Good catch 👍.

**Comment by amitjoy** [comment]
I will make the necessary changes.

**Comment by amitjoy** [comment]
It has to be reopened. I have started developing a generic bundle that streams OSGi events using Server Sent Events. I am using the following libraries to develop the bundle:

- Jetty EventSource Servlet - https://github.com/jetty-project/jetty-eventsource-servlet
- Jetty Continuation - https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-continuation

Using this bundle, any Server Sent Event clients can subscribe to any Event Admin Topic and receive updates in asynchronous way. I will make the PR by tomorrow.

**Comment by cdealti** [comment]
@MMaiero I believe the original memory leak issue has been resolved, right?
In this case can we close this and open another one referring to the old content if needed?
