### ISSUE TITLE
BLE Connection Limits

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1004]
During the BLE connect process, Kura should check for cases where too many BLE links are already present. The error from GATTTOOL reports as:

Connecting... connect error: Too many links (31)

This case should be handled explicitly and immediately terminate the connect process instead of waiting for a timeout. A specific error should also be thrown to indicate that the maximum number of devices have been connected.

@pierantoniomerlino Thoughts on this?

**Comment by pierantoniomerlino** [comment]
@dwoodard1 It seems that the maximum number of connections is an hardware limitation, so I agree with you to handle this exception separately.

**Comment by dwoodard1** [comment]
@pierantoniomerlino Yes, it is a hardware limitation. Luckily, GATTTOOL seems to always report with the same error message. So, we should be able to provide the "too many links" error independent of the hardware used.

**Comment by cdealti** [comment]
I believe the legacy BLE API and implementation will be soon phased out, preferring the Tinyb one.
