### ISSUE TITLE
Document how to set up Raspberry Pi (1)

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1008]
To me it looks like as if the Raspberry Pi foundation has abandoned the original Raspberry Pi distribution [1]. There is no clear way what and how to download and setup a Raspberry Pi for Kura.

If we still need as Raspberry Pi (for ARMv5 SF) then we should document this in order to allow proper testing.

[1] https://www.raspberrypi.org/downloads/

**Comment by ctron** [comment]
So from what I have read here [1] and hereh [2] our ARMv5 SF target would be obsolete?!

[1] http://elinux.org/RPi_Distributions#What_is_armhf.3F
[2] http://elinux.org/RPi_Distributions#Debian_.28Squeeze.2F6.x.29

**Comment by MMaiero** [comment]
Can we close this issue due to the merging of #1018?
