### ISSUE TITLE
Memory leak in ConfigurationService

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1012]
There is a memory leak in the configuration service. To the map `m_pendingDeletePids` items will only be added. But never removed.

**Comment by MMaiero** [comment]
@ctron Maybe I didn't get the point but the elements in m_pendingDeletePids aren't removed here? https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java#L1565

**Comment by ctron** [comment]
I just had a look at it. I should have been more verbose I guess. I don't remember it myself 😉  ...

Maybe I did mean `m_ocds` (which actually is a map and not a set). To me it also looks like `m_pendingDeletePids` gets cleared. The while loop still leaves room for missing removals. But I don't remember if that was the case.

Let's close it and wait for some OOM situation ....
