### ISSUE TITLE
Drop support for ARMv5 SF/soft float

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1013]
As all models of the Raspberry Pi back to model 1 support ARMv6 HF/hard float, there seems to be no need to maintain additional native binaries for the ARMv5 SF target.

**Comment by ctron** [comment]
So just to remember from the last project call. Kura currently doesn't make use of ARMv5,  but we still want to leave them in Kura for the time being. With one of the next Kura versions we will provide a to re-compile those binaries with the Kura build system.

**Comment by cdealti** [comment]
@MMaiero I believe we decided to remove them. @ctron do you agree?

**Comment by MMaiero** [comment]
Working on this.
Do we want to drop also x86?

**Comment by ctron** [comment]
+1
