### ISSUE TITLE
Re-compile with libudev.so.1

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1014]
To me it seems as if all target support `libudev.so.1`. So instead of maintaining two native variants I would suggest to drop support for `libudev.so.0` and switch to `libudev.so.1`.

**Comment by cdealti** [comment]
@unverbraucht can you please check if you need to continue supporting libudev.so.0 for the PC engine distrib?

**Comment by dwoodard1** [comment]
@jread Can you respond to the above comment from @cdealti ? We will start the QA process for Kura v3.0.0 in the coming weeks, so we need to make sure you can still QA the PC Engine distribution.

**Comment by unverbraucht** [comment]
Hi guys,

the PC engines board is running Debian 8 in our setup so libudev.so.1 should be perfect.

**Comment by cdealti** [comment]
@ctron duplicate of #1321?
