### ISSUE TITLE
Fix Fedora target to use libudev.so.1

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1015]
The merge of the Kura 2.1.0 branch into the Kura 3.0.0 develop branch brought back the issue of linking against the missing `libudev.so.0` library.

**Comment by MMaiero** [comment]
@ctron I think that this is fixed right? Now the linux.usb fragment uses libudev.so.1, right?

**Comment by ctron** [comment]
At least the 64bit version, I am not sure about the rest.

We should check with `ldd`, just to be sure. And drop any symlinks which got created in the past.

**Comment by cdealti** [comment]
@ctron can we close this? Fedora works!

**Comment by ctron** [comment]
True, Fedora works.

**Comment by azzadin7** [comment]
Hello, may i know what version of fedora you used and it works with kura ? And is the installation way of kura will be the same with raspberry installation.

Thanks

**Comment by MMaiero** [comment]
@azzadin7 Please have a look here: https://github.com/eclipse/kura/tree/develop/kura/distrib/src/main/resources/fedora25
