### ISSUE TITLE
PR #1007 broke distribution for assets

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1024]
Currently, when trying to instantiate an asset from the wire composer, the Javascript part returns an INTERNAL_ERROR exception.

**Comment by ctron** [comment]
Hard to test as there is no driver instance in Kura currently. Do you have some steps to reproduce?

**Comment by MMaiero** [comment]
I'm doing a full testing, for that reason I've assigned the issue to me. 
But was pretty logic, since we divided the bundle in two, to add the newly created bundle into the distribution. Obviously those things happen. So, no problem on this. I wanted just to track the activity.

I will push a PR soon with the fix.

**Comment by MMaiero** [comment]
Closing due to #1035 merging
