### ISSUE TITLE
Eclipse Drag and Drop Review

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1032]
As the Eclipse Marketplace is planning a major update in conjunction with our M1 release, we should review the drag and drop functionality in Kura.

**Comment by dwoodard1** [comment]
@MMaiero Can this be closed with #1102 ?

**Comment by cdealti** [comment]
@MMaiero ping

**Comment by MMaiero** [comment]
We discussed this during the weekly project call: the integration done till now has been improved in M1, so a first step of improvement has been done. We still miss a review of the existing apis, in order to be able to determine if new features need to be integrated.

**Comment by MMaiero** [comment]
@nicolatimeus Will try to see what is the effort to extend the marketplace integration

**Comment by MMaiero** [comment]
The part for the marketplace notification has been completed and added to Kura 3.1.0.
I will review the PR by @nicolatimeus about the version check.
