### ISSUE TITLE
Rename org.eclipse.kura.asset.provider.default to org.eclipse.kura.asset.utility.provider

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1033]
Consequent to PR #1007 the org.eclipse.kura.asset.provider was splitted into 2 separate bundles:

- org.eclipse.kura.asset.provider

- org.eclipse.kura.asset.provider.default

In my opinion the org.eclipse.kura.asset.provider.default name is a little bit misleading because the ".default" suffix has never been used before in our bundles and because the org.eclipse.kura.asset.provider.default is, in reality, not an implementation of APIs provided in org.eclipse.kura.asset.provider. As an example in org.eclipse.kura.asset.provider we have BaseAsset class that is a real implementation that has to be used to programmatically leverage the asset feature without wires support.

For these reasons, I would suggest to rename the org.eclipse.kura.asset.provider.default project into org.eclipse.kura.asset.utility.provider 
What do you think?

**Comment by ctron** [comment]
IIRC this bundle hosts at least two services. So naming it "utility" seems a bit misleading.

**Comment by MMaiero** [comment]
What would be your proposal?

**Comment by amitjoy** [comment]
The `.default` bundle provides utility service implementations. `org.eclipse.kura.asset.utility.services.provider` would be my recommendation

**Comment by ctron** [comment]
So the reason for that was simply that is was previously all in the `org.eclipse.kura.asset.provider` bundle, which seemed to be fine then. Adding `default` as the default implementation.

I am strongly against `utility` as this is currently used nowhere else either. Which we could also change of course. So adding `utility` to the package name would help then. Also `utility` to me indicates something which cannot live on its one. Which is not the case here as this bundle registers at least two services. Which are not intended for subclassing.

This bundle contains two services, implementing services from `org.eclipse.kura.asset` and `org.eclipse.kura.driver`. So this already is a mixup. But we could simply stick to `assets`  as the dominant package name. 

Following the currently schema would probably make to something containing `core` in the bundle. Like `kura.core`, `kura.core.configuration`. So if we just follow this pattern it would probably something like `org.eclipse.kura.core.asset.provider`?!

**Comment by amitjoy** [comment]
The `org.eclipse.kura.core.feature` is the old naming convention that Kura followed. When we started developing Kura Wires, we followed the naming scheme that OSGi community suggests - `.api` for the api bundle and `.provider `or `.adapter` for implementation. Hence, we followed this schematic pattern for nomenclature.

As `Asset` and `Driver` belongs to a same component model and Asset is dependent on Driver, it has been kept together in the same bundle. The `AssetService` and `DriverService` are utility services that provides utility methods to work on Assets and Drivers.

**Comment by ctron** [comment]
So maybe you could reference to this decision and to the specification. I think that would help.

**Comment by amitjoy** [comment]
It is actually specified by OSGi enRoute project.

http://enroute.osgi.org/tutorial_base/300-api.html

**Comment by amitjoy** [comment]
To simplify the things, I am proposing the following changes.

1. New Bundle - `org.eclipse.kura.asset.helper.provider` - that will contain `AssetService`
2. New Bundle - `org.eclipse.kura.driver.helper.provider` - that will contain `DriverService`
3. `org.eclipse.kura.asset.provider`will stay as it is that contains `Asset` implementation - `BaseAsset`

In this way, we will have more flexibility of replacing an implementation at runtime easily.

**Comment by amitjoy** [comment]
Fixed by #1035

**Comment by MMaiero** [comment]
I was thinking in having only two bundles grouping all the asset stuff into a bundle and all the driver stuff into another. But I don't find a proper naming for the driver part. Also, the result could seem a little bit asymmetrical. So, I agree in having the bundles split in 3 (#1035) for the time being. If we find a better solution later, we will modify that properly.

**Comment by amitjoy** [comment]
Grouping assets in one bundle would result in having 2 service implementations in one bundle. This is okay but in considering the advantages of OSGi, any of these service implementations won't be dynamically updated in the OSGi runtime container. So, at best separating these services in respective bundles would enable runtime updation.

It looks as if the services related to Asset Component Model are scattered around but the naming convention of the projects signifies the grouping of bundles in respective feature. We can also create features or subsystems to group bundles depending on the features that the bundles correspond to.

**Comment by MMaiero** [comment]
Closing since #1035 was merged
