### ISSUE TITLE
Clean up or remove 'pom_pom.xml'

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1040]
Looking at the `pom_pom.xml` file it looks to me as if the only two modules which are still using this are `distrib` and `tools`. Digging deeper into the structure looks like that this could me massively improved. Which could also help to clean up the mess of two POM files in a single directory, renaming `manifest_pom.xml` back to `pom.xml`.

The `pom_pom.xml` could either be removed and only necessary section be ported over to either the tools or the `distrib` project or we could create a new parent module for both of them. But looking into the way the `distrib` module is currently being activated, this looks like all the profiles will always result in an activation of the `distrib` module and thus making the different profiles unnecessary.

**Comment by dwoodard1** [comment]
I agree, I believe the pom_pom.xml can be merged into the manifest_pom.xml. And the manifest_pom.xml renamed to pom.xml. This was a historical artifact for when we needed both a "manifest first" and "pom first" build. 

I am not sure I follow your logic on the profiles. I use this feature quite often when building for a specific target. For example, running mvn -f pom_pom.xml -Praspberry-pi-2-3 will only generate installers artifacts for the Raspberry Pi 2/3. This saves a considerable amount of time in the build.

**Comment by ctron** [comment]
I agree on the latter part for the "distrib" project. But I was only referencing the main/parent pom_pom list of profiles. I use the distrib profiles myself pretty often.
