### ISSUE TITLE
[GPS] When GPS fix is acquired, is not possible to switch back to static position

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1051]
In order to reproduce this issue, proceed as follows:
1. enable the position service and select static position: the static coordinates will be published.
2. disable static position and wait for acquiring a fix from GPS: the new coordinates will be published.
3. switch back to static position: the new static position will NOT be published.

**Comment by ctron** [comment]
I think is a duplicate of #918

**Comment by pierantoniomerlino** [comment]
@ctron I totally agree. I'll close the PR.
