### ISSUE TITLE
Not waiting for process to finish in LinuxProcessUtil doesn't work

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1062]
Some methods in org.eclipse.kura.core.linux.util.LinuxProcessUtil class have a parameter "wait" with which you can wait for the process to finish or immediately continue.

When I set "wait" parameter to "false" I expected that it will not wait for the process to finish, but it doesn't.

I noticed that in the LinuxProcessUtil.java file on line 44 ProcessUtil.exec() method is called which always waits for the process to finish. Stepping into this method I traced the bug to the SafeProcess.java file on line 97.

**Comment by djurod** [comment]
I investigated this a little more and found out that both "wait" and "background" parameters in LinuxProcessUtil class methods are totally useless, because in the end when you start a process it will ALWAYS wait for the process to finish.

Also it appears that "internal" uses of this class (in other Kura bundles) in almost all cases already calls the start method which waits for the process to finish. I found only two uses of startBackground() method, which, according to the supplied parameter, should wait, but because of the way this class is implemented it actually does.

There are also a few "FIXME:MC This leads to a process leak" comments that should ideally be resolved...

My recommendations for fixing this are:
- Remove both parameters. This will simplify the API so that only the supported functionality is exposed.
- Fix the implementation. This would mean that also the lower level classes would need to be fixed or extended.

Because of these issues I am unable to continue writing tests for this class as either at least a few of the methods will be removed. The current implementation doesn't really allow me to check if my test are written correctly.

**Comment by ctron** [comment]
What speaks against using Apache Commons Exec instead of some self made functionality?!

**Comment by cdealti** [comment]
Nothing. However I believe that ACE creates two new threads for every command executed.
This is why we have never used it.

To make a long story shorter, the self made functionality was added as a temporary workaround to prevent a memory leak occurring with some versions of the JVM but it has been fixed now.

I agree it should be replaced with something else but I would like to understand the implication it terms of memory footprint, CPU usage, long term stability etc.

**Comment by MMaiero** [comment]
Since Kura 4.2.0 this class is now deprecated. Closing.
