### ISSUE TITLE
I am working on eInfochips eragon410 board(qualcomm processor)

### ISSUE THREAD

**Issue by shankarit1252** [eclipse/kura#1063]
I have installed linux OS on the device, will this eclipse kura works to receive sensors data through BLE.
could u help me out

**Comment by dwoodard1** [comment]
@shankarit1252 Github Issues is typically used for tracking bugs in the framework or new features to be added. This type of question is better suited for the mail list or forums [1]. To answer your question, there is not a Kura version that officially supports qualcomm processors. If you would like more information on the question, please post to the mail list or the forum.

[1] https://www.eclipse.org/forums/index.php/f/273/

Thanks,
--Dave
