### ISSUE TITLE
Change Package Infos in API Bundle that contain @since annotation

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#1069]
Wires and its related packages that contains `@since` annotations in its package infos contain wrong information about its availability using package versions. We can also use `@version` as OSGi core and compendium specifications also use this.

**Comment by cdealti** [comment]
@amitjoy I've addressed this here:

https://github.com/cdealti/kura/tree/api-analysis

**Comment by MMaiero** [comment]
Closing since the related PR was merged
