### ISSUE TITLE
CloudCallServiceImpl - call methods setting requester.client.id to #client-id sends response to local device

### ISSUE THREAD

**Issue by wnagele** [eclipse/kura#108]
I just tried using `CloudCallServiceImpl` to send `CONF-V1` requests to a Kura device. It seems to me that there is a bug in that implementation.

On line 122 it sets the `requester.client.id` to the topic placeholder `#client-id`. This in turn is send to the remote Kura device which then replaces it with its own client-id when sending the response. Not the intended outcome. This prevents the response from ever being picked up by the sender - it subscribes to the correct topic beforehand (using the same placeholder on line 110.

Before looking into a fix for this - am I missing something here? The problem with fixing this is that the client-id isn't available inside that implementation.

I've tested with manually providing the correct client-id on line 122 and that works properly.

Hints?

**Comment by cdealti** [comment]
Nice catch! The ``CloudCallService`` is only used by JUnit tests and this passed unnoticed.

The right fix would be to get the client ID from the Kura ``DataTransportService`` [1].

Can you submit a PR with such a fix?

[1] http://download.eclipse.org/kura/releases/1.3.0/docs/apidocs/

**Comment by dwoodard1** [comment]
@cdealti Should we address this or remove the CloudCallService?

**Comment by cdealti** [comment]
It's an API and its removal would be a major chance. Did we agree on breaking the API in 3.0? Or should be wait until really needed

**Comment by dwoodard1** [comment]
I thought we were breaking the API in 3.0. If so, we should probably just remove it. If not, should fix the Service at is currently broken.

**Comment by cdealti** [comment]
I'll start with ``@deprecated``

**Comment by cdealti** [comment]
Closing as all the deprecated API will be removed at the same time
