### ISSUE TITLE
Possible NPE and non-working check

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1092]
In `DeploymentPackageUninstallOptions.java` the following check is done:

```java
super.setJobId((Long) request.getMetric(METRIC_JOB_ID));
if (super.getJobId() == null) {
  throw new KuraInvalidMessageException("Missing jobId!");
}
```

However the parameter type of `setJobId` is actually `long` instead of `Long`. So instead of the `KuraInvalidMessageException` a NPE will be thrown here.

Beside that I don't see any ready to prefix every call with `super`.

**Comment by MMaiero** [comment]
@ctron Have you already started implementing something? Otherwise, I can take care of these DEPLOY-V2 issues.

**Comment by ctron** [comment]
No, I haven't done anything here.

**Comment by cdealti** [comment]
@markoer @darionct is this something you have noticed?

**Comment by markoer** [comment]
One test actually touched this issue, but (wrongly) assumed it expected behavior.
