### ISSUE TITLE
Easy Installation of Development Environment

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#110]
To ease the setup of Development Environment, an **Oomph Catalogue** can be provided. Many eclipse projects, for instance, **E4 Tools**, **EMF** provide **Oomph Catalogue**s for a hassle free development environment setup.

Another solution could be to create an **Yatta Profile** to package an **Eclipse Installation** which abstracts all the required steps for Development Environment setup.

**Comment by mcarrer** [comment]
+1 great idea.

Is anybody in the community willing to help us getting it started?

Thanks.
-Marco

On Mar 31, 2016, at 11:00 PM, Amit Kumar Mondal <notifications@github.com<mailto:notifications@github.com>> wrote:


To ease the setup of Development Environment, an Oomph Catalogue can be provided. Many eclipse projects, for instance, E4 Tools, EMF provide Oomph Catalogues for a hassle free development environment setup.

Another solution could be to create an Yatta Profile to package an Eclipse Installation which abstracts all the required steps for Development Environment setup.

-

**Comment by amitjoy** [comment]
For my personal use, I have created an **_Yatta Profile_** which comprises all the necessary plugins and the bundles from a specific branch (_**kura2**_) for the Development Environment setup.

You can find it in [https://marketplace.yatta.de/](https://marketplace.yatta.de/).

**Comment by mcarrer** [comment]
Thanks Amit, that’s great.

@Dave - can we advertise this in the Kura web site?
https://marketplace.yatta.de/profiles/l6NV

@Amit - is the Yatta Profile something that can be automated with the Kura build so we can have this automatically created in every build?

-Marco



On Apr 2, 2016, at 7:45 PM, Amit Kumar Mondal <notifications@github.com<mailto:notifications@github.com>> wrote:


For my personal use, I have created an Yatta Profile which comprises all the necessary plugins and the bundles from a specific branch (kura2) for the Development Environment setup.

You can find it in https://marketplace.yatta.de/.

**Comment by amitjoy** [comment]
So far what I have explored, I couldn't find any such maven integration to create automated build for a Yatta Profile. But if there is a change in the specified kura branch, for instance, new bundles are added, then all the bundles including the new ones will automatically be imported while setting up new development environment. 

For instance, the Yatta Profile that I have created tracks **_kura2_** branch and if a new developer wants to setup development environment for the first time, this Yatta Profile will automatically import all the existing projects from **_kura2_** branch.

**Comment by mcarrer** [comment]
If we create a yotta profile on the master branch, we should be able to have a it following the product releases.

Would that work?


On Apr 3, 2016, at 12:43 AM, Amit Kumar Mondal <notifications@github.com<mailto:notifications@github.com>> wrote:


So far what I have explored, I couldn't find any such maven integration to create automated build for a Yatta Profile. But if there is a change in the specified kura branch, for instance, new bundles are added, then all the bundles including the new ones will automatically be imported while setting up new development environment.

For instance, the Yatta Profile that I have created tracks kura2 branch and if a new developer wants to setup development environment for the first time, this Yatta Profile will automatically import all the existing projects from kura2 branch.

**Comment by amitjoy** [comment]
Yeah, we can create an Yatta Profile on the Master branch as well, so that in the following releases it would track the released changes on the branch. That would work.

**Comment by dwoodard1** [comment]
Hi Amit,

I just tried the profile and it worked great! Very cool stuff. Maybe we should setup a profile for the master and develop branch. I would be happy to promote this on the Kura website.

One question, the profile seems to tie the Kura source code location to the Eclipse installation directory. Is that configurable? It is not a big deal, it was just a bit confusing for me.

Thanks and let me know if I can help get this rolling.

Thanks,
--Dave

On Apr 4, 2016, at 06:17, Amit Kumar Mondal <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, we can create an Yatta Profile on the Master branch as well, so that in the following releases it would track the released changes on the branch. That would work.

**Comment by amitjoy** [comment]
Hi Dave,

As you suggested, I have created two Yatta Profiles for _master_ as well as _develop_ branches.

https://marketplace.yatta.de/profiles/4d0a - Develop
https://marketplace.yatta.de/profiles/1B8n - Master

As the profile is tied to the branch provided in the configuration, it clones the complete repository in its Eclipse installation folder. I couldn't find any such configurable property to set the location. If I find any way to configure this, I would update the profiles then.

**Comment by amitjoy** [comment]
@dwoodard1 @mcarrer @cdealti 

Please do find the new updated Yatta Profiles for _**Kura Development Environment setup**_.

https://marketplace.yatta.de/profiles/X4Wj - _develop_ branch
https://marketplace.yatta.de/profiles/OqmT - _master_ branch

These profiles now perform all the **manual tasks** (_importing projects, building the target platform, building all the bundles, setting up custom target platform_ and so on) **automatically**. Now contributors can setup their development environment very easily (within 2-3 clicks).

I believe these profiles would definitely help future contributors.

**Comment by ibinshtok** [comment]
Use profiles to new web page.

**Comment by cdealti** [comment]
@dwoodard1 Can we close or postpone this?

**Comment by cdealti** [comment]
@dwoodard1 I think so.

**Comment by ctron** [comment]
I think this is solved by PR #320 using the Eclipse Installer.

**Comment by dwoodard1** [comment]
Closing this issue. We now have a Yatta profile and Oomph installer for Kura. Any issues with these methods should be tracked separately.
