### ISSUE TITLE
[Kura 3.0.0 M1 QA] Default kura.style.dir doesn't exist

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1106]
In the fresh Kura installation kura.style.dir points to /opt/eclipse/kura/console/skin which is not present in installation. This results in warning during startup:
`WARN  o.e.k.w.s.s.SkinServlet - Resource Directory /opt/eclipse/kura/console/skin does not exist`

RPi3, Kura 3.0.0-SNAPSHOT build 940

**Comment by MMaiero** [comment]
Expected by design.
If you want to customize the UI style, you can specify a custom css in the console/skin folder and have that applied instead of the default one, without the need to recompile the web ui.

**Comment by markoer** [comment]
It seems that having the directory available does no harm, but prevents the warning. It might be a compromise to create the directory during installation.

**Comment by MMaiero** [comment]
I believe we can consider this as P2 and eventually apply some changes for M2. Do you agree on that?

**Comment by markoer** [comment]
Of course, it's not an error, so it's not really that important.

**Comment by cdealti** [comment]
Why don't we simply remove the warning?
