### ISSUE TITLE
[Kura 3.0.0 M1 QA] Issue with modal confirmation dialog(s)

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1107]
Modal dialogs tend to not be closed if user presses Enter while they are open.

Steps to reproduce:
* Update clock.ntp.host
* Click Apply
* Press Enter
* Confirm Save dialog (Yes)

Dialog doesn't close, but action is taken i.e. configuration is saved. The dialog's buttons are still enabled and functioning.

The same behavior is observed with warnings on leaving the current site:
* Update clock.ntp.host
* Go to another page
* Press Enter
* Press No - you stay on the page, but dialog is still open
* Press Yes - you leave the page, but dialog is still open

RPi, Kura 3.0.0-SNAPSHOT build 940

**Comment by MMaiero** [comment]
@markoer I'm trying with build 941 (but between them there shouldn't be changes affecting the configuration part of the UI) and I don't see the problem.

The dialog is always disappearing.

Why you press Enter before confirming?

**Comment by MMaiero** [comment]
Wait. I cannot reproduce the issue with Safari. With Chrome I see what you mean. But it seems that you are stacking confirm modals one over the other.

**Comment by markoer** [comment]
I got this result with Firefox.
Why I pressed Enter? I just tried if there's a default, yet. And the result surprised me a bit.
But you're correct. Somehow 2 modals were opened. It seems the first one doesn't properly focus. And only one of them is ever successfully hidden. The problem is that the second refuses to close short of pressing the close button (X). Maybe add close()/hide()/... to Yes and No, too.

**Comment by MMaiero** [comment]
I think a possible solution could be the one in #1109.
Could you give it a try?
If it is ok also for you, I will merge it and tag the M1 for the QA build.

**Comment by markoer** [comment]
#1109 looks OK, locally. It actually solves 2 things - default button and Enter.
Granted, you can still tab away from the buttons in the modal dialog and then press Enter, but that's just pushing it :)
When you merge it, I'll try the scenario with the CI server's build.

**Comment by markoer** [comment]
Verified in build 945.
