### ISSUE TITLE
[Kura 3.0.0 M1 QA] Kura Wires doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1113]
Steps to reproduce:
- Connect to Kura web page in Internet Explorer
- Select System->Wires

The blue "overlay" with the gear symbol is shown, but the gear symbol doesn't rotate and the complete web page is frozen. When you reload the web page it recovers unless you open Wires again...

BeagleBone Black, Kura 3.0.0-SNAPSHOT build 943
Internet Explorer v11.0.9600.18537

**Comment by djurod** [comment]
According to @markoer he had the same problems on RPi3. Otherwise it appears to work (at least it loads the web page) on Chrome and Firefox.

**Comment by amitjoy** [comment]
In addition, the `EventSource` is not fully compliant with IE as well. I investigated a bit on resolving the issue with `EventSource` in IE.

As I don't have any IE to check if Wires works on IE, I can't confirm on any potential reason for such behaviour on IE. But I can try to make a PR to partially solve the `EventSource` issue on IE.

**Comment by cdealti** [comment]
@MMaiero In the last Kura weekly call I believe we decided to postpone this, right?

**Comment by MMaiero** [comment]
No, we decided to simply disable the events to IE merging #1152 in Kura 3. In the meanwhile, we will discuss about the changes proposed by @amitjoy in #1151 but them will eventually be added only for Kura 4.0.0 or 3.x.

**Comment by MMaiero** [comment]
I think we can also close this when #1152 is merged because, excluding sse every other feature of Wires works with IE. Eventually, later, we will open another issue to add sse support for IE.
