### ISSUE TITLE
[Kura 3.0.0 M1 QA] Wires: cannot add component after deleting one

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1121]
After a component is removed graph must be saved if you want to add a new component:
![image](https://cloud.githubusercontent.com/assets/22816717/23206623/9dcd1352-f8ee-11e6-9c86-57bc39b8a763.png)

It is an annoying limitation that should be removed, if there is no specific need for it.
Option is for this dialog to allow saving the graph and the desired component is added immediately after the dialog is closed.

Low-priority issue.

Kura 3.0.0-SNAPSHOT, build 945.

**Comment by amitjoy** [comment]
This has been implemented for the following reasons:

1. If the user deletes a Wire Component of name "a", and adds it again
2. On clicking on new Wire Component "a", the old associated properties will be shown
3. It's more frustrating to see properties of old Wire Component "a" in the new one
4. I thought, it is better to delete a Wire Component and save the Wire Graph first before adding a new one

**Comment by markoer** [comment]
In this case, make the dialog as proposed above:

Do you want to save the graph before continuing?
(Y) / N

And then continue adding the component.

**Comment by amitjoy** [comment]
According to your proposed dialog, what happens if the user does not save the Wire Graph and adds a Wire Component with the same name?

I have mandated `Saving a Wire Graph after deleting a Wire Component ` to get rid of the possibilities of adding a Wire Component with the same name.

I am open to suggestions.

**Comment by ctron** [comment]
I am sorry, but I cannot follow that argument from https://github.com/eclipse/kura/issues/1121#issuecomment-281627616

Now when you create a new component and don't save the graph, what properties are shown in this case?

**Comment by amitjoy** [comment]
Suppose you have a Wire Component in the Wire Graph with name - `MyComponent`. In the runtime, it is an OSGi service that associates several properties. Now when someone deletes this Wire Component from the Wire Graph, the Wire Component is just visually removed from the Wire Graph but not from the runtime. The user must click on save to reflect all these changes such as removing a Wire Component from the Wire Graph or adding new one.

Now after the removal, the user adds another Wire Component with the same name `MyComponent`. If we do not mandate saving the Wire Graph after deleting a Wire Component, in this case, clicking on `MyComponent` Wire Component will display the associated properties of old `MyComponent` that has just been removed visually from the Wire Graph which I felt more misleading to the users.

**Comment by markoer** [comment]
So it seems that when you create a new graph, the behavior is different. Is there any chance to treat the graph in the same way regardless of whether you are editing a new one or an old one? I.e. keep all the components including their configuration on the client and push everything when the graph is saved.

If not - and saving is still mandatory - there's also the following to consider. There's a possibility that the user won't want to save the new graph. Or will want to cancel the changes. If you want to avoid problems here, Kura should get user's consent before saving. A slight modification of the presented dialog solves this issue: Do you want to save and continue? Y => save and add the new component; N => just close the dialog and wait.

**Comment by ctron** [comment]
Thanks @amitjoy  for this explanation. However this was not the question I asked.

So, when the user creates a new component and **does not** save the graph, what properties are shown when the user clicks on it?

**Comment by amitjoy** [comment]
@ctron For the first time, it displays the input fields without any associated properties.

**Comment by amitjoy** [comment]
@markoer I agree that there can be a number of ways to implement this feature but as of now, it needs users to save the Wire Graph before adding a new Wire Component to the Wire Graph. You are right that a user can make the Wire Graph dirty and also want not to save it but discard. It can be done if the user moves on to another page in Kura Web UI and select discard dirty changes but I agree with you that there should be a button just above the Wire Graph canvas -`Discard Local Changes` or similar to discard all dirty changes thereon.

**Comment by ctron** [comment]
@amitjoy  Great, so do the same when the component gets removed and re-added. And you are done.

**Comment by amitjoy** [comment]
@ctron When the Wire Component gets removed by the user from the Wire Graph, it is not removed from runtime but visually from Wire Graph and the user needs to click on save to have it removed from runtime.

**Comment by ctron** [comment]
@amitjoy Cool ... but if the user does not click save ... and you let him add a new component (even with the same name) and remember (by yourself) that you just added this and then apply the same logic as if the component was just created. Then you would have an easy and understandable workflow for the user.

**Comment by amitjoy** [comment]
@ctron If I let him add a new Wire Component to the Wire Graph, then clicking on the new Wire Component will display the associated properties of the old Wire Component as it is still present in the runtime.

**Comment by ctron** [comment]
So, as I said .. here is what you need to do ... implement a new functionality, a boolean state, which records the information that the new component is not yet saved. And in that case, show the other properties, not the ones currently present in the runtime.

**Comment by amitjoy** [comment]
The implementation to achieve this is a bit complex. I will try to have a look at it and find a suitable solution.
