### ISSUE TITLE
[Kura 3.0.0 M1 QA] Bugs in camel example publisher

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1123]
Two bugs were found in the org.eclipse.kura.example.camel.publisher:

1. Wrong period is applied for both int and double signals
In examplePublisher.makeSine() method the frequency needs to be doubled. It is currently `pi / T` but it should be `2 * pi / T`.

2. Amplitude for double signal is not read correctly from the configuration
Name of the configuration value in the xml is `double.amplitude` but it should be `double.amp`

**Comment by MMaiero** [comment]
@djurod I've merged #1124. Can this be closed?

**Comment by djurod** [comment]
Yes
