### ISSUE TITLE
[Kura 3.0.0 M1 QA] Wires: Unexpected component configuration is shown

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1125]
Steps to reproduce:
- Add a modbus service and name it "modbusDriver"
- Go to Wires and add any component and name it "modbusDriver"

Expected result: Appropriate component configuration for the selected component

Actual result: Content of the modbus service configuration is shown instead of the expected wires component configuration.

Note: the problem appears to be triggered when you name the Wires component the same as the modbus service.

**Comment by djurod** [comment]
By some coincidence I found it also "works" with the CamelFactory service (which is btw not actually shown in the service list after you add it...).

It appears that if you use the same name as one of the (manually added?) services it shows you the configuration for that service and not the Wires component...

**Comment by amitjoy** [comment]
This is quite weird as the in the runtime `kura.service.pid` is unique. It appears that the problem that you guys have encountered consequently signifies that in the runtime 2 separate service components acquired same `kura.service.pid`.

**Comment by MMaiero** [comment]
@nicolatimeus Will manage this
