### ISSUE TITLE
[Kura 3.0.0 M1 QA] Unable to delete manually added CamelFactory services

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1128]
Steps to reproduce:
1. Manually add a CamelFactory service (Services --> [+])
2. Go to System --> Cloud Services
3. Select the manually added service from step 1 and click on the delete button

Expected result: The selected service should be removed

Actual result: Service is not removed, even after trying to delete it multiple times.

**Comment by ctron** [comment]
The actual issue is that the service should not be allowed to be created in the first place.
