### ISSUE TITLE
CamelContext should not be restarted on the service properties update

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#113]
Currently `MetatypePropertiesFunction` restarts `CamelContext` when SCR properties are updated. We should not do it, as it interrupts messages flow.

**Comment by hekonsek** [comment]
I plan to remove support for `MetatypePropertiesFunction` until somebody (@gautric?) would like to create the version of that function which doesn't restart router.

**Comment by hekonsek** [comment]
I vote for temporary removal of that function, as Camel context uptime is more important for production applications than having SCR-properties.

**Comment by cdealti** [comment]
By SRC you mean SCR? Do you mean the configuration properties of your ``ConfigurableComponent``?

The properties can be received both in the ``activate`` and ``updated`` methods of your declarative service. ``activate`` is called once while ``updated`` is called at every configuration change.

Can you describe your context in greater detail?

**Comment by gautric** [comment]
the main idea is the reuse of Metatype configuration in order to inject some attributes to configure Camel route via some placeholder.
The current component could be improved and should manage configuration update as well as possible.

**Comment by hekonsek** [comment]
Yes, I mean SCR :)

Currently Camel Context is restarted on every `updated` invocation. Unfortunately it is unacceptable behavior as it interrupts flow of the messages in a gateway. So if we want to support Metatype-based properties for Camel (which could be a nice addition) then we should find a way to feed SCR properties into Camel without restarting Camel Context.

**Comment by cdealti** [comment]
Understood. Can you start the Camel Context on ``activate`` and just update it (without restarting it - assuming this is possible) on ``updated``?
Is this a Camel or OSGi/Kura limitation?

**Comment by hekonsek** [comment]
I think it should be possible just to update without Context restart. I just don't have time right now to investigate it, so I would prefer to have `MetatypePropertiesFunction` removed for a while. It is better not to support `MetatypePropertiesFunction` for some time then to restart Camel context on every properties update event.

**Comment by hekonsek** [comment]
Done. The support for `MetatypePropertiesFunction` has been removed for a while. @gautric Feel free to create a pull request with `MetatypePropertiesFunction` which doesn't require to restart `CamelContext`.
