### ISSUE TITLE
ConfigurableComponentTracker calls bundleContext.getService(ref) when it shouldn't

### ISSUE THREAD

**Issue by scottslewis** [eclipse/kura#1131]
Currently the ConfigurationServiceImpl creates and starts a ConfigurableServiceTracker.  Here's the source for ConfigurableComponentTracker:

https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurableComponentTracker.java

The ConfigurableServiceTracker is created with this constructor code:

        // TODO: find a better filter
        // This works but we track everything
        super(context, context.createFilter("(" + Constants.OBJECTCLASS + "=*)"), null);

As it says in the comment this filter of objectClass=* means that every created service is tracked.   One consequence of this is that all services registered will have their context.getService(ref) method called by this tracker, whether or not they have any actual consumers.    This is wasteful and defeats the declarative services laziness.

Another consequence is that for extenders like OSGi Remote Service Admin and Blueprint, the calls to getService(ref) will fail (return null) because these extenders create proxies for the service, and they are specified to use the Bundle consumer (in this case org.eclipse.kura.core.configuration) to load the service interfaces classes.   Because the kura configuration bundle classloader does/will not have access to some service interfaces classes (e.g. those services created by apps, etc) it will be unable to call context.getService(ref) when these extenders are being used.

Ideally the ConfigurableServiceTracker should not track all services, but rather some subset (e.g. based upon service properties or service interfaces) of services in order to avoid creating spurious errors when proxies are created.

**Comment by ctron** [comment]
There currently is a way to achieve this, unfortunately this is not the default behavior of Kura at the moment.

You can set the system property `org.eclipse.kura.core.configuration.trackOnlyRelevantServices` to `true` and it will not use the `ConfigurableComponentTracker` but do proper tracking of services. However it was considered a breaking change back when I made this change and so the default sticks with the "track all" approach.

Also see: https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java#L85

**Comment by ctron** [comment]
I would suggest to remove the old behavior as Kura 3.0.0 may do breaking changes.

**Comment by scottslewis** [comment]
Hi Jens,   Is the System property you mention in your comment relatively new?   I'm setting it to true with 2.1.0 and I'm not getting the expected behavior (i.e. I'm still getting the ConfigurableComponentTracker tracking/adding/calling getService on my services).

**Comment by ctron** [comment]
You are right. This is only present in Kura 3.0.0.

**Comment by ctron** [comment]
... better said ... will be present ...

**Comment by ctron** [comment]
I opened a PR for removing the old behavior: https://github.com/eclipse/kura/pull/1137

**Comment by cdealti** [comment]
@ctron can this be closed?
