### ISSUE TITLE
Factory Components Configurations not deleted from the snapshot

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#1139]
When deleting a factory configuration through the `deleteFactoryConfiguration` API, the component configuration is not removed from the snapshot.

The Factory Configuration for the component is then restored at next restart, rendering deletion of Factory Components instances impossible.

Even when uploading a brand new snapshot not containing the configuration of the Factory Components, the merge between the running configuration and the newly uploaded file restores said configurations in the snapshot.

**Comment by MMaiero** [comment]
Checked in Kura 3.0.0-SNAPSHOT and the issue seems solved.
Closing.
