### ISSUE TITLE
ClockService should ignore updates with long 'getDelay'

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#1160]
kura 1.4

details in this post:
https://www.eclipse.org/forums/index.php/t/1084809/

```
InetAddress ntpHostAddr = InetAddress.getByName(m_ntpHost);
TimeInfo info = ntpClient.getTime(ntpHostAddr, m_ntpPort);
m_lastSync = new Date();
info.computeDetails();

m_listener.onClockUpdate(info.getOffset());
ret = true;
```

before calling 'onClockUpdate' there should be a guard condition eg

`if (info.getDelay() < 1000)`

as an aside, it also appears `ntpClient.close();` is only called if an exception is raised. this should be in a finally.

**Comment by MMaiero** [comment]
@pierrepitiot Could you take care of this?

**Comment by pierrepitiot** [comment]
Yes I will

**Comment by MMaiero** [comment]
@pstanton We created PR #1218 to solve this issue. Could you give it a look and see if it solves your issue? Thanks.
