### ISSUE TITLE
TinyB library integration

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1164]
The tinyB library (https://github.com/intel-iot-devkit/tinyb) is a small and easy to use Bluetooth LE API.
It exposes the BLE GATT API for Java using BlueZ over DBus.

The idea is to try to integrate this small library with Kura.

**Comment by cdealti** [comment]
@pierantoniomerlino what are the system requirements of TinyB?

* Bluez version?
* Glib version?

**Comment by cdealti** [comment]
@pierantoniomerlino can you please add the steps needed to run this on the Raspberry Pi (e.g. compile the minimum required version of BlueZ)?

**Comment by pierantoniomerlino** [comment]
The requirements for tinyb are:
- glib-2.0>=2.40
- gio-2.0>=2.40
- gio-unix-2.0>=2.40
- Bluez-5.43 (see [1] for more info; successfully tested also with 5.41)

[1] https://github.com/intel-iot-devkit/tinyb/issues/58

**Comment by pierantoniomerlino** [comment]
Installation guide for tinyB on a RaspberryPi3

1. Update
sudo apt-get update

2. Install Oracle JDK:
sudo apt-get install oracle-java8-jdk

3. Install missing packages
sudo apt-get install libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev libglib2.0 doxygen cmake git

4. Update Bluez to 5.43
	1. Download bluez-5.43.tar.xz
	2. tar -xf bluez-5.43.tar.xz
	3. cd bluez-5.43/
	4. ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-library -disable-systemd --enable-experimental --enable-maintainer-mode
	5. make
	6. sudo make install
	7. edit /lib/systemd/system/bluetooth.service : ExecStart=/usr/libexec/bluetooth/bluetoothd -E

5. Reload bluetooth.service
	1. sudo systemctl daemon-reload
	2. sudo systemctl restart bluetooth.service

6. Install tinyB
	1. git clone https://github.com/pierantoniomerlino/tinyb.git
	2. cd tinyb
	3. git checkout interfacename
	4. set variables:
		export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt
		export JAVA_AWT_LIBRARY=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/arm/libawt.so
		export JAVA_JVM_LIBRARY=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/arm/server/libjvm.so
		export JAVA_INCLUDE_PATH=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/include
		export JAVA_INCLUDE_PATH2=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/include/linux
		export JAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/include
	5. mkdir build
	6. cd build
	7. cmake -DBUILDJAVA=ON ..
	8. make
	9. sudo make install
	10. sudo cp java/tinyb.jar /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/ext/

7. Run HelloTinyB
	1. sudo su
	2. cd /home/pi/tinyb/build
	3. export LD_LIBRARY_PATH=/usr/local/lib
	4. java -cp examples/java/HelloTinyB.jar:/usr/local/lib/java/tinyb.jar HelloTinyB <address>
