### ISSUE TITLE
Wrong order of operations in WireAsset

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1166]
In WireAsset.onWireReceive() method from org.eclipse.kura.internal.wire.asset package (from org.eclipse.kura.wire.component.provider bundle) the method documentation says that first all associated reading channels are read and after that all associated writing channels are written, but the method is implemented in a way that first the writing channels are written and then the reading channels are read.

Is this a bug in implementation or in documentation?

@amitjoy: since it appears that you originally wrote both the documentation and the implementation where this inconsistency was already present, maybe you could comment on the correct order?

**Comment by amitjoy** [comment]
The correct order of execution is to read the channels first and then perform write operations. During minor changes in WireAsset, this order got swapped. It is fixed by #1167.
