### ISSUE TITLE
Kura Wires: Inconsistent design of DbServiceHelper class

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#1176]
I found something in [DbServiceHelper](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/common/DbServiceHelper.java) that is at least a bug in documentation. The getInstance() method is documented in a way that makes you think you are dealing with a singleton, but the only thing it actually does is that it calls the only (private) constructor in the class.

Probably this was meant to be a singleton at some point in the past and later changed basically to an ordinary class and the getInstance() method and its documentation remained. In this case I would recommend that the getInstance() method is removed and the constructor is made public.

But this could also be an incorrect attempt to make a singleton. This might be a bigger issue.

After taking another look at what the class does I would even say that it is probably even not needed. The only thing it does compared to the class it »wraps« is that it adds a few small features:
- execution of a SQL statement (with optional `int` parameters) in a transaction
- sanitation of SQL table and column names

From what I see it would make more sense to add these features directly in the DbService and just work directly with it instead of having this wrapper.

Also it might make more sense to replace the optional `int` parameters in the execute() method with optional `Object` parameters to make it more usable.

**Comment by djurod** [comment]
@amitjoy could you please check this?

**Comment by amitjoy** [comment]
The `DbServiceHelper` is an extended version of `DbService` that composes `DbService` and provides useful functionalities required for DB Store and DB Filter Wire Components.

You are right, the documentation erroneously signifies it to be a singleton but it is a faulty Javadoc generation by `JAutodoc` plugin in Eclipse as `getInstance()` method is mostly used in Singleton pattern. My motive was to incorporate a `static factory pattern` (not **Factory** or **Abstract Factory**) that prefers static factory methods to constructors. 

I have also made PR #1177 that fixes relevant Javadoc issues and renames the method `getInstance()` to `of(DbService)` for better comprehension of this class.

**Comment by djurod** [comment]
This of course solves the direct issue, but I would still recommend to move the extended functionality to `DbService`, but only in case it is generally useful and not just for Kura Wires.

This is something that you might want to discuss with whoever is responsible for the `DbService` API...

**Comment by amitjoy** [comment]
I completely agree with the idea of using `DbService` as a full-fledged version instead of requiring such helper classes that wraps `DbService` to provide extended service functionalities. I am also not sure if `execute(..)` kind of methods will be appropriate to `DbService` as it has been made very generic to SQL connections and such `execute()` operations have not been included as these are performed by `Statement` and its sub interfaces.
