### ISSUE TITLE
Get ready for Java 9

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1186]
Although we just recently adopted Java 8, there is an effort at Eclipse going on to target compatibility for Java 9 [1], which is scheduled to arrive mid 2017.

I think we should try out Java 9 and see in which issues we are running before that final GA.

[1] https://wiki.eclipse.org/Java_9_Readiness

**Comment by kartben** [comment]
I have just recently (successfully) run Kura 3.2.0 on Java 9 but it requires upgrading to Oxygen.1a.
Note that Equinox now ships Apache Felix SCR instead of the Equinox implementation. This didn't seem to cause any obvious regression but may require some extra testing.

I am happy to provide a patch if people are interested.

**Comment by ctron** [comment]
Sounds like a good idea!

**Comment by MMaiero** [comment]
Hi Benjamin,
I believe it's a great idea!

We are considering anyway an upgrade of Equinox in one of the next releases (for now it's an idea, it still needs to be carefully planned) so it could be a good starting point to have a branch targeting the integration of a new Equinox and Java 9.

**Comment by ctron** [comment]
I would really like to see an updated version of SCR sooner rather than later. I would be happy to review and merge a PR.

@MMaiero Maybe you could explain what is required beyond a working PR from @kartben

**Comment by kartben** [comment]
I am not sure upgrading equinox and enabling Java9 compatibility has to be part of the same effort?
But yeah I will submit a PR starting with the upgrade to Equinox Oxygen.2 (which will bring Apache Felix SCR)

**Comment by MMaiero** [comment]
As you probably understand, such set of changes require a full round of QA tests to verify that everything works and probably has also effects on dependent projects.
We are a project that is quite stable and widely used in production so we must be very careful in terms of changes we perform.
Having a separate PR allows us to have it split from develop and mergeable at the right time, depending also on the planning done by the project lead.

**Comment by ctron** [comment]
My understanding is that there is an upcoming release of Kura. Which requires QA to be performed anyway. As this change wouldn't introduce any incompatibilities (and if we could make a decision based on that) I don't see any reason which speaks against merging such a PR.

Which effects on which dependent projects do you exactly mean? I think it is important for the community to understand what could hinder an upcoming change to be merged into Kura.

**Comment by kartben** [comment]
Please see PR #1916 for the proposed update to Equinox Oxygen.2.
It would be great to get this merged sooner than later - fwiw I doubt that this is in any way "riskier" than the Jetty bump which happened a few months back? Equinox is pretty stable, no?

**Comment by ctron** [comment]
Yes, I see it the same way.

I am currently giving the PR a test run. So far no issues, everything looks fine.

**Comment by MMaiero** [comment]
I believe this can be closed now.
