### ISSUE TITLE
[Wires] Components can be hidden outside the graph area

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1188]
If Wires graph is created on a higher resolution with more space for components and browser window is later resized to smaller size, the components may be hidden. The same happens if such a graph is opened in a smaller window in the first place.

![image](https://cloud.githubusercontent.com/assets/22816717/23895090/e356ba66-08a4-11e7-9d8d-7c59d7981edc.png)

Options are probably these:
* use relative component positioning
* add scrollbar(s)
* don't allow to resize canvas/browser to less that graph width
* dynamically re-order to fit

Kura 3.0.0-SNAPSHOT build 976
RPi3
FF, Chrome

**Comment by MMaiero** [comment]
Should be solved by PR #1750
