### ISSUE TITLE
[Camel] Migrate CamelRouter tests from Rhiot to Kura

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#119]
We have some nice unit tests for CamelRouter which should be migrated from Rhiot to Kura. That would give us some safety net against regressions.

**Comment by cdealti** [comment]
Postponed to Kura 2.1.0

**Comment by hekonsek** [comment]
Hi Jens,

I was thinking about this [1] test. Also migrating `io.rhiot.component.kura.test.TestKuraServer` from Rhiot to Kura might be useful.

[1] https://github.com/rhiot/rhiot/blob/master/gateway/components/camel-kura/src/test/java/io/rhiot/component/kura/router/RhiotKuraRouterTest.java

**Comment by ctron** [comment]
I just browsed through the code. It looks to me that there are some Felix specific things in there. And the class is rather small. Starting another CQ for that ... I don't know.

I think in the same time I can replicate what you are doing by starting from scratch. What do you think?

**Comment by ctron** [comment]
I re-created the actual unit test. Sticking to JUnit4 components.

**Comment by cdealti** [comment]
@ctron Can we close it?

**Comment by ctron** [comment]
Yes we can! :smile:
