### ISSUE TITLE
[Wires] Component avoidance during initial placement

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1193]
What happens consistently is that components are placed on top of one another when initially added to the graph. In this case logger was stacked on top of a timer.

![image](https://cloud.githubusercontent.com/assets/22816717/23900658/6c044c38-08ba-11e7-8897-28e5d4fa7dba.png)

In some cases, but unfortunately almost impossible to reproduce, the components are reordered in this way when graph is saved.

Kura 3.0.0-SNAPSHOT build 945 (most likely)
FF, Chrome

**Comment by MMaiero** [comment]
Should be solved by PR #1750
