### ISSUE TITLE
[Net] PPP password is not a (MetaType) Password

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1196]
Found in Kura 2.0.2. Not verified in Kura 2.1.0.

Typically passwords have ``Password`` type and they are base64 encoded in the dowloaded snapshot.
For example (password is "admin"):

```
<esf:configuration pid="org.eclipse.kura.web.Console">
    <esf:properties>
        <esf:property type="Password" name="console.password.value" encrypted="true" array="false">
            <esf:value>YWRtaW4=</esf:value>
        </esf:property>
    </esf:properties>
</esf:configuration>
```

The PPP password is different. It's a ``String`` (not a Password) and not base64 encoded.

```
<esf:property type="String" name="net.interface.ppp0.config.password" encrypted="false" array="false">
    <esf:value>password</esf:value>
</esf:property>
```

Not a big deal since the password is likely stored in clean in the ppp pap/chap scripts...

**Comment by MMaiero** [comment]
Closing as #1367 is now merged.
