### ISSUE TITLE
Wifi password incorrectly read from snapshot in Access Point mode

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#1201]
"Upload and Apply" a snapshot cause the Wifi password in Access Point mode to be incorrectly read and thus makes the Wifi access point unusable.

To reproduce the situation:

- verify that you can connect to Wifi using testKEYS password
- download the latest snapshot then Upload and Apply it
- try to reconnect Wifi with testKEYS password -> does not work, the password has been modified and you have to restore it manually using another connection to the web interface of the gateway ….

The snapshot contains the right password, but after its upload, the hostapd config file contains the password encrypted.

This issue is very prejudicial for customers using the wifi to configure their systems.

**Comment by cdealti** [comment]
@ibinshtok can you asses the effort needed to fix this?
