### ISSUE TITLE
build for windows x64 taget platform failed with some jar packages not available

### ISSUE THREAD

**Issue by alex1818** [eclipse/kura#1204]
I am trying to build  the latest develop branch of kura for  windows platform, but with a failure like below:
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.armv5sf:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.armv5sf/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.armv6hf:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.armv6hf/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.x86:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.x86/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.x86_64:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.x86_64/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.x86_64.yocto:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.x86_64.yocto/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.usb.x86.ubuntu:1.0.9-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.linux.usb.x86.ubuntu/1.0.9-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.bluetooth:1.0.7:jar
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.linux.watchdog:1.0.6:jar
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.core.status:1.0.3-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.core.status/1.0.3-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.net.admin:1.0.13-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.net.admin/1.0.13-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.protocol.modbus:2.0.1-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.protocol.modbus/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.example.camel.aggregation:1.1.1-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.example.camel.aggregation/1.1.1-SNAPSHOT/maven-metadata.xml
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.example.camel.quickstart:1.1.0:jar
[INFO] Configured Artifact: org.eclipse.kura:org.eclipse.kura.windows.command:1.0.0-SNAPSHOT:jar
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.windows.command/1.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://raw.github.com/eurotech/kura_addons/mvn-repo/org/eclipse/kura/org.eclipse.kura.windows.command/1.0.0-SNAPSHOT/org.eclipse.kura.windows.command-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] kura-pom-first ..................................... SUCCESS [  0.845 s]
[INFO] tools .............................................. SUCCESS [  0.027 s]
[INFO] Eclipse Kura Archetypes ............................ SUCCESS [  0.163 s]
[INFO] Eclipse Kura App Quickstart Archetype .............. SUCCESS [02:28 min]
[INFO] distrib ............................................ FAILURE [01:13 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:56 min
[INFO] Finished at: 2017-03-15T23:18:12+08:00
[INFO] Final Memory: 37M/350M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (get-kura-bundles) on project distrib: Unable to find artifact. Could not find artifact org.eclipse.kura:org.eclipse.kura.windows.command:jar:1.0.0-SNAPSHOT in kura_addons (https://raw.github.com/eurotech/kura_addons/mvn-repo/)
[ERROR]
[ERROR] Try downloading the file manually from the project website.
[ERROR]
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.eclipse.kura -DartifactId=org.eclipse.kura.windows.command -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file
[ERROR]
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.eclipse.kura -DartifactId=org.eclipse.kura.windows.command -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]
[ERROR] org.eclipse.kura:org.eclipse.kura.windows.command:jar:1.0.0-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR] kura_releases (https://repo.eclipse.org/content/repositories/kura/, releases=true, snapshots=false),
[ERROR] kura_addons (https://raw.github.com/eurotech/kura_addons/mvn-repo/, releases=true, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :distrib

I tried to download the jar packages manually, but none can be downloaded. It seems like they are moved or deleted? Can some help to build kura for Windows?

**Comment by MMaiero** [comment]
Hi Alex,
currently the windows version of Kura is not supported. That is the reason why you were not able to download the artifacts.

**Comment by dwoodard1** [comment]
@alex1818 To follow up a bit on Matteo's comments, we have had issues getting legal approval for some components needed to build Kura for Windows. As such, it has limited our development work on the Windows platform.

However, we do have installers available for Kura v2.0.0 with some getting started instructions [1].

[1] https://github.com/eurotech/kura_eth/wiki/KURA-for-Windows-Based-Systems

**Comment by ctron** [comment]
If it is just about running Kura in Windows you can also do this with docker: https://hub.docker.com/r/ctron/kura-emulator/

**Comment by alex1818** [comment]
@dwoodard1  thanks for your reply. The link is broken, can you send me a workable link? 
Another question: 
Does kura support working on standard PC like intel X86_64 using the Ubuntu system? Is there any building instructions available.  I find the build_menu bash script which says KURA can be build for debian and fedora target platform?

**Comment by alex1818** [comment]
@ctron 
Thanks for your suggestion. It is cool to try KURA through in docker way. I will give it  a try. But we still need to deploy Kura in a bare windows environment.

**Comment by alex1818** [comment]
@MMaiero 
 I have  seen some windows scripts, code and folder for windows in the target platform.
So I need to confirm that is it possible for me to build kura for windows on linux now? Is there any plan for Kura to support windows or OS independent?

**Comment by MMaiero** [comment]
As @dwoodard1 said the support for kura on Windows is available apart the code and tools that had legal issues.
So, as of now, the support is not complete and, even if able to compile fully, you would not be able to get a resulting installer to use on your Windows system.
We have plans to support Kura on Windows, but we are working with the Eclipse Legal team in order to solve the mentioned issues. The support will be completed only at that point.

**Comment by dwoodard1** [comment]
@alex1818 Apologies, that Wiki is on our private repository.

@cdealti Is there any reason we can't make the Wiki public in Kura?

**Comment by cdealti** [comment]
I don't believe we should make this binaries available until we cannot build the Kura port for Windows on Hudson and this does not seem possible for various legal issues. I would also add that we are considering removing the Windows-specific code from Kura and making it available in Everyware Software Framework (commercial license)
