### ISSUE TITLE
[Driver] Contribute Siemens S7 Driver

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1207]
The CQ (12777) to redistributed Moka 7 in source and binary form has been approved.

* Add Moka 7 source code to target-platform
* Submit Kura S7 Driver

**Comment by cdealti** [comment]
@dwoodard1 can you please take a look to the legal aspects of repackaging Moka7 in the Kura target-platform?

**Comment by dwoodard1** [comment]
@cdealti I believe we answered all the questions for this, correct? Can we close?

**Comment by cdealti** [comment]
yes, this issue has been completed
