### ISSUE TITLE
Show the description of a configurable service

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1223]
Currently only the "name" attribute of a configurable service is shown. However there is also, like for the attributes, a field "description" which could provide more information about a component.

As this seems to be a rather simple UI change I would hope that this still could to into Kura 3.0.0.

**Comment by MMaiero** [comment]
@nicolatimeus Will manage this

**Comment by cdealti** [comment]
Why is this in the Backlog pipeline?

**Comment by MMaiero** [comment]
Closing as #1525 is merged
