### ISSUE TITLE
[Camel] Create Kura DataService component

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#123]
I would be nice to have a dedicated wrapper around `DataService`.

**Comment by MMaiero** [comment]
@ctron Is this solved?

**Comment by ctron** [comment]
No, but I am also not sure if this should be. From what I know the `CloudService` is the proposed interface to use. I will chat with Henryk about that.

**Comment by dwoodard1** [comment]
@ctron Can this be closed?
