### ISSUE TITLE
Support Azure IoT and Aws IoT cloud platforms

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1242]
Initial support in order to enable Kura to publish telemetry messages to the Azure IoT and Aws IoT cloud platforms.
The CloudService will add Json serialization support. At the level of cloud Client, the applications will continue to use Kura Payload (flat set of key-value pairs). Underneath, depending on the configuration, the Cloud Service will publish to the specified cloud platform via Protobuf or Json.

**Comment by cdealti** [comment]
All issues complete.
