### ISSUE TITLE
[Wires] MQTT namespace

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1246]
CloudPublisher is a WireComponent converting an WireEnvelope in a KuraPayload that is published over MQTT.

Each WireRecord in a WireEnvelope is trivially converted to a KuraPayload and published on a configurable semantic data or control topic. The emitter PID of the WireEnvelope is discarded.

The CloudPublisher is agnostic with respect to the contents of the WireEnvelope. It does not know for example if a WireEnvelope contains data readings emitted from a WireAsset.

On the other hand WireAssetS are first-class citizens of a Wire graph and the source of the information which is processed by the downstream Wire components.

Eventually the WireEnvelope representing the output of the processing is connected to a CloudPublisher and published to a Cloud platform.

In the simples case a WireAsset is directly connected to a CloudPublisher and it would be useful to publish the telemetry data under a well-known topic namespace, for example (full topic):

``<accountName>/<deviceID>/W1/A1/<assetName>``

In this case ${assetName} is matches the emitterPID of the WireEnvelope emmited by the WireAsset and received by a CloudPublisher.

Interested applications can then subscribe to (or query a message datastore for):
* ``<accountName>/<deviceID>/W1/#`` all Wires (W) topics
* ``<accountName>/<deviceID>/W1/A1/#`` all WireAsset (W/A) topics
* ``<accountName>/<deviceID>/W1/A1/<assetName>`` all topics for a specific WireAsset

In a more complex scenario there might be filters between the WireAsset "source" and the CloudPublisher "sink" and the emitterPID of the WireEnvelope received by the publisher no longer matches the emitterPID of the WireEnvelope emmited by the WireAsset.
However the published data still represents "Asset" (filtered) data and should be published under the topic above.

Unfortunately the Wires model does not have a notion of source of an WireEnvelope since a given WireEnvelope instance does not move across the graph but only from one WireEmitter to downstream WireReceiverS that are free to emit something semantically different.

A possible convention could be:
* Modify the CloudPublisher to allow entering a "semantic topic template" like ``W1/A1/$assetName`` where tokens prefixed with '$' will be expanded to the value of a property with the same name in a WireEnvelope's WireRecord.
* Modify the WireAsset to add an ``assetName`` property to the WireEnvelope's WireRecord.

[1] https://eclipse.github.io/kura/ref/mqtt-namespace.html

**Comment by cdealti** [comment]
@amitjoy @ctron does this make sense to you? it's meant to promote WireAssetS to fist-class citizens in Kapua.

**Comment by mcarrer** [comment]
The proposal makes sense to me. As commented by Cristiano, it is a necessary enhancement to allow Kapua to be able to subscribe and query for the data published by a specific Asset.

**Comment by amitjoy** [comment]
I agree with @cdealti that Wires should be relegated to first class citizens. It will be flexible enough to provide such customizable properties so that Kapua can subscribe to specific properties of specific assets.

**Comment by cdealti** [comment]
Edited the original comment to version the namespace:
``W`` -> ``W1``
``A``  -> ``A1``

**Comment by MMaiero** [comment]
We need to improve the documentation with this new topic design.
