### ISSUE TITLE
Kura Camel To/From Different Cloud Service Topics

### ISSUE THREAD

**Issue by fvanloon-bolt** [eclipse/kura#1249]
When creating a Kura Camel XML Router, I would like to create a "route" that listens on 1 Kura Cloud Service and publishes to a 2nd Cloud Service (local Mosquitto to AWS MQTT for example).

I was able to create this basic route, but I've found that the Topic Id on the 2nd Cloud Service is being ignored, and instead it it publishing to the listening Topic Id instead.

I have 2 Cloud Services setup.. 
#1) "CloudService" (to AWS) ... Account-Name=bolt-aws, Client-Id=fog1
#2) "CloudService-local" (to local Mosquitto) ... Account-Name=bolt-local, Client-Id=local1

I created a Kura Component to write to the "CloudService-local" every 15s ... it connects with an "APP ID" of "bolt-thing" and publishes to Topic "SN00000192937".
So.. in the logs I see it writing to the full Topic of "bolt-local/local1/bolt-thing/SN00000192937".

> 11:42:51,787 [] INFO  BoltThing:231  - Bolt-Thing.. Published to SN00000192937 message: org.eclipse.kura.message.KuraPayload@4ca1ac9e with ID: 1083
> 11:42:51,788 [DataServiceImpl:Submit] INFO  MqttDataTransport:512  - Publishing message on topic: bolt-local/local1/bolt-thing/SN00000192937 with QoS: 0

Then, I setup a Kura Camel route (using the Camel XML Router):
```
<routes xmlns="http://camel.apache.org/schema/spring">
	<route id="routeAllToAWS">
		<from uri="local-cloud:bolt-thing/SN00000192937" />
		<to uri="aws-cloud:bolt-gateway/all" /> 
	</route>
</routes>
```

NOTE: I also had to add "Cloud Service Mappings" to the Camel XML Router:
`aws-cloud=org.eclipse.kura.cloud.CloudService,local-cloud=org.eclipse.kura.cloud.CloudService-local`

The connections work fine.  The route is forwarding the message.. but it is not sending it to "bolt-gateway/all" like I expected.. it is instead sending it to: "bolt-gateway/SN00000192937".  It seems to be ignoring the "topicId" portion of the "to uri".

> 11:42:51,789 [MQTT Call: local1] INFO  CloudServiceImpl:440  - Message arrived on topic: bolt-local/local1/bolt-thing/SN00000192937
> 11:42:51,790 [MQTT Call: local1] INFO  DataServiceImpl:441  - Storing message on topic :#account-name/#client-id/bolt-gateway/SN00000192937, priority: 5
> 11:42:51,791 [MQTT Call: local1] INFO  DataServiceImpl:444  - Stored message on topic :#account-name/#client-id/bolt-gateway/SN00000192937, priority: 5
> 11:42:51,793 [DataServiceImpl:Submit] INFO  MqttDataTransport:512  - Publishing message on topic: bolt-aws/fog1/bolt-gateway/SN00000192937 with QoS: 0

This is a really simple example just to illustrate the problem.  In reality, I'd like to listen to the local topic, then based on conditional logic publish to AWS on multiple different topics (using <choice>, <when> tags).

**Comment by ctron** [comment]
I dug a bit into this issue and from what it looks to me, this is an odd but "correct" behavior.

When a message is sent to an endpoint, the topic can be overridden by specifying the header value `CamelKuraCloudService.topic`. However the consumer endpoint, consuming from the cloud service also sets this header value to the topic name this message is coming from.

So if you are now re-directing messages from "left to right", then the topic value in the header is always present and takes precedence over the URI topic value.

You could try unsetting the header value for `CamelKuraCloudService.topic` and re-test your scenario if this solves the issue for you?

**Comment by fvanloon-bolt** [comment]
That did fix the issue, thank you.
I added this between the from and to tags and it works now.
`<removeHeaders pattern="CamelKuraCloudService.topic"/>
`

**Comment by ctron** [comment]
Thanks for the quick response! I will add this to the documentation.
