### ISSUE TITLE
Drag and drop of Marketplace listing should send back a successful install count

### ISSUE THREAD

**Issue by IanSkerrett** [eclipse/kura#1250]
If someone installs a package into Kura using the drag and drop from Eclipse IoT Market, Kura should send a successful install count back to Eclipse Marketplace.  This can be done through the Marketplace REST API. If Kura does this, it will allow Eclipse Marketplace to keep track of the number of times each package has been installed.

**Comment by nicolatimeus** [comment]
@IanSkerrett I've tried to find some documentation describing the Marketplace REST APIs regarding sending back the successful install count, but I wasn't able to find anything on this topic.
Can you please provide some more information about this?

**Comment by IanSkerrett** [comment]
Chris can you please help with this request.

**Comment by dwoodard1** [comment]
@IanSkerrett I'm not sure Chris will get your message. Do you know his Github ID?

**Comment by cdealti** [comment]
@dwoodard1 I believe @nicolatimeus succeeded updating the counters via REST by looking at the Oomph implementation. However I believe it would be good if this info would be publicly available.

**Comment by IanSkerrett** [comment]
Sorry I don't know his github id.

**Comment by kartben** [comment]
adding @chrisguindon to the thread :-)

**Comment by nicolatimeus** [comment]
I was able to find some code that reports a successful installation feedback in [this](https://github.com/eclipse/epp.mpc/blob/792fe72194e147eb9abb8c2e047bcc9b3a1c9753/org.eclipse.epp.mpc.core/src/org/eclipse/epp/internal/mpc/core/service/DefaultMarketplaceService.java#L810) part of the Eclipse Marketplace Client source code.
Can I use the same REST call also for Kura? If yes do I need to supply any additional parameter?

**Comment by chrisguindon** [comment]
I am concerned about how we flag a successful install on marketplace. With this said, I created Bug 517546 - Protect successful install endpoint on marketplace to discuss this (https://bugs.eclipse.org/bugs/show_bug.cgi?id=517546). 

This bug is currently flagged as a security bug. @kartben, can you add @cdealti and @nicolatimeus to the cc list of this bug to allow them to read it?

**Comment by cdealti** [comment]
@nicolatimeus do you have a PR ready for this?

**Comment by cdealti** [comment]
@chrisguindon we have #1446 ready to be merged. Should we wait until you make a decision on the above bug?

**Comment by chrisguindon** [comment]
@cdealti I think you can move ahead with your patch. After a bit of discussion on the bug, I do not expect any changes that would break this api since this would have a negative impact on previous version on the Eclipse IDE.

@IanSkerrett what do you think?
