### ISSUE TITLE
Add an OSGi command for maniupulating GPIO

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#1252]
It would be interesting to have a simple CLI interface to manipulate GPIOs from the OSGi console.

Something like `kura.gpio(1).setValue(true)` or `kura.gpio(1, OUTPUT).setValue(true)` 

I am not sure about what could be the most straightforward syntax (both from the pov of people who will have to type the command, and from the pov of making parsing simple / unambiguous).
Maybe implementing this as a Karaf command would be easier/more flexible?

**Comment by cdealti** [comment]
PR is welcome ;-)
