### ISSUE TITLE
Apply new Driver API changes to Asset Provider Test

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#1253]
The new Driver API changes for prepared read need to be applied to [StubDriver](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.asset.provider.test/src/main/java/org/eclipse/kura/asset/provider/test/StubDriver.java) in Asset Provider Test fragment.

**Comment by cdealti** [comment]
@markoer any idea about this?

**Comment by markoer** [comment]
Well, I have to agree with @amitjoy that when implementation is updated, tests should be, too. We currently don't have problems with this (test) module, because it's commented out.

**Comment by markoer** [comment]
Duplicated in #1608 and implemented in #1609.
