### ISSUE TITLE
Switch away from log4j 1.x

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1255]
Log4J is EOL for over a year now [1]. I guess it is time to switch.

I would recommend to switch to logback as is provides all the necessary extensions Kura currently pulls in with the "extra" log4j package and also directly integrates with SLF4J.

[1] https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces

**Comment by markoer** [comment]
Should be solved with #2059.
