### ISSUE TITLE
Cannot find plugins if target-definition/ is not a direct subdirectory of the workspace

### ISSUE THREAD

**Issue by unixero** [eclipse/kura#1263]
Noticed this during an upgrade from kura 1.4.0 to 2.1.0. Downloaded the developer's workspace from kura's downloads page (https://www.eclipse.org/kura/downloads.php). Git clone'd my repository, a subdirectory containing all my eclipse projects was created, then I cd'ed into it and unpacked the developer's workspace there.

Result: maven compiles cleanly, but the Eclipse IDE does not. Errors make no sense, like "The import org.eclipse.kura cannot be resolved".

In the end I found this to be caused by target-definition/ not being a *direct* subdirectory of the Eclipse workspace. The kura-equinox_3.8.1.target file contains references like:

${workspace_loc}/target-definition/equinox_3.8.1/repository/plugins

But ${workspace_loc}/target-definition/ does not exist. The issue can be fixed by editing this file and replacing this with ${project_loc} (will have to click again on "set as target platform" after this change).

Kura forum link: https://www.eclipse.org/forums/index.php/t/1085096/

**Comment by cdealti** [comment]
The proper way of importing the user workspace is via ``File | Import | General | Existing Projects into Workspace`` and then ``Select archive file``.
