### ISSUE TITLE
[WebUI] Usability Improvements

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kura#1268]
## Overall
- [x]  When making a selection in the navigation bar, can we avoid the little shift of the icons?
- [x]  Use the same font, weight and size for System and Services in the Navigation bar as the Title of each page
- [x]  For the title of each page, move the text a bit to the left (padding 3px); same for the instruction text underneath
- [x]  Rearrange the footer to be in a single line
- [x]  Move Refresh Button to last in the toolbar
- [x]  In the navigation bar, can we align the all the texts by giving the same width to all icons through extra padding if necessary? So move to a table-like layout?

## Device

- [x]  Command * Change the order of the buttons * Execute | Reset
- [x]  Profile | Threads | System Properties * keep consistent the style of the table
- [x]  Bundles * Move Refresh button last

## Network
- [x]  Align the left margin with the other panels. Now it is more to the right than the others
- [x]  Align the Interface Name panel top with the interface management box
- [x] Align the Help Text with the first widget on the left
- [x] The text in the "Help Text" box can be increased to 12px
- [x] Change "Help Text" to "Information" and make it size 14px like all the headers within a configuration box
- [x]  The size of the Labels in the TCP/IP tab * Status, Configure, ... * should be the same as the one in the Hardware Tab
- [x]  TCP/IP and Hardware tab font size should be 14px like in the Device and Firewall * let's keep the Tab name size consistent

## Firewall
- [x] There is an extra space above the toolbar * keep spacing consistent with the Device > Bundles UI
* I do not like the Apply button. If we batch the changes, we may need to have a Cancel as well. Or we can make we change effective after it is made.

## Cloud Services
- [x]  Add some instruction text at the top of the page
- [x]  Move Refresh Button to last
* In my build, I am not able to build a second CloudService instance
- [x]  In the new Cloud Service dialog, remove the icons from the buttons and just have them as Submit and Cancel
* Maybe add a Title over the Tabs for the currently selected CloudService?
* CloudService
    - [x]  device.display.name * Change tip to remove reference to Eurotech Everware Cloud. Say "Server defined relies on the remote management server to define a name."
    - [x]  topic.control-prefix * Topic prefix for system and device management messages
    - [x]  enable.default.subscriptions * Disables the default subscriptions to the gateway management MQTT topics. When disabled, the gateway will not be remotely manageable
* MQTTDataTransport
    - [x]  topic.context.account-name * For connections to remote management servers, this is generally the name of the server side account.
- [x]  We need to be consistent with the representations of the Tabs
    * Sometimes with have a standalone bar with the content underneath like in the Device, Network, Firewall
    * Sometimes the bar is just followed by the content like in the Cloud Service and in the Install/Upgrade dialog

## Packages
- [x]  Add some instruction text at the top of the page
- [x]  Move the instructions on the Eclipse Marketplace to the instructions at the top of the page
- [x]  Make Eclipse Marketplace a link to the IoT section
- [x]  Move buttons inside the box which contains the table of the packages * like in the Firewall and Settings UI
- [x] Move the Refresh button last
* Install/Upgrade dialog:
    - [x]  Change the title to Install/Upgrade Package
    - [x]  Change the order to of the Submit and Cancel button for consistency
    - [x]  Do not use bold of the instruction text
    - [x]  Review usage of Tabs?

## Settings
- [x] Move Refresh button last
* Keep the internal padding within the grey box consistent; Snapshot has narrower padding than the others. Use the wider padding, keeping it consistent with the Firewall UI

## Wires
* Align all components on the left
* New Component dialog * Remove the icons from the buttons and just have them as Submit and Cancel in that order
- [x]  Move **Zoom In/Out** in the wires canvas as **+/-** buttons in Google Maps. Zoom in/out with respect to the center
- [x]  Support for dragging the canvas as in Google Maps
- [x]  Fit to width
- [x]  Default placement of a new component
* Move **Wire Components** selection to a **New (with drop down)** button. This frees up space for the canvas

## Services
* In the New Component dialog:
    - [x]  Tooltip should be "Create a new Component" not component factory I think
    - [x]  Title of the dialog should be "New Component"
    - [x]  Factory: dropdown value should be "--* Select Component Factory ----"
    - [x]  Buttons should be Submit and Cancel with the same spacing as other dialogs

## Others
- [x]  We may also consider a separate section for Drivers and Assets.
  They can indeed be used outside of the Graphs but the UI does not allow for it now.

**Comment by MMaiero** [comment]
Regarding the Firewall apply button we decided to place a Reset one to allow the possibility to refer changes without commit them

**Comment by MMaiero** [comment]
> In my build, I am not able to build a second CloudService instance

There is a hint, but effectively it disappears when the user starts writing content in the text box.
I'll open another issue just to track this.

**Comment by MMaiero** [comment]
> Maybe add a Title over the Tabs for the currently selected CloudService?

We tried to design something but it was not successful. Indeed, the currently selected cloud service is shown in the table. So, maybe, there is no need to replicate this information.

**Comment by MMaiero** [comment]
> Move Wire Components selection to a New (with drop down) button. This frees up space for the canvas

Maybe we can keep this as a proposal

**Comment by MMaiero** [comment]
> New Component dialog * Remove the icons from the buttons and just have them as Submit and Cancel in that order

In a new issue
