### ISSUE TITLE
[Wires] Column names in DB Store

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1269]
Currently, the Kura Wires DB store uses channel names as the column name for the database. This can create column names such as "Channel 1_timestamp". I am not a DB expert, but I believe this is generally considered bad practice. This can also make complex queries in the DB filter quite messy.

I would recommend using some marshalling/unmarshalling scheme to remove the spaces. Meaning "Channel 1_timestamp" becomes "Channel_1_timestamp. This would mean not allowing "_" in the channel names, but I think that is a worthwhile trade off.

**Comment by MMaiero** [comment]
Solved by #1323
