### ISSUE TITLE
Client ID is limited to 23 characters (MQTT 3.1 constraint that was relaxed in 3.1.1) preventing connection to some 3.1.1 servers

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#128]
https://github.com/eclipse/kura/blob/7d17a281acf0d8b8406a97992a23f9466e29d562/kura/org.eclipse.kura.core/OSGI-INF/metatype/org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.xml#L61 constraint should be removed, so as people can use client IDs longer than 23characters if they're using MQTT 3.1.1

**Comment by pierrepitiot** [comment]
I removed the limit on client-id size in MqttDataTransport metatype definition.

Be aware that for the moment, a limit still exists in Eurotech MQTT broker filter, the client id size must not exceed 64 characters. This limit is specific to Eurotech and should be fixed in a next release.
