### ISSUE TITLE
Why metrics in KuraPayload is a Map<String,Object> instead of Map<String,KuraMetric> ?

### ISSUE THREAD

**Issue by ghost** [eclipse/kura#1280]
Hello,

Everything is on title. Is it mandatory to have this Map abstract ? Because we have problem with a customer who build a OSGI bunddle and pass a String instead of metric structure. Protobuf deserializing had failed and we spent lot of time to understand where it comes. The API is confusing.

Thanks,

**Comment by dwoodard1** [comment]
@FabGre Maybe you can explain the problem a little more. What do you mean they passed a String instead of a metric structure? How would using Map<String, KuraMetric> instead of Map<String, Object> solve this problem?

**Comment by ghost** [comment]
Hi @dwoodard1 , we are working on this problem for now and it was not solved. It seems that we have a missunderstanding between us and Eurotech guys whose try to help us with our Protobuf deserializing problem. In a first time they confirmed our hypothesis about KuraMetric but they miss understood our question and finally explained us that it's possible to pass a simple object to Kurapayload metric Map and the framework do the job to transform it as a metric structure in the MQTT payload.

But I always think that the API is confiusing because the javadoc tell that the Object should be a metric structure and finnaly you have to pass value object.

**Comment by ctron** [comment]
Well I tend to agree with @FabGre that there is room for improvement.

If you look at the KuraPayload class, then the metrics are stored in a `Map<String,Object>`. However if you for example would put in a `KuraMetric` class or a `Short` value, then, while encoding, the method `setProtoKuraMetricValue` would simply throw an exception. IMHO the API Kura provides should only allow metric to be added to the payload structure which are also supported by Kura.
