### ISSUE TITLE
I saw docker ctron/kura

### ISSUE THREAD

**Issue by maul5** [eclipse/kura#1284]
Hello.

I have a question.

I saw ctron/kura in Docker Hub.

Does this run in Raspbian (Model 2 or 3)?

**Comment by ctron** [comment]
No the `ctron/kura` images only run on x86_64 targets.

Maybe it would be interesting though to create a docker image for "arm" as well.

**Comment by maul5** [comment]
1) Is that possible? and Is there no problem?

2) How can I make it?

**Comment by MMaiero** [comment]
I think you can have a look at this: https://hub.docker.com/r/mmaiero88/kura-armv7hf/
It's an initial porting. But maybe it can be a starting point.

There is also a more optimized version: https://hub.docker.com/r/mmaiero88/kura-armv7hf-opt/

**Comment by maul5** [comment]
Can I make kura docker image?

How can I make it?

**Comment by MMaiero** [comment]
There are some tutorials online.The real issue here is that you need to create an image with a raspberry pi. The cross compiling is an option, but I've never tried it.

**Comment by maul5** [comment]
I saw this page(http://eclipse.github.io/kura/doc/raspberry-pi-quick-start.html) and made docker image in Raspberry Pi 3 (Raspbian).

But I could not find start command in docker image.

How can I kura start?
