### ISSUE TITLE
[Wires] Wires DataType lacks the KuraPayload float type

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1295]
Wires DataType only supports double precision floating point numbers (why?).
The single precision floating point type of a KuraPayload cannot be removed for backward compatibility reasons.

* Add the float type to DataType or
* Document that metrics of type float received by a WirePublisher will be converted to a float DataType when converting the KuraPayload to a WireRecord

**Comment by MMaiero** [comment]
The official HSQLDB documentation states (http://hsqldb.org/doc/1.8/guide/ch09.html):

> The recommended Java mapping for the JDBC datatype FLOAT is as a Java type "double". Because of the potential confusion it is recommended that DOUBLE is used instead of FLOAT.

**Comment by amitjoy** [comment]
Single precision floating point doesn't provide large degree of precision and to retain accuracy in performing precise calculations, wires didn't include `floats`.

The idea was to include primitive types (except `floats`) to be used as the datatypes in wires. And keeping this in mind, the existent datatypes were included. Previously while designing, I was not aware of the backward compatibility issues of `floats` in `KuraPayload`. You are right, it should be introduced.
