### ISSUE TITLE
Is Running Kura 2.1.0 possible in Docker of Raspbian(used Raspberry Pi 3)?

### ISSUE THREAD

**Issue by maul5** [eclipse/kura#1297]
I try to make Kura Docker image **in Raspberry Pi 3**.

Is Running Kura 2.1.0 possible in Docker of Raspbian? (**used Raspberry Pi 3**)

**My Dockerfile**

```
FROM resin/rpi-raspbian:jessie-20170331

RUN apt-get update && apt-get install oracle-java8-jdk
RUN apt-get install wget && apt-get install vim && apt-get install gdebi

RUN wget http://download.eclipse.org/kura/releases/2.1.0/kura_2.1.0_raspberry-pi-2-3_installer.deb
RUN gdebi kura_2.1.0_raspberry-pi-2-3_installer.deb

EXPOSE 80
```

**Running error message**

![kura_error](https://cloud.githubusercontent.com/assets/7858036/24697604/c26c8f98-1a28-11e7-8160-b55ade0d5a7a.png)

**Comment by MMaiero** [comment]
Yes, it is possible. In the link provided in a previous issue, you have also the docker image with Kura 2.1.0.
I would also suggest to refer to the forum or mailing list for this kind of issues. Thanks

**Comment by MMaiero** [comment]
@maul5 Can this be closed? Thanks.
