### ISSUE TITLE
Fix source directory build configuration in test fragments

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#1310]
The build configuration of the unit test fragments show that the source directory is set to `src/main/java`. This needs to be changed to `src/test/java`.

**Comment by cdealti** [comment]
@amitjoy I believe this is discussed in [1].
@markoer can explain this in greater detail.

[1] https://github.com/eclipse/kura/wiki/Development-Environment-Tips-and-Tricks#in-ide

**Comment by amitjoy** [comment]
I have created this issue as most of the unit tests as of now comprise `src/main/java` as source directory in `build.properties` whereas it should be `src/test/java`

**Comment by markoer** [comment]
In short, if `src/test/java` is added to source.., its classes will be compiled into `target/classes` instead of `target/test-classes` and therefore be picked up by tycho-surefire-plugin instead of surefire-plugin. And this would be wrong.

**Comment by MMaiero** [comment]
Can we close this?

**Comment by MMaiero** [comment]
Closing for now. Please reopen it if needed.
