### ISSUE TITLE
Provide CentOS 7 based image

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1320]
We would like to have a CentOS 7 based image of Kura.

**Comment by cdealti** [comment]
@ctron are you willing to provide and maintain this Kura port (with and without network support)?

**Comment by cdealti** [comment]
@ctron I don't see any interest in doing this. Can we close?

**Comment by ctron** [comment]
If you don't see interest, then please go ahead and close it.

**Comment by cdealti** [comment]
OK, thanks. We can always reopen it
