### ISSUE TITLE
[Kura App Store] Modbus driver deployment package version

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1326]
The currently available Eclipse Marketplace Modbus driver (https://marketplace.eclipse.org/content/modbus-driver-eclipse-kura) claims to be version 1.0.0, but when installed Kura reports version 0.1.0. The reason is that DP's manifest reports 0.1.0 instead of 1.0.0.

**Comment by cdealti** [comment]
That driver has not been officially released by Kura and will not work with Kura 3.0.0.
The Everyware Software Framework (ESF) Modbus Driver - Community Edition for Kura 3 will be published soon on the Marketplace.

@amitjoy I believe it should be removed.

**Comment by cdealti** [comment]
The ESF Modbus Driver - Community Edition has been published to the Eclipse Marketplace. @amitjoy can you remove yours?

**Comment by amitjoy** [comment]
Will do. 👍
