### ISSUE TITLE
[Kura App Store] Modbus and OPC-UA driver deployment packages

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1327]
The drivers currently available on Eclipse Marketplace (https://marketplace.eclipse.org/taxonomy/term/4397%2C4396/title) are only compatible with Kura 3.0.0-M1. Versions for 3.0.0 are not available, yet.

**Comment by cdealti** [comment]
The official OPC-UA driver for Kura 3 has been published on the Eclipse Marketplace [1].
The Everyware Software Framework (ESF) Modbus Driver - Community Edition for Kura 3 will be available soon.

[1] https://marketplace.eclipse.org/content/opc-ua-driver-kura
