### ISSUE TITLE
Raspberry pi zero w

### ISSUE THREAD

**Issue by ardmn** [eclipse/kura#1328]
Hello. Can you help me please . I want install kura on Raspberry pi zero w.  I try install [url=http://www.eclipse.org/downloads/download.php?file=/kura/releases/2.1.0/kura_2.1.0_raspberry-pi_installer.deb]Raspbian - Stable[/url] from download page but rpi  freezes when it try setting up kura. I don't understent what from this list i need:
-Raspbian (Model 2 or 3) - Stable,
-Raspbian (Model 2 or 3, No Net)- Stable,
-Raspbian - Stable,
-Raspbian (No Net)- Stable,
-Raspbian (Model B+)- Stable,
-Raspbian (Model B+, No Net)- Stable , Raspbian (Model A+)- Stable

I dont understend difference between "Raspbian - Stable" and "Raspbian (Model 2 or 3) - Stable".

I found topic [url=https://www.eclipse.org/forums/index.php/m/1758006/?srch=zero#msg_1758006]Will Kura support Raspberry Pi zero W? [/url] but it so old.

**Comment by MMaiero** [comment]
Hi,
raspberry pi zero is currently not a supported platform but, as stated here: https://www.eclipse.org/forums/index.php?t=msg&th=1085140&goto=1758188&#msg_1758188
downloading the installer for raspberry pi 2/3 and changing few properties it should be possible to have it working.

> I dont understend difference between "Raspbian - Stable" and "Raspbian (Model 2 or 3) - Stable".

I think this is an error, the `Raspbian - Stable` should refer to raspberry pi model b. @dwoodard1 Maybe we need to correct that.

**Comment by ardmn** [comment]
@MMaiero  Thank you. I see that rpi B+ and rpi zero have simmilar hardware . And I install b+ version. https://www.eclipse.org/forums/index.php?t=msg&th=1085140&goto=1758188&#msg_1758188  - help me to have access to kura by wifi . But i can't  connect by ethernet and get ssh connection raspberian . though before installing kura i has normal ethernet ssh (by usb).  If I try get ssh connection by wifi(kura_gateway_) :  ssh kura_ip -p 22 that I can't enter password because  I don't know it.

**Comment by MMaiero** [comment]
@ardmn Did you solve your issue?

**Comment by cdealti** [comment]
The default WiFi password is _testKEYS_
