### ISSUE TITLE
[Kura 3.0.0 QA] Example publisher on Amazon

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1334]
The example publisher package posted on Amazon (https://s3.amazonaws.com/esf-resources/securityQA/org.eclipse.kura.example.publisher.dp) worked with Kura up to 3.0.0-M1, now it shows this issue. The bundle provided with the Hudson build works OK.

When installed, the log shows successful installation and it even publishes messages, but it doesn't show up among the services in the UI. It doesn't show in EC either. Probably due to the changed required interfaces for configurable components?

Tested as part of DEN-DEPLOY-001.

Kura 3.0.0 b22 on RPi2 and RPi3

**Comment by MMaiero** [comment]
The example publisher is now a factory and instances need to be created with the + button on the left

**Comment by markoer** [comment]
In this case (if the package on Amazon has already been updated), the issue is more severe: it's not possible to select the example publisher factory component in +'s dialog on the left when it's installed from the mentioned URL, but it still publishes messages.

When I uninstall package from URL and install bundle 1.0.100 from b22 an instance of ExamplePublisher is added immediately (and is visible under Services) and I can add new instances via +.

**Comment by MMaiero** [comment]
No, the packages in the QA report and the ones in the marketplace will be updated after the release.
Only the dps produced by the build should be used in this case, due to the breaking changes in the configuration service and driver implementations.

**Comment by cdealti** [comment]
The new example publisher has been published to the Eclipse Marketplace in the IoT category [1]

[1] https://marketplace.eclipse.org/content/example-publisher-eclipse-kura
