### ISSUE TITLE
[Kura 3.0.0 QA] User workspace plugins BREE

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1335]
UW-SETUP-002 requires no errors to be present after the imported projects build. There are however a few warnings: org.eclipse.kura.example.publisher is the only project with BREE=1.8, the rest have it set to 1.6 and/or 1.7. And even org.eclipse.kura.api now requires Java 1.8.

Kura 3.0.0 b22

Low priority

**Comment by MMaiero** [comment]
I think this can be closed due to #1351 merging. Is it ok for you @markoer?

**Comment by markoer** [comment]
Let's wait till I try it with the next build. I'm sure it will work, but still... I'll close it right after I test it.

**Comment by markoer** [comment]
Verified in Kura 3.0.0 b28 release candidate. Closing the issue.
