### ISSUE TITLE
[Kura 3.0.0] camel.aggregation and camel.quickstart examples should be "normalized"

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1338]
These two projects have caused and are causing a couple of problems:

1. After importing the classical user_workspace_archive_3.0.0.zip, they contain errors (see picture below)

![screenshot from 2017-04-20 15 44 11](https://cloud.githubusercontent.com/assets/1225835/25233869/9847942e-25e0-11e7-9f85-982e30e1ce42.png)

2. They require an extra manual step when deployed to Nexus which is not required for the other examples. Note that their deployment is skipped by default [1].

I can speculate these problems arise because these examples do not inherit from the kura/manifest_pom.xml and they are meant to be standalone projects.

However, the build is already complex enough and we don't need further exceptions.

@ctron can you please modify these projects to follow the same structure as the others?  

[1] https://github.com/eclipse/kura/blob/release-3.0.0/kura/examples/org.eclipse.kura.example.camel.aggregation/pom.xml

**Comment by cdealti** [comment]
@ctron any thoughts on this?

**Comment by ctron** [comment]
I think the were scheduled to be moved to some extra repository. What is the status on this one?

**Comment by cdealti** [comment]
the status is that they will not be moved until we have decided how to build them:

1. Manifest-first (Tycho/PDE)
2. POM-first (maven-bundle-plugin)

how to include them in the user workspace zip archive (if this still makes sense).
As all the examples are still in eclipse/kura I'd prefer if they all built the same.

**Comment by cdealti** [comment]
@cdealti please review
