### ISSUE TITLE
Create an EclipseKura account in slideshare

### ISSUE THREAD

**Issue by mcarrer** [eclipse/kura#136]
Create an EclipseKura account in slideshare and share slides from EclipseCON conferences and Kura tutorials

**Comment by cdealti** [comment]
Postponed to Kura 2.1.0

**Comment by dwoodard1** [comment]
@mcarrer @cdealti You must create a LinkedIn account in order to have a Slideshare account. Not sure this makes sense for a project. Thoughts?

**Comment by MMaiero** [comment]
@kartben Do you have some suggestions on this topic?

**Comment by dwoodard1** [comment]
Done: http://www.slideshare.net/eclipsekura.
