### ISSUE TITLE
[Documentation] Improve Kura wires documentation

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1361]
The Kura Wires documentation should be improved:
* Basic concepts on Kura Wires: WireComponents, WireEnvelops, WireFields and WireRecords
* Tutorial on FIFO component

**Comment by MMaiero** [comment]
@nicolatimeus Will create a tutorial about the FIFO component and the Javascript filter

**Comment by MMaiero** [comment]
I will take the update of the documentation for WireComponents, WireEnvelops, WireFields and WireRecords
