### ISSUE TITLE
[Documentation] Kura documentation improvements

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1362]
PR #1355 tries to re-organise the Kura documentation, dividing documents in sections. However, many documents and tutorials are missing.

**Comment by cdealti** [comment]
@pierantoniomerlino [ASSET-V1 MQTT Namespace](http://eclipse.github.io/kura/dev/asset-v1.html) should go under [Kura Remote Device Management](http://eclipse.github.io/kura/ref/mqtt-namespace.html) or at least in the same section (definitely not under the Development section)

**Comment by pierantoniomerlino** [comment]
@cdealti Why did I put it under the Development section? Boh! Probably it was a copy-and-paste typo. I'm going to move it under the Reference section.
