### ISSUE TITLE
WiFi password (PSK) can't contain '&' 

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1369]
WiFi password (PSK) can't contain '&' . Example the value of ``Math&Science`` in "Wireless Password" field of the "Wireless" configuration tab is converted into ``Math&amp;Science`` in "psk" option of the /etc/wpa_supplicant.conf file.

**Comment by cdealti** [comment]
@MMaiero does it happen to prevent JS injection?

**Comment by MMaiero** [comment]
@ibinshtok I've opened #1406 to try to solve this issue. Could you please give it a look?

**Comment by ibinshtok** [comment]
@MMaiero I'll look at this. Thank you!
