### ISSUE TITLE
[Kura 3.0.0 QA] Configuration service: mixing configurable services with factory components

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1373]
I will describe 2 scenarios that may occur when I want to use ExamplePublisher with Kura 3.0.0. Both show some issue.

Scenario 1:
New Kura installation.
Install example publisher bundle from OSGi console (install file:///.../ org.eclipse.kura.example.publisher-1.0.100.jar). Don't start the bundle, yet. Try to add a new service (+). It's not listed. Start the bundle (e.g. start 95). Try to add it again and now it's listed as a factory component. Don't add it, anyway. Stop and/or uninstall the bundle. Make sure it's not listed in OSGi anymore (`ss` doesn't list it). Try to add the service now – it's still listed as a factory component. It can be added and configured. Configuration service doesn't handle bundle (and factory component, in this case) unregistration.

Scenario 2:
New Kura installation.
Add the old publisher from Amazon and also uninstall it after it publishes a few messages.
Then add example publisher bundle from the jar, available with the build. It's the one that should be started after you create an instance using a factory. But a configuration for the component already exists in the latest snapshot. It will start publishing when you click '+' to add a new service. But you don't have to complete the form – clicking '+' is enough. The trouble is that this one is not configured properly – has no cloud service reference and no app.id.
If you add the new instance, you will now have 2.

Kura 3.0.0 b31 on RPi3

**Comment by cdealti** [comment]
Scenario 1 is due to the ConfigurationService implementation not tracking bundle uninstall.
Scenario 2 no idea yet

**Comment by cdealti** [comment]
Scenario 1 is fixed in 3.2.0.
No interest in fixing scenario 2.
