### ISSUE TITLE
BeagleBone Black, dnsmasq disrupts kura's DHCP service

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#1374]
Installation image 

[bone-debian-8.7-iot-armhf-2017-03-19-4gb.img.xz](https://debian.beagleboard.org/images/bone-debian-8.7-iot-armhf-2017-03-19-4gb.img.xz)

 has dnsmasq service enabled by default. It prevents kura's DHCP service from running. Documentation should be updated with instruction to disable dnsmasq service:
`sudo systemctl disable dnsmasq.service`

**Comment by cdealti** [comment]
@darionct what's the status of this?

**Comment by darionct** [comment]
Documentation has been updated:
http://eclipse.github.io/kura/intro/beaglebone-quick-start.html
