### ISSUE TITLE
[Wires] Asset configuration is not updated after a ChannelDescriptor change.

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#1376]
If a BaseAsset instance is attached to a driver, and the channel descriptor of a driver is changed by adding new properties (for example by installing a new version of the driver with a different channel descriptor), the configuration of the existing Asset will not be updated.

The expected behaviour would be that the old configuration of the Asset gets merged with the default values of the new properties (if any) obtained from the channel descriptor.

Currently if the cannel descriptor of a driver changes, the configuration of an existing BaseAsset attached to it will contain null values for the new properties.

**Comment by MMaiero** [comment]
Closing as #1387 was merged
