### ISSUE TITLE
Kura.Camel : jdbc No bean found in the registry for: dataSource of type: javax.sql.DataSource 

### ISSUE THREAD

**Issue by austindsouza** [eclipse/kura#1377]
Hi 

I have started learning Eclipse Kura. I understood the basics of it. Now I want to give a try to read streaming data and sinking to Oracle database, using Kura-Camel runner. 
However, I couldn't find example of how to add a dataSource to Kura Context .

I'm implementing this using kuraCamelQuickstart example deployed in Kura Emulator, and my approach is like this

String url = "jdbc:oracle:thin:@MYSERVER:1521:myDB";
DataSource dataSource = setupDataSource(url);
SimpleRegistry reg = new SimpleRegistry() ;
reg.put("myDataSource",dataSource);
CamelContext context = new DefaultCamelContext(reg);
context.addRoutes(new JDBCExample().new MyRouteBuilder());

However I am getting the following error: 
Failed to resolve endpoint: jdbc://dataSource?useHeadersAsParameters=true due to: No bean could be found in the registry for: dataSource of type: javax.sql.DataSource

How to do this within KuraCamelRunner 

Can anyone please help me.

**Comment by ctron** [comment]
I am not sure if I fully understand what you are doing by that snippet. But I think that the data source you put into the context is named `myDataSource` in your example instead of `dataSource`.

**Comment by austindsouza** [comment]
Hi Ctron,

Thanks for your reply, Here is my full code.

public class GatewayRouterJava implements ConfigurableComponent {
    private static final Logger logger = LoggerFactory.getLogger(GatewayRouterJava.class);
    
    String url = "jdbc:oracle:thin:@myserver:1521:myDB";
    DataSource dataSource = setupDataSource(url);
   
    private static final RouteBuilder NO_ROUTES = new RouteBuilder() {

        @Override
        public void configure() throws Exception {
        }
    };

    private CamelRunner camel;
    private String cloudServiceFilter;
    public void start(final Map<String, Object> properties) throws Exception {
        logger.info("Start: {}", properties);

        final String cloudServiceFilter = makeCloudServiceFilter(properties);
        this.camel = createCamelRunner(cloudServiceFilter);
        this.camel.setRoutes(fromProperties(properties));
        this.camel.start();
    }

	private DataSource setupDataSource(String connectURI) {
        BasicDataSource ds = new BasicDataSource();
        ds.setDriverClassName("oracle.jdbc.driver.OracleDriver");
        ds.setUsername("admin");
        ds.setPassword("admin");
        ds.setUrl(connectURI);
        return ds;
	}

	public void updated(final Map<String, Object> properties) throws Exception {
        logger.info("Updating: {}", properties);
        final String cloudServiceFilter = makeCloudServiceFilter(properties);
        if (!this.cloudServiceFilter.equals(cloudServiceFilter)) {
            this.camel.stop();
            this.camel = createCamelRunner(cloudServiceFilter);
            this.camel.setRoutes(fromProperties(properties));
            this.camel.start();
        } else {

            this.camel.setRoutes(fromProperties(properties));
        }
    }

    public void stop() throws Exception {
        if (this.camel != null) {
            this.camel.stop();
            this.camel = null;
        }
    }

    private CamelRunner createCamelRunner(final String fullFilter) throws InvalidSyntaxException {
        final BundleContext ctx = FrameworkUtil.getBundle(GatewayRouterJava.class).getBundleContext();

        this.cloudServiceFilter = fullFilter;

        final Builder builder = new CamelRunner.Builder();
        
        SimpleRegistry reg = new SimpleRegistry() ;
	    reg.put("myDataSource",dataSource);
	    
	    CamelContext context = new DefaultCamelContext(reg);
	    try {
			context.start();
		} catch (Exception e) {
			e.printStackTrace();
		}

        builder.dependOn(ctx, FrameworkUtil.createFilter(fullFilter),
                new ServiceConsumer<CloudService, CamelContext>() {

                    @Override
                    public void consume(final CamelContext context, final CloudService service) {
                        context.addComponent("cloud", new KuraCloudComponent(context, service));
                    }
                });
        return builder.build();
    }

    private static String makeCloudServiceFilter(final Map<String, Object> properties) {
        final String filterPid = Configuration.asStringNotEmpty(properties, "cloudService",
                "org.eclipse.kura.cloud.CloudService");
        final String fullFilter = String.format("(&(%s=%s)(kura.service.pid=%s))", Constants.OBJECTCLASS,
                CloudService.class.getName(), filterPid);
        return fullFilter;
    }

    protected RouteBuilder fromProperties(final Map<String, Object> properties) {
        if (!Configuration.asBoolean(properties, "enabled")) {
            return NO_ROUTES;
        }

        final int maxTemp = asInt(properties, "temperature.max", 20);
        return new RouteBuilder() {

            @Override
            public void configure() throws Exception {
            	from("mqtt:bar?subscribeTopicName=test&host=tcp://localhost:1883")
            	.process(new MyProcessor())
            	.to("jdbc:myDataSource?resetAutoCommit=false");
            }
        };
    }
}

**Comment by ctron** [comment]
Ok, I think I understood the problem.

Your are manually creating a Camel context, but should rather be using the one provided by the `CamelRunner`.

The `CamelRunner.Builder` allows you to provide your own registry:

```java
Builder builder = new CamelRunner.Builder();
…
builder.registryFactory ( () -> {
    SimpleRegistry reg = new SimpleRegistry() ;
    reg.put("myDataSource",dataSource);
}) ;
…
return builder.build();
```

**Comment by austindsouza** [comment]
Hi ctron,
Thanks for your reply,  will try this.

Meanwhile If I want to use Camel XML Router in Kura web UI, how to set jdbc Datasource definaton in spring configuration.

I tried to do this like this:
==== XML ====
routes xmlns="http://camel.apache.org/schema/spring"
  bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource"
	property name="driverClassName" value="oracle.jdbc.driver.OracleDriver"
	property name="url" value="jdbc:oracle:thin:@myserver:1521:myDB"
	property name="username" value="monetdb"
	property name="password" value="monetdb"
  bean

  bean id="jdbcComponent" class="org.apache.camel.component.jdbc.JdbcComponent"
	property name="dataSource" ref="dataSource"
  bean

  route id="route1"
         from uri="mqtt:bar?host=tcp://localhost:1883&amp;subscribeTopicName=test1"
         to uri="jdbc:dataSource?useHeadersAsParameters=true"
  route
routes

==== XML ====


Can you guide me on this?

**Comment by ctron** [comment]
You can't use spring in the XML router. Just plain routes.

**Comment by austindsouza** [comment]
Hi ctron,

I tried your suggestion like this

SimpleRegistry reg = new SimpleRegistry() ;
reg.put("myDataSource",dataSource);
builder.registryFactory(createOsgiRegistry(ctx, reg));

and the previous error is gone now, However I'm getting  java.lang.ClassNotFoundException for JDBC driver.

I tried to add it manually including external jar from the build path and also by adding the jar in Target-definition, but no luck.

**Comment by ctron** [comment]
Well for this to work you either need an OSGi capable version of a JDBC driver, like IIRC postgresql. Or you will need to wrap this yourself.

You can also add the JAR file to your local bundle and add them via the `MANIFEST.MF` entry `Bundle-Classpath: `.

**Comment by austindsouza** [comment]
Hi ctron,

1) I tried to add the JAR file by creating lib folder in my project and added the jdbc JAR inside that, and then added -> Bundle-ClassPath: lib/mysql-connector-java-5.1.15.jar, .  in MANIFEST.MF file

2) Created a OSGI capable jar file in Eclipse File -> new -> Plug-in from Existing Archives.
both approach is giving me the following error.

org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class 'com.mysql.jdbc.Driver'
	at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.apache.camel.component.jdbc.JdbcProducer.processingSqlWithoutSettingAutoCommit(JdbcProducer.java:112)
	at org.apache.camel.component.jdbc.JdbcProducer.process(JdbcProducer.java:69)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:468)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.mqtt.MQTTConsumer.processExchange(MQTTConsumer.java:51)
	at org.apache.camel.component.mqtt.MQTTEndpoint$2.onPublish(MQTTEndpoint.java:256)
	at org.fusesource.mqtt.client.CallbackConnection$8.onPublish(CallbackConnection.java:521)
	at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
	at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
	at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
	at org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:132)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1420)
	... 23 more

**Comment by ctron** [comment]
The mysql connector already is an OSGi bundle. There is no need to wrap this one. Simply define an OSGi package or bundle dependency.

**Comment by austindsouza** [comment]
1) My build.properties file looks like this 

output.. = target/classes
source.. = src/main/java/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               about.html
additional.bundles = org.apache.commons.dbcp,\
                     org.apache.commons.pool,\
                     com.mysql.jdbc

2) MANIFEST.MF is like this

Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-SymbolicName: org.eclipse.kura.example.camel.quickstart
Bundle-Version: 1.1.100.qualifier
Bundle-Name: Camel Quickstart
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Service-Component: OSGI-INF/*.xml
Import-Package: org.apache.camel;version="[2.17.0,3.0.0)",
 org.apache.camel.builder;version="[2.17.0,3.0.0)",
 org.apache.camel.impl;version="2.17.2",
 org.apache.camel.model;version="[2.17.0,3.0.0)",
 org.eclipse.kura.camel;version="1.1.0",
 org.eclipse.kura.camel.camelcloud;version="[1.1.0,2.0.0)",
 org.eclipse.kura.camel.cloud;version="[1.1.0,2.0.0)",
 org.eclipse.kura.camel.component;version="[1.1.0,2.0.0)",
 org.eclipse.kura.camel.runner;version="1.1.0",
 org.eclipse.kura.cloud;version="[1.0.0,2.0.0)",
 org.eclipse.kura.configuration;version="[1.1.0,2.0.0)",
 org.eclipse.kura.message;version="[1.0.0,2.0.0)",
 org.osgi.framework;version="1.7.0",
 org.osgi.service.component;version="1.2.0",
 org.slf4j;version="[1.7.0,2.0.0)"
Bundle-ActivationPolicy: lazy
Bundle-Vendor: Eclipse Kura
Require-Bundle: org.apache.commons.dbcp

what am I missing?

**Comment by ctron** [comment]
Import-Package: com.mysql.jdbc

**Comment by austindsouza** [comment]
HI ctron,

I've added the mysql JDBC jar, now  I'm getting java.sql.SQLException: No suitable driver Exception.

My updated code looks like this now.

String url = "jdbc:mysql://localhost:3306/testing";

  private static final RouteBuilder NO_ROUTES = new RouteBuilder() {
        @Override
        public void configure() throws Exception {
        }
    };
    private CamelRunner camel;
    private String cloudServiceFilter;
    public void start(final Map<String, Object> properties) throws Exception {
        logger.info("Start: {}", properties);
        final String cloudServiceFilter = makeCloudServiceFilter(properties);
        this.camel = createCamelRunner(cloudServiceFilter);
        this.camel.setRoutes(fromProperties(properties));
        this.camel.start();
    }

    private DataSource setupDataSource(String connectURI) throws Exception {
    	BasicDataSource ds = new BasicDataSource();
    	URL[] classLoaderUrls = new URL[]{new URL("file:///home/user/JARs/mysql-connector-java-5.1.15.jar")};
    	URLClassLoader urlClassLoader = new URLClassLoader(classLoaderUrls);

    	ds.setDriverClassLoader(urlClassLoader);
        ds.setDriverClassName("com.mysql.jdbc.Driver");
        ds.setUsername("root");
        ds.setPassword("admin");
        ds.setUrl(url);
        return ds;
	}

	public void updated(final Map<String, Object> properties) throws Exception {
        logger.info("Updating: {}", properties);

        final String cloudServiceFilter = makeCloudServiceFilter(properties);
        if (!this.cloudServiceFilter.equals(cloudServiceFilter)) {
            // update the routes and the filter
            // stop the camel context first
            this.camel.stop();
            // create a new camel runner, with new dependencies
            this.camel = createCamelRunner(cloudServiceFilter);
            this.camel.setRoutes(fromProperties(properties));
            this.camel.start();
        } else {
             this.camel.setRoutes(fromProperties(properties));
        }
    }

    public void stop() throws Exception {
        if (this.camel != null) {
            this.camel.stop();
            this.camel = null;
        }
    }

    private CamelRunner createCamelRunner(final String fullFilter) throws Exception {
        final BundleContext ctx = FrameworkUtil.getBundle(GatewayRouterJava.class).getBundleContext();

        this.cloudServiceFilter = fullFilter;

        // create a new camel CamelRunner.Builder

        final Builder builder = new CamelRunner.Builder();
        
        SimpleRegistry reg = new SimpleRegistry() ;
        reg.put("myDataSource",setupDataSource(url));
        
        builder.registryFactory(createOsgiRegistry(ctx, reg));
         builder.dependOn(ctx, FrameworkUtil.createFilter(fullFilter),
                new ServiceConsumer<CloudService, CamelContext>() {

                    @Override
                    public void consume(final CamelContext context, final CloudService service) {
                        context.addComponent("cloud", new KuraCloudComponent(context, service));
                    }
                });
    return builder.build();
    }
    private static String makeCloudServiceFilter(final Map<String, Object> properties) {
        final String filterPid = Configuration.asStringNotEmpty(properties, "cloudService",
                "org.eclipse.kura.cloud.CloudService");
        final String fullFilter = String.format("(&(%s=%s)(kura.service.pid=%s))", Constants.OBJECTCLASS,
                CloudService.class.getName(), filterPid);
        return fullFilter;
    }
    protected RouteBuilder fromProperties(final Map<String, Object> properties) {
      if (!Configuration.asBoolean(properties, "enabled")) {
            return NO_ROUTES;
        }
        final int maxTemp = asInt(properties, "temperature.max", 20);
        return new RouteBuilder() {
          @Override
            public void configure() throws Exception {
         	from("mqtt:bar?subscribeTopicName=test&host=tcp://localhost:1883")
            	.process(new MyProcessor())
            	.to("jdbc:myDataSource?resetAutoCommit=false");
             }
        };
    } 

Error: 
org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'com.mysql.jdbc.Driver' for connect URL 'jdbc:mysql://localhost:3306/testing'
	at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1452)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.apache.camel.component.jdbc.JdbcProducer.processingSqlWithoutSettingAutoCommit(JdbcProducer.java:112)
	at org.apache.camel.component.jdbc.JdbcProducer.process(JdbcProducer.java:69)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:468)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.mqtt.MQTTConsumer.processExchange(MQTTConsumer.java:51)
	at org.apache.camel.component.mqtt.MQTTEndpoint$2.onPublish(MQTTEndpoint.java:256)
	at org.fusesource.mqtt.client.CallbackConnection$8.onPublish(CallbackConnection.java:521)
	at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
	at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
	at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
	at org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1437)
	... 23 more

**Comment by ctron** [comment]
So if you enforce the class loader of this jar, then the pool seems to have a problem to find your class. I would suggest to not work around OSGi, but to set the class loader returned by your class. This should be the correct OSGi class loader for your bundle. If you bundle properly imports all packages, you should be good to go.

**Comment by austindsouza** [comment]
Hi ctron,

Thanks for your time and support, I'm bit lost here. Can you please tell me what exactly I need to do here.

**Comment by ctron** [comment]
So in general you need to wire up OSGi dependencies. If you can give me a sample project (e.g. on GitHub) I can try to fix it for you.

**Comment by austindsouza** [comment]
Please find my GitHub repo https://github.com/austindsouza/Eclipse-Kura

**Comment by austindsouza** [comment]
Hi ctron,
Did you get a chance to look into my GitHub project?

**Comment by ctron** [comment]
Not on the weekend sorry. I will look into this in the next days.

**Comment by austindsouza** [comment]
Hi ctron,
Sorry to bother you again. Did you checked the issue?

**Comment by ctron** [comment]
I am sorry but I cannot put any priority on this task, I will check this in the next few days, as I said. If it is that urgent, then I suggest that your invest a little bit of time into OSGi, which will help you understand the underlying issue and fix the issue. Otherwise please be patient until I can find some time to solve your issue.

**Comment by amitjoy** [comment]
I am not sure if the mysql-connector jar is OSGi-fied properly. You can also add the simple jar (non OSGi-fied) in a folder in your project (e.g lib) and add Bundle-Classpath in your manifest (MANIFEST.MF) to point to this lib folder. And then you can manually set the `DataSource`'s `URLClassLoader` in the following way. This should set the proper classloader to the `DataSource` to load the mysql driver.

```java

private static Map<String, ServiceTracker<Object, URLConverter>> urlConverterTrackers = new ConcurrentHashMap<>();

static {
         try {
             final URL url = new URL("platform:/plugin/org.eclipse.kura.example.camel.quickstart/lib/mysql-connector-java-5.1.15.jar");
             final Optional<URLConverter> converter = getURLConverter(url);
             Optional<URL> fileUrl = Optional.empty();
             if (converter.isPresent()) {
                 fileUrl = Optional.of(converter.get().toFileURL(url));
             }
             Optional<ClassLoader> classLoader = Optional.empty();
             if (fileUrl.isPresent()) {
                 classLoader = Optional
                         .of(new URLClassLoader(new URL[] { fileUrl.get() }, GatewayRouterJava.class.getClassLoader()));
             }
             if (classLoader.isPresent()) {
                 ds.setDriverClassLoader(classLoader.get());
             }
         } catch (final IOException e) {
             logger.error(e.getMessage(), e);
         }
     }

public static Optional<URLConverter> getURLConverter(final URL url) {
         final BundleContext ctx = FrameworkUtil.getBundle(GatewayRouterJava.class).getBundleContext();
         if ((url == null) || (ctx == null)) {
             return Optional.empty();
         }
         final String protocol = url.getProtocol();
         ServiceTracker<Object, URLConverter> tracker = urlConverterTrackers.get(protocol);
         if (isNull(tracker)) {
             final String urlFilter = "(&(objectClass=" + URLConverter.class.getName() + ")(protocol=" + protocol + "))";
             Filter filter = null;
             try {
                 filter = ctx.createFilter(urlFilter);
             } catch (final InvalidSyntaxException e) {
                 return Optional.empty();
             }
             tracker = new ServiceTracker<>(ctx, filter, null);
             tracker.open();
             urlConverterTrackers.put(protocol, tracker);
             return Optional.of(tracker.getService());
      }

//call it in deactivate() or stop()
private static void closeURLConverterTrackers() {
         if (!urlConverterTrackers.isEmpty()) {
             for (final ServiceTracker<Object, URLConverter> tracker : urlConverterTrackers.values()) {
                 tracker.close();
             }
             urlConverterTrackers = CollectionUtil.newConcurrentHashMap();
         }
     }
```

**Comment by ctron** [comment]
Hi @austindsouza, I found some time to prepare an example with JDBC + MySQL.

As I find the Tycho approach rather complicated I built that based on plain Maven. You can find the source here: https://github.com/ctron/kura-examples/tree/master/camel/camel-example-2

There is a readme and a simple way to test this. The component itself should rather straight forward, and you should be able to take this over to your example. However the maven build ensures that you have all your dependencies correctly resolved, this should sort out the issues you had with OSGi. For testing and debugging you can of course use Eclipse as an IDE, but if you feel more comfortable with a different IDE, then this shouldn't be a problem.

Let me know when you run into problems.

**Comment by austindsouza** [comment]
Hi Ctron,

This example worked fine as expected...
Thank you so much for your time and continuous support.

**Comment by ctron** [comment]
Sorry that I couldn't to that earlier. If you encounter any problems let me know and I will take a look.

Thanks for the feedback!

**Comment by ghost** [comment]
Hi,
I am new to camel, trying to retrieve bytea file from postgreSQL and save in my local directory in xml format. I tried. I have service running which is saving xml file in postgreSQL(in bytea format) now m trying to retrieve that file in same format, but not able to. Can you please help

**Comment by dwoodard1** [comment]
@jaspannud I would recommend creating a new Issue with your question. Comments to closed Issues will not receive much attention.
