### ISSUE TITLE
eclipse kura and AWS IoT™ platform : aws device ssl certificate error

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#1388]
I try to connect kura and aws, but no success,
I get this error:
ILLEGAL_ARGUMENTorg.eclipse.kura.web.shared.GwtKuraException: ILLEGAL_ARGUMENT
at Unknown.gd(denali-0.js)
at Unknown.pd(denali-0.js)
at Unknown.SYb(denali-0.js)
at Unknown.XYb(denali-0.js)
at Unknown.f3(denali-0.js)
at Unknown.b3(denali-0.js)
at Unknown.A1(denali-0.js)
at Unknown.h2(denali-0.js)
at Unknown._n(denali-0.js)
at Unknown.oo(denali-0.js)
at Unknown.eval(denali-0.js)
at Unknown.je(denali-0.js)
at Unknown.me(denali-0.js)
at Unknown.eval(denali-0.js)

PS: I have entered this command: openssl pkcs8 -topk8 -inform PEM -outform PEM -in xxxxxxxxxx-private.pem.key -out outKey.pem -nocrypt, but but without success.

Kura version: 3.0.0.
Device:Raspberry Pi.

Thanks in advance

**Comment by MMaiero** [comment]
Hi, did you follow the tutorial available here: http://eclipse.github.io/kura/cloud/kura-aws-cloud.html ?

**Comment by marentwickler** [comment]
thanks,
yes, i have entered all steps from this guid, but by tab Device SSL Certificate comes this error.

**Comment by MMaiero** [comment]
Is the keystore correctly set and linked by the SSL tab in Kura?

**Comment by marentwickler** [comment]
thanks,
yes, default:/opt/eclipse/kura/security/cacerts.ks.
I have also tried with /opt/eclipse/kura/security/cacerts, but same error.

**Comment by MMaiero** [comment]
but, is there the corresponding file in one of these locations?

**Comment by MMaiero** [comment]
Kura, by default, is provided without a specific keystore file. You need to create that, as described in the documentation file.

**Comment by marentwickler** [comment]
now i used /opt/eclipse/kura/security/cacerts as keystore, but same error.

**Comment by marentwickler** [comment]
at the beginning I have worked with this document :https://blog.benjamin-cabe.com/2015/10/23/tutorial-connecting-eclipse-kura-to-aws-iot.
by them the keystore is the default value.

**Comment by MMaiero** [comment]
That guide was used as a reference for the new one here http://eclipse.github.io/kura/cloud/kura-aws-cloud.html that is more up to date.
Looking at point 7, it suggests to create a directory: `sudo mkdir /opt/eclipse/security`. Did you follow this step? If so, the path you provided in the Kura web ui is not correct.

**Comment by marentwickler** [comment]
yes,  i have entered all steps from 1 to 9, but always same error.

**Comment by dwoodard1** [comment]
@marentwickler I noticed you closed this issue, did you resolve your issue? If so, could you share your solution? It may help others who run into the same problem.

**Comment by marentwickler** [comment]
@dwoodard1,@MMaiero   thanks, yes i resolved my issue, on tab MqttDataTransport-AWS  the parameter  lwt.retain was on true, solution is  lwt.retain=false, then  Raspberry-Pi device is connected with AWS platform IoT.
I have used guid :https://eclipse.github.io/kura/cloud/kura-aws-cloud.html.
