### ISSUE TITLE
[Wires] Fifo is really FIFO only while it's full

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1391]
Fifo component takes the last element out of the queue making it partially a LIFO.

```java
...
if (!run) {
    break;
}
next = queue.remove(queue.size() - 1);
consumer.signal();
...
```
Until it's full it will behave erratically, when it fills up, it works properly, if it doesn't discard the inbound envelopes. When it starts to empty, it emits the oldest few elements.

Kura 3.1.0, develop branch

**Comment by MMaiero** [comment]
Merged PR #1392. Closing then.
