### ISSUE TITLE
Connecting Heater Example with  AWS-Platform

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#1393]
hello,
I can't  transfer data from kura Heater Example to AWS-platform.
-device:Raspberry Pi
-kura cloud is connected to AWS IoT platform
-on kura-cloud web console: Tab MqttDataTransport-AWS=> 
                                                  lwt.topic=$aws/things/client_id/shadow/update
-on Heater web console: publish.semanticTopic=sample/topic
-on AWS Platform: Subscribe to a topic=sample/topic

what am I doing wrong?

thanks in advance

**Comment by MMaiero** [comment]
Hi,
I think that the heater example takes the default cloud service. If you added the AWS cloud stack in addition to the default one, the heater demo will take the latter to publish.
I would suggest using the [Example publisher](https://marketplace.eclipse.org/content/example-publisher-eclipse-kura). It is a little bit complex, in comparison to the heater demo, but it allows to select the cloud service stack to use.

Best regards,
Matteo

**Comment by marentwickler** [comment]
thanks,
I have run the Example publisher  on raspberry pi, I can't transfer data from kura-device to aws-platform, I need the right parameters such as lwt.topic from MqttDataTransport-AWS, publish.appTopic from Example publisher modul, Subscribe to a topic from AWS Platform...

--------------------                                  --------------------
 Kura-device-Topic  ,MQTT parameters        <======>           remote cloud service     , Topic &  parameters       
                                   
--------------------                                   --------------------

AWS IoT Platform work with Reserved Topics lik $aws/things/thingName/
shadow/update and with Subscription topic.
what am I doing wrong?
I have tried, but without success.

thanks in advance

**Comment by MMaiero** [comment]
Hi,
could you share an excerpt of your kura.log file? In theory, if you have followed the guide you should be able to be connected and you should also be able to publish. What you could more, is to modify the cloud service preference to publish in JSON, so the data would be readable using the AWS console tooling.

At this time, the cloud service or the example publisher do not support device shadow. If you want to achieve that support, you need to create a specific application.

Best regards,
Matteo

**Comment by marentwickler** [comment]
Hi,
my kura.log file:
2017-05-25 12:07:15,392 [pool-26-thread-1] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :#account-name/#client-id/EXAMPLE_PUBLISHER/data/metrics, priority: 5
2017-05-25 12:07:15,394 [pool-26-thread-1] ERROR o.e.k.c.d.s.DbDataStore - Store capacity exceeded
2017-05-25 12:07:15,394 [pool-26-thread-1] ERROR o.e.k.e.p.ExamplePublisher - Cannot publish topic: data/metrics
org.eclipse.kura.KuraStoreCapacityReachedException: "Error performing operation on store. Store capacity exceeded"
	at org.eclipse.kura.core.data.store.DbDataStore.store(DbDataStore.java:285)
	at org.eclipse.kura.core.data.DataServiceImpl.publish(DataServiceImpl.java:443)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:139)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:125)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:111)
	at org.eclipse.kura.core.cloud.CloudClientImpl.publish(CloudClientImpl.java:105)
	at org.eclipse.kura.example.publisher.ExamplePublisher.doPublish(ExamplePublisher.java:317)
	at org.eclipse.kura.example.publisher.ExamplePublisher.access$5(ExamplePublisher.java:276)
	at org.eclipse.kura.example.publisher.ExamplePublisher$1.run(ExamplePublisher.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
thanks in advance

**Comment by MMaiero** [comment]
Could you please link the entire file? The snippet is not sufficient to understand what is going on

**Comment by marentwickler** [comment]
Hi,
These errors are always repeated,
kura-console.log:

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-05-25 11:37:47.973
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@e52dc 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0.jar

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-05-25 12:20:16.453
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@2ad159 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0.jar

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-05-25 12:23:49.915
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@1bf0cc0 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0.jar

**Comment by MMaiero** [comment]
Those errors in kura-console.log are related to some bug into multiple cloud connections, but I believe it is tracked in an issue.

I would like to have a look at the entire kura.log file (maybe you can share it via s3 or dropbox) to understand what is going on.

Thanks.

**Comment by MMaiero** [comment]
@marentwickler Any update?

**Comment by marentwickler** [comment]
@MMaiero hi,
today I solved the problem, my new  configuration is so:

on kura cloud configuration:
-lwt.topic is empty file
-lwt.retain=false
-topic.control-prefix=$aws

 On Example Publisher Modul
-cloud.service.pid=org.eclipse.kura.cloud.CloudService-AWS
-app.id=EXAMPLE_PUBLISHER
-publish.retain=false
-publish.appTopic=data/metrics

on AWS platform
-Subscribe to a topic= IoT account-name(account-name for thing)/client-id(client-id thing)/EXAMPLE_PUBLISHER/data/metrics

Then I transformed the data from kura to AWS cloud.

Best regards,

**Comment by MMaiero** [comment]
Thanks for the update.
In your opinion, do we need to change something in the documentation? Is there something unclear that we need to change?

For now, I will close the issue.

**Comment by marentwickler** [comment]
@MMaiero Hi ,
yes,The documentation is very good, but is not complete, because  the other platforms changes also, and there are many use cases,It will be easier for beginners, if the question 'why' will be answerd .That's great Effort from you and from your team.Thanks so much.
and i am on kura for next issue and next difficulty :-).
