### ISSUE TITLE
Write to Modbus Asset Channel

### ISSUE THREAD

**Issue by kcsj17** [eclipse/kura#1395]
I can successfully read from Modbus asset channel and publish to the cloud, but How do I subscribe to cloud service and be able to write to SPECIFIC Modbus Asset Channels when the topic value changes?

**Comment by MMaiero** [comment]
Hi, 
you can use the Subscriber block or, otherwise, you can leverage the ASSET-V1 cloudlet to send commands directly to the asset (please have a look here: https://github.com/eclipse/kura/wiki/ASSET-V1-MQTT-Namespace).

Best regards,
Matteo

**Comment by MMaiero** [comment]
@kcsj17 any updates?

**Comment by kcsj17** [comment]
To be honest, I dont quite understand as yet how to use the Subscriber block to receive write messages to a specific channel. Specifically, 1) the format the mqtt message has to take. 2) the necessary configuration of the subscriber block.

**Comment by MMaiero** [comment]
The message received by the subscriber has to carry a metric with a name and a type that matches the channel name and type defined in the asset block.

**Comment by MMaiero** [comment]
Closing since there are no updates for a long time. Please reopen it, if needed.
