### ISSUE TITLE
Fix trivial Sonar Lint problems in the network bundles

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1405]
@ibinshtok we could try to fix some of the most trivial Sonar Lint problems in the network bundles.
Before fixing the others (e.g. cyclomatic complexity) it would be good to have some code coverage by @markoer to avoid regressions.
Please let me know if we can schedule this for the next 3.1 milestone.

**Comment by ibinshtok** [comment]
@cdealti yes, we can

**Comment by MMaiero** [comment]
@ibinshtok Is this completed?

**Comment by markoer** [comment]
I still have work on the testing side. Probably refactoring is not finished either.

**Comment by ibinshtok** [comment]
@MMaiero  I still need to clean up the following packages:
org.eclipse.kura.linux.net
org.eclipse.kura.linux.net.dhcp
org.eclipse.kura.linux.net.dns
org.eclipse.kura.linux.net.iptables
org.eclipse.kura.linux.net.modem
org.eclipse.kura.linux.net.ppp
org.eclipse.kura.linux.net.route

**Comment by cdealti** [comment]
@ibinshtok any reason you moved this from **In progress** to **New Issues**?

**Comment by ibinshtok** [comment]
@cdealti I did not doi that. Moved it back to "In Progress"

**Comment by cdealti** [comment]
@ibinshtok please re-estimate this issue.

If you cannot commit to complete the remaining part:
1. Clear the milestone
2. Move this item at the bottom of the Backlog pipeline

**Comment by ibinshtok** [comment]
To complete this issue we need to touch the following packages:
In the org.eclipse.kura.api project:
org.eclipse.kura.net
org.eclipse.kura.net.dhcp
org.eclipse.kura.net.dns
org.eclipse.kura.net.firewall
org.eclipse.kura.net.modem
org.eclipse.kura.net.route
org.eclipse.kura.net.wifi

In the org.eclipse.kura.core.net project:
org.eclipse.kura.core.net
org.eclipse.kura.core.net.modem
org.eclipse.kura.core.net.util

In the org.eclipse.kura.net.admin project:
It looks like we need to go through all packages and fix the remaining trivial issues.

**Comment by cdealti** [comment]
@ibinshtok I'd prefer to split this in multiple tasks (issues). We don't need to fix everything in this sprint.
What do you think we should address first?
Please coordinate with @markoer to reduce the dependencies.

**Comment by cdealti** [comment]
Let's go ahead with API net packages. @ibinshtok please create a new issue

**Comment by cdealti** [comment]
I'll convert this into an Epic (as it may span multiple sprints) and add issues as user stories(or tasks ?)
