### ISSUE TITLE
Karaf dependency versions should match kura.build.properties values

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1407]
In order to keep consistency between the distrib of Kura and the Karaf build, the versions in Karaf features poms must match the ones specified in kura.build.properties and kura.target-platform.build.properties

**Comment by cdealti** [comment]
There was an issue opened by @ctron stating that Maven will not be able to resolve locally compiled -SNAPSHOT dependencies (if any in kura.build.properties and kura.target-platform.build.properties). But it seems I cannot find this issue.

**Comment by cdealti** [comment]
See #99.
