### ISSUE TITLE
Karaf tuning

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1415]
* Karaf persistence options (full persistence, Karaf persistence + OSGi clean, no persistence). Boot time and reliability on Karaf restart, OS reboot, power-cycling
* JVM (OpenJDK vs Oracle JRE) on x86_64/arm
* JVM Xmx, Xms
* logging (analogous to kura.log)
* logging of the JVM stdout stderr (analogous to kura-console.log)
* Long running test monitoring resources

**Comment by cdealti** [comment]
@MMaiero can we provide some visibility to the results in a WiKi page? It does not matter if we used a commercial gateway (comparable with the Beagle Bone Black).

**Comment by MMaiero** [comment]
https://github.com/eclipse/kura/wiki/Karaf-notes

**Comment by cdealti** [comment]
Thanks. Can you please fix the links in the Wiki page (they all appear on the same line)?

Can you please clarify the differences between the Karaf distribution (e.g. emulator) and a regular Kura distribution (e.g. with net admin)?

Can you please provide a rough description of the hardware used for startup times (CPU, CPU speed, number of cores, RAM).

Can you clarify how the startup time has been measured.

Do you suggest starting Karaf with OSGi clean set to true? Can you shortly explain why?

**Comment by cdealti** [comment]
See #99
