### ISSUE TITLE
Promote Assets and Drivers like Cloud Services in the Web UI

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1420]
This is an initial discussion on how to manage Driver and Asset instances from the Web UI.

1. Configurations of Drivers and Assets will be moved from the generic **Services** section of the Web UI to and dedicated **Drivers and Assets** section similarly to what we did with **Cloud Services**.
2. In theory, Drivers and Assets can be used without Kura Wires so it should be desirable if they could be created and managed separately. For example, Kura already allows to create configurations of ``BaseAsset``
2.1. Configurations of ``BaseAsset`` created from **Drivers and Assets** will be then available in the Wire Composer which only manages configuration of ``WireAsset``. Vice versa configurations of ``WireAsset`` will be available in **Drivers and Assets**.
2.2. Currently the Wire Composer does not allow creating a configuration of Driver and since this ability will be removed from the generic **Services**, creating a new Driver configuration will be available from **Drivers and Assets**
2.3. Such configurations of Driver can be shared between ``BaseAsset`` and ``WireAsset`` (they can be selected from the Wire Composer). Is this confusing?
2.3. There is an one-to-many relation between Driver and Asset that need to be properly represented in **Assets and Drivers**. Note that only instances of ``BaseAsset`` are shown here
3. **Drivers and Assets** shall allow reading a channel on demand (a box showing the channel value with a refresh button)

**Comment by nicolatimeus** [comment]
Some UI mockups for the new Assets and Drivers section are available in the [Kura Wiki](https://github.com/eclipse/kura/wiki/Assets-and-Driver-Web-Ui-section-mockups)

**Comment by cdealti** [comment]
I like 1 and 3 of the Driver and Asset mockups.

I've edited the description of this issue and added a new requirement (3).

I believe the changes to Wire Composer should also keep in mind #1268 (and #1462).

**Comment by dwoodard1** [comment]
For Assets and Drivers, I think my vote would be for Proposal 1. However, if the expandable lists are too complicated to do in GWT, the tabs in Proposal 3 are also okay.

**Comment by nicolatimeus** [comment]
A [new proposal](https://github.com/eclipse/kura/wiki/Assets-and-Driver-Web-Ui-section-mockups#update-11-07-2017) has been added to the Wiki.

**Comment by cdealti** [comment]
@MMaiero feel free to convert this in an epic and start adding small issues to achieve the new proposal goal.
