### ISSUE TITLE
Kura: Camel-Ignite Could not resolve module Exception

### ISSUE THREAD

**Issue by austindsouza** [eclipse/kura#1426]
Hi,

I am trying to to create a "camel route" that listens to mqtt data and publishes to a Ignite-cache within kura context, using the below code snippet. 

public void configure() throws Exception {
            	
            	from("mqtt:bar?subscribeTopicName=test&host=tcp://localhost:1883")
				.process(new Processor() {
					public void process(Exchange exchange)throws Exception {
						exchange.getIn().setHeader(IgniteConstants.IGNITE_CACHE_KEY, exchange.getIn().getBody(String.class));
					}
				})
				.to("ignite-cache:cache:myCacheName?operation=PUT");
            	
            }

However when I tried to install the dependency jars to Kura's emulator I am getting the error.

osgi> install file:///home/user/Downloads/ignite-core-2.0.0.jar
gogo: BundleException: Could not resolve module: org.apache.ignite.ignite-core [96]
  Unresolved requirement: Import-Package: javax.cache.configuration

I have already installed the bundle which contains the javax.cache.configuration package, and its status is active. 
id	State       Bundle
95    ACTIVE   javax.cache.api_1.0.0

What am I missing, can anyone help?

Best Regards.

**Comment by ctron** [comment]
Do you have something to reproduce this?

**Comment by austindsouza** [comment]
In Kura Emulator try to install the following jar's 1) ignite-core-2.0.0.jar  2) cache-api-1.0.0.jar

install file:///home/user/Downloads/cache-api-1.0.0.jar
install file:///home/user/Downloads/ignite-core-2.0.0.jar

**Comment by ctron** [comment]
From which locations did you get those two files?

**Comment by austindsouza** [comment]
http://central.maven.org/maven2/org/apache/ignite/ignite-core/2.0.0/ignite-core-2.0.0.jar
http://central.maven.org/maven2/javax/cache/cache-api/1.0.0/cache-api-1.0.0.jar

**Comment by ctron** [comment]
Ok, I will try to reproduce this.

**Comment by ctron** [comment]
So looking at those two bundles I think the result is correct:

```
osgi> bundle 95
javax.cache.api_1.0.0 [95]
  Id=95, Status=ACTIVE      Data Root=/tmp/.kura/configuration/org.eclipse.osgi/95/data
  "No registered services."
  No services in use.
  Exported packages
    javax.cache; version="1.0.0"[exported]
    javax.cache.annotation; version="1.0.0"[exported]
    javax.cache.event; version="1.0.0"[exported]
    javax.cache.spi; version="1.0.0"[exported]
  Imported packages
    javax.management; version="0.0.0" <org.eclipse.osgi_3.11.1.v20160708-1632 [0]>
  No fragment bundles
  No required bundles


osgi> start 94
gogo: BundleException: Could not resolve module: org.apache.ignite.ignite-core [94]
  Unresolved requirement: Import-Package: javax.cache.configuration

```

The bundle `cache-api` does not export `javax.cache.configuration`.

You can reproduce this by:

```
docker run -ti ctron/kura-emulator
osgi> install http://central.maven.org/maven2/javax/cache/cache-api/1.0.0/cache-api-1.0.0.jar
osgi> install http://central.maven.org/maven2/org/apache/ignite/ignite-core/2.0.0/ignite-core-2.0.0.jar
osgi> start javax.cache.api
osgi> start org.apache.ignite.ignite-core
osgi> bundle javax.cache.api
```

So it looks like you are missing some other bundle.

**Comment by austindsouza** [comment]
With your tips and comments, was able to get quite a but further, by adding the required packages in  cache-api-1.0.0.jar MANIFEST file's  Export-Package like this 

javax.cache.configuration,javax.cache.expiry,javax.cache.integration,javax.cache.management,javax.c
 ache.processor

then I could able to install  ignite-core-2.0.0.jar and cache-api-1.0.0.jar

Now I'm getting another issue while installing camel-ignite-2.17.2.jar in Kura Emulator.

osgi> install http://central.maven.org/maven2/org/apache/camel/camel-ignite/2.17.2/camel-ignite-2.17.2.jar
gogo: BundleException: Could not resolve module: org.apache.camel.camel-ignite [106]
  Unresolved requirement: Import-Package: org.apache.ignite; version="[1.5.0,2.0.0)"

**Comment by ctron** [comment]
True: You seem to be using "ignite-2.0.0", however camel-ignite seems to be expecting 1.5.0 (inclusive) to 2.0.0 (exclusive). So 2.0.0 is out of range.

**Comment by austindsouza** [comment]
Hi,

I am trying to add Camel-Ignite context to Kura, my implementation is like this 

private CamelRunner createCamelRunner(final String fullFilter) throws Exception {
        final BundleContext ctx = FrameworkUtil.getBundle(GatewayRouterJava.class).getBundleContext();

        this.cloudServiceFilter = fullFilter;

        // create a new camel CamelRunner.Builder
        
        final Builder builder = new CamelRunner.Builder();
        SimpleRegistry reg = new SimpleRegistry() ;
        
        TcpDiscoveryVmIpFinder ipFinder = new TcpDiscoveryVmIpFinder();
		ipFinder.setAddresses(Collections.singletonList(HOST));

		TcpDiscoverySpi discoSpi = new TcpDiscoverySpi();
		discoSpi.setIpFinder(ipFinder);

		IgniteConfiguration cfg1 = new IgniteConfiguration();
		cfg1.setDiscoverySpi(discoSpi);
		cfg1.setPeerClassLoadingEnabled(false);

		CacheConfiguration cacheCfg = new CacheConfiguration<String, String>();
		cacheCfg.setName("myCacheName");
		cacheCfg.setCacheMode(CacheMode.PARTITIONED);
		cfg1.setCacheConfiguration(cacheCfg);
		
		reg.put("igniteCfg",cfg1);

        builder.registryFactory(createOsgiRegistry(ctx, reg));
        ((CamelContext) ctx).addComponent(getScheme(), IgniteComponent.fromConfiguration(cfg1));

when I'm uploading the plugin to emulator I got this error - 

java.lang.ClassCastException: org.eclipse.osgi.internal.framework.BundleContextImpl cannot be cast to org.apache.camel.CamelContext
at org.eclipse.kura.example.camel.quickstart.GatewayRouterJava.createCamelRunner(GatewayRouterJava.java:168)
at org.eclipse.kura.example.camel.quickstart.GatewayRouterJava.start(GatewayRouterJava.java:94)

**Comment by austindsouza** [comment]
Thank you @ctron .

I've changed the ignite-version in camel-ignite component's pom.xml file now its working.

**Comment by ctron** [comment]
Cool. Let me know if you need any additional help!
