### ISSUE TITLE
Missing CQs for native code binaries

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1427]
Kura seems to distribute the following artifacts for which I could not locate license information or CQs:

https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/intel-edison/bind.init
https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/intel-edison/dos2unix.bin
https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/intel-edison/named.bin
https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/intel-edison/rndc-confgen.bin
https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/intel-edison/rndc.bin

**Comment by dwoodard1** [comment]
@ctron I will create a PR removing these files. We don't support the "networking" version of the Intel Edison. This is likely legacy stuff that was never cleaned up.

**Comment by dwoodard1** [comment]
@cdealti We don't currently distribute the "networking" version of the Intel Edison installer. Should we remove this profile entirely?

**Comment by cdealti** [comment]
I agree on removing the profile and the files.

**Comment by dwoodard1** [comment]
Created PR #1432

**Comment by ctron** [comment]
Removing the profile from the current git repository state may not be enough. Please check with EMO if you need to remove the files from the Git history and the downloadable artifacts from download.eclipse.org.

**Comment by dwoodard1** [comment]
@ctron I have removed the downloads from the Eclipse server and the profile/files have been removed from the repo. Are we good to close?

**Comment by ctron** [comment]
Do you have any response from EMO regarding the repository?

**Comment by dwoodard1** [comment]
@ctron EMO approved the actions we have taken as sufficient. No need to purge the repo history. Can we close?

**Comment by cdealti** [comment]
@ctron can we close?

**Comment by ctron** [comment]
Sorry. Yes you can. I saw the reply.
