### ISSUE TITLE
New BLE beacon/advertisement API

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1447]
* Receive raw advertisement packets
* Broadcast raw advertisement packets
* Utilities to encode/decode popular beacon formats. We will initially provide the iBeacon encoder/decoder. Note that is not an OSGi service.

**Comment by pierantoniomerlino** [comment]
Implemented the iBeacon and Eddystone encoder/decoder. Eddystone supports only UID and URL packet formats.

**Comment by pierantoniomerlino** [comment]
@cdealti please review #1528

**Comment by MMaiero** [comment]
Can this be closed? @pierantoniomerlino

**Comment by pierantoniomerlino** [comment]
Yes!
