### ISSUE TITLE
Travis-CI build timeouts

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1465]
* @MMaiero  Reduce the number of permutations in the _web2_ project via a system property (_.travis.yml_)
* @MMaiero Build only a single _distrib_ profile (_.travis.yml_)
* @markoer  optimize _tests/org.eclipse.kura.core.test_

**Comment by ctron** [comment]
I would suggest to investigate Travis build pipelines in order to work around this limitation.

**Comment by cdealti** [comment]
@ctron good idea

**Comment by MMaiero** [comment]
https://docs.travis-ci.com/user/build-stages/

**Comment by markoer** [comment]
The problem is that documentation states the jobs don't share persistence:
https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs

**Comment by MMaiero** [comment]
Closing as the basic points were merged with the 2 PR. Opened #1479 to investigate the possibility to have build-stages.
