### ISSUE TITLE
[Web UI] Create screenshots of new web UI

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#147]

**Comment by cdealti** [comment]
Screenshots have been asked on the Kura mailing list.

**Comment by dwoodard1** [comment]
I believe @MMaiero  has already done this and posted to the mail list. Can this be closed?

**Comment by MMaiero** [comment]
Yes, if they are enough, I think it can be closed

**Comment by kartben** [comment]
I guess at some point all the screenshots in the documentation will need to
be updated though (or maybe at least add somewhere a warning to indicate
that the documentation may feature screenshots from an old version of Kura)

**Comment by pierrepitiot** [comment]
@dwoodard1, I updated all the screenshots in the rev 4.0 documentation if you have time to take a look

**Comment by cdealti** [comment]
@pierrepitiot we are talking about the Kura documentation here. Can you update the screenshots of the Kura documentation?

**Comment by pierrepitiot** [comment]
As soon as Kura 2.0 will be released I'll update the screenshots in the documentation.

**Comment by MMaiero** [comment]
@pierrepitiot Maybe we can also update this image with the new webUI: http://eclipse.github.io/kura/doc/intro.html

@hekonsek Could you please update the Kura screenshot [here](http://eclipse.github.io/kura/doc/kura-camel.html) with the new web UI? Maybe It's also better to remove the Everyware cloud console screenshot.

**Comment by pierrepitiot** [comment]
Intro.html has been updated.

**Comment by dwoodard1** [comment]
@MMaiero @pierrepitiot Can we close this?

**Comment by MMaiero** [comment]
@dwoodard1 We have updated our part. We are waiting for the screenshot updates for the Camel part.

**Comment by MMaiero** [comment]
I think this can be closed since also the Camel page has been updated.
