### ISSUE TITLE
[QA] Add rate limit checks

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1474]
@markoer See #1416.

Add the following checks to the QA spreadsheet:

Scenario: slow publishing app is not affected by rate limit
* Configure device to connect to EC
* Make sure rate limit is enabled, average is 1 msg/s and burst size is 10 msg/s
* Install publisher application and configure it to publish 1 msg/s with QoS = 0
* In kura.log check the actual publish rate is 1 msg/s
* Check the actual publish rate is not affected changing the rate limit average to 10 msg/s
* Check the actual publish rate is not affected changing the rate limit burts size to minimum
* Check the actual publish rate is not affected disabling rate limit

Scenario: fast publishing app is rate limited. Rate limit does not interfere with lifecycle messages and device management.
* Disconnect the CloudService from the Web UI
* On EC delete the device (if it already exists)
* Make sure rate limit is enabled, average is 1 msg/s and burst size is 10 msg/s
* Configure publisher application to publish at 10 msg/s with QoS = 0
* Wait until the DataService db store capacity is exceeded (check kura.log)
* Login to EC (session may have timed out). In rapid sequence do:
* Connect the CloudService from the Web UI
* On EC, select the device and check:
  * The Device status is green (connected)
  * Device Profile contains correct information
  * All Tabs are enabled (none grayed-out)
  * Try getting device configuration
* Check in kura.log that the actual publish rate does not exceed the configured rate limit average (1 mgs/s with default settings).
* Also check the initial message burst did not exceed the configured rate limit burst. In the log you will continue seeing db store capacity exceeded warnings

Scenario: Rate limit does not interfere with publish of lifecycle messages
* Make sure the DataService db store capacity is exceeded (check kura.log) 
* Manually disconnect the CloudService from the Web UI
* On EC check the device status. It must be yellow (device disconnected)
* On EC delete the device
* Unplug the Ethernet cable
* Manually connect the CloudService from the Web UI
* Check the reconnect attempts in the kura.log file. Wait a few minutes
* Replug cable and repeat above checks

Scenario: Disconnect Certificate is sent on OS shutdown when rate limit is enabled
* Make sure the DataService db store capacity is exceeded (check kura.log)
* Shutdown the OS
* On EC check the device status. It must be yellow (device disconnected)

**Comment by cdealti** [comment]
@MMaiero please add what you think is needed

**Comment by MMaiero** [comment]
Scenario n.2:

- We must specify to use the example publisher, since it is the only example we have that goes so fast.
- I don't think we need to disconnect the device to reach the maximum number of messages in datastore, since we are creating 10 messages/s and pushing at 1 message/s.
- We must keep in mind that the cloud side should display based on server-side timestamp. For example, now in our test environment, we have device-side timestamp.

**Comment by MMaiero** [comment]
Scenario 1:
I'm not sure about this test: `Check the actual publish rate is not affected changing the rate limit average to 10 msg/s` since the messages are created at a rate of 1 per second and published at the same rate, changing to a bigger publishing rate should not have effect in any case, since there are no messages waiting to be pushed.

**Comment by MMaiero** [comment]
Scenario 3:
I believe that for Kura target devices unplugging the ethernet is a little bit problematic since, for example, the raspberry pi 2 has only one ethernet and no wifi.
Maybe a possibility is to change the eth0 config setting it from WAN to LAN in order to cause, more or less, the same effect.

**Comment by MMaiero** [comment]
On Scenario 3, maybe it could be done with the same effect disconnecting the cloud service, installing a publishing application and leaving it for some time, then connect the cloud service and see that all the lifecycle messages are published first and then that the data messages are published immediately for the first 10 and then the remaining at a rate of 1 message per second.

**Comment by MMaiero** [comment]
I would add the following tests to test the specificities of the new feature. Maybe we can merge these proposed ones with yours.

Scenario a (test with rate limiting disabled): 
- Connect to the cloud platform;
- Disable rate limit;
- Disconnect from the cloud platform;
- Install the example publisher (it should default to 1 message per second);
- Let the example create few messages;
- Connect to the cloud platform;
- Check that all the stacked messages are immediately sent to the cloud platform and then 1 message per second is sent to the remote service.

Scenario b (test with default rate limiting configuration): 
- Disconnect from the cloud platform;
- Install the example publisher (it should default to 1 message per second);
- Let the example create few messages;
- Connect to the cloud platform;
- Check that all the lifecycle messages are immediately pushed, one data message is sent immediately and then 1 message per second is sent to the remote cloud platform.

Scenario c (test with rate limiting, bucket size of 10 messages): 
- Disconnect from the cloud platform;
- Install the example publisher (it should default to 1 message per second);
- Let the example create few messages;
- Connect to the cloud platform;
- Check that all the lifecycle messages are immediately pushed, 10 data messages are sent immediately and then 1 message per second is sent to the remote cloud platform.

Scenario d (test with rate limiting, bucket size of 10 messages, average of 10 messages per minute): 
- Disconnect from the cloud platform;
- Install the example publisher (it should default to 1 message per second);
- Let the example create few messages;
- Connect to the cloud platform;
- Check that all the lifecycle messages are immediately pushed, 10 data messages are sent immediately and only 10 messages per minute are sent to the remote cloud platform (messages should be generated by the publisher but only a limited number is sent).

**Comment by MMaiero** [comment]
@markoer Any thoughts on this?

**Comment by markoer** [comment]
I didn't comment on it here, but I am preparing the test procedures.

**Comment by markoer** [comment]
Some of the steps above are similar to what we already had in the test procedures (prepared well before the PR was merged). I rewrote them and added the suggestions from this issue. I believe most are covered, now.

* DATA-LIMIT-001
(No limiting)

Make sure only one network device is enabled for WAN e.g. eth0.
In System->Cloud Services->DataService enable connect.auto-on-startup. Set this configuration (disable rate limiting):
enable.rate.limit = false
Apply and connect to the broker.

In System->Packages install org.eclipse.kura.example.publisher.ExamplePublisher deployment package as in DEN-CONF-001.
Make sure ExamplePublisher’s rate is 1000 and QOS is 0.

Observe (in kura.log) that messages arrive (1/s) and are published immediately.

* DATA-LIMIT-002
(Slow messages)

In System->Cloud Services->DataService set
enable.rate.limit = true
rate.limit.burst.size = 1.

Observe that messages are still published immediately i.e. 1/s.

* DATA-LIMIT-003
(Slow messages)

Set rate.limit.average = 10
rate.limit.time.unit = SECONDS.

Observe that messages are still published immediately i.e. 1/s.

* DATA-LIMIT-004
(No interference with lifecycle messages and device management)

Configure rate.limit.* = 1/second, rate.limit.burst.size = 10.
Configure ExamplePublisher publish.rate = 10 (i.e. 100/s).

Wait for DataService’s DB capacity is exceeded, then set publish.rate to 100000 (1msg/100s).

Observe that remote configuration on the broker (e.g. EC) is accessible and changeable.
Observe that messages are published 1/s.

* DATA-LIMIT-005
(Burst works)

Update rate.limit.burst.size = 100.

Observe that 100 messages are sent immediately, the rest are still coming 1/s.

* DATA-LIMIT-006
(Average limiting works)

Update rate.limit.average = 10.

Observe that 10 msg/s are published until the queue is empty. After that 1 msg every 100 s is published.

* DATA-LIMIT-007
(No interference with lifecycle messages and device management)

Make sure that DB capacity is exceeded by setting
ExamplePublisher publish.rate = 10
DataService rate.limit.average = 1.

Connect to the broker (e.g. EC).
Observe that the device is connected.
Update ExamplePublisher publish.rate = 10000 on the broker and observe that the publishing actually slows down.

* DATA-LIMIT-008
(No interference with lifecycle messages and device management)

Make sure that DB capacity is exceeded by setting
ExamplePublisher publish.rate = 10
DataService rate.limit.average = 1.

Enable WiFi interface on gateway and connect to Kura via wlan IP.

Connect to the broker (e.g. EC).
Observe that the device is connected.
Disconnect the device (change eth0 WAN->LAN), maybe also disconnect the network cable.
Wait until the device is disconnected.
Connect the device (change eth0 LAN->WAN)..
Observe that the device is connected ’immediately’.

* DATA-LIMIT-009
(No interference with lifecycle messages and device management)

Shutdown the device and observe that it ’immediately’ becomes disconnected on the broker.

**Comment by MMaiero** [comment]
@markoer Ok for me. Thanks
