### ISSUE TITLE
[Testing] Add H2DbService unit and integration tests

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1475]
@markoer please consider this task after #1457 is merged.

**Comment by MMaiero** [comment]
@markoer PR #1457 has been merged.

**Comment by markoer** [comment]
Thanks for info.

**Comment by cdealti** [comment]
@cdealti please review #1527

**Comment by cdealti** [comment]
@markoer #1527 has been merged. Do you plan to add specific tests for the H2DbService?

**Comment by markoer** [comment]
#1509 belongs here as well... I suppose this is what you meant, @cdealti?

**Comment by MMaiero** [comment]
I believe we can close, right?

**Comment by markoer** [comment]
I suppose so, yes.
