### ISSUE TITLE
[Question] Should the WatchdogService be enabled by default?

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1476]
With the connection monitor feature integrated, it would be better to have the watchdog service enabled by default in order that, if the user wants to enable the connection monitor, it has not to remember to enable the watchdogService as well.

I believe that a possible way to prevent the WatchdogService from kicking in if it is enabled but no components are ticking, is to use the list of registered CriticalComponents: if no CriticalComponents are registered, the watchdog should not trigger a reboot. At the other side, if one or more CriticalComponents are registered and tracked by the watchdog service, but there is no ticking, the reboot should be triggered.

**Comment by cdealti** [comment]
I vote no. Usually the watchdog is enabled only in production.

**Comment by pierrepitiot** [comment]
I tend to agree with Cristiano, I already had some cases where a wrong parameter triggers the watchdog at every reboot and in this case it is very complicated to recover the gateway, specially on a remote site.
You need to have made good testing before enabling the watchdog when you develop an application using it.

**Comment by MMaiero** [comment]
I believe that is better to keep the things as they are now. Closing.
