### ISSUE TITLE
[CQs] Build and test dependencies for Kura 3.1.0

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1478]
This is an issue for tracking all build and test dependencies for Kura 3.1.0

**Comment by MMaiero** [comment]
```
org.honton.chas : exists-maven-plugin : 0.0.3  Apache License 2.0 https://github.com/chonton/exists-maven-plugin
```
```
biz.aQute.bnd : bnd-baseline-maven-plugin : 3.4.0 : Apache 2.0
https://github.com/bndtools/bnd
```

**Comment by cdealti** [comment]
@pierantoniomerlino please edit the above comment adding CMake.

**Comment by cdealti** [comment]
@nicolatimeus please update the post above adding bnd-baseline-maven-plugin 3.4.0 (release)

**Comment by MMaiero** [comment]
`de.dentrassi.maven : osgi-dp : 0.3.0 EPL https://github.com/ctron/osgi-dp`

**Comment by markoer** [comment]
bundle: com.codahale.metrics.core
mvn:
`io.dropwizard.metrics : metrics-core : 3.2.2 : Apache License 2.0 : https://github.com/dropwizard/metrics`

**Comment by dwoodard1** [comment]
@MMaiero @cdealti @markoer I would like to file the CQ for build and test dependencies today (or tomorrow at the latest). Is the below four all we need? If not, please add what is needed. If so, please give a +1 as soon as you can.

org.honton.chas : exists-maven-plugin : 0.0.3
biz.aQute.bnd : bnd-baseline-maven-plugin : 3.4.0
de.dentrassi.maven : osgi-dp : 0.3.0
io.dropwizard.metrics : metrics-core : 3.2.2

**Comment by dwoodard1** [comment]
Created: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14155

**Comment by dwoodard1** [comment]
@markoer Can you please respond to this question from the Eclipse PMC:

"our of curiosity: In what way are you guys using io.dropwizard.metrics so that
it is just a test and/or build dependency that is not relevant during runtime?"

**Comment by markoer** [comment]
It is needed for the OPC-UA driver provider tests. The implementation bundle only uses the Milo client libraries, while the tests use the server part as well. This way the driver can connect to the server and interact with it. And it seems that the client part doesn't use the library in question, so it was not necessary before.

**Comment by ctron** [comment]
But you so know that you don't need a CQ if this is only a transient dependency of another Eclipse project.

**Comment by MMaiero** [comment]
I believe this can be closed. @dwoodard1
