### ISSUE TITLE
Wiki Eclipse pages

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1486]
I believe Eclipse's Wiki pages for Kura (like [1]) should simply refer to the official documentation we provide in Github: in my opinion, it's currently difficult to keep all those references aligned and such change would simplify the updates.

[1] https://wiki.eclipse.org/Kura/Getting_Started

**Comment by MMaiero** [comment]
What do you think @dwoodard1 ?

**Comment by dwoodard1** [comment]
@MMaiero Yes, I completely agree. Ideally there are a couple of steps here:

1. All documentation on https://wiki.eclipse.org/Kura gets moved to Github Wiki pages. Any existing pages on the Eclipse Wiki should point users to Github Wiki
2. Any Wiki entry that is duplicate information of what we have in documentation should be replaced in the Wiki with a link to the proper documentation

Make sense?

**Comment by MMaiero** [comment]
I agree.
Why don't we have a look at the wiki.eclipse.org pages and start open issues to track the porting/modification?
