### ISSUE TITLE
DbDataStore question

### ISSUE THREAD

**Issue by atmanuel** [eclipse/kura#1487]
Regarding the DbDataStore class, I might be missing some details, but does it make sense to set the purge age proportional to the database occupation?
I mean something like(or smarter than)  "purgeAge *= (100 - ((100 * getMessageCount) / this.m_capacity))" in order to do not achieve the "KuraStoreCapacityReachedException" exception.
Another approach could be, while the store capacity limit is reached it might work as a fifo by removing the oldest message and storing the new one, instead of dropping the new messages.
Any suggestion/comment?

**Comment by cdealti** [comment]
@atmanuel I agree that the current implementation may be questionable. We will consider your suggestions when we will redesign the implementation.

**Comment by atmanuel** [comment]
ok, it is just a suggestion...  (I was inspecting a bit the source code to understand why it was reaching the storage limit in high message rate scenarios)

**Comment by cdealti** [comment]
No need to close it. Let's keep it open as a discussion item
