### ISSUE TITLE
message publisher question

### ISSUE THREAD

**Issue by atmanuel** [eclipse/kura#1488]
Regarding DataServiceImpl (@submitPublishingWork), does it make sense to do not limit the "in flight messages" to such low maximum((MAX_IN_FLIGHT_MSGS_PROP_NAME)?  It might be configurable to a much higher number(currently 10 from GUI), even to a best effort parameter just to send the stored messages (and get profit when running in fast cpus).

**Comment by cdealti** [comment]
@atmanuel ten inflight messages was (still is?) the maximum number Paho was able to handle. We further limit this to be able to publish higher priority messages.

**Comment by atmanuel** [comment]
ok, understood...didn't know about such limitation.
Thank you.
