### ISSUE TITLE
Kura v2.0.0 Release

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#149]
- [x] Release new web UI
- [x] Enhanced Camel integration
- [x] Multitons Support
- [x] Connection to multiple Cloud Platforms
- [x] Drag & Drop of apps from Eclipse Marketplace
- [x] Archetypes for Kura setup
- [x] Support for WiFi multi mode on supported modules

**Comment by cdealti** [comment]
@dwoodard1 
* **Enhanced Camel integration** most of the code has been already committed by Henryk on the develop branch. We still need to migrate an example (the author is Henryk) from the RHIOT project (see #198)

* **Multitons Support** the PR #194  will be corrected and merged tomorrow

* **Connection to multiple Cloud Platforms** a new PR will be created tomorrow and merged to develop

* **Drag & Drop of apps from Eclipse Marketplace** can we assume this will not impact the release review?

* **Archetypes for Kura setup** the PR #223 has been merged to develop

**Comment by cdealti** [comment]
@dwoodard1 ready to go
