### ISSUE TITLE
Verify compatibility of the old Bluetooth implementation with Bluez 5.43 

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1517]

**Comment by pierantoniomerlino** [comment]
Tested with
- org.eclipse.kura.example.ble.sensortag
- org.eclipse.kura.example.beacon
- org.eclipse.kura.example.beacon.scanner

**Comment by MMaiero** [comment]
@pierantoniomerlino Can this be closed?

**Comment by pierantoniomerlino** [comment]
Yes!
