### ISSUE TITLE
Enable connections to multiple Cloud platforms

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#152]

**Comment by cdealti** [comment]
Currently Kura only allows a single Cloud connection at a time (i.e. a single MQtt connection).
The typical Kura app depends, often as a Declarative Service, on the ``CloudService`` to publish and subscribe to MQtt topics.
The ``CloudService`` is a singleton and uses the ``DataService`` (in turn a singleton) to connect to the Cloud through the ``DataTransport`` (another singleton). Their current implementations are ``ConfigurableComponents`` each with its own configuration.

This design does not allow a scenario where a Cloud connection is used for device management, for example to remotely manage the configuration of a ``ConfigurableComponent``, while another connection is used to push telemetry data to a data store.

Another rationale for this story is that the current ``CloudService`` implementation publishes Cloud-specific life-cycle messages (e.g. the Birth, and Disconnect certificates) and subscribes to specific control topics. These messages might not be meaningful for other Clouds which may require other protocols.

The constraints for this user story are:
* Backward compatibility API changes to the ``CloudService``. Accordingly to Semantic Versioning the version of the ``org.eclipse.kura.cloud`` package will change in the minor number. API consumers (apps) will not be affected by the change. API implementors following Semantic Versioning must be updated.
* Backward compatibility API changes to the ``DataService`` and the ``DataTransport``. They are seldom directly used by apps but are in the Kura API.
* Kura has support for remote software updates. Commercially supported products based on Kura have the ability of upgrading Kura without requiring changes to apps.
* Existing apps are typically implemented as Declarative Services and assume that the ``CloudService``,  ``DataService`` and ``DataTransport`` are singletons. They assume a single Cloud connection (or simply don't care about it).  Upgrading Kura to enable multiple Cloud connections must happen in a way that guarantees that some special apps (for example the ``Cloudlet``S) will continue using the right connection. More explicitly, after a remote upgrade, a ``Cloudlet`` app which allows to remotely manage the device MUST still use the previous connection, without requiring manual intervention to reconfigure anything or updating the app itself.

**Comment by MMaiero** [comment]
@cdealti I think we should document this in Kura site reporting how to create a new stack (programmatically until we modify the web UI).

**Comment by cdealti** [comment]
Please see the Kura [Wiki](https://github.com/eclipse/kura/wiki/Multiple-Cloud-Connections).
