### ISSUE TITLE
QA tests for the connectivity monitor of the DataServiceImpl

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1526]
@markoer can you draft QA tests and **do a preliminary check**?
This has high priority.

See #1138 

- [ ] When enabled and properly configured it should cause a system reboot (via the Watchdog Service) **only**  if the DataService cannot connect to the broker for any reason but those described in [1] section **3.2.2.3 Connect Return code**. For example unplugging the Ethernet cable should cause a reboot but connecting with a bad username or password should not.

- [ ] Verify if changing the **connect.retry-interval** parameter could cause spurious reboots

- [ ] Use your imagination to try to cause spurious reboots

[1] http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html

**Comment by markoer** [comment]
Currently I have the cases below.
**Bad username** currently causes a **reboot**.

* DATA-CRIT-001 (disconnect)

Prepare the following setup.
System->Network:
Disable all network interfaces except lo, eth0 and wlan0.
Setup eth0 as Enabled for WAN.
Setup wlan0 as Enabled for LAN and access point with a 'DHCP and NAT', 'Pass DNS Servers through DHCP' = false.

System->Cloud Services->DataService:
connect.auto-on-startup = true
connect.retry-interval = 60
enable.recovery.on.connection.failure = true
connection.recovery.max.failures = 3
Make sure device connects to the broker.

Enable Watchdog service:
Services->WatchdogService:
Watchdog enable = true

Connect to Kura through wlan0.
Observe the log: tail -f /var/log/kura.log

Disconnect the network cable. Make sure device cannot ping the outside network.

There will be messages that the eth0 interface is down and later that the client connection was lost. 3 reconnect attempts will be made. After the last one times out, there will be a warning message that connection failed, info 'Maximum number of connection attempts reached. Requested reboot' and in the end a Watchdog service's warning: 'Critical service DataServiceImpl failed -> SYSTEM REBOOT'.

After this the device should reboot.

* DATA-CRIT-002 (invalid credentials)

Prepare the same setup as DATA-CRIT-001.

Change the MQTT transport's username to an invalid one:
System->Cloud Services->MqttDataTransport:
username = &lt;invalid user>

Apply and observe the log.

After 3 attempts a reboot will be requested with similar log messages as before.

**Comment by MMaiero** [comment]
Yes, currently that requirement is not implemented: I will provide a fix for that

**Comment by markoer** [comment]
A few new cases:

* DATA-CRIT-003 (invalid hostname)

Prepare the same setup as DATA-CRIT-001.

Change the MQTT transport's broker to an invalid one:
System->Cloud Services->MqttDataTransport:
broker-url = "mqtt://<nonexistinghost>:1883"

Apply and observe the log.

After 3 attempts a reboot should be requested, and produce similar log messages as before (UnknownHostException should be visible in the log).

* DATA-CRIT-004 (connection refused)

Prepare the same setup as DATA-CRIT-001.

Change the MQTT transport's host to localhost, but with a closed port (make sure there's no server running on that port):
System->Cloud Services->MqttDataTransport:
broker-url = "mqtt://localhost:1883"

Apply and observe the log.

After 3 attempts a reboot should be requested, and produce similar log messages as before (Connection refused should be visible in the log).

* DATA-CRIT-005 (reconfiguration)

Prepare the same (invalid) setup as DATA-CRIT-003 or DATA-CRIT-004.

Apply and observe the log.

Wait for 2 connection attempts to be made, then update the configuration to some other invalid option.
Repeat the step above and observe that reboot is not requested even after 4 retries (connection attempts are reset at reconfiguration).

After 3 attempts (5 altogether) a reboot should be requested, and produce similar log messages as before (Connection refused should be visible in the log).

* DATA-CRIT-006 (period=0)

Prepare the same setup as DATA-CRIT-001.

Update System->Cloud Services->DataService:
connect.retry-interval = 0

Disconnect eth0 cable.

Device should reboot fast, but what then? Likely the constant rebooting was not planned.

**Comment by cdealti** [comment]
@MMaiero please review #1534
@markoer please review #1532

**Comment by markoer** [comment]
#1532 reviewed and approved 17. 7. 2017 11:55.
