### ISSUE TITLE
OSGI console is not redirected to Eclipse IDE with Kura 3.0

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1529]
Using Kura 3.0.0 and Eclipse IDE (Neon or Oxygen) with mToolkit, the OSGI console is not redirected to the Eclipse console.

To replicate the issue, proceed as follows:
- Start Kura 3.0 in debug mode;
- Connect to Kura from Eclipse IDE using mToolkit;
- The connection will succeed and all bundles will be listed under the Framework tab;
- Select the Console tab: the ```Failed to redirect framework output: ``` message will be displayed and it is not possible to interact with the OSGI console on the device.

**Comment by cdealti** [comment]
In Kura 3.0.0 we switched to Equinox 3.11.1. I assume this has broken the OSGi console redirect. Unfortunately mToolkit is no longer officially maintained.

In the past Eurotech fixed the IDE plugin [1] for Eclipse Neon [1].

[1] https://github.com/eurotech/mtoolkit

**Comment by ctron** [comment]
It may be useful to switch to something standard based like OSGi remote management.

**Comment by cdealti** [comment]
In the meantime, let's fix it again
