### ISSUE TITLE
Add JAX-RS to target platform

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#153]
Adding JAX-RS to target platform will allow creation of REST APIs to Kura services.

**Comment by hekonsek** [comment]
So do plan to have a REST API for all Kura services exposed on the device?

**Comment by dwoodard1** [comment]
Not for now. In the short term we want to include JAX-RS to enable the ability to add REST endpoints as needed in Kura. We will provide examples on how to do this. If anyone is interested in contributing a more robust/secure solution, we would be happy to help with the effort.

**Comment by EndruBoy** [comment]
Hello,
can I ask what's the status of this feature? I plan to deploy a bundle with a simple REST API to Kura but still investigating if it's possible.

**Comment by ctron** [comment]
I think we could go two ways. I know that the whole JAX-RS stack with swagger and the "hstaudacher" implementation is approved by the Eclipse Foundation. So we could just add that.

Or we could leverage some functionality from Karaf.

**Comment by dwoodard1** [comment]
We have had some promising results using the OSGi JAX-RS Connector [1]. It is very easy to use and is licensed EPL. I don't know that it needs to be in the core of Kura, but it would be easy to distribute as an "add on". Thoughts?

[1] https://github.com/hstaudacher/osgi-jax-rs-connector
