### ISSUE TITLE
Modify the wire composer to allow driver management

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1530]
According to what designed in https://github.com/eclipse/kura/wiki/Assets-and-Driver-Web-Ui-section-mockups the Wire composer should be updated to be able to manage the creation of a Driver directly from inside the composer.
The scope is to allow the user to manage and/or design a graph completely from the composer page, without the need to go out of it.

A first draft is available at the following link: https://github.com/MMaiero/kura/tree/enh_drivers-assets-refactor

**Comment by MMaiero** [comment]
Attached few screenshots of the new prototyped design.

The configuration tab for a generic Wire component:
![Schermata 2017-07-14 alle 14.36.42.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/f7ebcd01-7826-4b94-a7ec-b1212824743a)


When the dropped wire component is an Asset, the configuration tabs are 2: one for the asset configuration with the usual channels, the other for the related Driver instance that allows to manage the driver configuration.
![Schermata 2017-07-14 alle 14.40.22.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/a7472433-b5f2-4e32-8878-824191f100cd)

![Schermata 2017-07-14 alle 14.40.31.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/e75541b7-b225-4f31-980f-7d641eec4303)

New modal for the Asset creation.
![Schermata 2017-07-14 alle 15.36.49.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/b0ba7b55-516e-42c4-a2ef-0324f4d81bea)

If the + driver button is clicked, a new modal is opened and allows to define a new driver instance selecting from the proper driver factories.
![Schermata 2017-07-14 alle 15.36.55.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/d300095d-b9f8-4d11-ab34-eae65608c964)

![Schermata 2017-07-14 alle 15.37.00.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/bfca4fa5-13c9-460a-abf7-0f93a15733db)

When done, a new driver instance is created and available to be used to associate with the new asset.
![Schermata 2017-07-14 alle 15.37.11.png](https://images.zenhubusercontent.com/572701dfbf93871ccd9a576a/cc3c8d2e-090b-4b72-8a53-7fc3d9fa00e9)

**Comment by MMaiero** [comment]
Open items:
- maybe the asset configuration tab name can be differently highlighted? I'm thinking that we could have a generic title (e.g Timer - t1 or Asset - a1) and the tab name can be respectively "Configuration" and "Asset Configuration", depending if it is related to a generic Wire component or Asset component.

- The new Driver button: maybe the + is not sufficient. Maybe it is better to have it as "New Driver"

- Complete the new Driver modal validation.

- Currently, the existing Drivers are not Configurable Components

**Comment by cdealti** [comment]
* In the second screenshot **Driver Config** should be **Driver - <name>**
* In the fourth **Component Name** should be **Asset Name**
* In the fourth **Avalilable Drivers** could be just **Driver** (an instance) and...
* ...In the fifth **Avalilable Driver Factories** could just be **Driver Factory**
* The **+** button I believe we both don't like it
* Last screenshot: it allows you to click **+** again and create a new Driver. Is the old one deleted?

Instead of having the **+** button we could add a third "New Driver" button close to the "Cancel" and "Apply" one which lead you to the Driver creation dialog. There you only have the option to cancel or apply everything (driver + asset creation).

**Comment by MMaiero** [comment]
> In the second screenshot Driver Config should be Driver -

Agreed.

> In the fourth Component Name should be Asset Name
> In the fourth Available Drivers could be just Driver (an instance) and...
> ...In the fifth Available Driver Factories could just be Driver Factory

ok.

> The + button I believe we both don't like it

Yes, as written, I don't like it too.

> Last screenshot: it allows you to click + again and create a new Driver. Is the old one deleted?

The old one is not deleted, because it is created when saving the new driver modal.

> Instead of having the + button we could add a third "New Driver" button close to the "Cancel" and "Apply" one which lead you to the Driver creation dialog. There you only have the option to cancel or apply everything (driver + asset creation).

Uhm, I believe it would be confusing for people: we don't have it in this way all around the ui. What is more, is that you need the asset name to complete the procedure, other than selecting the driver instance. The new driver button would need a pre-requisite of specifying a name for the asset. But that would be confusing with the fact that you have not completed the form by selecting something in the driver drop down.
I believe that having a "new driver" button is the best option. If the user decides that the just created driver is not ok he can simply decide to select another instance or create a new instance.

**Comment by MMaiero** [comment]
Changes applied, squashed commits.
The modals for a new asset and driver now have a header that allows to understand what is going on. Improved paddings.

**Comment by MMaiero** [comment]
Closing due to #1552 merge
