### ISSUE TITLE
Create "Drivers and Assets" tab 

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1531]
Taking as a reference the wiki page https://github.com/eclipse/kura/wiki/Assets-and-Driver-Web-Ui-section-mockups , the proposal 4 should be implemented. This new page in Kura Web UI should allow the tracking of all the Assets and Drivers as described in the wiki page.

Eventually, this issue will be splitted in multiple issues, if needed.

**Comment by cdealti** [comment]
@MMaiero I believe this can be closed. Are there any remaining tasks?
