### ISSUE TITLE
Create blog posts for Multitons

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#155]
Blog post should explain what Multions are, the services exposed, and highlight that multitons are persisted across restarts.

**Comment by cdealti** [comment]
Multitons was only an internal nickname here. It does not match the Wikipedia definition.
The concept is actually implemented as "Multiple configurations of a component (declarative service).
It has been used to support the Multiple Connection Feature added by Kura 2.0.0. There is a Wiki page so I believe we can close this.
