### ISSUE TITLE
[Testing] Provide EthernetMonitorServiceImpl unit tests

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1554]
Provide org.eclipse.kura.net.admin.monitor.EthernetMonitorServiceImpl unit tests.

Part of #1547.

**Comment by cdealti** [comment]
@ibinshtok please always close the issue associated to the PR you are merging. You can filter by "Assignee" to see if you are mentioned as an co-assignee

**Comment by ibinshtok** [comment]
Closing this issue associated with PR#1560
