### ISSUE TITLE
connect.retry-interval=0 causes DataService activation failure

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1556]
Setting the `connect.retry-interval` to 0 seems to work until reboot.
After a reboot, the DataService component starts continuously to try to activate, determining the impossibility to use the default cloud service and all the related stack.
I believe the root cause is related to the `IllegalArgumentException` thrown by the [scheduleAtFixedRate](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate(java.lang.Runnable,%20long,%20long,%20java.util.concurrent.TimeUnit)) .

This determines that the `startConnectionMonitorTask` method throws that runtime exception till going up in the stack-trace at the `activate` level. This causes the component to continuously be restarted by the framework.

I've tested the same behaviour in Kura 3.1.0-SNAPSHOT and Kura 3.0.0. I've not done tests for previous versions of Kura.

**Comment by cdealti** [comment]
@pierrepitiot can you please review the associated PR #1557?

**Comment by pierrepitiot** [comment]
Ok, I'll take a look soon.
