### ISSUE TITLE
CommandCloudApp doesn't use received working directory parameter

### ISSUE THREAD

**Issue by diegovisentin** [eclipse/kura#1558]
Hi,
In Kura v2, you could send to CommandCloudApp a request with a specific working directory (see `KuraCommandRequestPayload.setWorkingDir()` ).
How can I do the same in Kura v3?

Regards, Diego

**Comment by cdealti** [comment]
Hello Diego.
The setter is still there [1]. Do I miss something obvious?

[1] https://github.com/eclipse/kura/blob/KURA_3.0.0_RELEASE/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/KuraCommandRequestPayload.java

**Comment by diegovisentin** [comment]
My issue is that "workingDir" attribute of KuraCommandRequestPayload seems no more used by CommandCloudApp.

**Comment by cdealti** [comment]
Hi,
 It looks like we haven't changed this recently and the provided working directory is still used by CommandCloudApp. Can you provide a test case or a detailed description on how you use it?

**Comment by diegovisentin** [comment]
In the current version of CommandCloudApp [1] there isn't a single call of `KuraCommandRequestPayload.getWorkingDir()`. Instead all commands are executed in the working-directory specified in component properties or using the system temp directory (this logic is made by the method `CommandCloudApp.getDefaultWorkDir()`).
Therefore if I send a command that specify a working-directory, this information is simply not used by CommandCloudApp.

NB: in old versions of CommandCloudApp there was the method `getDir()` that used the received metric for executing command in requested working-directory; from some point in time this method was commented and then removed from the code.

[1]
[https://github.com/eclipse/kura/blob/KURA_3.0.0_RELEASE/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java](https://github.com/eclipse/kura/blob/KURA_3.0.0_RELEASE/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java)

**Comment by cdealti** [comment]
It happened [here](https://github.com/eclipse/kura/commit/1c577d8be41dee4d0394fb66bc0cbe79ec528693) when we added the bits for Windows support. I need to figure out why we did this.

**Comment by cdealti** [comment]
@malikm do you remember why you changed [this](https://github.com/eclipse/kura/commit/1c577d8be41dee4d0394fb66bc0cbe79ec528693#diff-626b7f4b19decd7a93b5c44558818271R191)?

**Comment by malikm** [comment]
@cdealti If I recall right, on Windows we were getting null default working directory, so this was to provide a correct temp path in this case.

**Comment by diegovisentin** [comment]
Is there any possibility that this bug will be fixed for version 3.1?
