### ISSUE TITLE
[Wires] Create blog post for Kura Wires

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#156]
The blog post should include:

Simple Flow
- Converting heater demo to wire emitter
- Show how to instantiate CloudPublisher wire receiver
- Show how to create a wire between heater and publisher

Complex Flow
- Show how to instantiate DbWireRecordStore
- Show how to instantiate DbWireRecordFilter
- Show how to instantiate Timer
- Create wire between heater and record store
- Create flow between timer, record filter, and publisher

**Comment by cdealti** [comment]
The Kura Wires announcement has been posted: 

1. https://dzone.com/articles/kura-wires
2. http://blog.amitinside.com/Industry-4-with-Kura

**Comment by amitjoy** [comment]
Overview on Kura Wires:

https://dzone.com/articles/kura-wires-a-different-perspective-to-develop-iiot
http://blog.amitinside.com/Kura-Wires-bits-and-pieces/

**Comment by amitjoy** [comment]
Comparing Kura Wires with Notable Dataflow Programming Frameworks:

https://dzone.com/articles/different-dataflow-programming-approaches-and-comp
http://blog.amitinside.com/Different-Dataflow-Programming-Approaches/

**Comment by cdealti** [comment]
@LucaDazi @amitjoy Can we close this issue?

**Comment by amitjoy** [comment]
@cdealti I believe we can but we still can create other issues to create blog posts on Kura Wires usage.

**Comment by kartben** [comment]
I think the point mentioned in the initial ticket are still very valid. It would be great to have at least one blog post in the form of a mini tutorial about how to effectively use Kura Wires :)

**Comment by amitjoy** [comment]
These are the relevant blog posts to show a sneak peek on the Kura Wires UI.

https://dzone.com/articles/kura-wires-a-sneak-peek
http://blog.amitinside.com/Kura-Wires-First-Look/

**Comment by MMaiero** [comment]
@amitjoy Do you think we can close this?

**Comment by amitjoy** [comment]
Yeah We can
