### ISSUE TITLE
kura and Azure IoT Hub cloud platform

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#1570]
Hello,
I want to connect raspberry with Azure IoT hub,but it is not easy.

I get my IotHub certificate, after pasting them in to the “Server SSL Certificate” tab under “Settings” in Kura  in form : 
Storage Alias: azure-ssl
Certificate:
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

and after clicking the Apply button, I have this Error:

Thu Jul 27 19:10:28 GMT+100 2017 ErrorLogger INFO: : ILLEGAL_ARGUMENTorg.eclipse.kura.web.shared.GwtKuraException: ILLEGAL_ARGUMENT
   at Unknown.tg(denali-0.js)
   at Unknown.Bg(denali-0.js)
   at Unknown.Sfc(denali-0.js)
   at Unknown.Xfc(denali-0.js)
   at Unknown.hdb(denali-0.js)
   at Unknown.ddb(denali-0.js)
   at Unknown.Bbb(denali-0.js)
   at Unknown.jcb(denali-0.js)
   at Unknown.sr(denali-0.js)
   at Unknown.Gr(denali-0.js)
   at Unknown.eval(denali-0.js)
   at Unknown.Ch(denali-0.js)
   at Unknown.Fh(denali-0.js)
   at Unknown.eval(denali-0.js)

I use this manual : https://eclipse.github.io/kura/cloud/kura-azure.html.
has Someone  an idea,What should I do to fix these errors?

Thanks in advance

**Comment by dwoodard1** [comment]
@cdealti Does anyone on your side have access to Azure in order to test this?

**Comment by cdealti** [comment]
@marentwickler are you using Kura 3.0.0?
@pierantoniomerlino can you please assist?

**Comment by pierantoniomerlino** [comment]
@marentwickler it seems to me an issue related to the certificates rather than to the connection to Azure. Is it possible to see the kura.log and kura-console.log?

**Comment by marentwickler** [comment]
hello,
@cdealti yes, I use kura 3.0.0

**Comment by marentwickler** [comment]
hello,
@cdealti,
@pierantoniomerlino,
@dwoodard1
Later I got the connection with Azure Hub  without certificates step,I  have jumped step:
Storage Alias: azure-ssl
Certificate:
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

But I have to change each time the password({device_SAS_token}),And this is not a good solution.

thanks in advance

**Comment by pierantoniomerlino** [comment]
@marentwickler The SAS token will expire in 1 hour by default, but using the "iothub-explorer" command with "-d" option it is possible to set a custom expiration time.

**Comment by marentwickler** [comment]
What is with certificates? What role do they have? I got the connection with Azure Hub without certificates step.

**Comment by pierantoniomerlino** [comment]
@marentwickler The certificates are used to trust the Azure IoTHub. You were able to connect to Azure without the certification step because probably they are already in your keystore. This explains also the error you got during the certificate installation.
