### ISSUE TITLE
Fix Lint issues in the net packages of the org.eclipse.kura.api

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1577]
Fix Lint issues in the following packages:
org.eclipse.kura.net
org.eclipse.kura.net.dhcp
org.eclipse.kura.net.dns
org.eclipse.kura.net.firewall
org.eclipse.kura.net.modem
org.eclipse.kura.net.route
org.eclipse.kura.net.wifi

**Comment by cdealti** [comment]
@ibinshtok please make sure you read the Wiki on Semantic Versioning [1] before starting.
However, the bnd-baseline-maven-plugin will help you and will cause the build to fail if you cause breaking changes. 

[1] https://github.com/eclipse/kura/wiki/Kura-Semantic-Versioning

**Comment by MMaiero** [comment]
@ibinshtok Any updates on this task?
