### ISSUE TITLE
[Messaging] Share cloud connection with external applications

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1585]
`CloudCat` (name mutuated from _netcat_, _socat_ etc). Copies **cloud application messages** from one `CloudClient` to another, on two distinct `CloudService`S.

Only the application part of the full topic is preserved, the remaining parts are completed accordingly to the CloudService configurations.
The KuraPayload and the QoS of the received message are copied unmodified.

Each CloudClient can be configured to subscribe to a list of application topics.
This is only needed if a CloudService is configured to disable the default subscriptions or if custom subscriptions are needed.

The typical use case is to share the connection to a cloud platform with an external application.

The external client connects, for example over Websockets, to the Kura embedded broker, optionally subscribing to some topics (see Kura documentation).

Messages published by the external client will be delivered by the Kura embedded broker to the connected CloudClient of the CloudCat
which will copy the application topic, the payload and the QoS to the other CloudClient.

External application are likely to prefer JSON over Google protobufs as the KuraPayload encoding (see documentation).

CloudCat enables extending the Kura Remote Device Management to external applications.

**Comment by MMaiero** [comment]
Closing as #1651 has been merged
