### ISSUE TITLE
Internal error when I build the Kura project on the windows 

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/kura#1586]
Hey,
I am trying to build kura project via the Eclipse installer way
but during the building, there is some error exception, the log information as fellows:
[INFO] Computing target platform for MavenProject: org.eclipse.kura:org.eclipse.kura.api:1.3.0-SNAPSHOT @ D:\Kura\iot-kura-develop\git\kura\kura\org.eclipse.kura.api\pom.xml
[INFO] Adding repository file:/D:/Kura/iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location file:/D:/Kura/iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository/: No repository found at file:/D:/Kura/iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository. -> [Help 1]

Any advice?
Thank you in advance,

Alex

**Comment by dwoodard1** [comment]
@OrangeAlex We are aware of some issues when trying to build Kura with Windows. We strongly encourage people to use Linux or OS X. It seems you are trying a Linux VM per #1601, can we close this issue in favor of that?

**Comment by OrangeAlex** [comment]
@dwoodard1 Ok, i have accept your suggestion and construct kura with Ubuntu , so  thank you very much ,this issue can be closed , i think. ^_^
