### ISSUE TITLE
Kura 3.1.0-M1 Publish deployment packages on the Eclipse Marketplace

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1596]
- [x] S7 Driver (New!)
- [x] Javascript Wires component (New!)
- [x] OPC-UA (Updated)

**Comment by MMaiero** [comment]
Deployment packages uploaded as new entries in the Kura Marketplace. Waiting to have those new entries approved and available.

**Comment by MMaiero** [comment]
Published. Closing.
