### ISSUE TITLE
Bluetooth in emulator imrove code and documentation

### ISSUE THREAD

**Issue by andreamathis** [eclipse/kura#1597]
Hello
I tried to run the [tisensortag](https://github.com/eclipse/kura/tree/release-3.0.0/kura/examples/org.eclipse.kura.example.ble.tisensortag) example in the emulator, but it did not find my sensor tag.
After debugging I found the following issues:
1. in `org.eclipse.kura.linux.bluetooth.le.BluetoothLeScanner:191`
    `processErrorStream(String string)` was called multiple times with the string
   `"Set scan parameters failed: Operation not permitted"` while I was wondering and waiting.
   Could you please log the given string? Btw, String might be empty in successful case.
2. in the [documentation](https://eclipse.github.io/kura/dev/bluetooth-le-example.html) the `hciconfig` calls are made as root (sudo), but the emulator has no root permission. Therefore I tried the following which listed the sensor tag in my example application.
No clue if this is the proper solution, but it works for me:
```
andrea@VirtualBox:~/workspace_$ hcitool lescan
Set scan parameters failed: Operation not permitted
andrea@VirtualBox:~/workspace_$ which hcitool
/usr/local/bin/hcitool
andrea@VirtualBox:~/workspace_$ sudo setcap cap_net_raw+ep /usr/local/bin/hcitool
[sudo] password for andrea: 
andrea@VirtualBox:~/workspace_$ hcitool lescan
LE Scan ...
D0:03:4B:2E:CA:88 (unknown)
D0:03:4B:2E:CA:88 (unknown)
21:FF:4E:66:6F:F1 (unknown)
^Candrea@VirtualBox:~/workspace_$
```
3. in `org.eclipse.kura.linux.bluetooth.le.BluetoothLeScanner:203`
Maybe this is OS or bluetooth dependent, but String `"Set scan parameters failed:"` is given to `processErrorStream(...)`, according to 1.

My setup is:
Kura emulator 3.0.0 in ubuntu in virtualbox on windows

Thanks for your your support and this cool framework
Andrea

**Comment by MMaiero** [comment]
Hi,
did you try starting the eclipse instance that runs the emulator as root? Maybe that could solve.

Best regards,
Matteo

**Comment by MMaiero** [comment]
@andreamathis Any update? Did you manage to solve the issue?

**Comment by MMaiero** [comment]
Closing, since there is no update. You can reopen it at any time if needed.
