### ISSUE TITLE
How to use Kura Wires

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/kura#1623]
Hi , i have install Kura on the Raspberry Pi , meanwhile ,  i have install the OPC UA server simulator and OPC UA  Driver , however  i don not konw how to use them , where can i get more detail introduce or guild document except official web? i am very wondering to access the OPC UA device via Kura on the Raspberry Pi

**Comment by amitjoy** [comment]
@OrangeAlex The detailed documentation on Kura Wires is available online. For insight into how to use Kura Wires, please refer to the presentation videos.
