### ISSUE TITLE
Kura does not support Consistent Network Device Naming

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#1638]
The last Raspian Stretch image (Release date: 2017-08-16) [1] supports by default the Consistent Network Device Naming feature [2], [3]. Kura uses the eth0 interface as primary network interface and uses it to set up several components. If the CNDN is enabled, Kura fails to start and the webUI is not shown in the browser.

Since this new feature will become common in new distros, Kura should support it.
In the meanwhile, a simple workaround is to disable it, following this procedure:
1. edit the ```/boot/cmdline.txt```
2. add at the end of the line ```net.ifnames=0```
3. reboot the device

[1] https://www.raspberrypi.org/downloads/raspbian/
[2] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Consistent_Network_Device_Naming.html
[3] https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming

**Comment by Amar82** [comment]
Hi Pier,

nice to meet you again :) .

my scenario is my sensors use i2c to connect to kura, and kura should connect  via wifi to internet router to connect to broker in cloud.
I am trying to connect Kura ( 3.1), via wifi ( station mode) to my home router ( router is connected to Internet).  But I am not able to do so.
I am using the wifi driver of Pi3 B+, there is NO additional wifi driver.

I have following network settings:
 ethernet setting : disabled
lo setting disabled

wlan settings - 
WAN
manual ip setting : 192.168.0.7 
gateway : to local router 192.168.0.1
corresponding subnet masks & DNS addresses

but I am getting errors & broker is not getting connected.

Please suggest the settings , or what I am doing wrong.
Should I use separate wifi driver ?

**Comment by MMaiero** [comment]
@Amar82 I believe your question is not related to the issue opened by @pierantoniomerlino.
I've also seen you opened a forum issue here with the same question: https://www.eclipse.org/forums/index.php/m/1776149/#msg_1776149

I believe it's better if you don't cross post. In this way, we will not have duplication. 
Or, if needed, please open a specific issue in GitHub.

Thanks.

Best regards,
Matteo

**Comment by cdealti** [comment]
There are hardcoded "eth0", "eth1", "wlan0" and "wlan1" occurrences in the source code
