### ISSUE TITLE
How to deploy Kura deployment package with parameter

### ISSUE THREAD

**Issue by austindsouza** [eclipse/kura#1648]
Hi,

I have an use case where I need to deploy a Kura OSGI plugin from our UI to the running emulator.
And when the package starts I need to create a table in JDBC database dynamically.

My question here is 
Is it possible to pass the name of the table as a parameter in curl command and read it in the OSGI plugin so that to set the table name as passed parameter value as the table name?

To upload the package I've used curl command as given below.

curl -i -X POST --cookie "JSESSIONID=1q1ayau5xchymwhbn2vltbgm2; HttpOnly" --user admin:admin -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryPkbBNlWAKYcjXkgH" -F "uploadedFile=@/tmp/edge/hello_osgi.dp" -F "xsrfToken=58e5cc1c-3478-4794-a5b1-b1bdfb6cde02" http://localhost:8080/denali/file/deploy/upload

the package is uploaded successfully and I can see its status in Kura web UI.

Can anyone help me on this.

Thanks & Regards,
Austin

**Comment by dwoodard1** [comment]
@austindsouza Sorry for the delay, the Kura team has been busy trying to get out our latest release. Unfortunately, what you request would require an update to the upload servlet. If you feel this would be a good addition, feel free to submit a pull request and we can review it.

Alternatively, and possibly a better approach, is to use EventAdmin. The package is installed via the DeploymentAgentService, which registers an event within EventAdmin after an installation attempt. You could register a listener for these events. This would give you more insight to successful or failed installation attempts.
