### ISSUE TITLE
Bluetooth notifications do not work

### ISSUE THREAD

**Issue by DmitryChizhikov** [eclipse/kura#1657]
Due to misprint in the `org.eclipse.kura.linux.bluetooth.le.BluetoothGattImpl` class notifications do not work.
Misprint in line 416 `String x = "Notification hanlde = ";` needs to be corrected.

Also, starting from some bluez version `gatttool` uses escape sequences in output. So, the line 417 in same file (see below) works incorrectly:
`String sub = line.substring(x.length()).trim();`
It seems it should be replaced with something like this:
`String sub = line.substring(x.length() + line.indexOf(x)).trim();`
Otherwise handle id cannot be extracted correctly.

**Comment by pierantoniomerlino** [comment]
@DmitryChizhikov thank you for the suggestion, I'll take a look on that. Which version of Bluez are you using? What is the output of the command?

**Comment by DmitryChizhikov** [comment]
@pierantoniomerlino  I am using 5.46, which is the latest one. But issue appeared since version 5.40 at least.
Currently the output looks like:
`[KNotification handle = 0x004e value: 2f ff ff ff c8 03 `
Due to these extra 3 chars before `Notification handle = ` substring keeps ` = 0x004e value:... ` instead of expected `0x004e value:...` and subsequent split takes `=`, not `0x004e` as handle id.
