### ISSUE TITLE
[Wires] Check CQ status for the external javascript libraries

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#166]

**Comment by cdealti** [comment]
@dwoodard1 Can you please check IPZilla? It looks like the CQ for ``JointJs Version: 0.9.6`` has been closed due to inactivity.

**Comment by dwoodard1** [comment]
@cdealti  Yes, there was a bit of a long story to this. Whenever we are ready to move forward with JointJS, I can re-open the CQ.

**Comment by cdealti** [comment]
@dwoodard1 any updates?

**Comment by dwoodard1** [comment]
Yes, approved: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10983
