### ISSUE TITLE
Authentication Issue with Deploy V2

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1663]
Kura currently uses java.net.Authenticator to handle Basic Authentication for HTTP requests. There is a documented issue [1] in which if a successful authentication occurs, the credentials are cached, and any future authentication attempt will succeed, even if bad credentials are provided. Since the referenced bug is noted as a "won't fix", Kura should move to a different Authentication scheme. The proposed solution is to manually add the needed Basic Auth headers to the URL request. 

[1] https://bugs.openjdk.java.net/browse/JDK-4679480

**Comment by MMaiero** [comment]
@dwoodard1 Any update on this?
