### ISSUE TITLE
Some problem about Kura Development 

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/kura#1669]
hi ,  nowdays, i wonder to development my application, according to the official Document about Development(Url:https://eclipse.github.io/kura/dev/kura-setup.html), i download the Kura User Workspace archive named "user_workspace_archive_3.0.0.zip", and then i import it into my workspace at Eclipse IDE, but i found the problem:
according to the document , when i finish the project import,  i should have four projects in my workspace: org.eclipse.kura.api ,org.eclipse.kura.demo.heater ,org.eclipse.kura.emulator,target-definition.
however , when i import the project from the "user_workspace_archive_3.0.0.zip" , i have no project named "org.eclipse.kura.api", so  i think this project contains all the api for the development on kura framwork, so Does it mean that i could not do development? how to deal with it?
Any good suggestion?
Best Regards

**Comment by MMaiero** [comment]
Hi,
the Kura APIs are included in the user workspace target platform. In fact, if you apply the .target definition, the project will not return errors. So, you can still build your new projects using the Kura APIs provided by the environment.
Please refer to the [Eclipse Kura Documentation](http://eclipse.github.io/kura/) for more details and, in particular, for an overview about the existing Kura APIs, I would suggest having a look at the [Javadocs](http://download.eclipse.org/kura/docs/api/3.0.0/apidocs/).

Best regards,
Matteo
