### ISSUE TITLE
[Kura 3.1.0 QA] Rollback doesn't restore deleted services

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1700]
Encountered during a variation of DEN-SNAP-002 on Kura 3.1.0 RC b40 on RPi3.

* Add a H2DbServer service. Configure it and apply changes.
* Make sure Java listens on the configured port.
* Delete it.
* Go to System->Settings and Rollback to the previous snapshot.
* Refresh page.
* The deleted service is not in the Services list and not started (no listener on the TCP port), but probably should be
* Restart Kura.
* Service is now back.

**Comment by cdealti** [comment]
@markoer we will add this to the list of known issues.

**Comment by markoer** [comment]
OK

**Comment by markoer** [comment]
Very good. When the code is merged and build is available, I'll check it again and close.

**Comment by markoer** [comment]
Verified in 3.2.0-SNAPSHOT b1242. Closing.
