### ISSUE TITLE
[Kura 3.1.0 QA] Artemis in emulator

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1702]
Artemis bundle is not selected in the default emulator configuration in user workspace. The result is that Artemis broker service is not available there.

Kura 3.1.0 RC b40 user workspace zip on Linux

**Comment by MMaiero** [comment]
This should be solved now. Ok to close? @markoer

**Comment by markoer** [comment]
I was going to wait for the new build to verify the fix, but close it, if you wish.
