### ISSUE TITLE
[Kura 3.1.0 QA] Wires page jumping up and down

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1703]
Open wires graph in a browser window high enough that that graph and component configuration don't fit one page and narrow enough that components are listed on the right of the graph. Open configuration of one of the components and scroll a bit down so that view is not on the top of the page as shown below:

![image](https://user-images.githubusercontent.com/22816717/30955945-bd628484-a435-11e7-9bd7-48a34c112ae1.png)

Click on a different component so that its configuration is displayed.

Chrome:
The view jumps to the top of the page and then returns.

Firefox and IE:
The view jumps to the top of the page and stays there.

This result is probably more unsettling in FF and IE as the clicked component is no longer under mouse pointer after I click on it. But double jump in Chrome is also not too nice.

Kura 3.1.0 RC b40 on RPi3 with browsers on Windows

**Comment by cdealti** [comment]
@markoer we will not fix this for 3.1.0
