### ISSUE TITLE
[Kura 3.1.0 QA] TISensorTag failing read result

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1705]
Set up a TiSensorTag driver and asset and try to read its data via REST. Log contains the error as in #1704. Channel flag still reports successful read:
`[{"channelStatus":{"channelFlag":"SUCCESS"},"name":"Channel-1","valueType":"DOUBLE","value":0.0,"timestamp":1506584576691}]`

It's probably not related to REST, but is easily observed there.

Kura 3.1.0 RC b40 on RPi3

**Comment by cdealti** [comment]
@pierantoniomerlino can you please take a look?

**Comment by markoer** [comment]
Due to SensorTag update to 1.40 I cannot reproduce the particular conditions any longer. A fix is provided that theoretically produces better results. I therefore recommend to close the issue and open another if we manage to reproduce the problem.
