### ISSUE TITLE
Modem: If the Telit modem is manually turned off, kura does not attempt to turn it back on

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#171]

**Comment by MMaiero** [comment]
@ibinshtok I think this is a very old issue. And, if I remember well, it should be closed, right?

**Comment by ibinshtok** [comment]
@MMaiero I think we can close it even though it has not been fixed. The problem is that if the modem is turned off by somebody else how would Kura know that this is not a USB disconnect event?

**Comment by MMaiero** [comment]
ok.
@cdealti Do you agree on closing?

**Comment by MMaiero** [comment]
Closing. We will reopen it if needed.
