### ISSUE TITLE
Accessing the Kura logs should be possible via Web-UI

### ISSUE THREAD

**Issue by kamir** [eclipse/kura#1710]
Instead of using the tail command in the device level, it would be great to be able to access the logs within the Kura-Web-UI - maybe linked from Status-Page.

**Comment by dwoodard1** [comment]
@kamir Thanks for the feedback. You can use the command feature in the UI (Device->Command) to  tail or cat the log file. But I understand this is not a running log. If you are interested in implementing such a feature, we are always looking for contributions. Otherwise, we can add it to our backlog.

**Comment by kamir** [comment]
Thanks for the hint.

I tried to execute a command, but this ends with:

Error
INTERNAL_ERROR

I used the root password of the device and no password. Same issue in both
cases.

Regarding the implementation of such a log-view feature, I think this would
be a good point to start.
I know how to work with servlets, but it my take a while and some pointers,
because I am new to the GWT framework.

Cheers, Mirko

**Comment by dwoodard1** [comment]
Which command did you run? You must run processes that terminate cleanly, meaning you can't use things like tail -f. You can run commands like cat, tail -n 100, ifconfig, ps aux, etc.

**Comment by kamir** [comment]
I used the *cat* command, and also *ls *to see where the cmd runs.

**Comment by markoer** [comment]
Can you please try to run the commands with a full path e.g. /bin/ls, /bin/cat, /bin/pwd, etc.? You might have more success running them so.
Otherwise, which system and OS/version are you using?

**Comment by kamir** [comment]
Hello, and thanks for the hint.


I have tested it with an absolute path, but *no luck*.


OS :
- latest Raspbian + Kura 3.0.0

[image: Inline image 1]

I used the default password "kura-password" for the "kura-sys" user and
also the linux root password.

Best wishes,
Mirko





[image: cloudera] <http://cloudera.com/>
Dr. des. Mirko Kämpf
*Solution Architect*
phone: +49 176 206 35 199 <+49%20160%209668%203050>skype: kamir1604
mail: mirko@cloudera.com

Cloudera, Inc. <http://cloudera.com/>
1001 Page Mill Road
Building 2
Palo Alto, CA 94304

**Comment by MMaiero** [comment]
Hi,
did you specify a password in the "Command Service"?
If not, it's not needed to provide it when running your commands in the local web UI.
In my raspberry pi, with a fresh install of Kura, if I try to run via web UI the command **ls /tmp**, it works.  

Best regards,
Matteo

**Comment by MMaiero** [comment]
We have recently added a "Download logs" feature in Kura that allows the user to download all the meaningful device logs directly from the UI.

Closing , then, for now.
