### ISSUE TITLE
Modem: manually killing pppd with Kura running never triggers a modem reset

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#172]

**Comment by cdealti** [comment]
@ibinshtok Can you please check this? If you keep killing ``pppd`` while Kura is running, the modem is never reset. Do not fix it for now, only understand the behavior and the effort required.

**Comment by pierantoniomerlino** [comment]
@MMaiero Do you remember on which device you showed this behaviour? I checked on 10-05 and 10-11 and the monitor correctly detected that the pppd is not active. Since this issue is quite old, there were some modifications that fixed it? Can we close it?

**Comment by MMaiero** [comment]
It was an old issue ported to github. If you performed some tests and the issue is already solved, I think we can close for now
