### ISSUE TITLE
[Kura 3.1.0 QA] WiFi DHCP: Gateway IP wrong in GUI

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1724]
Perform test NET-WIFI-001 and move to NET-WIFI-003 (WAN, DHCP, Station mode). Wait for the interface to obtain the IP from DHCP, refresh page to be sure.

GUI shows Gateway is 127.0.0.1 instead of the correct IP; route returns the proper IP/default route.
![image](https://user-images.githubusercontent.com/22816717/31223676-54640c64-a9cb-11e7-9cdc-c365b75d0e0d.png)
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.242.17.250   0.0.0.0         UG    0      0        0 wlan0
```

Restart Kura.
GUI now shows empty Gateway; route still returns the proper IP/default route.
DNS Servers are not displayed in either case.

GUI should probably display the IP that `route` returns.

Kura 3.1.0 RC b41 on RPi3

**Comment by markoer** [comment]
Similar thing actually happens with ethernet, except that one of DNS servers is available as a label before Kura's restart.

**Comment by cdealti** [comment]
@ibinshtok @markoer I believe this is a regression added with 451370bac18cf527fa2733e43a8aa03ba77eb8ad a precisely with the refactor of `getDhcpDnsServers`.

**Comment by markoer** [comment]
Verified in 3.1.0 RC b42.
