### ISSUE TITLE
[System dependencies] Check if resolvconf causes issues with network administration

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1727]
Some gateways are not shipped with the binary in question, it's recommended to remove it for Fedora and it didn't seem to cause problems on Raspbian so far.
The expected result of this issue is to determine whether having it installed on the rest of the supported systems affects Kura in any way and should therefore be removed as a precondition for Kura installation.

**Comment by MMaiero** [comment]
Managed now by the Kura installer + declared dependencies
