### ISSUE TITLE
Add more properties to Kura's configuration dynamically and display new configuration in web UI 

### ISSUE THREAD

**Issue by austindsouza** [eclipse/kura#1735]
Hi,

I'm looking for a method to add new configurations to Kura's configurable properties dynamically when the  OSGI bundle starts. After adding the configurations it should display the newly created configurations in WebUI.

Is their any method to achieve this?

I have tried to do this in java like below in activate method

Map<String, Object> properties = new HashMap<String, Object>();
        properties.put("prop.string", new String("prop.value"));
        properties.put("prop.long", Long.MAX_VALUE);
        properties.put("prop.double", Double.MAX_VALUE);
        updated(properties);

this is adding the new properties to the configuration while printing properties however the change is not reflecting in UI.
can anyone help me on this where i'm going wrong.

Thanks in advance,
Austin.

**Comment by MMaiero** [comment]
Hi Austin,
the changes you are doing to the configuration are done locally to the bundle but are not reflected into the configurationservice which actually manages and persists all the configurations.
Furthermore, even if persisted in the configuration service, those properties, I believe, are not declared in the component OCD description, so they will not be displayed in the Kura Web UI.

For what you want to achieve, I believe you should have a look at the SelfConfiguring Components. There are few around in the Kura codebase.

Best regards,
Matteo

**Comment by austindsouza** [comment]
Hi Matteo,

Can you provide me some pointers on SelfConfiguring Components ?

Thanks,
Austin

**Comment by MMaiero** [comment]
https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java

**Comment by MMaiero** [comment]
@austindsouza Did that help you?
Can we close this issue?

**Comment by austindsouza** [comment]
@MMaiero Is their any example available for reference? 
It would be helpful.

**Comment by MMaiero** [comment]
As far as I know, we don't have self-contained examples for this.
But, I believe, the base asset is a good starting point.

**Comment by austindsouza** [comment]
Hi @MMaiero ,

I am trying this with modifying configurable component example. 

My aim here is to create a component definition file with "service.pid" and other details, after that I need to specify the configurable parameters to this bundle's metatype that defines the parameters, default values, types, etc dynamically while runtime. 
 
Not in xml file like giving 
       AD id="param1.string"
            name="param1.string"
            type="String"
            cardinality="0"
            required="true"
            default="Some Text"
            description="String configuration parameter"

Is it possible to do this, if yes then how to achieve this ?

Regards,
Austin

**Comment by MMaiero** [comment]
Hi,
if you have a look at the [SelfConfiguringComponent interface](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/configuration/SelfConfiguringComponent.java) you will see that you need to implement the `getConfiguration` method. That one, when invoked by the framework, will return the [ComponentConfiguration](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/configuration/ComponentConfiguration.java). 
In BaseAsset you have that implemented for the Asset [here](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java#L328)

Best regards,
Matteo

**Comment by austindsouza** [comment]
@MMaiero
Thank you very much for your help, It worked!!!

Best regards,
Austin

**Comment by MMaiero** [comment]
Great!
