### ISSUE TITLE
Networking: check why sometimes eth0 is toggled on wlan0 reconfiguration

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#174]

**Comment by cdealti** [comment]
@pierrepitiot Can you try to just recreate this, please? It's been there since a long time and might have already been fixed.

**Comment by pierrepitiot** [comment]
I was not able to reproduce the problem.

**Comment by cdealti** [comment]
@pierrepitiot @ilya Let's keep this in progress till the QA. During the net QA let's take also a look to the kura.log field.
