### ISSUE TITLE
[Kura 3.1.0] Build error due to exists-plugin

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1747]
Currently, trying to build Kura 3.1.0 from the ```KURA_3.1.0_RELEASE``` tag results in a build error like shown below:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.772 s
[INFO] Finished at: 2017-10-16T15:15:45+00:00
[INFO] Final Memory: 24M/397M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.honton.chas:exists-maven-plugin:0.0.3:remote (default) on project target-platform: Artifact already exists in repository: org.eclipse.kura:target-platform:3.1.0/target-platform-3.1.0.pom -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The workaround for this exception is to disable the ```exists-maven-plugin``` both from target-platform/pom.xml and from kura/pom.xml.

This will make the build working again.

**Comment by kartben** [comment]
Is there an ETA for this? I would hope that this is high priority on the list for the Kura team, as not being able to build a *released* tag usually doesn't send the right message to the community. But it's good to know there is a workaround.

**Comment by kartben** [comment]
I am not sure what to make of the silence on this issue :-)
Jens, maybe you can go ahead and merge your PR, tag the repo as 3.1.1, and someone else can take care of effectively releasing the bits? Would that work for everyone?

**Comment by ctron** [comment]
Sure I can do that by tomorrow.

**Comment by MMaiero** [comment]
Hello everyone,
I'll try to formalise here our idea on how to solve this issue. The constraints we see are the following:
- we would like to preserve the existing tag. That is the effective tag used to perform the 3.1.0 release and that should be kept as is.
- we would like to not modify the release branch. Indeed, since the changes are already merged into develop, the branch could be easily removed without loosing commits and preserving the linearity of the contributions.
- we would like to have the exists plugin always enabled and give the capability to disable it by selecting a specific profile. In our opinion, having it enabled only during the release process will highlight possible issues too late in the process.

To meet all those requirements, we started a maintenance branch called `maintenance-3.1` that has, as a first commit, a fix for the exists plugin by providing a profile to allow the user the capability to disable it when building.
We will create a new tag named `KURA_3.1.0_RELEASE_AMENDED`.

In this way, all the history is preserved, the developers can use the new tag to build their own Kura 3.1.0 and the exists plugin will be always enabled to prevent errors with versions.

Hope to hear your thoughts on this.

**Comment by kartben** [comment]
I might be missing something but I don't think anyone as ever suggested to
"re-tag" 3.1.0? Rewriting history (well in this case it's more "moving"
history, I guess) doesn't sound like a good idea… I think it is fine, and
even advisable, to "admit" 3.1.0 is a faulty release (don't read this in a
negative way, I mean it is not faulty functionally wise, but it should be
buildable) and so the right thing to do would be to follow up ASAP with a
3.1.1 service release. And yes, over time, maybe other fixes should be made
available in the Kura 3.1.x stream so I guess starting a proper maintenance
branch makes sense.
I don't understand well enough the rationale behind the exists plugin to
comment on that, but I would hope that this "implementaiton detail" is
pretty independent of pushing out a 3.1.1 fixed release.

**Comment by ctron** [comment]
👍 
> … and so the right thing to do would be to follow up ASAP with a 3.1.1 service release.

**Comment by MMaiero** [comment]
ok, so we will proceed in this way as soon as possible.

**Comment by ctron** [comment]
As it seems there is no progress but also no feedback which speaks against merging PR #1782 

So I'm going ahead and merge this in order to restore the build.

**Comment by MMaiero** [comment]
I believe we agreed on a path in the previous comments.
Yesterday we filed the release info for 3.1.1 that will be based on maintenance-3.1 branch.
So, in theory, there should be no need to merge #1782

**Comment by ctron** [comment]
> I believe we agreed on a path in the previous comments.

Yes, then again there was silence, so I assumed this issue got forgotten again. Great to see that there will be a solution to that soon.
