### ISSUE TITLE
Wifi: dhcp is still running after switching from AP to station mode

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#175]
wlan0 enabled for LAN with static IP addr, AP mode and DHCP+NAT. Switching to Station Mode leaves dhcpd running.

**Comment by cdealti** [comment]
@pierrepitiot Can you just try to recreate this, please?

**Comment by pierrepitiot** [comment]
I was not able to reproduce. The dhcpd still running is the one associated to eth0 if the default config is unchanged.
