### ISSUE TITLE
[Web UI] Initial page view on a narrow screen

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1758]
Open a browser and reduce width so that Web UI will show menu for narrow devices. Reload the page and the result is this:

![image](https://user-images.githubusercontent.com/22816717/32162611-e135433c-bd59-11e7-9c10-b978ce9e6ba9.png)

Menu remains open with a modal over the content that makes one think it doesn't work. It might be better to close the menu initially, after Kura loads.

3.2.0-SNAPSHOT on RPi3 and Firefox.

**Comment by MMaiero** [comment]
I agree. 
But I also believe we should load the status page instead of a clean page.

**Comment by markoer** [comment]
Correct. That would also be nice.
