### ISSUE TITLE
Problem in building the Kura Development Environment

### ISSUE THREAD

**Issue by mvtn** [eclipse/kura#1762]
Hi,

I am trying to build Kura via the Oomph installer under the Linux.  

- Into cd ../kura I run mvn clean install and the same command into target-platform/
- I Build without CAN support
mvn -Dmaven.test.skip=true -f pom.xml clean install

After that, the build is a success. 

BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:07 min
[INFO] Finished at: 2017-11-02T16:39:38+00:00
[INFO] Final Memory: 161M/820M

But into the Eclipse workspace I got Errors (13 items). org.eclipse.kura.docs/pom.xml, org.eclipse.kura.driver.s7plc.provider/pom.xml and org.eclipse.kura.wire.script.filter.provider/ScriptFilter.java, org.eclipse.kura.wire.script.filter.provider/WireEnvelopeWrapper.java,
org.eclipse.kura.wire.script.filter.provider/WireRecordListWrapper.java
org.eclipse.kura.wire.script.filter.provider/WireRecordWrapper.java

Errors:
Access restriction: The constructor 'NashornScriptEngineFactory()' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	ScriptFilter.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 140	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The method 'NashornScriptEngineFactory.getScriptEngine(ClassFilter)' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	ScriptFilter.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 141	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireEnvelopeWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 15	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireEnvelopeWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 17	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireRecordListWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 18	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireRecordListWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 20	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireRecordWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 23	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'AbstractJSObject' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	WireRecordWrapper.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 25	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'NashornScriptEngineFactory' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	ScriptFilter.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 41	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'NashornScriptEngineFactory' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	ScriptFilter.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 140	Java Problem

Description	Resource	Path	Location	Type
Access restriction: The type 'NashornScriptEngineFactory' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar')	ScriptFilter.java	/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider	line 140	Java Problem

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:3.0.0:copy (execution: default, phase: generate-sources)	pom.xml	/org.eclipse.kura.driver.s7plc.provider	line 38	Maven Project Build Lifecycle Mapping Problem

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.eclipse.tycho.extras:tycho-document-bundle-plugin:0.26.0:javadoc (execution: eclipse-javadoc, phase: generate-resources)	pom.xml	/org.eclipse.kura.docs	line 38	Maven Project Build Lifecycle Mapping Problem

- Output of **mvn -version :**
~/Desktop/EclipseKura/iot-kura-master/git/kura/kura$ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-28-generic", arch: "amd64", family: "unix"

Thanks for any help. :)

**Comment by MMaiero** [comment]
Hi,
I believe those errors are due to some wrong configs in Eclipse, since the maven build seems to succeed.
You can work anyway, we will try to see if there is some configuration change that can prevent those errors to be displayed in the IDE.

Thanks.

Best regards,
Matteo
