### ISSUE TITLE
Kura DB Store Query

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1773]
I have noticed inconsistent behavior between a traditional DB Manager query and a query executed in the Kura Wires DB Filter. Specifically, this is related to trying to read the last value entered in the DB and determine if it is above/below a certain threshold. An example query would be something like:

`SELECT "Torq","TIMESTAMP" FROM (SELECT * FROM "WR_data" ORDER BY TIMESTAMP DESC LIMIT 1) WHERE "Torq" > 200`

In an external DB Manager, the above query only returns a result if the last entry (based on TIMESTAMP) is > 200. In the Wire DB Filter, the query returns a result if the desired value was ever > 200.

**Comment by MMaiero** [comment]
It can be a good improvement. But I believe we need a flag in order to keep compatibility with the current behaviour.

**Comment by dwoodard1** [comment]
I'm not sure I understand. What is the default behavior? Shouldn't the filter match standard SQL queries?

**Comment by MMaiero** [comment]
Sure, but if we change now the current behaviour we risk to break the existing graphs.

**Comment by dwoodard1** [comment]
OK, but this seems like a bug fix to me. I don't think we can worry about breaking implementations that only work due to a bug. If you don't consider this a bug, then I would agree with you.
