### ISSUE TITLE
Unable to locate source code of apache-log4j-extras-1.1.jar

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1783]
Looking at the dependency `log4j.apache-log4j-extras_1.1.0.jar` which is required by Kura I do see there are modifications being made compared to the version of Maven Central:

Maven Central: `acd91d528e26aa771198d930cf08e953  apache-log4j-extras-1.1.jar`
Kura: `2ca71cfab66acdb29a205dcd63139b96  log4j.apache-log4j-extras_1.1.0.jar`

Is there any place to find find the source code for those changes?

**Comment by MMaiero** [comment]
I believe the artefact is the same as the one of the first contribution and should match the CQ approved. It only got a renaming from the original `apache-log4j-extras-1.1.jar` to `log4j.apache-log4j-extras_1.1.0.jar`.

I currently have no other detail on the md5 difference with the version available in maven central.

**Comment by ctron** [comment]
So how can we be sure it actually matches the approved CQ?

Could you look this up please.

**Comment by dwoodard1** [comment]
@ctron Is the issue that the CQ [1] was approved as "unmodified"? Does renaming the binary count as "modifying" the library?

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=7838

**Comment by ctron** [comment]
No it doesn't. But as the checksum doesn't match anymore it seems that the content has been altered. Which indicates that the content has been modified, as the name of file is not part of the checksum.

**Comment by dwoodard1** [comment]
I understand. I believe we changed the manifest to make it a fragment bundle. Let me verify that is the only change.

**Comment by ctron** [comment]
If that is the case, then why not follow the approach the GWT, usb4java, JDK DIO, … modules take and re-assemble the bundle inside the Kura build system. That way we could all be sure.

**Comment by ctron** [comment]
Is there any update on this one?

**Comment by MMaiero** [comment]
Can this be closed? The fixes are both in maintenance branch and develop
