### ISSUE TITLE
Maven Archetype does not work - or can someone show me how to use it?

### ISSUE THREAD

**Issue by tobiashochguertel** [eclipse/kura#1788]
I want to use the quickstart archetype which is present from kura/tools/archetype...

I have installed this archetype via "mvn clean install" and successfully created a project from this archetype.

But the created project from this archetype does not build.

The first error which get shows me that the generated pom.xml is not up-to-date with the used equinox version, and also the copyied files for target-definition are empty for `p2-repo-equinox_3.8.1`.

```
        <repository>
            <id>p2-repo-equinox_3.8.1</id>
            <layout>p2</layout>
            <url>file://${basedir}/../target-definition/equinox_3.8.1/repository/</url>
        </repository>
```
https://github.com/eclipse/kura/blob/develop/kura/tools/archetype/example/src/main/resources/archetype-resources/__rootArtifactId__/pom.xml

I think this should be 

```
        <repository>
            <id>p2-repo-equinox_3.11.1</id>
            <layout>p2</layout>
            <url>file://${basedir}/../target-definition/equinox_3.11.1/repository/</url>
        </repository>
```

- Can someone check if this quickstart-archetype is working as expected?
- It looks for me that this quickstart-archetype is not ready to use?

I was also expecting that there would be a <parent> entry defined in my generated project from the quickstart-archetype?

If needed I can create log files - but for yet this description should be sufficient.

**Comment by dwoodard1** [comment]
Thank you for reporting this issue. The archetype feature is experimental and has not been kept up to date with develop. We will use this issue to track the work to update the archetype. If interested, feel free to propose a fix with a PR and we can merge. Otherwise, we will get to this as soon as we can.

**Comment by tobiashochguertel** [comment]
I create a PR, maybe someone decline these PR's with some hints about what I have to change - especially the OSGi Parts is new for me.

**Comment by MMaiero** [comment]
Closing as #2041 is now merged in develop
