### ISSUE TITLE
BluetoothLE: compatibility issue

### ISSUE THREAD

**Issue by gavinying** [eclipse/kura#179]
There are at least 2 different types of gatttool response so far, however the existing code only works with the first scenario, 

Scenario 1: 
[   ][BC:6A:29:AE:CC:33][LE]> connect
[CON][BC:6A:29:AE:CC:33][LE]>

Scenario 2: 
[54:4A:16:5A:14:C6][LE]> connect
Attempting to connect to 54:4A:16:5A:14:C6
Connection successful
[54:4A:16:5A:14:C6][LE]> 

It took me quite a few hours to figure it out, nevertheless, I have fixed it and will share it later.

**Comment by ccustine** [comment]
I have a similar fix which still uses the regex with an OR and should work for both versions.
https://github.com/ccustine/kura/commit/7a1fba0182656f0859ea99011c2bbb4e9a69eb24

I'm not sure that I understand 80e0512 but I think you guys have that figured out on the PR thread.

If you need any help testing this let me know.  I am using BlueZ 5.39.

**Comment by pierantoniomerlino** [comment]
@ccustine 
Thank you for the suggestion. Indeed this is the right regex.

Since the compatibility with Bluez-5.x needs some work, I open a new issue on it #209
