### ISSUE TITLE
[PortFwd] Fields for internal and external ports mixed up

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#1812]
Configuration dialog for port forwarding mixed up internal and external ports, as shown on the screenshot:

![portfwd](https://user-images.githubusercontent.com/26378947/33131611-63476996-cf97-11e7-92dc-368f65c29320.png)

This results in the following iptables statements:
```
2017-11-22 13:37:34,022 [qtp29142573-7084] INFO  o.e.k.l.n.i.LinuxFirewall - Adding port forward rule to firewall configuration: 
-A FORWARD -s 0.0.0.0/0 -d 172.16.0.5/32 -i eth0 -o eth1 -p tcp -m tcp -j ACCEPT; 
-A FORWARD -s 172.16.0.5/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT; 
-A PREROUTING -i eth0 -p tcp -m tcp --dport 4050 -j DNAT --to-destination 172.16.0.5:3040; 
-A POSTROUTING -d 172.16.0.5/32 -o eth1 -p tcp -j MASQUERADE
```
This does not seem right, destination should be 172.16.0.5:4050?

**Comment by ibinshtok** [comment]
@darionct I believe everything is ok here, the prerouting rule:
-A PREROUTING -i eth0 -p tcp -m tcp --dport 4050 -j DNAT --to-destination 172.16.0.5:3040;
is correct. You have specified the internal port to be 3040. This is the port at the destination host 172.16.0.5. This is a port on the host inside the firewall you are trying to reach from outside. On the other hand, the --dport parameter is a port on a gateway that you specify when you are trying to reach the 172.16.0.5:3040.

**Comment by darionct** [comment]
@ibinshtok OK, my remark about IP tables was incorrect. 
However, HTML id's on the web page are still mixed up. I suggest we fix it for consistency reasons.
