### ISSUE TITLE
[Emulator] NumberFormatException while installing new packages

### ISSUE THREAD

**Issue by samizel** [eclipse/kura#1816]
Hello,

because of a wrong default value of "file.upload.size.max" in the kura.properties you receive a NumberFormatException while installing a new package.

Greetings
Andreas

**Comment by samizel** [comment]
PullRequest https://github.com/eclipse/kura/pull/1818

**Comment by MMaiero** [comment]
Closing as PR #1818 has been merged.
Thank you very much for finding it and for the PR!
