### ISSUE TITLE
Move Multitons API and implementation from kura2 to develop

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#182]

**Comment by cdealti** [comment]
@LucaDazi 
* org.eclipse.kura.multiton**s** -> org.eclipse.kura.multiton
* ``MultitonService``: add a lengthy Javadoc to describe how the MultitonService works, for example:
  * What does the ``factoryPid`` parameter mean? I think we should mention the ``Metatype`` here.
  * Does a "multiton" need to be a ``ConfigurableComponent``?
  * How does it play with the ``ConfigurationService`` and ``ConfigAdmin``?
* Do we need the word _Instance_ in every method? For example the ``CloudService`` has a ``newCloudClient`` method, not a  ``newCloudClientInstance``.
* getRegisteredMultitonInstance() -> getRegisteredMultitonInstance**s**()
* newMultitonInstance(factoryPid, takeSnapshot, instanceName) -> newMultitonInstance(factoryPid, instanceName, takeSnapshot)
  * Does the instance name need to be globally unique? Do we enforce this?
  * newMultitonInstance requires an instance name argument and returns the PID assigned by the ``ConfigAdmin``. Does this PID need to be exposed?
* removeMultitonInstance requires the ``ConfigAdmin`` PID. Is this needed? Cannot we delete the multiton instance name passed to newMultitonInstance instead?
* Should we define a ``Multiton`` first class citizen which is returned by ``newMultitonInstance`` and with a ``release`` method?
* addMultitonServiceRegistrationCallback -> addMultitonServiceRegistrationListener
* removeMultitonServiceRegistrationCallback -> removeMultitonServiceRegistrationListener
* MultitonRegistrationCallback -> MultitonRegistrationListener
  * OSGi usually has a slightly different API for this registration thing, for example the [ServiceListener] (https://osgi.org/javadoc/r4v43/core/org/osgi/framework/ServiceListener.html) or the [BundleListener] (https://osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleListener.html)

**Comment by LucaDazi** [comment]
- Add references to OSGi Service Factories in the ``ConfigurationService`` API javadoc

**Comment by LucaDazi** [comment]
Pull Request updated.
