### ISSUE TITLE
Modbus driver will stop working with merge of enh_wiregraph branch

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#1820]
Kura 3.2.0, branch enh_wiregraph: Modbus driver is installed form the Eclipse marketplace, however driver factory component is not available in the "Drivers and assets".
API and package versions have been updated so modbus driver needs to be updated accordingly.

**Comment by MMaiero** [comment]
We decided to keep the driver APIs as they are now and to move all the new features to specific new packages.
For this reason, the old drivers should continue to work also after the wire graph update.

**Comment by MMaiero** [comment]
Closing for now due to API compatibility preserved.
