### ISSUE TITLE
[Wires] Faulty refresh in Chrome

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1822]
Zoom out and panning zoomed-out wire graph leaves component traces as depicted below:
![image](https://user-images.githubusercontent.com/22816717/33554006-4dcdc804-d8fb-11e7-8e2d-d1585e33e961.png)
![image](https://user-images.githubusercontent.com/22816717/33554011-514ab564-d8fb-11e7-9463-6b7e420e5c71.png)

The lingering effect was not observed when moving components as page is refreshed and traces are therefore removed when dragging is finished.

Applies to Chrome (v.62) on Windows. OK in Firefox while zoom doesn't work in IE.
Kura 3.2.0-SNAPSHOT b1258 on RPi3.

**Comment by markoer** [comment]
Update: with zoom working in IE, this still only happens in Chrome.

**Comment by markoer** [comment]
Verified in build 1278.

**Comment by MMaiero** [comment]
Sorry @markoer to have closed the issue without commenting that I've performed tests with Chrome for Mac and Windows verifying that the fix works.
