### ISSUE TITLE
[Services UI] Services menu refresh unreliable when adding components

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1824]
Scenario:
* install ExamplePublisher package
* create a new component based on ExamplePublisher factory component with ExamplePublisher name
* wait for the Services menu to auto-refresh

The last step only happens in about 20% cases on both Firefox and Chrome. The rest of the cases the menu will either only blink as if refreshed or not react at all. Page refresh does the trick.

Kura 3.2.0-SNAPSHOT, but it also happens in earlier releases. Clients were Chrome and Firefox on Windows.

**Comment by MMaiero** [comment]
I've tried with the latest 3.2.0 and the example publisher in marketplace and it worked every time in my Chrome (63). @markoer could you please check if the is still an issue for you?

**Comment by markoer** [comment]
Hmm... I cannot reproduce it anymore. Works in both FF and Chrome, now.
Closing the issue. If it reappears, I can still reopen it.
