### ISSUE TITLE
DEPLOY-V2: download always uses the defalut java keystore

### ISSUE THREAD

**Issue by kandrej** [eclipse/kura#1856]
Deploy-v2 always uses the default java keystore to connect to the server to download a deployment package.

To reproduce the issue:
1. Create your own ca certificate
2. Add the ca certificate to kura's truststore
3. Use the certificate to sign a server certificate
4. Try to download a deployment package from the server using deploy-v2

**Comment by MMaiero** [comment]
Closing as #1829 got merged
