### ISSUE TITLE
[Camel] Create a blog post to announce the upcoming Camel integration in Kura 2.1.0

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#186]
OK but where?

**Comment by cdealti** [comment]
@hekonsek  @dwoodard1 is there anything announcing this?

**Comment by MMaiero** [comment]
@ctron Do you have any plan on this?

**Comment by ctron** [comment]
No. But I can start writing something up when we approach the relase date of 2.1.

**Comment by ctron** [comment]
https://dentrassi.de/2016/11/24/providing-telemetry-data-with-opc-ua-on-eclipse-kura/

**Comment by ctron** [comment]
https://dzone.com/articles/providing-telemetry-data-with-opc-ua-on-eclipse-ku

**Comment by dwoodard1** [comment]
I believe this can be closed based on the linked blog posts, correct?
