### ISSUE TITLE
Add support for WPA2-Enterprise

### ISSUE THREAD

**Issue by iyanmv** [eclipse/kura#1868]
In the docs it is mentioned that:

> It is NOT recommended performing manual editing of the Linux networking configuration files when the gateway configuration is being managed through Kura. (...)

However, in the network tab is not possible to configure the wireless interface to connect to a WPA2-Enterprise network. These types of networks are very common in business and industrial environments.

It is easy to create a `wpa_supplicant.conf` file and add it to `/etc/network/interfaces` but is this considered safe when the gateway is managed trhough Kura?

**Comment by dwoodard1** [comment]
Hello,

WPA2-Enterprise is not officially supported in Eclipse Kura. However, your solution should work in most conditions. The documentation just provides a recommendation. 

Unless you see a specific issue, could you close this issue?
