### ISSUE TITLE
Provide support for "Layer 2 Only" interface configuration mode.

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1879]

**Comment by cdealti** [comment]
@ibinshtok I believe this issue has been opened to add support for bridging network interfaces.
Do you believe this can be realistically achieved by end of February?

**Comment by ibinshtok** [comment]
@cdealti yes this is for bridging network interfaces as well as handling wireless interface with IOS to allow Kura to configure Layer 2 portion (i.e. hostapd and wpa_supplicant). I am still testing my changes, but planning to submit a PR tomorrow.
