### ISSUE TITLE
Change the release build process to correctly publish javadocs

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1898]

**Comment by MMaiero** [comment]
@dwoodard1 Did you have the chance to have a look at this?

**Comment by dwoodard1** [comment]
No, not yet. I will try and have a look over the weekend.

**Comment by dwoodard1** [comment]
@MMaiero I just checked the publish build, the portions to push the javadocs are commented out, but not sure why. Let me know when you run the release build and I can verify that the expected directory structure is present.

**Comment by dwoodard1** [comment]
There was a permissions issue on one of the folders. Seems to be working now.
