### ISSUE TITLE
client-id configuration parameter is too short

### ISSUE THREAD

**Issue by bportaluri** [eclipse/kura#191]
The client-id parameter in the MqttDataTransport configuration page is 24 chars.
For IBM IoT Platform the deviece id is composed as d:org_id:device_type:device_id so it can be a quite long string. See http://iotf.readthedocs.io/en/latest/devices/mqtt.html
This is too small and should be at least 32 characters.

**Comment by MMaiero** [comment]
Hi,
this issue has already been addressed in #128 and will be solved in next Kura release.
Thanks for your report.
Regards,
Matteo

**Comment by bportaluri** [comment]
Thank you
