### ISSUE TITLE
[Artemis] Upgrade to version 2.5.0 

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#1911]
This is an epic to group and track all the issues related to the Upgrade of the current Artemis 2.3.0 to 2.5.0.

**Comment by MMaiero** [comment]
This work will likely close issue #1644

**Comment by ctron** [comment]
As the Artemis release 2.5.0 is imminent, I would like to change this to an upgrade to 2.5.0.

**Comment by kartben** [comment]
I would expect this is too late to get this done for Kura 3.2.0, right?

**Comment by MMaiero** [comment]
I agree, we are going a little bit too far. Let's postpone for the next release, if @ctron agrees.

**Comment by ctron** [comment]
Whatever works for you. I would prefer to have Artemis 2.5.0 over 2.4.0.

I think it would make sense though to have an understanding when the best time is for Kura to make such changes and when not. So what does "next release" mean time-wise?

**Comment by cdealti** [comment]
Well, Artemis 2.1.0 is not usable, being affected by the stealing link bug. However, the time frame is too tight now to start CQs. It will be for the next time.
