### ISSUE TITLE
User should be able to set PDP context number for setting APN.

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#1914]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb):
    - Platform (e.g. Raspberry pi 2):
    - Kura version affected (e.g. Kura 3.1.0): 
    - Java version (paste the result of **java -version**:
    - Host OS (e.g. Debian): 
    - Host OS version

  - [ ] Development environment
    - Version: 
    - Operating system (Mac OS, Windows, Linux):
    - OS Version:
    - IDE Version:
    - Host System Java Version:
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:

**Comment by ibinshtok** [comment]
User should be able to set PDP context number for setting APN when configuring cellular modems. Currently PDP context number is hard coded to 2 for LE910 V2 modem and to 1 for all other GSM/LTE modems. Also dial string is hard coded as atd*99***2# for LE910 V2 modem. The current issue is configuring LE910 V2 for Verizon where both PDP context 1 and 2 are reserved. I think we should keep the idea of providing default dial string and allow user to lead respective field of the 'Cellular' configuration empty. But if user submits the dial string (e.g. atd*99**3#), we should use it and use 3 as PDP context number as well to form the 'at+cgdcont=' command in the chat script.

**Comment by ibinshtok** [comment]
@MMaiero do you know if European version of LE910 V2 modem supports the at#fwswitch? command?
If so, what what it returns? For example on US version it returns 0 for AT&T FW image and 1 for Verizon as shown below:
at#fwswitch?
#FWSWITCH: 0

OK

**Comment by MMaiero** [comment]
@ibinshtok In our test device it returns error:

> at#fwswitch?
ERROR

**Comment by cdealti** [comment]
Fixed by #1930.
