### ISSUE TITLE
 Support SCR/Declarative Services 1.3+

### ISSUE THREAD

**Issue by scottslewis** [eclipse/kura#1933]
Currently, the target platform included in the Kura Developers Workspace (3.1.1) zip is:

org.eclipse.equinox.ds_1.4.400.v20160226-2036

This version of the equinox ds impl supports 1.2 of the OSGi SCR (Declarative Services) specification.

There have been a number of very useful improvements in version 1.3 of the SCR specification, including prototype scope services and configuration property types.  For some use cases, prototype scope services in particular are necessary.

bug 501950 replaced the original equinox impl with the Apache Felix SCR implementation.  bug 501950 was resolved for Oxygen.0, and it fully supports version 1.3 of SCR.   The PDE annotation tooling bug 376950 in Eclipse Oxygen also supports 1.3.

It would be very helpful to Kura consumers to support SCR 1.3 by also including the Apache Felix SCR impl in Kura distributions.

bug 501950:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=501950

**Comment by kartben** [comment]
PR #1916 provides a fix for this issue.
