### ISSUE TITLE
[DbDataStore] Stale messages not purged with timezone other than UTC

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#1941]
Kura uses a HouseKeeper thread to purge messages from the internal data store once they have been published. The query to find these messages (QoS == 0) is of the form:

`DELETE FROM <table_name> WHERE qos = 0 AND publishedOn <= DATEADD('ss', 5, NOW()) AND publishedOn IS NOT NULL;"`

The NOW() function returns the current time from the underlying OS. However, when updating the "publishedOn" column once a message is published, the Java code uses Date().getTime(), which always returns UTC. Because of this, systems with a timezone set to anything west of UTC will never clear messages from the datastore.

Kura should be able to handle systems with a timezone set to something other than UTC.

**Comment by cdealti** [comment]
I've only found this for *H2*:

https://stackoverflow.com/questions/13176251/set-default-timezone-h2-database

Not sure if this is the expected behaviour
