### ISSUE TITLE
karaf-emulator can't login to web ui

### ISSUE THREAD

**Issue by spnettec** [eclipse/kura#1946]
When i run 
       cd emulator-instance
       mvn exec:java -Prun
It's work well.But i can not login to web ui using admin:admin.
Only login to karaf webconsole using karaf:karaf

**Comment by cdealti** [comment]
@spnettec running Kura on Karaf is no longer maintained. @dwoodard1 @MMaiero @ctron At some point we should discuss removing unsupported/untested builds and platforms from the codebase.

**Comment by kartben** [comment]
@ctron thoughts? I can confirm I can't login either. Not sure there is a trivial fix or not, but in general I agree that the karaf emulator doesn't look in such a good shape, which is too bad cause it is super handy :)

**Comment by ctron** [comment]
Well I would love to see support for Karaf. As I agree, it is a valuable addition IMHO. However there are a bunch of issues in Kura which prevent you from actually using it, the biggest one being the concept of the ConfigurationService. But I think we iterated over them for few times in the past and this situation probably won't change soon. So I agree that removing support for Karaf seems like the best approach in the current situation.

**Comment by cdealti** [comment]
closing as Karaf support will be discontinued in Kura 4.0.0.
