### ISSUE TITLE
Incompatible use of OSGi Designate element

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1952]
I think that Kura currently uses the `<Designate>` element in a way that is incompatible with the OSGi specification.

The result is that you cannot use e.g. the maven-bundle-plugin/bndtools to create a Kura factory component. Eclipse PDE doesn't offer support for editing Metatypes, so it simple is ignored.

Looking at "105.6.2" (R4)of the OSGi compendium specification is says that:
> For factories, the related pid attribute is ignored because all instances of a factory must share the same meta type.

The OSGi R6 annotation follow that by only having a boolean indication for the factory: [1]

From a first look in think the solution to this problem would be rather simple:
* The Kura configuration service should use the factory ID instead of the PID in the case of a factory (`org.eclipse.kura.core.configuration.ComponentMetaTypeBundleTracker.processBundleMetaType(Bundle)`)
* Fix the NPE in `org.eclipse.kura.core.configuration.util.ComponentUtil.getDesignate(Tmetadata, String)` which expects the PID to be set
* Extend `org.eclipse.kura.core.configuration.util.ComponentUtil.getDesignate(Tmetadata, String)` in order to check for either PID or factory PID

[1] https://osgi.org/javadoc/r6/cmpn/org/osgi/service/metatype/annotations/Designate.html

**Comment by cdealti** [comment]
@ctron isn't this fixed by PR #1952?

**Comment by ctron** [comment]
#1952 actually is this issue … but there was PR #1953 who's commits got directly merged by ceb6e3cf39d86f5dc497e1c6e87f2606b952f340

But yes, it is merged into `develop` and I think we can close this now.
