### ISSUE TITLE
[Wires] Creating a component named ")" is possible

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1956]
- Component affected:
  - [X] Kura Wires

  - If needed to replicate the issue, please provide references for the browser used:
    - Name: Firefox
    - Version: 58.0.2
     
- Textual description of the issue:

Kure Wires doesn't prevent one from creating a component named `)`. The Web UI fails with an empty stack track. The component gets created:

~~~
{org.eclipse.kura.configuration.ConfigurableComponent, org.eclipse.kura.wire.WireComponent, org.eclipse.kura.wire.WireReceiver, org.osgi.service.wireadmin.Consumer}={kura.service.pid=), service.pid=org.eclipse.kura.wire.Logger-1520846210926-10, service.factoryPid=org.eclipse.kura.wire.Logger, component.name=org.eclipse.kura.wire.Logger, component.id=59, kura.ui.service.hide=true, log.verbosity=QUIET, service.id=184, service.bundleid=116, service.scope=bundle}
  "Registered by bundle:" org.eclipse.kura.wire.component.provider_1.0.100 [116]
  "Bundles using service"
    org.eclipse.equinox.wireadmin_1.0.600.v20150715-1528 [21]
    org.eclipse.kura.wire.provider_1.0.100 [118]
    org.eclipse.kura.core.configuration_1.1.100 [63]
~~~

But it doesn't show up in the Wires canvas.

As `)` will probably break the LDAP style filter for OSGi at several locations, I am pretty sure this will cause other problems as well.

IMHO in the end the Wires framework (NOT THE UI) should prevent creating components with a name like that. Although it will be helpful if the UI prevents that as well. Also see #1955.

**Comment by MMaiero** [comment]
I believe this can be closed now
