### ISSUE TITLE
[Wires] Use alphabetical ordering for Wires components

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1958]
IMHO the current ordering of Wire components is not really intuitive. I guess using an alphabetical ordering based on the label would make sense.

**Comment by tafitzgerald** [comment]
@ctron wires components are currently ordered by number of inputs vs outputs. Do you think that an alphabetical ordering would be better suited?

**Comment by tafitzgerald** [comment]
Created fork that orders wire components alphabetically. I would think it helpful to indent or stack similar components to make consumer/producer families more apparent. PR soon to come.
