### ISSUE TITLE
[Web] Escaping doesn't seem to work properly

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1959]
Using the "new component" dialog it is possible to create components with names like `)`, and `"`.

While `)` can be deleted afterwards the `"` (and also others like `&` or `'`) gets expanded to `&quot;` and then can no longer be deleted as a component named `&quot;` doesn't exist. I guess at some point this gets escaped twice.

**Comment by darionct** [comment]
"New Cloud Service Pid" is not validated. Ne service dialog allows you to enter anything and then Kura shows error popup "A generic unrecoverable error happened. " and it is no longer able to list cloud services, not even those properly named, so service list is empty. There seem to be no way to recover form this situation.
However it does show warning "Must match regex" if the field is blank. 
Validation for New Factory Component is different and more strict.
Tested on Kura RC build 44, Beaglebone black.
