### ISSUE TITLE
[Connection Status] Provide info on whether Kura is connected to Internet

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#196]
The connection status, which is output by the Kura `CloudConnectionStatusService` does not indicate if the gateway is connected to Internet (e.g. can ping www.google.com).
Among the reasons why Kura cannot connect is that there is not Internet connectivity (cable disconnected, missing DNS servers, firewall-related problems, etc).
This information is useful for initial troubleshooting of connectivity problems.

When the connection status is output to a led, if Kura cannot connect to the Cloud the led indication alternates between a slow and a fast blink.
This actually means that Kura cannot establish an MQTT connection to the broker.

We should provide a mechanism to verify and report also Internet connectivity problems.
Among the possible methods:
- actively ping a configurable host. This covers cable and DNS problems and it's relatively lightweight.
- actively probe the broker establishing a plain TCP connection. This covers cable, DNS and firewall problems but it's an heavier mechanism.
- passively use connectivity information by already running Kura services like the `ClockService`.

Above failed Internet connectivity checks would result in the status led being always off.

**Comment by kartben** [comment]
+1! 😊

**Comment by GiovanniFerrari** [comment]
Hi every one,

are there any news about this feature?

Thanks
