### ISSUE TITLE
[Web] Unable to identify component type after creation

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1960]
After creating a new component with the Kura Web UI, the component type is no longer visible and the user has to figure out the component type based on the structure of the service's attributes. Of course this will only work if the services do have different attributes.

IMHO the service type/component type should be visible in the UI alongside the service/component ID.

**Comment by nicolatimeus** [comment]
The component type should be visible in the heading of the configuration section
<img width="493" alt="screen shot 2018-03-15 at 09 19 46" src="https://user-images.githubusercontent.com/8960773/37451548-263af3f8-2832-11e8-8f11-9615c79377ec.png">

**Comment by ctron** [comment]
You are just looking at the Wires UI I assume:

![image](https://user-images.githubusercontent.com/202474/37509605-43d492b8-28f8-11e8-8c67-966fd3138d82.png)

I agree that (if the service has a description) with Kura 3.2 this will be a bit improved. Still you have to deduct it from the description. And if that is empty you are back to the original problem.

**Comment by tafitzgerald** [comment]
Wires components are labeled differently than the services panel. I am working different options to display the component type on the main ui panel for services, but real estate can be tricky to display both component type and name.
