### ISSUE TITLE
"master" branch of Kura looks dead

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1961]
IIRC Kura follows the "git flow" model [1]. With that I would expect that the "master" branch is up to date with the most recent released version. [2]

Looking at the master branch of Kura however I can only see a last update "a year ago" with a version of "2.1.0" [3].

[1] https://github.com/eclipse/kura/tree/master#development-model
[2] http://nvie.com/posts/a-successful-git-branching-model/
[3] https://github.com/eclipse/kura/blob/master/kura/pom_pom.xml

**Comment by MMaiero** [comment]
Hi, please have a read at the following document: https://github.com/eclipse/kura/wiki/New-Kura-Git-Workflow

**Comment by ctron** [comment]
Then I think you make this very prominent in the master branch. Currently is simply looks dead.

**Comment by kartben** [comment]
I agree this is confusing. @MMaiero the link you provided makes it hard to understand what the actual flow is expected to be for the project? For example there is a header that reads "Kura QA and Release Using the GitFlow Model" and another that reads "Kura QA and Release Using the Anti-GitFlow Model", plus the very last one that adds even more confusion :-)

Am I correct in assuming that 'master' should simply be deleted? I don't think it captures any important information at this point?
