### ISSUE TITLE
[Web] Broken form validation

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1962]
- Component affected:
  - [X] Kura Web UI

  - If needed to replicate the issue, please provide references for the browser used:
    - Name: Firefox
    - Version: 58.0.2
    - Name: Chrome
    - Version: 64.0.3282.167 (Official Build) (64-bit)
     
- Textual description of the issue:

Having a properly filled out form causes a validation error when pressing the apply button:

![image](https://user-images.githubusercontent.com/202474/37279449-20d74d6a-25eb-11e8-915b-71fc6b84e69e.png)

**Comment by MMaiero** [comment]
Hi, could you please provide a test case o something in the develop codebase that can allow us to validate the issue report and work on a fix?

Thanks

**Comment by nicolatimeus** [comment]
@ctron does this apply to the current develop/release-3.2.0 branch?

**Comment by ctron** [comment]
I will test this when I do the test for Fedora.

**Comment by MMaiero** [comment]
@ctron Any update on this?

**Comment by ctron** [comment]
I didn't encounter this at all.
