### ISSUE TITLE
[Kura 3.2.0 QA] Wires, adding component produces warning that component already exists

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#1976]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Installer name: kura_3.2.0_beaglebone_debian_installer.deb
    - Platform : BBB
    - Kura version affected (e.g. Kura 3.1.0): Kura 3.2.0
    - Java version : java version "1.8.0_151"
    - Host OS (e.g. Debian): 
    - Host OS version

  - [ ] Development environment
    - Version: 3.2.0
    - Operating system (Mac OS, Windows, Linux): debian
    - OS Version: 9
    - IDE Version:
    - Host System Java Version:
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:
When wires graph is deleted, component configuration remains in the snapshot. Adding new component with the same name produces error popup with the message that name already exists, even though graph is empty.  

[addComponentError-snapshot.zip](https://github.com/eclipse/kura/files/1833234/addComponentError-snapshot.zip)
It occurs occasionally, so it is difficult to reproduce. Snapshot in the attachment is taken in described state.

**Comment by markoer** [comment]
We now have the cause for the issue.

One of the tests creates a graph with Timer component named Timer01, works with it and never deletes anything (neither the components nor the graph). The next test uploads a partial snapshot of a previously saved graph, that doesn't have a Timer01-named component. This graph is then properly deleted. If you try to create Timer01 now, it will fail with that message.

Should the partial snapshot merge consider the current graph components? That's probably out-of-scope of configuration service.
A possible enhancement would be to introduce an additional button on the Wires page that would perform the partial (graph) configuration merges first deleting the existing graph.

**Comment by cdealti** [comment]
This is hard to fix as the configuration service always merges configurations. We can keep this open as a requirement on how the configuration service should work.
