### ISSUE TITLE
[Camel] Contribute RHIOT quickstart to Kura examples

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#198]
The [RHIOT quickstart code] (https://rhiot.gitbooks.io/rhiotdocumentation/content/quickstarts/kura_camel_quickstart.html) should be contributed to Kura examples.

**Comment by cdealti** [comment]
@hekonsek I Henryk, any progress on this?

**Comment by hekonsek** [comment]
Done. Documentation is here [1].

[1] http://eclipse.github.io/kura/doc/kura-camel.html
