### ISSUE TITLE
[Kura 3.2.0 QA] Wire graph deletion also deletes related asset(s)

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1981]
- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb): kura_3.2.0_raspberry-pi-2-3_installer.deb
    - Platform (e.g. Raspberry pi 2): Raspberry Pi 3
    - Kura version affected (e.g. Kura 3.1.0): 3.2.0 milestone build
    - Java version (paste the result of **java -version**: java version "1.8.0_65"
    - Host OS (e.g. Debian): Raspbian
    - Host OS version: 9 Lite
     
- Textual description of the issue:

Add a driver and attach an asset to it. Use this asset in a wire graph (add component and apply). Delete the graph. Asset is now gone.

Is it always wise to delete assets when deleting graphs? I may want to use the existing assets in a different way and don't want to remove separate components. But now I have to reconfigure the used assets.

**Comment by MMaiero** [comment]
It's a behaviour introduced with the Wires refactoring. The idea is that once in wires, the component is managed as Wire component. So, when the graph or the specific component is deleted in the composer, is deleted also from the framework.

A possibility is to add a message asking if the component needs to be removed from the composer only or from the framework. But, I believe, it will make the interaction more difficult for the user.

**Comment by cdealti** [comment]
Closing
