### ISSUE TITLE
[RPI3] Bind permission related issues

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#1989]
- Component affected:
  - [ ] Distribution
    - Installer name kura_3.2.0_raspberry-pi-2-3_installer.deb:
    - Platform (e.g. Raspberry pi 2): Raspberri PI 3
    - Kura version affected (e.g. Kura 3.1.0): 3.2.0
    - Java version (paste the result of **java -version**:
    - Host OS (e.g. Debian): Raspbian
    - Host OS version: Raspbian GNU/Linux 9 (stretch)

  - [ ] Development environment
    - Version: 
    - Operating system (Mac OS, Windows, Linux):
    - OS Version:
    - IDE Version:
    - Host System Java Version:
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:

Currently Kura generates the `/etc/bind/named.conf` configuration file using two different templates, depending (at least) on the value of the configuration parameter **Pass DNS Servers through DHCP** in the **DHCP and NAT** section of the web UI.

Both of these configuration file variants specify a custom logging configuration for `named`:

1. If the parameter is set to `false`, `named` is configured for logging on `data/named.run`.
2. If the parameter is set to `true`, `named` is configured for logging on `/var/log/named.log`.

In the scenarios above I've found the following issues:

1. In the first scenario, if the daemon is invoked using `/etc/init.d/bind9 start`, it will fail to start printing the following messages on `/var/log/syslog`:

```
Mar 27 06:02:38 raspberrypi named[7768]: automatic empty zone: EMPTY.AS112.ARPA
Mar 27 06:02:38 raspberrypi named[7768]: configuring command channel from '/etc/bind/rndc.key'
Mar 27 06:02:38 raspberrypi named[7768]: command channel listening on 127.0.0.1#953
Mar 27 06:02:38 raspberrypi named[7768]: configuring command channel from '/etc/bind/rndc.key'
Mar 27 06:02:38 raspberrypi named[7768]: couldn't add command channel ::1#953: address not available
Mar 27 06:02:38 raspberrypi named[7768]: isc_stdio_open 'data/named.run' failed: file not found
Mar 27 06:02:38 raspberrypi named[7768]: configuring logging: file not found
Mar 27 06:02:38 raspberrypi named[7768]: loading configuration: file not found
Mar 27 06:02:38 raspberrypi named[7768]: exiting (due to fatal error)
```

The daemon start correctly if the following log-related section of `/etc/bind/named.conf` is removed:

```
logging {
	channel default_debug {
		file "data/named.run";
		severity dynamic;
	};
};
```

If the section above is removed bind will use the default logging configuration and forward log messages to the `syslog` daemon.

2. In the second scenario, `bind` is configured to log on `/var/log/named.log`, and to keep 3 backup versions of the file. When the daemon starts it will try to rename `/var/log/named.log` into 
`/var/log/named.log.0`, but it will fail because it does not have the permissions for modifying the `/var/log/ `directory, as it runs as the `bind` user

```
Mar 27 06:15:45 raspberrypi named[9026]: generating session key for dynamic DNS
Mar 27 06:15:45 raspberrypi named[9026]: sizing zone task pool based on 6 zones
Mar 27 06:15:45 raspberrypi named[9026]: set up managed keys zone for view _default, file 'managed-keys.bind'
Mar 27 06:15:45 raspberrypi named[9026]: configuring command channel from '/etc/bind/rndc.key'
Mar 27 06:15:45 raspberrypi named[9026]: command channel listening on 127.0.0.1#953
Mar 27 06:15:45 raspberrypi named[9026]: configuring command channel from '/etc/bind/rndc.key'
Mar 27 06:15:45 raspberrypi named[9026]: couldn't add command channel ::1#953: address not available
Mar 27 06:15:45 raspberrypi named[9026]: unable to rename log file '/var/log/named.log' to '/var/log/named.log.0': permission denied
```

This can be fixed as well by removing the logging related section of `/etc/bind/named.conf`. The `/var/log/named.log` is created by Kura installer script, which also changes the ownership of the file to the `bind` user. If the file is removed, `bind` will not be able to recreate it and it will fail to start.

**Comment by nicolatimeus** [comment]
@markoer can you please check if the issues above are present also in the Rasbian version used for the Kura QA?

**Comment by markoer** [comment]
The behavior is the same on Raspbian 9.
