### ISSUE TITLE
[Camel] Camel bundles are in RESOLVED state and must be manually started

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#199]
63	RESOLVED    org.apache.camel.camel-core_2.16.0
64	RESOLVED    org.apache.camel.camel-core-osgi_2.16.0
65	RESOLVED    org.apache.camel.camel-kura_2.16.0

Please fix [config.ini](https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/ant/build_equinox_distrib.xml).

Please submit through a Pull Request

**Comment by hekonsek** [comment]
I don't think we need to start them. Those just provide dependencies to customer modules. Do you see any issue related to the fact that these bundles are not started?

**Comment by cdealti** [comment]
I assumed that they needed to be started since they can be started and they become ACTIVE.
I had this impression installing the quickstart and this needs to be manually started.
Should I close the issue?

**Comment by hekonsek** [comment]
Yes, you don't need to start them. I think we can close this.

**Comment by cdealti** [comment]
OK, thanks.
