### ISSUE TITLE
bluetoothGattImpl.java writeCharacteristicValue can not success notify

### ISSUE THREAD

**Issue by zengbiao** [eclipse/kura#1991]
in BluetoohGattImpl.java:
    @Override
    public void writeCharacteristicValue(String handle, String value) {
        if (this.proc != null) {
            this.charValueUuid = null;
            String command = "char-write-cmd " + handle + " " + value + "\n";
            sendCmd(command);
        }
    }

I want to enable notification, only way is call "writeCharacteristicValue" and it will call "char-write-cmd",
but actually "char-write-req" can enable notification.

char-write-req  <handle> <new value>           Characteristic Value Write (Write Request)
char-write-cmd  <handle> <new value>           Characteristic Value Write (No response)

===here are result:
[FE:97:18:09:14:43][LE]> char-write-req 0x0024 0100
Characteristic value was written successfully
Notification handle = 0x0023 value: e1 05 00 00 4d 0a 15 02 

[FE:97:18:09:14:43][LE]> char-write-cmd 0x0024 0100
[FE:97:18:09:14:43][LE]>   //nothing happened

my hcitool version "HCI Tool ver 5.43"

how to solve this???

**Comment by pierantoniomerlino** [comment]
@zengbiao The writeCharacteristicValue uses indeed the char-write-cmd under the hood.
However, it shouldn't be any difference between the two commands (-cmd vs -req). The only difference is that -req returns the result of the operation, while -cmd doesn't return anything.

I checked on my TiSensorTag and here are the results:
```
[B0:B4:48:BF:D7:80][LE]> char-write-cmd 0x27 01
[B0:B4:48:BF:D7:80][LE]> char-read-hnd 0x24
Characteristic value/descriptor: 90 0a 7c 0d 

[B0:B4:48:BF:D7:80][LE]> char-write-req 0x25 0100
Characteristic value was written successfully
Notification handle = 0x0024 value: ec 0a 7c 0d 
Notification handle = 0x0024 value: 04 0b 7c 0d 
Notification handle = 0x0024 value: d8 0a 80 0d 

[B0:B4:48:BF:D7:80][LE]> char-write-req 0x25 0000
Characteristic value was written successfully

[B0:B4:48:BF:D7:80][LE]> char-write-cmd 0x25 0100
Notification handle = 0x0024 value: d0 0a 80 0d 
Notification handle = 0x0024 value: cc 0a 80 0d 
Notification handle = 0x0024 value: c0 0a 80 0d 
[B0:B4:48:BF:D7:80][LE]> char-write-cmd 0x25 0000
```

**Comment by zengbiao** [comment]
@pierantoniomerlino , thanks for your reply, i don't know why i can't see any notification via "char-write-cmd" , but "char-write-req" can get notification.
may it be that my bluez version is 5.43?

**Comment by pierantoniomerlino** [comment]
@zengbiao I tested it on a RPi 3 with Bluez 5.43 and a TiSensorTag.

**Comment by MMaiero** [comment]
@zengbiao Any update? Can this be closed?
