### ISSUE TITLE
NET-ETH0-005 unclear

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1994]
The QA test 'NET-ETH0-005' says:

> Reboot the gateway (Power OFF/ON) and check it reconnects.

However if is unclear to what it should reconnect. To the network, as this is the current context. Or to the MQTT broker, because that was used in the last step.

If the latter is the case, then this test has to fail because all previous steps keep the default setting of "connect on startup" set to "false" and thus the gateway **must not** re-connect on startup.

**Comment by cdealti** [comment]
> However if is unclear to what it should reconnect.

To the broker.

> If the latter is the case, then this test has to fail because all previous steps keep the default setting of "connect on startup" set to "false" and thus the gateway must not re-connect on startup.

NET-ETH0-003 says:
> Configure DataService to enable connect.auto-on-startup

and NET-ETH0-004 does not modify this setting.

Do I miss something obvious?

@markoer can you please comment?

**Comment by markoer** [comment]
@cdealti It's exactly as you commented. The tests in a certain group are meant to be executed in order so as not to set everything from scratch in each test.

**Comment by ctron** [comment]
So maybe using:

> and check the cloud service reconnects to the broker

would be more precise.
