### ISSUE TITLE
[Camel] Do we need to add sun.*,com.sun.* bootdelegation to Kura?

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#200]
As explained in the [quickstart](https://rhiot.gitbooks.io/rhiotdocumentation/content/quickstarts/kura_camel_quickstart.html) bootdelegation must be added to config.ini:

```
org.osgi.framework.bootdelegation=sun.*,com.sun.*
```

Are there alternatives to bootdelegation?

**Comment by cdealti** [comment]
@hekonsek as you reported this is necessary (for now). Please **submit this as a pull-request**.
You can create a PR branch directly in the upstream Kura repository

**Comment by ctron** [comment]
I do think that this one is resolved with PR #365.

**Comment by hekonsek** [comment]
Resolved by Jens and Camel upgrade.
