### ISSUE TITLE
DEN-DEPLOY-001 is unclear

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2001]
The text of DEN-DEPLOY-001 is unclear, at some point is states:

> After it is added and page is reloaded it is available in Services window and its configuration is accessible

However the context before and after this sentence is the actual DP. There is no "services" window and the DP is actually visible in the package list. However the next test will fail unless a new service instance was created.

So the test should explicitly mention to create a service. And IMHO this should be an explicit step in the testing procedure and should not be mixed with DEN-DEPLOY-001.

**Comment by cdealti** [comment]
@markoer please fix it
