### ISSUE TITLE
Issue with DEN-DEPLOY-005

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2003]
Although that is also not part of DEN-DEPLOY-005, the result for me is that the package got upgraded (at least it seems that way), but the old package is still in the `packages` folder. But not in the `dpa.properties` file.

So that might or might not be an issue.

**Comment by cdealti** [comment]
It is expected that the old package is removed from the `dpa.properties` file, otherwise it would be reinstalled at the next Kura start.

Deleting uninstalled/upgraded packages from the `packages` directory would be a good idea too but not critical for the release, I believe.

**Comment by ctron** [comment]
The behavior seems a bit asymmetrical with the package uninstallation, in which case the package is actually removed from the file system.
