### ISSUE TITLE
DEN-DEPLOY-008 kind of fails

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2004]
I am not sure what the "planned for installation" location is, but dropping a link on the footer does open a webpage of the Eclipse Marketplace and navigates away from the Kura admin web page.

True, the installation isn't triggered by that, but IMHO this is not the correct behavior.

**Comment by cdealti** [comment]
Agreed but not critical.

**Comment by markoer** [comment]
The original design expected link to be dropped in this location (intended for installation):
![image](https://user-images.githubusercontent.com/22816717/38353302-55e31614-38b6-11e8-9e80-745f2151f228.png)

In the last release it was updated to include the larger part of the window, obviously excluding the footer and menu to the left as indicated by a different-color div:
![image](https://user-images.githubusercontent.com/22816717/38353334-67518160-38b6-11e8-8ed0-eef783c7c72e.png)

The location not meant for installation behaves in an ordinary way the browser is supposed to behave - it opens the page the link of which was dropped there.

**Comment by ctron** [comment]
> obviously excluding the footer and menu to the left

Is there any reason for that?
