### ISSUE TITLE
DEN-CONF-002 kind of fails

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2005]
Setting the time interval to "500" ms lets the publisher still publish at 1 second.

Looking at the payload you discover that the timestamp actually has a 500 ms difference. Stopping the publisher doesn't actually stop the publishing. So my assumption is that some internal buffer is filling up.

**Comment by pierantoniomerlino** [comment]
@ctron Did you tried to disable the rate limit? Take a look at the **enable.rate.limit** here [1].

[1] : https://eclipse.github.io/kura/config/data-service-configuration.html

**Comment by ctron** [comment]
No, that wasn't mentioned in the test so far. But my assumption would be that in this case exceeding messages would be dropped and not buffered. As the default setting for the example publisher is QoS 0.

But I will try this next.

**Comment by cdealti** [comment]
@ctron If you don't mind, I will remove the `bug` label for now.

@markoer can you please add a clarification about the rate limit in the QA spreadsheet?
