### ISSUE TITLE
Array validation doesn't work properly

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2007]
This is related to DEN-CONF-036, I know it is not part of the test, still I think it is a bug.

The field `metric.short.array` states that is has a range of "Metric range min -32760 max 32760". Entering "32761" causes a proper error to appear, but selecting the next field in the array makes the error disappear again. The (out of range) value can be saves and gets applied to the service:

~~~
2018-04-03 14:22:11,581 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.e.p.ExamplePublisher - Update - metric.short.array: [10, 20, 30, 32761]
~~~

I do think that validation checks should be done by Kura configuration service **in addition** to the UI, in order to fix issues like this.

**Comment by cdealti** [comment]
>I do think that validation checks should be done by Kura configuration service in addition to the UI, in order to fix issues like this.

I totally agree on this.

However the simple Meta Type validation is still insufficient for most use cases, for example where a string is used to represent an IP address or an XML or JSON document.

In these cases, the application receiving the configuration is still responsible for validating it.

If you think it is critical, we could evaluate fixing this issue in the Web UI first and postpone the rest. What do you think?

**Comment by ctron** [comment]
IMHO it is necessary to fix all layers of this. If a service requires more than the Meta Type service provides, then it is the responsibility of the service to validate. But this is not about "on top" validation.

However if Kura provides an API then the consumer of this API should be able trust the contract of it. I don't think that consumers should be required to enforce those contracts.

Of course a good start is to this the UI layer and sync it with the current behavior of single item fields.

**Comment by cdealti** [comment]
@markoer can you please check? Fixing this in the Admin UI should not be too hard. Do you want to try?

**Comment by MMaiero** [comment]
It seems to be verified on the supported platforms. Let's close for now
