### ISSUE TITLE
Unsaved changes dialog triggers incorrectly

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2013]
While testing Kura 3.2 RC I noticed a few times that the "there are unsaved changes" dialog triggers incorrectly. Making a change, pressing "Apply" applies the changes, the "apply" button even gets disabled. Yet the Web UI asks to discard changes when moving away from the service.

**Comment by MMaiero** [comment]
Could you please provide a replicable set of actions in order to identify the issue?

**Comment by ctron** [comment]
I thought that would be clear by:

> Making a change, pressing "Apply" applies the changes, the "apply" button even gets disabled. Yet the Web UI asks to discard changes when moving away from the service.

As this is an issue which sporadically appears (at least I haven't found a pattern yet) I cannot give you a set of instructions to replicate this with with 100% certainty.

**Comment by tafitzgerald** [comment]
I have seen this occur before as well and it happens irregularly. This is due to the field being marked as "dirty" when it is touched. This seems to be a minor bug in the system and will be corrected. Thanks for your input on this @ctron.

**Comment by MMaiero** [comment]
@tafitzgerald Any progress on this topic?

**Comment by tafitzgerald** [comment]
Should be finished. I'm waiting to test before creating PR.

**Comment by tafitzgerald** [comment]
Tested and submitted PR #2631
