### ISSUE TITLE
Deleting a component keeps tab open

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2014]
Tested with Kura 3.2 RC:

* Create factory service instance
* Select service
* Delete service -> tab remains open
* Make changes to configuration
* Press "Apply" -> Error

![image](https://user-images.githubusercontent.com/202474/38256300-3b40f8ca-375e-11e8-823d-b9a8fd3cc1dd.png)

I think there are two things wrong here:

1. The service tab should be closed when the service is deleted
1. A proper error message should be shown when the "apply" action fails

**Comment by MMaiero** [comment]
It seems to be verified on the supported platforms. Let's close for now
