### ISSUE TITLE
New Factory Component - drop-down-list item missing for a installed package

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#2015]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Platform: observed on multiple platforms
    - Kura version affected (e.g. Kura 3.2.0): 

  - [ ] Development environment
    - Version:  3.2.0 RC #445 
    - Deployment package: ExamplePublisher 1.0.300      

  - If needed to replicate the issue, please provide references for the browser used:
    - Name: Firefox 
    - Version: 57.0.4
     
- Textual description of the issue:
Package is successfully installed and listed on the "Packages" tab but it's factory component is missing from the drop-down list when clicked on "+" in Services menu. Therefore, component can not be added to the services menu. Issue can be resolved by reinstalling the package. 
Another variant of this issue occurs when package is uninstalled, but menu item is still present in the drop-down list. Selecting it produces no result, no errors/warning or the log output.

**Comment by cdealti** [comment]
@markoer it seems that most of the problems of Kura 3.2.0 are about ExamplePublisher.
Also see #2002 and #2009. Can you please thoroughly review/debug it with highest priority?

**Comment by darionct** [comment]
Fix confirmed on RC build #45. Tested on RPi and BBB.
