### ISSUE TITLE
DRIVERS-BLE-002 unclear

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2018]
In `DRIVERS-BLE-002` it says:

> set the appropriate sensortag.address

But what address is that?

**Comment by pierantoniomerlino** [comment]
@ctron The address of your SensorTag, of course. The one that you can get from a scanning ;-)

**Comment by ctron** [comment]
I guess "set the address of your sensor tag" would make it more clear, at least to me. As I don't have a sensor tag, I am out of luck anyway.

**Comment by pierantoniomerlino** [comment]
I'll take note of that. Thanks

**Comment by ctron** [comment]
Awesome. Thanks.

**Comment by cdealti** [comment]
@markoer can you please add this clarification to the QA spreadsheet?

**Comment by MMaiero** [comment]
Can this be closed now?
