### ISSUE TITLE
Deleting an asset component from the Wires UI also deletes the actual asset

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2019]
Again, maybe this is intended that way, but I stumbled over the following, IMHO weird, behavior:

* Create new driver
* Create new asset
* Add asset to write graph
* Apply wire graph
* Delete asset from wire graph
* Apply wire graph

The result is that both the wire asset component **and** the asset is gone. I would expect the asset to survive in order to (maybe) use it with different APIs of Kura.

**Comment by MMaiero** [comment]
I believe it is a duplicate of #1981

**Comment by ctron** [comment]
> I believe it is a duplicate of #1981

True!
