### ISSUE TITLE
Wrong column content in assert/driver view

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2020]
Maybe it is actually intended that way, but I assume that the content of the Factory PID column in the driver/asset table is filled incorrectly:

![image](https://user-images.githubusercontent.com/202474/38308169-88c1227e-3816-11e8-956d-0aee9e528f4c.png)

I would assume that the factory PID should be filled with the actual ID of either the OPC UA driver: `org.eclipse.kura.driver.opcua` instead of again the driver service ID.

**Comment by MMaiero** [comment]
Yes, that is definitely a regression

**Comment by cdealti** [comment]
Seems an easy fix. Let's do it
