### ISSUE TITLE
[Kura 3.2.0 QA] Package uninstallation log

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2038]
A message is entered into kura-console.log when a deployment package is uninstalled. Applies to locally installed packages as well as for those installed from marketplace. The package is uninstalled OK.

- Component affected:
  - [x] Distribution
    - Installer name: kura_3.2.0_raspberry-pi-2-3_installer.deb
    - Platform: Raspberry Pi 3
    - Kura version affected: 3.2.0 RC 45
    - Java version: 1.8.0_65
    - Host OS: Raspbian
    - Host OS version: 9 lite

- Textual description of the issue:
kura-console.log when uninstalling a package:
```
!ENTRY  1 0 2018-04-12 13:44:40.883
!MESSAGE [IAgent][DeploymentEventListener@ec9f2f] [handleUninstall] No such deployment package with symbolic name: 

!ENTRY  1 0 2018-04-12 13:44:41.038
!MESSAGE [IAgent][DeploymentEventListener@ec9f2f] [handleComplete] There is no information for started session
```

**Comment by cdealti** [comment]
This should be logged by the mToolkit agent...
