### ISSUE TITLE
IfcfgConfigReader semplification

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2047]
The PR #2043 fixes the issue described in #2042. The following code was changed:

```
} else if (netInterfaceStatus != NetInterfaceStatus.netIPv4StatusUnmanaged) {
        netInterfaceStatus = NetInterfaceStatus.netIPv4StatusL2Only;
}
```

However is not clear how this code is reached, since the only case is when the **netInterfaceStatus** has been already set to **netIPv4StatusL2Only**. Is this true?
My proposal is to remove this else statement, as done here bc995c7ea0cf909f7805d61362ea6f74723077fe .
Here are the outputs of ```ip addr``` and ```cat /etc/network/interfaces``` output for the wlan0 interface configured as **Layer 2 Only** and then as **Not Managed** on a Raspberry Pi with the modification:

```
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:28:eb:36 brd ff:ff:ff:ff:ff:ff

# Commented out to prevent wpa_supplicant from starting dhclient
#!kura!auto wlan0
# Commented out to prevent wpa_supplicant from starting dhclient
#!kura!iface wlan0 inet manual
```

**Comment by cdealti** [comment]
@ibinshtok  Let's fix this while it is still hot

**Comment by ibinshtok** [comment]
@cdealti  Ok, working on cleaning up IfcfgConfigReader and IfcfgConfigWriter ...
