### ISSUE TITLE
I don't understand the IfcfgConfigWriter...

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2049]
The IfcfgConfigWriter is responsible to write the configuration files for network interfaces.
The method ```debianWriteUtility``` writes the Debian-style config files in the case of the Raspberry Pi and adds some commented lines for **ONBOOT** and **BOOTPROTO** properties:

```
// ONBOOT
if (((NetConfigIP4) netConfig).isAutoConnect()) {
    if (osVersion.equals(KuraConstants.Raspberry_Pi.getImageName())
            && netInterfaceConfig.getType() == NetInterfaceType.WIFI
            && ((NetConfigIP4) netConfig).isDhcp()) {
        sb.append("#!kura!auto " + interfaceName + "\n");
    } else {
        sb.append("auto " + interfaceName + "\n");
    }
}

// BOOTPROTO
if (osVersion.equals(KuraConstants.Raspberry_Pi.getImageName())
        && netInterfaceConfig.getType() == NetInterfaceType.WIFI && ((NetConfigIP4) netConfig).isDhcp()) {
    sb.append("# Commented out to prevent wpa_supplicant from starting dhclient\n");
    sb.append("#!kura!iface " + interfaceName + " inet ");
} else {
    sb.append("iface " + interfaceName + " inet ");
}
```

As far as I understand, this is done to prevent the OS to start the ```dhclient``` utility and assign an IP address outside Kura. Is this analysis true?
However, when the wlan interface is configured as ```Layer 2 Only``` the ```dhclient``` is not started by the OS, since the IP address is managed by an external application. But the commented lines are there:

```
# Commented out to prevent wpa_supplicant from starting dhclient
#!kura!auto wlan0
# Commented out to prevent wpa_supplicant from starting dhclient
#!kura!iface wlan0 inet manual
```

**Comment by cdealti** [comment]
@ibinshtok any ideas why the Raspberry Pi is special?

**Comment by ibinshtok** [comment]
@cdealti Configuration for wlan0 interface in the /etc/network/interfaces file on Raspberry Pi was commented out to prevent wpa_supplicant from starting dhclient. I need to retest this on the most recent Raspbian image though. It is possible that we no longer need it.
