### ISSUE TITLE
Building Kura Source code from Git

### ISSUE THREAD

**Issue by Amar82** [eclipse/kura#2052]
Please describe the issue you are encountering in Kura.

I have been developing Kura plugins for time being.

But I now want to try my hand in Kura source code. Want to build my own executable set up of  Kura.
How to do that,  can you please guide me .

I follwed the steps mentioned here... but the source code is not getting checked out

Getting Started
The simplest way to start developing on Eclipse Kura is to use an Eclipse Installer based setup. To correctly setup the environment, proceed as follows:

Start the Eclipse Installer
Switch to advanced mode
Select "Eclipse for Committers" and configure the "Product Version", then select a JRE 1.8+ and press the Next button
Select the Eclipse Kura installer from the list. If this is not available, add a new installer from https://raw.githubusercontent.com/eclipse/kura/develop/kura/setups/kura.setup, then check and press the Next button
Select the "Developer Type":
"User": if you want to develop applications or bundles running on Kura, select this option. It will install only the APIs and the examples.
"Developer" : if you are a framework developer, select this option. It will download and configure the Eclipse Kura framework.
Update Eclipse Kura Git repository username and customize further settings if you like (e.g. Root install folder, Installation folder name)
Leave all Bootstrap Tasks selected and press the Finish button
Accept all the licenses and wait for the installation to finish
**At first startup Eclipse IDE will checkout the code, perform a full build and configure a few Working Sets. Now you are ready to develop on Eclipse Kura.**

For further information, building and deployment instructions, please visit the getting started page.

**Comment by MMaiero** [comment]
Hello,
could you please provide a more detailed overview of what is failing and which errors are you getting?

**Comment by MMaiero** [comment]
Closing due to no feedback.
@Amar82 Feel free to reopen if needed.
