### ISSUE TITLE
Is MQTT 5 migration for Cloud Service planned ?

### ISSUE THREAD

**Issue by svilenvul** [eclipse/kura#2062]
I was reading the documentation about Eclipse Kura MQTT namespace and asked myself are there any plans for migration to MQTT 5 ?

From what I read so far MQTT 5 adds support for application specific headers and standardizes Requst/Response pattern with Reply topic. Correct me if I am wrong, but as these features are not available in MQTT 3.x, Eclipse Kura's implementation relies on Reply topic in the payload. 

This is major release (after 4 years !) that has no backwards compatibility and adds a lot of new features to the protocol stack. It could be very beneficial to project.

**Comment by cdealti** [comment]
> I was reading the documentation about Eclipse Kura MQTT namespace and asked myself are there any plans for migration to MQTT 5 ?

Hi. There are no plans to migrate to MQTT v5 yet. I've heard that Paho will have a release supporting it by July.

> From what I read so far MQTT 5 adds support for application specific headers and standardizes Requst/Response pattern with Reply topic. Correct me if I am wrong, but as these features are not available in MQTT 3.x, Eclipse Kura's implementation relies on Reply topic in the payload.

You are right, a long time ago Kura developed its own request/response protocol on top of MQTT v3.
On top of that, Kura, Kapua and Hono have committed to develop an alternative protocol, but still on top of MQTT v3.1.1.
