### ISSUE TITLE
DataService enable.recovery.on.connection.failure is causing a reboot systematic on first boot

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#2067]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Kura 3.2 and previous
    - Platform : Reliagate 10-11
           
- Textual description of the issue:

WAN interface = Cellular
Configuration of the DataService enabling "enable.recovery.on.connection.failure" feature after enabling the watchdog. 
Reboot the gateway (power off/power on), on the first boot, the Watchdog service triggers a reboot while the connection is established. After this reboot everything is ok.

[kura.log](https://github.com/eclipse/kura/files/1941581/kura.log)

**Comment by MMaiero** [comment]
@pierrepitiot Could it be that the reboot is caused by the date update?
I've tested in my environment and, if the RTC backup battery is not enabled, the system boots with a 2017 date. When the connection goes up, the date is updated and this causes the watchdog to trigger the reboot.

**Comment by pierrepitiot** [comment]
I confirm that the issue is related to the RTC backup. If the battery is enabled, the problem does not exist. I think we can close the issue.

**Comment by cdealti** [comment]
The WatchdogService should be modified to use [System.nanoTime](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--) to compute time differences that are not affected by changes to the system time/date.
