### ISSUE TITLE
Native Support for UP Development Kit

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#2078]
Let's use this issue to track adding native support for the UP Development Kit [1]. The kit is based on Ubuntu 16.04 server and the Intel Celeron processor. So, adding support for this should also allow support for other x86 64-bit platforms.

[1] https://software.intel.com/en-us/iot/hardware/up-squared-grove-dev-kit

**Comment by ctron** [comment]
There is PR #2093 for supporting this on CentOS 7

**Comment by kartben** [comment]
@ctron niiice! I think it would be nice to also support Ubuntu (although I of course get where you're coming from :-)) as asking people to reflash their entire system is not the best "sales pitch" for promoting how easy it is to install Kura. Even better might actually be to make the main "distro" and x86 docker image?

**Comment by kartben** [comment]
cc @fromgilbert

**Comment by ctron** [comment]
@kartben If you want Kura in a container you can use: https://hub.docker.com/r/ctron/kura-emulator/ which is based on https://github.com/ctron/kura-emulator

**Comment by kartben** [comment]
That's great but neither of these seem to maintained by the project. I
think this would have a much bigger impact to maintain whatever is in your
personal repo as part of the Kura repo, and have the documentation and
website refer to an Eclipse Kura branded image :-)

Le lun. 14 mai 2018 à 23:52, Jens Reimann <notifications@github.com> a
écrit :

**Comment by ctron** [comment]
Oh I completely agree that is would be better to have something offered by the project itself. I just wanted to mention that, if you need one right now, you don't have to start from scratch to make your own docker image.
