### ISSUE TITLE
Include camel-amqp component jar in base distribution

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#208]

**Comment by ctron** [comment]
Started CQs:

11939 – Apache Camel AMQP Version: 2.17.2
11940 – Apache Qpid Client Version: 0.28
11941 – Apache Qpid Common Version: 0.28
11942 – Apache Camel JMS Version: 2.17.2
11945 – Apache Camel Spring Version: 2.17.2
11946 – org.springframework.jms Version: 4.2.4.RELEASE (using Orbit CQ10971)
11947 – org.springframework.context Version: 4.2.4.RELEASE (using Orbit CQ10966)
11948 – org.springframework.beans Version: 4.2.4.RELEASE (using Orbit CQ10965)
11949 – org.springframework.aop Version: 4.2.4.RELEASE (using Orbit CQ10963)
11950 – org.springframework.expression Version: 4.2.4.RELEASE (using Orbit CQ10969)
11951 – spring-tx 4.2.4.RELEASE (using Orbit CQ11637)

**Comment by cdealti** [comment]
@ctron what's the status of this?

**Comment by ctron** [comment]
I will check.

**Comment by ctron** [comment]
I will do this in combination with #2057
