### ISSUE TITLE
emitAllReadChannels method doesn't handle Runtime exceptions

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2102]
The `emitAllReadChannels` method in `WireAsset` class doesn't handle the unchecked exceptions, but only `KuraException`. So, if an unchecked exception as `RuntimeException` is thrown, it is simply passed to the upper layer and this can stop the current thread.

For example, if a Driver doesn't support readings, the `emitChannelRecords` throws an `IllegalArgumentException` that is not caught by the `emitAllReadChannels` method. The results is that the current thread on Wires is closed.

**Comment by nicolatimeus** [comment]
FYI if any unchecked exception is thrown during the `update()` method of a `Wire`, (for example inside a `onWireReceive()` method), and it is not handled, it will be eventually handled by the WireAdmin [1] which will emit an event that can be received by registering a WireAdminListener, but might not be logged.

For the WireAsset I agree that we can catch and log any unchecked exceptions emitted by the Driver.

[1] https://github.com/eclipse/rt.equinox.bundles/blob/master/bundles/org.eclipse.equinox.wireadmin/src/org/eclipse/equinox/internal/wireadmin/WireImpl.java#L188
