### ISSUE TITLE
Review supported platforms

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2114]
I believe we should have a review of the supported platforms, maybe cleaning out the current list.

**Comment by MMaiero** [comment]
I believe that the following platforms can be removed:

- Fedora 
- Fedora-nn
- Intel Edison-nn
- Raspberry-pi
- Raspberry-pi-nn
- Raspberry-pi-bplus
- Raspberry-pi-bplus-nn

Maybe we could create a specific profile for
- Raspberry-pi-3
- Raspberry-pi zero w

Still wondering if the 
- pcengines-apu
- pcengines-apu-nn 

profiles will have any future

**Comment by MMaiero** [comment]
Discussed during the weekly meeting.

The proposal is available in the meeting notes: https://dev.eclipse.org/mhonarc/lists/kura-dev/msg01002.html

**Comment by cdealti** [comment]
closing
