### ISSUE TITLE
[website] HTML content for the new HTML website is invalid

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#2131]
There seems to be a few issues with the HTML content of the new website, and some closing tags are not properly matched with the corresponding ones, and vice-versa.

See https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.eclipse.org%2Fkura%2F

**Comment by nicolatimeus** [comment]
Should be ok now. Remaining issues are likely related to the theme.

**Comment by cdealti** [comment]
closing
