### ISSUE TITLE
Cloud service selection in examples

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2138]
In the examples provided by Kura (iBeaconScanner/Advertiser, EddystoneScanner/advertiser, ecc.) it is not possible to select the Cloud service to use to publish messages.
So, if more than one Cloud service is instantiated, the examples choose a random one with unexpected results...

**Comment by MMaiero** [comment]
Maybe this can be associated to the new Cloud Connection APIs

**Comment by MMaiero** [comment]
Will be solved by pr #2154
