### ISSUE TITLE
Camel XML router service missing

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2143]
"Camel XML router" service is gone now that Camel has been upgraded.

- Component affected:
  - [] Distribution
    - Platform: RPi 3
    - Kura version affected: 3.3.0-SNAPSHOT
    - Java version: 1.8.0_65
    - Host OS: Raspbian
    - Host OS version: 9 Lite

**Comment by MMaiero** [comment]
@ctron Could you have a look at this, please?

**Comment by ctron** [comment]
Yes, it is gone as it became a configurable component. You should be able the create a new instance using the Kura Web UI.

**Comment by MMaiero** [comment]
Do we have QA tests on this that need an update?

**Comment by markoer** [comment]
One or two tests will require a minor update, yes.

**Comment by MMaiero** [comment]
@markoer Could you please update the tests and share the changes with @ctron? Then, I believe, we can close this issue.

Thanks

**Comment by markoer** [comment]
Added to the beginning of CAMEL-XML-001:
In Services -> + add a new org.eclipse.kura.camel.xml.XmlRouterComponent component and name it CamelXMLRouter.
