### ISSUE TITLE
Missing tinyb package

### ISSUE THREAD

**Issue by CobraFlow** [eclipse/kura#2144]
Please describe the issue you are encountering in Kura.
Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb):
    - Platform (e.g. Raspberry pi 2):
    - Kura version affected (e.g. Kura 3.1.0): 
    - Java version (paste the result of **java -version**:
    - Host OS (e.g. Debian): 
    - Host OS version

  - [Y] Development environment
    - Version: develop branch
    - Operating system (Mac OS, Windows, Linux): Linux
    - OS Version: Ubuntu 16.04 LTS
    - IDE Version:
    - Host System Java Version:  1.8.0_131
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:

From a clean clone, I am unable to build Kura using build-all.sh.
I get Missing requirement: org.eclipse.kura.ble.provider 1.0.200 requires 'package tinyb 1.0.0' but it could not be found
Maven does download a tinyb-1.0.0.jar earlier in the build and it exists in the maven repo.

**Comment by CobraFlow** [comment]
Update.
Deleted initial tinyb folder from ~/.m2 and now build goes much further . 
Now fails not finding :
`groupId org.eclipse.kura.feature`
`artifactId org.eclipse.kura.driver.s7plc`
`packaging dp`
`version 1.0.100`

**Comment by CobraFlow** [comment]
Update.

The s7plc artifact is created but with a version of 1.0.200.

**Comment by MMaiero** [comment]
Hi @CobraFlow,
any update on this?
I've tested it, but it works for me.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Closing as there seem to be no update.

Please feel free to reopen if needed.
