### ISSUE TITLE
[Bluetooth] Expose buzzer and leds on SensorTag Example

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#215]

**Comment by ccustine** [comment]
@pierantoniomerlino Are you working on this currently?  If not, I may be able to do this for you in the next 1-2 weeks. Let me know!

**Comment by pierantoniomerlino** [comment]
@ccustine 
Hi,
thank you for the proposal!
I'm not working on it, so feel free to work on it.

BTW, time ago I developed a Android app based on the official TI SensorTag app and I used the buzzer and leds. Here the code: https://github.com/eurotech/edc-examples/tree/master/SensorTag

**Comment by pierantoniomerlino** [comment]
Hi @ccustine!

Did you have the possibility to work on this issue? Do you need some testing?

**Comment by pierantoniomerlino** [comment]
Hi @ccustine,

did you work on this issue? Since we need it for a demo, could you share something? Otherwise it is not a problem for me to work on it.

Thank you!

**Comment by pierantoniomerlino** [comment]
Solved by #246.

**Comment by ccustine** [comment]
I tested this thoroughly yesterday and everything works well.

**Comment by cdealti** [comment]
@ccustine Thanks! 
By the way how is the buzzer on your SensorTag 2? On mine is very weak and unstable.
It has a firmware dated July 2015. I've downloaded the latest BLE stack from TI to see if there is a later version or if we can improve the situation by compiling a new one.

**Comment by ccustine** [comment]
@cdealti Yeah it seems like the frequency is very low so the sound is quite bad. Maybe that is for reduced power requirements :-)

**Comment by cdealti** [comment]
@ccustine you know the alarm on cheap quarz watches... They are loud and run off a coin battery. Tomorrow i'll take a look to the firmware. I'm pretty sure it can work better. I'll let you know my findings
________________________________
Da: Chris Custine <notifications@github.com>
Inviato: mercoledì 8 giugno 2016 21.47.50
A: eclipse/kura
Cc: De Alti, Cristiano; Mention
Oggetto: Re: [eclipse/kura] [Bluetooth] Expose buzzer and leds on SensorTag Example (#215)


@cdealti<https://github.com/cdealti> Yeah it seems like the frequency is very low so the sound is quite bad. Maybe that is for reduced power requirements :-)

-

**Comment by cdealti** [comment]
@ccustine I have a new firmware with improved buzzer support [here](https://github.com/cdealti/sensortag). Sounds good!
