### ISSUE TITLE
kura-raspberrypi(scanner) and DEVICES-WEMOS-D1-MINI-WIFI

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#2168]
Hello,
who has Idea for binding kura-raspberrypi(scanner) and DEVICES-WEMOS-D1-MINI-WIFI?

thanks in advance

**Comment by MMaiero** [comment]
Hi,
what is the setup that you are trying to achieve?

Best regards,
Matteo

**Comment by marentwickler** [comment]
@MMaiero
Hi MMaiero,

-Kura 3.1 on raspberrypi 3 
-WEMOS-D1-MINI-WIFI Arduino

I will get each measure values from devices(WEMOS-D1-MINI-WIFI Arduino) per wifi in real time and i forward it to cloud as json-package.

I prefer not using http-protocol for reading data from devices(WEMOS-D1-MINI-WIFI Arduino),i prefer , that kura scan wifi-IP addresses and read each measurements values from each device .

Best regards,

**Comment by MMaiero** [comment]
Hi,
we never tested those devices so we cannot provide precise information if it will be working or not.

But, maybe, you could use the access point functionality of Kura instead to have Kura scan for the different devices.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Closing for now due to inactivity. Feel free to reopen it, if needed.
