### ISSUE TITLE
Enable HTTPS on Eclipse Kura 3.1.1

### ISSUE THREAD

**Issue by mpalmier74** [eclipse/kura#2174]
As a user of Eclipse Kura 3.1.1 I want to enable HTTPS access to the Kura web console so that transactions between my web browser and Kura cannot be subject to man in the middle attack.

I tried to setup Eclipse Kura 3.1.1 based on Rohit Dubey suggestion at link:
https://dev.eclipse.org/mhonarc/lists/kura-dev/msg00712.html

Dubey's solution works fine on Eclipse Kura 2.1.0 but it does not work in Eclipse Kura 3.1.0

In particular after changing the configuration in config.ini port 80 appears to be disabled (expected), but port 8443 is not opened. I can verify this by doing "netstat -na | grep 8443" which returns no result.
I could not find in kura.log and kura-console.log any hint about the problem.

I'm filing this as an issue based on a response to similar question in Eclipse Kura forum:
https://www.eclipse.org/forums/index.php/t/1090979/

**Comment by MMaiero** [comment]
Hi, 
did you correctly open the https port setting it in Kura's firewall configuration?

Best regards,
Matteo

**Comment by MMaiero** [comment]
Hi, 
any update on this?

Can this be closed?

Best regards,
Matteo

**Comment by mpalmier74** [comment]
Hi Matteo, sorry for the long delay. This issue can be closed as the problem was about a firewall rule
