### ISSUE TITLE
Cannot find Target Platform Location during build

### ISSUE THREAD

**Issue by fwaznad** [eclipse/kura#2176]
Hi,

I followed the instruction here https://wiki.eclipse.org/Kura/Getting_Started for kura eclipse configuration. I installed  "Eclipse for Committers" and followed the instruction. Unfortunately when I run eclipse kura Emulator there are problem occurred. it showed 
`The org.eclipse.osgi plug-in is missing from this configuration.`
The target platform are not found as image below. What is the step that I missed?
 Please help
![image4211](https://user-images.githubusercontent.com/42095161/43677996-054d6a78-983e-11e8-9700-2957c6159bb9.png)

Maven version is:
`Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-121-generic", arch: "amd64", family: "unix"
`
When I run mvn clean install from kura repo. Error occured,

```
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.12.50' from location file:////home/fawwaz/kura-iot/kura/org.eclipse.kura.api/../target-definition/equinox_3.12.50/repository/: URI has an authority component -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.12.50' from location file:////home/fawwaz/kura-iot/kura/org.eclipse.kura.api/../target-definition/equinox_3.12.50/repository/
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

```
Thanks

**Comment by MMaiero** [comment]
Hi, it seems that the target platform is not filled.
You should follow the single steps build: https://wiki.eclipse.org/Kura/Getting_Started#Single_step_build
and see if it succeeds.

Otherwise you could also use the oomph setup as described here: https://eclipse.github.io/kura/dev/kura-setup.html

Best regards,
Matteo

**Comment by fwaznad** [comment]
Thanks Matteo, I will try to setup it again. I followed the oomph setup several times but no luck.

**Comment by MMaiero** [comment]
Closing for now due to inactivity. Feel free to reopen it, if needed.
