### ISSUE TITLE
[Test] Cleanup tycho-surefire-plugin configurations a bit 

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#2185]
I've noticed a few things on the tycho-surefire-plugin configuration that maybe need some cleanup.

In the Kura parent pom:
```
<plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-surefire-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <providerHint>junit4</providerHint>
                    <parallel>both</parallel>
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                    <argLine>${jacocoArgs} -Deurotech.framework.mode=emulator -Dds.showtrace=true</argLine>
                    <dependencies>
                        <dependency>
                            <type>p2-installable-unit</type>
                            <artifactId>org.eclipse.equinox.ds</artifactId>
                        </dependency>
                    </dependencies>
                </configuration>
</plugin>
```
According to the documentation, `<parallel>` and `<useUnlimitedThreads>` only apply to the `junit47` provider.

The above plugin configuration is overridden by the one in `tests/pom.xml`

```
<plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-surefire-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <argLine>${tycho.argline}</argLine>
                    <failIfNoTests>false</failIfNoTests>
                    <providerHint>junit4</providerHint>
                    <useUnlimitedThreads>false</useUnlimitedThreads>
                    ...
                </configuration>
</plugin>
```

Again,  `<useUnlimitedThreads>` should not be necessary with `junit4`.

As all tests inherit the plugin configuration from `tests/pom/xml`, I believe the configuration in the parent pom is useless and even misleading.

In the configuration of the `target-platform-configuration` plugin in `tests/pom.xml` an `extraRequirement` for `org.eclipse.kura.api` should be automatically resolved and hence not necessary. 

Also the `extraRequirement` for `org.hamcrest` should be automatically resolved if we used JUnit provided by the Kura target platform as opposed to the one resolved from:

```
<dependencies>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
</dependencies>
```

Also, I cannot find in the Tycho documentation any reference to <argLine> and <resolver>: 
```
<plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>target-platform-configuration</artifactId>
                <configuration>
                    <pomDependencies>consider</pomDependencies>
                    <argLine>-consoleLog</argLine>
                    <resolver>p2</resolver>
```
And do we really need `<pomDependencies>consider</pomDependencies>`?

@markoer what do you think?

**Comment by markoer** [comment]
Removal of extra <code>org.eclipse.kura.api</code> is OK, so is cleanup of junit47-related settings. Move of the offending configuration to test/pom.xml is appropriate.
org.hamcrest must remain where it is because otherwise mockito will not resolve its dependencies.

Changes are available in #2223.
