### ISSUE TITLE
NPE during package installation via cloud

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2215]
An additional property is needed during cloud package installation. Without it an NPE is thrown when publish is called.

- Component affected:
  - [ ] Distribution
    - Installer name: kura_3.3.0_SNAPSHOT_raspberry-pi-2-3_installer.deb
    - Platform: Raspberry pi 3
    - Kura version affected: Kura 3.3.0-SNAPSHOT 
     
- Textual description of the issue:
Install example publisher package through cloud (e.g. EC). It will start downloading and fail at first progress notification when this.cloudServiceImpl.publish(publishMessage) is called in NotificationPublisherImpl.publish(). Failure would happen in CloudServiceImpl.publish(), line 939.

Stack trace is unfortunately not available.

Fix is available in #2214.

**Comment by nicolatimeus** [comment]
Closed by #2214
