### ISSUE TITLE
CloudConnectionStatusServiceImpl does not cancel workers on component deactivation

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#222]
If the GPIOService disappears at runtime (e.g in emulator mode, one will stop or uninstall the emulator.GPIO bundle), the CloudConnectionStatusService keeps using a stale EmulatedPin. 
notificationWorker should be canceled on deactivation of the component.

**Comment by cdealti** [comment]
@kartben a PR with the fix is welcome ;-)

**Comment by cdealti** [comment]
@kartben ping

**Comment by cdealti** [comment]
@kartben we are ready to cut a release branch. If you have a PR for develop, we will be glad to merge it

**Comment by MMaiero** [comment]
@LucaDazi Could you please repost the PR?

**Comment by MMaiero** [comment]
Reminder to check if the issue has been solved over time. @MMaiero @nicolatimeus @pierantoniomerlino
