### ISSUE TITLE
Linker issue with tinyb

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2232]
In one of he last commits a new linker issue has been introduced like we had it in the past with tinyb:

~~~
Framework is not running in emulation mode
Native code library failed to load.
java.lang.UnsatisfiedLinkError: /tmp/kura/data/org.eclipse.osgi/53/0/.cp/lib/libtinyb.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/kura/data/org.eclipse.osgi/53/0/.cp/lib/libtinyb.so)
~~~

This currently breaks CentOS/RHEL. I think this should be fixed before the 3.3/4 release.

**Comment by pierantoniomerlino** [comment]
@ctron Probably the new tinyb lib broke something... On which device/OS did you find this issue? I'll try to reproduce the problem.

**Comment by pierantoniomerlino** [comment]
@ctron Yes, it's like #2091

**Comment by spnettec** [comment]
Can't compile ble provider

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project org.eclipse.kura.ble.provider: Compilation failure: Compilation failure:
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeDeviceImpl.java:[247]
[ERROR] 	result = this.device.remove();
[ERROR] 	                     ^^^^^^
[ERROR] The method remove() is undefined for the type BluetoothDevice
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[34]
[ERROR] 	import tinyb.TransportType;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^
[ERROR] The import tinyb.TransportType cannot be resolved
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[289]
[ERROR] 	removedDevices = this.adapter.removeDevices();
[ERROR] 	                              ^^^^^^^^^^^^^
[ERROR] The method removeDevices() is undefined for the type BluetoothAdapter
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[298]
[ERROR] 	this.adapter.setDiscoveryFilter(uuids, rssi, pathloss, toTransportType(transportType));
[ERROR] 	                                                       ^^^^^^^^^^^^^^^
[ERROR] The method toTransportType(BluetoothTransportType) from the type BluetoothLeAdapterImpl refers to the missing type TransportType
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[303]
[ERROR] 	this.adapter.setRssiDiscoveryFilter(rssi);
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method setRssiDiscoveryFilter(int) is undefined for the type BluetoothAdapter
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[306]
[ERROR] 	private TransportType toTransportType(BluetoothTransportType type) {
[ERROR] 	        ^^^^^^^^^^^^^
[ERROR] TransportType cannot be resolved to a type
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[309]
[ERROR] 	return TransportType.AUTO;
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] TransportType cannot be resolved to a variable
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[311]
[ERROR] 	return TransportType.BREDR;
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] TransportType cannot be resolved to a variable
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[313]
[ERROR] 	return TransportType.LE;
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] TransportType cannot be resolved to a variable
[ERROR] /Users/heyoulin/iot-kura-develop/git/kura/kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/BluetoothLeAdapterImpl.java:[315]
[ERROR] 	return TransportType.AUTO;
[ERROR] 	       ^^^^^^^^^^^^^
[ERROR] TransportType cannot be resolved to a variable
[ERROR] 13 problems (10 errors, 3 warnings)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the b

**Comment by pierantoniomerlino** [comment]
@spnettec Hi, you'd try to delete you local repository (~/.m2/repository/tinyb) and build kura again.

**Comment by ctron** [comment]
@pierantoniomerlino CentOS/RHEL 7.x

**Comment by spnettec** [comment]
@pierantoniomerlino I have tried but no lucky. This just can fix eclipse classpath error. The  build error still there.

**Comment by spnettec** [comment]
delete  local repository (~/.m2/repository/p2/osgi/bundle/tinyb) and build kura again is ok.
