### ISSUE TITLE
Commit 2149c3280ae38cd77ca5edc619af2b5e80d5668a causes JVM to segfault

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2235]
The changes in commit 2149c3280ae38cd77ca5edc619af2b5e80d5668a cause the JVM to reproducibly segfault for me.

The segfault happens at a later state. When the JVM tries a hostname lookup, the "dl-init" call on `libnss_dns.so.2` causes a segfault by calling a wrong memory address.

Reverting commit 2149c3280ae38cd77ca5edc619af2b5e80d5668a does fix this issue.

**Comment by MMaiero** [comment]
Could you please link the PR that introduced the offending commit?
Searching for it in the list of commits returns nothing, in my case.

**Comment by ctron** [comment]
Sorry, I linked the commit of me reverting this actual commit. The actual commit is: 2149c3280ae38cd77ca5edc619af2b5e80d5668a

I think it came from PR #2178
