### ISSUE TITLE
Could you please add typed JSON  to CloudPayloadJsonDecoder?

### ISSUE THREAD

**Issue by spnettec** [eclipse/kura#2240]
According this [wiki:](https://github.com/eclipse/kapua/wiki/K-Payload-JSON-Format)

I add this patch:

diff --git a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
index 7ed8385..9b784d2 100644
--- a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
+++ b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
@@ -142,7 +142,7 @@
             String name = member.getName();
             JsonValue value = member.getValue();
 
-            Object javaValue;
+            Object javaValue = null;
             if (value.isNumber()) {
                 try {
                     javaValue = value.asLong();
@@ -153,7 +153,27 @@
                 javaValue = value.asBoolean();
             } else if (value.isString()) {
                 javaValue = value.asString();
-            } else {
+            } else if (value.isObject()) {
+                JsonObject.Member member0 = value.asObject().iterator().next();
+                String name0 = member0.getName();
+                JsonValue value0 = member0.getValue();
+                if (name0.equalsIgnoreCase("string"))
+                    javaValue = value0.asString();
+                else if (name0.equalsIgnoreCase("double"))
+                    javaValue = value0.asDouble();
+                else if (name0.equalsIgnoreCase("float"))
+                    javaValue = value0.asFloat();
+                else if (name0.equalsIgnoreCase("int") || name0.equalsIgnoreCase("int32")
+                        || name0.equalsIgnoreCase("int64"))
+                    javaValue = value0.asInt();
+                else if (name0.equalsIgnoreCase("bool"))
+                    javaValue = value0.asBoolean();
+                else if (name0.equalsIgnoreCase("long"))
+                    javaValue = value0.asLong();
+                else if (name0.equalsIgnoreCase("bytes"))
+                    javaValue = Base64.getDecoder().decode(value0.asString());
+            }
+            if (javaValue == null) {
                 throw new IllegalArgumentException(String.format("Unparsable metric %s", name));
             }
             payload.addMetric(name, javaValue);

**Comment by spnettec** [comment]
Sorry for the format. Paste agin

`diff --git a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
index 7ed8385..9b784d2 100644
--- a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
+++ b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
@@ -142,7 +142,7 @@
             String name = member.getName();
             JsonValue value = member.getValue();
 
-            Object javaValue;
+            Object javaValue = null;
             if (value.isNumber()) {
                 try {
                     javaValue = value.asLong();
@@ -153,7 +153,27 @@
                 javaValue = value.asBoolean();
             } else if (value.isString()) {
                 javaValue = value.asString();
-            } else {
+            } else if (value.isObject()) {
+                JsonObject.Member member0 = value.asObject().iterator().next();
+                String name0 = member0.getName();
+                JsonValue value0 = member0.getValue();
+                if (name0.equalsIgnoreCase("string"))
+                    javaValue = value0.asString();
+                else if (name0.equalsIgnoreCase("double"))
+                    javaValue = value0.asDouble();
+                else if (name0.equalsIgnoreCase("float"))
+                    javaValue = value0.asFloat();
+                else if (name0.equalsIgnoreCase("int") || name0.equalsIgnoreCase("int32")
+                        || name0.equalsIgnoreCase("int64"))
+                    javaValue = value0.asInt();
+                else if (name0.equalsIgnoreCase("bool"))
+                    javaValue = value0.asBoolean();
+                else if (name0.equalsIgnoreCase("long"))
+                    javaValue = value0.asLong();
+                else if (name0.equalsIgnoreCase("bytes"))
+                    javaValue = Base64.getDecoder().decode(value0.asString());
+            }
+            if (javaValue == null) {
                 throw new IllegalArgumentException(String.format("Unparsable metric %s", name));
             }
             payload.addMetric(name, javaValue);
`

**Comment by spnettec** [comment]
```
diff --git a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
index 7ed8385..9b784d2 100644
--- a/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
+++ b/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonDecoder.java
@@ -142,7 +142,7 @@
             String name = member.getName();
             JsonValue value = member.getValue();
 
-            Object javaValue;
+            Object javaValue = null;
             if (value.isNumber()) {
                 try {
                     javaValue = value.asLong();
@@ -153,7 +153,27 @@
                 javaValue = value.asBoolean();
             } else if (value.isString()) {
                 javaValue = value.asString();
-            } else {
+            } else if (value.isObject()) {
+                JsonObject.Member member0 = value.asObject().iterator().next();
+                String name0 = member0.getName();
+                JsonValue value0 = member0.getValue();
+                if (name0.equalsIgnoreCase("string"))
+                    javaValue = value0.asString();
+                else if (name0.equalsIgnoreCase("double"))
+                    javaValue = value0.asDouble();
+                else if (name0.equalsIgnoreCase("float"))
+                    javaValue = value0.asFloat();
+                else if (name0.equalsIgnoreCase("int") || name0.equalsIgnoreCase("int32")
+                        || name0.equalsIgnoreCase("int64"))
+                    javaValue = value0.asInt();
+                else if (name0.equalsIgnoreCase("bool"))
+                    javaValue = value0.asBoolean();
+                else if (name0.equalsIgnoreCase("long"))
+                    javaValue = value0.asLong();
+                else if (name0.equalsIgnoreCase("bytes"))
+                    javaValue = Base64.getDecoder().decode(value0.asString());
+            }
+            if (javaValue == null) {
                 throw new IllegalArgumentException(String.format("Unparsable metric %s", name));
             }
             payload.addMetric(name, javaValue);
```

**Comment by MMaiero** [comment]
Hi,
thank you for the comment.
I believe you should provide a pull request with your changes, in order also to give proper rights for your contribution and to start a discussion about this topic.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Hi @spnettec any update on this topic?

**Comment by spnettec** [comment]
Hi @MMaiero  
Sorry for long time reply. I'm a little busy recently. I have not set up Create Pull Requests environment. Below attachment patch is used in my test project. The Publisher can publish json format topic to the Subscriber and then write to opc ua. I use prosys-opc-ua-simulation-server tool.
[CloudPayloadJsonDecoder.patch.txt](https://github.com/eclipse/kura/files/2670574/CloudPayloadJsonDecoder.patch.txt)

[snapshot_1544590598160.xml.txt](https://github.com/eclipse/kura/files/2670577/snapshot_1544590598160.xml.txt)

**Comment by MMaiero** [comment]
We need to wait for your Pull request to be able to process it and eventually merge into the code.

Please have a look at: https://www.eclipse.org/contribute/ and, in particular, to the "Fix Bugs or Implement Enhancements" section.

Best regards,
Matteo
