### ISSUE TITLE
Cloud connections table refresh

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2263]
After a new cloud connection is added the table with the list of available connections is (sometimes) not refreshed. Manual refresh or page reload helps.

Component affected:
- [ ] Distribution
  - Installer name kura_4.0.0-SNAPSHOT_raspberry-pi-2-3_installer.deb
  - Platform Raspberry Pi 3
  - Kura version affected 4.0.0-SNAPSHOT

**Comment by MMaiero** [comment]
@markoer Could you please verify that PR #2280 solves the issue?

**Comment by markoer** [comment]
Looks OK in RC b49.
