### ISSUE TITLE
[Cellular] PDP Auth failed using context #1 in 4G network (Telit LE910-EU1 and LE910-V2 EU, possibly NA versions)

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#2264]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb): All
    - Platform (e.g. Raspberry pi 2): All
    - Kura version affected (e.g. Kura 3.1.0): 3.2.0 and earlier releases
    - Java version (paste the result of **java -version**: NA
    - Host OS (e.g. Debian):  NA
    - Host OS version NA

  - [ ] Development environment
    - Version: 
    - Operating system (Mac OS, Windows, Linux):
    - OS Version:
    - IDE Version:
    - Host System Java Version:
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:

With  Kura 3.2.0 and earlier versions, network registration fails using context #1 in a 4G network.
Found in the following products:
* Telit LE910-EU1 fw 20.00.413
* Telit LE910-EU V2 fw 20.00.402

If the 4G network is **not** available, the setup generated by Kura works fine. In this case the modem can automatically update to 4G if the network becomes available after the initial authentication in 2G or 3G.

However, by default, the above Telit modems are configured to always prefer a 4G network if this is available and in this case the Kura setup is such to cause a network registration reject (User Authentication failed) by the network.

The following manual configuration has proven to work reliably with an TIM M2M SIM and PAP authentication, in a 4G, 3G and 2G network (the mobile operator usually provides all three access technologies).

```
AT+CREG=2 # For debug purposes: enable network registration URC
AT#SIMDET=1 # Needed after a power cycle if Kura has not already done this
AT+COPS=2 # Deregister from network
AT+CGDCONT? # List PDP contexts
AT+CGDCONT=<CID> # Delete all CIDs but CID 1
AT+CGDCONT=1,"IP",<APN> # Set APN for CID 1
AT#PDPAUTH=1,1,< username>,<password> # Set credentials for PDP auth for CID 1
AT+COPS=0 # Register to the network. You should see URCs in the terminal
```
CID 1 (APN and auth) and operator selection are saved to the NVM so this would be only needed once, when the configuration changes. Network de-registration and registration takes some time and are asynchronous to the AT command. It does not make sense to do this in the pppd chat script.

Telit technical support suggests to avoid setting again CID 1 in the pppd chat script.
Remove the line

```
OK      AT+CGDCONT=<CID>,"IP",<APN>
```

Also make sure to specify CID 1 in the dial string

```
ATD*99***1#
```

Note that specifying the PDP authentication with the `AT#PDPAUTH` command is mandatory to register to a 4G network and in this case the PDP authentication credentials in `/etc/ppp/peer/pppX` are redundant (indeed they could be removed). However they are still necessary for a 3G or 2G network where `AT#PDPAUTH` alone does not allow to establish the PPP link.

## Notes
Telit modems can be forced using network access technologies using the `AT+WS46` command. For example, for the LE910-EU1 (which is 4G/2G modem)

```
AT+WS46=30 # 4G preferred with fallback to 2G
AT+WS46=12 # 2G only
AT+WS46=28 # 4G only
```
**Note** that switching between selection using the above command may cause the serial port used by pppd to stop responding to AT commands or return to command mode (even using `ATH` or `AT+CHUP` from the other serial port). This issue has been observed to also happen in other circumstances that need to be further investigated with Telit. Luckily Kura will reset the modem if this occurs.

The AT command `AT#REBOOT` can be used to reboot the modem (at least during system level testing). It is faster than the reset by pin but maybe less reliable.

**Comment by cdealti** [comment]
There's no easy fix for this.
First this (commit)[https://github.com/eclipse/kura/commit/52ebd68386ce2129890c4a59fd09908c2b4580cd] forces using CID 2 for LE910-EU1 and LE910-V2 EU, which is not always appropriate.

Second, to support these SIMs, the PDP context MUST not be set in the chat script because the Telit modem will attempt to update it with the network when pppd starts. This may easily lead to an unresponsive modem that would trigger a modem reset, ending up in a loop.

Please note that the PDP context and authentication are stored in the NVM of the modem so it would be enough (and much more reliable) to do this once when a new configuration is applied (from the UI or from a snapshot).

Following this approach the source of truth for the cellular interface configuration would be split between the pppd configuration files (including kuranet.conf) and the NVM of the modem.

Now, the first point above, suggests to move the PDP context (APN) to kuranet.conf (as it MUST be removed from the chat script). The authentication MUST be retained in the pppd configuration files and so there's no need to store it in kuranet.conf.

A reliable approach would be the following.

On modem detection (included after a reset), if the modem's interface pppX is not already up, the modem is deregistered, configured and registered again.

**Comment by cdealti** [comment]
@dwoodard1 can you please test on a LE910-V2 NA with Verizon Wireless? Just to make sure I've not introduced a regression.

**Comment by cdealti** [comment]
Updated to support LE910-VA NA with AT&T fw which does not support the PDP authentication AT command.

**Comment by pierantoniomerlino** [comment]
Successfully tested on BoltGATE 20-25 (with systemD) with Telit LE910 EU v2.
I deleted the context 2 before every tests. Works with Vodafone SIM (without authentication and 4G) and Arkessa SIM (with authentication but 2G).

**Comment by dwoodard1** [comment]
@cdealti I can confirm that this PR works with both AT&T and Verizon LTE.
