### ISSUE TITLE
[Kura 4.0.0 QA] Adding wires components in IE/Edge

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2271]
Adding components has new issues in IE and Edge browsers.

IE:
- drag a component to canvas (drop target is not rendered)
- type in the name
- component should show up on the desired place
  - instead the component is out of viewport
- add another component by dragging it to canvas (and entering its name)
  - component should show up on the desired place
  - instead it is rendered next to the previous one and they are both panned into view
- all this repeats

Loggers 1-3 (bottom left) were clicked, the rest (4-9) were dragged to canvas. I used no manual panning until the end when I pressed zoom-to-fit.
![image](https://user-images.githubusercontent.com/22816717/46610998-b4e8c580-cb0c-11e8-85c9-7ea6a03ee4e3.png)

[Edit] Note: IE 11 upd. vers. 11.0.65 (older) on Win 7 behaves as expected i.e. drop targets are rendered and respected.

Edge:
- drag a component to canvas (drop target is rendered)
- type in the name
- component should show up on the desired place
  - instead the component renders centered
- add another component by dragging it to canvas (and entering its name)
  - component should show up on the desired place
  - instead it is rendered on top of the previous one
- add another component by clicking on it (and entering its name)
  - component should show up next to other components and panned to center
  - instead it is rendered on top of the previous one
- view can be panned resulting in the same behavior

4 loggers stacked on top of each other (dragged and/or clicked):
![image](https://user-images.githubusercontent.com/22816717/46610815-1bb9af00-cb0c-11e8-9ab9-c31c33c10e9b.png)

System
- Component affected:
  - [ ] Distribution
    - Platform Raspberry pi 3
    - Kura version affected: Kura 4.0.0 RC b47

  - [ ] Browser
    - Operating system: Windows
    - OS Version: 10
    - Browser: IE upd. vers. 11.0.85, Edge 42

**Comment by cdealti** [comment]
@markoer can you close this if it has been fixed?

**Comment by markoer** [comment]
Issue is fixed (verified in RC b48). If the fix affects something else, a new issue can be added.
