### ISSUE TITLE
Firewall, "Open port" dialog valiation

### ISSUE THREAD

**Issue by darionct** [eclipse/kura#2278]
Kura 4.0.0 RC 46, tested in Firefox 62
    
When adding a new port to firewall, if port value is incorrect (duplicate), validation message is not presented but dialog does not allow neither to "Submit nor "Cancel".

-Steps to reproduce
Select Firewall, New
Enter port 80 (already exists)
Try to submit, cancel or close dialog

-Expected result: validation message
-Result: dialog remains on the screen without feedback and can not be closed or removed.

**Comment by MMaiero** [comment]
@darionct Could you please verify that the issue is now solved?

**Comment by darionct** [comment]
Confirmed in Kura 4.0.0. RC#49. 
Warning with appropriate message is shown in case of duplicate entry.
