### ISSUE TITLE
[Kura 4.0.0 QA] Service disappears from menu when reconfigured

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#2279]
ExamplePublisher disappears when it's reconfigured in a certain way:
* install ExamplePublisher
* add service
* service appears in the menu
* click on it and configure publisher and/or subscriber
* apply and confirm
* service disappears from the menu

It seems to be related to the selection of cloud connection(s). If I update some other parameter, it’s OK. When I change either one of those 2, it happens. Page refresh solves the issue that doesn’t reappear in the next save. The service also reappears if I reconfigure the same or other parameters again. And doesn’t disappear afterwards.
 
e.g. DB server doesn’t have this issue – no cloud connection to configure.

  - Kura version affected: Kura 4.0.0 RC b48
  - OS: Raspbian 9 on RPi3
  - Browser:
    - Name: Firefox
    - Version: 61.0

**Comment by MMaiero** [comment]
@markoer Could you please verify if PR #2283 solves the issue?

**Comment by markoer** [comment]
Verified in RC b49.
