### ISSUE TITLE
[Documentation] No need to disable networking service

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2286]
On Raspberry pi, the documentation should be updated in order to do not disable networking service.
This will prevent having the raspberry pi booting without any interface enabled.

@markoer Could you please check and confirm?

**Comment by markoer** [comment]
I'm missing some context, here :(

**Comment by MMaiero** [comment]
Right,
I was seeing that if network service is disabled in raspberry, as suggested from instructions, Raspberry networking will not be available until Kura starts.

The same does not happen is networking service is not disabled: networking will be up and configured immediately and even before Kura startup.

No idea why we decided to disable network service by default. Maybe you remember something and can shred some light on this.
