### ISSUE TITLE
kura.data.dir unused

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#2301]
Please describe the issue you are encountering in Kura.

Fill the following form and provide a textual description if you are reporting a bug. 
Provide only a textual description otherwise.

- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb): N.A.
    - Platform (e.g. Raspberry pi 2): N.A.
    - Kura version affected (e.g. Kura 3.1.0): 4.0.0
    - Java version (paste the result of **java -version**: N.A.
    - Host OS (e.g. Debian): N.A.
    - Host OS version N.A

  - [ ] Development environment
    - Version: 
    - Operating system (Mac OS, Windows, Linux):
    - OS Version:
    - IDE Version:
    - Host System Java Version:
      
  - [ ] Oomph installer
  - [ ] Add-ons
    - Name:
    - Version:
    - URL:
  - [ ] Eclipse Kura Marketplace
  - [ ] Kura Website
  - [ ] Kura Documentation

  - If needed to replicate the issue, please provide references for the browser used:
    - Name:
    - Version:
     
- Textual description of the issue:

It seems `kura.data.dir` is no longer used.

```
grep -R -i kura\\.data\\.dir .
./distrib/src/main/ant/build_equinox_distrib.xml:        -Dkura.data.dir=${DIR}/data \
./distrib/src/main/ant/build_equinox_distrib.xml:        -Dkura.data.dir=${DIR}/data \
./distrib/src/main/ant/build_equinox_distrib.xml:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7-nn/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7-nn/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-centos-7-nn/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-ubuntu-16/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-ubuntu-16/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_intel-up2-ubuntu-16/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2-nn/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2-nn/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_raspberry-pi-2-nn/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_rock960-ubuntu-16-nn/start_kura.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_rock960-ubuntu-16-nn/start_kura_background.sh:        -Dkura.data.dir=${DIR}/data \
./distrib/target/kura_4.0.0-SNAPSHOT_rock960-ubuntu-16-nn/start_kura_debug.sh:        -Dkura.data.dir=${DIR}/data \
```

**Comment by pierantoniomerlino** [comment]
@MMaiero **kura.data.dir** isn't used indeed... because the correct property is **kura.data** as reported in the kura.properties file and [here](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/system/SystemService.java#L69).

Maybe we should keep this property, but correct the one in the start script.

**Comment by MMaiero** [comment]
@pierantoniomerlino We should check for defaults. If the default Kura.data is taken, then we can remove the property from the start script as a duplication. Otherwise we should check why everything works.
