### ISSUE TITLE
Asset configuration: Unit factor field

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#2312]
We've recently started using Kura to read industrial devices on some plant we are monitoring to evaluate a full implementation in our systems but found a difficulty in variables processing. Most of the industrial devices we read on our systems requires some scale on the value read to convert to the proper unit:

- Modbus register: 42045 (cV)
- Value we intend to read: 420,45 V

We have solved the issue with an intermediate specific component that process this scaling, but we think the real solution would be to include it in the Asset configuration so that any driver implemented by third party developers have to take this in consideration.

The final solution we are proposing would be a field on _BaseChannelDescriptor_ named similar to value.scale or value.factor with default value to 1 that is multiplied by the value read from the industrial device right before sending the value to the next wire component in case the value is numeric

**Comment by MMaiero** [comment]
Hi @pintify,
thank you for the suggestion.
Are you gonna make a proposal in form of pull request?

Best regards,
Matteo

**Comment by pintify** [comment]
I'm not really familiarized with the source code of Kura neither have prepared the development environment properly, just implemented a couple of simple additional plugins. I could try anyway but I think it's very likely that I miss something and introduce a bug.

**Comment by MMaiero** [comment]
No worries, it will in any case be evaluated by the team before merging.

Matteo

**Comment by amitjoy** [comment]
That's a good enhancement proposal. I also had a similar idea to introduce units of measurements for channel emits that would enable us to perform scaling and factoring as well. I couldn't pull it off so far as I have been busy in the past weeks but I will resume my work asap. I am also encouraging you to keep us posted about your progress so that we can synchronize as well.

**Comment by pintify** [comment]
Not too much progress by now, just downloading the source, try to compile and look around for the classes implied

**Comment by pintify** [comment]
I've created a PR that only considers the creation of the field and leaves to the developer of the driver its usage.

I wonder if it would be better to implement the scale directly. I can only think of a way to use the factor and therefore the code would be always the same in every driver. Besides it would guarantee that the feature is supported and compatible with current drivers.

**Comment by pintify** [comment]
Solved with https://github.com/eclipse/kura/pull/3694
