### ISSUE TITLE
Add Groovy support to Kura Camel

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#232]

**Comment by kartben** [comment]
Can you guys please make sure these extra/non-core bundles are brought by a
dedicated profile at build time, or something equivalent? These days I'm
running Kura on a device with hardly enough flash to fit Kura 1.3. Amy
additional MB to the Kura distro means saying goodbye to compatibility (out
of the box at least) with the most constrained gateways, and that would be
too bad.

Le lun. 23 mai 2016 10:07, Henryk Konsek <notifications@github.com> a
écrit :

**Comment by hekonsek** [comment]
If we decide to use Karaf in Kura at some point, we could use Karaf "features" [1]. That would mean that by default Kura will contain only "core" modules. Then users could install additional modules (i.e. set of bundles) bu executing shell commands like:

    feature:install camel
    feature:install groovy
    feature:install webui
    feature:install camel

...and so forth. With approach we could reduce vanilla Kura size singnificantly while keep an ability to install new awesome features.

What do you think?

CC @cdealti @dwoodard1 

[1] https://karaf.apache.org/manual/latest/#_feature_and_resolver

**Comment by dwoodard1** [comment]
I think adding support for Karaf is important, and installing Camel via features would be great. But isn't Karaf itself a fairly large container when compared to Equinox? Also, the default installers (Debian packages, etc) that we distribute use Equinox.

I agree with @kartben, we should be mindful of the the size of Kura. We are already increasing the size of the next release with the new GWT library. Maybe we could package Camel as a DP and include it in the Eclipse Marketplace. I should have the "Drag and Drop" from the Marketplace working in the next day or so.

**Comment by hekonsek** [comment]
Karaf distribution is 19 MB. I guess that what you get in return for those few extra megabytes it worth it :) .

The big plus of Karaf is that we could start to manage many Kura modules as "features" which will be downloaded only when needed, so we may actually end-up with smaller distribution than Equinox (which includes all the modules now, even if you don't need them).

So even if the initial size of Karaf is bigger than Equinox, you can download/install only those modules that are interesting for you. Sooner or later Equinox distribution will become too large anyway. Karaf is a way to provide lightweight core container and additional modules only on demand.
