### ISSUE TITLE
Possible OSGi framework refresh when a dp is reinstalled

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#2324]
**Describe the bug**

When a dp is uninstalled and reinstalled in Kura 4.0.0, sometimes the framework refreshes a lot of bundles in the framework, even if these bundles seem to be completely unrelated with the ones in the dp. The effect is similar to the one described in #1928.

This behaviour sems to be caused by the `log4j2-api` bundle (`org.apache.logging.log4j.api_2.8.2`). This bundle seems to dynamically import "random" packages at runtime. 

If the bundle imports a package that is provided by some bundle deployed in a dp, and the dp is uninstalled and then reinstalled, all bundles that use logging will likely be refreshed.

The `log4j2-api` bundle is able to import any package dynamically because the `org.apache.log4j2-api-config_1.0.0` adds the following entry to its manifest:

```
DynamicImport-Package: *;resolution:=optional
```

The fragment was introduced to solve other issues with log4j2.
I've not investigated the cause of the dynamic imports of `log4j2-api` yet.

This workaround allows to avoid this issue if a dp update needs to be performed:

- uninstall the dp
- restart Kura
- install the new version

**To Reproduce**
I've not discovered a pattern to reproduce this yet. Uninstalling and reinstalling the dp can cause the issue, depending on the current imports of the `log4j2-api` bundle.

**Expected behavior**
The refresh caused by reinstalling a dp ideally should only affect a small set of bundles correlated with the ones in the dp.

**Comment by nicolatimeus** [comment]
An event that causes the unnecessary imports to appear is printing exception stack traces.

This is caused by the usage of `org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter`, for printing stack traces, which tries to get additional information about the classes appearing in the trace (e.g. provider jar) using `Class.forName()`.
See the source code of `org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter` and `org.apache.logging.log4j.core.impl.ThrowableProxy` for more details.

This can be reproduced by triggering an exception log trying to connect a CloudConnection with an invalid broker URL using the web ui. Doing this will cause the `org.eclipse.kura.core.data` package to be imported by `org.apache.logging.log4j.api`.

The unnecessary imports do not appear if `org.apache.logging.log4j.core.pattern.ThrowablePatternConverter` is used, this can be selected by adding

`%throwable{full}`

to the pattern in `log4j.xml`

**Comment by pintify** [comment]
I've experienced this behaviour after uninstalling a meta package with multiple bundles declared inside, but it never happened with any of them separately. The issue does not happen when the package is installed, only when reinstalled or uninstalled.
