### ISSUE TITLE
Update AWS connection documentation

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2332]
**Describe the bug**
It seems that AWS is moving away from the old Verisign certificate https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html

**To Reproduce**
1. Go to https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html

**Expected behavior**
None at the moment

**Screenshots**

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3] All
 - OS version: [e.g. provide the result of `uname -a`] All
 - Additional info: 

**Additional context**
We need to update the existing documentation to reference the new certificates used by AWS and provide proper instructions to Kura Users on how to use AWS connection

**Comment by pierrepitiot** [comment]
The documentation has been updated, please check the new link before closing the issue.
