### ISSUE TITLE
[Web UI] web2 network configuration glitch

### ISSUE THREAD

**Issue by lmarshall-eth** [eclipse/kura#234]
Steps to reproduce:
- Go to network configuration area
- Select an interface, eth0
- Change a property without hitting Apply
- Select another interface, wlan0
- See "There are unsaved changes..." box
- Click "No"

Expected Behaviour:
We are returned to the eth0 configuration

Actual Behaviour:
The wlan0 interface is selected

**Comment by cdealti** [comment]
@lmarshall-eth Possible duplicate or related to #290
