### ISSUE TITLE
LinuxNetworkUtil#toolExists() should check for tool's existence in PATH

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#235]
I recently ported Kura to a target that has no ethtool, etc. out-of-the-box so I had to compile those manually and put them on my filesystem. Since /sbin, /usr/sbin etc. are on read-only partition, I ended up putting the executables in ~/bin. 
However, LinuxNetworkUtil#toolExists() only checks for the tool's existence in "/sbin/", "/usr/sbin/" and "/bin/" (while later on, it doesn't really matter where the tool really is since ProcessUtil.exec() will look for it in the PATH). See https://github.com/eclipse/kura/blob/063bc48d3c860182a821a6691e51b4bb71e4510b/kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/LinuxNetworkUtil.java#L326
I had to "hack" the methods so as it would look for the tool in my folder.

I would suggest toolExists() is updated to look for the tool's existence in the PATH.

**Comment by cdealti** [comment]
@kartben I believe we should externalize this stuff in configuration files, e.g. in ``kura.properties``

kura.os.prog.chmod=/bin/chmod
