### ISSUE TITLE
Unable to access networks with hidden SSID

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2351]
**Describe the bug**
As reported [here](https://www.eclipse.org/forums/index.php/t/1096573/) it seems that Kura is unable to access to wifi networks with an hidden SSID

**To Reproduce**
1. Go to Network and select wifi interface
2. set the hidden SSID and the corresponding password
3. Save the changes, Kura should be able to join the network

**Expected behavior**
Kura should be able to join networks with hidden SSID by simply specifying the network name in the proper field and the corresponding password.

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3] Raspberry Pi 3 but reproducible in every board with network support and WI-Fi module

**Additional context**
N/A

**Comment by pierantoniomerlino** [comment]
The **Ignore Broadcast SSID** option in the **Wireless** tab can enable the access to networks with hidden SSIDs.
From the Kura documentation [1]:

> 
    Ignore Broadcast SSID - operates as follows if set to true:
        In Access Point mode, sends an empty SSID in beacons and ignores probe request frames that do not specify full SSID.
        In Station mode, does not scan for the SSID before attempting to associate.

So, when set to true in Access point mode, the SSID will not be broadcasted, creating a hidden SSID network. When in Station mode, Kura will not check or search for the SSID, enabling the connection to hidden SSIDs.

@MMaiero I verified this with a couple of RPis. Could you test it on your setup?

[1] https://eclipse.github.io/kura/config/wi-fi-configuration.html

**Comment by MMaiero** [comment]
Reported to the original author in the Kura forum.
Closing for now
