### ISSUE TITLE
Publish mqtt messages to kura from third party software 

### ISSUE THREAD

**Issue by nickes** [eclipse/kura#2360]
**Describe the bug**
I'm trying to publish MQTT message to my kura gateway from a third party program like [eclipse/mqtt-spy](https://github.com/eclipse/paho.mqtt-spy).  _Simple JSON_ as payload format works great (first screenshot). But I'm forced to use **Kura Protobuf**, on grounds that I'm also using Kapua as a backend and this is where my problem begins:
Kura does not decode the same published message (Second screenshot). I'm sure that this has something to do with the encoding of the published message. I searched for third party solutions, but none of them seems to support this encoding. 
So I would be very grateful if somebody could give me a hint for this issue.
BTW: I also opened an issue at the mqtt-spy repo.

**To Reproduce**
On Kura:
1. Connect to Kapua and set a subscriber
2. Link the subscriber to an application.
3. Go to Cloud Connections > Cloud Connections > Payload Encoding
4. Select 'Kura Protobuf'

On your third party software (e.g. MQTT-Spy)
1. Connect to your Kapua Cloud Broker   
2. Publish a message to the topic specified in the kura subscriber
3. Check if kura received the content of the payload (e.g. in /var/log/kura.log)

**Expected behavior**
As already mentioned, I expected that the published messages would be displayed by kura. 
I do not rule out that I may have misunderstood something and would be happy to receive feedback here as well.

**Screenshots**
![screenshot from 2019-01-15 14-47-19](https://user-images.githubusercontent.com/1750282/51186398-dc081d80-18d9-11e9-8e9b-ffdd69ac351e.png)
![screenshot from 2019-01-15 15-22-11](https://user-images.githubusercontent.com/1750282/51186426-e6c2b280-18d9-11e9-86be-f178b7a2ad46.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
 - Additional info: Kura 4.0.0. and Kapura 1.0.3

**Additional context**
none

**Comment by nickes** [comment]
Maybe I don't see the bigger picture here. I'm just looking for a solution to publish a message from kapua or a third party software to kura. Is there any way to do that or have I misunderstood something?

**Comment by MMaiero** [comment]
Hi, maybe I'm not understanding your issue, but in the second screenshot I believe you received the message. The difference between the two messages displayed is that in the last one the content is in the body.

**Comment by nickes** [comment]
Hi @MMaiero, thank you for your reply. 
I also think that the content is in the body, but I don't know a way to display the content of it (as shown in the first example). Do you know how to decode it? 
My issue is that I don't see a way to send MQTT messages over kapua to my kura instance.

**Comment by MMaiero** [comment]
Hi, to decode and display the message content, please have a look at the APIs.

The ability to send a message from Kapua to a target Kura device is supported through Kapua's REST APIs.

Best regards,
Matteo

**Comment by nickes** [comment]
Thank you for this information. I'll take a look at the REST API. I set the issue to closed for now.
