### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by avargun** [eclipse/kura#2363]
Hi,

I would like to connect to Kura from a remote application by using Kura's Rest API .
I am using Kura simulator.  I couldn't find exact url of Kura Api or any documentation how can i reach to rest services or send get or post requests. I tried http://--ip--/services,  http://--ip--/kura/services,  http://--ip--/services/assets as Kura Rest URL. Do i have to install something to start Rest Services? where am i wrong? 

Thank you.

**Comment by nicolatimeus** [comment]
Hi @avargun,

Some documentation about currently implemented REST APIs is available at [1].
If you are able to access the Kura Web UI at `http://ip/kura`, then Asset REST APIs should be reachable at `http://ip/services/assets`.

REST support is provided by the following bundles that should be included in the Kura distribution out of the box: 

**org.eclipse.kura.rest.provider**
**org.eclipse.kura.rest.asset.provider**

If REST support is available in your setup, you should see the **RestService** entry in the Web UI under Services.

You can try opening `http://ip/services/assets` with your browser, If everything is ok, you should see a JSON array containing the names of the Assets available in your setup (the array will be empty `[]`  if there are no Assets).

[1] https://eclipse.github.io/kura/builtin/rest-service.html

**Comment by MMaiero** [comment]
@avargun Can this issue be closed?

Best regards,
Matteo

**Comment by aycanvargun** [comment]
yes. thank you.
