### ISSUE TITLE
org.eclipse.kura.protocol.can not available in eclipse repository

### ISSUE THREAD

**Issue by SubChord** [eclipse/kura#2369]
**Describe the bug**
The dependency org.eclipse.kura.protocol.can is not available in the https://repo.eclipse.org/content/groups/releases/ repository.

**To Reproduce**
Browse to:  https://repo.eclipse.org/content/groups/releases/org/eclipse/kura/ and see that it is not there.

**Expected behavior**
I expect it to be there. Now I need to include a jar into my build in order to be able to use CAN as a dependency and it can not be included as a dependency in gradle without having the .jar in a local folder.

**Comment by MMaiero** [comment]
Hi,
unfortunately we cannot distribute that bundle in Eclipse repositories due to its dependency that is not Eclipse friendly.
You need to build it on your own using the -Pcan profile.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Closing for now. Please feel free to reopen it, if needed.
