### ISSUE TITLE
RequestHandler stops application 

### ISSUE THREAD

**Issue by nickes** [eclipse/kura#2375]
**Describe the bug**
I'm trying to implement a **command-and-control functionality** into my **heater demo example**. That means that my demo implements the classes ConfigurableComponent, CloudSubscriberListener, CloudConnectionListener, CloudDeliveryListener and additionally **RequestHandler**. Unfortunately my demo stops responding (no logs) after installing the bundle in Kura with the RequestHandler and the functions _setRequestHandlerRegistry_, _unsetRequestHandlerRegistry_ and _doGet_. 
I'm getting the feeling that I misunderstood the usage of the RequestHandler class, but on the other hand I don't see any differences to these examples ([CommandCloudApp](https://github.com/eclipse/kura/blob/41617c5d2cc8262057e696db2abf686d11b3939d/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java) or [AssetCloudlet](https://github.com/eclipse/kura/blob/41617c5d2cc8262057e696db2abf686d11b3939d/kura/org.eclipse.kura.asset.cloudlet.provider/src/main/java/org/eclipse/kura/internal/asset/cloudlet/AssetCloudlet.java))
**To Reproduce**
1. Extend the heater demo example by adding RequestHandler 
2. Add the functions **setRequestHandlerRegistry**, **unsetRequestHandlerRegistry** and **doGet** as seen in [CommandCloudApp](https://github.com/eclipse/kura/blob/41617c5d2cc8262057e696db2abf686d11b3939d/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java)
3. Import all missing packages
4. Export the project as a deployable plugin-in and install the bundle on Kura
5. After a _successful_ installation, the demo should stop responding (no more logs)

**Expected behavior**
Based on the examples I expected that the demo shouldn't stop responding after adding Requesthandler. 

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux kura 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
 - Additional info: Kura v4.0.0

**Comment by nickes** [comment]
Speaking of the **command-and-control** functionality: 
It would be a great help if someone could give me information about sending command-and-control messages **from kapua's REST api to kura**. I was thinking about the **/{scopeId}/devices/{deviceId}/requests** template from swagger, but I'm not sure about the parameters.
Has anyone here done this before and tell her/his experiences?

**Comment by MMaiero** [comment]
Hi,
do you have any code snippet that we can use for debugging?
Even better if you can share a complete bundle that we can download and test.

Best regards,
Matteo

**Comment by nickes** [comment]
Hi @MMaiero,
thank you for your quick reply. I attached the files.
[org.eclipse.kura.example.zip](https://github.com/eclipse/kura/files/2846693/org.eclipse.kura.example.zip)

**Comment by MMaiero** [comment]
@nickes I would suggest to try to replicate what done, for example, in https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java that I believe matches what you want to achieve.
Please remember to update your component configuration as done here: https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/OSGI-INF/commandCloudApp.xml

**Comment by MMaiero** [comment]
@nickes Any updates?

**Comment by nickes** [comment]
@MMaiero I updated my application using the given example and it finally works.
Here are the changes that I made:

- I added the following lines to my **component.xml**:
`<reference name="RequestHandlerRegistry"
              policy="dynamic"
              cardinality="0..n" 
              bind="setRequestHandlerRegistry"
              unbind="unsetRequestHandlerRegistry"
              interface="org.eclipse.kura.cloudconnection.request.RequestHandlerRegistry"/>`
- I also **add**ed the **dependencies** in my **MANIFEST.MF** (using the **import-Package** option)

I have learned, that this _process_ must be done with all packages/interfaces I want to use.
Now I can continue my project.

Thank you for your support @MMaiero !

**Comment by giuseppeferro** [comment]
> @MMaiero I updated my application using the given example and it finally works.
> Here are the changes that I made:
> 
> * I added the following lines to my **component.xml**:
>   `<reference name="RequestHandlerRegistry" policy="dynamic" cardinality="0..n"  bind="setRequestHandlerRegistry" unbind="unsetRequestHandlerRegistry" interface="org.eclipse.kura.cloudconnection.request.RequestHandlerRegistry"/>`
> * I also **add**ed the **dependencies** in my **MANIFEST.MF** (using the **import-Package** option)
> 
> I have learned, that this _process_ must be done with all packages/interfaces I want to use.
> Now I can continue my project.
> 
> Thank you for your support @MMaiero !

Hi @nickes ,
I would to replicate your application using command-and-control functionality.
i'm following your hints but i was not able to publish into CTRL/DEVICES/{requester.client.id}/REALTIME-CMD-V1/REPLY/{request.id} topic.
i'm using Kura 4.1.0
Can you help me to use properly RequestHandlerRegistry?
have you some example code?
Thanks in advance
