### ISSUE TITLE
Extract only Kura BLE API component

### ISSUE THREAD

**Issue by vikram919** [eclipse/kura#2384]
I wanted to use ble functionality in another project, apart from ble i do not require other components. Is it possible to use ble alone rather than extracting whole project?
Thank you

**Comment by MMaiero** [comment]
Hi, this is more a question for the [Kura Forum](https://www.eclipse.org/forums/index.php/f/273/) and not an issue or a feature request.

In general I would say that it is possible, not considering all the OSGi-related code.

Best regards,
Matteo
