### ISSUE TITLE
Multhitread: multiple instances of the same driver

### ISSUE THREAD

**Issue by cn73** [eclipse/kura#2391]
I set up a wire graph with 2 opcua driver instance connect two assets with different ip. In each asset we have an indipendent opcua server. Sometimes I get a connection timeout in one of the two, the real problem is that in the 60 seconds before the timeout triggers, the other one does not seem to work ... there is not a multithread management in the multiple instances of the same driver?

**Comment by nicolatimeus** [comment]
Hi @cn73,

Separate OPC-UA driver instances should be able to operate concurrently if driven by different threads, regarding your problem, I can think about the following explanation:

If you are using Wires, and you have one Driver instance per server and one Asset per Driver instance, and you connect the two Asset instances to a same wires Timer, then the requests for the two servers will be carried out by the same thread. 
Moreover, all Timer instances share a same thread pool (with 10 threads by default), it is possible that even if you are using multiple Timers, in some circumstances the requests for the two servers are performed by the same thread.
You can try placing a FIFO component instance between each Asset and the Timer (you will need two FIFO instances in total). This will ensure that the two instances use different threads for the requests. You should also properly configure the FIFO components, for example consider setting the **discard.envelopes** parameter to `true`.

**Comment by cn73** [comment]
In the real case we have 8 asset, 4 OPCUA e 4 another driver. For each asset we set a single driver instance and a single timer. Now we'll try the FIFO component, your suggestion was very useful, thanks so much.

**Comment by MMaiero** [comment]
@cn73 Can this be closed?

**Comment by cn73** [comment]
Yes, thank you
