### ISSUE TITLE
Is Raspberry Pi 3 Model B+ fully supported?

### ISSUE THREAD

**Issue by joerg-wille** [eclipse/kura#2398]
Could not find any information on the web site, nor in the release notes.
Which is the better board to buy for Kura Raspberry Pi 3 Model B or B+?
Or doesn't make any difference for Kura?
Edit: Since this is actually a question in the first place, I will ask in the [forum](https://www.eclipse.org/forums/index.php/f/273/).

**Comment by markoer** [comment]
We do most of the testing on a 3B, but also use a couple 3B+ RPis. So as @MMaiero answered in the forum, both are OK.
