### ISSUE TITLE
Use artemis mqtt data in kura

### ISSUE THREAD

**Issue by 0xc0d** [eclipse/kura#2406]
Hi.

I want to send data that received in built-in MQTT broker, to the Cloud platform.

actually I'm following thos scenario to get collected data from remote MCU which is in same LAN (connected to LAN Access Point) and send them to the Eclipse Kapua.

thank you in advance

**Comment by bitvijays** [comment]
Hey @Aggr3ssor Hope you are doing well. I am just wondering how did you do this? Receive MQTT message on the built-in MQTT broker (part i am missing) and send them to Eclipse Kapua (Probably use the Publisher example). 

I tried to use eclipse.paho.client. library. However, I believe we have to use CloudClient or CloudManager?

and possibly org.eclipse.kura.cloudconnection.eclipseiot.mqtt.ConnectionManager? Any reference to existing code or documentation would be helpful.

PS: I am not a java developer, however, i was able to do the hello world example in Kura Dev Guide.

Thank you :)

**Comment by 0xc0d** [comment]
Hey
I believe you will find you answer in #2350 

But I should tell you I left eclipse IoT because of poor documentation, there is more better free and open source platform out there which has more clear document and more up to date tutorials, if you had followed eclipse kura youtube tutorials you definitely noticed that the version they use to make is 3.0.0 at last and it's confusing, as  you know there are some big difference between them, it is so bothering me because there is no MQTT driver (at eclipse marketplace at least). and you should do many things to handle it.plus the kura wires is not that good. further more there are many things which are annoying like apply any thing any time and confirmation and so on.

at the end I believe that Eclipse Kura is good IoT gateway but not the best.

I dont know if I was right or not  but it was my 10-days experience with that and I did not get a clear idea about how it works.

even if it's too good and I did not figure it out, there is still a big problem "poor documentation".
I would recommend you to search more around by using this keyword "Best free IoT platforms".

anyway thank you for you replay.

**Comment by MMaiero** [comment]
Hi @Aggr3ssor ,
I am sorry that you did not have a positive experience with Kura.
As you know this is an open source project based on contributions and the documentation reflects this. We are trying our best to provide new features and documentation but feedback is really welcome to help us to improve. So, If you have changes that you want to submit, those are more than welcome and will help the project to grow.

Anyways, thank you for your feedback as it helps us to improve.

Matteo

**Comment by bitvijays** [comment]
@Aggr3ssor Thank you for the honest feedback. @MMaiero Thank you for taking that feedback positively. we believe Eclipse IoT/ Kura are great products and you guys are doing amazing work. I might have few more questions regarding the connecting the MQTT Server which I will ask in the other thread. Will read more about MQTT Namespaces. Thank you @MMaiero and @Aggr3ssor ! Cheers!
