### ISSUE TITLE
Rock 960: cannot get client id

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2414]
**Describe the bug**
When the rock 960 is started, Kura is not able to get the client id even if the interface is specified in the kura.properties file.
Only stopping and restarting kura solves the issue 

**To Reproduce**
1. Start the system
2. Wait for kura to start
3. Exceptions will be displayed in log showing that no client id was found 
4. mqttdata transport config is not complete

**Expected behavior**
Being specified in kura.properties, the client id (that is the MAC address) should be immediately picked.

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Board Rock 960
 - OS version: Ubuntu 18
 - Additional info: Using an external USB-C adapter for Ethernet

**Additional context**
N/A

**Comment by marcellorinaldo** [comment]
Solved with PR #3497.
