### ISSUE TITLE
Uninstall leakage

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#2415]
**Describe the bug**
The uninstallation scripts don't remove properly the Kura files. Specifically on the intel-up2-centos-7, the kura.service file is not removed in the prerm script.

**Expected behavior**
All the files included in install.sh should be removed or restored on the uninstallation. At least those that are intended to be managed only with Kura.

**Additional context**
There are other related files besides kura.service such as iptables and logrorate that could be restored, but maybe those are intended to be left.

**Comment by markoer** [comment]
Where did you find this service file (full path)?
In #2387 I had limited testing options, so I might have missed something. Would you care to test an update on your device?

**Comment by pintify** [comment]
Sorry, I've checked your commit and looks like the problem was solved, but I'm not working on the most recent version. I will use your changed script. Thanks for everything.
