### ISSUE TITLE
[Web UI] Help is not always visible in the new web ui

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#242]
Help says "Mouse over enabled items on the left to see help" but the vertical spacing is too large and at a certain point help is not more visible

**Comment by dwoodard1** [comment]
@pierrepitiot Can you give a specific example of this? All of the help text I see looks okay.

**Comment by dwoodard1** [comment]
@cdealti @MMaiero @pierantoniomerlino @ibinshtok @LucaDazi I believe Pierre is on Holiday. Has anyone else seen this issue? Can you provide instructions for repeating?

**Comment by pierantoniomerlino** [comment]
@dwoodard1 I tried to replicate the issue, but I have never seen it.

**Comment by MMaiero** [comment]
I have no ways to test here but, if I remember well, if you go in the modem tab and scroll down, the help box does not scroll down. So, you cannot get help.

**Comment by cdealti** [comment]
Yes. Select Network | <modem> | Cellular and scroll down the configuration. The help box does not scroll down accordingly. I believe we can postpone it.

**Comment by pierantoniomerlino** [comment]
Ah! Now I understand.

**Comment by dwoodard1** [comment]
@cdealti I have a fix, it is pretty simple. As long as we don't want to release today it can stay.

**Comment by dwoodard1** [comment]
@MMaiero @pierantoniomerlino Should be better now, please confirm.
