### ISSUE TITLE
Kura 4.1.0 QA

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2422]
Assignments:

- ~~Raspberry pi 2/3~~: @markoer 
- ~~Rock960~~: @MMaiero 
- ~~Upsquared Ubuntu~~: @pierantoniomerlino 
- ~~Upsquared Centos 7~~: @pierantoniomerlino 
- ~~Docker Image~~: @markoer 
- ~~User Workspace~~: @pierantoniomerlino

**Comment by MMaiero** [comment]
Rock 960 is done. Spreadsheet available [here](https://eurotech2.sharepoint.com/sites/ETHCommunity/Shared%20Documents/Eclipse%20Kura/QA/4.1.0-RC1/qa_kura_4.1.0-RC1_rock960.ods?d=wcecb80b260d7466a8263381c43210e6b)

**Comment by pierantoniomerlino** [comment]
Also UP2 (ubuntu) is done. QA results [here](https://eurotech2.sharepoint.com/:x:/r/sites/ETHCommunity/_layouts/15/Doc.aspx?sourcedoc=%7B405A5701-5A52-4E2C-A5D1-434464693F93%7D&file=qa_kura_4.1.0-RC1_upsquared_ubuntu.ods&action=default&mobileredirect=true)

**Comment by pierantoniomerlino** [comment]
Kura partially tested on UP2 (Centos). Only installation and cloud connection tested. No spreadsheet available.
