### ISSUE TITLE
[Web UI] Command file upload dialog

### ISSUE THREAD

**Issue by matijaKnez-ct** [eclipse/kura#2430]
**Describe the bug**
Similar as #848, the upload button is covered by field and unevenly aligned. The bug appears in Firefox browsers (Firefox 65.0.1 used).

**To Reproduce**
1. Click on Device
2. Click on Command tab

**Screenshots**
![screen1](https://user-images.githubusercontent.com/45663278/56356549-6e6dd500-61d9-11e9-9dc2-8ab7af12f04c.PNG)

**Target Environment**
 - RaspberryPi 3 B+
 - Kura 4.0.0

**Comment by MMaiero** [comment]
Hi, the service is now disabled by default. You need first to enable it before invoking new commands

**Comment by pierrepitiot** [comment]
After different tests and searches on the Internet it seems that this look & feel cannot be easily modified:
"Unfortunately, this is how the input type='file' /  renders in various browsers. The FileUpload widget just wraps that input type."

**Comment by MMaiero** [comment]
Since it seems an issue only related to Firefox, I would set is a Won't fix.
