### ISSUE TITLE
Building Kura from source build-all.sh javax.comm error package not found

### ISSUE THREAD

**Issue by ghost** [eclipse/kura#2431]
I am trying to build kura from source with karaf using build-all.sh
I want to use karaf so that I can implement active-standby installations on 2 raspberry pi.
if there are an other approach to achieve high-availability of kura please inform me. 

The error I get is the following:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.kura.api 2.0.0
[ERROR]   Missing requirement: org.eclipse.kura.api 2.0.0 requires 'package javax.comm 1.2.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.kura:org.eclipse.kura.api:2.0.0 @ /home/pi/Downloads/kura-KURA_4.0.0_RELEASE/kura/org.eclipse.kura.api/pom.xml: See log for details -> [Help 1]
org.apache.maven.MavenExecutionException: Cannot resolve dependencies of MavenProject: org.eclipse.kura:org.eclipse.kura.api:2.0.0 @ /home/pi/Downloads/kura-KURA_4.0.0_RELEASE/kura/org.eclipse.kura.api/pom.xml

**Comment by MMaiero** [comment]
Hi, could you please detail your setup?

We tried to build it with maven and it worked. Maybe you need to update your setup.

Best regards,
Matteo

**Comment by spnettec** [comment]
Same issue.  This happens in maven 3.6.1. When i swich to 3.5.4.  It's ok.

**Comment by MMaiero** [comment]
That's correct @spnettec, seen that too in these days.

**Comment by ghost** [comment]
Thanks, I will check and let you know

**Comment by MMaiero** [comment]
Closing as it is not a Kura specific issue
