### ISSUE TITLE
Split Camel quickstart example into "bridge" and "native cloud client" examples

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#245]

**Comment by cdealti** [comment]
@hekonsek what do you exactly mean?

**Comment by ctron** [comment]
The first step is done by letting the `kura-cloud` component pick up an instance of `CloudService` from OSGi.

**Comment by ctron** [comment]
https://ctron.github.io/osgi-dp/

**Comment by ctron** [comment]
I think this can be closed.

Any objections?
