### ISSUE TITLE
After Rebooting Kura Device Packages Are Missing

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2456]
If user installs Kura packages from Kapua (one after another, without any timeout or waiting), the packages are not (properly) installed on the device - they are missing, when device is rebooted. 
This is also reported on kapua side (eclipse/kapua#2596). 

**Testflow:**
1. Login to Kapua with kapua-sys user (kapua-sys/kapua-password)
2. Connect a live Kura device to Kapua (e.g. device1)
3. Go to Devices -> device1 -> Packages
4. install several packages  (10+) one after another, without any timeout or waiting 
5. After the packages are installed, check on the Kura device (under "Packages") if they are listed there. 
6. Reboot the device (from device itself or from kapua from Command service)
7. On device go to Packages and observe the packages list - packages are missing. 

**Expected behavior**
No matter how fast the packages are installed, they should always stay instaleld after the reboot (from device or from kapua).

**Screenshot No. 1 (After installation, before reboot on kura):**
![Screenshot 2019-06-06 at 09 54 31](https://user-images.githubusercontent.com/15121999/59016383-67f6f380-8841-11e9-91f4-7c2a06d33d2c.png)

**Screenshto No. 2 (After installation, before reboot on kapua):**
![Screenshot 2019-06-06 at 09 54 26](https://user-images.githubusercontent.com/15121999/59016400-6d543e00-8841-11e9-989e-fe24c1403c4c.png)

**Screenshot No. 3 (after reboot):**
![Screenshot 2019-06-06 at 09 55 51](https://user-images.githubusercontent.com/15121999/59016365-5e6d8b80-8841-11e9-99fe-4c0d4408d3f9.png)

**Target Environment:**
 - Raspberry Pi 3 B+
 - OS version: MAC OS Mojave, version 10.14.4
 - Additional info: /

**Version of Kapua**
1.1.0-SNAPSHOT

Browsers used: 
- Google Chrome (Version 74.0.3729.131 (Official Build) (64-bit))
- Safari (Version 12.1)
- Mozilla Firefox (66.0.3 (64-bit))
- Opera (Version:60.0.3255.70)

**Comment by MMaiero** [comment]
Since @pierrepitiot was not able to recreate the issue and since there is a refactoring in progress,
we agreed to keep this on hold and try to revamp it later on.

The objective is to define with the help of @LeoNerdoG a set of tests related to deployment.

**Comment by LeoNerdoG** [comment]
OK I agree with the plan. My team will review the tests regarding the deployment and suggest some changes regarding this.

**Comment by LeoNerdoG** [comment]
Hey @pierrepitiot,
were you able to reproduce this issue? What is the status now about this?

**Comment by pierrepitiot** [comment]
Sorry, I didn't work on that for a long time but as far as I remember I was not able to reproduce this issue...

**Comment by LeoNerdoG** [comment]
ok cool, i am just asking since I was able to reproduce this on latest version of Kura and Kapua. 
I will ask others if they can reproduce.

**Comment by MMaiero** [comment]
Is this still an issue?

**Comment by LeoNerdoG** [comment]
Will check and let you know.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this on latest develop and it still happens.
