### ISSUE TITLE
The DnsServerServiceImpl for SystemD contains illegal commands

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2457]
**Describe the bug**
The DnsServerServiceImpl for SystemD calls `/etc/init.d/named`.

**Additional context**
Here the link at the code:

https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.linux.systemd.provider/src/main/java/org/eclipse/kura/internal/linux/systemd/net/dns/DnsServerServiceImpl.java#L192

**Comment by MMaiero** [comment]
@pierantoniomerlino Are you taking care of this?

**Comment by pierantoniomerlino** [comment]
@MMaiero Not at the moment, but I can assign it myself.
