### ISSUE TITLE
kura boot error because of xml.bind with java11

### ISSUE THREAD

**Issue by jread** [eclipse/kura#2488]
The current Kura stable 4.1.0 and the developer 4.2.0 exit at start when using java11 (as is now standard with Debian10). Currently Debian10 is not supporting older java versions.

Error:
Kura Started (pid=477) ...
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

I understand that java.xml.bind is now removed from java EE 11.
Is there a simple work around?

regards
John

**Comment by MMaiero** [comment]
Hello,
we have not tested deeply the java 11 compatibility.
I believe that the only options for the missing xml.bind library is to provide it in the environment or maybe, if the dependency is at OSGi level see if OSGi can be updated to a newer version

**Comment by jread** [comment]
I have tested a simple standalone OSGi (3.14) there and it seems not to have any problems.

**Comment by spnettec** [comment]
remove java.xml.bind in --add-modules=java.sql,java.xml,java.xml.bind  or replace by --add-modules=ALL-SYSTEM
