### ISSUE TITLE
KuraCloudComponent should allow more than 2 topic levels

### ISSUE THREAD

**Issue by ccustine** [eclipse/kura#250]
#The code in KuraCloudComponent only allows 2 topic levels (appId/topic) which is fine when using the bridged mode, but this hampers portability if you change the camel route to use native cloud client.  Code in question is [here](https://github.com/eclipse/kura/blob/9701210c393e818c13cc2d4f198b2495139304f7/kura/org.eclipse.kura.camel/src/main/java/org/eclipse/kura/camel/cloud/KuraCloudComponent.java#L44-L44). Discussed this with @hekonsek .

**Comment by hekonsek** [comment]
Many thanks, Chris. I will pick it up from here.

**Comment by hekonsek** [comment]
Fixed.
