### ISSUE TITLE
Firewall rules are deleted after opening port with reverse range

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2502]
**To Reproduce**
1. Go to Kura UI web page
2. Click on Firewall system item
3. Click on "+ New" to add new open port
4. Enter port range in reverse order
5. Enter all fields with valid data (screenshot attached)
6. Click on Submit button - Warning message appears (screenshot attached)
7. Click on Close button
8. Click on Apply button 

**Expected behavior**
After step6 - Error message should appear that port cannot be added since range is in reverse order

**Actual result **
Iptabes rule are deleted and cannot be restored

**Screenshots**

-before:

![kura_ui_before](https://user-images.githubusercontent.com/3385815/61641328-3924c780-ac9f-11e9-850d-66587c80edd1.PNG)
![rules_before](https://user-images.githubusercontent.com/3385815/61641331-39bd5e00-ac9f-11e9-8c54-a3d83a0915ca.PNG)

-when adding:

![port_entry_info](https://user-images.githubusercontent.com/3385815/61641329-3924c780-ac9f-11e9-85db-57cc5188098c.PNG)
![warning](https://user-images.githubusercontent.com/3385815/61641332-39bd5e00-ac9f-11e9-948a-984638776c29.PNG)

-after:

![kura_ui_after](https://user-images.githubusercontent.com/3385815/61641326-388c3100-ac9f-11e9-8b83-44f8d85e425b.PNG)
![rules_after](https://user-images.githubusercontent.com/3385815/61641330-3924c780-ac9f-11e9-8c10-921c8a6ffea1.PNG)

**Target Environment:**
 - Board [Raspberry Pi 3 B+]
 - OS version: [Linux raspberrypi 4.19.50-v7+]
 - Kura version: 4.1.0
 - Kura log is bellow
[port_range_issue_log.txt]
(https://github.com/eclipse/kura/files/3417940/port_range_issue_log.txt)

**Comment by MMaiero** [comment]
@mstankovic Could you please test the PR submitted and verify if it solves the issue?

Thanks

**Comment by mstankovic** [comment]
@MMaiero i'm confirming. it solves the issue.
tested and verified as fixed.

**Comment by MMaiero** [comment]
@mstankovic @pasqualenaclerio I tried to have a look at the proposed PR but I'm not satisfied by it: it considers only the case where ports are provided in ranges. In case of a single port, it fails. Please review it

**Comment by MMaiero** [comment]
@mstankovic I made some changes to the pull request. Could you please check that it is working with both single port and range?

**Comment by mstankovic** [comment]
@MMaiero i checked all scenarios. this issue is fixed.

Note: 
-user cannot add port 3 since there is a validation error but im able to add port 003 (or 03) which actually adds port number 3.

-also im able to add range 1:3

**Comment by mstankovic** [comment]
@MMaiero 
situation where user cannot add ports from 1 to 9 is reproducible on kura 4.1.0 too.
so it's not regression from #2502

from my point of view that is trivial issue and should not block this pr

**Comment by MMaiero** [comment]
Ok, so I'll merge it.
