### ISSUE TITLE
Improve the documentation of DB Store and DB Filter

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#2508]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

The existing documentation is missing all the important details about the `DB Store`

1. The primary key of the underlying table is an autogenerated and auto-incremented long identifier
2. The tables has a TIMESTAMP column representing the reception timestamp of a WireEnvelope
3. On receiving a Wire Envelope the DB Store may either ALTER the table to add new columns, by the name and type of the Wire Records' properties in the envelope, or DROP the table if the table schema and the envelop cannot be "reconciled". 
3. An index is created only for the TIMESTAMP column, in DESCending order
4. On receiving a Wire Envelope, if the COUNT(*) or rows is found to be greater than or equal to `maximum.table.size`, the DB Store will either TRUNCATE the whole table or DELETE *arbitrary* so that the remaining row count equals `cleanup.records.keep`. Note that the rows are not deleted in any particular chronological order, not taking advantage of the index. Due to this behavior, the only sensible values for `cleanup.records.keep` are 0 (TRUNCATE) or `maximum.table.size` (no more envelopes are inserted when the table is full) 

The documentation of `DB Filter` is misleading

1. The property representing the SQL _statement_ is `sql.view`. The Meta Type description clarifies ;) that it represents an "SQL to be executed to build a view". I wonder why the term "view" is improperly used here.

2. The property `cache.expiration.interval` has a lengthy description saying "This value specifies the cache validity in seconds. When cache expires, it will cause a new read in the database. A database read will be performed for every trigger received if the value is set to 0.". The description should simply say that "the last *result-set*, possibly empty, would be emitted for the duration of the configured interval"; an option which does not make much sense.

**Comment by MMaiero** [comment]
@mattdibi Can you please have a look, when you have time, if the documentation is now more up-to-date?

**Comment by mattdibi** [comment]
@MMaiero the latest page about the `DB Store` and `DB Filter` that I can find is [this one](https://eclipse.github.io/kura/docs-develop/kura-wires/single-port-wire-components/db-store-and-filter/) and looks like it's still lacking the information highlighted here. We might need to expand on this...
