### ISSUE TITLE
 All the example bundles shall use the default CloudService

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#251]
With the introduction of multiple connections now the example and demo bundles should be changed so to use the default communication stack by default.

**Comment by cdealti** [comment]
@ctron Do you thing we should implement the CloudService selection for all the examples as described in the [Kura Multiple Connections Wiki](https://github.com/eclipse/kura/wiki/Multiple-Cloud-Connections#selecting-a-connection-at-runtime)?

**Comment by ctron** [comment]
I would say so :+1:

**Comment by cdealti** [comment]
@ctron. Still of this idea? Also see #466

**Comment by ctron** [comment]
Not really. But doing nothing isn't a good idea either.

**Comment by MMaiero** [comment]
Closing this as superseded by #466
