### ISSUE TITLE
HttpService | User is able to disable both connectors

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2513]
**Describe the bug**
User is able to disable both connectors (http and https) and after that kura UI is not available 

**To Reproduce**
1. Go to HttpService service item
2. Disable both connectors (tick false for HTTP Enabled and tick false for HTTPS Enabled)
3. Click on Apply to apply changes
4. Click on Yes - confirmation button

**Expected behavior**
User should not be able to tick both "false"

**Workaround**
connect to telnet console and restart the Jetty bundle

**Target Environment (please complete the following information):**
 - Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux

**Comment by MMaiero** [comment]
Hi @mstankovic, it is like that per design decision.

Matteo
