### ISSUE TITLE
Error occurs when user change session timeout

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2514]
**Describe the bug**
Error occurs when user change session timeout

**To Reproduce**
1. Go to WebConsole service item 
2. Change value for "Session max inactivity interval" from 15 to 2 minutes
3. Click on Apply button
4. Click on yes - Confirmation dialog

**Expected behavior**
Changes should apply without error messages 

**Screenshots**
![timeout](https://user-images.githubusercontent.com/3385815/62128162-20866400-b2d4-11e9-9eb5-37d3b09d65fd.PNG)

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux
 - Browser: Chrome 

**Additional context**
If user closes error message and refreshes the page - web UI will be unavailable (some time) 
Note: there is no error in kura.log only INFO:

`Servlet org.eclipse.kura.web.server.servlet.FileServlet destroyed`

**Comment by MMaiero** [comment]
That is now the expected behaviour when acting in the web service configuration. This is due to the fact that the whole web service is restarted.

I believe we thought about setting a message to warn the users about this. But I have to double check to see if it is there.
