### ISSUE TITLE
Seed initial configuration when running the Emulator

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#252]
With the introduction of Multiple Connection the default communication stack is created starting from the snapshot_0.

When running the Emulator Kura starts without a snapshot_0, thus leading to the lack of a communication stack, which can be created later by the gogo shell commands.

A snapshot_0 for the emulator should be created as part of the Emulator bundle resources and used to seed initial configuration when needed.

**Comment by MMaiero** [comment]
@LucaDazi Could you check this? Thanks
