### ISSUE TITLE
Kura documentation

### ISSUE THREAD

**Issue by raysad** [eclipse/kura#2520]
Hi everyone,
I was trying to get started with Kura but I'm really stuck in trying to install it on my raspberry pi 3 B+.
In fact, the [quick-start](http://eclipse.github.io/kura/intro/raspberry-pi-quick-start.html) was a bit confusing.
The 3rd step in kura installation redirects to a response with two possible methods. Since step 2 consists in removing dhcpcd5 package, I **assumed** that I should go with the **Network Interfaces method**. But in step 7, i saw a dhcp server enabling error (I'm sorry I didn't copy and past it). Installation was successful even with that error and when I rebooted the raspberry pi I couldn't find any interfaces. Kura installation changed the ```/etc/network/interfaces``` and networking service failed. I had to restart from scratch with a new Raspbian image but I had the same problem.
Since I was unable to install the full version, I tried to install the **Kura no network** but I couldn't find an official tutorial on how to do it. Should I use **snapd** ?
Please point me in the right direction.
Thank you for any possible help.

**Comment by MMaiero** [comment]
Hi, maybe you can try to follow the sub mentioned steps and skip point 3 as I believe it's not mandatory. In theory Kura should be able, after the reboot, to set the network for you.

If not, please report the content of Kura.log and Kura-console.log.

Best regards,
Matteo

**Comment by raysad** [comment]
Hi @MMaiero ,
Thank you for your response. In fact, it was my fault. I thought the **RPI** should connect to my local gateway while it became **the** gateway.
Since I didn't need the network management at the moment, I stuck with the **nn** version. To install it, I just skipped the first 3 steps and it's working fine.
Best regards.
