### ISSUE TITLE
Error connecting to H2DbService

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#2521]
**Describe the bug**
I've experienced a problem connecting to the _H2DbService_. After changing the configuration of the service to store the data on disk instead of memory, a bundle developed by myself that used the service got stuck when trying to connect to the DB.

I'm trying to reproduce the error with debug logs (I experienced it on production environment), but what is clear is that the lock happens always after a database defragmentation.

**To Reproduce**
Not sure yet.

**Additional context**
As I can see, both _H2DbStore_ and _DataService_ creates the connection to the _H2DbService_ via the method `withConnection` but I'm doing it with the `getConnection` method (as I'm using the _BaseDbService_ interface), is there any difference?

**Comment by MMaiero** [comment]
Hi,
I believe that more context is needed here. Maybe also a test case is required to prove the issue and verify that it is actually solved.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Hello, any update on this?

**Comment by pintify** [comment]
Well, I've been unable to reproduce the error. I though I had configured everything just the same way but there have been no problems yet. I may close the issue until I'm pretty sure of the issue. Sorry for the disturbance.
