### ISSUE TITLE
[Documentation] Mention that Kura performs "at least once" message delivery to the cloud

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse/kura#2522]
I did not find any mention of message delivery "at least once" Qos.
Yet Kura seems to support it.

**Comment by MMaiero** [comment]
Hi,
thank you for your feedback.
Actually it depends on the specific cloud connection implementation to provide that support.
Yet, there is no direct mention in the documentation for the currently supported cloud providers.

We will work on that.

Best regards,
Matteo

**Comment by reda-alaoui** [comment]
Hi Matteo,

Just to be sure we are on the same page, in the eventuality of an unreachable cloud destination, the guarantee I am talking about should prevent Kura from loosing cloud targeted messages by storing them and retrying the message emission later.

Can you tell me which cloud connect implementation supports "at least once"?

**Comment by MMaiero** [comment]
In Kura you have the data service that stores the messages before sending them. Then you have the channel protection guaranteed by QoS 1 that is related also with the dataService: only the messages that are acked by the counterpart are then removed by Kura's database

**Comment by MMaiero** [comment]
Currently this level of protection is provided by all the cloud connections provided by the project.
