### ISSUE TITLE
[Documentation] Add a Kura development environment setup centered around Maven

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse/kura#2523]
http://eclipse.github.io/kura/dev/kura-setup.html only shows how to configure a Kura development environment requiring Eclipse IDE.
Many people use different IDEs with Maven.

I think it would be a good thing to have a tutorial explaining how to setup the environment based on Maven, regardless of the IDE.

It could take advantage of maven plugins `de.dentrassi.maven:osgi-dp` and `org.apache.felix:maven-bundle-plugin` for example.

**Comment by MMaiero** [comment]
Hi,
our builds currently use maven to build the project https://github.com/eclipse/kura/blob/develop/build-all.sh

We also had a page describing how to use maven to build the project https://wiki.eclipse.org/Kura/Getting_Started#Building but it's a bit outdated, also sue to the fact that people preferred to use directly the IDE and have a simple setup.

But, If you are willing to update our documentation adding this, the contribution is more than welcome!

Best regards,
Matteo
