### ISSUE TITLE
[Documentation] Add informations about OSGI

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse/kura#2524]
In the documentation, I did not find any mention of OSGI.
I think that the documentation should at least mention the supported OSGI version (OSGI 6 currently?).

**Comment by MMaiero** [comment]
Hi, 
a PR is more than welcome!

Best regards,
Matteo

**Comment by manan1979** [comment]
hi @MMaiero can i do it?

**Comment by MMaiero** [comment]
Hi @manan1979, sure!
You can create a PR to this branch: https://github.com/eclipse/kura/tree/docs-develop

Thanks for reaching out!
