### ISSUE TITLE
[Documentation] Use annotation instead of XML for OSGI component declaration

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse/kura#2525]
http://eclipse.github.io/kura/dev/serial-example.html shows how to develop a serial based module.

Although annotation component declaration is possible with OSGI 6 (supported by latest Kura), documentation and examples are still using XML component declaration. I think it can repel many people unfamiliar with OSGI.

IMO, XML component declaration should be replaced with annotation component declaration.

**Comment by MMaiero** [comment]
Hi,
the documentation was made long before adopting OSGi v6 and was kept like that also for legacy support purposes.

If you are willing to provide an update adding the annotation counterpart, the contribution is more than welcome!

Best regards,
Matteo

**Comment by ossnoser** [comment]
Could [this](https://github.com/eclipse/kura/tree/develop/kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater) considered a valid starting point?
