### ISSUE TITLE
Kura Routing Fuctionality with secondary ethernet port

### ISSUE THREAD

**Issue by paulfehrenbach** [eclipse/kura#2526]
Hi,
we're trying to configure Kura's routing functionality to create a subnet on a second ethernet port (using a usb-to-ethernet adapter on a pi3).
If we configure the built in ethernet port for WAN and the wifi for LAN, everything works perfectly.
When connecting the usb-to-ethernet adapter, the interface gets displayed correctly and can be configured the same way as the wifi.
The attached device gets an IP but no DNS. If we manually give a DNS to said device (e.g. 8.8.8.8) everything works as expected.
Greetings
Attached: Config of subnet ethernet port
![kura_router1](https://user-images.githubusercontent.com/54138147/63098911-49655500-bf74-11e9-9e67-568a6990c236.png)
![kura_router2](https://user-images.githubusercontent.com/54138147/63098921-4d917280-bf74-11e9-8ee9-11aa116c8408.png)

**Comment by MMaiero** [comment]
Hello,
could you please provide more details on your setup?

Do you actually see errors in the Kura.log or Kura-console.log files?
Anything meaningful in system logs like syslog?

Best regards,
Matteo

**Comment by paulfehrenbach** [comment]
Hi Matteo,
thank you for your reply. Of course, I will attach the logs:
Kura-Log after applying new config:
`2019-08-19T10:42:13,257 [EthernetMonitor_eth1] INFO  o.e.k.n.a.m.EthernetMonitorServiceImpl - Found a new Ethernet network configuration for eth1
2019-08-19T10:42:13,312 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - stopping pid=19320
2019-08-19T10:42:13,336 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - attempting to kill pid 19320
2019-08-19T10:42:13,336 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: kill 19320
2019-08-19T10:42:13,347 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - kill 19320 returned with exit value:0
2019-08-19T10:42:13,347 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - successfully killed pid 19320
2019-08-19T10:42:13,457 [qtp26337234-256] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1566207219435...
2019-08-19T10:42:13,710 [qtp26337234-256] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1566207733608.xml...
2019-08-19T10:42:13,784 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 start
2019-08-19T10:42:13,851 [qtp26337234-256] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/user/snapshots/snapshot_1566207733608.xml... Done.
2019-08-19T10:42:13,853 [qtp26337234-256] INFO  o.e.k.c.c.ConfigurationServiceImpl - Snapshots Garbage Collector. Deleted /opt/eclipse/kura/user/snapshots/snapshot_1566205526121.xml
2019-08-19T10:42:13,964 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 start returned with exit value:0
2019-08-19T10:42:13,968 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.n.a.m.WifiMonitorServiceImpl - initializing monitor
2019-08-19T10:42:13,980 [EthernetMonitor_eth1] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface eth1 down
2019-08-19T10:42:14,006 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifdown eth1

2019-08-19T10:42:19,205 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifdown eth1
 returned with exit value:0
2019-08-19T10:42:19,205 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifconfig eth1 down

2019-08-19T10:42:19,223 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifconfig eth1 down
 returned with exit value:0
2019-08-19T10:42:19,392 [EthernetMonitor_eth1] INFO  o.e.k.n.a.NetworkAdminServiceImpl - bringing interface eth1 up
2019-08-19T10:42:19,393 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifconfig eth1 up

2019-08-19T10:42:19,401 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifconfig eth1 up
 returned with exit value:0
2019-08-19T10:42:19,401 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: ifup --force eth1

2019-08-19T10:42:24,817 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - ifup --force eth1
 returned with exit value:0
2019-08-19T10:42:24,937 [EthernetMonitor_eth1] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: dhcpd -cf /etc/dhcpd-eth1.conf -pf /var/run/dhcpd-eth1.pid
2019-08-19T10:42:25,054 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 stop
2019-08-19T10:42:25,195 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 stop returned with exit value:0
2019-08-19T10:42:25,751 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: /etc/init.d/bind9 start
2019-08-19T10:42:25,907 [EventAdmin Async Event Dispatcher Thread] INFO  o.e.k.c.l.u.LinuxProcessUtil - /etc/init.d/bind9 start returned with exit value:0
2019-08-19T10:42:27,939 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask started.
2019-08-19T10:42:27,940 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Delete confirmed messages...
2019-08-19T10:42:27,946 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
2019-08-19T10:42:28,065 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask started.
2019-08-19T10:42:28,066 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Delete confirmed messages...
2019-08-19T10:42:28,072 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
2019-08-19T10:42:42,846 [qtp26337234-205] WARN  o.e.k.c.n.NetworkConfiguration - This invalid DhcpServerCfgIP4 configuration is ignored - org.eclipse.kura.net.dhcp.DhcpServerCfg: [ifaceName=eth0, enabled?=false, defaultLeaseTime=7200, maximumLeaseTime=7200, passDNS?=false], org.eclipse.kura.net.dhcp.DhcpServerCfgIP4: [subnet=192.168.238.0, subnetMask=255.255.255.0, prefix=24, routerAddress=192.168.238.104, rangeStart=172.16.0.100, rangeEnd=172.16.0.110, dnsServer=192.168.238.104]`
The syslog:

`Aug 19 10:43:45 McGraw kernel: [326309.966698] asix 1-1.2:1.0 eth1: link up, 100Mbps, full-duplex, lpa 0xC5E1
Aug 19 10:44:18 McGraw dhcpd[19901]: DHCPREQUEST for 192.168.239.2 from b8:27:eb:b7:39:b0 via eth1: ignored (not authoritative).
Aug 19 10:44:23 McGraw dhcpd[19901]: DHCPREQUEST for 192.168.239.2 from b8:27:eb:b7:39:b0 via eth1: ignored (not authoritative).
Aug 19 10:44:33 McGraw dhcpd[19901]: DHCPDISCOVER from b8:27:eb:b7:39:b0 via eth1
Aug 19 10:44:34 McGraw dhcpd[19901]: DHCPOFFER on 192.168.250.2 to b8:27:eb:b7:39:b0 (McGraw-Mender) via eth1
Aug 19 10:44:34 McGraw dhcpd[19901]: DHCPREQUEST for 192.168.250.2 (192.168.250.1) from b8:27:eb:b7:39:b0 (McGraw-Mender) via eth1
Aug 19 10:44:34 McGraw dhcpd[19901]: DHCPACK on 192.168.250.2 to b8:27:eb:b7:39:b0 (McGraw-Mender) via eth1
`
In the kura-console log nothing corresponding appears.
The Gateway (192.168.238.104) itself is connected to a Router (192.168.238.1) and should open a subnet (192.168.250.*), to clarify the addresses.
What other details can i provide you?
Greetings,
Paul

**Comment by MMaiero** [comment]
Is the content of /etc/resolv.conf properly set or not?

**Comment by paulfehrenbach** [comment]
Yes, it seems configured correctly.

![image](https://user-images.githubusercontent.com/54138147/63263118-fe0ab980-c287-11e9-87fc-94e59705eb20.png)

**Comment by MMaiero** [comment]
Ok, so I suspect there is some sort of glitch, maybe in the web ui.

**Comment by MMaiero** [comment]
Can I have more details on the setup of the different ports?
From the screenshot I see that the port is set for LAN so it is not expected that the connected devices get a gateway or DNS.
Maybe I'm missing something in the context.

**Comment by paulfehrenbach** [comment]
This is the setting of eth0 (connected to the Router-network):
![image](https://user-images.githubusercontent.com/54138147/63270558-b4769a80-c298-11e9-81b5-c47b10d2a577.png)
This is the setting of eth1 (which should open the subnet):
![image](https://user-images.githubusercontent.com/54138147/63270684-f1429180-c298-11e9-93d5-f4cc80a9d5fb.png)
![image](https://user-images.githubusercontent.com/54138147/63270749-0c150600-c299-11e9-95a3-64129516a925.png)

Maybe we misunderstood how it is expected to configure a subnet on that port.

**Comment by MMaiero** [comment]
ok, now it's more clear to me.
In theory you should be able to connect to the internet if connected to eth1. 
I will try to have a look.

**Comment by paulfehrenbach** [comment]
Hey Matteo,
Did you have a chance to check it yet?
Greetings

**Comment by pierantoniomerlino** [comment]
Hi @paulfehrenbach, could you please run this command on a terminal on the device?

`sudo cat /etc/sysconfig/iptables`

This will show the complete firewall configuration. Please check that there are a couple of rules that enable the forwarding between eth1 and eth0. Something like this (for wlan0):

`-A FORWARD -i wlan0 -o eth0 -j ACCEPT`
`-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT`

If the rules are not listed, please add them.

Best,
Pier

**Comment by fallada** [comment]
Hi, am having the same problem than @paulfehrenbach. After some testing, I got it running as a router over eth1 (wlan always worked for me).
This is the original config that _did not work_, after I enabled eth1 for LAN:
```
# Generated by iptables-save v1.6.0 on Mon Sep  9 10:54:29 2019
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 8000 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8000 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 5002 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 1450 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 1450 -j ACCEPT
-A INPUT -s 10.234.0.0/16 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A FORWARD -i wlan0 -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i eth1 -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 0 -m state --state RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Mon Sep  9 10:54:29 2019
# Generated by iptables-save v1.6.0 on Mon Sep  9 10:54:29 2019
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
# Completed on Mon Sep  9 10:54:29 2019
```
I got it working by adding the following lines _and_ disabling wlan over the webinterface.
```
-A INPUT -i eth1 -p tcp -m tcp --dport 8000 -j ACCEPT
-A INPUT -i eth1 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i eth1 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i eth1 -p tcp -m tcp --dport 1450 -j ACCEPT
-A INPUT -i eth1 -p tcp -m tcp --dport 80 -j ACCEPT
```
Disabling wlan made these lines disappear in the config (which seems necessary for enabling routing over eth1):
```
-A FORWARD -i wlan0 -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
```

Best regards,
Daniel

**Comment by sterwen** [comment]
We are also struggling with this bug since some months. We have made our investigations and it looks that the DNS configuration does not take into account the Ethernet port. Our technical expert will post additional details.

Obviously the fix above is not a final solution.

**Comment by solidrun-ejb** [comment]
From what I can see when the /etc/bind/named.conf is created, the ```allow-query``` only includes the network range from the wlan0 interface and not any other interface that is configured for LAN which would cause clients on the other interfaces to fail to resolve.

**Comment by MMaiero** [comment]
@pierantoniomerlino Can you please follow up on this?
Thanks

**Comment by pierantoniomerlino** [comment]
After some checks, to create a subnet on a second ethernet port (eth1) the following parameters should be configured:

- the firewall has to manage the forwarding of packets between eth0 (WAN) and eth1 (LAN);
- some ports should be opened on the firewall for the specific port (eth1);
- the dns server has to allow query from clients in to the subnet.

The first and third points are performed by Kura, while I manually opened the firewall ports (via Kura webUI :-) ). After the eth1 configuration this is the firewall config:

```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
    8   444 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 state NEW,RELATED,ESTABLISHED
    0     0 ACCEPT     tcp  --  wlan0  *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000
    0     0 ACCEPT     tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000
    0     0 ACCEPT     udp  --  wlan0  *       0.0.0.0/0            0.0.0.0/0            udp dpt:67
    2   656 ACCEPT     udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:67
    0     0 ACCEPT     udp  --  wlan0  *       0.0.0.0/0            0.0.0.0/0            udp dpt:53
    0     0 ACCEPT     udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:53
    0     0 ACCEPT     tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:5002
    0     0 ACCEPT     tcp  --  wlan0  *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1450
    0     0 ACCEPT     tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1450
    0     0 ACCEPT     tcp  --  *      *       10.234.0.0/16        0.0.0.0/0            tcp dpt:80
    0     0 ACCEPT     tcp  --  wlan0  *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80
    0     0 ACCEPT     tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000
    0     0 ACCEPT     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:67
    0     0 ACCEPT     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53
    0     0 ACCEPT     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1450
    0     0 ACCEPT     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  wlan0  eth0    0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  eth0   wlan0   0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
    3   183 ACCEPT     all  --  eth1   eth0    0.0.0.0/0            0.0.0.0/0
    2   284 ACCEPT     all  --  eth0   eth1    0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 0 state RELATED,ESTABLISHED
```

and this is the `/etc/bind/named.conf`:

```
// Forwarding and Caching Name Server Configuration
options {
	directory "/var/named";
	version "not currently available";
	forwarders {10.133.10.2;10.133.10.10;};
	forward only;
	allow-transfer{"none";};
	allow-query {172.16.1.1/24;192.168.250.1/24;};
	max-cache-ttl 30;
	max-ncache-ttl 30;
};
zone "." IN {
	type hint;
	file "named.ca";
};
include "/etc/named.rfc1912.zones";
```

With this configuration I was able to create a secondary subnet on eth1.
BTW, in the eth1 configuration you posted, there is an error on the *DHCP Ending Address*: it cannot end with 255.

**Comment by sterwen** [comment]
Hello,

Thanks for the tip, but this is not the problem we are facing. We want to route from Eth0 to ppp0. From Wlan0 it works because the correct configuration is made in /etc/bind/named.conf.
However, if the eth0 is configured as LAN with a DHCP server the DNS is not forwarded due to the fact that the eth0 0 IP address range is not indicated /etc/bind/named.conf.

**Comment by pierantoniomerlino** [comment]
@sterwen I'm sorry but I'm a bit lost on this issue...
I used a RPi with an external usb-2-ethernet dongle (eth1, as reported on the first posts), configured as follows

- eth0: WAN, DHCP client
- eth1: LAN, DHCP server, NAT and DNS server

This works on my setup and the correct configuration is made in `/etc/bind/named.conf`:

```
allow-query {172.16.1.1/24;192.168.250.1/24;};
```

The first post, however, reports that the eth0 is configured as:

- eth0: WAN, static

but it seems that the DNS servers are not set (see the content of `/etc/resolv.conf`). So, maybe, this can cause the issue.
However, you mentioned that you're using a cellular connection. What is your configuration?

**Comment by sterwen** [comment]
@pierantoniomerlino 
Today it works with 1 LAN having 172.16.1.1/24 address range. With the WiFi as LAN and Cellular as WAN it works perfectly as you state in your comment.
The problem arise when you want to route a second LAN (eth0) with Cellular as WAN. The IP is routed but the DNS is not passing. And this is the reason of the discussion on the issue.
The reason why it is not working is that the file /etc/bind/named;conf is not generated fully as only one LAN (the wlan0 in our case) is routed in this file while 2 LANs are configured on the gateway: wlan0 and eth0. So the allow query shall be 
allow-query {172.16.1.1/24;172.16.0.1/24;}; while it is in reality
allow-query {172.16.1.1/24;}; So only the wlan0 is having its DNS request forwarded

**Comment by sterwen** [comment]
I made further tests today and after recheck the /etc/bind/named.conf looks OK.
Here is the Kura network configuration and it looks OK.
![image](https://user-images.githubusercontent.com/30366677/68788482-c8395f00-0643-11ea-9071-b3026440d578.png)

With this configuration, the routing from the wlan0 is OK, while there is no DNS request forwarding from eth0. Pure IP routing works.

The named.conf file is also OK:

BS184300123:/etc/bind$ cat named.conf
// Forwarding and Caching Name Server Configuration
options {
        directory "/var/named";
        version "not currently available";
        forwarders {192.168.10.110;};
        forward only;
        allow-transfer{"none";};
        allow-query {172.16.0.1/24;172.16.1.1/24;};
        max-cache-ttl 30;
        max-ncache-ttl 30;
};
zone "." IN {
        type hint;
        file "named.ca";
};
include "/etc/named.rfc1912.zones";

**Comment by pierantoniomerlino** [comment]
@sterwen is the resolvconf service running?

**Comment by sterwen** [comment]
@pierantoniomerlino In fact the problem we were facing has been corrected on our side and was not linked to Kura. We found it after a long investigation
