### ISSUE TITLE
Check if bundle contexes correctly unget services after invoking getService

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#253]
Several OSGi Services are acquired using the bundle context.
After the services are no more needed they should be released calling ungetService(...) in order to keep the reference count of said services consistant.

**Comment by cdealti** [comment]
@LucaDazi do you remember what was the conclusion?

**Comment by cdealti** [comment]
@ctron can you take a look. I noticed you fixed something related in #530.

**Comment by ctron** [comment]
Yes #530 is exactly that.

Beside violating the spec :wink:  … 

Looking at Equinox's implementation this can happen:

```
if (useCount == Integer.MAX_VALUE) {
   throw new ServiceException(Msg.SERVICE_USE_OVERFLOW);
}
```

Now MAX_VALUE is quite a number, but running for some time, constantly getting called, you eventually reach it.

For ServiceFactory objects, they won't get garbage collected.

You probably won't run into any memory leaks, since everything seems to be reference counted.

But then again, cleaning up afterwards and following the spec seems like the right thing to do.

**Comment by cdealti** [comment]
@ctron are you willing to find and fix all the unbalanced occurrences for Kura 3.0?

**Comment by ctron** [comment]
Not really.

**Comment by cdealti** [comment]
@nicolatimeus can you please find all occurrences of these unbalanced calls and provide a list of the unbalanced calls for estimating the effort?

**Comment by nicolatimeus** [comment]
The table below reports the the invocations to `BundleContext.getService()`.

| Call Location | Released on all normal control paths | Always released on exception |
|----------|-----------------------------|---------------------|
|[ShellScriptResourceProcessorImpl.java:72](https://github.com/eclipse/kura/blob/1a3cf8e326a22250ec87ca31cf38f65d9c229d84/kura/org.eclipse.kura.deployment.customizer/src/main/java/org/eclipse/kura/deployment/rp/sh/impl/ShellScriptResourceProcessorImpl.java#L72)|yes|yes|
|[ServiceLocator.java:112](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L112)|yes|yes|
|[AssetServiceImpl.java:48](https://github.com/eclipse/kura/blob/5e333582078868e30e11d9136b9266f732fe0ba4/kura/org.eclipse.kura.asset.helper.provider/src/main/java/org/eclipse/kura/internal/asset/AssetServiceImpl.java#L48)|yes, but some references might be ungetted even if not needed||
|[BluetoothDeviceImpl.java:60](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.linux.bluetooth/src/main/java/org/eclipse/kura/linux/bluetooth/BluetoothDeviceImpl.java#L60)|no|no|
|[GwtWireServiceImpl.java:154](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtWireServiceImpl.java#L154)|no|no|
|[DriverServiceImpl.java:49](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.driver.helper.provider/src/main/java/org/eclipse/kura/internal/driver/DriverServiceImpl.java#L49)|yes, but some references might be ungetted even if not needed||
|[ComponentUtil.java:68](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/util/ComponentUtil.java#L68)|yes|yes|
|[ComponentUtil.java:138](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/util/ComponentUtil.java#L138)|no|no|
|[ComponentUtil.java:176](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/util/ComponentUtil.java#L176)|no|no|
|[ComponentUtil.java:424](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/util/ComponentUtil.java#L424)|no|no|
|[WireHelperServiceImpl.java:75](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.helper.provider/src/main/java/org/eclipse/kura/internal/wire/helper/WireHelperServiceImpl.java#L75)|yes, but some references might be ungetted even if not needed||
|[ConfigurationServiceImpl.java:1080](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java#L1080)|yes|yes|
|[ServiceLocator.java:191](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L191)|no|no|
|[WireHelperServiceImpl.java:112](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.helper.provider/src/main/java/org/eclipse/kura/internal/wire/helper/WireHelperServiceImpl.java#L112)|yes, but some references might be ungetted even if not needed||
|[GwtWireServiceUtil.java:123](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/GwtWireServiceUtil.java#L123)|no|no|
|[GwtWireServiceUtil.java:161](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/GwtWireServiceUtil.java#L161)|yes|no|
|[GpsClockSyncProvider.java:90](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.linux.clock/src/main/java/org/eclipse/kura/linux/clock/GpsClockSyncProvider.java#L90)|no|no|
|[GpsClockSyncProvider.java:87](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.windows.clock/src/main/java/org/eclipse/kura/windows/clock/GpsClockSyncProvider.java#L87)|no|no|
|[WireHelperServiceImpl.java:132](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.helper.provider/src/main/java/org/eclipse/kura/internal/wire/helper/WireHelperServiceImpl.java#L132)|yes, but some references might be ungetted even if not needed||
|[WireHelperServiceImpl.java:151](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.helper.provider/src/main/java/org/eclipse/kura/internal/wire/helper/WireHelperServiceImpl.java#L151)|yes, but some references might be ungetted even if not needed||
|[LinuxProcessUtil.java:411](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/util/LinuxProcessUtil.java#L411)|yes|no|
|[AssetServiceImpl.java:84](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.asset.helper.provider/src/main/java/org/eclipse/kura/internal/asset/AssetServiceImpl.java#L84)|reference is released even if service is still in use||
|[DriverServiceImpl.java:85](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.driver.helper.provider/src/main/java/org/eclipse/kura/internal/driver/DriverServiceImpl.java#L85)|reference is released even if service is still in use||
|[XmlConfigPropertiesAdapter.java:85](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/XmlConfigPropertiesAdapter.java#L85)|no|no|
|[ExamplePublisher.java:58](https://github.com/eclipse/kura/blob/develop/kura/examples/org.eclipse.kura.example.publisher/src/main/java/org/eclipse/kura/example/publisher/ExamplePublisher.java#L58)|no|no|
|[ExamplePublisher.java:70](https://github.com/eclipse/kura/blob/develop/kura/examples/org.eclipse.kura.example.publisher/src/main/java/org/eclipse/kura/example/publisher/ExamplePublisher.java#L70)|no|no|
|[CloudSubscriber.java:90](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/subscriber/CloudSubscriber.java#L90)|no|no|
|[CloudServiceImpl.java:459](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java#L459)|no|no|
|[ConfigurableComponentTracker.java:80](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurableComponentTracker.java#L80)|yes|yes|
|[WireComponentTrackerCustomizer.java:172](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.wire.provider/src/main/java/org/eclipse/kura/internal/wire/WireComponentTrackerCustomizer.java#L172)|yes|no|
|[XmlConfigPropertiesAdapter.java:258](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/XmlConfigPropertiesAdapter.java#L258)|no|no|
|[ServiceLocator.java:174](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L174)|yes|yes|

The `ServiceLocator.getService(Class)`, `ServiceLocator.getServices(Class)`, and `ServiceLocator.getServices(Class, String)` methods in the web ui bundle obtain a service reference to the requested service/s, calls  `BundleContext.getService()` on it and return the result.
Using these methods will probably always result in an unbalanced reference count, unless the caller obtains another service reference to the returned service and call `BundleContext.ungetService()` on it.
These methods should probably be redesigned.

The table below report the number of call sites for each method according to Eclipse:

| Method | Number of call sites |
|----|----|
|`ServiceLocator.getService(Class)`|>60|
|`ServiceLocator.getServices(Class)`|0|
|`ServiceLocator.getServices(Class, String)`|2|

The table below reports the details about `ServiceLocator.getService(ServiceReference)`, which obtains a `BundleContext` instance, calls `BundleContext.getService()` on it and then return the result.

| Call Location | Released on all normal control paths | Always released on exception |
|----------|-----------------------------|---------------------|
|[GwtStatusServiceImpl.java:89](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtStatusServiceImpl.java#L89)|yes|no|
|[GwtCloudServiceImpl.java:202](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtCloudServiceImpl.java#L202)|yes|yes|
|[GwtCloudServiceImpl.java:229](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtCloudServiceImpl.java#L229)|yes|yes|
|[GwtStatusServiceImpl.java:117](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtStatusServiceImpl.java#L117)|yes|no|
|[GwtStatusServiceImpl.java:169](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtStatusServiceImpl.java#L169)|yes|yes|
|[GwtStatusServiceImpl.java:190](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtStatusServiceImpl.java#L190)|yes|yes|
|[GwtCloudServiceImpl.java:144](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtCloudServiceImpl.java#L144)|yes|yes|
|[GwtCloudServiceImpl.java:270](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtCloudServiceImpl.java#L270)|no|no|
|[GwtCloudServiceImpl.java:250](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtCloudServiceImpl.java#L250)|no|no|
|[ServiceLocator.java:72](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L72)|probably not (see above)||
|[ServiceLocator.java:213](https://github.com/eclipse/kura/blob/0339ac787f90debdfc270c1dee0c16de16ea6f7e/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L213)|probably not (see above)||

**Comment by cdealti** [comment]
There's some duplication in [1] and [2].

@ctron @amitjoy wouldn't be better to collapse everything in the org.eclipse.kura.util bundle?

[1] https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.util/src/main/java/org/eclipse/kura/util/service/ServiceUtil.java
[2] https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/ServiceLocator.java#L174

**Comment by amitjoy** [comment]
@cdealti I second that 👍

**Comment by ctron** [comment]
Sure, go ahead.

**Comment by cdealti** [comment]
@amitjoy are you willing to do that ;-)?

**Comment by amitjoy** [comment]
Just had a quick look on the findings and I agree that in OSGi, the low-level methods can easily be misused by any developer and that's why we had a long discussion in #797. To cope up with the requirement of providing an easy to use helper class, I have designed an utility class in #1303. If it gets merged, we can refactor the aforementioned classes accordingly. I would be happy to do that.
