### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by RuslanLevond** [eclipse/kura#2532]
I have a Raspberry Pi 4 and I tried to install Kura using two different ways which are listed on Kura documentation, one the normal way and the other one with docker. Both methods didn’t work, is there anyway you are able to install Kura on Raspberry Pi 4 and when will there be an official support for Raspberry Pi 4s?

**Comment by MMaiero** [comment]
Hi,
what are the issues you are seeing?
Do you have any log that can be shared?

Best regards,
Matteo

**Comment by RuslanLevond** [comment]
Hey Matteo,

I am away right now but from what I can remember. It said that it has installed and no errors had come up. However, I couldn’t access Kura’s web services and kura.log file was missing.

**Comment by MMaiero** [comment]
When you have the chance, please share the content of Kura-console.log. Were you using java 8?

**Comment by RuslanLevond** [comment]
Sure I will share the log. I am pretty sure I used java 8 as in the tutorial you install version 8.

**Comment by MMaiero** [comment]
Hi @RuslanLevond any update on this?
