### ISSUE TITLE
Changing WLAN from AP to Station leaves DHCP server online

### ISSUE THREAD

**Issue by iacco** [eclipse/kura#2535]
**Describe the bug**
When you change the default WLAN interface of a device from Access Point to Station and connect to an SSID, the DHCP server you used to have active in the network, along with its network settings, stays active in the network you connected to, and becomes a "rogue" DHCP in the network.

**To Reproduce**
1. (if not already present) configure a WLAN interface as Access Point, and set the DHCP settings for it.
2. change under "wireless" the mode from Access Point to Station (the DHCP & NAT menu becomes disabled)
3. connect to an SSID
4. sniff the traffic with WireShark: you will see the device replying to DHCP discovers with the network settings of when the interface was set to Access Point

**Expected behavior**
The device does not have a DHCP server active and listening on a network it's connected on as station.

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 any device with WLAN capability. Reproduced with Kura 4.1

**Additional context**
N/A

**Comment by pierantoniomerlino** [comment]
@liaconissi I wasn't able to reproduce the issue. So, I closed it, but please reopen it if you find again the problem.
