### ISSUE TITLE
Kura  Making Wifi disable 

### ISSUE THREAD

**Issue by sharmmoh1983** [eclipse/kura#2538]
After installing Kura successfully and enabling wireless on raspberry pi, internet gets lost and new ip gets assigned. How to get wifi/internet access post Kura installation

What are the steps to add my wifi network through Kura UI.

**Comment by MMaiero** [comment]
Hello,
it's not clear to me, from your description, what is the setup you defined. But I would suggest to have a look at the following document: http://eclipse.github.io/kura/config/wi-fi-configuration.html

**Comment by sharmmoh1983** [comment]
@MMaiero 

I am trying to integrate modbus device to Kura . Do you have any sample for Modbus Simulator?

**Comment by MMaiero** [comment]
The project currently does not have Modbus support apart from an old protocol implementation that is deprecated nowadays: http://eclipse.github.io/kura/dev/kura-modbus-protocol.html
In the marketplace you can find a modbus driver provided by a company with a commercial licence: https://marketplace.eclipse.org/content/esf-modbus-driver

**Comment by sharmmoh1983** [comment]
So you are saying Kura doesnot have Modbus support hence no Modbus compatible device will work with Kura Gateway

**Comment by MMaiero** [comment]
Yes, there is no full open source solution at the moment.
As said, currently modbus is provided as a bundle from a separate company. To use it, you need to comply to the specific EULA.

**Comment by MMaiero** [comment]
Hi, did you manage to solve your issue?
Can this be closed?
