### ISSUE TITLE
upgrade minimal-json to reduce deadlock issue

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#2545]
**Describe the bug**
Using the minimal-jsonproject at version 0.9.4 there is a high instance of deadlocking.
https://github.com/ralfstx/minimal-json/issues/77
This is improved yet not entirely fixed in version 0.9.5
https://github.com/ralfstx/minimal-json/issues/88

```
kura/target-platform/config/kura.target-platform.build.properties :
              com.eclipsesource.minimal-json.version=0.9.4
```

I recommend upgrading to 0.9.5 or removing the dependency.

**Comment by MMaiero** [comment]
Hi @pstanton,
thank you for the suggestion.
If you are willing to make a pull request with the changes, it would be really appreciated.

Best regards,
Matteo

**Comment by pstanton** [comment]
I'm not familiar enough with your architecture.
