### ISSUE TITLE
Optimization and simplification of Network Monitor

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#2546]
While working on the implementation of the diversity antenna programming, I noticed some strange behavior of the Network Monitor. 
For example, when applying just a change in diversity antenna of the cellular connection while being connected to the gateway using eth1, the monitor restarts the eth1 connection causing an unnecessary loss of connection. 
There are also unnecessary reconfiguration of DHCP and DNS causing parasitic delays.

The Network Monitor should be reexamined a bit to fix these quirks.

**Comment by MMaiero** [comment]
Hi @pierrepitiot any update on this?
