### ISSUE TITLE
Disabled Tabs On Connected Device

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2556]
I have reported this bug on Kapua a while back but closed it, as it is more a Kura bug then kapua (probably), so I am opening it here. Original issue description is bellow, I am also adding [link to the eclipse/kapua github issue. ](https://github.com/eclipse/kapua/issues/2081)

If user adds another cloudService (e.g. org.eclipse.kura.cloud.CloudService-2), enters all the correct parameters and then connects to Kapua, _**Packages, Bundles, Configuration**_ and _**Command**_ tabs are disabled. 

**Testflow:**
1. Login as kapua-sys
2. Connect a live Kura device to Kapua (e.g. device0)
3. On device0, create another cloudService (e.g. org.eclipse.kura.cloud.CloudService-2), enter the correct credentials and connect to Kapua (change the name of device to e.g. device2)
4. In Kapua go to Devices, select device2 and observe the disabled tabs.

**Expected behavior:**
If device is connected, all the tabs should be enabled. 

**Screenshot:**
![screen shot 2018-10-04 at 13 14 40](https://user-images.githubusercontent.com/15121999/46470635-9e263400-c7d7-11e8-8fe4-dd6b0fc24d30.png)

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

**Comment by MMaiero** [comment]
Which version of Kura are you using?

**Comment by LeoNerdoG** [comment]
Hey,
this happened in October 2018 so I guess the 3.2.0. 
I will check also with 4.1 to see if I can reproduce.

**Comment by activey** [comment]
Ok I think I've "resolved" it. It was all related to cloud service pid value in kura instance. It HAS to be **org.eclipse.kura.cloud.CloudService**, no suffix/prefix or anything. Great it was mentioned anywhere, wasted like three days on that...

**Comment by MMaiero** [comment]
@LeoNerdoG Any update on this?

**Comment by LeoNerdoG** [comment]
hey @MMaiero,
I will try to check this today/tomorrow morning and update the issue.

**Comment by LeoNerdoG** [comment]
I have checked this with Kura 4.1.0 and I could not reproduce it so I am closing the issue.
