### ISSUE TITLE
why the cloudService must have predefined prefix pid name?

### ISSUE THREAD

**Issue by spnettec** [eclipse/kura#2564]
Why the cloudService must have predefined prefix pid name? 

I don't understand.

**Comment by MMaiero** [comment]
That was a simplification in order to match instances with factories in an easier way, without the need to perform costly introspection inside configurations.

**Comment by spnettec** [comment]
Can this pid be generated automatically? I'm doing web localization work.  This pid does not need to be displayed. Replace with description. Like i have done with "Create a new Component". You can try `docker run -d -p 1883:1883 -p 1888:1888 -p 8080:80 -p 443:443 -p 8088:8088  --name kura heyoulin/kura:v4.2.10`

**Comment by spnettec** [comment]
Merged latest snapshot and pushed v4.2.11.

I don't know whether i can commit PR for my revision. Because i have gone far away. 
I have fix many bugs and revise the api. I don't remember what bugs i have fixed.

**Comment by MMaiero** [comment]
I see. If you are willing to submit a PR, we will be very happy to review it.

Best regards,
Matteo

**Comment by spnettec** [comment]
Doublicate PID

![image](https://user-images.githubusercontent.com/1769060/67932926-c7dea400-fbff-11e9-8032-651a1c8ea743.png)

No error. Only show first created service configration

**Comment by MMaiero** [comment]
The check is performed per factory. There is no overall check. 
That could be an issue to be managed for example by the configuration service.
