### ISSUE TITLE
KuraComponent can't resolve its collaborators

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#257]
Some user reported that he need to programatically call `KuraComponent.setCamelContext(...)` and `KuraComponent.getCloudService()` before using the component.

**Comment by cdealti** [comment]
@hekonsek do we need to fix this for Kura 2.0?

**Comment by cdealti** [comment]
@hekonsek ping

**Comment by ctron** [comment]
I think this should be gone by the different handling of the in PR #381 [1]

Let's re-open is this issue comes back.

[1] https://github.com/eclipse/kura/pull/381
