### ISSUE TITLE
Asset blinking feature seems not to work

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2585]
**Describe the bug**
In current development version, the blinking feature of Kura Wires seems not to work properly

**To Reproduce**
1. Go to Kura Wires
2. Define a graph and save
3. See error

**Expected behavior**
The arcs between blocks should highlight when triggered.
From logs, there seems to be a data flow but no highlight in the arcs is displayed. 

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3] All
 - OS version: [e.g. provide the result of `uname -a`] All
 - Additional info: 

**Additional context**
N/A

**Comment by spnettec** [comment]
@MMaiero what error occur？

**Comment by MMaiero** [comment]
As described in the note. No visible error apart from the arcs not highlighted (probably events are not fired)

**Comment by spnettec** [comment]
Taken from my 4.3 snapshot. I have this problem before a month ago. I check my revision and find this PR can resolve this bug. Please test and review.

**Comment by spnettec** [comment]
I am pretty sure this bug is caused by compressed data by server.
So add this head can resolve the bug:
`response.setHeader("Content-Encoding", "identity"); `

**Comment by pierantoniomerlino** [comment]
I confirm that the line added by @spnettec fixes the issue about the wires blink.

**Comment by MMaiero** [comment]
Closing as PR #2609 is now closed.
