### ISSUE TITLE
Log report via MQTT

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#2596]
Troubleshooting remote systems is always a challenge and we end up in general by looking at the traces (or logs). This can be Kura logs or any other log on the system. This is also linked to the fact that Kura is not designed to easily give a feedback on the behavior of the platform except for a limited number of parameters (MQTT connectivity)

The possibility that we are considering is to develop a plugin that is able to collect the logs on the gateway and push them to MQTT (in Kapua for instance) so they can be analyzed from there.
The plugin takes as parameter the shell command that will be launched to collect the logs. That is quite trivial. A first version of the plugin is already under test.

On top, what is needed, but will be pushed for a later stage is to develop plugins that can collect data on the gateway and show them.

**Comment by MMaiero** [comment]
Hi @sterwen 
why not having such plugin able to inspect all the kura log and, based on configuration, publish messages to the cloud?
I mean: if the bundle is configured to report all the error/warn messages, the bundle will inspect kura log and publish a message when such event happens.
Furthermore, based on a request from the cloud, the bundle can publish in a message or set of messages all the logs in a range starting from a certain time. I believe this would be helpful for further and specific analysis.

Best regards,
Matteo
