### ISSUE TITLE
Add support for Quectel modems

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#2598]
Support for Quectel modem is required.  At least EC25-EC21/BG96

Modify the the code to add this modems support.

**Additional context**
The code is existing on our repo and we can create a pull request to merge it with the main kura repo

**Comment by MMaiero** [comment]
Hi,
Any contribution is more than welcome!
Please remember to comply to Eclipse requirements.

Best regards,
Matteo

**Comment by sterwen** [comment]
Concerning the code, this is 100% original code. No license of whatsoever attached. I believe this is what you mean by Eclipse requirements.

**Comment by sterwen** [comment]
A new pull request will be issued
