### ISSUE TITLE
no Publishing over mqtt on Yocto

### ISSUE THREAD

**Issue by llehman1** [eclipse/kura#2599]
We're experiencing problems when trying to publish data over MQTT.
We're using an UP Squared Board running Yocto.
Yocto details:
Version: Sumo
Layers: meta-java, meta-mender, openembedded

Kura in general is running stable on the board, also MQTT birth messages are sent to Kapua backend (also setting pages can be viewed etc.), but telemetry data aggregated along our WireGraph setup is not published.

The log does not show any messages regarding the publish component. It is correctly configured and the CloudConnection itself shows "connected".
It also does not show the "storing messages" - log entry altough the h2db is available.

The exact same build and configuration is working seamlessly on a raspberry pi running raspbian.

Someone else ever experienced a similar problem or has some deeper insights in the publishing process (likely a java related issue)?
Please ask for further details we should provide!

CloudConnection with Publishers
![Bildschirmfoto vom 2019-11-27 14-54-49](https://user-images.githubusercontent.com/25061511/69729316-62aa9f80-1126-11ea-9979-e3dd0c254858.png)

WireGraph Components (output tested)
![Bildschirmfoto vom 2019-11-27 14-57-15](https://user-images.githubusercontent.com/25061511/69729361-748c4280-1126-11ea-84da-929106ddd386.png)

db error in kura-console log
![Bildschirmfoto vom 2019-11-27 15-03-23](https://user-images.githubusercontent.com/25061511/69731457-3a24a480-112a-11ea-8266-160b7249e9f9.png)

h2db up squared - yocto (left) vs h2db raspberry pi - raspbian (right)
![Bildschirmfoto vom 2019-11-27 15-25-13](https://user-images.githubusercontent.com/25061511/69731560-62140800-112a-11ea-80c0-dee725a413f3.png)

**Comment by pierantoniomerlino** [comment]
@llehman1 Hi. Did you apply the same wire graph as the Rpi? I mean, did you download the graph from the Rpi and then applied it to the UPSquared?
Is there any log message in the test_logger component?

**Comment by MMaiero** [comment]
Hello @llehman1,
any update on this?
Otherwise we will close the issue for now.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Closing for now as there is no feedback from the user.
@llehman1 Please feel free to reopen it if needed.
