### ISSUE TITLE
Investigate why Camel quickstarts cannot be started anymore

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#260]
After merging new cloud service factories into Kura upstream, Camel quickstarts don't seem to work anymore. Camel SCR component is not started properly.

**Comment by hekonsek** [comment]
Hi Christiano,

Sorry, but this fix doesn't seem to work for me. Can you see Camel Context starting and messages being printed to logs?

**Comment by cdealti** [comment]
@hekonsek yes, I can see logs like these:
```
08:46:24,901 [Camel (camel-1) thread #7 - vm://myapp:xmltopic] INFO  lessThanTen:96  - Exchange[ExchangePattern: InOnly, BodyType: org.eclipse.kura.message.KuraPayload, Body: org.eclipse.kura.message.KuraPayload@3f19179d]
08:46:24,903 [Camel (camel-1) thread #7 - vm://myapp:xmltopic] INFO  MESSAGE_SENT_TO_CLOUD:96  - Exchange[ExchangePattern: InOnly, BodyType: org.eclipse.kura.message.KuraPayload, Body: org.eclipse.kura.message.KuraPayload@3f19179d]
08:46:24,904 [Camel (camel-1) thread #6 - vm://myapp:topic] INFO  equalToTen:96  - Exchange[ExchangePattern: InOnly, BodyType: org.eclipse.kura.message.KuraPayload, Body: org.eclipse.kura.message.KuraPayload@85d64c8]
08:46:24,906 [Camel (camel-1) thread #6 - vm://myapp:topic] INFO  MESSAGE_SENT_TO_CLOUD:96  - Exchange[ExchangePattern: InOnly, BodyType: org.eclipse.kura.message.KuraPayload, Body: org.eclipse.kura.message.KuraPayload@85d64c8]
```
Are you sure you have built the ``pr_fix_issue_260`` branch?

What is the output of ``ls`` in the OSGi Console, are the quickstart and aggregator components in the ``Satisfied`` state? If you are on the RPI the OSGi Console is available via ``telnet localhost 5002``.

**Comment by hekonsek** [comment]
Oh, I built the `develop`! Let me check against `pr_fix_issue_260`.

**Comment by hekonsek** [comment]
OK Cristiano. It works now. Many thanks!
