### ISSUE TITLE
[Web/UI] Cloud Service list items displays multiple times

### ISSUE THREAD

**Issue by Viha1208** [eclipse/kura#2600]
**Describe the bug**
Cloud status "Disconnected" displayed twice in "Cloud Services"

**To Reproduce**
1. Turned off(false) the "connect.auto-on-startup" option from "DataServices" tab. Cloud service is displays "Connected" status.
2.  Click on "Disconnect" option. Verified that 2 times Cloud status "Disconnected" displayed with "Cloud Factory PID" and "Cloud Service PID". Same information displayed here 2 times.
3. Again "Connected" and "Disconnected" cloud. Clicked on "Refresh" option and verified that "Disconnected" displayed only ones.

**Expected behavior**
I have only one cloud connection, so it should display only one entry of cloud status.

**Screenshots**
![image](https://user-images.githubusercontent.com/58774690/70623863-03c84880-1c45-11ea-8494-c13804547cce.png)

**Comment by MMaiero** [comment]
Hello, 
which version are you using?

From what I see, it seems a really old version of Kura.
Can you please provide more feedback?

Thanks.
Best regards,
Matteo

**Comment by Viha1208** [comment]
- Hi MMaiero,
I am using Kura 3.2.0 intel-edison build.

Is there any other information required?

**Comment by MMaiero** [comment]
That has been changed in newer versions of Kura. I would suggest you to move to a newer version of Kura

**Comment by MMaiero** [comment]
If it is ok, I'll close this issue since it should be fixed since Kura 4.0.0
