### ISSUE TITLE
systemctl restart kura does not work properly

### ISSUE THREAD

**Issue by alebianchin** [eclipse/kura#2602]
When running the systemctl restart kura command the kura process stops but doesn't start properly

When Kura is running : 
```
systemctl status kura
● kura.service - LSB: Kura initscript
   Loaded: loaded (/etc/init.d/kura; generated)
   Active: active (running) since Fri 2019-12-13 16:39:28 GMT; 2 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 271 ExecStart=/etc/init.d/kura start (code=exited, status=0/SUCCESS)
    Tasks: 102 (limit: 2200)
   Memory: 347.3M
   CGroup: /system.slice/kura.service
           └─330 java -Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:Heap

Dec 13 16:39:28 raspberrypi systemd[1]: Starting LSB: Kura initscript...
Dec 13 16:39:28 raspberrypi kura[271]: Starting Kura.
Dec 13 16:39:28 raspberrypi systemd[1]: Started LSB: Kura initscript.
```

After systemctl restart kura : 
```
systemctl status kura
● kura.service - LSB: Kura initscript
   Loaded: loaded (/etc/init.d/kura; generated)
   Active: active (exited) since Mon 2019-12-16 09:03:30 GMT; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5102 ExecStart=/etc/init.d/kura start (code=exited, status=0/SUCCESS)

Dec 16 09:03:30 raspberrypi systemd[1]: Starting LSB: Kura initscript...
Dec 16 09:03:30 raspberrypi kura[5102]: Starting Kura.
Dec 16 09:03:30 raspberrypi systemd[1]: Started LSB: Kura initscript.

```
kura-console.log : 
`Failed to start Kura. It is already running ...`

By runnning ps -ef you can see that there is no kura process actually running.

To solve you have to run systemctl stop kura and then systemctl start kura.

Kura running on Raspberry Pi 2 
Kura version : KURA_4.2.0-SNAPSHOT

**Comment by pierantoniomerlino** [comment]
KURA_4.2.0-SNAPSHOT (develop) uses the old SysV start-up scripts. Since the last Raspbian version uses SystemD, the SysV scripts are converted to a `kura.service` unit by `systemd-sysv-generator` (see man page), that simply wraps the original scripts in a SystemD unit. 

When the restart command is called (`systemctl restart kura`), the unit calls `/etc/init.d/kura restart` under the hood. The problem is that that command never worked :-((((

IMHO, we should move to SystemD unit...

**Comment by pierantoniomerlino** [comment]
According to [1] and [2], the default unit system in Raspbian is SystemD since 2015.
I think is time to drop the support for sysV init scripts...
