### ISSUE TITLE
Kura start a DHCP deamon on eth0 even if dhcpServer4.enabled is false

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#2612]
**Describe the bug**
Even with the following properties setup:
net.interface.eth0.config.dhcpServer4.enabled = false
Kura enable both a client AND a server. snapshot and journal file attached.
[kura-journal.log](https://github.com/eclipse/kura/files/4008056/kura-journal.log)
[snapshot_0.zip](https://github.com/eclipse/kura/files/4008057/snapshot_0.zip)

**To Reproduce**
1. Start Kura (4.0) with the snapshot attached
2. Check the journal with journalctl -u kura (with systemd)

**Expected behavior**
No DHCP server to be started on the eth0

**Screenshots**

**Target Environment (please complete the following information):**
 - ARM (iMX6)
 - OS version: Linux 4.9.150-imx6-sr
 - Additional info: 

**Additional context**

**Comment by MMaiero** [comment]
Hi,
just a confirmation, is this an error coming from a default distribution of Kura or from your customisation?

**Comment by pierantoniomerlino** [comment]
@sterwen I couldn't reproduce the issue on a RPi. Even replacing the snapshot_0 file, the DHCP server is not started.
I can suggest to update also the `kuranet.conf` file, setting `net.interface.eth0.config.dhcpServer4.enabled=false` and check if there are OS services that start the DHCP server outside Kura.

**Comment by pierantoniomerlino** [comment]
Closed for now since we weren't able to reproduce it.
