### ISSUE TITLE
Asset with only write channels still calls driver.read() method

### ISSUE THREAD

**Issue by alebianchin** [eclipse/kura#2626]
**Describe the bug**
If you develop a driver which does not support the read method (but it does support preparedRead()),
and you create a write channel, it will still call the read method, throwing an UnsupportedOperationException.

**To Reproduce**
1. Use a driver which does not support the read method
2. Create a write only channel
3. Go to the data tab.

**Expected behavior**
If there are no read channels the asset should not call the read method of the driver

**Comment by pierantoniomerlino** [comment]
As done in the [Eddystone Driver](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.driver.eddystone.provider/src/main/java/org/eclipse/kura/internal/driver/eddystone/EddystoneDriver.java), if a driver doesn't support read operation, the `read` method should return an empty `ChannelRecord`, setting the status to failed:

```
    @Override
    public void read(final List<ChannelRecord> records) throws ConnectionException {
        logger.warn(READ_ERROR_MESSAGE);
        for (final ChannelRecord record : records) {
            record.setChannelStatus(new ChannelStatus(FAILURE, READ_ERROR_MESSAGE, null));
            record.setTimestamp(System.currentTimeMillis());
        }
    }
```

Moreover, the `PreparedRead` method should return null:

```
    @Override
    public PreparedRead prepareRead(List<ChannelRecord> channelRecords) {
        logger.warn(READ_ERROR_MESSAGE);
        return null;
    }
```

In this way, no exceptions are thrown and the channels are correctly displayed in the web UI.
