### ISSUE TITLE
Eclipse Kura Installation hangs when adding maven repository

### ISSUE THREAD

**Issue by takaw** [eclipse/kura#2632]
**Bug Description**

The Eclipse Installer hangs when trying to install Eclipse Kura. The error occurs when trying to add the http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/ repository, as that URL needs to be accessed via HTTPS as of 15. January 2020.

**To Reproduce**
Steps to reproduce the behavior (from Eclipse Kura README):
1. Start the Eclipse Installer
2. Switch to advanced mode
3. Select "Eclipse for Committers" and configure the "Product Version", then select a JRE 1.8+ and press the Next button
4. Select the Eclipse Kura installer from the list.
5. Select the "Developer Type".
6. Update Eclipse Kura Git repository username and customize further settings if you like (e.g. Root install folder, Installation folder name)
7. Leave all Bootstrap Tasks selected and press the Finish button
8. Once you accept the license you will see the following error message in the log:

```
ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 HTTP Server 'Not Implemented': http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/content.xml
ERROR: org.eclipse.ecf.identity code=0 HttpComponents connection error response code 501.
  at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:276)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by MMaiero** [comment]
Hello, thanks for reporting. We are looking at this.

**Comment by leandrofabior** [comment]
I had this error too!

**Comment by leandrofabior** [comment]
I found the problem.
The instalation is call maven using http but it is not support on maven

![image](https://user-images.githubusercontent.com/6151744/73185064-2c74a680-40fc-11ea-9f58-54b6bad687c8.png)

**Comment by leandrofabior** [comment]
@MMaiero, 
You need to change the line 90 to https on  kura.setup file.
![image](https://user-images.githubusercontent.com/6151744/73197492-238dd000-4110-11ea-909e-32c5979194d1.png)

**Comment by pierantoniomerlino** [comment]
We should update also the Kura documentation about the Oomph installation procedure.
