### ISSUE TITLE
Asset configuration reseted after uploading new channels

### ISSUE THREAD

**Issue by manuelfa** [eclipse/kura#2639]
"Upload Channels" causes the reset of asset configurations like the timestamp.mode

**Steps to reproduce the behavior:**
1. Go to 'Driver and Assets'
2. Select a Driver and an Asset
3. Scroll down to 'Channels'
4. Click on 'Upload Channels'
5. Choose a csv
6. Click on 'Upload'
6. At the bottom of the side you will see that your configurations is reseted.

**Expected behavior**
Kura maintains the configuraton during the channel-update

![KuraAsset](https://user-images.githubusercontent.com/60254601/73059157-642de500-3e95-11ea-96ae-b68817afe53f.PNG)

**Target Environment:**
 - UP Squared Board
 - Kura 4.1
 

**Additional context**
We are working with a self-configured version of Kura 4.1.
It would be interesting if someone is able to reproduce this bug in order to know that this problem is not caused by our own changes.

**Comment by alebianchin** [comment]
Hi, are the configurations that get deleted already saved or are you uploading your channels before applying changes? In case of the latter it is intended to work that way.

**Comment by manuelfa** [comment]
> Hi, are the configurations that get deleted already saved or are you uploading your channels before applying changes? In case of the latter it is intended to work that way.

Yes, I saved the configurations before uploading the channels

**Comment by MMaiero** [comment]
@manuelfa we tried to reproduce the issue but, unfortunately, we couldn't confirm it.

Could you please provide us with more details, maybe the configuration you are using so that we can double-check?

**Comment by manuelfa** [comment]
I tried to reproduce it with the "normal" kura version but the bug appears too
Here is what i did:

1) Selected SINGLE_ASSET_GENERATED and applied
![1a](https://user-images.githubusercontent.com/60254601/73953220-631e9e00-4900-11ea-8221-da84ce5ab7e2.jpg)

2) Click on "Upload Channels", select file, check "Replace current channels", click on "Upload"
![2a](https://user-images.githubusercontent.com/60254601/73953655-02dc2c00-4901-11ea-8539-6ce390d2f1c4.jpg)

3) You can see the config is reseted
![3a](https://user-images.githubusercontent.com/60254601/73953731-230beb00-4901-11ea-8dc5-1b758449d51a.jpg)


@MMaiero what kind of detail will help, the snapshot0 ?

**Comment by MMaiero** [comment]
@manuelfa Thank you for the prompt response. That's definitely a bug. 

Thank you for reporting.
