### ISSUE TITLE
Wrong link on Eclipse Download page

### ISSUE THREAD

**Issue by alebianchin** [eclipse/kura#2640]
The download page for Kura 4.1 doesn't work for Intel UP2 Ubuntu 16 because it redirects to a file named `kura_4.1.0_intel-up2-ubuntu-16_installer.deb`. It should be `kura_4.1.0_intel-up2-ubuntu-18_installer.deb`and the name of the download should be changed to Intel UP2 Ubuntu 18 as well.

**Comment by MMaiero** [comment]
Fixed upstream in Kura Website
