### ISSUE TITLE
Review Rock960 support

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2647]
The Rock960 board seems to not have sufficient support from the community.

I would like to propose since now there is an AARCH64 Ubuntu distribution for Raspberry Pi, to investigate the feasibility of a profile for AARCH64 based on raspberry pi 3 or 4.

**Comment by MMaiero** [comment]
@tafitzgerald Do you have time to have a look at this and prepare a draft profile that we can review and test?

**Comment by tafitzgerald** [comment]
Yes, I can start while working issue #1958
