### ISSUE TITLE
OPC-UA DRIVER - Return a String Array

### ISSUE THREAD

**Issue by leandrofabior** [eclipse/kura#2658]
---
name: OPC-UA DRIVER - Return a String Array
about: I found a simple solution to return a StringArray from OPC UA.

---

**Is your feature request related to a problem? Please describe.**
My project need to process a StringArray from a OPC UA Server, I found a way to read it.

**Describe the solution you'd like**
On the DataTypeMapper class I insert the following code the map function.
![image](https://user-images.githubusercontent.com/6151744/73543994-e890e280-4416-11ea-884b-438a3a2a45d7.png)
` if (value instanceof String[]) {` 
 `                    String[] stringArray = (String[]) value;` 
 `                    return TypedValues.newStringValue(String.join(",", stringArray));` 
 `               } else {` 
`                     return TypedValues.newStringValue(value.toString());` 
`                 }`

**Additional context**
I have we this demo server to test:  opc.tcp://uademo.prosysopc.com:53530/OPCUA/SimulationServer

The original value reads using Prosys OPC UA Browser.
![image](https://user-images.githubusercontent.com/6151744/73544915-f7789480-4418-11ea-97a5-7471fa03c5ba.png)

I have used this asset configuration to test.

![image](https://user-images.githubusercontent.com/6151744/73544303-a4521200-4417-11ea-9e78-5bc5fafe0344.png)

The result was the values separated with comma as it is represented on the value field of OPC UA browser.

![image](https://user-images.githubusercontent.com/6151744/73544575-3a863800-4418-11ea-89f1-b0ec92545263.png)

It results the same value on the log:
![image](https://user-images.githubusercontent.com/6151744/73544823-c730f600-4418-11ea-9fde-0c10dd046652.png)

**Comment by MMaiero** [comment]
@alebianchin Can you have a look at this issue?

**Comment by MMaiero** [comment]
@leandrofabior Can you please have a look at the PR and provide comments on that?
