### ISSUE TITLE
OPC-UA DRIVER - node.id is too small

### ISSUE THREAD

**Issue by leandrofabior** [eclipse/kura#2659]
**Is your feature request related to a problem? Please describe.**
Some OPC-UA node names are too big to for the field, it makes reading difficult. The original field is smaller the 5 chars.
This is a sample on a node.id of a device from Altus:
`|var|XP300.Application.OPC_R.OPCUA_TAG`

**Describe the solution you'd like**
The ideal is that field (org.eclipse.kura.core.configuration.metatype.Tad) have a size property or something like that. It should be used to set size on the tag `<input type="text">` and the col size on `<table>` on HTML.

**Describe alternatives you've considered**
The field size is adjusted by the label name, I suggest insert some underline "_" before and affer the word node.id to remediate this on the OpcUaChannelDescriptor class. It make the input bigger.
This is not a pretty solution, but it improve so much the readability of the screen
![image](https://user-images.githubusercontent.com/6151744/73546482-13316a00-441c-11ea-8485-0779c947f412.png)

See the result:
![image](https://user-images.githubusercontent.com/6151744/73546919-ca2de580-441c-11ea-85b3-48088322237e.png)

**Comment by MMaiero** [comment]
@alebianchin Can you have a look at this issue?

**Comment by nicolatimeus** [comment]
Hi @leandrofabior, can you please try a Kura version built from the current develop branch? The changes introduced by PR [1] should allow you to manually resize configuration table columns.

[1] https://github.com/eclipse/kura/pull/2492

**Comment by leandrofabior** [comment]
HI @nicolatimeus i will that, It's a good solution too.
Thanks!
