### ISSUE TITLE
Oomph installer  - mvn needed to be installed

### ISSUE THREAD

**Issue by leandrofabior** [eclipse/kura#2661]
**Describe the bug**
The mvn, higger than 3.3, needs to be installed on the machine to buid project correctly

**To Reproduce**

1. Go to 'Oomph installer'
2. Do all the steps
3. The maven build process will return error because maven is not installed.
4. It's not possible to build without Eclipse. Using git/kura/build-all.sh

**Target Environment (please complete the following information):**
Centos 7

**Comment by eavelardev** [comment]
Solution in process for Kura 4.2.0 #2643
