### ISSUE TITLE
Minimum Kura build

### ISSUE THREAD

**Issue by sebascarra** [eclipse/kura#2671]
Hi everyone.

I am in an enterprise environment where I'm having issues procuring certain Kura's dependencies and plugins because of their vulnerabilities, which we will have to find a workaround for.

As a good starting point, we would like to focus on those components that are mandatory to build a Kura gateway. For the moment all the devices that will be linked to a Kura gateway will be TCP/IP devices (no Raspberry Pi's GPIOs, no Can/RS485/etc. and no wireless protocols such as Zigbee or Bluetooth for now).

The Kura gateways will be linked to **Kapua**. Moreover, Kura has to run in a Docker container inside the gateway.

With this in mind, what are the Kura modules that I have to build? The build process I'm following is at: https://wiki.eclipse.org/Kura/Getting_Started (shown below)

Build the **target platform**
cd ~/git/kura/target-platform
**mvn clean install**
Build the **core components**
cd ../kura
#Build with CAN support
mvn -Dmaven.test.skip=true -f pom.xml -Pcan clean install
#Build without CAN support
**mvn -Dmaven.test.skip=true -f pom.xml clean install**
**Prepare the for the Eclipse workspace**
**mvn -f manifest_pom.xml eclipse:clean && mvn -f manifest_pom.xml eclipse:eclipse
mvn -f pom_pom.xml eclipse:clean && mvn -f pom_pom.xml eclipse:eclipse**

Thanks everyone.

**Comment by MMaiero** [comment]
Hi @sebascarra,
to build Kura from source you can use the script available here: https://github.com/eclipse/kura/blob/develop/build-all.sh
Out of the box, you can choose to build Kura with or without Can support. 
If you need to manage what you want to build for your special case, you'll have to change and adapt the pom files.

To build the docker container you can use the instructions available here: https://github.com/eclipse/kura/tree/develop/kura/container/kura

Best regards,
Matteo

**Comment by MMaiero** [comment]
@sebascarra Can this issue be closed?
Any feedback you want to share?

**Comment by jiekechoo** [comment]
Is there any docs show me how to rebuild Kura? I want to change bundles for my hardware, I just need a guide. 

Thanks.
Jiekechoo

**Comment by MMaiero** [comment]
Hi,
did you try the links suggested in the previous comment (https://github.com/eclipse/kura/issues/2671#issuecomment-583754413)?

**Comment by jiekechoo** [comment]
I mean, want to build a minimal Kura zip to deploy in an Embedded device, the device contains 256MB mem, so I want to remove unnecessary bundles, how to do it?

**Comment by MMaiero** [comment]
I would suggest to create a new profile and start looking at this file https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/ant/build_equinox_distrib.xml that wraps all the profile creation to the final package

**Comment by jiekechoo** [comment]
Thanks, MMaiero

Is the file build_equinox_distrib.xml  global ? Can I modify it for specific profile ? Such as I created a new hardware profile for my device.

Could you give me some advice? WeChat: jiekechoo


Jiekechoo

**Comment by MMaiero** [comment]
The file is global, but can use properties provided by the profile.
