### ISSUE TITLE
Kura community on Slack/Gitter or similar site

### ISSUE THREAD

**Issue by sebascarra** [eclipse/kura#2672]
Hi everyone. Does Kura have a community of developers on something like Slack or Gitter (such as Kapua's on https://gitter.im/eclipse/kapua)???

I need to post several questions regarding changing some of Kura's dependencies and leaving out certain modules that we might not be able to build in a restricted environment.

I need to find an active community of Kura developers where we can discuss things more informally and dynamically, so as not to flood the Issues section in this repository.

Thank you very much.

**Comment by MMaiero** [comment]
Hi @sebascarra, 
we don't have a Slack or Gitter but you can use the developers mailing list or the Kura forum to post your questions.
Best regards,
Matteo

**Comment by sebascarra** [comment]
Thanks, I have posted a question. Expecting to get a shed of light soon :)
