### ISSUE TITLE
Eclipse kura on raspberry pi

### ISSUE THREAD

**Issue by jameel89** [eclipse/kura#2674]
I installed eclipse kura on raspberry pi but getting the problem. It is not getting start
 Loaded: loaded (/etc/init.d/kura; generated)
   Active: active (exited) since Sun 2020-02-09 22:34:15 IST; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 399 ExecStart=/etc/init.d/kura start (code=exited, status=0/SUCCESS)

Feb 09 22:34:15 raspberrypi systemd[1]: Starting LSB: Kura initscript...
Feb 09 22:34:15 raspberrypi kura[399]: Starting Kura.
Feb 09 22:34:15 raspberrypi systemd[1]: Started LSB: Kura initscript.

**Comment by MMaiero** [comment]
Hello,
do you see any log in /var/log/kura.log?

**Comment by jameel89** [comment]
Yes I am attaching the kura.log an
![IMG_20200210_100222](https://user-images.githubusercontent.com/60852436/74121466-a4a79580-4bed-11ea-82ea-12e3308052cc.jpg)d kura-console.log

![IMG_20200210_100055](https://user-images.githubusercontent.com/60852436/74121454-9e191e00-4bed-11ea-8e40-fe86030f2e88.jpg)

**Comment by MMaiero** [comment]
Hi, 
I believe you are trying to run Kura with a JVM later than version 8.
As of now, Kura is only compatible with Java 8.

Best regards,
Matteo

**Comment by jameel89** [comment]
Thanks for your reply.

**Comment by jameel89** [comment]
Can we install kura on rasbean buster and rasbean full

**Comment by MMaiero** [comment]
Yes.
As pointed out in the official documentation, the strict requirement we have is in running on Java 8

**Comment by jameel89** [comment]
Kura Started (pid=355) ...
Whats this

**Comment by MMaiero** [comment]
I'm sorry, but I don't understand your comment.
Can you provide more context?

**Comment by jameel89** [comment]
Eclipse kura is running on my monitor, but wlan0 as configured in dhcp for static address is not available. I can only use internet through eth0 cable. wlan0 is not showing. If i see ifconfig again there is no ip address shown. The two lines representing internet status at the top are also showing two red cross

**Comment by jameel89** [comment]
I mean can we run kura on wlan0. I am not getting kura on wlan but it's
working fine on ethernet cable.

**Comment by MMaiero** [comment]
By default, Kura should set wifi in access point mode. You should be able to see a new SSID if you perform a scan with your PC.
You can change this by simply logging into the Kura web UI and change the network configuration.

**Comment by jameel89** [comment]
After installing kura, I am not able to use putty for the raspberry pi. How can I use putty or vnc.

**Comment by MMaiero** [comment]
Putty should be usable since Kura sets the gateway in dhcp mode: the gateway should receive an IP and you should be able to access it using that IP.
No idea about vnc, but the principle should be the same.

**Comment by jameel89** [comment]
How the gateway receive an ip address.

**Comment by jameel89** [comment]
Thanks to you. I connected it through putty and vnc. But when I unplud ethernet cable raspberry is no longer work on putty and vnc. Is it mandatory to always connect R.Pi (kura installed) to the ethernet cable for the internet.

**Comment by MMaiero** [comment]
It obviously depends on the network configuration you have defined in Kura.
If you choose, you can also connect to the Internet using wifi. You just simply need to configure your desired setup using the networking section in the Kura web UI.

**Comment by jameel89** [comment]
I installed eclipse kura on raspberry pi. What is the procedure to connect the sensors with the R.PI(Kura) and collect the data. How can I write the code for any iot application. How to deploy the package in Kura

**Comment by jameel89** [comment]
Is there any end to end iot system using Eclipse paid training available.

**Comment by MMaiero** [comment]
Hi, 
to learn how to use and develop on Kura you can use the official documentation available here: http://eclipse.github.io/kura/
This is an open source project. If you want support or training you have to refer to the companies that are basing their commercial products on the Eclipse Kura codebase.

**Comment by jameel89** [comment]
I connected temperature sensor to kura. Now where can I see output on kura.

**Comment by MMaiero** [comment]
I'm sorry, but there is not enough context to provide you with some help.

**Comment by jameel89** [comment]
I made a system using eclipse kura wires. I also made the circuit and
connected the sensors. But as I am getting data from sensors. How can I
view the data. Do I need to connect cloud.

**Comment by MMaiero** [comment]
If you are using an asset, you can see the data in the "data" section of the corresponding asset.
Using plain wires, you can plug a logger and connect the data stream to the logger to see the data flowing.
