### ISSUE TITLE
Eclipse Kura and Eclipse Unide (Production Performance Management Protocol)

### ISSUE THREAD

**Issue by jameel89** [eclipse/kura#2676]
How can we use Eclipse unide (Production Performance Management Protocol) with kura.

**Comment by MMaiero** [comment]
We never tried out that. So, it probably needs some adaptation and integration work.

For future questions, that are not directly issues, I would suggest you to use the [Kura forum](https://www.eclipse.org/forums/index.php/f/273/). Maybe there, having a wider audience can provide you more feedback.

**Comment by jameel89** [comment]
I installed kura in raspberry pi. Connected sensors. Now I am unable to
connect to the cloud. Please help

**Comment by MMaiero** [comment]
I'm sorry, but once again there is no sufficient detail to understand what is the issue and how to suggest a proper solution.

Where are you trying to connect to?
What is the configuration?

Best regards,
Matteo

**Comment by LeoNerdoG** [comment]
Hi @jameel89,
as commented in one of the newest issue I would try the following (these are "generic" steps that you should always check before posting an issue):

 - the IP address I type for the Cloud is not correct
 - the cloud's broker is not working properly, although IP is OK. 
 - Username or Account name is not present in the cloud or there is a syntax mistake
 - Password is wrong (this happens most often on my side)

Try to reboot the device if possible and check that cloud is present where should it be. Also try to connect another device if you have it, just to check if the connection works properly. 

But as MMaiero said we need additional context to be able to help.
