### ISSUE TITLE
Default Cloud Conneciton Missing When Rolling Back to "0" Snapshot

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2684]
If user rolls back to seeded snapshot ("0" snapshot), the default Cloud Connection is missing (see screenshot bellow). Reload does not help, user has to restart the device entirely in order to get the default cloud connection. 

**Testflow:**
1. Go to Cloud Connections, enter all the necessary information for cloud connection (local Kapua in my case). 
2. Connect the device to Kapua
3. Go to Settings, rollback to the snapshot "0" 
4. After the process is finished, go to Cloud Connection again
Observe that the default Cloud Connection is not ther, although it should be. 

**Expected behavior:**
If user rolls back to "0" snapshot, the default cloud connecitons hould be present, but with default values. 

**Screenshots**
![Screenshot 2020-02-28 at 09 06 32](https://user-images.githubusercontent.com/15121999/75522404-31ce5500-5a0a-11ea-9f18-2a0c454a2443.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Should be solved now in develop

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
