### ISSUE TITLE
Cloud Publisher Name and Example Publisher Name Cannot be the Same

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2685]
If you want to create example publihser with name "publisher1" everything is fine. 
But if you want to create Cloud publisher with the same name, Kura returns an error (and vice versa). 
Is this OK? I guess there can be same names for Publisher Service and Cloud publisher. 

**Testflow:**
1. Login to Kura with admin/admin credentials
2. Install Example Publisher package with name "publisher1"
3. Go to Cloud Services, try to create a Publisher with name "publisher1"
4. Observe the generic error that appears when trying to do so.

**Expected behavior**
Is this the expected behaviour or not? 

**Screenshots**
![Screenshot 2020-02-28 at 09 18 11](https://user-images.githubusercontent.com/15121999/75522876-419a6900-5a0b-11ea-9415-673e1fdc3d01.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
In the current implementation, the name assigned to a component is directly used in OSGi and there, no duplicates are permitted. That is the reason of the error
