### ISSUE TITLE
Kura Reports an Error When User Clicks "Cancel" at New CloudConnection Creation

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2688]
If user clicks on "+ New Connection" in Cloud Connections and clicking Cancel without entering anything in PID section (just clicking on it), kura returns an error that PID field cannot be empty, which is not OK, since user has pressed "Cancel" anyway. 

**Testflow:**
1. Login as admin/admin into Kura
2. Go to Cloud Connections, click on "+ New Connection" and without populating the "PID" field (just click on it) click "Cancel"
3. Observe the error (screenshot bellow)

**Expected behavior**
If user clicks on "Cancel", dialogue box should close immediatelly without any errors. 

**Screenshot:**
![Screenshot 2020-03-04 at 13 53 03](https://user-images.githubusercontent.com/15121999/75881514-7fd6c480-5e1f-11ea-9a91-fb7f20bb23ec.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Not able to see this too from develop

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
When you open the new cloud connection window, click on "PID" (to set focus on it) and after that click Cancel - this way you will be able to reproduce the issue.

**Comment by MMaiero** [comment]
ok, now I see it. But I'm not sure that is an issue. 
I mean, the field is evaluated on focus lost (validateOnBlur)

**Comment by LeoNerdoG** [comment]
Hm, I understand. This is basically the same issue as the one where user clicks on "x" and all the fields in error state are for a brief moment in error state. 
If you think this is not an error, I would close it, but if there is a way, to check this case in the code, I would preffer that ("if focus on field and user clicks on "x" or "cancel" -> don't validate).

**Comment by MMaiero** [comment]
I don't think there is such possibility, honestly. But I'll look again in it. If not, I'll close the issue
