### ISSUE TITLE
Some Wire Components Not Transparent

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2691]
Some of the wire components in Wire graph service have transparent background and some do not - is this done on purpose? 
Transparent background:
 - Camel Consumer
 - Timer
 - Logger

Non_transparent background:
 - All others

**Tesflow:**
1. Login to Kura as admin/admin
2. Go to Wires, try to create a wire component with name that has 10k+ characters
3. Observe the behaviour

**Expected behavior**
There are some wire components that are transparent (the hide under every other component, regardless of the order they were created in) and other ones are solid as they should be (they hide 

**Screenshots**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I don't see it. Can you check with develop?

**Comment by LeoNerdoG** [comment]
I was not able to reproduce this, I am closing the issue. Maybe there was some glitch in the browser (e.g. uncleared chacge or something similar).
