### ISSUE TITLE
Kura Centers Wire Graph on First Created Item Uppon Return

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2693]
If user changes views from Wire graph to something else and then returns, the focus on wire graph is on the first created item and not on the graph as whole. 
This should be changed, since it has no sense to have focus on one element, if you have a big wire graph. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wires, create several wire components, connect some of them
3. Go to "packages" or any other service and then return to Wires
3. Observe focus of the Wire graph - it is on the first component that was added and not on the whole graph

**Expected behavior**
When user comes back to Wire view, the whole graph should be shown or rather focus should not be n a specific item.

**Screenshot:**
![Screenshot 2020-03-09 at 09 56 59](https://user-images.githubusercontent.com/15121999/76202302-e7608b80-61f4-11ea-95d2-4875c1c3009f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Duplicate to #2694
