### ISSUE TITLE
Kura Centers Wire Graph on First Created Item Upon Return to Wire Service

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2694]
If user does something and then clicks "Reset", the focus on wire graph is on the first created item and not on the graph as whole. 
This should be changed, since it has no sense to have focus on one element, if you have a big wire graph

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wires, create several wire components, connect some of them
3. Go to "packages" or any other service and then return to Wires
3. Observe focus of the Wire graph - it is on the first component that was added and not on the whole graph

**Expected behavior**
When user comes back to Wire view, the whole graph should be shown or rather focus should not be n a specific item.

**Screenshot:**
![Screenshot 2020-03-09 at 09 56 59](https://user-images.githubusercontent.com/15121999/76202302-e7608b80-61f4-11ea-95d2-4875c1c3009f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Can you double check if this still exists? I'm not able to recreate from develop

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I was not able to reproduce this issue, so I am closing it for now. If I stumbel upon it again, I will reopen the issue.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I was able to reproduce this issue (by accident but it doesn't matter).
Please follow the testflow bellow and please let me know if you can replicate it.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wire Graph, add some components to it (let them be unordered), apply the changes
3. Go to Packages, install a package (in my case it was wire-devel-component)
4. Return to Wire graph and observe the behaviour (gif bellow)

![123](https://user-images.githubusercontent.com/15121999/86894065-d112ff80-c102-11ea-8d12-188d7c04c945.gif)

**Comment by MMaiero** [comment]
No, I'm still not seeing it. We can leave it open for a further review. But I see it as a P2 issue
