### ISSUE TITLE
Component Name Inteferes With Wire Graph Border

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2696]
When user creates a wire component and clicks on it to see its parameters, the component name interferes with the wire graph borders (see screenshot bellow). This happens for all components. I suggest that the bottom window gets moved down a bit. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wire Graph, create a component (e.g. Camel Publisher)
3. Select the newly created component and obaserve the interference with the wire graph border (screenshot bellow).

**Expected behavior**
Component name should not interfere with the wire graph borders.

**Screenshot:**
![Screenshot 2020-03-10 at 09 09 01](https://user-images.githubusercontent.com/15121999/76292741-0a03aa80-62b0-11ea-99c9-b65e4058c999.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I believe this has been fixed in develop.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
this still hasn't been fixed. This only happens if the screen is resized a bit though, so it does not manifest always, but only under certain circumstances.

**Comment by MMaiero** [comment]
ok, so let's keep it as a P2
