### ISSUE TITLE
"Download Channels" Button Disabled in Wire Graph

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2700]
If user creates a wire graph asset and adds at least one channel to the asset, the "Download Channels" button is disabled until user click "Apply". is this normal behaviour or should "Download Channels" button be activated immediatelly after you create at least one channel (like "Delete channel" button is activated)?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to packages, install [Wires developer componenst fr Eclipse kura 4.x.y](https://marketplace.eclipse.org/content/wires-developer-components-eclipse-kura-4xy)
3. Go to Wire Graph, add "WireAsset" block 
4. Select the newly created WireAsset block and add at least one channel to it - observe te "Download Channels" button

**Expected behavior**
Should "Download Channels" button be activated immediatelly after you create at least one channel?

**Screenshot:**
![Screenshot 2020-03-11 at 07 44 03](https://user-images.githubusercontent.com/15121999/76389925-b99e5280-636c-11ea-995e-e81aa92649ed.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
It's a design choice due to how things are managed in the interaction with OSGi
