### ISSUE TITLE
Assets And Drivers Can be Deleted From Wire Graph?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2701]
if user creates an asset from Wire graph (driver already present), there are no problems, the asset shows in "Drivers and Assets" under the specified driver. 
But if user deletes the asset from wire graph, it is also deleted from the driver itself - is this behaviour normal? Because if user creates an asset in "Drivers and assets" view and then adds this asset into the graph, when graph (or component) is deleted, the asset is still present under the specific driver.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to packages, install [Wires developer componenst fr Eclipse kura 4.x.y](https://marketplace.eclipse.org/content/wires-developer-components-eclipse-kura-4xy)
3. Go to Drivers and Assets view and add a driver (e.g. driver1) with corresponding asset (e.g. asset1)
4. Go to Wire Graph, add "WireAsset" block (asset1)
5. Add another asset, but this time create a driver (e.g. driver2) with corresponding asset (e.g. asset2)
6. Apply changes and then delete the graph
7. Go to Drivers and assets and observe the consequence - driver2 and asset2 are deleted from Kura

**Expected behavior**
Is it normal for Wire graph to be able to delete Drivers and assets that have been created from Wire graph directly?

**Screenshots**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Hi @LeoNerdoG,
can you please provide reference about the Kura version you have currently under test?
I believe we had such discussion in the issues not long ago and a fix was provided.

Matteo

**Comment by LeoNerdoG** [comment]
Hej @MMaiero,
I am testing the latest 4.1.0 release that can be found [here](http://www.eclipse.org/downloads/download.php?file=/kura/releases/4.1.0/kura_4.1.0_raspberry-pi-2-3_installer.deb).

**Comment by MMaiero** [comment]
Ok, for this specific issue, I would ask to give a try to 4.2.0-SNAPSHOT. It should contain some fixes for this item here.

**Comment by LeoNerdoG** [comment]
Ok I will try with the specified version and report back.

**Comment by MMaiero** [comment]
@LeoNerdoG Any update on this?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I was not able to reproduce the issue in the latest develop branch, so I am closing this.
