### ISSUE TITLE
CRON Interval Field Not Validated Properly in Wire Graph

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2704]
When selecting "CRON" tye of interval in timer wire component, there is not validation for CRON field, user can write literally anything into it and Kura will accept it. Validation of this field is necessarry. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wire Graph, create a timer wire component (e.g. timer1)
3. Select timer1, select "CRON" type and type anything into the "cron.interval" field - there is no error regradless of the input.

**Expected behavior**
"cron.interval" field should be validated. 

**Screenshot:**
![Screenshot 2020-03-11 at 10 46 22](https://user-images.githubusercontent.com/15121999/76403968-ff1b4980-6385-11ea-8bb5-355cb7b96fe7.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
The OSGi metatype that is the basis for the visualisation does not have a cron type.
So the field is set as a plain text field. That's the reason why there is no specific validation for that field.
Unfortunately there is not so much we can do at the moment for this.
