### ISSUE TITLE
Vertical Line Moving When Clicking on "InstallUpgrade" Button in packages

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2708]
If user clicks on "Install/Upgrade" button in Packages, the whole vertical line moves a bit to the right as it would "compensate for something", although there is enough room for all the UI elements. 
After the windows is closed, everything moves back. 
This is not a serious bug, but I think it should be fixed, as it can get annoying (see GIF bellow)

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, click on "install/Upgrade" button
3. Observe the vertical line that splits left side of screen from the right

**Expected behavior**
Vertical line should not be moving when "Install/Upgrade" button is clicked.

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/76745057-7fbabb00-6775-11ea-8163-4cd959461281.gif)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG I can't reproduce this issue. Which browser are you using? Have you tried to modify the window size when this happen?

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have checkd this on Firefox (Version: 77.0.1 (64-bit)) and Safari (Version 13.1.1 (version: 15609.2.9.1.2). 
I am able to reproduce this every time (browser window should not be full screen).
