### ISSUE TITLE
"Copyright" Footer Covers Installed Packages And All Other Content

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2709]
If user narrows the browser window vertically, the "Copyright" footer covers the packages list (and all other lists as well). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install several packages
3. Narrow the browser window vertically (see screenshot bellow)
4. Observe the "Copyright" footer that covers packages list 

**Expected behavior**
Footer should never cover anything regardles of browser size. 

**Screenshot:**
![Screenshot 2020-03-16 at 11 44 02](https://user-images.githubusercontent.com/15121999/76748945-f0fd6c80-677b-11ea-8a5a-e1800ed82b63.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
This is what I see on my installation:

![Kura](https://user-images.githubusercontent.com/2919570/84017838-86755a80-a97f-11ea-9918-8b276f0d85a7.gif)

**Comment by pierantoniomerlino** [comment]
The issue can be reproduced simply scrolling down the page with the list of installed packages.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have checked this PR and it looks good - I think it can be merged.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
