### ISSUE TITLE
[Bluetooth] BluetoothUtil always use the default adapter (e.g. hci0)

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#271]
The adapter specified in the configuration of the BluetoothLE Sensor Tag app is not respected.
BluetoothGattImpl and BluetoothUtil always assume the default (hci0) adapter.

**Comment by pierantoniomerlino** [comment]
When the gatttool command is run, no adapter is specified. In BluetoothUtil.java the startSession method must be modified adding -i hciX.
