### ISSUE TITLE
Clickable Text in "Install/Upgrade Package" Dialogue Box

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2714]
When user opens "Install/Upgrade Package" window and clicks on "No file selected", this acts the same way as if user would click on the "Browse" button itself - is this the expected behaviour or not? Because it can be confusing for some users if they are not expecting this. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, click on "+ Install/Upgrade" button
3. Click on "No file selected" text and observe the behaviour

**Expected behavior**
Should browser open the "Browse" window when user clicks on the file name or only ehn user click directly on "Browse" button?

**Screenshot:**
![Screenshot 2020-03-25 at 08 32 53](https://user-images.githubusercontent.com/15121999/77512408-47049b00-6e73-11ea-98ec-5381fcabf16f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG I think that this is the expected behavior. The clickable area is defined by the widget itself.

**Comment by LeoNerdoG** [comment]
hey @pierantoniomerlino,
OK, I am closing this due to upper comment.
