### ISSUE TITLE
No Icons for Some of the Buttons in UI

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2716]
There are some buttons in the UI that don't have icons in them as others buttons do.
 - Reset button in Devices -> Command
 - Exceute button in Devices -> Command
 - Renew DHCP Lease in Network

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Devices -> Command and observe the Reset annd Excecute buttons - there are no icons in them
3. Go to Network, observe the Renew DHCP lease - there is no icon in it

**Expected behavior**
There should be icons in all the buttons

**Screenshot:**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
Also in Device->System Logs->Download

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
