### ISSUE TITLE
"Reset" Button Resets all the Fields in Settings?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2717]
This is more a question than it is an actual issue. 
If user enters something into varius fields in SSL Configuration, Server SSL Certificate and Device SSL Certificate and then presses "Reset" button, everything gets reset. I suggest that every view would have a different reset button, because user can do seomething in one field and want sto reset this, butthe side effect is that everything else gets reset. This is meant if user does this accidentally - a lot of data is lost. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Settings, change some fields in the tabs mentioned above
3. Click "Reset" button and check all the previously modified fields - they are all reset to previous value

**Expected behavior**
Every tab should have its own "reset" button in case end-user makes a mistake and presses it. 

**Screenshots**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
I think that the "reset" button affects only the tab you're looking, but when you move to another tab, all the modifications are lost. IMHO, we could implement the same behavior of the firewall tab: when the user clicks to a tab, it'll be prompted with a confirmation window that alerts that all the modifications will be lost.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
