### ISSUE TITLE
SSL Configuration Gets Saved Although User Does Not Save Them

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2718]
If user changes something in "ssl.default.trustStore" and then changes the view without saving the changes in this field, the changes are still there when you return. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Settings, click on SSL Configuration, change value of ssl.default.trustStore field
3. Without saving it change view to something else (e.g. Devices)
4. Change view back to Settings and observe the changed fields

**Expected behavior**
If user does not save the configuration, al the fields should be reset to previous values. 

**Screenshot No. 1:**
![Screenshot 2020-03-25 at 13 19 00](https://user-images.githubusercontent.com/15121999/77536696-0caff380-6e9d-11ea-92b6-388c9dea0aaa.png)

**Screenshot No. 2:**
![Screenshot 2020-03-25 at 13 19 06](https://user-images.githubusercontent.com/15121999/77536682-03bf2200-6e9d-11ea-893b-95a6b9b6555e.png)

**Screenshot No. 3:**
![Screenshot 2020-03-25 at 13 19 16](https://user-images.githubusercontent.com/15121999/77536707-1174a780-6e9d-11ea-8788-b338668f472f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Could you please check again this issue? I suppose that this could be solved with the last commits about the settings tab.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino, I have verified that this issue has been resolved, I was unable to reproduce it.
