### ISSUE TITLE
SSL Fields Stay in Error State Although Fields Reset

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2719]
Although user resets all the fields or changes the views without saving changes, all the fields are marked red. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Settings -> try to change anyt of the SSL fields
3. After you enter something in the fields, erase it and press Reset
4. Observe the fields that are marked in red

**Expected behavior**
After the Reset button is pressed, all the fields should be stripped of the red makration. 

**Screenshots**
![Screenshot 2020-03-25 at 13 42 31](https://user-images.githubusercontent.com/15121999/77537713-cd82a200-6e9e-11ea-9763-401969fbef06.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by mstankovic** [comment]
@pierantoniomerlino  this issue doesn't occur with the #3034

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have rechecked this in develop and noticed that it has not been properly resolved. 
If you go to Device SSL Certificates, click on "Private Key" and then somehwere outside (so field is in error state), you can change views easily between tabs and the field stays in error state. 
Can you please check if you can reproduce this?

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Uff.... you're right! I reopen the issue. Thanks!

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
the problem persists. If you change focus to one of the mandatory fields, enter nothing and swtich views, there is no prompt for inclomplete fields - cna you check again please?
