### ISSUE TITLE
No Confrmation When Trying to Reset SSL Configurations

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2729]
If user tries to reset certain configuration (e.g. in WireService) Kura always askas the user if he is sure that he wants to do that, but there is no pop-up window when user tries to reset SSL configuration - when Reset button is pressed, everything gets reset immediatelly. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Settings -> SSL Configuration/Server SSL Certificate/Device SSL Certificate
3. Enter something in any of the fields and then click Reset button
4. Observe the lack of pop-up confirmation window.

**Expected behavior**
When Reset button is pressed, a pop-up windows should show up in order for user to confirm the choice or not. 

**Screenshot (example of confirmation windows from Wire Service):**
![Screenshot 2020-03-27 at 11 11 25](https://user-images.githubusercontent.com/15121999/77745681-fe3c1600-701b-11ea-9838-fe7a0430db38.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by LeoNerdoG** [comment]
hey @MMaiero 
I have checked this and if user changes service view (goes from Settings to e.g. CloudService), Kura asks the user if he wants to discard changes (which is OK), but if user clicks YES and then returns, this is the case: 
![Screenshot 2020-07-06 at 10 51 23](https://user-images.githubusercontent.com/15121999/86574901-caf01800-bf76-11ea-9e35-cf13afa16248.png)

But: if user changes a tab in the SSL configuration, the changes are actually reverted. 
Can you please check this?

**Comment by MMaiero** [comment]
Is this still an issue?

**Comment by LeoNerdoG** [comment]
Will check and let you know.

**Comment by LeoNerdoG** [comment]
I have rechecked this and it is resolved (user gets asked if the changes should be reset or not).
