### ISSUE TITLE
No Icons in "OK" and "Apply" Buttons in WireAsset in WireGraph 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2730]
There is no icon on "OK" and "Apply" buttons in WireAsset component in Wire Graph (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Wire Graph and try to add WireAsset
3. Observe the "OK" and "Apply" button that don't have the icons

**Expected behavior**
"Apply" and "OK" buttons don't have any icons like other "OK" and "Apply" buttons.

**Screenshot No. 1:**
![Screenshot 2020-03-27 at 09 30 50](https://user-images.githubusercontent.com/15121999/77745414-82da6480-701b-11ea-90fe-5326faa9d734.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I believe we should remove the icons from all the buttons
