### ISSUE TITLE
cloudCat Description not Formatted Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2734]
When user creates instance of cloudCat service, its description is not very readable and also not formatted properly (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Create an instance of CloudCat (click "+" in Service)
3. Select the newly created CloudCat and observe its description (screenshot bellow)

**Expected behavior**
Description should be in more readable format. 

**Screenshot:**
![Screenshot 2020-03-30 at 14 53 41](https://user-images.githubusercontent.com/15121999/77915012-0e135e80-7297-11ea-9723-952b91544812.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
@nicolatimeus Can we reference the documentation page instead of having a long description?
