### ISSUE TITLE
Tooltip of cloudCat Instance is Too Long

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2735]
When user creates an instance of CloudCat and then hovers above it, the tooltip appears, which is OK. The problem is that the tooltip is just too long - it should be shortened. 

**Testflow:**
1. Login to Kura as admin/admin
2. Create an instance of cloudCat with unique name
3. When created, hover on it with mouse and observe the tooltip

**Expected behavior**
Tooltip should be short and descriptive. 

**Screenshot:**
![Screenshot 2020-03-30 at 15 01 24](https://user-images.githubusercontent.com/15121999/77915468-cf31d880-7297-11ea-8dc5-523987f2d0cc.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Related to #2734
