### ISSUE TITLE
Everything Before "." Symbol Ignored When Creating New Service Instance

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2736]
When creating new instance of a service, everything before "." symbol is ignored, so user can presumably create instances with the same name. For example: "1.1" is transformed into "1" and "1.2" is transformed into "2".

**Testflow:**
1. Login to Kura as admin/admin
2. Click on "+" and select a factory component (not important which one)
3. In the "name" field enter "1"
4. Create another one with name "1.1" and another one with name "1.2"

**Expected behavior**
Either "." symbol should not be allowed or nothing should be ignored before/after it. 

**Screenshots**
![Screenshot 2020-03-30 at 15 10 06](https://user-images.githubusercontent.com/15121999/77917050-4bc5b680-729a-11ea-9245-91a0ec84e2a4.png)

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3]
 - OS version: [e.g. provide the result of `uname -a`]
 - Additional info: 

**Additional context**

**Comment by MMaiero** [comment]
This was a precise choice taken in the past and that was kept for compatibility.
During time we added inside of the component view the definition of the factory that generated the instance. I will close it for now as we are interested in keeping the compatibility and the behaviour with previous versions of Kura
