### ISSUE TITLE
Heater Package Cannot be Deleted

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2741]
If user installs Example Heater package to Kura, there is a "Delete" button on the right hand side, but it is not functional - user can delete this package only by uninstalling it (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install Heater package [(click here)](http://download.eclipse.org/kura/releases/4.1.0/org.eclipse.kura.demo.heater_1.0.500.dp)
3. Go to Service, select the newly installed Heater package and try to delete it - the Delete buttonis inactive

**Expected behavior**
Delete button in Heater pckage should be active. 

**Screenshots**
![Screenshot 2020-03-31 at 14 48 20](https://user-images.githubusercontent.com/15121999/78029453-e688c880-7360-11ea-8fa8-173a3262d66a.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Heater is a singleton component not one that is created from a factory.
The only way to delete a singleton component is by removing the bundle that provide such feature.

**Comment by LeoNerdoG** [comment]
Ok, I am closing the issue due to the upper comment.
