### ISSUE TITLE
Generic Error When Switching Fast From "Packages" to "Wire Graph"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2742]
If user switches view between Packages and Wire Graph very fast, Kura reports an generic error (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages and click on "Wire graph"
3. Repeat second step several times and observe the behaviour

**Expected behavior**
If user switches between views veery fast this should not cause an error. 

**Screenshots**
![Screenshot 2020-04-01 at 11 15 08](https://user-images.githubusercontent.com/15121999/78125263-11325a00-7411-11ea-841e-3e7cea0a1db6.png)

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3]
 - OS version: [e.g. provide the result of `uname -a`]
 - Additional info: 

**Additional context**

**Comment by MMaiero** [comment]
Do this still happen?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I was unable to reproduce this exact issue, but if user clicks several times on same service (or starts switching between them very fast), Kura gets stuck in "cog mode" - see screenshot bellow. This can be fixed only with reloading the whole browser window. I suggest to keep this open or rather to continue with resolving it. 

![Screenshot 2020-09-07 at 14 11 19](https://user-images.githubusercontent.com/15121999/92386426-127c5700-f114-11ea-885e-c2c3a723999e.png)
