### ISSUE TITLE
Syntax Error in Sink Wire Component Description

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2743]
There is a syntax error in Sink wire component description. It is "If set to true the component will print on the log the time interval in milliseconds between the last two received envelopes" but should be "If set to true, the component will print on the log the time interval in milliseconds between the last two received envelopes.".

**Testflow:**
1. Login to Kura as admin/admin
2. Go Packages, install [wires development package](https://marketplace.eclipse.org/content/wires-developer-components-eclipse-kura-4xy)
3. Go to Wire graph, select "Sink" component and place it into the wire graph
4. Observe its description bellow.

**Expected behavior**
See above. 

**Screenshots**
![Screenshot 2020-04-01 at 11 00 50](https://user-images.githubusercontent.com/15121999/78119012-0fb06400-7408-11ea-8fa3-3068997d2f39.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
can you please check if the change made in PR #3063 is visible in develop branch? I have built it, but the change is not visible, the old text is still there? I deleted cache from my browser, built the right branch etc....but the change does not seem visible?

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Hi! Yes, the update is visible in develop... You can try to remove the .m2/repository/org/eclipse/kura in your home folder and re-build kura.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I cannot believe this - I tried eveerything, rebuilding kura from scratch, deelting .m2/, deleting caches in browser, using different browsers even reinstalling Raspbian on Rpi...but the change is not visible...am I missing something obvious??

**Comment by pierantoniomerlino** [comment]
Hi @LeoNerdoG , I really don't know... here is the screenshot of my installation:

<img width="1613" alt="Screen Shot 2020-09-10 at 9 01 31 AM" src="https://user-images.githubusercontent.com/2919570/92692578-a92f5a80-f344-11ea-8551-68ef4babe0c5.png">

**Comment by LeoNerdoG** [comment]
This is extremely annoying...I willt try to get to the bottom of this.
