### ISSUE TITLE
Download Channels Button Not Active When Channel Created

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2750]
When user creates a channel in one of the component in a specific driver, the "Download channels" button is not active until user presses Apply button - is this on purpose? Because one would expect that the "Download Channels" button would be active as soon as the channel is created AND selected. 

**Testflow:**
1. Login to Kura as admin/admin
2. Install Wires-development-package from Eclipse marketplace
3. Go to Wiregraph, select Wire Asset 
4. When created, click on it and add a channel to its asset
5. Observe the "Download Channels" button

**Expected behavior**
See above. 

**Screenshots**
![Screenshot 2020-04-01 at 13 55 40](https://user-images.githubusercontent.com/15121999/78134458-7ccff380-7420-11ea-82c3-02085cc8555c.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
The download channels uses the stored/saved configuration.
So, yes, that was an initial choice made when the feature was developed.

**Comment by LeoNerdoG** [comment]
Closing due to upper comment. 
@MMaier thanks for the clarification.
