### ISSUE TITLE
Driver Connection Delay Can be Set to Negative Value?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2754]
If user tries to enter a negative value into the driver's Connection Delay field in Wire Graph, Kura does not report an error. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install Wires-development-package from Eclipse Marketplace
3. Go to Wire Graph, create a wireAsset comonent and add a channel to it
4. Go to Driver tab and try to enter a negative value to Connection Delay field
5. Kura returns no errors when negative value entered

**Expected behavior**
Kura should return an error when entering a negative value.

**Screenshots**
![Screenshot 2020-04-02 at 09 59 43](https://user-images.githubusercontent.com/15121999/78255648-e111b680-74f7-11ea-89d9-9ed92157cee7.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
That depends on the driver metatype. 
The dummy driver is just a simple example driver not meant for direct use but just for development purposes
