### ISSUE TITLE
Different Behaviour When Adding and Uploading Channels

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2755]
If user adds a channel "manually" (by clicking "Add channel" button) to an asset in Wire Graph, the "Download" button gets disabled and Reset and Apply buttons get enabled. This is fine, but when user uploads channels, this does not happen, although user might add several new channels as well. We should unify this behaviour regardless of user adding channels manually or uploading them. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install Wires-development-package from Eclipse Marketplace
3. Go to Wire Graph, create a wireAsset comonent and add a channel to it
4. Try to upload a random .txt file via "Upload channels" button
5. Observe the error message

**Expected behavior**
Same behaviour when adding channels manually or uploading them.

**Screenshots**
/
Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I believe #2996 has addressed also this issue.
@LeoNerdoG can you please check and close this issue if the assumption is correct?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
yes, you are right. I have checked this and it has been successfully resolved with PR #2996.
