### ISSUE TITLE
Different Sizes of CheckBoxes in Wire Graph

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2756]
If user resizes the window size to 90%, the checkboxes in asset component get different sized (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages, install Wires-development-package from Eclipse Marketplace
3. Go to Wire Graph, create a wireAsset comonent and add a channel to it
4. Try to resize the browser window, observe the size of checkboxes

**Expected behavior**
If user resizes the browser window, checkbozes should remain the same (proprotional to the browser window size). 

**Screenshots**
![Screenshot 2020-04-02 at 15 39 18](https://user-images.githubusercontent.com/15121999/78258857-1cae7f80-74fc-11ea-809b-08c9bdd6c449.png)

UPDATE:
I found out that this happens only at certain resolutions - I am adding the GIF bellow to show this. 

![123](https://user-images.githubusercontent.com/15121999/78330205-ba995d00-7583-11ea-9691-ada1d109c9c1.gif)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Tested with Chrome on the latest develop, but I'm not able to see it.
I'm not sure if what you are seeing is kura Ui related

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I was unable to reproduce this issue, so I am closing.
