### ISSUE TITLE
Different Order of Cloud Connections?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2760]
if user create e.g. cloudService-1, cloudService-2,  cloudService-3,  cloudService-11,  cloudService-111,  cloudService-20, the will not be listed from 1 to 111, but they will be listed as:
 - 1
 - 11
 - 111
 - 2
 - 20
 - 3

This way it is really hard to track a lot of cloud connections, so I suggest that the list gets order simply from 1 up. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Cloud Connection, create several cloudConnections as shown above
3. Observe the list and its order

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-04-03 at 15 30 28](https://user-images.githubusercontent.com/15121999/78366205-74162380-75c0-11ea-866c-130547480e37.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I think a lexicographical ordering is applied there

**Comment by MMaiero** [comment]
@LeoNerdoG Do you have a proposal for that?
Otherwise I believe we can close this issue

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
yes, I suggest that all the items in Kura  (not only in CloudConenctions) are in "normal" order, so: 1,2,3,4,...10,11,12,13,...21,22,23,...
Otherwise it is very hard to track them.
