### ISSUE TITLE
No Example for CamelFactory Connection Service PID ? 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2762]
When creating for example "org.eclipse.kura.cloud.CloudService" or "org.eclipse.kura.cloudconnection.eclipseiot.mqtt.ConnectionManager" cloud connections, there is an example in the input field that shows, how the field should be populated or rather in what form the new cloud connection should look like, but there is no such example when creating "CamelFactory" cloud connection  - see screenshot bellow. 
The question here is if the cloud connection in form of CamelFactory has a predifined form or not? Is this the case here? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Cloud Connections, click on "+ New Connection"
3. Select "org.eclipse.kura.camel.cloud.factory.CamelFactory" and observe the input field bellow - there is no example as for the other two

**Expected behavior**
When creating CamelFactory cloud connection, there should be an example in the input field.

**Screenshot:**
![Screenshot 2020-04-03 at 15 06 20](https://user-images.githubusercontent.com/15121999/78364640-1d0f4f00-75be-11ea-87ff-9c952eb18f87.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
Show an help message is decision of the implementor. In this case the Camel cloud connection was donated by a contributor.
