### ISSUE TITLE
Different Design for Presenting Cloud Connection Names

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2766]
If user creates e.g. CamelFactory cloud connection, its name in the bottom tab is presented as "cloudname"-CloudFactory (screenshot No. 1). But if user creates either "CloudService" or "ConnectionManager" cloud connection the name convention is simply the last part of its PID (screenshot No. 2 and No. 3). I suggest that the name when createing CloudFactory gets "standardized - so it looks like the other examples.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Cloud Connections, create one camelFactory cloud connection (e.g. conn1)
3. Create one CloudService cloud connection(e.g. conn2)
4. Create one ConnectionManager cloud connection (e.g. conn3)
5. Observe the names in the bottom tabs (screenshots bellow)

**Expected behavior**
Names on the tabs bellow should be presented in the same way. 

**Screenshot No. 1:**
![Screenshot 2020-04-06 at 12 19 34](https://user-images.githubusercontent.com/15121999/78549144-2f79ca80-7802-11ea-854f-68b9ac1415e2.png)

**Screenshot No. 2:**
![Screenshot 2020-04-06 at 12 29 06](https://user-images.githubusercontent.com/15121999/78549160-386a9c00-7802-11ea-8ced-35de4f06a491.png)

**Screenshot No. 3:**
![Screenshot 2020-04-06 at 12 29 02](https://user-images.githubusercontent.com/15121999/78549168-3a345f80-7802-11ea-932f-5b2e44eaf3c6.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment]
I don't think that with the current design we can actually force it. Maybe we can make an alignment for the project distributed bundles. But everything in this case is decided by the cloud connection implementor.
