### ISSUE TITLE
New Firewall Fields Stay in Error State

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2768]
If user wants to open a port with invalid parameters, Kura colours the invalid fields in red. If user then cancels the operation and clicks "New" again, all the invalid fields from before are still marked red.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click "new" and enter all or some parameters that are invalid
3. Click Cancel and then "new" again - observe the fields that are marked red

**Expected behavior**
If user cancels the operation and then again clicks on "new" button, all the fields should be reset. 

**Screenshot No. 1:**
![Screenshot 2020-04-06 at 11 44 04](https://user-images.githubusercontent.com/15121999/78546555-eaec3000-77fd-11ea-9723-a38d000608a7.png)

**Screenshot No. 2:**
![Screenshot 2020-04-06 at 11 47 36](https://user-images.githubusercontent.com/15121999/78546562-ec1d5d00-77fd-11ea-9cbe-71c6d65983cf.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG this issue should be fixed with one of the last PR about firewall. Can you confirm?

**Comment by LeoNerdoG** [comment]
@pierantoniomerlino I am confirming that PR #2915 fixes this issue.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
