### ISSUE TITLE
Duplicate Entries Allowed in Firewall

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2770]
If user is trying to add a duplicate open port in firewall, Kura reports a warning, but the port is added anyway (see screenshot bellow). Follow the bottom testflow in order to duplicate the issue. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, add a port (e.g. 7100) wihtout specifying anything else
3. When you click Submit and the window closes, don't click anything before clicking "Edit"
4. When clicked Edit, the edit window should appear. Do not change anything, just press Submit
5. Close the warning and observe the firewall list - there is a duplicate entry. 
6. Click on Apply - Kura does not report any errors.

**Expected behavior**
Duplicate entries in Firewall should not be possible. 

**Screenshot:**
![Screenshot 2020-04-06 at 11 41 43](https://user-images.githubusercontent.com/15121999/78545160-9b0c6980-77fb-11ea-8478-5c0ee6b7c779.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG I was able to reproduce the issue: it seems that the selected row object in the table is still active, so clicking on the edit or delete button, the methods are activated with that object. I'll fix it cleaning the selected row. BTW, this issue can be hidden deselecting the Edit and Delete buttons, as suggested in #2771 and #2772

**Comment by LeoNerdoG** [comment]
@pierantoniomerlino I have checked this and it seemed to be working but it is not properly fixed. If you select an entry and then deselect it, the Edit button stays enabled (see GIF bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, add a port (e.g. 7100) wihtout specifying anything else
3. Click Submit
4. Select an entry (any entry in the firewall list) and unselect it (CMD+click/CTRL+click)
5. Observe the active button (Edit and Delete) although nothing is selected

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/80212247-6c81f180-8637-11ea-9c29-b3fecd661c94.gif)


Can you reopen the issue please, so we can track it properly? Thanks!

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully fixed - the select/deselect now works fine.
