### ISSUE TITLE
Edit Button in Firewall Active Although Nothing Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2771]
If user navigates to Firewall tab and looks at the buttons that are active, there is Edit button that is active although nothing is selected. When pressed, nothing happens. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall tab and observe the Edit button
3. Although nothing is selected, the edit button is active. When pressed, nothing happens.

**Expected behavior**
Edit button should not be active if nothing is selected. 

**Screenshot:**
![132](https://user-images.githubusercontent.com/15121999/78544782-f853eb00-77fa-11ea-9d69-086b8e7b56bb.gif)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I am confirming that this issue has been resolved, as Edit button is not active if nothing is selected.

**Comment by LeoNerdoG** [comment]
@pierantoniomerlino I have checked this and it seemed to be working but it is not properly fixed. If you select an entry and then deselect it, the Delete button stays enabled (see GIF bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, add a port (e.g. 7100) wihtout specifying anything else
3. Click Submit
4. Select an entry (any entry in the firewall list) and unselect it (CMD+click/CTRL+click)
5. Observe the active button (Edit and Delete) although nothing is selected

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/80212247-6c81f180-8637-11ea-9c29-b3fecd661c94.gif)


Can you reopen the issue please, so we can track it properly? Thanks!

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG I didn't know that it was possible to de-select a row with CMD+click/CTRL+click! Thanks.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
