### ISSUE TITLE
Delete Button in Firewall Active Although Nothing Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2772]
If user navigates to Firewall tab and looks at the buttons that are active, there is Delete button that is active although nothing is selected. When pressed, nothing happens. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall tab and observe the Delete button
3. Although nothing is selected, the delete button is active. When pressed, nothing happens.

**Expected behavior**
Delete button should not be active if nothing is selected. 

**Screenshot:**
![Screenshot 2020-04-06 at 11 43 09](https://user-images.githubusercontent.com/15121999/78545255-ce4ef880-77fb-11ea-9968-6f6c98951ed8.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I am confirming that this issue has been resolved, as Delete button is not active if nothing is selected.
