### ISSUE TITLE
 public List<GwtClientExtensionBundle> getConsoleExtensions()   will  warn “The response could not be deserialized”

### ISSUE THREAD

**Issue by Czou** [eclipse/kura#2773]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3]
 - OS version: [e.g. provide the result of `uname -a`]
 - Additional info: 

**Additional context**

**Comment by LeoNerdoG** [comment]
Hey @Czou,
can you please add a detailed description and testflow to the issue and possible screenshot? This way the development team will be able to solve the issue faster and without too much interaction with you. 

Leo

**Comment by MMaiero** [comment]
Hi @Czou 
as @LeoNerdoG stated, we need a description of the error and a way to recreate it.
If you can provide all the details, it will be really helpful.
In the meantime I'm closing the issue. Feel free to reopen it if needed.
