### ISSUE TITLE
Edited Port Jumps to the Bottom of the List

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2776]
If user edits one of the port numbers in Firewall, this entry jumps to the end of the list (see screenshots bellow where I edited port number "11"). This is very impractical if there are other port entries or if the list is very long, becasue user than has to scroll down in order to make a change (if he accidentally edited it). 
Entry also drops to the bottom if it is unsuccessfully edited (e.g. we want to change the protocol from udp to tcp but there is already another port with exact same configuration).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, select one of the ports (e.g. "1450") and change one of its parameters
3. Observe how the entry jumps to the bottom
4. if you click "Reset", the entry will jump back to its old position

**Expected behavior**
Port entries should not be thrown to the bottom if they are edited. 

**Screenshot No. 1:**
![Screenshot 2020-04-07 at 09 00 48](https://user-images.githubusercontent.com/15121999/78641124-03695280-78b1-11ea-842e-e064137e2ee5.png)

**Screenshot No. 2:**
![Screenshot 2020-04-07 at 09 01 00](https://user-images.githubusercontent.com/15121999/78641120-02382580-78b1-11ea-9ed3-6cd5f5153cba.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
