### ISSUE TITLE
Possibility of Editigin Unexisting Port

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2778]
@pierantoniomerlino 
This issue is similar to #2771, but I am reporting it anyway, so we don't forget about it. 
If user deletes a port, clicks Apply and immediatelly after that the "Edit" button, an Edit window opens with the possibility of editing the previosly deleted port. This should not be possible, as Edit button should be disabled anyway. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click on "new" and add a port "123". 
3. Click Apply
4. Select "123" and delete it
5. Click Apply
6. Without clicking anything else, click on "Edit" - observe the window that opens
7. When trying to click "Submit", nothing happens (as port "123" does not exist anymore

**Expected behavior**
User should not be able to edit an unexisting firewall port. 

**Screenshot:**
![Screenshot 2020-04-07 at 08 48 17](https://user-images.githubusercontent.com/15121999/78638446-95bb2780-78ac-11ea-93fb-95865c77fbb9.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
Yes, it's related to the previous one, but it worth to report it anyway. The fact is that the selected row object is still active and can be indeed edited. This should be fixed if we disable the Edit button after the application and when no rows are selected.

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
