### ISSUE TITLE
No Limit for "Port" Field in Firewall

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2779]
There are no limits for "Port or Port Range" field in Firewall. user only has to ignore the error thrown by Kura and Apply changes - although kura reports an error, all the changes are saved. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall and try to add a port with very long number (e.g. 900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909900090990009099000909)
3. If Kura prompts "duplicate error" exception, ignore it
4. Click Apply
5. Ignore the error thrown and observe the entry - port gets listed, although it shouldn't, as the port number is too large

**Expected behavior:**
There should be some sort of validation of the "Port" field.

**Screenshot:**
![Screenshot 2020-04-07 at 15 35 52](https://user-images.githubusercontent.com/15121999/78675528-7b517000-78e5-11ea-9cf5-e6c96638f970.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
