### ISSUE TITLE
Port "00" is Acceptable in Firewall

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2782]
If user enters only "0" into Port number, Kura highlights the field in red, which is OK (Screenshot No. 1), but if user enters "00", there is no error, user can normally add port with "00" to the list. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall service and click "new"
3. Try to add "0" as port number and click Submit - there is an error, whichc is OK (Screenshot No. 1)
4. Try to enter "00" into the Port number - there is no error (Screenshot No. 2)

**Expected behavior**
I guess that port "0" should not be allowed?

**Screenshot No. 1:**
![Screenshot 2020-04-07 at 15 38 35](https://user-images.githubusercontent.com/15121999/78676038-32e68200-78e6-11ea-9843-ebbaa36faa7f.png)

 **Screenshot No. 2:**
![Screenshot 2020-04-07 at 15 39 17](https://user-images.githubusercontent.com/15121999/78676042-3417af00-78e6-11ea-9d32-0405611e91ac.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
BTW, "01" is accepted and it's equivalent to "1". But it doesn't trigger the duplication check...

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
