### ISSUE TITLE
Generic Error When (Un)permitted Interface Name Too Long

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2785]
If user enters a (un)permitted interface name that is too long (see bellow), Kura throws a generic error. There should be an error thrown, but the lack of description makes it hard to debug (especially if user creates several open ports). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click "new" and add a very long (un)permitted interface name (e.g. "ioeirwroeriwepriweprwerwekrjlwrkerjlkwjrelwejrlwkjer"
3. Click Submit and then "Apply"
4. Observe the generic error

**Expected behavior**
If interface name is too long, thre should be an error in the field itself and not after the user clicks "Apply".

**Screenshot:**
![Screenshot 2020-04-08 at 08 38 18](https://user-images.githubusercontent.com/15121999/78752384-4e986980-7974-11ea-8413-c03ffc88d5d0.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
It seems that the limit is 15.

**Comment by pierantoniomerlino** [comment]
Closed by #2796

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
