### ISSUE TITLE
Firewall Port Range can be set in Reverse Order

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2786]
This issue is connected to issue #2502. 
User can still enter port range in the reverse order, which is stiill not OK, but the firewall table does not get deleted. I suggest that this field gets additional validation that if user inputs a reverse port range, it produces an error. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click "new"
3. In "Port range" enter "7200:7100"
4. Click Submit and then Apply - observe the generic error thrown by Kura
5. Click on "Cloud Connections" (or any other service), discardh changes
6. Return to Firewall service - the reverse port range is saved

**Expected behavior**
It should not be possible for user to enter the port range in reverse order. 

**Screenshot:**
![Screenshot 2020-04-08 at 11 26 09](https://user-images.githubusercontent.com/15121999/78768095-c2923c00-798b-11ea-8ecf-86441f86eda0.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
The same happens in the source port range field.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
