### ISSUE TITLE
"Source Port Range" Field Accepts Only One Number Without Error

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2787]
If user enters one number into the "Source Port Range", there is no error from Kura as one would expect, because the name of the field is port "range". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall service, click "new"
3. In "Source port range" enter only one number (e.g. 7100)
4. Press Submit and later Apply
5. Observe the lack of error/warning - is this OK?

**Expected behavior**
I guess that there should be an error when entering only one number into the "source port range"?

**Screenshot:**
![Screenshot 2020-04-08 at 11 34 23](https://user-images.githubusercontent.com/15121999/78781664-f3c93700-79a0-11ea-876a-c8ebb13ba901.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
Since `iptables` accepts both a single source port or a range of ports, I prefer to modify the labels.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfully resolved.
