### ISSUE TITLE
(Un)permitted Interface NameField Stays in Error State After Adding Spaces

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2788]
If you add something similar to the example bellow, in the (un)permitted interface name fields, they stay in error state, although user cleans everything and enteres something different in (e.g. "eth0"). 
Please follow the bellow testflow to recreate the issue. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click "new"
3. In (un)permitted interface name enter "asdasd             a               " 
(some characters, then several spaces, then character again and then spaces again)
4. Add valid Port number
5. Click Submit
6. Change the (un)permitted interface name to soemthing real (e.t. eth0) 
7. Observe the field which stays in error state. 
Evan if you close the window and open it again, it stays in error state.

**Expected behavior**
If "(un)permitted interface name" field is empty, it should not be in error state. 

**Screenshot:**
![Screenshot 2020-04-08 at 14 52 23](https://user-images.githubusercontent.com/15121999/78786424-06476e80-79a9-11ea-9e6b-c75823656062.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG I think that this issue has been already fixed by #2796. Could you please check if you can reproduce it anymore?

**Comment by MMaiero** [comment]
This is still happening to me even with #2814 fixes applied

**Comment by LeoNerdoG** [comment]
I have verified that this isse has been resolved. I have tried this on Kura 4.2.0_SNAPSHOT from May 4th 2020.
