### ISSUE TITLE
"Internal Port" and "External Port" in Port Forwarding not Marked as Mandatory

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2789]
If user wants to set port forwarding, there are three fields that are marked as mandatory and those are:
 - input interface
 - output interface
 - Lan address

But when user clicks Submit after populating those fileds, the Internal port and External port are put in error state, because they were not populated (they are not marked as mandatory). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Port Forwarding
3. Enter all the mandatory parameters (valid)
4. Hit Submit and observe the two fields in error state

**Expected behavior**
If the two fields are mandatory, they should be "equiped" with the asterix symbol ("*") as all amndatory fields. If they are not, user should be able to submit the settings without specifying those. 

**Screenshot:**
![Screenshot 2020-04-09 at 07 40 31](https://user-images.githubusercontent.com/15121999/78861773-ed38cf00-7a35-11ea-832f-8f31e4eb9f2f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by LeoNerdoG** [comment]
@pierantoniomerlino 

I have a question regarding solution for this issue - if user does not set the internal/external port, they get set to "0" (both). I think this is not the correct way, becasue if fields are amndatory, they should be filled by user. If not, they can get populated with some default values, like this solution provides. So I guess we just have to remove the asteriks "*" symbol from the fields? 

Also I get generic error when I try to apply the changes (see screenshot bellow), but the changes get set anyway (if i reload the page, the settings are there, even if I click "reset", the changes seem to be set).

![Screenshot 2020-05-06 at 09 20 57](https://user-images.githubusercontent.com/15121999/81147629-f789b280-8f7a-11ea-9b5e-edc80ba5fe54.png)

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Thank you for the check. I'll take a look at that. In the meantime, I reopen the issue to keep track of it.

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Ahhh, now I understand! If a field in the form is not "touched", the check is not triggered and the user can submit an empty values... It applies also on the open ports and ip forwarding.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
yes, exactly. Sorry if I didn't write it more accuratelly. If you'll have any more questions regarding my issues, just ping me, because sometimes I have multiple issues "under test" and I might not write the testflow or description down properly.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
