### ISSUE TITLE
[Web UI] Cloud connection icon should show the connection status of the default connection

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#279]
For the time being the red/green cloud connection icon will only show the status of the default connection.

**Comment by MMaiero** [comment]
@cdealti Do we have to apply changes only to web2 or also to the old web bundle?

**Comment by cdealti** [comment]
@MMaiero I believe at this point the classic web UI is behind web2. For example, it misses the changes to properly display multiple cloud connections (I guess).
I would not update web and see what happens ;)
