### ISSUE TITLE
Edit Button Actieve Although Nothing Selected in Firewall -> Port Forwarding

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2791]
This issue is best described through a testflow, which I am providing bellow. In short: if nothing is selected when clicking "Edit" button in Firewall -> Por Forwarding, then Kura gets an old configuration of the port that ise being forwarded (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Port Forwarding 
3. Click "new" and enter the following parameters:
 - Input interface: "1"
 - Output interface: "2"
 - LAN Address: 1.2.3.4
 - protocol: TCP
 - internal port: 10
 - external port: 20
 - Masquerading: yes
All other fields should remain blank
4. Click Submit and then Apply - observe the generic error, close it
5. Select the newly created entry and click "Edit"
6. Change "Input interface" to "eth0" and "output interface" to "eth1"
7. Click Submit and Apply
8. Without selecting anything just click "Edit"
9. Observe the parameters - they are the old ones. From where does Kura get these parameters?

**Expected behavior**
If nothing is selected, Edit Button should be disabled - this way user cannot encounter this scenario.

**Screenshot:**
![Screenshot 2020-04-09 at 08 55 23](https://user-images.githubusercontent.com/15121999/78867369-49552080-7a41-11ea-9b81-ad5cdcf52a05.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Is it possible that this issue has been already addressed by #2814? Could you please check with the last build of Kura develop if this problem is still present?

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
you are right, this issue indeed has been resolved via PR #2814. 
I am closing this, becaus eit has been fixed.
