### ISSUE TITLE
Fields in Firewall Service Marked Red When Canceling Creation/Edit

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2792]
If user clicks on one of the mandatory fields when creating/editing an entry in "Open Ports", "Port Forwarding" or "IP Forwarding/Masquerading" and then the upper right "x" to close the window, the fields are for a brief moment in error state. 
This is inot a critical issue, but some users could ask themselves what is wrong with the field. I know that every time you change the focus from empty mandatory field it gets in error state, but is there a way to fix this if clicked "x"?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall ("Open Ports", "Port Forwarding" or "IP Forwarding/Masquerading") and click "new" or 
2.1 Select a entry and click on Edit
3. Select one of the mandatory fields (modify them if they're not empty) and then click "x" in the upper right corner
4. Observe the mandatory field that is in error state for a brief moment

**Expected behavior**
See suggestion above. 

**Screenshots**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment]
The form fields are not cleared when the dismiss button is clicked.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have checked this in latest develop branch and there is a corner case that is not being covered. 
If user entere something in the mandatory field, then immediatelly deletes the content and clicks "x", the mandatory field is briefly in error state, because the focus did not change. 
Should I open a new issue for this? 
Otherwise the issue above has been successfully fixed.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have found another corner case for this issue - I will not open a new issue, since this is very similar to the existing issue. 
If user selects a entry in "Open Ports", "Port Forwarding" or "Masquerading", clicks on one of the mandatoy fields (just click, so the focus is on the field, presses ESC key on keyboard and after that again "Edit" in kura, the selected field is in error state. 
Can you please check this?

![234](https://user-images.githubusercontent.com/15121999/86001994-fcfdf900-ba0f-11ea-9e1f-7dd8ad985cb6.gif)

**Comment by pierantoniomerlino** [comment]
Ok. I reopen the issue to keep track of the new corner case.
@LeoNerdoG I confirm the issue.

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Yes, indeed the first issue is not solved, but IMHO is not so critical. I'll close this issue anyway. @MMaiero what do you think about that?

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG does the first issue happen only when the mandatory field is filled with a wrong value? I mean, if a wrong value is written, you can keep pressed the "x" button and see that the field is red. This because the focus is changed and the field is evaluated. But if the value is correct, I don't see the red highlight.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
if I see correctly, user first has to enter something into the mandatory field and then delete it. 
From this standpoint it is logical that the field is in error state for brief moment, but I suggest that if the focus changes to "X", that the fields do not get validated.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
