### ISSUE TITLE
Packages installed in kura disappear when reboot the Raspberry Pi after change CloudService Payload Encoding from Kura Protobuf to simple json

### ISSUE THREAD

**Issue by liucunjie** [eclipse/kura#2799]
**Describe the bug**
Packages installed in kura disappear when reboot the Raspberry Pi after change CloudService Payload Encoding from Kura Protobuf to simple json

**To Reproduce**
1. Go to 'Packages' and Install/Update modbus driver downloaded from Eclipse Marketplace
2. Go to  'Cloud Connections' and change CloudService Payload Encoding from Kura Protobuf to simple json,  Click on 'Apply'
3. Reboot the Raspberry Pi
4. Go to 'Packages' and the installed packages disappear

**Expected behavior**
N/A.

**Screenshots**
N/A.

**Target Environment (please complete the following information):**
Board [e.g. Raspberry Pi 3B+]
OS version: 2018-11-13-raspbian-stretch-lite
[Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
]
 - Additional info: 
Kura Version: KURA_4.2.0-SNAPSHOT

**Additional context**

**Comment by liucunjie** [comment]
The Installed Packages is in /tmp Directory? So the /tmp is cleaned when reboot, is it reason?

**Comment by MMaiero** [comment]
Hi, the package from the eclipse marketplace is kept in /tmp only during downloading. If the downloading succeeds and the package is correctly installed, it is then moved inside /opt/eclipse/kura that is in persistent storage.

I will check with my raspberry if the issue occurs to me.

**Comment by liucunjie** [comment]
Hi, MMaiero, thanks for your great job first, i reproduce the issure
1、I download the driver .dp file from eclipse marketplace first
2、Second, I install the .dp file use the Kura web
3、I reboot my raspberry, and the Packages in the list
4、I reboot my raspberry again, and the Packages disappear
What I miss something?

I found kura cp the .dp file into /opt/kura, but not .jar
and the .jar file is in the /tmp only

**Comment by MMaiero** [comment]
So, the dp is what matters. Once installed you should have it in /opt/eclipse/kura/data/packages/. You can also check the content of dpa.properties file:

```
pi@raspberrypi:~ $ cat /opt/eclipse/kura/data/dpa.properties
#Fri Apr 17 12:31:15 BST 2020
com.eurotech.modbus.driver=file\:/opt/eclipse/kura/data/packages/com.eurotech.modbus.driver_1.0.400.dp
```

This is the file that will be used by Kura at every framework reboot to know which packages need to be reinstalled.

The content of /tmp/kura is just a working directory.

**Comment by MMaiero** [comment]
I've just checked with my Pi with the following OS:
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
I've used the modbus driver bundle in the marketplace and tested installing it both loading from my system and also using the drag and drop. 
I've tested invoking a plain reboot command and a power cut off. In all the cases the bundle was there at reboot.

**Comment by liucunjie** [comment]
1、i install the .dp file,  the content of dpa.properties file is like yours, and the .dp file is also in the  /opt/eclipse/kura/data/packages/
2、when i reboot twice, the content of dpa.properties file is not changed,  but .dp file disappear in the  /opt/eclipse/kura/data/packages/

maybe i miss something, i will test carefully again, maybe something is wrong with my raspberry

**Comment by MMaiero** [comment]
You are correct: it gets loaded at first reboot but then is not there anymore.

I will check. But seems definitely a bug.

**Comment by MMaiero** [comment]
It seems that the issue is not there in the 4.1.x branch.

I will look in the 4.2.x commits to find where we broke things.

By the way, thank you for the feedback and for posting this!

**Comment by MMaiero** [comment]
@liucunjie a PR has been created.
Any feedback on that is more than welcome :-)
