### ISSUE TITLE
"401" Error When Sessions Ends

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2835]
If user reaches maximum time for the session and after that clicks something, Kura returns 401 error (see screenshot bellow). It is OK that Kura logs user out after time expires, but the error is not necessary here. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Web Console and set the "Session max inactivity interval" to "1". 
3. Logout and login again
4. Wait for a minute and then click anything in the UI
5. Observe the error. 

**Expected behavior**
If user reaches the max session time and gets logged out, Kura should not escort that with an error. 

**Screenshot:**
![Screenshot 2020-05-05 at 14 11 03](https://user-images.githubusercontent.com/15121999/81065516-eb9ae380-8edb-11ea-9ec1-33c25488df11.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG could you please take a look at the proposed solution?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
