### ISSUE TITLE
Undescriptive Generic Error if "Session max inactivity interval" Changed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2836]
If user changes "Session max inactivity interval" and applies changes, Kura returns undescriptive generic error (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Web Console service
3. Change "Session max inactivity interval" to "1" and apply changes
4. Observe the error thrown. 

**Expected behavior**
Kura should not throw generic error when logging out. 

**Screenshots**
![Screenshot 2020-05-05 at 14 11 03](https://user-images.githubusercontent.com/15121999/81064615-48959a00-8eda-11ea-90b8-fd82304c4509.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
I believe we can close this issue @LeoNerdoG: it is related to https://github.com/eclipse/kura/issues/2838 and for the Unauthorized message now it has been changed to a more descriptive message when the session ends.
What do you think?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
Yes, you are correct about the situation when the session expires, but the problem here is in the moment when user changes the max session interval parameter - in that case we get this unescriptive error that is shown above or rather this one: 

![Screenshot 2020-09-03 at 10 38 29](https://user-images.githubusercontent.com/15121999/92092987-11c18900-edd3-11ea-98a8-d388816f019d.png)

and this is the main reason I would keep this issue open. When fixing with PR, both issue can be fixed at once, #2838 an this one. What do you think?

**Comment by MMaiero** [comment]
I would keep only one issue. At least we don't have duplication that can be confusing.

The error you are seeing there is caused by the fact that after applying the config change the backend is restarted. So the front-end cannot interact and displays that error.

**Comment by LeoNerdoG** [comment]
Ok I am closing the issue due to upper comment.
