### ISSUE TITLE
404 Error When Changing Console Username And/or Password

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2838]
If user changes console username and/or password, Kura returns a 404 error, although nothing error prune happens. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Web Console service and change console username
3. Change console password also
4. Press "Apply"
5. Observe the 404 error

**Expected behavior**
If user changes console username and password, Kura should not throw an error (except if something actually causes error), but should only be logged out. 

**Screenshot:**
![Screenshot 2020-05-05 at 14 32 50](https://user-images.githubusercontent.com/15121999/81066731-db840380-8edd-11ea-8845-c8a82f3c6e24.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
That has already been observed and reported as an issue.
We have also a PR that solves this issue but we kept that on hold due to the fact that there will be an important refactoring in Kura 5 to support multi users

**Comment by mstankovic** [comment]
@MMaiero what's the status of this? Its blocking me while implementing new test cases for WebConsole service?
