### ISSUE TITLE
Port Forwarding Entries Not Properly Deleted

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2846]
If user has at least two entries in the Port Forwarding section of Firewall service, selects the second one, click on Delete and confirms, the entry is not deleted - it is still in the list (see the screenshots bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go Firewall -> Port Forwarding
3. Enter two different Ports to be forwarded
4. Apply changes
5. Select second one and click on Delete. Confirm the deletion
6. Observe the list (Screenshot No. 2)

**Expected behavior**
If user deletes an entry in port forwarding list, it should disappear from the list. 

**Screenshot No. 1:**
![Screenshot 2020-05-06 at 09 41 44](https://user-images.githubusercontent.com/15121999/81158621-733e2c00-8f88-11ea-8233-504c86131196.png)

**Screenshot No. 2:**
![Screenshot 2020-05-06 at 10 57 53](https://user-images.githubusercontent.com/15121999/81158627-7507ef80-8f88-11ea-98c8-8944e22c4cf8.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Same behavior in Ip Forwarding tab...

**Comment by LeoNerdoG** [comment]
hey @pierantoniomerlino,
I have checked this and it's still an issue (see GIF bellow) - latest build of kura develop has been used: [link to the newest kura build](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

I have followed the testflow above and I was able to reproduce it. 

![123](https://user-images.githubusercontent.com/15121999/82409689-92e85080-9a6e-11ea-8de3-2f26089ea592.gif)

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
