### ISSUE TITLE
"Require uppercase and lowercase characters in new passwords" Ignored When Updating Password

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2848]
If user sets "Require uppercase and lowercase characters in new passwords" to True, Kura ignores this setting when user is updating the console password. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to WebConsole Service and set "Require uppercase and lowercase characters in new passwords" to True
3. Apply changes
4. Try to update password so it doesn't contain upper and lower case characters
5. Apply changes
Kura does not return an error (ignore the "404" error)

**Expected behavior**
"Require uppercase and lowercase characters in new passwords" should not be ignored when updating password.

**Screenshot:**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
That field is for now only limited to the wifi password, as far as I know.

I would suggest for now, since the development is in progress to keep the UI tests on hold

**Comment by LeoNerdoG** [comment]
OK cool. I have noticed this and reported so we have this in the issue list.
