### ISSUE TITLE
Watchdog Syntax Errors

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2853]
There are some minor syntax errors in Watchdog service that should be fixed (ses creehsot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Watchdog Service and observe its descriptions
3. There are some syntax errors that need fixing

**Expected behavior**
/

**Screenshot:**
![Screenshot 2020-05-06 at 12 59 08](https://user-images.githubusercontent.com/15121999/81169665-7ee61e80-8f99-11ea-94ef-fd0288eca2f8.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Fixed by PR #2872

**Comment by LeoNerdoG** [comment]
Hey @MMaiero and @iacco,
I have to report that this issue has not been resolved. 
I have checked latest develop (build 1793 on https://ci.eclipse.org/kura/job/kura-develop/) and I have built develop branch on my machine and the result is the same, there are still the syntax errors as reported in the issue. 
Can you please check on your side if this works or not?

**Comment by MMaiero** [comment]
Have a look at #2947

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
