### ISSUE TITLE
"Internal port" And "External port" Defaultly Set to "0"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2855]
"Internal port" and "External port" properties are marked as mandatory when creating new port forward entry. However, if user does not populate them, the changes are saved nontheless (both ports have value "0", which is not ok, because this is not a valid port (see screenshot No. 1). 
If user wants to enter "0" into both ports, Kura marks fields as in error state, which is ok, but is not consistent - the fields should not be left empty nor should the accept ports <1 and >65535. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall ->  Port forwarding, click "New"
3 Enter "input interface", "output interface" and "LAN address" parameters
4. Do not enter "internal port" and "external port" parameters
5. Click Submit and then Apply

**Expected behavior**
The fields should not be left empty nor should the accept ports <1 and >65535. 

**Screenshot No.1:**
![Screenshot 2020-05-07 at 08 18 02](https://user-images.githubusercontent.com/15121999/81261254-0ab08700-903c-11ea-98e4-dc08f159e37d.png)

**Screenshot No. 2:**
![Screenshot 2020-05-07 at 08 23 09](https://user-images.githubusercontent.com/15121999/81261247-084e2d00-903c-11ea-9f18-24aa3a97c2d9.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
