### ISSUE TITLE
Default Title For Port Forwarding Entries That Are Being Edited

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2856]
If user decides to edit a port forwarding entry, the title is generic for all items in the list: "Update Port Forward Entry: 0". This should be changed. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> port forwading
3. Create new port forwarding entry
4. Click Submit and Apply
5. Select the newly created item and click Edit - observe the title

**Expected behavior**
The title should not be generic (in this case: "Update Port Forward Entry: 0")

**Screenshot:**
![Screenshot 2020-05-07 at 08 34 16](https://user-images.githubusercontent.com/15121999/81262298-db9b1500-903d-11ea-909a-b6d1da7240cb.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?
I have tested with latest develop and I don't see the issue.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
