### ISSUE TITLE
User Able to Submit Port Forward Entry With Just "Source port range"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2857]
User is able to submit a new port forward item jsut by entering the "Source Port Range" parameter (observe the screenshots bellow, follow the testflow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> port forwading
3. Create new port forwarding entry with only "Source port range" defined
4. Click Submit and Apply
Kura does not throw any error (ignore the generic error that shows no amtter what you do)

**Expected behavior**
Submitting a port forwarding entry should not be possible if mandatory fields are not set. 

**Screenshot:**
![Screenshot 2020-05-07 at 08 37 46](https://user-images.githubusercontent.com/15121999/81262405-1a30cf80-903e-11ea-98b5-b6f0e34c05ab.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
