### ISSUE TITLE
"Permitted MAC Address" Field Permanently in Error State

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2858]
If user enters an invalid MAC address into the "Permitted MAC address" in Firewall ->Port Forwarding  -> New, Kapua marsk the field in red, which is OK. But if user fixes the issue, the field stays in error state. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> port forwading
3. Go to "Permitted MAC address" field and enter "aa:bb:cc:dd:ee:ff:gg" MAC address (invalid address)
4. Delete the last two ("gg") and replace them with valid numbers (e.g "11")
5. Clicki Submit - nothing happens, the MAC field stays in error state

**Expected behavior**
When user fixes the MAC address problem, he should be able to able to submit changes. 

**Screenshot No. 1:**
![Screenshot 2020-05-07 at 08 48 59](https://user-images.githubusercontent.com/15121999/81263728-814f8380-9040-11ea-9e54-7e97bdb9bf1a.png)

**Screenshot No. 2:**
![Screenshot 2020-05-07 at 08 49 06](https://user-images.githubusercontent.com/15121999/81263725-801e5680-9040-11ea-8b25-8fa5823a02a7.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
