### ISSUE TITLE
User Able to Submit Port Forward Entry With Just One Mandatory Parameter

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2861]
This issue is basically the same as #2859, #2857, and #2860 but I am opening this just to have a clear thread for every issue reported. If fix will be provided for all of them at once, please reference them in the PR and then close them accordingly.
User is able to submit a new port forward item jsut by entering one of the mandatory paramters (only LAN address, or only Output interface, or only input interface or only Internal Port or only External Port). Observe the screenshots bellow, follow the testflow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> port forwading
3. Create new port forwarding entry with only one mandatory parameter set 
4. Click Submit and Apply
Kura does not throw any error (ignore the generic error that shows no amtter what you do)

**Expected behavior**
Submitting a port forwarding entry should not be possible if mandatory fields are not set. 

**Sample Screenshot:**
![issue2](https://user-images.githubusercontent.com/15121999/81288487-08aeee00-9065-11ea-80f9-e7224f0cc4f1.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved - user has to enter all the mandatory parameters in order to add a forwarded port.
