### ISSUE TITLE
User is unable to add IP forwarding Item to List

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2862]
I have encounter a problem in Firewall -> Ip forwarding/Masquerading. When I enter all the valid paramteres, click Submit and then Apply, I get a generic error and item is not added to the list (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> IP forwarding
3. Click "new" and add valid parameters to all the fields and click Submit
4. Click Apply and observe the error

**Expected behavior**
If user enters valid parameters into the IP forwarding dialogue box, there should be no errors. 

**Screenshot:**
<img width="801" alt="Screenshot 2020-05-07 at 13 20 04" src="https://user-images.githubusercontent.com/15121999/81289963-870c8f80-9067-11ea-89fe-fce20a9afcd9.png">

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is some error log visible in kura.log or Kura-console.log files?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
all I get is:
<img width="1275" alt="Screenshot 2020-05-07 at 13 51 33" src="https://user-images.githubusercontent.com/15121999/81291375-ef5c7080-9069-11ea-9290-e0391b80fe93.png">

**Comment by MMaiero** [comment]
Ok, it seems like there are new changes in the raspberry for iptables 
@pierantoniomerlino can that affect the 4.1.1?

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG @MMaiero I'm not able to reproduce this error neither with the 4.1.1 nor 4.2.0-SNAPSHOT.
Here is my configuration:
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT [Link to the last develop commit](https://github.com/eclipse/kura/commit/3c66c528070845edf4f928c873dc3e553e1a9371)

Which is your `iptables-restore` command version? Mine is `iptables-restore v1.8.2 (nf_tables)`

**Comment by LeoNerdoG** [comment]
Hi @pierantoniomerlino,
I finally figured out how to reproduce the issue. It is not solely up to IP Forwarding/Masquerading tab, but also "Port Forwarding".
Plase follow the testflow bellow and let me know if you were able to reproduce the issue. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Port Forwarding
3. Click on "New" and enter only "Source port range" (e.g. 1234)
4. Click Submit and Apply
5. Close the error thrown by Kura
6. Go to IP Forwarding/Masqeurading 
7. Click on "New", enter all the valid parameters
8. Click Submit and Apply, observe the error. 

It looks like that if the error from Port Forwarding section affects the IP Forwarding/Masquerading tab.

**Comment by MMaiero** [comment]
Is this error still there?

**Comment by LeoNerdoG** [comment]
I have checked this issue again and it seems to be resolved, I can add forwarded IP without a problem.
