### ISSUE TITLE
User Can Add Empty IP Forwarding/Masquerading Item

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2865]
If user does not enter any parameters into the input fields when creating new IP Forwarding/Masquerading, Kura reports an error when clicking Apply (nothing is thrown when Submit is clicked), but the item is added anyway (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall - > IP Forwarding/Masquerading
3. Click New, without entering any parameters click Submit
4. Click Apply, close the error and observe the item list

**Expected behavior**
If user does not enter mandatory parameters, "new" window should not close when Submit is pressed. 

**Screenshot:**
![Screenshot 2020-05-11 at 08 07 14](https://user-images.githubusercontent.com/15121999/81529111-6f325580-935e-11ea-95c6-ffc67e54e410.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
