### ISSUE TITLE
Duplicate Entries in IP Forwarding/Masquerading When Deleting an Entry

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2866]
If user has for example two entries in IP Forwarding/Masquerading and then deletes first one, the second one gets duplicated (see screenshots bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall - > IP Forwarding/Masquerading
3. Create a unique entry (enter only mandatory parameters
4. Create another unique entry, Submit and Apply changes
5. Select first entry in the list and delete it
6. Observe the situation (second entry is somehow duplicated)

**Expected behavior**
If user deletes an entry, ther should be no duplicates afterwards. 

**Screenshot No. 1:**
![Screenshot 2020-05-11 at 08 08 46](https://user-images.githubusercontent.com/15121999/81529288-db14be00-935e-11ea-944e-86d3bc01f587.png)

**Screenshot No. 2:**
![Screenshot 2020-05-11 at 08 08 53](https://user-images.githubusercontent.com/15121999/81529291-dd771800-935e-11ea-958e-558e16d8ed7d.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG could you please check if this issues is still present?

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have verified that this issue has been resolved.
