### ISSUE TITLE
Special Symbols in Network -> Wireless -> "Network Name" Not Parsed Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2868]
If user enters invalid special characters into Network -> Wireless -> Network Name, they are not parsed correctly (see screenshot bellow). This network is also not visible in the neetwork list when searching for it.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> Wireless -> Network Name 
3. Enter "!"#$%&'(){}~Ææ~¿ˇÈ" into Network name
4. Submit changes
5. Observe the result (in Network Name)
6. Try to find the network with e.g. mobile phoen - it cannot be found

**Expected behavior**
If user enters invalid symbols into the "Network name", the configuration should not be accepted. 

**Sceenshot:**
![Screenshot 2020-05-11 at 14 25 28](https://user-images.githubusercontent.com/15121999/81561295-45dfec80-9393-11ea-96b1-0902c0f87478.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by salvatore-coppola** [comment]
Added regex to validet SSID name.
Fixed.
