### ISSUE TITLE
"Wlan0" Still Visible in RPi Configuration, Although Disabled

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2869]
If user sets Wireless Status to "Disabled" it is still seen in the network list, if user executes command "ifconfig" on Raspberry. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> Wireless -> Network Name 
3. Set the Status to "Disabled"
4. SSH yourself to Raspberry and execute command "ifconfig"
5. Observe the list - wlan0 is there

**Expected behavior**
If user disables the Wlan0, it should not appear in the list, when executing "ifconfig" command on Raspberry. 

**Sceenshot:**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
That is an intended behaviour. Disabled for kura means that there is no address assigned and services to have the wifi as access point or station mode are not running.
This corresponds to a de-facto disabled interface.

**Comment by LeoNerdoG** [comment]
Hey @matteo,
I am closing this issue due to the upper comment.
