### ISSUE TITLE
Wired subscriber and logger

### ISSUE THREAD

**Issue by mordredz** [eclipse/kura#2871]
Hi, I'm building a system with this architecture: 

Client MQTT (Python Paho) --> Mosquitto --> Kura (Docker) --> View Payload in kura.log

For Kura's subscription to a Mosquitto topic I created the CloudService and the subscriber. The subscription and the creation of the topic were successful, as I receive messages correctly.

![screenshot](https://user-images.githubusercontent.com/52132942/81670829-79308300-9448-11ea-8328-0f50d8ce9643.png)

Subsequently in the wiregraph I used the subscriber block (in which I selected the subscription pid) and in the logger block I indicated the verbose option

![immagine](https://user-images.githubusercontent.com/52132942/81670929-a67d3100-9448-11ea-8de8-239dd287dec6.png)

The problem is that I keep getting only the information that I have received the message without viewing the message content.

Could anyone help me out please?

Thanks in advance.

Note: for the format of messages to be sent to kura I used the one indicated in the following link:
https://github.com/eclipse/kapua/wiki/K-Payload-JSON-Format in particular: Simple JSON Encoding

**Comment by MMaiero** [comment]
Hi, 
is it possible that the message content is in the body of the payload?
If that is true, the logger currently logs just the content of the metrics and not the content of the message body.

**Comment by MMaiero** [comment]
Hi @Salvocll any update on this?
Can the issue be closed?
