### ISSUE TITLE
"Passwords do not match" Error, Although WIfi Passwords Are Same

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2874]
If user deletes "Wireless Password" and "Verify Password" fields, and then enters "verify" before "wireless password", Kura returns an error, that passwords are not the same, although they are. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> wireless
3. Delete the "wireless password" and "verify password"
4. Enter new password in "verify password"
5. Enter the same password in "wireless password"
6. Observe the error

**Expected behavior**
If bothe passwords are the same, Kura should not report an error. 

**Screenshots**
![Screenshot 2020-05-18 at 09 34 16](https://user-images.githubusercontent.com/15121999/82187290-791f0000-98ec-11ea-9539-660fb4e43dac.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
This should be solved due to the recent changes made

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
