### ISSUE TITLE
Generic Error if User Applyes Changes Without Wifi Password

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2875]
If user tries to apply new changes without specifying password AND its "verification" part, Kura reports a generic undescriptive error (sees creenshot bellow). If user forgets to enter one of them, Kura returns a warning message

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> wireless
3. Delete the "wireless password" and "verify password"
4. Enter new password in "verify password"
5. Enter the same password in "wireless password"
6. Observe the error

**Expected behavior**
If both passwords are the same, Kura should not report an error. 

**Screenshots**
![Screenshot 2020-05-18 at 09 47 20](https://user-images.githubusercontent.com/15121999/82203796-133e7280-9904-11ea-92da-2002ab277ecb.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
I believe this should be solved now with the latest changes applied, right?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I am confirming that this issue has been resolved.
