### ISSUE TITLE
Generic Undescriptive Error When Network's Password Wrong

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2876]
When device is in station mode and you select an access point from the list, Kura reports and undescriptive generic error if the password is not correct (see the screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> wireless
3. Set the Wireless mode to "Station Mode"
4. Mistype the networks password
5. Click Apply

**Expected behavior**
Kura should report an error if user mustypes the access point's password, but the error should be handled more gracefully. 

**Screenshot:**
![Screenshot 2020-05-18 at 13 26 23](https://user-images.githubusercontent.com/15121999/82208077-2ef94700-990b-11ea-8796-dd6c95c2a21e.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
I'm not getting this error.
Are you sure that it is not related to the fact that the client part is not anymore able to connect to the Kura web server?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I checked this again and it seems that you are right. I am closing this, since the error message is fine in this case.
