### ISSUE TITLE
"Information" Section has Fixed Width

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2877]
If user narrows the browser window, the "Information" section in Network -> wlan0 -> Wireless does not shrink accordingly (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> wireless
3. Shrink the browser window and observe the "Information" section

**Expected behavior**
"Information" should be shrinked according to the browser width. 

**Screenshot:**
![Screenshot 2020-05-18 at 13 30 23](https://user-images.githubusercontent.com/15121999/82208547-0a519f00-990c-11ea-9547-2d8ee6ddd6a6.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by salvatore-coppola** [comment]
Fixed
