### ISSUE TITLE
"Information" Changes to "Help" When Narrowing Browser Window

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2878]
If user has a "full size" browser window, there is an "Information" section in Network (see screenshot bellow). But if user narrows the browser window, the "Information" section gets replaced with small "?", question mark icons, and when pressed a "help" section opens up. 
I suggetst that we change "Help" into "Information", because it is actual section with more information and not help directly.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> wireless
3. Observe the "information" section
4. Narrow the browser window so "?" replace the "information" section
5. Click on the "?" icon and observe the name of the window - it is "help" instead of "information"

**Expected behavior**
The name of the bottom section should be "Information" and not "help"

**Screenshot:**
![Screenshot 2020-05-18 at 13 17 12](https://user-images.githubusercontent.com/15121999/82212004-1e989a80-9912-11ea-9a71-100bf042bdee.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by salvatore-coppola** [comment]
Fixed
