### ISSUE TITLE
Menu on Left Disapperas at Certain Browser Size

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2879]
There is a certain point (size) of browser window when menu on the left is missing. I was able to recreate this issue several times and always the browser size was somewhere around 990 px (width) and 1000 pixels (heigth).

**Testflow:**
1. Login to Kura as admin/admin
2. When on home page, resize it to cca 990 x 1000 pixels
3. Observe the missing side bar on the left

**Expected behavior**
Sidebar should never go missing, regardless of the browser size. 

**Screenshot:**
![Screenshot 2020-05-19 at 08 51 12](https://user-images.githubusercontent.com/15121999/82294248-2148cd80-99ae-11ea-89c4-56b50cd65c6a.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
The side bar should be replaced by a menu that is made available by a "hamburger" button on the top left. It is not the case in your setup?
![Screenshot 2020-06-15 at 14 16 56](https://user-images.githubusercontent.com/10448126/84656454-fef59180-af12-11ea-8cce-f25833869bf9.png)

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
Yes, it is. But there is a certain point in browser's height and width, where this menu is not available any more. Beyond this point everything works fine again. So you have to find the "sweet spot" for this issue to manifest itself.
