### ISSUE TITLE
[Modbus] Implement the MBAP header for TCP/IP communication

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#288]
According to modbus.org, the MBAP header is required for TCP/IP communication, when sending a PDU. The MBAP header contains transmission ID, protocol identifier, length information and a unit identifier.
Without the header the slave device rejects the transmission when checking the header content. 
See: http://www.modbus.org/docs/Modbus_Messaging_Implementation_Guide_V1_0b.pdf

**Comment by cdealti** [comment]
Closed via #995
