### ISSUE TITLE
Duplicated Results of Available Networks Search

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2880]
If user presses "search" button in Network -> wlan0 -> Wireless (station mode) for searching the available networks, Kura reports all the available networks multiple times (see screenshot bellow - the network names have been erased on purpose).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless (station mode)
3. Click several times on "search" button for searching all the available networks
4. Observe the network list - it is repeated several times

**Expected behavior**
If user clicks seach button mutliple times, results should not be duplicated. 

**Screenshot:**
![Screenshot 2020-05-19 at 09 42 51](https://user-images.githubusercontent.com/15121999/82301033-f5324a00-99b7-11ea-94d2-e98bda77f1c9.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 4th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb))

**Comment by MMaiero** [comment]
I couldn't recreate the issue.
Can you double check with develop if this is still the case?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this on latest develop and the issue persists. I am attachin a GIF bellow to show you the problem "in action". 

![123](https://user-images.githubusercontent.com/15121999/84742141-57c73780-afb0-11ea-9ed2-84d12ec5a371.gif)

**Comment by MMaiero** [comment]
ok, now is more clear. Thanks

**Comment by salvatore-coppola** [comment]
Fixed, the list is cleared befor it is loaded in the grid.
