### ISSUE TITLE
Undescriptive Error Message For Wireless Password

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2883]
If user sets access point password that is too weak, Kura reports an error: "Password must be 5, 13 ASCII characters, or 10, 26 HEX characters", which is not very user friendly. 
Can it be something like: "Password must be at least 8 characters long and must contain at least one lower case letter, one upper case letter, a number and a special symbol."?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Set "Access Point" as Wireless Mode
4. Set the Network Name (unique) and set Wireless Security to WEP
5. Enter a very weak password (e.g. "123123123")
6. Observe the error 

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-05-20 at 08 55 43](https://user-images.githubusercontent.com/15121999/82414849-f3c85680-9a77-11ea-99fa-d99725e8b96c.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by salvatore-coppola** [comment]
Added a better errore message.
Fixed
