### ISSUE TITLE
Why Two Columns For Same Parameter (Channel Frequency)?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2885]
If you navigate to Network -> wlan0 -> Wireless and observe the "Available Channels" table, there are two basically the same columns (Frequency (MHz)), one is slightly more accurate then the other. My question here is if we can ditch the rigth one, as the left column is much more precise and we get no additional data out of right one? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Observe the "Frequenecy" table bellow, there are two slmost identiacal columns

**Expected behavior**
Should there be two identical columns for same thing (wlan frequency)?

**Screenshot:**
![Screenshot 2020-05-19 at 11 26 37](https://user-images.githubusercontent.com/15121999/82412368-d2656b80-9a73-11ea-8dd3-ef040a2ac0f7.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by sterwen** [comment]
The management of WiFi channels needs anyway an overhaul. My proposal would be a least to replace the second column header by 'band' instead of frequency. The first column shall be 'central frequency' anyway.

**Comment by salvatore-coppola** [comment]
The table is not present anymore.
Won't fix.
