### ISSUE TITLE
"Wireless Password" Stays in Error State

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2886]
If user adds a bad WEP password, then changes Wireless mode from Access Point to Station Mode and back, the Wireless Password field is still in the error state, if WEP is selected. On the GIF bellow there is only the second part shown. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Select Station Mode, and WEP for Wireless Security
4. Enter a invalid WEP password
5. Change mode to Station Mode and then back to Access Point
6. Go to Wireless Security and select WEP - observe the error from before

**Expected behavior**
If user changes view, the password fields should be returned to default values? 

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/82417539-faf16380-9a7b-11ea-88ce-600f3cbaf6d5.gif)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Hi @LeoNerdoG,
not sure about this. What are you suggesting here? To keep the inserted password?

Matteo

**Comment by LeoNerdoG** [comment]
Hey @matteo,
basically if user selects "None" from Wireless Security, all the fields should be "reset" or cleared of their error message. I guess the password entry stays there if user changes wireless security from none to something else but I suggest that the fields get reset to some default values, because it is not logical for user to see the error, if the password has not been entered yet.

**Comment by MMaiero** [comment]
Is this issue still there after the changes made?

**Comment by LeoNerdoG** [comment]
Yes, the issue persists.

**Comment by MMaiero** [comment]
Having another look, the field is reported in any case as erroneous when you select the WEP because the actual field is not a string allowed by WEP.
I believe there is little we can do there.

Also, the switch between wireless modalities causes the reloading of the current defaults. That is the reason why if you set a WEP compatible key and then switch, the password is not kept in any case.

**Comment by salvatore-coppola** [comment]
Since the last version the password is resetted with a placeholder after the change of the wireless mode..
Won't fix.
