### ISSUE TITLE
"Status" Fields in Network -> wlan0 Should be Renamed to "Mode"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2892]
There are several mode options for wlan0 for end-user to choose from. The problem is that this field is named "status", which is not entirely correct. I suggest that this gets renamed to "Mode", becasue user is actually selecting the mode for this wlan and not setting its status (status should be "enabled/disabled", but we have other options too, so word "Mode" is more appropriate for this field) - what do you think? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> TCP/IP
3. Observe the "Status" field - it should actually be named "Mode"

**Expected behavior**
"Status" field should actually be named "Mode", because we are not only choosing between "on/off" but there are plenty of other options too. 

**Screenshot:**
![Screenshot 2020-05-21 at 08 35 13](https://user-images.githubusercontent.com/15121999/82530837-77e51180-9b3e-11ea-86ce-6fa086936c3d.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
@pierantoniomerlino @nicolatimeus What do you think?

**Comment by sterwen** [comment]
I agree, from a pure semantic point of view, 'status' is not something you set but something you read. So 'Mode' is a better wording.

**Comment by MMaiero** [comment]
The real problem in this is that, for uniformity, we should change also the name used to persist the property in the snapshot (i.e. net.interface.lo.config.ip4.status) to something like: net.interface.lo.config.ip4.mode. But this is a breaking change we need to take care of. I would not directly and only go for a label change in UI because then it will generate confusion to users when they have to deal with the snapshot.

**Comment by salvatore-coppola** [comment]
@MMaiero what about this ? Do we let the name as is now and close the issue ?

**Comment by salvatore-coppola** [comment]
For now the field mainteins its current name.
Won't fix.
