### ISSUE TITLE
Only "Station Mode" Available When Wlan0 Status set to "Enabled for WAN"?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2893]
If user sets the status of the wireless interface to "Enabled for LAN", then there are all options available in "wireless" tab (Station Mode and AP mode). But if user changes the status to "Enabled for WAN", the Wireless Mode status is automatically set to "Station Mode" - is this correct behaviour?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> TCP/IP
3. Set the status to "Enabled for WAN"
4. Go to Wireless tab - observe the disabled "Wireless Mode" field

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-05-21 at 08 44 14](https://user-images.githubusercontent.com/15121999/82531248-43be2080-9b3f-11ea-94cd-c3a9f67c4080.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Yes, when wan is selected, the only way to reach internet for the gateway is if it is connected as a client in an existing network.

**Comment by LeoNerdoG** [comment]
I am closing this issue due to the upper comment.
