### ISSUE TITLE
Strange Error in Network Service When Web Session Ends

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2894]
If you reach the "Session max inactivity interval", which is set in WebConsole -> "Session max inactivity interval" and try to click e.g. Apply button in Newtork -> wlan0 -> Wireless, Kura reports a 401 error, stating: "NetwokButtonBarUI: 401 Unauthorized". 
Can we make this error message a little more user friendly? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to WebService -> "Session max inactivity interval" and set it to 1 minute
3. Go to Network -> wlan0 -> Wireless and wait for 1 minute
4. After one minute press Apply - observe the error 

**Expected behavior**
The error shown should be more user friendly. 

**Screenshot:**
![Screenshot 2020-05-22 at 07 47 56](https://user-images.githubusercontent.com/15121999/82635509-a3c8cb80-9c00-11ea-8f53-e645120670d4.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
But the user actually is not authorised to perform actions since the session ended. Anyways, I will try to have a look if it's possible to improve the message or the change will affect other interactions

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked this again and the error now is: 
![Screenshot 2020-09-01 at 09 04 49](https://user-images.githubusercontent.com/15121999/91812985-3df1d400-ec32-11ea-8961-7498afd6a1ba.png)

which is OK from my standpoint so i am closing this issue. If you think that this should be upgraded, please feel free to reopen the issue.
