### ISSUE TITLE
Wrong Description in Network (regarding DHCP & NAT)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2896]
If you read the information text in Network (see screenshot bellow), there is clearly stated that: "DHCP Server and NAT can be configured only for interfaces enabled for LAN usage."
This is not true, because if user sets a particular interface to "Enabled for LAN", the DHCP & NAT option is disabled (Screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0/eth0
3. Set the desired interface to "Enabled for LAN"
4. Observe the "DHCP & NAT" tab - it is disabled 

**Expected behavior**
According to the description, DHCP & NAT tab should be enabled it user sets particular network interface to "Enabled for LAN"

**Screenshot:**
![Screenshot 2020-05-21 at 08 50 37](https://user-images.githubusercontent.com/15121999/82639171-80098380-9c08-11ea-897c-f1a98d4ac053.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by LeoNerdoG** [comment]
@MMaiero I have an update for this issue - DHCP & NAT tab gets enabled if Status is set to "Enabled for LAN" and Configure to "Manually" (if set to "DHCP", the tab is disabled) - is this the desired behaviour?

**Comment by MMaiero** [comment]
Yes. Once you are in DHCP client you cannot set DHCP and NAT acting as a server

**Comment by LeoNerdoG** [comment]
Ok. I think this can be closed then, because I thought that if you set "Enabled for LAN" this option gets automatically enabled. The description is OK I guess.
