### ISSUE TITLE
No Error When Trying To Apply Network Settings Without Specifying Channel (wifi)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2900]
If you try to apply changes without specifying the channel for wireless network, Kura returns no errors, but instead seelcts channel-1 (it looks like that this is the default channel, although this is not stated anywhere). 
Is this the desired behaviour? Is suggest that we change this so that Kura checks if a channel is selected or we ada  text to the description of the field (e.g. "If you don't select a channel, Kura will select the default channel, which is channel-1").

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Deselect the one channel that is selected on the bottom and try to apply changes
4. Observe the lack of info message from Kura - check the Channel table -> channel-1 is selected. 

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-05-25 at 10 43 55](https://user-images.githubusercontent.com/15121999/82805611-96bc0e80-9e84-11ea-81bd-44fb0b651e98.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Hi @LeoNerdoG,
right. But if you apply such configuration and reload the page, actually channel 1 is selected.
Anyways, I get your point, a check before applying is needed. But I see this as a p2 issue.

**Comment by salvatore-coppola** [comment]
The wireless table in not present anymore.
Won't fix.
