### ISSUE TITLE
Password Field Stays in Error State When Changing From WEP to WPA/WPA2

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2904]
If user first select WPA/WPA2 from Wireless Security Menu, deletes password, selects WEP and then again WPA/WPA2, the error message "Password must be 5, 13 ASCII characters, or 10, 26 HEX characters" stays in place, which is not OK, because this error message should be associate with WEP wireless security and not WPA/WPA2. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Select Access Point Mode
4. Set the Wireless Security to WPA/WPA2
5. Delete the "Password" entry, then delete "Confirm Password" entry
6. Select "WEP" from Wireless Security Menu
7. Delete both password fields 
8. Select WPA/WPA2 again from Wireless Security menu
Observe the error "Password must be 5, 13 ASCII characters, or 10, 26 HEX characters" which is not correct if Wireless Security set to WPA/WPA2.

**Expected behavior**
If user changes the wireless security paramter, the errors should disappear (regardless of the switch; from WEP to WPA or some other switch).

**Screenshot:**
![Screenshot 2020-05-27 at 08 18 04](https://user-images.githubusercontent.com/15121999/82985572-8aef5a00-9ff4-11ea-9db4-e019edc5a596.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
@LeoNerdoG I was unable to recreate the issue. In any case I believe this is also fixed by the currently proposed PRs for the wireless part of the UI

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I will check and let you know here.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have checked PR #2925 and it fixes this issue. 
After the mentioned PR is merged, we can close this issue.
