### ISSUE TITLE
HTTP Service Not Working Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2907]
If user sets "HTTP Enabled" to "True", the service is not available (for HTTPS it works). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to HTTPService 
3. Set HTTP Service to "True" (leave the port number at 80)
4. Try to connect to  [kura-ip]:[80]. - the connection cannot be established

**Expected behavior**
If user enables the HTTP Service, Kura should be accessible on the [kura-ip]:[port].

**Screenshot:**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Hi @LeoNerdoG,
did you open the port 80 in the firewall configuration?

**Comment by LeoNerdoG** [comment]
hey @MMaiero,
yes, that was the problem. I suggest that we add a note above the field or maybe a tooltip saying: "Please ensure that this port is properly liste in Firewall" or something similar. 
This way users will not forget about opening the port in Firewall which obviosluy happens very quickly 😄
