### ISSUE TITLE
Should HTTP and HTTPS be Mutualy Exclusive? 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2908]
For now, user can switch both services, HTTP and HTTPS off, so effectivelly Kura is not accessible - at all. Should these two options be mutually exclusive, so user does not "lock himself out"? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to HTTPService 
3. Set HTTP Service to "False"
4. Set the HTTPS Service to "False"
5. Try to acces Kura through UI - that is not possible

**Expected behavior**
I suggest that HTTP and HTTPS's settings are mutually exclusive (both cannot be turned off). 

**Screenshot:**
/

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
In theory, the user can also enable both and maybe associate that with a firewall policy to restrict accesses.
The other way around, the user can decide to disable UI access disabling both services and, maybe, enable them when needed from the cloud platform.

**Comment by pintify** [comment]
But it would be interesting the option to force the UI through command line on boot, for example. This would avoid the "lock himself out" situation that @LeoNerdoG describes in case cloud platform connection fails or even is not even configured (both for error or lack of interest in the platform).

**Comment by salvatore-coppola** [comment]
User could choose to disable all http connectors and we have to keep the possibility to do that.
We have added a warning if there are no ports defined for any connectors.
