### ISSUE TITLE
WiFi Channels 12-14 not usable in AP mode

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#2913]
**Describe the bug**
When the max WiFi channel is set to 14, channels 12-14 cannot be used in access point mode.
The table with the possible channels has always 11 rows.

In station mode, it possible to connect to access point using channels 12-14.

**To Reproduce**
1. Go to Network/wlan0/wireless
2. Click on Wireless => Access point
3. Scroll down to "Channels"
4. No channels 12,13,14 available

**Expected behavior**
There should be 3 additional rows for the 12, 13, 14

**Target Environment (please complete the following information):**
 - Board I.MX6
 - OS version: Debian 
 - Additional info: Kura 4.0.0

**Additional context**

**Comment by MMaiero** [comment]
From what I see testing on a sample device and looking at the code, channels 12 and 13 are supported.

![Screenshot 2020-06-03 at 14 29 04](https://user-images.githubusercontent.com/10448126/83636738-bf3fb900-a5a6-11ea-81f0-ff40e2ae126e.png)

I don't think I have a device supporting channel 14. It seems anyway not supported by our current UI.
