### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by tmontanaro** [eclipse/kura#2921]
Hello, I'm approaching Kura in the last days as an iPOJO user who is looking for a consolidated infrastructure to enhance the developments of his team in IoT domain ... and I'm a little confused by the documentation.
I will report here the questions to which I cannot answer hoping that someone can help me in finding related answers.
What I understood is that Kura creates a sort of abstraction layer among IoT devices and services that consume incoming data. So it tries to simplify the process of "standardizing" the format of data coming from IoT devices to share them through common interfaces like REST APIs or MQTT.
The "Wires" components and the provided Web Interface should help such interactions through a GUI.
Now, hoping that I actually understood the role of Kura, I cannot find answers to the following questions:
1. Where can I find detailed documentation about each existing plugin? e.g. I tried to create an MQTT subscriber connected (through Wires) to an MQTT publisher and I took 2 days to understand that data are published on topic "Topic Context Account-Name"/"Client-id"/"Application Id"/"Application Topic".
2. Where can I find information about the development of a new bundle that publishes data to be managed through Wires?
3. Where can I find information about the development of a new bundle that consumes data to be managed through Wires?
4. Is there any SDK or similar environment (with related documentation) to develop bundles/applications/... run on Kura?
5. Apart from the possibility to set configuration parameters through the web interface, is there any way to also set them through files (e.g., Felix usually supports .conf files saved in a specific folder)
6. Is there any way to use iPOJO bundles over Kura?
7. I see that developers are working at version 5.0.0, where can I find more information about possible release date? Will the new version be better documented?

I would like to thank in advance all the people who will help me. ;-)

**Comment by MMaiero** [comment]
Hi @tmontanaro,
first of all welcome to the project!

Regarding your questions:
1. Most of the components are described in the [official Kura documentation](http://eclipse.github.io/kura/). Regarding the Wires Components there is a specific section in the documentation with usage examples.
2. and 3. what you mean with "publishes data"? Publishes through MQTT? Or published a Kura Envelope through wires? Or other?
4. Have a look here: http://eclipse.github.io/kura/dev/kura-setup.html
5. Kura stores its components configuration in snapshots files that are stored in /opt/eclipse/kura/user/snapshots/. Snapshot files are encrypted after the first boot. Kura has also a generic configuration file to provide configuration parameters to the framework. The file is available here: /opt/eclipse/kura/framework/kura.properties
6. Never tried that, sorry.
7. The features are usually discussed and documented as Github issues. When a feature targets a release is usually associated to a project like here: https://github.com/eclipse/kura/projects/4

Hope this helps. 
Best regards,
Matteo

**Comment by tmontanaro** [comment]
Hello @MMaiero and thank you very much for your fast reply.
I will try to answer to your further questions following the same question numbers used in my previous post.

1. Ok. I will try to read everything again, however I have to say that I already tried to read it and sometimes the reported information are not enough to let a novice person understand how to do things (when and if I will be able to understand how everything works I would be glad to contribute to enhance the documentation if you like it).
2. Your questions are directly connected to what I've just said in the previous point. Actually I don't know what an envelope is. I only know that the MQTT subscriber is able to "push data" on something (maybe the Event Admin) and then, through wires, we are able to push that data on another component (like the MQTT publisher). I would like to understand what the "something" is so that I can implement new components that pushes data on that "thing" to let them interact with other (maybe existing) components.
3. My question n. 3 may be more clear now. I already set Eclipse, Kura etc but I don't know what is in the middle that let every component communicate through wires. Is it the OSGi Event Admin?
And it is connected to my question n.4.
(YOUR 4). Ok, thanks
(YOUR 5). Ok, I will let you know if I will be able to do it
(YOUR 6). Ok, thanks

**Comment by MMaiero** [comment]
Hi @tmontanaro,
regarding 1, I would also suggest to reach out the Kura team via the [Eclipse Kura forum](https://www.eclipse.org/forums/index.php/f/273/), the [mailing list](https://accounts.eclipse.org/mailing-list/kura-dev), or even better via [Gitter](https://gitter.im/eclipse/kura). Any contribution to the documentation or the project in general is more than welcome!

The typical usage of a subscriber is in association with a MQTT Cloud connection: the subscriber listens to a specific topic to receive messages that can then be used as feed to start the wires processing. It's what we called an emitter component. A Wires MQTT publisher does the opposite: is a terminal component or receiver only that receives the wires messages (or envelopes) and publishes them to the related cloud connection at the specified MQTT topic. But we can have a separate discussion, if you want, going into the details of your scenario and trying to design the flow.

Kura wires rely on top of OSGi Wire Service. When constructing a wire component you don't have to deal with the low level specificities: just simply implement the needed interfaces (you can find in the code many examples of other wire components) and start developing from there.

Best regards,
Matteo
