### ISSUE TITLE
Firewall | Port Forwarding | Internal port field validation 

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2927]
**Describe the bug**
User is able to add string "80:82" as a internal port for port forwarding item
field is not marked as invalid and submit button not responding  

**To Reproduce**
1. Go to Firewall 
2. Click on Port Forwarding tab
3. Click on new button 
4. for Internal port add "80:82"

**Expected behavior**
Field should be marker as invalid

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3

**Comment by MMaiero** [comment]
This is not anymore possible due to the fixed applied to the firewall section of the UI.

**Comment by LeoNerdoG** [comment]
Hey @mstankovic,
I have checekd this and it looks like it has been fixed with PR #2915 - please check on your side (with latest develop branch) and close it if it is fixed
