### ISSUE TITLE
Firewall | Port Forwarding | Able to add Forwarded Port although didn't fulfill mandatory fields

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2928]
**Describe the bug**
Some of fields in the "Port Forward Entry Information" dialog are marked as mandatory but user is able to add entry without fulfilling those fields 

**To Reproduce**
1. Go to Firewall
2. Click on Port Forwarding tab
3. Click on +new
4. Click on submit 

**Expected behavior**
A mandatory fields should get "invalid" and user should not be able to submit without fulfilling those fields 

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3

**Comment by MMaiero** [comment]
This should be fixed with the latest changes made in the firewall section of the UI.

**Comment by LeoNerdoG** [comment]
Hey @mstankovic,
I have checekd this and it looks like it has been fixed with PR #2915 - please check on your side (with latest develop branch) and close it if it is fixed.

**Comment by mstankovic** [comment]
confirming - this is fixed. Closing.
