### ISSUE TITLE
Installing Package for Kura 3.x.y on Kura 4.x.y

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2929]
I have noticed that user is able to install packages that are meant for kura 3.x.y. on Kura 4.x.y without an error - is this desired behaviour or not? I would say not, since there are two different versions of packages, one for each version?

**Testflow:**
1. Login to Kura as admin/admin
2.  Go to Packages, try to install a kura 3.x.y package on kura 4.1.1
3. There is no error, package gets installed without an error

**Expected behavior**
is this allowed - to be able to install package for Kura 3.x.y on kura 4.x.y?

**Screenshots**
/

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 10th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
They can install it, but it will not start.
Unfortunately that is a limitation of the eclipse marketplace that we reported a long time ago.

**Comment by zhanghenglang** [comment]
How to solve this kind of problem? I installed de.dentrassi.camel.utgard-0.2.0 on kura4.1.2, but it cannot be used .

**Comment by MMaiero** [comment]
You need a release of the package for Kura 4
