### ISSUE TITLE
No Error When Adding Forwarding Port Without Populating Mandatory Fields

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2930]
User is able to add forwarded port without specifying any of the paramters. Kura reports nothing when "Apply" is clicked and when "Submit" is clicked, Kura reports an error, but nothing happens (if you discard changes, the entry is still there). 
Moreover, if you enter invalid forwarded port and then try to open a port in "Open Ports" tab (which has nothing to do with port forwarding), you loose all the open ports (Open port list disappears - issue #2931).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Port Forwarding, try to forward a port without specifying a thing
3. Click Apply and Submit
4. Observe the error when you click Apply
5. Navigate away from this tab, discard changes and then return - the invalid entry is still there

**Expected behavior**
If user does not specify mandatory parameters, Kura should not let him submit the parameters.

**Screenshots**
![Screenshot 2020-06-11 at 14 34 02](https://user-images.githubusercontent.com/15121999/84387027-a6f91b00-abf2-11ea-8c40-f54243e1e252.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 10th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
This is not possible anymore with the latest changes made in the Firewall section of the UI

**Comment by LeoNerdoG** [comment]
Hey @MMaiero, I am confirming that this has been resolved with PR #2915. Closing.
