### ISSUE TITLE
Open Ports Disappear if Error in IP Forwarding

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2931]
If user enters invalid port forwarding information (see issue #2930), "Open Ports" disapper (after user wants to add a valid open port entry) - screenshot bellow. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Port Forwarding, try to forward a port without specifying a thing
3. Click Apply and Submit
4. Observe the error when you click Apply
5. Navigate away from this tab, discard changes and then return - the invalid entry is still there
6. Go to Open ports, try to add a valid port, click Submit and Apply - observe how Open ports list disappears

**Expected behavior**
Open Porst list should not disappear if user enters invalid information into IP forwarding tab. 

**Screenshots**
![Screenshot 2020-06-11 at 14 58 58](https://user-images.githubusercontent.com/15121999/84387971-18859900-abf4-11ea-8e80-84c162e8a393.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 10th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
I believe this is not replicable now with the latest changes applied and due to the fact that now the precondition to this issue cannot be met.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero, I am confirming that this has been resolved with PR #2915. Closing.
