### ISSUE TITLE
Unable to execute reboot command over REST API

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2932]
**Describe the bug**
REST API call for executing (reboot) command is not working.  

**To Reproduce**
1. Go to Command Service and set Command Enable to true
2. Connect Kura to Cloud 
3. Try to execute reboot command over REST API
- Method type: 
`POST`
- Method URL: 
`https://api-sandbox.everyware-cloud.com/v2/devices/{KURA_CLIENT_ID}/command.xml`
- Method body: 
```
<?xml version='1.0'?>
<commandInput xmlns='http://eurotech.com/esf/2.0'><command>reboot</command><workingDir>/tmp</workingDir><runAsync>true</runAsync></commandInput>
```

**Expected behavior**
Command should be executed

**Target Environment:**
 - Board Raspberry Pi3
 - OS version: latest raspbian 
 - Additional info: KURA_4.2.0-SNAPSHOT
 - EC v4

**Comment by MMaiero** [comment]
Hi,
do other commands work?
If you try to execute the same command locally or via EC console, do they succeed?
Any meaningful error in the logs?

**Comment by MMaiero** [comment]
Just tried with Kura develop locally and from console and it works for me on both a generic command and on reboot.
@mstankovic Can you check on your environment?

**Comment by mstankovic** [comment]
@MMaiero im able to execute commands via EC console for rapsberry pi connacted to the cloud but for 10-12 im getting error. see below
![Capture](https://user-images.githubusercontent.com/3385815/84494897-8db3a580-acaa-11ea-9943-507eefc79a48.PNG)

also able locally for kura and RPi. For 10-12 I will tell you a bit latter as son as I get into Comtrade

do you use the same url I provided in the description above?

**Comment by MMaiero** [comment]
That message is because the gateway rebooted immediately not providing feedback. It's just a corner case.

I've not tried with rest apis but in theory they follow, device side, the same path as commands pushed via console.
So, device side everything seems to be working as expected, I would say

**Comment by mstankovic** [comment]
confirming that this is not an issue. Im closing this one.
