### ISSUE TITLE
No Check if Open Ports Have Mutual Excluding Parameters

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2935]
User can add two different open ports that have mutual excluding paramters (e.g. one's permitted interface name is eth0 and other's unpermitted interface name is eth0 - this means, that the created two ports (same port) is virtually unusable). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Open Ports
3. Add a port with following parameters:
 - Port or port range: 10
 - Protocol: TCP
 - Permitted Interface: eth0
4. Add a port with following paramaeters:
 - Port or port range: 10
 - Protocol: TCP
 - Unpermitted Interface: eth0
There is no warning from Kura regarding this and if there are a lot of ports (e.g. 100+) it is very hard for user to spot this problem (or even think about it).

**Expected behavior**
Should Kura provide an insight into the open port configuration when creating (opening) new port?

**Screenshots**
![Screenshot 2020-06-12 at 13 22 32](https://user-images.githubusercontent.com/15121999/84498471-00c01a80-acb1-11ea-8bc4a7ea0e2b8e68.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 10th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by JCodyA** [comment]
Hello!  I'd love to contribute and this looks like a reasonable place to start but I'm a bit new to this.  I'll have a look at the code and return with questions more than likely.

**Comment by MMaiero** [comment]
Hi @JCodyA,
thanks! It would be a great first contribution to the project!
For any help needed, we are here.
Best regards,
Matteo

**Comment by marcellorinaldo** [comment]
@MMaiero solved.
