### ISSUE TITLE
Drag and drop of deployment packages

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2940]
Currently the drag-and-drop feature for installing deployment packages is limited to the Eclipse marketplace. So, only a link to the marketplace is allowed in to the packages tab.

IMHO, a useful feature could be the upload of .dp files from the local filesystem with drag-and-drop.

**Comment by LeoNerdoG** [comment]
Hey all,
I have checked this and now user gets an error message when trying to install multiple packages at once. 
All other cases are also okay.
