### ISSUE TITLE
Confirm Password Field in Error State Without Description

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2945]
If user deletes the Password content, the "Confirm Password" is in error state, but there is no description of what is wrong (although it is obvious, there should be an error message, description). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless 
3. Select Access Point mode and enter a valid Password, confirm it in Confirm Password
4. Now clear the Password field and keep it empty
5. Observe the Confirm Passwowrd field

**Expected behavior:**
Everytime Kura reports an error/warning (especially if a field is in error state), there should be a description of what is wrong. 

**Screenshot:**
![Screenshot 2020-06-15 at 13 28 48](https://user-images.githubusercontent.com/15121999/84652656-4167a000-af0c-11ea-9bbd-bf0e5b422761.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 15th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Using the latest develop I get this:
![Screenshot 2020-06-17 at 10 40 19](https://user-images.githubusercontent.com/10448126/84875983-fcb44400-b086-11ea-9318-8201587b22e6.png)

**Comment by LeoNerdoG** [comment]
hey @MMaiero,
I know what is the problem. If you delete the Password (Confirm Password stays intact) and focus does not change from Password to somewhere else, there is no error message, just Confirm Password is in error state. But if the focus changes, then error message appears. 
Is this the desired behaviour or should error message be displayed immediatelly aftre the validation is done between the fields?

**Comment by MMaiero** [comment]
I've seen that. But I believe it's just cosmetic at that point. What do you think?

**Comment by LeoNerdoG** [comment]
Maybe, but I just discovered another thing (it is best described through a testflow):

1. Enter password into Password field (e.g. 123123123)
2. Enter the same password in Confirm Password 
3. click outside both boxes (so focus changes)
4. Add one character/number in Password field (e.g. 3)
5. Change focus to "Confirm Password" and then back to "Password" (so error message appears on Confirm Password)
6. Delete the lastly added characater in "Password" field - observe the error message that stays above "Confirm password" field until you change focus

![123](https://user-images.githubusercontent.com/15121999/84894071-891f3080-b0a0-11ea-8762-80f7b58822fe.gif)

I would leave this issue open, becasue there should be a consistency in error messaging. it is not critical, so we can fix this later, but I would fix it eventually.

**Comment by salvatore-coppola** [comment]
Fixed.
Added validation on keyup and blur events.

**Comment by MMaiero** [comment]
I can still confirm this issue. The verification works but the "Passwords do not match" still stays there until you change focus.

**Comment by salvatore-coppola** [comment]
I have added a password check also on keyupevent for the verify password field.
