### ISSUE TITLE
Firewall | Port Forwarding | Able to add duplicated items

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2948]
**Describe the bug**
User is able to add duplicated items - port forwarding rules 

**To Reproduce**
1. Go to firewall service
2. Click on port forwarding tab
3. Fill all fields and click on submit
4. Click on New and type the same parameters for new item and click on submit button

**Expected behavior**
User should not be able to add the same rule twice 

**Screenshots**
![dupli](https://user-images.githubusercontent.com/3385815/84772793-be157f80-afdb-11ea-8c19-c9b2da76f44d.PNG)

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest Raspbian 
 - Additional info: Kura 4.2.0-SNAPSHOT

**Comment by pierantoniomerlino** [comment]
@mstankovic Could you please try with the last develop build? I think that some improvements were introduced with the last PR about firewall.

**Comment by MMaiero** [comment]
I believe I've tried that and was able to recreate the issue

**Comment by pierantoniomerlino** [comment]
@MMaiero @mstankovic I confirm the issue :-((((

**Comment by pierantoniomerlino** [comment]
@MMaiero @mstankovic It seems that the issue is caused by the Integer objects comparison. Replace  the `==` with `equals` method fixes the problem.

**Comment by pierantoniomerlino** [comment]
This opens to another thought: which fields are required to set an entry as duplicate? Currently, in openPorts are all the fields, while in Port/IPForwarding are all the fields except `masquerading`. It makes sense? If we consider all the fields, the code is very simple, since we don't need to compare each field separately...

**Comment by MMaiero** [comment]
Can we have a PR that can help us to determine the corner cases?
