### ISSUE TITLE
Special Symbols in "Network Name" Not Properly Parsed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2949]
User is able to enter various special symbols into "Network Name", which (after clicking on Apply) produces unrecogizable symbols (see screenshot bellow). Moreover, if user clicks Apply several times, the number of symbols increase, because unrecognizable symbols get "described" with more unrecognizable symbols. 
The problem here is that the symbols are not properly parsed (they are allowed but should not be used). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> Wireless
3. Set the "Wireless Mode" to "Access Point"
4. Enter symbols into "Network Name" field (e.g. ""#$%&'()@‹›€ı–")
5. Press Apply and observe the result.

**Expected behavior**
Special symbols should be allowed in "Network Name" field, but should be properly parsed. 

**Screenshot:**
![Screenshot 2020-06-17 at 09 08 25](https://user-images.githubusercontent.com/15121999/84867580-ae4d7800-b07b-11ea-8fcb-f319a63c1d2b.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 16th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment]
Is that issue specific for the network part or applicable, for example, for services?

**Comment by LeoNerdoG** [comment]
I will check and let you know.

**Comment by MMaiero** [comment]
By the way, isn't this a duplicate of #2868?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
yes, you are right. Closing as duplicate.
