### ISSUE TITLE
"Cloud Services" Parameters Not Properly Parsed on "Status" Tab

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2953]
If user enters long item name (account name, broker URL, username, or Client ID), the name is not parsed well. 
If there are no spaces or symbols in the string (e.g. "/", "-", "_", etc.) everything is in one line (Screenshot No. 1), otherwise everything is in multiple lines (Screenshot No. 2). 
Also if user enters some specific symbols into the fields, they are not parsed properly - the fields are empty (Screenshot No. 3).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to CloudService and change the parameters of the default CloudService 
3. Go to About page and observe the CloudService parameters - they are not changed

**Expected behavior**
If user changes some parameters on the CloudService, this should be reflected on About page. 

**Screenshot No. 1:**
![Screenshot 2020-06-18 at 10 14 15](https://user-images.githubusercontent.com/15121999/84998119-b4ad2400-b14f-11ea-95d8-0fea1d5eb8f8.png)

**Screenshot No. 2:**
![Screenshot 2020-06-17 at 14 30 55](https://user-images.githubusercontent.com/15121999/84998173-c8f12100-b14f-11ea-8994-638a8840a0bc.png)

**Screenshot No. 3:**
![Screenshot 2020-06-18 at 15 23 47](https://user-images.githubusercontent.com/15121999/85025932-521c4e00-b178-11ea-83fb-1c05e42f1dc9.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from June 16th, 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by salvatore-coppola** [comment]
One line visualization in device status has been fixed.
Adding a validator to connection field will be considered.
