### ISSUE TITLE
[Web UI] Status | Connection: if the connection username is not set, "null" is shown

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#296]
If the username is not set (left blank) in the MqttDataTransport, it is shown as "null" in the Connection Status page of the Web UI.

This was found in an 2.0.0 SNAPSHOT so it might have already been fixed.

**Comment by pierrepitiot** [comment]
The bug is still present. Null is returned by org.eclipse.paho.client.mqttv3.MqttConnectOptions.getUserName().
