### ISSUE TITLE
Refactor UI fields check

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#2961]
**Is your feature request related to a problem? Please describe.**
Extend the feeds verification through all the UI

**Describe the solution you'd like**
Currently an extensive verification, meta type driven, is only performed at the level of the service configuration. All the classes and interfaces there are private and cannot be reused in other parts of the UI.
The verification framework should be extracted and made available to the other parts of the UI to improve, for example, the checks in the Network section.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MMaiero** [comment]
E.g. #2955

**Comment by nicolatimeus** [comment]
Something similar has been done as part of #2912 , but maybe it requires a couple more tweaks

**Comment by MMaiero** [comment]
@nicolatimeus that's great. Let's try to finalise the PR and let's see if we can extend those features through all the UI
