### ISSUE TITLE
IP Forwarding/Masquerading -> Error dialog is missing when adding duplicated item

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2981]
**Describe the bug**
When Im trying to add duplicated item (with same input/output ports) nothing happens. item is not added and error dialog in not shown. This can is a bit confusing for user.

**To Reproduce**
1. Go to Firewall section -> Ip Forwarding tab
2. Click on New button and add rule with input/output ports (eth1, eth2)
3. Submit
4. Apply - optional step
5. Click on New button again
6. try to add the same rule (with same input/output ports - eth1, eth2)
7. click on Submit button

**Expected behavior**
Error dialog should appear saying that user is about to add duplicated rule.

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest raspbian
 - Additional info: Kura 4.2.0-snapshot

**Comment by LeoNerdoG** [comment]
I am confirming this - I tried on my device with latest develop and was able to reproduce it.
