### ISSUE TITLE
Asset channels cannot be removed from Wire composer

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#2985]
**To Reproduce**
1. Create an Asset with some channels defined
2. Open the Wire Composer and delete at least one channel from the Asset
3. Save the graph
4. Reload the web ui

**Expected behavior**
The channels deleted at step 2. are non longer present

**Actual behavior**
The channels are still present

**Target Environment (please complete the following information):**
Kura develop branch

**Comment by LeoNerdoG** [comment]
I was able to reproduce the issue, confirming.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
