### ISSUE TITLE
Camel Factory cloud connection | Service PID field validation

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2989]
**Describe the bug**
Currently this (Camel Factory) cloud connection type doesn't have proper Service PID field validation. Currently able to add values: 
- CamelFactory
- org.eclipse.kura.cloud.CloudService
- org.eclipse.kura.cloudconnection.eclipseiot.mqtt.ConnectionManager
as a Service PID. This should not be possible. 

**To Reproduce**
1. Go to Cloud Connection system item
2. Click on New to add new CC
3. Choose Camel Factory for Factory PID
4. Type "org.eclipse.kura.cloudconnection.eclipseiot.mqtt.ConnectionManager" for Service PID and click on Apply button

**Expected behavior**
Validation error should appear!

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest Raspbian

**Comment by salvatore-coppola** [comment]
Added regex expression to validate Camel Service PID. Fixed
