### ISSUE TITLE
WiFi channels selection improvement

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#2990]
**Is your feature request related to a problem? Please describe.**
Currently, the WiFi channel selection is hard coded in the user interface package with 11 channels in the 2.4GHz band. This is not taking into account the countries that can allow channels 12 to 14, not the capabilities of the WiFi adapters. This is not allowing either the use of 5GHz channels (#2914). Automatic channel selection (#2547 ) shall also be possible.

**Describe the solution you'd like**
The channel selection user interface must be revamped:
1- Selection via pull-down list rather than check box. The choice shall corresponds to the available channels
2- A first level of selection shall be the bands if dual band is available. Another possibility being to use WiFi mode (b/g/n => 2.4, ac =5)
3- Automatic selection can be added as a choice. In that case we shall have 2 new pull down menus with min and max channels.

All WiFi configuration shall come from 'iw', this shall work on most of Linux machines. Maybe there will be a need of emulation for other platforms.

**Comment by MMaiero** [comment]
Hi,
for channels 12 to 14 I believe there was already an issue opened https://github.com/eclipse/kura/issues/2913 with a PR that went upstream to better manage channel 14 https://github.com/eclipse/kura/pull/2916

For 5ghz there is already an issue opened: https://github.com/eclipse/kura/issues/2914

Isn't this a duplicate?

**Comment by sterwen** [comment]
It is not a duplicate even if there are some overlap. The proposal is to restructure the user interface to cope with dual bands and more WiFi features like mesh networks in future improvements.
I agree that the #2914 could be merged with this one.

**Comment by MMaiero** [comment]
Closing as solved in 5.0.0
