### ISSUE TITLE
Quectel EG-25 context command is wrong

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#2992]
**Describe the bug**
The chat script generated by Kura for the Quectel EG-25 is wrong. The result is:

```
ABORT	"BUSY"
ABORT	"VOICE"
ABORT	"NO CARRIER"
ABORT	"NO DIALTONE"
ABORT	"NO DIAL TONE"
ABORT	"ERROR"
""	\rAT
TIMEOUT	1
"OK-+++\c-OK"	ATH0
TIMEOUT	45
OK	at+cgdcont
=1,"IP","web.omnitel.it"
OK	"\d\d\d"
""	"atd*99***1#"
CONNECT	"\c"
```

Please note that the **at+cgdcont** command is splitted in to two rows.

**Expected behavior**
The **at+cgdcont** command has to be set on a single line.

**Comment by MMaiero** [comment]
I believe this also needs to be back-ported, right?
