### ISSUE TITLE
[Network] dhcpd not restarted when switching from WAN to LAN/DHCP Server mode

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#300]
On ESF first start, eth0 and wlan0 are configured as dhcp+nat mode, and dhcpd and named services are running.
If the dhcp/nat mode is disabled on the 2 interfaces (eg disabling wlan0 and configuring eth0 as WAN/DHCP client), it is never restored when switching back to LAN/DHCP+NAT server mode. dhcpd and named are never restarted even after rebooting the system.

**Comment by cdealti** [comment]
@pierrepitiot Please try to recreate.

**Comment by pierrepitiot** [comment]
I tried several times to reproduce the sequence that gave me the issue but never had the issue again.
I think this problem is a side effect occurring randomly in a very special config, I don’t think we should spend more time on it. Do we need to keep the issue open in case someone encounters it again ? (personaly I don't think so)

**Comment by cdealti** [comment]
Closing because it cannot be recreated.
