### ISSUE TITLE
Kura Reports "Duplicate Entry" if Space Last Character in Port Number (Firewall)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3000]
This issue consists of two parts (there are two scenarios).
Sceanario/Issue 1: 
If user enters a space character after the port number in Firewall -> Open Ports -> New (e.g. "123 "), Kura reports "duplicate entry" error, although the port entered is unique. What makes things worse, this does not happen always (at least on my side this was somehow random...).

Scenario/Issue 2: 
If user enters "198237912873912739127391739172389723" into "Port or Port Range" field, Kura returns "duplicate entry error", which is not correct, validation should fail on field itself and Kura reporting "max value is 65535". 

**Testflow for scenario 1:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Open Ports -> New
3. Enter a unique parameter into "Port or Port Range" with a space characetr in the end (e.g. "123 ")
4. Press Submit and observe the error. If it does not show immediatelly, try couple of times

**Expected behavio for Scenario 1:**
There should be a validation for this case. 

**Testflow for scenario 2:**
1. Login to Kura as admin/admin
2. Go to Firewall -> Open Ports -> New
3. Enter 198237912873912739127391739172389723 into "Port or Port Range" field
4. Press Submit and observe the error. 

**Expected behavio for Scenario 2:**
See above.

**Screenshots (for both scenarios):**
![Screenshot 2020-07-29 at 07 55 19](https://user-images.githubusercontent.com/15121999/88765306-925aed00-d176-11ea-911d-5437b753ca37.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (July 27th, 2020)

**Comment by pierantoniomerlino** [comment]
Both issues are caused by the failing conversion of the ports value to Integers. The first scenario can be avoided trimming the values passed in the "ports range" field.

**Comment by pierantoniomerlino** [comment]
For the second scenario we need an exception management during values conversion.

**Comment by mstankovic** [comment]
covered both scenarios in automated tests

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
