### ISSUE TITLE
Generic Error if Subscriber or Publisher Selected in Wire Graph

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3004]
If user selects Publisher/Subscriber from Wire Components list and puts it in the Wire graph, an error appears when user clicks on the component and trying to change its parameters (see screenshot bellow).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to WireGraph, add Publisher/Subscriber to the Wire Graph
3. Select the newly create Publisher/Subscriber and observe the error. 

**Expected behavior**
No error should be displayed if user clicks on a component in Wire Graph. 

**Screenshot:**
![Screenshot 2020-07-29 at 13 23 32](https://user-images.githubusercontent.com/15121999/88794392-b5999280-d19e-11ea-8f60-9740d8e464c6.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (July 27th, 2020)

**Comment by pierantoniomerlino** [comment]
@LeoNerdoG Hi, I can't reproduce the issue... could you please check it again with the last develop build? Or provide us more details? Thanks!

**Comment by MMaiero** [comment]
I have tested this before holidays and was happening also to me. Now testing with develop, the problem seems solved.

**Comment by LeoNerdoG** [comment]
Hey @pierantoniomerlino,
I have checked this in latest develop and as Matteo said - it seems resolved. I am closing this.
