### ISSUE TITLE
Kura Gets Stuck in Loading View if Services Clicked Too Fast

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3005]
If user very fast clicks same service multiple times or if he circles through them very fast, the view gets stuck in loading screen and sometimes does not recover even after two minutes. 
I don't think is a critical issue, but it can be confusing for end user if this happens, because it seems that Kura is doing something when it really isn't. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Any of the services and start clicking its name on the menu on the left (e.g. Packages)
3. Observe how Kura gets stuck in "loading view" - it can last up to a minute or two untill Kura wakes up again

**Expected behavior**
Kura should not get stuck in "circling cog" view. 

**Screenshots**
![Screenshot 2020-07-29 at 13 26 30](https://user-images.githubusercontent.com/15121999/88794684-20e36480-d19f-11ea-864d-69975c28faed.png)

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (July 27th, 2020)

**Comment by MMaiero** [comment]
Is this still an issue?

**Comment by LeoNerdoG** [comment]
Will check and let you know.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero, this is still an issue.
