### ISSUE TITLE
Kura Ignores CSV if Contains More Than 1k+ Channels in Asset

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3006]
If user uploads an asset that has a lot of channels (I tried with more than 1k), Kura simply ignores it, without showing any kind of errors. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Packages and install Dummy wire development package
3. Go to Wire Graph and create a wireAsset (create a driver and an asset)
4. Upload a CSV file that has more than 1k channels - observe the behaviour

**Expected behavior**
Kura should not ignore uploaded CSV file - there should be some kind of info or error message. 

**Screenshots**
/
**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (July 27th, 2020)

**Comment by nicolatimeus** [comment]
Hi @LeoNerdoG, I tried to reproduce the reported behaviour.
I tested with the current develop branch (2/9/2020) with Chrome 84.0.4147.135 on OSX.
I tried uploading a CSV file containing 9999 channels to a `DummyDriver` Asset both in the Drivers and Assets and the Wires sections, I created the csv with the following script:

```bash
#!/bin/bash

echo "enabled,name,type,value.type,listen,value"

I=1

while [ ${I} != ${1} ]
do
  echo "true,Channel-${I},READ,INTEGER,false,0"
  I=$((I + 1))
done
```

Uploading the snapshot took some time but eventually succeeded. I noticed that during this process the progress wheel is not shown all time, this seems a bug to me and should be fixed. This behaviour might cause the user to think that nothing is happening.
I've also been able to apply the resulting configuration and perform a read using the Drivers and Assets web ui. Both operations took some time but eventually succeeded.
Having an Asset with this number of channels defined makes some Web Ui operations quite slow (for example loading the Wire Graph or the Drivers and Assets section).

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
thanks for the comment. I will recreate the issue with newest versions of kura and web browser. I will let you know how it goes.

**Comment by LeoNerdoG** [comment]
hey @nicolatimeus,
thanks for the script you provided, it helped a lot. 
I was able to reproduce the behaviour you described. Kura does not ignore the assets that are being uploaded, but it can get extremely slow (for example I tried to upload 12k channels in Wires and got error - see bellow), sometimes gets stuck, sometimes it takes a long time and nothing happens...so the behaviour is really not consistent. 
Do you think that there should be an upper limit for the assets being uploade and then concentrate to make system responsive for those extreme numbers (for e.g. 10k assets)?

![Screenshot 2020-09-03 at 11 40 16](https://user-images.githubusercontent.com/15121999/92099269-9a8ff300-edda-11ea-9b63-85890b402f14.png)

If you need any more help from me, just let me know. But I think that we should really discuss corner case/upper limits here, otherwise we will loose a lot of time fixing something that is hard to fix.

**Comment by MMaiero** [comment]
How is the CPU and ram usage? Maybe a lot changes with a more powerful device.

**Comment by MMaiero** [comment]
In any case 12k channels are **a lot**
