### ISSUE TITLE
Issue while accessing properties in gatt characterstics

### ISSUE THREAD

**Issue by VarshneyNaupada** [eclipse/kura#3017]
Hi Team, 
I have followed tinyB and example documentation to implement BLE devices. 
I am able to get UUIDs for Services and GATT Characterstics., but unable to get the service name , GATT characteristic names and also Characteristic properties( Read/write..) 

Kindly provide me some example codes to get these names and properties.

**Comment by pierantoniomerlino** [comment]
Hi @VarshneyNaupad,
the Kura Bluetooth and TinyB APIs don't expose a method for retrieving the service or characteristic names, since this property is vendor specific.
I can suggest to get the (optional) descriptors of the services/characteristics and see if these information are contained there. Regarding the characteristic properties, you can use the `getProperties` method that returns a List of `BluetoothLeGattCharacteristicProperties`.

**Comment by VarshneyNaupada** [comment]
Hi @pierantoniomerlino ,

I understand your point on Service or Characteristic names. 
 As you have mentioned this "  Regarding the characteristic properties, you can use the getProperties method that returns a List of BluetoothLeGattCharacteristicProperties  "

I have tested similar way to get let me share my code snippet used and also error which i am receiving 

List < BluetoothLeGattCharacteristicProperties > bleGattCharPropertiesList = bleGattChar.getProperties();
	for(BluetoothLeGattCharacteristicProperties bleGattCharProp : bleGattCharPropertiesList) {
		logger.info("Inside for - get prop Name: " + bleGattCharProp.name());
}

I am receiving below error at line 

List < BluetoothLeGattCharacteristicProperties >  bleGattCharPropertiesList =  bleGattChar.getProperties();

Error : 
java.lang.IllegalArgumentException: No enum constant org.eclipse.kura.bluetooth.le.BluetoothLeGattCharacteristicProperties.notify
        at java.lang.Enum.valueOf(Enum.java:238)
        at org.eclipse.kura.bluetooth.le.BluetoothLeGattCharacteristicProperties.valueOf(BluetoothLeGattCharacteristicProperties.java:1)
        at org.eclipse.kura.internal.ble.BluetoothLeGattCharacteristicImpl.getProperties(BluetoothLeGattCharacteristicImpl.java:134)

**Comment by pierantoniomerlino** [comment]
@VarshneyNaupada Mhh.... it smells of a bug. IMHO, there is an issue related to the capitalization of the items in the enum.

**Comment by VarshneyNaupada** [comment]
Hi  @pierantoniomerlino

Could you please let me know, what is our next step to resolve it.
