### ISSUE TITLE
KuraException with some KuraErrorCode are not printed properly.

### ISSUE THREAD

**Issue by chris-gcn** [eclipse/kura#3021]
Hi Kura Team,

**Describe the bug**
While trying to log some `KuraException`, a simple `System.out.println` or a logging of that exception are failing to retrieve the associated message:

`
WARN  o.e.k.KuraException - Could not load Exception Messages Bundle for Locale en_US
org.eclipse.kura.KuraException: Generic Error - INVALID_PARAMETER: {1}
	at org.eclipse.kura.core.configuration.ConfigurationServiceImpl.createFactoryConfiguration(ConfigurationServiceImpl.java:409)
...
`

The error code here is `INVALID_PARAMETER`.

After investigation, it seams that properties into `KuraExceptionMessagesBundle.properties` from bundle `org.eclipse.kura.api` are not in line with the enums defined into `enum KuraErrorCode` of that same bundle.

**Expected behavior**
log a pre-defined error message despite the "GenericError"'s one.

**Target Environment :**
 - KuraEmulator (for now)

Thank you all for your work!

**Comment by MMaiero** [comment]
Following the list of misaligned elements that needs to be fixed:

```
SERIAL_PORT_INVALID_CONFIGURATION,
SERIAL_PORT_NOT_EXISTING,
DECODER_ERROR,
OPERATION_NOT_SUPPORTED,
INVALID_PARAMETER,
BLE_REMOVE_ERROR,
BAD_REQUEST,
NOT_FOUND,
SERVICE_UNAVAILABLE,
DISCONNECTION_FAILED;
```
