### ISSUE TITLE
1Wire Communication(dsb18b20 sensor) with GPIO 

### ISSUE THREAD

**Issue by VarshneyNaupada** [eclipse/kura#3028]
Hi Team,

I am able to control LED with GPIO Driver and Asset. I tried similar way to get data from temperature sensor which is dsb18b20.
As it uses 1-wire Communication, I am unable to get any data.

Kindly help me by providing the approach to get data as well as some code spinets.

**Comment by pierantoniomerlino** [comment]
Hi @VarshneyNaupada,

the GPIO Driver can be used to simply read a GPIO value. It doesn't implement any kind of protocol such as 1-Wire.
So, if you want to decode the protocol and get the value, you'd develop a custom Driver that do the job.
You can use the GPIO Driver as a reference.

**Comment by VarshneyNaupada** [comment]
Hi @pierantoniomerlino ,

Thank you , I will look into it. I have tried using python script.. it actually reads from default pin (GPIO4), So for custom driver I need to include GPIO code also to read , guide me if i am going in other way round.

Also, would like to know , if we have any Drivers for Camera which Kura supports ?

Thanks Again :)

**Comment by MMaiero** [comment]
Hi @VarshneyNaupada,
no, we currently don't have drivers for cameras.

In any case, if you are planning to implement one, please consider contributing back to the project and community.

Best regards,
Matteo

**Comment by MMaiero** [comment]
Closing for now. If you have any update, please feel free to reopen it
