### ISSUE TITLE
Support of WPA-EAP authentication method in WiFi Station mode

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#3035]
**Is your feature request related to a problem? Please describe.**
Support of WPA-EAP authentication method in WiFi Station mode

**Describe the solution you'd like**
Change the UI to add 4 fields when the WPA-EAP method is selected.
Make the corresponding change in the code that generates the wpa-supplicant file

**Describe alternatives you've considered**
Modifying the wpa-supplicant file outside of Kura and triggering a Kura restart.

**Additional context**
This Feature request is part of a set that aims to improve/bring new features in WiFi management
#2990 #2914 #2547 
Our goal will be to have a single pull request for all WiFi related issues.

**Comment by MMaiero** [comment]
@sterwen Was this added by your contribution to the wifi section?
