### ISSUE TITLE
Same Port for HTTP and HTTPS Stop Kura Entirely

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3045]
If user sets HTTP's  service port to 443 (the same port as HTTPS service), Kura stops responding. user has to manually change settings in firewall on the device itself or reinstall Kura. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to HTTP Service and set HTTP's port to 443 (the same port as for HTTPS Service).
3. After several minutes try to refresh page - nothing happens, Kura does not start.

**Expected behavior**
Setting the same port number to HTTP and HTTPS should not be possible. 

**Screenshots**
/

**Target Environment:**
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: latest develop branch (August 25th, 2020)

**Comment by MMaiero** [comment]
We cannot currently address that due to OSGi meta type limitations

**Comment by MMaiero** [comment]
Closing for now
