### ISSUE TITLE
DEPLOY-V2 documentation incorrect

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#306]
After testing out this feature I found a few behaviours which do not match the documentation at https://eclipse.github.io/kura/ref/mqtt-namespace.html#deploy-v2

1. "job.id" is missing.
2. "dp.download.protocol" should not say "default HTTP" this suggests it is not mandatory. Maybe "e.g. 'HTTP'" would be better, or make it default/non-mandatory in the implementation.
4. "dp.install.system.update" should state "mandatory", or default to "false" in the implementation.

**Comment by pstanton** [comment]
in addition, the dpName and dpVersion should definitely be split and sent in different metrics to match the input parameters, as considered in the comment in the below snippet:

```
	public void installCompleteAsync(DeploymentPackageOptions options, String dpName) throws KuraException{
		KuraInstallPayload notify = new KuraInstallPayload(options.getClientId());
		notify.setTimestamp(new Date());
		notify.setInstallStatus(INSTALL_STATUS.COMPLETED.getStatusString());
		notify.setJobId(options.getJobId());
		notify.setDpName(dpName); //Probably split dpName and dpVersion?
		notify.setInstallProgress(PROGRESS_COMPLETE);

		callback.publishMessage(options, notify, RESOURCE_INSTALL);
	}
```

**Comment by dwoodard1** [comment]
@pstanton The requested changes have been made: http://eclipse.github.io/kura/ref/mqtt-namespace.html . Let me know if you see any errors.

**Comment by pstanton** [comment]
great, thanks david
