### ISSUE TITLE
Unable to deselect cloud connection item

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3062]
**Describe the bug**
User is not able to deselect cloud connection item holding CTRL key 

**To Reproduce**
1. Go to Cloud Connection service -> First item (if exist) is already selected
2. Hold CTRL key and click on selected item in order to deselect it 

**Expected behavior**
Should be able to deselect item so we can verify button statuses when there is nothing selected 

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: latest raspbian

**Comment by MMaiero** [comment]
Didn't we apply a fix to prevent this?
I believe there was a PR not long ago where we changed how the selection works in the cloud connection view

**Comment by LeoNerdoG** [comment]
I believe this has been fixed in PR #2976, wihich fixed issue #2686. @MMaiero, if this is not an actual issue or is desired behaviour, please close it.

**Comment by mstankovic** [comment]
@MMaiero if this is not an issue I need to update automated test case. Please let me know

**Comment by MMaiero** [comment]
I don't think that there is a real need to support cloud service deselection. I would not invest on that.

**Comment by mstankovic** [comment]
ok, thank you. I will close this issue and modify test case.
