### ISSUE TITLE
Configuring ethernet interface for LAN might cause failure in networking.service

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#3074]
**Describe the bug**

Configuring an ethernet interface for LAN in DHCP mode causes the following section to be added to /etc/network/interfaces:

```
auto eth0
iface eth0 inet dhcp
        post-up route del default dev eth0
```

The `post-up route del default dev eth0` line seem to cause issues when ethernet cable is not connected.
The `ifup eth0` command will fail causing the failure of the `networking.service` unit.
The following error message can be noted in the output of the `ifup -v eth0` command.

```
route del default dev eth0
SIOCDELRT: No such process
```

If the Ethernet cable is connected and the gw is able to set up a route from DHCP, the route will be removed and `ifup` will succeed.

**To Reproduce**
* Configure `eth0` for LAN in DHCP mode
* Do not connect network cable
* Observe failure in `ifup eth0`

**Expected behavior**
Configuring a network interface for LAN in DHCP mode should not cause failures in `networking.service`.

**Screenshots**

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3] rpi3, possibly others 
 - OS version: [e.g. provide the result of `uname -a`] Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
 - Additional info: 

**Additional context**

**Comment by MMaiero** [comment]
I believe we need some updates to the install scripts associated to this PR

**Comment by pierantoniomerlino** [comment]
@MMaiero Yes, we'd to update the interfaces file.
