### ISSUE TITLE
Add a BLE example for advertising as an Eddystone (Google) beacon

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#308]
It would be nice to be able to have a Kura gateway behave as an Eddystone beacon, e.g broadcasting it's admin URL. See: 
- https://github.com/google/eddystone/blob/master/protocol-specification.md
- hcitool command example: https://hackaday.io/project/10314-raspberry-pi-3-as-an-eddystone-url-beacon

**Comment by MMaiero** [comment]
@pierantoniomerlino Do we have something for this?

**Comment by pierantoniomerlino** [comment]
@MMaiero We have the API to run a custom hcitool command, so we can develop a example bundle to do that.

**Comment by pierantoniomerlino** [comment]
The #1528 added also support for Eddystones.

**Comment by Amar82** [comment]
I deployed the eddy stone package in my Kura 3.1.0 installed in RPi3.
package location: https://marketplace.eclipse.org/content/eddystone-advertiser-eclipse-kura

While the Eddystone URL is working fine, the UID part is not working. Google Beacon Tools is not able to detect the beacon. I guess the beacon is not working when in  UID option.

parameters: 
Minimum time interval between beacons (milliseconds) : 1000
Max Interval :1000
Tx Power: 16 dbm
Namespace: 6ffecdfec9b34b8064af
instance: 18df68aa4ee4

adapter : hci0

PLease help me on this.

regards
Amar

**Comment by pierantoniomerlino** [comment]
Hi,

I tested your parameters with the Kura Eddystone advertiser example and it seems to work.
I configured the bundle and scanned for Eddystones both with Google Beacon Tools and nRF Connect apps.

You could take a look on the kura.log and kura-console.log files to check if there are some exceptions or errors.

Best,
Pier

**Comment by Amar82** [comment]
Hi Pier,

I redeployed the bundle, all seems fine , but cant see in the Eddystone UID, in  Google Beacon Tools or Beacon Scanner. I have deployed the kura_3.1.0_raspberry-pi-2-3_installer.deb in my Raspberry pi 3 B+. (  am I using wrong package ? )

can u please take a look at logs, I couldn't fine any error in them:

OSGI Console details - =======
**74	Active		org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser**			org.eclipse.kura.example.eddystone.advertiser(bid=133)
osgi> xomp 74
gogo: CommandNotFoundException: Command not found: xomp
osgi> comp 74
	Component[
	name = org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser
	activate = activate
	deactivate = deactivate
	modified = updated
	configuration-policy = require
	factory = null
	autoenable = true
	immediate = true
	implementation = org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser
	**state = Unsatisfied**
	properties = {service.pid=org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser}
	serviceFactory = false
	serviceInterface = [org.eclipse.kura.configuration.ConfigurableComponent]
	references = {
		Reference[name = BluetoothLeService, interface = org.eclipse.kura.bluetooth.le.BluetoothLeService, policy = static, cardinality = 1..1, target = null, bind = setBluetoothLeService, unbind = unsetBluetoothLeService]
		Reference[name = BluetoothLeEddystoneService, interface = org.eclipse.kura.ble.eddystone.BluetoothLeEddystoneService, policy = static, cardinality = 1..1, target = null, bind = setBluetoothLeEddystoneService, unbind = unsetBluetoothLeEddystoneService]
	}
	located in bundle = org.eclipse.kura.example.eddystone.advertiser_1.0.0 [133]
]
Dynamic information :
  **The component is satisfied
  All component references are satisfied**
  Component configurations :
    Configuration properties:
      eddystone.url = https://www.facebook.com/
      component.name = org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser
      objectClass = String[org.eclipse.kura.configuration.ConfigurableComponent]
      tx.power = 16
      eddystone.uid.namespace = 6ffecdfec9b34b8064af
      eddystone.uid.instance = 18df68aa4ee4
      kura.service.pid = org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser
      service.pid = org.eclipse.kura.example.eddystone.advertiser.EddystoneAdvertiser
      min.beacon.interval = 1000
      component.id = 54
      enable.advertising = true
      max.beacon.interval = 1000
      eddystone.type = UID
      iname = hci0
    Instances:
      org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@14ec757
    	Bound References:
        String[org.eclipse.kura.ble.eddystone.BluetoothLeEddystoneService]
      		-> org.eclipse.kura.internal.ble.eddystone.BluetoothLeEddystoneServiceImpl@10a0906
        String[org.eclipse.kura.bluetooth.le.BluetoothLeService]
      		-> org.eclipse.kura.internal.ble.BluetoothLeServiceImpl@588db9

osgi> 

========
Kura.log  details -
2017-10-24 08:06:22,855 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.e.e.a.EddystoneAdvertiser - Updating Bluetooth Eddystone example...
2017-10-24 08:06:22,856 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.b.b.BluetoothLeBeaconManagerImpl - Stop Advertising on interface hci0
2017-10-24 08:06:22,863 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.e.e.a.EddystoneAdvertiser - Bluetooth adapter interface => hci0
2017-10-24 08:06:22,864 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.e.e.a.EddystoneAdvertiser - Bluetooth adapter address => B8:27:EB:F8:97:5C
2017-10-24 08:06:22,868 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.b.b.BluetoothLeBeaconManagerImpl - Set Advertising Data on interface hci0
2017-10-24 08:06:22,871 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.b.b.BluetoothLeBeaconManagerImpl - Set Advertising Parameters on interface hci0
2017-10-24 08:06:22,875 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.b.b.BluetoothLeBeaconManagerImpl - Start Advertising on interface hci0
2017-10-24 08:06:22,913 [qtp8374076-74] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1508814382851.xml...
2017-10-24 08:06:22,


=====
Kura-Console.log:  ( I think no problems in Kura console )

!ENTRY org.eclipse.equinox.ds 1 0 2017-10-24 07:24:52.389
!MESSAGE Could not bind a reference of component org.eclipse.kura.core.configuration.CloudConfigurationHandler. The reference is: Reference[name = CloudService, interface = org.eclipse.kura.cloud.CloudService, policy = dynamic, cardinality = 0..1, target = (kura.service.pid=org.eclipse.kura.cloud.CloudService), bind = setCloudService, unbind = unsetCloudService]

!ENTRY org.eclipse.equinox.ds 1 0 2017-10-24 07:24:53.365
!MESSAGE Could not bind a reference of component org.eclipse.kura.core.deployment.hook.DeploymentHookManager. The reference is: Reference[name = DeploymentHook, interface = org.eclipse.kura.deployment.hook.DeploymentHook, policy = dynamic, cardinality = 0..n, target = null, bind = bindHook, unbind = unbindHook]

!ENTRY org.eclipse.equinox.ds 1 0 2017-10-24 07:25:01.041
!MESSAGE Could not bind a reference of component org.eclipse.kura.net.admin.NetworkConfigurationService. The reference is: Reference[name = ModemManagerService, interface = org.eclipse.kura.net.admin.modem.ModemManagerService, policy = dynamic, cardinality = 0..1, target = null, bind = setModemManagerService, unbind = unsetModemManagerService]

regards
Amar
