### ISSUE TITLE
[question] How to create services via Kapua

### ISSUE THREAD

**Issue by megla-tlanghorst** [eclipse/kura#3084]
Following eclipse/kapua#3077 is there any way to create a new instance of a service that's automatable (via kapua or command line for specifically) for creating a new CloudService (and Data and MQTT Services)? We can't access the devices directly so something remote would be required for that. I've tried sending new configurations for the (not yet existing) kura services but that just seems to be ignored.

**Comment by MMaiero** [comment]
Hi, the easiest way, for now is to deploy a snapshot containing the new components that you want to be instantiated.

**Comment by megla-tlanghorst** [comment]
Yeah that seems to be doable if I figure out the format on disk, because it seems there's no endpoint in the kapua API for that, but thanks!
