### ISSUE TITLE
Review ConfigurationService password management

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#3087]
Currently the methods in `ConfigurationService` APIs that allow to retrieve `ComponentConfiguration`s differ in terms of password encryption in the returned configuration. Some methods return encrypted passwords and some others don't.
Examples of methods returning encrypted passwords:

* `getComponentConfigurations()`
* `getComponentConfigurations(org.osgi.framework.Filter)`

Examples of methods returning unencrypted passwords:

* `getComponentConfiguation(String)`
* `getSnapshot(long)`

These differences do not seem to be documented at the moment. We should unify the behavior of the method.

**Comment by Alee985** [comment]
Hi! I am beginner to open source
@nicolatimeus @MMaiero Can you please help me over it
Can I start work on it?

**Comment by MMaiero** [comment]
Hi @Alee985!
Thanks for reaching out!
We would really love to have a new contributor to the project!
if I may suggest, I think you can start learning and practicing contributing to the project taking one of the issues marked as "help wanted" https://github.com/eclipse/kura/labels/help%20wanted
There are quite a few interesting ones like: https://github.com/eclipse/kura/issues/4173, https://github.com/eclipse/kura/issues/3250 or https://github.com/eclipse/kura/issues/2863

Let me know if you need further info on how to start contributing.
Best regards,
Matteo

**Comment by Alee985** [comment]
@MMaiero Thank You for the guidance. I will look into the issues you shared
