### ISSUE TITLE
Bundle org.eclipse.equinox.http.jetty stuck in STARTING state

### ISSUE THREAD

**Issue by malveo** [eclipse/kura#3092]
**Bug description**

The HTTP service stay stuck in STARTING state when building Kura on the branch
`develop` for target `intel-up2-ubuntu-18`

**Step to reproduce**
```s
$ mvn -Dmaven.test.skip=true -f target-platform/pom.xml clean install
$ mvn -Dmaven.test.skip=true -f kura/pom.xml clean install
$ mvn -Dmaven.test.skip=true -f kura/distrib/pom.xml clean install -Pintel-up2-ubuntu-18
```

install Kura:

```s
$ telnet localhost 5002
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
osgi> ss | grep http
5       ACTIVE      org.eclipse.equinox.http.registry_1.1.400.v20150715-1528
22      STARTING    org.eclipse.equinox.http.jetty_3.4.0.v20170503-2025
24      ACTIVE      org.eclipse.equinox.http.servlet_1.4.0.v20170524-1452
26      ACTIVE      org.eclipse.jetty.http_9.4.19.v20190610
112     RESOLVED    io.netty.codec-http_4.1.34.Final
149     ACTIVE      org.eclipse.kura.http.server.manager_1.0.0.202010021510
```

Verify HTTP service:

```s
curl -kis http://localhost:80
```

Start the bundle manually:
```s
$ telnet localhost 5002
osgi> start 22
```

Verify HTTP service again:

```s
curl -kis http://localhost:80
HTTP/1.1 302 Found
Date: Fri, 02 Oct 2020 15:49:57 GMT
X-FRAME-OPTIONS: SAMEORIGIN
X-XSS-protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Pragma: no-cache
Location: http://localhost/admin/console
Content-Length: 0
```

**Expected behavior**
The bundle `org.eclipse.equinox.http.jetty` must start in automatic mode without manual intervention.

**Target Environment:**
- Linux 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- openjdk version "1.8.0_265"

**Workaround**
Appending `\:start` to org.eclipse.equinox.http.jetty in `config.ini`

**Comment by MMaiero** [comment]
Hi, 
do you have keytool in the path?
In the past we have seen a similar issue and the cause was due to an incomplete installation.

Matteo
