### ISSUE TITLE
Is it Possible to send data to Kafka directly from Kura?

### ISSUE THREAD

**Issue by koiralo** [eclipse/kura#3101]
Recently I started to use Kura, Is it possible to send/receive data directly from/to Kafka as like in MQTT?
Or can we create Similar things as for MQTT, Is it possible to create a new Cloud connection for Kafka?
If there is no Cloud Connection Manager for Kafka and we have to implement a new Cloud connection can someone guide me?  I would be happy to contribute to it.

**Comment by MMaiero** [comment]
Hi,
we have never tested that.
But I believe that a specific cloud connection that sends data to Kafka can be done. As long as the CloudConnection APIs are implemented, the Kura applications will be unaware if they are publishing via MQTT or other means.

A contribution is more than welcome!

Best regards,
Matteo

**Comment by koiralo** [comment]
Thanks, @MMaiero for a quick response. 
Are there any Docs or previous examples to follow for creating new CloudConnection Implementation? 
I started looking at https://eclipse.github.io/kura/cloud-api/4-stack-dev-guide.html, bud didn't found anything else in detail.
Would be great If any references. 

Also what are these two implementation for 
**org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider**
**org.eclipse.kura.cloudconnection.raw.mqtt.provider**

Thank You,
Shankar Koirala

**Comment by MMaiero** [comment]
Correct. That is a guide made for developers. We have tried to summarise there all the info or starting points needed to develop a cloud connection stack for new cloud connections in Kura.

The two mentioned are implementations of that set of APIs. The first one is an MQTT cloud connector for the Eclipse IoT projects that utilises a specific contract agreed between different Eclipse projects. The other is again an MQTT connector.

Best regards
