### ISSUE TITLE
[Multiple Cloud Connections] Spurious component reactivations upon configuration change

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#311]
Multiple connections: updating a service (e.g. MqttDataTransport) of a connection
has the effect to cause the unwanted reactivation of the next higher layer service (i.e. DataService)
of the other connection(s). This in turn will cause the reactivation of all dependent components.
This is not desired and not yet understood (Equinox bug?).

**Comment by cdealti** [comment]
I wonder if we should consider upgrading Equinox at some point

**Comment by dwoodard1** [comment]
I think we should consider upgrading. I believe we are 5 versions behind at this point.


On Jul 15, 2016, at 07:52, Cristiano De Alti <notifications@github.com<mailto:notifications@github.com>> wrote:


I wonder if we should consider upgrading Equinox at some point

**Comment by cdealti** [comment]
@MMaiero is this still present in Equinox 3.11?

**Comment by MMaiero** [comment]
@cdealti Unfortunately yes

**Comment by cdealti** [comment]
Then we should report this behavior to Equinox

**Comment by MMaiero** [comment]
I agree.
Following what reported in kura-console.log. If I remember well, this is the same message that we got from the old osgi.

`!ENTRY org.eclipse.kura.core.cloud 2 0 2017-03-14 13:20:39.076
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@18e0f3a 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0-SNAPSHOT.jar

!ENTRY org.eclipse.kura.core 2 0 2017-03-14 13:20:41.159
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@18cfa37 
	Details:
	Problematic reference = Reference[name = DataTransportService, interface = org.eclipse.kura.data.DataTransportService, policy = static, cardinality = 1..1, target = null, bind = setDataTransportService, unbind = unsetDataTransportService]
	of service component = org.eclipse.kura.data.DataService
	component implementation class = org.eclipse.kura.core.data.DataServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core_1.0.11-SNAPSHOT.jar

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-03-14 13:20:43.339
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@fbc2c1 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0-SNAPSHOT.jar

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-03-14 13:21:30.392
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@134be49 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0-SNAPSHOT.jar

!ENTRY org.eclipse.kura.core 2 0 2017-03-14 13:21:32.568
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@1f59ff2 
	Details:
	Problematic reference = Reference[name = DataTransportService, interface = org.eclipse.kura.data.DataTransportService, policy = static, cardinality = 1..1, target = null, bind = setDataTransportService, unbind = unsetDataTransportService]
	of service component = org.eclipse.kura.data.DataService
	component implementation class = org.eclipse.kura.core.data.DataServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core_1.0.11-SNAPSHOT.jar

!ENTRY org.eclipse.kura.core.cloud 2 0 2017-03-14 13:21:34.098
!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@948dc1 
	Details:
	Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]
	of service component = org.eclipse.kura.cloud.CloudService
	component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl
	located in bundle with symbolic name = org.eclipse.kura.core.cloud
	bundle location = initial@reference:file:../../kura/kura/plugins/org.eclipse.kura.core.cloud_1.1.0-SNAPSHOT.jar`

**Comment by ctron** [comment]
Are you sure this is an Equinox bug? What would the bug report towards Equinox look like?

**Comment by cdealti** [comment]
Closing as it is not causing any harm.
