### ISSUE TITLE
The iBeacon Scanner sometimes fails to detect beacons

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#3113]
**Describe the bug**
The iBeacon Scanner example [1] sometimes fails to detect the incoming beacons. It seems that if the beacons are generated by the iBeacon advertiser [2] running in a RPi, it works as expected. When the iBeacons are emitted by an Android smartphone with some app, the iBeacon scanner cannot detect any packets.

**To Reproduce**
1. Install the iBeaconScanner example and enable it
2. Install on a different device the iBeaconAdvertiser and enable it
3. See on the log of the first device that the iBeacons are detected
4. Disable the iBeaconAdvertiser and use an Android app to emit iBeacon packets
5. See on the logs of the first device that any packet is detected.

**Expected behavior**
All packets should be detected regardless the device has emitted them.

[1] https://github.com/eclipse/kura/tree/develop/kura/examples/org.eclipse.kura.example.ibeacon.scanner
[2] https://github.com/eclipse/kura/tree/develop/kura/examples/org.eclipse.kura.example.ibeacon.advertiser

**Comment by MMaiero** [comment]
Closing as also https://github.com/eclipse/kura/pull/3118 is now merged for 5.0.0
