### ISSUE TITLE
Maybe Sensehat Joystick Example has some errors.

### ISSUE THREAD

**Issue by 97Albino** [eclipse/kura#3126]
**Describe the bug**
Sensehat joystick example does not function normally.

**To Reproduce**
1. Follow example : [Moving a pixel using the Joystick](http://eclipse.github.io/kura/devices/sensehat-driver.html)
2. No matter which button I press, the pixels move  `x-coordinate : +1` & `y-coordinate : +1` .

**Expected behavior**
The pixels should move in the direction taught by the joystick.
I think there may be a problem with the script code on documentation.

**Screenshots**
Before I press the button.
![KakaoTalk_20201030_141257911](https://user-images.githubusercontent.com/58206274/97662388-3f1c7180-1aba-11eb-9a59-3e079940cabf.jpg)

After I press the button.
![KakaoTalk_20201030_141257911_01](https://user-images.githubusercontent.com/58206274/97662405-4b083380-1aba-11eb-9e55-259c86710176.jpg)

**Target Environment (please complete the following information):**
 - Board [Raspberry Pi 3]
 - OS version: 
![image](https://user-images.githubusercontent.com/58206274/97650769-d9ba8780-1a9d-11eb-90ac-21583f9f456d.png)

 - Additional info: Kura 4.1.0

**Additional context**
When I run joystick example on raspberry pi, I works well.

**Comment by nicolatimeus** [comment]
Hi @97Albino, the led matrix configuration in your photos seems consistent with the sin wave example and not with the joystick example.

The example scripts in documentation cannot be run concurrently on the same graph because they will ovewrite the entire framebuffer content.

I suggest you to delete the wire graph and start from scratch with the joystick example alone, If I remember correctly the sin wave example is not interactive, the output will not change in response to joystick events.

**Comment by MMaiero** [comment]
@97Albino Did you solve your issue?

Can this be closed?

**Comment by 97Albino** [comment]
I followed your advice but that was not solution.

I found the pixel moves when the joystick event occurs.

And through the kura.log, I confirmed that the joystick input is operating normally.

**Comment by nicolatimeus** [comment]
Hi, can you please post a wire graph snapshot of your setup?

**Comment by 97Albino** [comment]
Here is my setup.

![image](https://user-images.githubusercontent.com/58206274/98512722-1cecd580-22aa-11eb-83dd-4dca3728ee75.png)

I only use joystick, PIXEL_MOVE, fb.

![image](https://user-images.githubusercontent.com/58206274/98502197-c032f000-2294-11eb-9b25-e8beaa78a404.png)

![image](https://user-images.githubusercontent.com/58206274/98502296-04be8b80-2295-11eb-8b24-585aac7356c8.png)

I used `Moving a pixel using the Joystick` [example](http://eclipse.github.io/kura/devices/sensehat-driver.html#led-matrix). 

![image](https://user-images.githubusercontent.com/58206274/98502452-641c9b80-2295-11eb-9649-6fc13dc05b34.png)

![image](https://user-images.githubusercontent.com/58206274/98502492-772f6b80-2295-11eb-8961-488fb773b2ac.png)


[graph_snapshot_1604907338018.zip](https://github.com/eclipse/kura/files/5508749/graph_snapshot_1604907338018.zip)

**Comment by 97Albino** [comment]
@nicolatimeus any updates?

**Comment by nicolatimeus** [comment]
Sorry for the late reply, the problem is that I don't have a SenseHat available at the moment, I will try and let you know as soon as I can get one

**Comment by 97Albino** [comment]
@nicolatimeus 
Hi, I have some good news.

I solved that problem by modifying [**Moving a pixel using the Joystick example code**](http://eclipse.github.io/kura/devices/sensehat-driver.html).

git commit


>
    if (update) {
    // framebuffer update requested
    // clear old pixel
    state.fb[state.y*FB_SIZE + state.x] = 0
   
    // compute new pixel position 
    // I revised here
    **if (state.dx==!0)
    {
      state.x = (state.x + state.dx + FB_SIZE) % FB_SIZE
    }
    
    if (state.dy==!0)
    {
      state.y = (state.y + state.dy + FB_SIZE) % FB_SIZE
    }**
    //

    // set new pixel
    state.fb[state.y*FB_SIZE + state.x] = 1
    // clear deltas
    state.dx=0
    state.dy=0
    // emit record
    output.add(state.outRecord)
    }

I guess that the error occurred when **state.x** and **state.y** were executed at the same time.

So I limited unnecessary behavior when a joystick event occurred and was able to solve the problem.

But, I'm not sure this is good solution.

**Comment by MMaiero** [comment]
Hi @97Albino 
thank you for the feedback. Why don't you create a pull request with the changes?
Due to the Eclipse rules we cannot merge directly or with our name code contributed by third parties.

Best regards,
Matteo
