### ISSUE TITLE
Is it unable to use Subscriber from ConnectionManager?

### ISSUE THREAD

**Issue by 97Albino** [eclipse/kura#3129]
Hi 

I tried to add `org.eclipse.kura.cloudconnection.eclipseiot.mqtt.CloudSubscriber` from  `org.eclipse.kura.cloudconnection.eclipseiot.mqtt.ConnectionManager` to recive data from HONO.

I will control GPIO by using HONO.

But,  I can't find `org.eclipse.kura.cloudconnection.eclipseiot.mqtt.CloudSubscriber`.

![image](https://user-images.githubusercontent.com/58206274/98324588-05a2b380-2030-11eb-83d1-94e243756aff.png)

Any solution about it?

**Comment by MMaiero** [comment]
I believe that the subscriber was not an option for the Hono contract that was decided.
