### ISSUE TITLE
User Gets Logged Out if PDF File Uploaded in Device -> Command

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3132]
If user selects a .PDF fiel as file to be uploaded and executed in Device -> Command and clicks "Execute" several times (without adding a command to be executed, e.g. "pwd"), Kura logs user out and saying "Session has expired". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Device -> Command and select a .PDF document in "File" section
3. Without entering a command to execution, press "Execute" button several times - observe the error and how you will get logged out. 

**Expected behavior**
Kura should not log user out in this case. 

**Screenshots**
![Screenshot 2020-11-09 at 09 16 40](https://user-images.githubusercontent.com/15121999/98516090-53a3fb00-226c-11eb-8952-3ae38df81fb2.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.118-v7+ 1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
 - Additional info: latest develop brach

**Additional context**
/

**Comment by MMaiero** [comment]
I believe we need to restrict the type of files that can be uploaded. I believe the code expects just zip and .sh files, isn't it @nicolatimeus ?

**Comment by LeoNerdoG** [comment]
Hey guys, I have checked this again and it happens with a ZIP file also. When you unzip it or rather whe the command is executed, you get logged out.

**Comment by nicolatimeus** [comment]
Yes, probably the restriction is missing, we can add it as done in the other web UI sections.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
