### ISSUE TITLE
500 Server Error if Timeout Field Contains Space

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3133]
If Timeout field in Command Service -> Timeout contains leading space characters, Kura reports a 500 Server error (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Command Service
3. Enter "       10" into timeout field
4. Press Apply - observe the error

**Expected behavior**
Kura should notpermitt user to apply changes if the field contains invalid symbols. 

**Screenshots**
![Screenshot 2020-11-09 at 11 30 35](https://user-images.githubusercontent.com/15121999/98530565-5fe58380-227f-11eb-9c53-3762744f644a.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.118-v7+ 1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
 - Additional info: latest develop brach

**Additional context**
/

**Comment by MMaiero** [comment]
Is this still an issue?

**Comment by LeoNerdoG** [comment]
I will check and close if not recreatable.

**Comment by LeoNerdoG** [comment]
Hey @MMaiero, this is still an issue.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
