### ISSUE TITLE
Should "Command Working Directory" be Moved to Device -> Command?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3134]
When trying to execut certain commands and move from folder to folder this is pretty hard to do, since "cd" command does not do what it is supposed to. Instead you have to go to Command Service -> Command Working directory and change it there and then go back to Device -> Command. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Device -> command
3. Try to type ls -l command, observe the output. 
4. Try to type "cd .." -> nothing happens
5. Go to Command Service -> Command working directory and change directory there
6.  Now that you have moved to another directory, you are able to list files in that directory

**Expected behavior**
See above. 

**Screenshots**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 4.19.118-v7+ 1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
 - Additional info: latest develop brach

**Additional context**
/

**Comment by MMaiero** [comment]
The working directory is a configuration choice that can be made by a person different from the one that is actually executing the command.
