### ISSUE TITLE
Feedback in Wire-Graph

### ISSUE THREAD

**Issue by manuelfa** [eclipse/kura#3135]
My goal is to embed a PID-controller in my Wire-Graph.
In order to do this, I need a feedback between two components in the graph, but Kura doesn't enable the wires to connect.
I need to connect the output from compoent B with the input of component A and the ouput of A with the input of B. 
There would not be a infinite recursion because A doesnt trigger its ouput if the onWireReceive() is called by an input comming from B.

My current workarround is to store the output from B in a Kura database component and query them in a second databse compnent in front of  component A. 

Do you know another way to do it?
Is it basically possible to adjust Kura so that feedback works or would it leed to any problems with the execution modell? 

Thank you

**Comment by MMaiero** [comment]
Hi,
feedback was not enabled to prevent infinite recursion. As we don't know what the connected components are doing, we needed to block it in all cases.
The solution you pointed out is a possible way to achieve this. Or use a publisher/subscriber with the internal broker could be another solution.
If you have experience with loops and associated algorithms that can be implemented to improve the execution model of the Wires feature, please feel free to open a pull request. We will be happy to receive new contribution to improve the product.

Best regards

**Comment by manuelfa** [comment]
Thanks for your quick response.
Can you tell me at which point the schedul logik is implemented? 

Best regards

**Comment by MMaiero** [comment]
I would suggest to start looking at the following bundles: org.eclipse.kura.wire.helper.provider and org.eclipse.kura.wire.provider. For the visual part that blocks the loop, have a look in the org.eclipse.kura.web2 bundle.

**Comment by MMaiero** [comment]
Any feedback for this item? Can this be closed?
