### ISSUE TITLE
Publishing Kurapayload on Kapua using data service  

### ISSUE THREAD

**Issue by funnyboys1008** [eclipse/kura#3137]
Hi,

I'm trying to publish data on kapua ,through my osgi plugin. I want to send a kura payload  to kapua and for this i'm using  data service interface. It has a function to publish but it takes bytes[] as an input. Is there any way by which i can publish my kura payload through the data service ?

Here is an example for a payload in the demo heater plugin 

```
KuraPayload payload = new KuraPayload();
        
        payload.setTimestamp(new Date())
        payload.addMetric("temperatureInternal", this.temperature);
        payload.addMetric("temperatureExternal", 5.0F);
        payload.addMetric("temperatureExhaust", 30.0F);

        KuraMessage message = new KuraMessage(payload);

        // Publish the message
        try {
            this.cloudPublisher.publish(message);
            logger.info("Published message: {}", payload);
        } catch (Exception e) {
            logger.error("Cannot publish message: {}", message, e);
        }
```

The same thing i want to implement using the data service interface, is there anything possible ?

Thanks!

**Comment by MMaiero** [comment]
Hi, the preferred and suggested way to publish a message is by using the CloudPublisher API. That is built on top of the DataService API and manages all the conversions, simplifying the publishing like you have shown in the example above.
As you have pointed out the DataService API can be used but only supports the message as a byte[]. 

Best regards

**Comment by funnyboys1008** [comment]
okay,is there any way by which this payload can be sent through dataservice api ?

Regards

**Comment by MMaiero** [comment]
Sure there is. I suggest to have a look at the code of the CloudService.

**Comment by funnyboys1008** [comment]
I tried using the encoding files  in "eclipse.kura.core.cloud" but everytime i try to import the packages , it shows some error related to cyclic dependency .

A cycle was detected when generating the classpath org.eclipse.kura.demo.heater_1.0.501.202011120945, org.eclipse.kura.core.cloud_1.1.401.202011120945, org.eclipse.kura.core_1.0.502.202011120945, org.eclipse.kura.core.configuration_2.0.201.202011120945, org.eclipse.kura.core_1.0.502.202011120945

Regards

**Comment by MMaiero** [comment]
Yes, a cycle has been generated since you are using both the core.cloud and the core bundle that is used by the core.cloud bundle as well

**Comment by funnyboys1008** [comment]
but i have only imported the kura.core.cloud package, and there is no other core packages imported like kura.core.configuration

**Comment by MMaiero** [comment]
Hello, is this still an issue? Can this be closed?
