### ISSUE TITLE
The Kura documentation should mention the default login credentials admin/admin

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#315]
Copied over from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=497751

Right now neither the Raspberry Pi Quickstart nor the "Getting started" section mention that the default credentials are admin/admin.

**Comment by MMaiero** [comment]
http://eclipse.github.io/kura/doc/raspberry-pi-quick-start.html
http://eclipse.github.io/kura/doc/beaglebone-quick-start.html
Done.
@dwoodard1 If it is ok, I think we can close

**Comment by ctron** [comment]
+1
