### ISSUE TITLE
Disabling Password and Certificates not Mutually Exclusive

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3153]
Kudos to @mstankovic for finding this issue. I am adding it here so we have a sepparate issue for it (for easier tracking)
In WebConsole service in Certificates user can disable Password and/or Certificates authentication. The problem is that those two are not mutually execlusive, meaning that user can (accidentally or not) disable both of them and device becomes inaccessible. This can however be fixed through cloud (if device is connected to one).

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Web Console
3. Try to disable Password and Certificate authentication methods
4. Refresh page and observe how Kura is not accessible anymore. 

**Expected behavior**
User should not be able to disable both authentications at once. 

**Screenshot:**
![Screenshot 2020-11-17 at 08 07 16](https://user-images.githubusercontent.com/15121999/99357342-0814d100-28ac-11eb-8fb6-06d37fff55c9.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by MMaiero** [comment]
I believe that is acceptable to be able to disable the authentication methods, if desired. 
Probably we should add a message saying that no authentication method is currently enabled/available for the users

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
