### ISSUE TITLE
No Description of Web Console Service and HTTP Service

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3155]
When user changes something in WebConsole or HTTP Service, various error messages might appear. Nontheless, user might not be aware of that, due to the lack of descriptions in these services (see screenshots bellow from Kura 4.2.0 version). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> WebConsole
3. Observe the lack of description
4. Go to Security -> HTTP Serivce -> observe the lack of description.

**Expected behavior**
Descriptions should be added to WebConsole and HTTP services.

**Screenshot No. 1:**
![Screenshot 2020-11-17 at 08 33 59](https://user-images.githubusercontent.com/15121999/99359810-e74e7a80-28af-11eb-802b-8aa470f12dce.png)

**Screenshot No. 2:**
![Screenshot 2020-11-17 at 08 33 46](https://user-images.githubusercontent.com/15121999/99359797-e289c680-28af-11eb-93bd-63437bad9abf.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
Fixed
