### ISSUE TITLE
Rearranging Buttons in "Add Certificate" Modal

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3158]
Currently the "Add Certificate" modal has button arrangement as they are in services (e.g. in ClocService, where Apply and Reset buttons are in top left corner). I think this should be changed so the Apply (or rather Submit) and Reset buttons are in the bottomr right corner as in all other modals. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte HTTPS Server Certificate
4. Observe the buttons arrangement

**Expected behavior**
When certificate is added (or error appears), modal for adding certificate should be closed. 

**Screenshot:**
![Screenshot 2020-11-17 at 10 28 29](https://user-images.githubusercontent.com/15121999/99371788-a78f8f00-28bf-11eb-8eb3-2d30c4dce259.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
Fixed.
