### ISSUE TITLE
Random Filtering by "Type" When Clicking "Refresh" in Certificates

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3159]
If user clicks "Refresh" button multiple times in Certificates, the certs are filtered randomly by "Type". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte HTTPS Server Certificate
4. Add a valid certificate, click Apply
5. Click "Refresh" several times and observe the list of certificates

**Expected behavior**
If user presses "Refresh", there should be no filtering. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
The filter is not present anymore.
Won't fix.
