### ISSUE TITLE
Debian package should declare dependency on java

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#316]
Copied over from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=497749

Since the Kura platform does require Java as a runtime it should declare a dependency on `java7-runtime-headless`, which will provide a suitable JRE.

Currently the Kura package only depends on:

   hostapd, isc-dhcp-server, iw, dos2unix, bind9, unzip, ethtool, telnet

**Comment by MMaiero** [comment]
@pierrepitiot
