### ISSUE TITLE
Dialogue Box for Deleting Certificate Contains Certificate Alias

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3160]
When deleting a certificate from the list, a dialogue box opens for confirming the decision. The problem here is that dialogue box contains certificate alias, which can lead to a very big dialogue box. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte Server SSL Certificate
4. Enter a very long name for certificate alias
5. Add a valid certificate, click Apply
6. Select the newly created ceritifacet and click "Uninstall"
7. Observe the dialogue box test

**Expected Behaviour:**
I recommend that this gets changed to "Are you sure you want to remove the selected certificate? Removing a certificate might have unexpected effects on the stability of the framework. If in doubt, answer "No"."

**Screenshot:**
![Screenshot 2020-11-17 at 10 54 04](https://user-images.githubusercontent.com/15121999/99375734-57ff9200-28c4-11eb-845f-923ea8d8b9e7.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
Already patched.
Won't fix.
