### ISSUE TITLE
Cannot User Certificate Login Unless "Remember my decision" Selected

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3164]
If user does not check "Remember my decision" box when trying to login with a certificate, there is no way of logging into Kura. If the checkbox is checked, then user can login into Kura. 
This can be a problem if Kura will contain multiple login certificates from multiple users. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte HTTPS Client Certificate, add a valid certificate
4. Add the corresponding .pfx key into the browser
5. Reboot raspberry
6. On login page select "Certificate" and select the newly added certificate
7. Do not check the "Remember my decision" box, try to login
8. Check the "Remember my decision" box, try to login - this time it is successful

**Expected behavior**
I would expect that user is able to login with his certificate even if the "Remember my decision" is not checked. Now...I don't know if this is related to browser or not, but if Kura contains multiple login certificates, this can be a problem. 

**Screenshot:**
![Screenshot 2020-11-18 at 09 50 36](https://user-images.githubusercontent.com/15121999/99507406-a031b980-2983-11eb-9114-d5cbbdc91862.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
The behaviour in Firefox is as expected. if the User doesn't accept to remeber the use of the certificate each time a new connection is opened, a new authorization windows is displayed. 
After some requests the users is allowed to login correctly but every time a resource is requested a new windows is displayed.
Other Browsers (e.g. Edge) don't allow user to not remember the authorization.
Won't fix.
