### ISSUE TITLE
No "Alias" for "HTTPS Client Certificate"

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3166]
Curnetly there is no "Alias" field when adding "HTTPS Client Certificate" which results in a generic name. The problem is if user adds several LOGIN certificates - they are undistinguishable from one another.  Is it possible to add "Alias" field when creating "HTTPS Clietn Certificate"?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte HTTPS Client Certificate, add a valid certificate
4. observe the name of the certificate

**Expected behavior**
Is it possible to add "Alias" field when creating "HTTPS Clietn Certificate"? 

**Screenshot:**
![Screenshot 2020-11-18 at 09 57 20](https://user-images.githubusercontent.com/15121999/99508066-76c55d80-2984-11eb-9453-d45a62cd59f7.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
Now alias is present in the unified management of certificate list.
Wont' fix.
