### ISSUE TITLE
"Impossible to remove certificate" Error in kura.log File When Deleting a Certificate

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3167]
If user deletes a certificate, there is a "Impossible to remove certificate" error in kura.log file, although the certificate is not visible in the UI anymore. I think that either logs should be changed or behaviour of the UI (add info windows that says "restart device for changes to take affect" or something similar). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Select e.g. HTTPS Server Certificate, add all the necessarr parameters, click Apply
4. Select the newly created certificate, delete it, observe the message in kura.log

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-11-18 at 12 34 27](https://user-images.githubusercontent.com/15121999/99537615-3083f480-29ac-11eb-9ee0-a30a3494dc4b.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by LeoNerdoG** [comment]
@nicolatimeus if I see correctly - now there is no message when user deletes a certificate? If this is desired behaviour then this is fixed. Otherwise please provide an update or an idea of the expected behaviour.

**Comment by MMaiero** [comment]
Yes, this is the desired behaviour since we have updated the code.
