### ISSUE TITLE
Assign different name to "extended" packages

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#317]
Copied over from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=497746

Currently the installer packages for Kura are available in a "normal" and "extended" version.

However the file names offered for download do not make this visible to the user. So your cannot decide, from the name of the package, if it is the normal or extended version.

e.g.: "kura_1.4.0_raspberry-pi-2_installer.deb" is used for both the normal and extended version.

I would suggest to rename the extended packages to something like "kura_1.4.0_raspberry-pi-2_installer_extended.deb"

**Comment by cdealti** [comment]
@dwoodard1 can you please take a look?

**Comment by dwoodard1** [comment]
This is definitely confusing. However, with Kura 2.0, we will no longer need the extended downloads. There will only be two installers per platform (with or without networking). Do you think we should try and clean up the old downloads?

**Comment by cdealti** [comment]
@dwoodard1 Shall we provide only the installer with the Web UI?

**Comment by dwoodard1** [comment]
@cdealti  The build is not currently setup to create a "no web UI" installer. This would delay the release by a bit if we want to provide this. It may be simpler to give instructions on how to remove the web bundle if it is not needed.

**Comment by MMaiero** [comment]
@dwoodard1 for this release we can build it without the web profile (as usual) and simply rename the files as _no_web.dp. Eventually we can think to see if we can automate this stuff. Maybe with a specific device_profile in the distrib pom file: we could have full build, nn and no web. The cost will be a longer build and a little bit of effort when adding a new device...

**Comment by dwoodard1** [comment]
@MMaiero @cdealti We have never created "no web UI" builds before, why now? The only reason for the separate downloads previously was due to the license issue with GXT. Seems to me we should just do a standard build and add the "no web UI" installers later if needed.

**Comment by MMaiero** [comment]
@dwoodard1 I agree with your position. So I think this issue can be closed, right?

**Comment by dwoodard1** [comment]
I think this is still an issue. Let me try and summarize:

- We are currently only distributing installers that include the web UI. It may be useful to include an installer without the UI bundle
- If we do provide this type of installer, we should make it clear in the installer name that the UI is not included
- There is a similar issue with the user workspace. Currently the version number is not included in the archive. It would be nice to include the version to differentiate one user workspace from another.

**Comment by cdealti** [comment]
Do we really need to create different installers? There are already many of them.
If one does not want the UI she can simply delete the bundle

**Comment by ctron** [comment]
I think this can be closed as there is currently only Kura with Web UI. So the difference between "classic" and "extended" is gone.
