### ISSUE TITLE
"X" Button in Certificate Modals not Needed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3170]
Because there is a "Close" button on all steps when adding certificates (and you can also cancel the process with pressing the ESC key on keyboard) I think that the "X" button in the top rigt corner can be removed. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Observe the "X" button in the top right corner

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-11-18 at 12 30 27](https://user-images.githubusercontent.com/15121999/99529963-f4976200-29a0-11eb-9749-27a9f3567969.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.

**Comment by salvatore-coppola** [comment]
Resolved
