### ISSUE TITLE
No Tooltip for Alias Field

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3171]
If you hover above the "Alias" field in Security Service, there is no tooltip. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Select one of the options and observe the Alias field - if you hover above there is no tooltip. 

**Expected behavior**
I would add a tooltip becasue all other fields have them (either that or a detailed description as for example "Certificate" and "Private key" fields in Security Service). 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
That view is no more available, replaced by keystore modal panel.
Won't fix.
