### ISSUE TITLE
No Filtering by Alias in Certificates

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3173]
Currently there is only "Type" filtering but it would be very nice to have filtering by Alias. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security, observe the filtering options
There is no option fo filtering by Alias.

**Expected behavior**
See above.

**Screenshots**

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
There's no more filters on that table.
Won't fix.
