### ISSUE TITLE
Syntax Errors in HTTPS Service

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3174]
There are two syntax errors in the HTTP Service Settings. 
1. Instead "Specifies the path for the CRL for client certificate revcation check." in HTTPS Client Revocation URL" should be "Specifies the path for the CRL for client certificate revocation check."
2. Instead "Specifies whether to check revocation status of client certificats." in HTTPS Revocation Check Enabled" should be "Specifies whether to check revocation status of client certificates."
3. Instead of "Https Revocation Check Enabled" should be "HTTPS Revocation Check Enabled"
4. Instad of "Https Client Revocation URL" should be "HTTPS Client Revocation URL"
5. Instead of "Https Client CRL path" should be "HTTPS Client CRL path"
6. Instead of "Https Revocation Soft-fail Enabled" should be "HTTPS Revocation Soft-fail Enabled" 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service
3. Observe the syntax errors (described above)

**Expected behavior**
Syntax error should be fixed (see above). 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by salvatore-coppola** [comment]
1. Already fixed.
2. Fixed.
3. Fixed.
4. Fixed.
5. Fixed.
6. Fixed.
