### ISSUE TITLE
Modem interface number management

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#3176]
**Describe the bug**
The #3141 adds the support for multiple modems. Since the user can modify the interface number (i.e. ppp0, ppp1, ecc.) and there aren't any restrictions on that, this can cause weird behaviors. If the interface numbers are the same, for example, Kura will apply the same configuration to the two interfaces. Moreover, if an old configuration is stored on the filesystem and a new modem is attached with the same interface number, the old config is applied to the new modem.

**To Reproduce**
**A couple of test cases should be reported!**

**Expected behavior**
IMHO, Kura should block the invalid interface number, for example because another interface has the same one. Or, Kura could manage the interface names in an automatic way, preventing the user to change them.

**Comment by MMaiero** [comment]
@pierantoniomerlino any more thoughts on this? What is the effort needed?

**Comment by MMaiero** [comment]
@pierantoniomerlino This can be closed, right? I believe we have solved it in 5.1.0

**Comment by pierantoniomerlino** [comment]
@MMaiero Yes.
