### ISSUE TITLE
Kura Breaks if "HTTPS Keystore Path" Does not Point to a File

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3179]
If user changes "HTTPS Keystore Path" so it does not point to a file, but rather leaves it like "/opt/" (or something similar), Kura is enable to restart and user has to reinstall Kura in order to get it work again. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTPS Service -> "HHTPS Keystore Path"
3. Enter e.g. "/opt/" and wait for Kura to respond. 
4. Try restarting device
5. Kura stays unaccessible.

**Expected behavior**
Kura should not be unaccessible if user does not enter a proper path into "HHTPS Keystore Path". There should be some kind of validation on this field. 

**Screenshot No. 1:**
![Screenshot 2020-11-20 at 13 56 31](https://user-images.githubusercontent.com/15121999/99802703-6d7cf200-2b38-11eb-9b5a-8b0da5fe6187.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
I don't know if such check can be implemented: it will need to be able to inspect the path and access the keystore prior to saving the configuration.
With the current OSGi metatype is actually hard if impossible to achieve.
