### ISSUE TITLE
There should be Oomph based setups for Kura

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#318]
Looking at the documentation I think it would be nice to have Oomph based setups for developing for and with Kura.

I think you would need two setups:
* One for people writing applications for Kura
* One for people working on Kura

This should remove the requirement to download and unzip a complete workspace.

**Comment by kartben** [comment]
fwiw I think @amitjoy has worked on a Yatta profile https://marketplace.yatta.de/profiles/l6NV

**Comment by ctron** [comment]
Thanks @kartben for bringing this to my attention. However, as I looked into the description, this still leaves a few things to do. Also, to my knowledge, Yatta profiles cannot be edited as Oomph setups can be. In the past I had to ask Yatta to do this.

**Comment by amitjoy** [comment]
After having a conversation with the Yatta guys, they are coming with a GUI support to customize your own Yatta Profile. It's in progress and I believe it would definitely be helpful for developers to use Yatta Profile for setting up development environment.

**Comment by ctron** [comment]
Sure that would a great enhancement. I mean they can also convert it now using the Ommph setup in PR #320, this should do the trick and you don't have to wait.

**Comment by ctron** [comment]
I did enhance the Oomph setup in way that the user has the ability to choose in the initial setup dialog whether he wants the full Kura setup (developer) or just the Getting started modules (user).
