### ISSUE TITLE
Kura not Reporting Error for Failed Login

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3182]
if user presses "Login" button mutliple times when username and password credentials are wrong, Kura stops reporting error but instead only shows the rotating cog and that's it. 

**Testflow:**
1. Open https://kura-ip
2. Without entering a usernaem or password start clicking on "Login" button
3. When error appears, press "ESC" key on the keyboard and continue with clicking on "Login"
4. After several clicks Kura will stop showing the error message. 

**Expected behavior**
Kura should always show error if user enters wrong username and/or password.

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/99806507-69ec6980-2b3e-11eb-9f60-ed7506f42565.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by MMaiero** [comment]
Was that already an issue or is added by the PR for certificate authentication?

**Comment by LeoNerdoG** [comment]
I have checked this and it tourns out this is also in develop.

**Comment by marcellorinaldo** [comment]
@MMaiero solved.
