### ISSUE TITLE
Unable to Login via HTTP in Firefox

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3183]
If user is trying to login via HTTP in Firefox, the HTTP (non secure) connection is not working - the login flashes like user is logging in, but then the login screen appears again. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTPS Service -> HTTP Enabled -> set to True
3. Open port 80 in the firewall 
4. Refresh page
5. Try to login via HTTP in Firefox
6. Observe the behaviour

**Expected behavior**
User should be able to access Kura via secure and non-secure protocol in the same browser? 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
Is this an issue already there in develop or added by the certificates login PR?

**Comment by LeoNerdoG** [comment]
hey @MMaiero,
I have checked this on develop branch and there the behaviour is Ok, so this has been introduced through PR.

**Comment by nicolatimeus** [comment]
This probably happens if the user tries to login with HTTP after logging in with HTTPS. The server probably asks the browser to replace over HTTP the session cookie that has been previously set via HTTPS.
A workaround should be clearing the Kura related cookies from the browser and retrying.
We can investigate if it is possible to fix this by changing server configuration.

**Comment by LeoNerdoG** [comment]
@nicolatimeus actually user is not able to login at all, regardless if the session cookies are deleted or not. Login page is shown and user can enter username and password, but upon pressing "Login", screen flashes and user is thrown back to login page. 
I deleted history, cache and cookies before testing this. My FF version is 83.0 (64-bit).

**Comment by MMaiero** [comment]
I have tested with Firefox 81 and 84 without issues. As suggested, clearing the cookies solved the login issues when https and http are both used

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I have tested this and have to say that in order to be able to login via HTTP (non-secure), user actually has to close the browser first. I am adding flow for logging in in case somebody needs this. 

If user has firstly logged in via HTTPS (secure), then logging via HTTP (non secure) is possible if:
**Login flow:**
1. User clears history and cookies
2. Opens port 80 and enables HTTP protocol
3. CLOSES the FF browsers and reopens it
4. Logs in via HTTP -> now you are able to login. 

if user does not clear cookies, history and reopens the browser, login is not possible. 
I am closing this as resolved, due to upper Login flow.
