### ISSUE TITLE
Docker | Cannot start Kura container

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3185]
**Describe the bug**
Cannot start Kura docker container

**To Reproduce**
1. Build Kura Image from develop branch
```
*git branch: 'develop', url: 'https://github.com/eclipse/kura.git'
cd kura/container/kura_centOS
docker build -t kura_centos .
```
2. Try to run container from Kura image
```
sudo docker run --name kura-docker kura_centos:latest
```
3. Check for running containers
```
sudo docker ps
```

**Expected behavior**
Kura docker container should start

**Additional context**
Also happens for **Alpine** image

**Comment by MMaiero** [comment]
This should be solved now, right @mstankovic ?

**Comment by mstankovic** [comment]
yes @MMaiero 
Im able to run containers with instructions from https://github.com/eclipse/kura/pull/3184
