### ISSUE TITLE
Firewall Error for "discarding changes" Although Nothing Changed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3187]
If you follow the testflow below you will see, that Kura asks user if he wants to discard changes, although nothing has been changed in the Firewall. I have efound this issue in develop branch. 

Error in Firewall "do you wnat to discard changes" althoug nothing has changed. Try to add port range 0:65535 and then try to change views. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click New. Add new port range "1:65535"
3. Try to again add port range "1:65535"
4. Close the Waring and close the "New" modal.
4. Try to switch views - observe the behaviour. 

**Expected behavior**
Kura should not report that there are unsaved changes, because there are none, if user is trying to add a non valid port range into the Firewall. 

**Screenshot:**
![234](https://user-images.githubusercontent.com/15121999/100229099-fd011700-2f23-11eb-9166-956efb0013bd.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
@MMaiero solved.
