### ISSUE TITLE
Kura Unaccessible if HTTP and HTTPS Port the Same (No Validation)

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3188]
If user sets the same port for http and for https, kura is not accessible anymore. If (by some chance) the device is connected to Kapua, this can be changed and Kura can be access again, but I think, that there should be some kind of validation for HTTP, HTTPS and certificate HTTPS. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service
3. Set the http and https ports to the same value (e.g. 99, after it has been opened in the Firewall)
4. Observe the behaviour (reboot the device if necessary)

**Expected behavior**
there should be some kind of validation on these port fields. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
This is unfortunately not possible with basic OSGi metatype

**Comment by LeoNerdoG** [comment]
Hey @MMaiero,
I suggest to keep this open? Or should we close it as it is not possible to fix as you described above?

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I have checked fix for this issue in PR #3207 and have two comments:
 - modal title should be Error and nto Warning
 - Text should be: "HTTP connector port configuration is not valid or same port is used for more than one connector." instead "HTTP connector port configuration is not valid or some port is used for more than one connector."

![Screenshot 2020-12-11 at 14 46 31](https://user-images.githubusercontent.com/15121999/101910867-da2b5f80-3bbf-11eb-9183-f663049e2b6f.png)

**Comment by nicolatimeus** [comment]
Commit 75328fb should implement the suggested changes

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been successfuly fixed with upper commit.
