### ISSUE TITLE
HTTPS Keystore Path and Password not Mandatory Fields

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3189]
Currently HTTPS keystore and password fields are not mandatory, which can lead to some inconvenient scenarios and device being inaccessible (e.g. user accidentally deleting one of the fields, forgeting about it and saving changes -> afterwards device is not accessible anymore). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service, delete the HTTPS Keystore path and/or Password field
3. Reboot the device, try to acces it via HTTPS
4. Observe the behaviour (reboot the device if necessary)

**Expected behavior**
I would recommend to mark those fields as mandatory, because if they are not populated, user cannot access the device via HTTPS anyway. 

**Screenshot:**
![Screenshot 2020-11-25 at 15 06 00](https://user-images.githubusercontent.com/15121999/100237839-bfa28680-2f2f-11eb-949e-07a6f8414311.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
I can agree on the analysis, but since there is the possibility to have just http configured and enabled, I believe we cannot force the requirement on those fields. A misconfiguration is always possible but I don't know how we can prevent it right now.

**Comment by salvatore-coppola** [comment]
Since the latest kura snapshot version, keystore paths are mandatory. Keystore password could be blank because it's not alway required.
Wont'fix.
