### ISSUE TITLE
Keystore Password Restored After Reboot

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3190]
If user deletes keystore password and reboots the device, password is restored - I don't think that this is desired behaviour, becasue if user for example deletes the keystore path, it stays empty after reboot. 
I am sure that password is restored, because user can normally add and delete certificates.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service, delete the HTTPS Keystore Password
3. Reboot device and go to Security -> HTTP Service -> observe the Password field - it is not empty

**Expected behavior**
If user deletes keystore password, it should stay empty after reboot. (?) 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
Is actually there a password? I mean, if you download the snapshot, the password is reported?

**Comment by LeoNerdoG** [comment]
Hey, yes there is a password in the downloaded snapshot.

**Comment by MMaiero** [comment]
@LeoNerdoG Is this issue still there?

**Comment by LeoNerdoG** [comment]
@MMaiero  I will check and let you know.

**Comment by LeoNerdoG** [comment]
Kura now reports that keystore password is necessary if HTTPS enabled  - which is OK. 
Password is successfully deleted if HTTPS is disabled, so i am closing this.
