### ISSUE TITLE
Kura Hangs After Keystore Password Deleted

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3191]
If user deletes Keystore password, Kura UI stops responding untill device is rebooted. This should not happen, as if user changes something in HTTP service, UI should be temporarily unavaliable, but should start working again after some time. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> HTTP Service, delete the HTTPS Keystore Password
3. observe the behaviour - you have to reboot the device in order for UI to start working again.

**Expected behavior**
Device reboot should not be necessary if keystore password is changed/deleted. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
Is this referred to develop?

**Comment by LeoNerdoG** [comment]
Hey, I can confirm that this happens also in develop, so it is not issue introduced in PR 3143.

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I have checked this issue or rather its fix in PR #3207 and now Kura reports an error if user wants to save empty keystore path (Screenshot No. 1). The only problem is that the fields keystore path and password are not labeled with asterix as mandatory and also not labeled red when empty (as all other fields when they do not contain valid parameters). 

![Screenshot 2020-12-11 at 14 44 28](https://user-images.githubusercontent.com/15121999/101910648-83258a80-3bbf-11eb-877e-86aa3a721921.png)

**Comment by nicolatimeus** [comment]
See comment https://github.com/eclipse/kura/issues/3193#issuecomment-743297207

**Comment by LeoNerdoG** [comment]
Hey, thanks for the detailed answer in issue 3193. 
I guess that this is then desired behaviour? Should we close this issue or leave it open and re-mark it as an "enhancement" or "good to have" or something similar? I think it is not a P1 anymore.
