### ISSUE TITLE
Wrong Title for Error Messages

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3192]
There are some cases when adding certificate or changing HTTPS port number produces an error. Kura successfully reports those on the screen but the problem is that the name of the window is "Warning" but the actual content is an erronous. Below there is a full list of cases when this happens. 

1. If you want to add a HTTPS Client Certificate that is not in correct form (Screenshot No. 1)
2. When you try to add a "key" certificate instead a "cert" into Server SSL Certificate or any other non-valid certificate file (Screenshot No. 2)
3. Adding invalid certificate files (key or cert) in Device SSL Certificate (Screenshot No. 3)
4. Adding an invalid Application Certificate (Screenshot No. 2)
5. Adding same certificate for "cert" and "key" parameters for HTTPS Server certificate (Screenshot No. 3)
6. Adding an invalid certificates (cert, key or both) when adding HTTPS Server certificate (Screenshot No. 2)

**Testflow:**
1. Login to Kura as admin/admin
2. After login press the "backspace" key on the keyboard
3. Observe the effect - user gets logged out. 

**Expected behavior**
Kura should ask user if the changes made should be saved or not. 

**Screenshot No. 1:**
![Screenshot 2020-11-20 at 12 40 57](https://user-images.githubusercontent.com/15121999/99797032-cb0c4100-2b2e-11eb-9729-8a81ebaa5bf5.png)

**Screenshot No. 2:**
![Screenshot 2020-11-26 at 11 17 18](https://user-images.githubusercontent.com/15121999/100338612-1912c000-2fd9-11eb-9f16-ad7d6eee1c89.png)

**Screenshot No. 3:**
![Screenshot 2020-11-26 at 11 20 53](https://user-images.githubusercontent.com/15121999/100338971-8e7e9080-2fd9-11eb-9d8b-5544122b9f1a.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR 3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
The screenshot seems to be not based on develop

**Comment by LeoNerdoG** [comment]
You are right, this is from PR 3143, I have changed the "tested branch" to "PR 3143".

**Comment by salvatore-coppola** [comment]
fixed
