### ISSUE TITLE
No Warning That Certificate Aliases Changed to Lower Case Letters

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3194]
If user wants to add two different e.g. Server SSL Certificates, one "abc" and other "ABC", this is actually one certificate, because Kura lowers all the characters. I think there should be some kind of warning about this. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add Certificate
3. Add a SSL Server certificate with name "abc"
4. Add another SSL Server certificate with name "ABC"
5. Observe results - for Kura this is one certificate named "abc"

**Expected behavior**
See above. 

**Screenshot:**
![Screenshot 2020-11-26 at 12 55 10](https://user-images.githubusercontent.com/15121999/100348115-c04a2400-2fe6-11eb-83d6-213cf2343b0a.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_

**Additional context**
/

**Comment by MMaiero** [comment]
it is actually in the Java implementation for keystokes.
We could see if it is possible to forse a lowercase input. But I would call it as a P2 for now

**Comment by salvatore-coppola** [comment]
fixed forcing lowercase in inputbox
