### ISSUE TITLE
Kura not Accessible Anymore if HTTPS Access Disabled

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3198]
If user disables HTTPS access and enables HTTP access (on port 80, port added into Firewall), Kura is not accessible any more. You cannot acces via HTTP or with certificates (if firewall ports opened and certificates added, of course). 

**Testflow:**
1. Login to Kura as admin/admin
3. Go to Firewall, open port 80
3. Go to Security -> HTTP Service 
4. Enable HTTP service and disable HTTPS service
5. Reboot the device -> observe the behaviour, Kura does not load

**Expected behavior**
If user enables HTTP service and disables HTTPS service, Kura should be at least accesible through HTTP Service. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ (this does NOT happen on latest develop branch!)

**Additional context**
/

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus, I have checked the fix on PR #3207 and user is not able to login via HTTP, but is able to login with certificate if this option is enabled and certificate loaded, so it is still not fixed.

**Comment by nicolatimeus** [comment]
Hi @LeoNerdoG .
I've tried to reproduce again, after reboot in my case port 80 was reachable and I could get to the login screen. After entering username and password I encountered #3183. 
I could login after closing all browser windows (I used a Chrome in incognito mode) and retrying.
Can this be a duplicate of #3183?

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I should have added into the issue description the following:
 - after you open port 80, enable HTTP and disable HTTPS, you can access login page from every browser via HTTP (Chrome, FF, Opera, Safari), but you cannot login in FF (see below)
 - you are able to login only in Chrome, Opera and Safari, but not from FF -> this is actually issue #3183 and it looks like this issue is a duplicate of 3183, so I am closing this one. 
Maybe it got fixed in the mean time. Nonetheless, one issue less to worry about.
