### ISSUE TITLE
project layout maven/bnd

### ISSUE THREAD

**Issue by stbischof** [eclipse/kura#3205]
Is there any plan to change the project layout to maven/bnd?

**Comment by MMaiero** [comment]
Hi, 
not at the moment. But we are open to contributions!

Best regards,
Matteo

**Comment by stbischof** [comment]
Just wanted to know that you are open for. Maybe i can give aome support

**Comment by stbischof** [comment]
@MMaiero
- Are there any reasons for the fixed jar of paho-client in the core bundle? must it be included and why? updates e.g. `org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.2.5` possible? 

- is JavaSE-1.8 still the target version?

**Comment by MMaiero** [comment]
Hi, 
we had to fork pho and create the .kx version due to some bugs that we solved locally [1] but were still pending upstream.
I have not checked recently if those were solved recently with one of the latest releases.

Regarding question 2, yes Java 8 is our current baseline target.

Best regards,
Matteo

[1] https://github.com/eurotech/paho.mqtt.java/tree/maintenance-1.2.1

**Comment by stbischof** [comment]
@MMaiero could we have a call to speak about #3567 and the main ideas of my changes. just want to be sure that you are okay with before i go more down the rabbit hole

**Comment by MMaiero** [comment]
Hi @stbischof,
sure.
What about tomorrow? I have a free slot from 4 pm to 5pm CET or from 5pm to 6pm CET.
Otherwise we can schedule something on Thursday morning, if you prefer.

Matteo

**Comment by stbischof** [comment]
4PM CEST(Berlin, Rome) would be great.

stbischof@bipolis.org

**Comment by MMaiero** [comment]
Hi @stbischof 
I have sent out the invite.
Actually, I would like to have another committer of the project (@nicolatimeus ) to be at the call and he cannot be there before 5pm.
Is that possible to shift the meeting at 5?

Thanks.
Matteo

**Comment by stbischof** [comment]
Sure!

**Comment by MMaiero** [comment]
Thank you very much. I'll update the invite.

Thanks again for the availability

**Comment by stbischof** [comment]
Sorry, i got an conflict. I must cancel the  meeting

**Comment by MMaiero** [comment]
No problem, when do you have another slot available?
