### ISSUE TITLE
No support for systemd based systems

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#321]
Right now it seems that Kura does not support Linux distributions which are based in systemd.

This includes:
- A dependency on `libudev.so.0`
- The requirement to have a startup script named `/etc/init.d/named`

**Comment by cdealti** [comment]
And maybe more ;)

**Comment by dwoodard1** [comment]
This issue is impacting the latest Debian release for the Beaglebone Black, so it will need to be resolved in the next release.

@cdealti @ibinshtok We can add a fix to the installer as outlined in #548, but we may need to consider better support for systemd. Thoughts?

**Comment by ctron** [comment]
I would suggest not playing around with symlinks like that. A proper fix seems more appropriate.

**Comment by cdealti** [comment]
systemd support should be forthcoming ;)

**Comment by ctron** [comment]
That sounds great!

**Comment by MMaiero** [comment]
I think that @ccustine PR should have solved this. So, I would like to close it.

**Comment by ctron** [comment]
Partly. Regarding `libudev` that was just a workaround. The real fix was in commit 156998fad87a04b28a3c1c75d0c1959a0d7181e9 . However this commit only provided a fix for x64_86 and we do need updates for ARM as well.

**Comment by cdealti** [comment]
Close via #967
