### ISSUE TITLE
"New Identity Name" in Error State by Default

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3217]
If user wants to create new identity, the "new identity" field is in error state by default, because focus is on it and nothing has been entered (which is actually a valid behaviour, but the field should not be focused in the first place). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, click "New Identity"
3. Observe the identity name field - it is in error state, although nothing has been done

**Expected behavior**
Identity name should not be in error state by default. 

**Screenshot:**
![issue1](https://user-images.githubusercontent.com/15121999/101349206-4db23180-388d-11eb-99c4-846b88d45475.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
@MMaiero solved.
