### ISSUE TITLE
Possible to Create Two Identical Identities

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3218]
It is possible to create two identical identities if you add spaces after the valid name (first name is e.g. "name1 " and second one is "name1     ") - these two both get translated into "name1".  You can see below that I have created three identities with name "1". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, click "New Identity"
3. Enter "name1 " (with one space at the end)
4. Add another identity, named "name1   " (e.g. three spaces at the end)
5. Apply changes - observe the behaviour

**Expected behavior**
User should not be able to add two different user names (either this should be checkd or spaces should be a part of username). 

**Screenshot:**
![issue2](https://user-images.githubusercontent.com/15121999/101349667-f365a080-388d-11eb-9b86-c2586d7e0a64.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by code-incubus** [comment]
I've verified that this issue has been fixed within PR #3207.

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I have checked this and found out that if user enters certain number of spaces between first and last character, they all get truncated to only one space, therefore user is able to implicitly create same user multiple times:
![Screenshot 2020-12-13 at 23 50 00](https://user-images.githubusercontent.com/15121999/102026435-13b9c180-3d9e-11eb-8eb8-5e7eaf33f5ee.png)

Another problem is that the actual identity names are different (so in my case "1       1" and "1   1"), but are not propelry show in the Identities list.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
