### ISSUE TITLE
Long Identity Name not Displayed Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3219]
If user creates an identity with extremely long name (e.g. 30+ characters), it is not displayed properly (see screenshot below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, click "New Identity"
3. Add an identity with very long name (see example below) - observe the behaviour

**Expected behavior**
I suggest that identity name gets limited to some normal amount of characters (e.g. 25 or something similar). 

**Screenshot:**
![issue3](https://user-images.githubusercontent.com/15121999/101349936-62db9000-388e-11eb-9ab1-eabc01483d55.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
