### ISSUE TITLE
Wrong Title for Modal When User has no Permissions

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3220]
If you crate an identity/user without assigning permissions to it, then a modal opens up when you enter Kura with this user, wich notifies you that this user does not have any permissions. The problem here is that the title of the modal is "Warning" and the content looks erronous (although this is more Warning than an Error, or maybe even Info). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, click "New Identity"
3. Add a password to new identity, do not add any permissions. 

**Expected behavior**
I would expect for the title and the content to be of the same kind (error or warning or info). 

**Screenshot:**
![issue4](https://user-images.githubusercontent.com/15121999/101350119-b9e16500-388e-11eb-93df-71dba53b77d6.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
