### ISSUE TITLE
No Paging in Identities

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3221]
If you create more than 15 identities in Identity Service, there is no way of accessing them. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add 15+ new identities
3. Try to access those on 2nd page - you cannot. 

**Expected behavior**
I would expect to have either paging set on page or max 15 identities per device. 

**Screenshot:**
![issue5](https://user-images.githubusercontent.com/15121999/101351855-88b66400-3891-11eb-8979-b8e51ab779bc.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
