### ISSUE TITLE
Long Username Not Properly Displayed at the Top 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3222]
If you create a user with extremely long username, it is not properly displayed at the top (see GIF below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add an identity with extremely long name
3. Add password to the identity, login as this user
4. Observe name on the top  -it is not properly displayed

**Expected behavior**
Long usernames should be properly displayed. 

**Screenshot:**
![issue6](https://user-images.githubusercontent.com/15121999/101351987-bbf8f300-3891-11eb-826b-39bef8bd8e0e.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
We are going to limit the number of characters displayed to e.g. 25. For longer names we will "ellipsis" it

**Comment by MMaiero** [comment]
Closed by #3398
