### ISSUE TITLE
Apply and Reset Buttons in Identities Activated Although no Changes Made

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3224]
If you only click on the Permissions field in Identities, Apply and Reset buttons get activated. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, click on existing identity
3. Click on one of permissions - observe the Apply and Reset buttons (see GIF below)

**Expected behavior**
Apply and Reset buttons should get activated if user actually changes something. 

**Screenshot:**
![issue9](https://user-images.githubusercontent.com/15121999/101352667-ccf63400-3892-11eb-9504-3d8b9f0b5789.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
