### ISSUE TITLE
Spaces in Confirmation Modal Shown Properly, Ignored in Idnetities List

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3225]
If you create a user with name "        123        ", the spaces are properly shown when applying the changes, but not in the identities list itself (there yous ee only "123"). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add an identity "       123       "
3. Click Apply, observe the username in the confirmation box
4. After the changes are applied, observe the username in the Idnetity list

**Expected behavior**
Username should be properly displayed in both, the confirmation modal and identity list. 

**Screenshot:**
![issue10](https://user-images.githubusercontent.com/15121999/101353025-4130d780-3893-11eb-8914-1302bb9fac1e.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by code-incubus** [comment]
I've verified that this issue has been fixed within PR #3207.

**Comment by LeoNerdoG** [comment]
Closing due to upper comment.
