### ISSUE TITLE
Username with all "O" not Properly Displayed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3226]
If you create a user with only "O" (capital "O") characters, the name will not get displayed properly (see screenshot below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add an identity " OOOOO......OOOOOO" (with more than 30 Os)
3. Add a password to this user
4. Apply changes and observe the username ot being displayed properly in the modal
5. Logina s this user and observe the username at the top - it is not displayed porperly either.

**Expected behavior**
All usernames (inlcuding this with only capital "o") should always be dispalyed properly. 

**Screenshot:**
![issue11](https://user-images.githubusercontent.com/15121999/101353621-2ad74b80-3894-11eb-8769-67cae1f86a71.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
Solved with PR #3398.
