### ISSUE TITLE
All "Critical" Identities Always Shown in Confirmation Modal

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3227]
If you create several new users or if you have soem that have no permissions assigned or passwords, Kura always shwos these users in the confirmation modal, which can be very annoying for end user, if the list of "incomplete" users is long (see screenshot below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add several identities with no permissions
3. Observe the modal when applying changes. Although you change something for on user, all other users are mentione in the modal

**Expected behavior**
Should all "incomplete" users be displayed im the confirmation modal? 

**Screenshot:**
![issue11](https://user-images.githubusercontent.com/15121999/101353621-2ad74b80-3894-11eb-8769-67cae1f86a71.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
At the moment, we decided to keep all the wrong user configurations visualized for better awareness/security for the system administrators.

**Comment by MMaiero** [comment]
Closed by #3398
