### ISSUE TITLE
Idnetities Displayed Randomly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3228]
if you create several identities (even more than 15), they are randomly displayed after login/refresh.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add 15+ identities to the identities list
3. Refresh page or logout/login again and observe the identities list. 

**Expected behavior**
I suggest that users/identities are displayed in a name ascending/descending order or something similar to this and not randomly. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
