### ISSUE TITLE
Kura Does Not Stop Refreshin Page if Certain Permissions Added

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3229]
If user adds kura.admin, kura.network.admin or kura.wires permissions to a user, user is not able to use Kura normally as UI is getting refreshed constantly with error "Session Expired". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add and identity 
3. Login as newly created user when no permissions are added
4. Add kura.admin, kura.network.admin or kura.wires permissions to the newly created user
5. Refresh the page, observe the behaviour when you click on e.g. Network or Assets

**Expected behavior**
Kura should not report "session expired" and logout user if user has all the proper permissions.

**Screenshot:**
![issue14](https://user-images.githubusercontent.com/15121999/101355768-5871c400-3897-11eb-902c-d9e4a4343c85.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by code-incubus** [comment]
I've verified that this issue has been fixed within PR #3207.

**Comment by LeoNerdoG** [comment]
Closing due to upper comment.
