### ISSUE TITLE
User Able to Operate Normally Although Permissions Removed

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3230]
If you remove permissions (e.g. kura.admin) from user when he is working on other browser, nothing happens until user logs out? Is this the desired behaviour? 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add and identity, add some permissions to the identity
3. Login as newly created user
4. Remove permissions from newly created user from other browser and apply changes. 
5. Newly created user is still able to operate normally...

**Expected behavior**
See above. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Similar to https://github.com/eclipse/kura/issues/3234

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus,
I have checked this and not user gets these three notfications:
1. 
![Screenshot 2020-12-16 at 13 12 39](https://user-images.githubusercontent.com/15121999/102347218-62cf4480-3fa0-11eb-87a8-bc79f579310a.png)

2. 
![Screenshot 2020-12-16 at 13 11 35](https://user-images.githubusercontent.com/15121999/102347226-65ca3500-3fa0-11eb-8795-785f941a76a5.png)

3. 
![Screenshot 2020-12-16 at 13 11 39](https://user-images.githubusercontent.com/15121999/102347232-682c8f00-3fa0-11eb-9f3f-d0d787f894d6.png)

I would just like to check if the transition from 2 to 3 is OK - I mean in this particular case user does not get logged out, although Kura has stated that Session has expired? Can you please check this?

**Comment by LeoNerdoG** [comment]
Hey @nicolatimeus, I have checked the fix in PR #3256 and I can see that the second modal has been changed to "The current identity is not allowed to perform the requested operation." which is OK, but the title of the modal is "Warning" instead of "Error" and the same goes for the third modal ("The curret user has no permissions") - can you please fix the modal's titles?
