### ISSUE TITLE
"Define new password" in Error State Although Nothing Entered

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3231]
If user wants to add a password to an identity, the "Define new password" field is in error state (and confirm password in the next modal also), although nothing has been entered. This is becasue the focus is on the empty field. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add a password to the user
3. Observe the Password/confirm password modals when they open - fields are by default in error state.

**Expected behavior**
Focus should not be on Password field when user is adding a password/confirming password,  becasue otherwise the field is by default in error state, which is not OK. 

**Screenshot:**
![issue 16](https://user-images.githubusercontent.com/15121999/101356282-1c8b2e80-3898-11eb-9856-d9e26e821855.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
@MMaiero solved in new Kura version

**Comment by MMaiero** [comment]
Thanks. Closing then. @LeoNerdoG please feel free to reopen it if needed
