### ISSUE TITLE
User Unable to see Packages, Regardless of kura.packages.admin Permission

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3232]
Although user has kura.packages.admin permission, he is not able to see the packages (see screenshot below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add a user and a password to it (do not add kura.packages.admin permission just yet)
3. In second browser login as newly created user
4. In first user add kura.packages.admin permission
5. In second browser refresh page - observe the error. 

**Expected behavior**
User should be able to see packages, if kura.packages.admin permission set. 

**Screenshot:**
![issue18](https://user-images.githubusercontent.com/15121999/101356564-8acff100-3898-11eb-99d8-075314d755e4.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by marcellorinaldo** [comment]
@MMaiero solved in new Kura version

**Comment by MMaiero** [comment]
Thanks. Closing then. @LeoNerdoG please feel free to reopen it if needed
