### ISSUE TITLE
Syntax Error in Permission Section in Identities

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3233]
There is a syntax error in Permission description in Identities. It should be "Assign or revoke permissions to the selected identity." instead of "Assign or revoke permission to the selected identity.". 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add a user with password
3. Add kura.packages.admin permission to the user, login as this user
4. Go to packages, observe the error message

**Expected behavior**
See above. 

**Screenshot:**
![issue19](https://user-images.githubusercontent.com/15121999/101356917-0a5dc000-3899-11eb-9e57-16a4cdebb3ae.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by code-incubus** [comment]
I've verified that this issue has been fixed within PR #3207.

**Comment by LeoNerdoG** [comment]
Closing due to upper comment.
