### ISSUE TITLE
"Session Expired" if User Click Apply Before Confirmin Password for New User

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3235]
If you click Apply before entering confirmation password into the confirmation Box, you have not only to refresh page, but reboot the device, becasue Kura is not responsive anymore. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to identities, add a user
3. Add another user, but this time add a password for the second user
4. Right before the secon modal for "confirm password" appears, click "Apply" - observe the behaviour 

**Expected behavior**
"Password" and "Confirm Password" should be in the same modal, that way user cannot click Apply before entering confirmation password. 

**Screenshot:**
![issue21](https://user-images.githubusercontent.com/15121999/101357646-05e5d700-389a-11eb-898b-a54e86bb6bbf.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closing for now. @LeoNerdoG can you confirm?

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved. 
Now the "confirm" modal is not a sepparate modal, so it is impossible to click Apply between the two modals.
