### ISSUE TITLE
Connect/Disconnect Button Not Working in Cloud Connection Service 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3236]
If you create a user with only kura.cloud.connection.admin permission, the Connect/Disconnect button does not work when you enter all the necessary parameters. You get a "Session expired" error instead (see screeenshot below). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Identities, add a user with kura.cloud.connection.admin permission (e.g. user1)
3. Login as user1, enter all the necessary (VALID!) parameters for a cloud connection
4. Click Connect/Disconnect - observe the behaviour. 

**Expected behavior**
Kura should connect the device to the cloud without showing error "Session expired". 

**Screenshot:**
![issue5](https://user-images.githubusercontent.com/15121999/101491400-f9c64c00-3963-11eb-9a50-5144bc14e132.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3207**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closing for now. @LeoNerdoG can you confirm?

**Comment by LeoNerdoG** [comment]
Hey @MMaiero I am confirming that this issue has been resolved. 
I tried with my local instance of Kapua and the connection was sucessfull in first try.
