### ISSUE TITLE
Generic Error When Trying to Create a Non-unique Cloud Connection

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3239]
If user is trying to create a Cloud Connection with a non-unique name, Kura throws a generic error instead one with a detailed message. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Cloud Connections, create a new cloud connection(e.g. "org.eclipse.kura.cloud.CloudService-1")
3. Try to add another "org.eclipse.kura.cloud.CloudService-1" cloud connection - observe the error. 

**Expected behavior**
Kura's message should be more detailed. 

**Screenshot:**
![issue17](https://user-images.githubusercontent.com/15121999/101478941-b2cf5b00-3951-11eb-85aa-263fdffc74f9.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: latest develop branch**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
Added an unique-value validator. Fixed
