### ISSUE TITLE
Warning Instead Error When Creating a Driver Without Factory

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3240]
If user is trying to create a driver without seelcting a factory, Kura throws a Warning modal, which actually contains an error style message. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Drivers and Assets tab, click Add, add a driver name
3. Without selecting a factory, press Submit - observe the error

**Expected behavior**
Modal's title should be "Error" or the whole modal should be in warning-like style. 

**Screenshot:**
![issue1](https://user-images.githubusercontent.com/15121999/101478814-8adff780-3951-11eb-960e-d676fa1b02c9.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: latest develop branch**_

**Additional context**
/

**Comment by daodol** [comment]
kura 5.4.2 This issue still exists
os:mint linux 21
