### ISSUE TITLE
Cog Position Dependant on the Initial Browser Size

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3241]
This is not a fatal issue, but I have noticed it, so I am reporting it, before I forget. 
If the browser window is very small before user logs into Kura and after login enlarges it, the cog position is in the same spot as before. A simple refresh fixes this, so there is a workaround, but is there a way to fix this without user having to refresh the UI? 

**Testflow:**
1. Resize the browser window 
2. Login to Kura as admin/admin
3. Enlarge the browser window
4. Navigate through some services, observe the cog placement

**Expected behavior**
Position of the cog should be handled according to the current browser window size. 

**Screenshot:**
![issue1](https://user-images.githubusercontent.com/15121999/101600008-02b62c80-39fb-11eb-911f-fdbcdd6f7b29.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: latest develop branch**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
