### ISSUE TITLE
Files Always Uploaded in /tmp Folder

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3242]
If you upload a file to Kura, it is always put into /tmp folder, and not to the updated destination (e.g. /home/pi or something else). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Command Service, enable it
3. Change the "Command working directory" to e.g. /home/pi
4. Go to Device -> Command service, upload a .sh or some other file
5. Execute command "ls -l" and observe that uploaded file is not in this path
6. Check the /tmp and see that the uploaded file is there

**Expected behavior**
If user changes the Command Working Directory, all uploaded files should ne put there? 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: latest develop branch**_

**Additional context**
/

**Comment by MMaiero** [comment]
This has been closed by Alessandro with PR https://github.com/eclipse/kura/pull/3285

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been resolved.
