### ISSUE TITLE
Kura device Bundles

### ISSUE THREAD

**Issue by funnyboys1008** [eclipse/kura#3252]
Hi,

I was working on kura, just out of curiosity  i wanted to know how the bundles on kura device sent to kapua. Like are these bundles published on some mqtt topic and then displayed on the kapua console ? or is there any other way.It would be great if you could refer to me some code files where all this is going on.

**Comment by MMaiero** [comment]
Hi,
please have a look here: https://eclipse.github.io/kura/ref/mqtt-namespace.html

**Comment by MMaiero** [comment]
Hi @funnyboys1008,
can this be closed?
