### ISSUE TITLE
Number of Spaces in Username not Shown Correctly 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3257]
If user adds a user with username "1 1 1 1 1         1", the username is shown as "1 1 1 1 1 1" in upper right menut (when logged in as this user), in confirmation box when appying configuration in Certificates (screenshot No. 2) and when second user strips permission from this user (screenshot No. 2)

**Testflow:**
1. Login to kura as admin/admin
2. Go to Identities, click Add
3. Add user with name "1 1 1 1         1"
4. Observe the useranem when you login with this user (upper right corner)
5. Observe username when you add some permissions to the user (everything truncated to 1 space)
6. Observe the username when second user revokes permission from this user (again truncated to 1 space)

**Expected behavior**
Username should be always correctly shown. 

**Screenshot No. 1:**
![issueKUra5](https://user-images.githubusercontent.com/15121999/104010231-7a1edd80-51ac-11eb-8db9-6b11872eb758.png)

**Screenshot No. 2:**
![Screenshot 2021-01-08 at 11 29 29](https://user-images.githubusercontent.com/15121999/104010251-8145eb80-51ac-11eb-97ba-59928058da1c.png)

**Screenshot No. 3.**
![issueKura5-1](https://user-images.githubusercontent.com/15121999/104010367-acc8d600-51ac-11eb-9d91-82f969c5aa59.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by MMaiero** [comment]
Closed by #3398
