### ISSUE TITLE
Pressing Backspace in Certificate Fields Puts Them in Error State

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3258]
If user presses backspace key on keyboard when entering "alias", "server certificate" or "Client certificate", then the field gets into error state (see screenshot below). 

**Testflow:**
1. Login to kura as admin/admin
2. Go to Certificates, click Add
3. Select one of the certificates and select "alias" field
4. Press "backspace" key on the keyboard
5. Observe how field gets into error state, although nothing has been deleted

**Expected behavior**
If user presses backspace in an empty field, it should get into error state. 

**Screenshot:**
![Screenshot 2021-01-08 at 08 37 29](https://user-images.githubusercontent.com/15121999/104007882-ef88af00-51a8-11eb-96dc-19ba2e07ce4f.png)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
I would not change this, when the user presses backspace he aims to modify the value so trigger the validation is a right behaviour.

**Comment by MMaiero** [comment]
Thanks @salvatore-coppola for checking. @LeoNerdoG I agree with Salvatore's comment. I'm going to close this issue but feel free to reopen it if needed.
