### ISSUE TITLE
Second Field in Error State if User Too Fast

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3259]
If user clicks on the second empty field in certificates too fast (before "Apply" button gets activated), the second field is set into error state, although nothing has been entered. See GIF below. 

**Testflow:**
1. Login to kura as admin/admin
2. Go to Certificates, click Add
3. Select one of the certificates and select "alias" field
4. Hoover with mouse above second field (e.g. "Server certificate")
5. Immediatelly after entering e.g. "1" into the Alias field, click on the second field
6. Observe the result

**Expected behavior**
If field is empty, it should not be put into error state (I guess it should be put into error state after you change focus and is still empty, but not before?).

**Screenshot:**
![issueKura2](https://user-images.githubusercontent.com/15121999/104008374-a71dc100-51a9-11eb-93bb-4b3268637581.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
fixed

**Comment by MMaiero** [comment]
Thanks @salvatore-coppola for checking. @LeoNerdoG I'm going to close this issue but feel free to reopen it if needed.
