### ISSUE TITLE
org.eclipse.kura.web2 is missing about.html

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#326]
The project `org.eclipse.kura.web2`is missing the required `about.html` file.

Since there seem to be some icon resources in the project, this has to be explicitly mentioned in the "Third Party Content" section.

**Comment by dwoodard1** [comment]
Which icon resources are you referring to? I believe all the icons/images (except Kura logo) come from the bootstrap js/css. Are you seeing something different?

**Comment by ctron** [comment]
The files under org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/resources/icons

**Comment by ctron** [comment]
That is fine if they come from bootstrap. But still external dependencies have to be named in the `about.html`

**Comment by ctron** [comment]
Also see https://www.eclipse.org/legal/epl/about.php

**Comment by dwoodard1** [comment]
@ctron I forgot about the icons directory. Those do not come from bootstrap and I am not sure they are needed.

@MMaiero Can we get rid of these icons? My quick search shows we are only using two (for connection status). Seems like a lot of icons to only be using two.

**Comment by MMaiero** [comment]
@dwoodard1 Yes, I think we can remove them
