### ISSUE TITLE
Certificates Fields in Error State Although not Empty if User too Fast

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3260]
If user is too fast when selecting other fields when adding certificates, this can result in Kura marking a valid field as invalid (see screenshot below). For more information please see testflow below. 

**Testflow:**
1. Login to kura as admin/admin
2. Go to Certificates, click Add
3. Select one of the certificates and select "alias" field
4. Enter "1" and then populate other fields with valid paramters
5. Go to Alias and delete "1", click somewhere outside
6. Observe the field in error state - this is OK
7. Focus on "Alias" field, but hoover on another field with mouse
8. In exact moment when you enter "1", press/focus on other field
9. Observe how Alias field stays in error state, although properly populated

**Expected behavior**
Field should not be in error statae, if paramters valid. 

**Screenshot:**
![123123](https://user-images.githubusercontent.com/15121999/104009207-f0224500-51aa-11eb-95d4-9a9bfec896d1.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
fixed

**Comment by MMaiero** [comment]
Thanks @salvatore-coppola for checking. @LeoNerdoG I'm going to close this issue but feel free to reopen it if needed.
