### ISSUE TITLE
Possible to add Certificates With Erronous Fields

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3261]
If user is able to put one of the fields in error state, although parameters are entered (see issue #3260), the certificate can be added, but Kura reports an error and the modal disappears.
This behaviour is somwhere between adding a normal certificate (with valid parameters) and between adding an invalid certificate (when "dropdown" modal is shown). 

**Testflow:**
1. Login to kura as admin/admin
2. Go to Certificates, click Add
3. Select one of the certificates and select "alias" field
4. Enter "1" and then populate other fields with valid paramters
5. Go to Alias and delete "1", click somewhere outside
6. Observe the field in error state - this is OK
7. Focus on "Alias" field, but hoover on another field with mouse
8. In exact moment when you enter "1", press/focus on other field
9. Observe how Alias field stays in error state, although properly populated
10. Press Apply - observe the behaviour

**Expected behavior**
User should not be able to add certificates which fields are invalid, but also the validation itself should be done properly. 

**Screenshot:**
![234234](https://user-images.githubusercontent.com/15121999/104010073-4348c780-51ac-11eb-97ee-4fd7861a0bf0.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
fixed

**Comment by MMaiero** [comment]
Thanks @salvatore-coppola for checking. @LeoNerdoG I'm going to close this issue but feel free to reopen it if needed.
