### ISSUE TITLE
Modal in Certificates not Wide Enough

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3262]
If you open "Add certificate" modal, you will see, that it is not wide enough (there are some words that are "in the way" of the scrollbar"). This is only a minor issue, but should be addressed nontheless. 

**Testflow:**
1. Login to kura as admin/admin
2. Go to Certificates, click Add
3. Try to resize the three windows (alias, server certificate, user certificate), so that the scrollbar disappears
4. Observe the behaviour

**Expected behavior**
Modal for adding certificates should be wide enough.

**Screenshot:**
![123](https://user-images.githubusercontent.com/15121999/104015672-42686380-51b5-11eb-9214-ae2a7ede29bc.gif)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: develop**_

**Additional context**
/

**Comment by salvatore-coppola** [comment]
fixed
