### ISSUE TITLE
Web Console Tab | Missing "unsaved warning" dialog when switching tabs

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3263]
**To Reproduce**
1. Go to Security Item
2. Click on Web Console tab
3. Change some field (e.g. value for "Web Server Entry Point")
4. Click on some other tab (Http Service) or some other Item (Command Service Item)

**Expected behavior**
There should pop up warning with message: "There are unsaved changes. Do you want to discard them and continue?"

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

**Additional context**
This is regression issue.

**Comment by LeoNerdoG** [comment]
I have verified that this has been resolved in latest develop branch.
