### ISSUE TITLE
Problem after network configuration change

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3268]
**Describe the bug**
After network configuration change on Kura Im unable to ping outside (google.com) until device reboot

**To Reproduce**
1. Go to Network and disable eth1 
2. Enable eth1 for WAN
3. Try to ping google.com
4. Not able -> Workaround: reboot the device

**Expected behavior**
I should be able to ping outside (after network configuration change) without rebooting device 

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

**Additional context**
logs attached 
[snapshots.tar.gz](https://github.com/eclipse/kura/files/5813354/snapshots.tar.gz)
[kura.log](https://github.com/eclipse/kura/files/5813355/kura.log)

**Comment by pierantoniomerlino** [comment]
@mstankovic Is it a RPi3 with a USB dongle that provides eth1? The eth1 interface get an address from the DHCP server?
Finally, could you please send me the unencrypted last snapshots? You can download it from the Web Console.

Thanks!

**Comment by mstankovic** [comment]
@pierantoniomerlino Im using rpi3 in a small fixture. Eth1 gets address from DHCP server. Im using USB to ETH adapter for eth1.


[snapshot_1610557118168.zip](https://github.com/eclipse/kura/files/5813479/snapshot_1610557118168.zip)

**Comment by pierantoniomerlino** [comment]
Thanks @mstankovic! From the snapshot it seems that the eth1 interface is configured as LAN:

```
            <esf:property array="false" encrypted="false" name="net.interface.eth1.config.ip4.status" type="String">
                <esf:value>netIPv4StatusEnabledLAN</esf:value>
            </esf:property>
```

Could you please re-run the test and sent me the logs again? Proceed as described above, so:

1. Go to Network and disable eth1
2. Enable eth1 for WAN
3. Try to ping google.com

**Comment by mstankovic** [comment]
Hey @pierantoniomerlino i was wrong eth0 is the interface for WAN.

I repeated the test and reproducing issue.
1. disable eth0
2. enable eth0 for WAN
3. ping google.com


[snapshot_1610619440788.zip](https://github.com/eclipse/kura/files/5813776/snapshot_1610619440788.zip)
[cosole_log.txt](https://github.com/eclipse/kura/files/5813777/cosole_log.txt)
[kura.log](https://github.com/eclipse/kura/files/5813780/kura.log)

**Comment by pierantoniomerlino** [comment]
It seems that this rule

```
-A postrouting-kura -o eth1 -j MASQUERADE
```

is not correctly applied, even if it written on the `/etc/sysconfig/iptables` file.

**Comment by pierantoniomerlino** [comment]
@mstankovic Could you please test the fixes in the draft PR?

**Comment by mstankovic** [comment]
@pierantoniomerlino still reproducing..
kura.log and the latest snapshot attached
[kura.log](https://github.com/eclipse/kura/files/5815102/kura.log)
[snapshot_1610635327538.zip](https://github.com/eclipse/kura/files/5815103/snapshot_1610635327538.zip)
