### ISSUE TITLE
API Driver Interface has wrong property name

### ISSUE THREAD

**Issue by ashmookler1** [eclipse/kura#3275]
**Describe the bug**
The Kura API Driver Interface has a field called DRIVER_PID_PROPERTY_NAME that is currently set to "driver.pid". This property doesn't exist in the drivers and throws an exception whenever it is used. The correct property name is "kura.service.pid".

**To Reproduce**
1. Attempt to run any function that relies on DRIVER_PID_PROPERTY_NAME. For example, DriverService.getDriverPid(Driver driver). 
2. An exception will be thrown because the property "driver.pid" doesn't exist. 

**Expected behavior**
DRIVER_PID_PROPERTY_NAME should have the correct property name for the driver PID, which is "kura.service.pid". This would allow any function that uses DRIVER_PID_PROPERTY_NAME to work correctly (for example, allowing getDriverPid to return the driver PID instead of throwing an exception). 

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Board: Any (I am using a Eurotech Reliagate 10-12, but this bug isn't hardware specific)
 - OS version: Any (I am using Linux reliagate-10-12 4.9.216-eurotech-ti #1 Wed Jun 3 11:35:11 UTC 2020 armv7l armv7l armv7l GNU/Linux, but this bug isn't OS specific)
 - Additional info: 

**Additional context**
N/A

**Comment by nicolatimeus** [comment]
Yes, I don't think that any of the drivers in Kura codebase sets the `driver.pid` property as you reported. The drivers are identified by the `kura.service.pid` property just like other Kura `ConfigurableComponents`.
A property named `driver.pid` is used in `Asset` configuration and is set to the `kura.service.pid` of the attached Driver, but that is a different topic.

The `DriverService` implementation [1] seems to be affected also by other issues like leaking references to the Driver instances after calling `BundleContext.ungetService()` on the corresponding `ServiceReference`s.

I don't think that the `DriverService` is used anywhere inside Kura codebase, it looks like a utility service whose functionality can be easily replicated with plain OSGi/Declarative Service APIs without much effort, I wonder if we should deprecate it.

[1] https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.driver.helper.provider/src/main/java/org/eclipse/kura/internal/driver/DriverServiceImpl.java

**Comment by MMaiero** [comment]
@nicolatimeus Can we proceed with the deprecation?

**Comment by MMaiero** [comment]
@nicolatimeus ping

**Comment by nicolatimeus** [comment]
Yes, maybe we can deprecate the `DriverService`.

**Comment by MMaiero** [comment]
Agreed. Can we make a PR with that? We need to update also the release notes.

**Comment by MMaiero** [comment]
Closing as `DriverService` has been deprecated
