### ISSUE TITLE
Setting Maven compiler settings to Java 7

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#330]
As described in the Eclipse Wiki [1] Kura has a dependency on Java 7.

However the maven compiler settings are still at Java 6.

I would like to raise this to Java 7 for Kura 2.0.

[1] https://wiki.eclipse.org/Kura/Getting_Started#Java

**Comment by cdealti** [comment]
@ctron see my comment to #327

**Comment by ctron** [comment]
Maybe I do continue here ...

So what is the reason for that sticking with source level compatibility on 1.6?

Since this would mean that I can switch to EE 7, but cannot use "try-with-resources"?

**Comment by cdealti** [comment]
Exactly

**Comment by ctron** [comment]
I don't see any reason at all. The other way round, maybe.

So let's do it of nobody objects with a real reason.

**Comment by hekonsek** [comment]
Actually even Camel requires Java 1.7 to work. :) It will be nice to upgrade to Java 7. 

Anybody has something against upgrading JDK to 1.7 for Kura 2.0? @kartben @mcarrer @dwoodard1 ?

**Comment by cdealti** [comment]
For the build we use Tycho. If I change the plugin configuration in ``manifest_pom.xml`` to compile Java 7 code:

```
                        <plugin>
                                <groupId>org.eclipse.tycho</groupId>
                                <artifactId>tycho-compiler-plugin</artifactId>
                                <version>${tycho-version}</version>
                                <configuration>
                                        <source>1.7</source>
                                        <target>1.6</target>
                                        <compilerArgument>-warn:[+|-]warning_tokens_separated_by_comma</compilerArgument>
                                        <!-- <compilerArgument>-err:-forbidden</compilerArgument> -->
                                        <!-- <useJDK>BREE</useJDK> -->
                                </configuration>
                        </plugin>
```

I get:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.20.0:compile (default-compile) on project org.eclipse.kura.api: Fatal error compiling: Target level '1.6' is incompatible with source level '1.7'. A target level '1.7' or better is required -> [Help 1]
```

Our industrial grade gateways all ship Oracle Java SE Embedded 7 and 8 so we could set both ``source`` and ``target`` to 1.7.

I cannot exclude however that there aren't gateways in the field with a Java 6 VM and/or if Kura can still run on a Java 6 VM.

**Comment by ctron** [comment]
I agree both source and target level should be the same.

Currently Kura states it requires Java 7, the Web UI 2 and Camel will only run on Java 7. So as of now, Kura 2.0.0 cannot run on Java 6 anymore.

So what is the strategy for Java compatibility then? Or the roadmap? Can we agree that for Kura 2.1.0 we start going with Java 7?

**Comment by cdealti** [comment]
Just set 1.7 where you really need it (Camel) for the time being.

**Comment by hekonsek** [comment]
I'm closing the PR then, as we apparently need to stick as many Kura elements to Kura 1.6 as we can :( . The reason here would be the possible customer constrains.
