### ISSUE TITLE
Firewall settings not saved in the file system after network configuration change

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#3323]
**Describe the bug**
When changing the network configuration, the firewall rules are not permanently saved to /etc/sysconfig/iptables. Therefore upon the next reboot the gateway is not accessible anymore.

**To Reproduce**
1. Start from a default network configuration Eth0 => WAN DHCP client, wlan0 LAN DHCP server.
2. Access to the gateway works (https/ssh/...). Routing LAN to WAN is working
3. Configure ppp0 as WAN, Eth0 LAN DHCP client, Wlan0 LAN DHCP server
4. Access to the gateway works (https/ssh/...). Routing LAN to WAN is working
5. Here we verify /etc/sysconfig/iptables and we can see that the firewall configuration is not saved
6. reboot
7. After reboot, the gateway starts normally and we can verify that from the console but no remote access possible

*Applying /usr/sbin/iptables-save before the reboot solve the issue*

**Expected behavior**
Same behavior after reboot.

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - Board NXP i.MX6
 - OS version: Linux BS184300123 5.4.47-imx6-sr #1 SMP Mon Feb 15 22:07:42 UTC 2021 armv7l armv7l armv7l GNU/Linux
 - Additional info: 

**Additional context**

**Comment by pierantoniomerlino** [comment]
I follow the sequence of commands reported in the issue and I found that indeed `/etc/sysconfig/iptables` is not updated with all the needed rules. After a reboot, it is possible to access to the web console but the ip forwarding rules between wlan and ppp is gone. **Maybe** this is related to #1195.

**Comment by pierantoniomerlino** [comment]
This issue is not directly related to #1195, but it is due to a bug on the `LinuxFirewall`.

**Comment by pierantoniomerlino** [comment]
@sterwen I tried to fix this issue in #3334. Could you please test it on your device?

**Comment by sterwen** [comment]
Hello,

Tested and the correction is OK.
