### ISSUE TITLE
Unprivileged Command Service with 'su' invocation must be run from a terminal

### ISSUE THREAD

**Issue by malveo** [eclipse/kura#3332]
**Describe the bug**

Running command with  Command Service in Unprivileged mode return `su: must be run from a terminal`

**To Reproduce**

1. Go to 'Device' > 'Command'
2. Execute any command for example: 'id'
3. Return: 'su: must be run from a terminal'

**Expected behavior**
Executing command, returning command output.

**Screenshots**

![image](https://user-images.githubusercontent.com/6190864/111826955-998f6080-88e9-11eb-9970-767bb7f48104.png)

**Comment by pierantoniomerlino** [comment]
Hi @malveo, have you tried with the last build of develop branch? Which device are you using?

**Comment by MMaiero** [comment]
@malveo Any update on this? Can it be closed?

**Comment by malveo** [comment]
Hi @MMaiero @pierantoniomerlino,

built today from develop branch the problem does not occur.

Thank you!
