### ISSUE TITLE
[Wires] CQ for Kura Wires API and core bundle 

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#335]
# c10n

Name:           c10n
Version:        1.2
Description:    C10N (Cosmopolinat) is a Java library, focused on making
internationalisation more modular, easier to evolve and maintain,
robust-to-change and IDE-friendly without excess of external tools.

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11675

@amitjoy FYI

**Comment by cdealti** [comment]
@LucaDazi can you confirm the [above CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11675) is the only one required by #360?

If so, can we close this?

**Comment by MMaiero** [comment]
@amitjoy Can we close this?

**Comment by amitjoy** [comment]
Yes


Amit Kumar Mondal
Phone: +49 176 8081 5427 Email: admin@amitinside.com(mailto:admin@amitinside.com)  
Skype: arsenalnerk GitHub: a(http://blog.amitinside.com/)mitjoy
Blog: blog.amitinside.com(http://www.amitinside.com/)
