### ISSUE TITLE
Iptables config rules for environment with ro rootfs

### ISSUE THREAD

**Issue by malveo** [eclipse/kura#3361]
Hello Folks,

For environments with the rootfs in read-only mode is preferred to make FIREWALL_CONFIG_FILE_NAME 

https://github.com/eclipse/kura/blob/0d50f11782caf39c01249ea4ed4535323cb2762c/kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfigConstants.java#L17

configurable via Kura properties file.

Thank you!

**Comment by MMaiero** [comment]
Hi @malveo 
are you willing to submit a PR with the needed changes?

Thanks.
Matteo
