### ISSUE TITLE
Failed to connect to any of the matching endpoints

### ISSUE THREAD

**Issue by MichalS-94** [eclipse/kura#3365]
Hi,
I have a problem with connection OPC Server simulator to the OPC Driver. I did everything like in this tutorial "https://eclipse.github.io/kura/wires/kura-wires-opcua.html" and when im trying to see Data in Asset I get this error:
![image](https://user-images.githubusercontent.com/64809601/117175462-2d03ee80-adcf-11eb-913f-1bbe34a54f65.png)

I checked IP (localhost) and the port number (1234) and its the same as this one in tutorial.
Anybody knows how to connect this endpoints?

**Comment by MMaiero** [comment]
Hi,
did you try to perform a telnet to the server/port to see if a service is actually running and listening for connections?

**Comment by MichalS-94** [comment]
![image](https://user-images.githubusercontent.com/64809601/117303434-f84e7080-ae7c-11eb-8933-1e63b72e1cbf.png)

I checked it and the server simulator port is listening

**Comment by MMaiero** [comment]
Can you show the configuration you have set for the asset?

**Comment by MichalS-94** [comment]
![image](https://user-images.githubusercontent.com/64809601/117305389-000f1480-ae7f-11eb-91dd-7eb186aba11b.png)

Here is my configuration for asset

**Comment by MMaiero** [comment]
Can you also add the config for the corresponding driver?

**Comment by MichalS-94** [comment]
Below config for the driver:

Endpoint IP: localhost
Endpoint port: 1234
Server Name: <empty>
Force endpoint URL: false
Session timeout: 120
Request timeout: 60
Acknowledge timeout: 40
Application name: opc-ua client
Application URI: urn:kura:opcua:client
Subscription publish interval: 1000
Keystore path: PFX or JKS Keystore
Security policy: None
Username: user123
Password: Kapu@12345678
Client certificate alias: client-ai
Enable server authentication: false
Keystore type: PKCS12
Keystore password: default
Max request items: 200
Subtree subscription events channel name format: BROWSE_PATH

**Comment by MichalS-94** [comment]
I removed the container with Kura and did the tutorial again and everything is working now. I don't know where I went wrong the first time.
