### ISSUE TITLE
Simple Artemis MQTT Broker - Subscriber

### ISSUE THREAD

**Issue by MichalS-94** [eclipse/kura#3369]
Hi,
I have a problem with subscribing data from Artemis broker. I connected the broker via Cloud Connections and created a subscriber. Next step I made a simple wire graph with subscriber and logger but its not working. Anybody knows how to properly subscribe from broker? Below are screenshots of subscriber configuration and python publisher code.
![image](https://user-images.githubusercontent.com/64809601/117627581-99d50b00-b178-11eb-91a9-b7d5f138ef52.png)

![image](https://user-images.githubusercontent.com/64809601/117627919-e4ef1e00-b178-11eb-9d7f-16c2017cd805.png)

![image](https://user-images.githubusercontent.com/64809601/117627715-bbce8d80-b178-11eb-8a82-e7467562de92.png)

![image](https://user-images.githubusercontent.com/64809601/117627779-ca1ca980-b178-11eb-8172-4b69d51b863c.png)

PS: I wrote a simple subscriber to check if the broker works and everything is fine with the broker so I think the problem is with the subscriber in Kura.

**Comment by MMaiero** [comment]
Hello,
any additional details on this issue?

Thanks
Matteo
