### ISSUE TITLE
Filed to install deployment package - Apache Camel

### ISSUE THREAD

**Issue by MichalS-94** [eclipse/kura#3384]
Hi,
I have problem with installing packages from Eclipse Marketplace. I'm trying to install below packages:
-Apache Camel MQTT endpoint
-Apache Camel Groovy language support
-Apache Camel GSON data format

and for each i have the same error:
![image](https://user-images.githubusercontent.com/64809601/119305171-a8d3b700-bc68-11eb-85a8-7205895c2a49.png)

Anybody knows is there any way to install this packages?

**Comment by MMaiero** [comment]
Kura accepts only OSGi deployment packages. If the packages you are trying to install are not .dp files, you will not be able to install them.
The kura.log file could also provide you with more details on what happened.

**Comment by MichalS-94** [comment]
Thank you for your response.
The package im trying to install is .dp file but in logs I found an HTTP response code 501. 
![image](https://user-images.githubusercontent.com/64809601/119324502-3242b380-bc80-11eb-961b-dede3f10951f.png)

Do you know how can I fix it?

**Comment by MMaiero** [comment]
it may be due to the fact that maven since some months access only https connections

**Comment by MMaiero** [comment]
@MichalS-94 Can this be closed?

**Comment by MichalS-94** [comment]
Yes, Thank you.
