### ISSUE TITLE
kura4.1.2安装de.dentrassi.camel.utgard-0.2.0，不能正常使用，依赖过时。

### ISSUE THREAD

**Issue by zhanghenglang** [eclipse/kura#3386]
After installing de.dentrassi.camel.utgard-0.2.0 on kura 4.x.y, it cannot be used normally because of the obsolescence of the dependency. How should this problem be solved?

**Comment by zhanghenglang** [comment]
Are there any good thoughts and ideas when using the opcda driver on kura4.x.y? Can the dependencies of opcda be used normally on kura4.x.y?

**Comment by MMaiero** [comment]
The component you are looking for has been provided/supported by a single developer not by this project. I believe you should try to reach out the contributor of the bundle and see if there can be an update.
