### ISSUE TITLE
[KEYS-V1] - POST/keystore/entries/csr response format problems.

### ISSUE THREAD

**Issue by Coduz** [eclipse/kura#3387]
**Describe the bug**
When performing a request to Kura to `POST/keystores/entries/csr` the request is processed corretly but the format of the response not consistent with the other resources response (i.e. : `GET/keystores/entries`) and it has some unwanted `"` in it.

**To Reproduce**
1. Make a resquest to Kura via MQTT at: `POST/keystores/entries/csr` with a correct request.
2. Take a look at the response. The response is encoded in the body

>"-----BEGIN CERTIFICATE REQUEST-----\nMIICgTCCAWkCAQAwPDELMAkGA1UEBhMCVVMxEDAOBgNVBAoTB0VjbGlwc2UxDDAK\nBgNVBAsTA0lvVDENMAsGA1UEAxMES3VyYTCCASIwDQYJKoZIhvcNAQEBBQADggEP\nADCCAQoCggEBAJxPiEF4xzpclKwG1IFkRTvI2QM3ui3Ns9Ixi1Z7KP0T+AkduD8t\npZ2rxI12wnq2aB0EGaptuHA4OFit2o7/KSgnOVtSEPWbbeA67EV+vR6jxxaoxZje\nNbqcy8rhu6aAP9s5R15vGCVbHCCuSvGe0aasCjgxpdno8A+ir6tiLB+H0ShpjAly\nezgJwQbX9QTphHGzzSyfB2jitewpwm+yJgH+lEG8OQPYGjzjOYrfnDBQj7dQqgjB\nmAUJx7poJsCsCy0ZYMwBdue1Nm10Was3mBOIxUm5kOT2RWebqyLspYFOSZSReW3P\nqU9T8p2IaCvnlVbm/YuM8OMZtACMw7n3hF0CAwEAAaAAMA0GCSqGSIb3DQEBCwUA\nA4IBAQB/OEEhmHZnvHS0at9WohHDriyxjQrHXaJyjZX5WtrEOgTxG2toL+FdrS1L\nxs0FGrwgQZA+ITw0cX5sG/IQEwpo34HeHyY4w+DLXaD7QYnutYlc27tUniY1EaLO\nyYJ2xhegem+WWMTDAQU89lTWEQZZv7p+RAspkL+fBCP1LPWQF93Jm58XeYE3p9HF\nIit45TDD2XG8OhO/9nks3yPtf71W72RaALRBIQTN85nf+6PHM8RZg00Y/2y3uVcF\ngGnxgt3c0sComUybH9SPcadTnGqcWvmo+9RPecpFzY+0XYGkFWtwWqd0XyRsI4dz\nC2nnE0ndz01z5/ryWMbEWvOsuuB3\n-----END CERTIFICATE REQUEST-----\n"

As you can see the response body is a String instead of a Json object, and it contains `"` at the beginning and at the end. 
Also the `\n` aren't in form of a new-line and therefore any user that receives this body must do the following:

```
 String kuraSignedCertificate = new String(kuraResponsePayload.getBody());
 kuraSignedCertificate = kuraSignedCertificate.replace("\"", "");
 kuraSignedCertificate = kuraSignedCertificate.replace("\\n", "\n");
``` 

to be able to process the certificate.

As comparison the certificate returned by `GET/keystores/entries/entry` does not have these problems.

**Expected behavior**
It would be nice to have a response as a JSON format like the others, without any unwanted chars and with properly formatted new-lines.

Kapua tries first to read the bodys the below format, and fallbacks to try to read it as a String.

```
{
    "signingRequest": "[...]"
}
```

**Screenshots**
_None_

**Target Environment (please complete the following information):**
N/A

**Additional context**
I'm implementing Kapua support for KEYS-V1 request handler! 
Kapua PR: https://github.com/eclipse/kapua/pull/3315

**Comment by salvatore-coppola** [comment]
I modified the rest api to return the following json text, @Coduz is this ok ?

```json
{
    "signingRequest": "-----BEGIN CERTIFICATE REQUEST-----\nMIICgTCCAWkCAQAwPDELMAkGA1UEBhMCVVMxEDAOBgNVBAoTB0VjbGlwc2UxDDAK\nBgNVBAsTA0lvVDENMAsGA1UEAxMES3VyYTCCASIwDQYJKoZIhvcNAQEBBQADggEP\nADCCAQoCggEBAJqcSohOr6BgmVU1kHx9AFsTr3lLa7Bf1GLMlBaid05vso4YpWZq\nEe7RwbuibFAf9TA4a/UsAMmo9fTZ/j79dH8CcYCDHnxd6bJt3kzp4KQqiiEXFsHl\n/9nh9QFvCPrlUIiJfJWvbGz/BClDyNxppo8wWQ7QdJ6HzuRZq2eZ0QCSCO/2g3Uz\njYrpXUGu8rrVn4lXtLgyASX+Ep7imHPFCEH5wVxipvH/6H01wP2y7feOXgYcykdM\nvNsnRdvXEUe7mTCx0VoEv8VKs9VRmZxXrfHoA5ZByAJ+w/8rFELlX/Rpxz0sOBq+\nr5809GwsfqQFzL3WbJhZtzyyAgrsrMjFQvsCAwEAAaAAMA0GCSqGSIb3DQEBCwUA\nA4IBAQCWhujuaXaGPeG3bJ1oJm1CZv3YcRtpCvesBWKSBFUYQFepklqf2d01jbfL\nt3xowJzAIHFg+XPy9bwPMKRqxvFbUoJhRYaLiahFLfonE4PIq/8qW6jJ56jRpTfd\nB6O5Bl3+hVpCfM2n1x9ZzIGgTn2yoBlhAeRtLKA+GD19bnzt6YhiBNLqcKSlsXEr\nNPldK/dqOjO0scYzVY7nP4nWN9g5IvlWyU99A5L7uO/9afn+NFJ7DbI6FjrFSzFN\naS0NBr9rpvvUsZ+7mWIlYMxPMflPvTWJlUGr4yDLZjsRelye59p9kq89VwIeL77Q\n0Rqksl59ZH76Z2shHmdVso9VYo/O\n-----END CERTIFICATE REQUEST-----\n"
}
