### ISSUE TITLE
Firewall block all ports if ppp configuration leads to not active link

### ISSUE THREAD

**Issue by sterwen** [eclipse/kura#3388]
**Describe the bug**
When configuring a ppp connection with Kura, if this is not succeeded and the gateway is rebooted, then all ports are locked.

**To Reproduce**
1. Configure a ppp connection with either a wrong apn or even a network problem leading to a non active ppp link
2. Reboot to try fixing above
3. No way to access the gateway as all ports are closed

**Expected behavior**
In any case, we shall not have a complete lockout. To recover a local console access is necessary. If connection to Kapua is available, then a skilled person can also send the recovery command.

**Screenshots**
N/A

**Target Environment (please complete the following information):**
 - NXP iMX6
 - OS version: Linux 5.4 (Debian)
 

**Additional context**

**Comment by MMaiero** [comment]
Hi @sterwen 
Is this still an issue?

Matteo
