### ISSUE TITLE
VMware installs 2021-01-11-raspios-buster-i386.iso after installing kura3.2.0 access error

### ISSUE THREAD

**Issue by zhanghenglang** [eclipse/kura#3389]
![image](https://user-images.githubusercontent.com/70355661/119598015-b4fc7780-be14-11eb-88ae-07bb5de0816a.png)

**Comment by MMaiero** [comment]
Hello, 
I'm sorry, but I'm not aware of such distribution.
In order to try to provide some help we'll definitely need the content of the kura.log and Kura-console.log files as well as a description of the setup.

**Comment by zhanghenglang** [comment]
![image](https://user-images.githubusercontent.com/70355661/119635148-f78a7800-be45-11eb-80f9-64b893e75eb9.png)

**Comment by zhanghenglang** [comment]
> Hello,
> I'm sorry, but I'm not aware of such distribution.
> In order to try to provide some help we'll definitely need the content of the kura.log and Kura-console.log files as well as a description of the setup.
![image](https://user-images.githubusercontent.com/70355661/119636520-4edd1800-be47-11eb-9828-64da21122a1b.png)

**Comment by MMaiero** [comment]
It seems that the database is not booting for a reason.
That may be also the cause of the UI not available.
Having the full log uploaded to this issue could help to see if there are other error s or problems with the installation.

**Comment by zhanghenglang** [comment]
> 看来数据库没有启动是有原因的。
> 这也可能是UI不可用的原因。
> 将完整的日志上传到此问题可能有助于查看是否存在其他错误或安装问题。

[kura-console.log](https://github.com/eclipse/kura/files/6545506/kura-console.log)

**Comment by zhanghenglang** [comment]
[kura.log](https://github.com/eclipse/kura/files/6545513/kura.log)

**Comment by MMaiero** [comment]
From the Kura-console.log you'll see that almost every service failed to start, especially the ones with native code.
It may be because you are trying to run on a x86 platform. I'm not sure, but it may be that 32 bit intel is not a supported platform for 3.2.0

**Comment by zhanghenglang** [comment]
> 从Kura-console.log中，您会看到几乎所有服务都无法启动，尤其是带有本机代码的服务。
> 可能是因为您试图在x86平台上运行。我不确定，但可能是3.2.0不支持32位Intel平台

So which version of 3.x.y supports 32-bit Raspberry Pi? When installing the Raspberry Pi on the virtual machine, no 64-bit version was found.

**Comment by MMaiero** [comment]
Raspberry Pi is 32 bit, but it is ARM architecture. Are you installing in an ARM based virtual machine?

**Comment by zhanghenglang** [comment]
> Raspberry Pi是32位的，但它是ARM体系结构。您要安装在基于ARM的虚拟机中吗？

I installed it on a virtual machine, but not on an ARM-based virtual machine.

**Comment by MMaiero** [comment]
I believe that is the issue.

**Comment by zhanghenglang** [comment]
> 我相信这就是问题所在。

![image](https://user-images.githubusercontent.com/70355661/119799596-ccb82680-bf0e-11eb-87af-f1f56dc0e4a8.png)
If I want to use the DockerFile provided above to install kura 3.2.0, how should I change my GIT_REPO and GIT_BRANCH? Or can you use the DockerFile provided above to complete the deployment and installation on centos 7?

**Comment by MMaiero** [comment]
The containers are pre-built and available in the docker hub https://hub.docker.com/r/eclipse/kura but I believe we have introduced the containers only with Kura 4. Not sure if that works with Kura 3.

**Comment by zhanghenglang** [comment]
> 这些容器是预先构建的，可以在docker hub [https://hub.docker.com/r/eclipse/kura中使用，](https://hub.docker.com/r/eclipse/kura)但是我相信我们仅在Kura 4中引入了这些容器。不确定是否可以在Kura 3中使用。

It can only be used on kura4, and cannot be used on kura3.

**Comment by MMaiero** [comment]
Hi @zhanghenglang 
any feedback on this?
