### ISSUE TITLE
Add BaseDbService to provided interfaces of H2DbServiceImpl

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#3395]
**Is your feature request related to a problem? Please describe.**
I've created an alternative database driver in Kura for SQLite implementing BaseDbService, now I intend to track this kind of services along with currently existent H2DbService from another component via interface reference. I've referenced BaseDbService but it seems that, even though the H2DbService implements that interface, it is not declared in its OSGI info.

**Describe the solution you'd like**
Extend this definition:
```xml
   <service>
      <provide interface="org.eclipse.kura.configuration.ConfigurableComponent"/>
      <provide interface="org.eclipse.kura.db.H2DbService"/>
   </service>
```

To this:
```xml
   <service>
      <provide interface="org.eclipse.kura.configuration.ConfigurableComponent"/>
      <provide interface="org.eclipse.kura.db.BaseDbService"/>
      <provide interface="org.eclipse.kura.db.H2DbService"/>
   </service>
```

In https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core/OSGI-INF/h2db.xml

**Comment by pintify** [comment]
Actually, I've reviewed H2DbService and I don't see anything specific about H2 database, wouldn't it make sense integrate both interfaces or convert H2DbService to GenericDbService (or anything else)?

I comment this because I was going to implement H2DbService in my SQLite service as a workaround but I think that the method required by this interface is useful even as a final solution.

Just as a possible alternative solution...

**Comment by MMaiero** [comment]
Hi @pintify 
I agree in having the service exposing itself as a baseDbService. It makes sense.
I cannot recall if there was a specific reason for having the h2dbservice extending the interface. Maybe some sort of specificities.
We were discussing internally and the original proposal you made seems reasonable for us and we were going to make a PR for that.
Best regards,
Matteo
