### ISSUE TITLE
[Configuration] Support multiple configurations for SelfConfiguringComponentS

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#342]
The ``ConfigurationService`` needs to support creating configurations (via ``createFactoryConfiguration``) for ``SelfConfiguringComponent``S too.

**Comment by LucaDazi** [comment]
This may actually already be working without any change.
Putting a "service.factoryPid" property in the ComponentDefinition xml, and having the Component to require configuration seems to do the trick.
More on that: no need for the Component to be a ConfigurableComponent or a SelfConfiguringComponent.

I'll perform some more test on it and report back.

**Comment by cdealti** [comment]
Great! Thanks!

**Comment by cdealti** [comment]
@LucaDazi If this already work we should update the Javadoc.

**Comment by MMaiero** [comment]
@LucaDazi Do you have any update on this? Thanks

**Comment by LucaDazi** [comment]
@MMaiero I guess this can be closed. It has been thoughroughly tested during Kura Wires development.
