### ISSUE TITLE
[Web2]: Setting the "name" property to anything different than the "id" sets an empty value

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#343]
Setting the "name" attribute to anything different than the "id" attribute in the metatype model will cause the "name" to rendered as label, but fail to retrieve the data from the generated form since the label is used as ID:

```java
String id = ((FormLabel) fg.getWidget(i)).getText();
param = m_configurableComponent.getParameter(id.trim().replaceAll("\\*$", ""));
```

A possible workaround would be to set the ID into the title an also retrieve it from there, making the label just a label:

```java
FormLabel formLabel = new FormLabel();
if (param.isRequired()) {
  formLabel.setText(param.getName() + "*");
} else {
  formLabel.setText(param.getName());
}
formLabel.setTitle(param.getId());
```

and:

```java
param = m_configurableComponent.getParameter(fg.getWidget(i).getTitle());
```

**Comment by cdealti** [comment]
Closed by #345.
