### ISSUE TITLE
There are errors in JS console after opening Status/Network system item

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3444]
**Describe the bug**
There are errors in JS console after opening Status/Network system item

**To Reproduce**
1. OPen WEB UI
2. Open developer JS console
3. Click on Status/Network system item
4. See errors

**Expected behavior**
There should not be errors

**Screenshots**
![Capture](https://user-images.githubusercontent.com/3385815/123122577-6dceca00-d446-11eb-9aaa-3c38827dd9d9.PNG)
![Capture1](https://user-images.githubusercontent.com/3385815/123122588-71625100-d446-11eb-969f-4b9b5bc0b421.PNG)

**Target Environment (please complete the following information):**
 - Board Raspberry Pi 3
 - OS version: Linux raspberrypi 5.10.17-v7+ # 1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
 - Additional info: build 5.0 - RC2

**Comment by spnettec** [comment]
In EntryClassUi.ui.xml  line 162

b:TabListItem   should be b:AnchorListItem

**Comment by MMaiero** [comment]
Hello,
do you think you can contribute your changes with a PR?

Best regards,
Matteo
