### ISSUE TITLE
Improve certificate import

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#3468]
**Describe the bug**

One of the reasons why I had troubles with #3467 is, that Kura seems to have a very fragile PEM import process:

* If the PEM file has trailing whitespaces (e.g. at the end of the line, like the official cross signed Let's Encrypt certificate has), then the parser fails -> Whitespaces should be ignored
* When the parser fails, it only reports back "error" to the console, which doesn't help finding the issue -> report the actual error

**Comment by MMaiero** [comment]
This should have been solved with a PR now available in 5.0.0 RC3
