### ISSUE TITLE
WpaSupplicantConfigReader.getWifiClientConfig() should support cases where key_mgmt scheme is not set

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#348]
As per the documentation of wpa_supplicant.conf, the "key_mgmt" entry defaults to "WPA-PSK WPA-EAP" when it is not set.
Therefore, there may be cases where "psk=......" entry is set event though no key_mgmt has been explicitely defined. 
Currently, the WpaSupplicantConfigReader will not properly detect the `WifiSecurity` mode for those wpa_supplicant.conf that don't have a key_mgmt scheme explicitly set.

**Comment by cdealti** [comment]
@kartben I know this is old but do you remember the steps to recreate this? @ibinshtok is this a known issue or has it been already fixed?

**Comment by ibinshtok** [comment]
@cdealti no, as far as I know this has never been addressed.

**Comment by cdealti** [comment]
@ibinshtok is it clear what @kartben describes?

**Comment by kartben** [comment]
Let me reformulate, with what I remember:
An *existing* wpa_supplicant.conf file may *not* have the "key_mgmt" entry set, as it is not supposed to be mandatory, and yet have a "psk" set to do WPA PSK / WPA EAP auth. Kura always adds it to the file when changes are made to it, but a "vanilla" Pi or Samsung ARTIK may not have the entry set.

An easy way to reproduce should be to just remove the key_mgmt entry from the wpa_supplicant.conf file that setups a WPA-PSK based connection to an access point. The wireless connection should still be properly managed via pure linux, but Kura will get confused (I have to admit i don't remember exactly how, but looking at https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/WpaSupplicant.java#L291 it looks like maybe it falls back to trying to use no security)

Hope this helps?

**Comment by ibinshtok** [comment]
@cdealti I will try to recreate this tomorrow and let you know.

**Comment by salvatore-coppola** [comment]
@MMaiero the `WpaSupplicantConfigReader` doesn't exist anymore, now the confuration is alway read from the snapshot.
In the snaphost if we find that no security is set we use NONE and i belive it is fine https://github.com/eclipse/kura/blob/bbe229b746f54c695f5e218119fd353bfc8fb76f/kura/org.eclipse.kura.core.net/src/main/java/org/eclipse/kura/core/net/NetworkConfiguration.java#L638

**Comment by MMaiero** [comment]
Great! Thanks for the update. Closing.
