### ISSUE TITLE
createFactoryConfiguration seems to always save snapshots

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#358]
The new `createFactoryConfiguration` method in the CloudService generates a snapshot even if the `takeSnapshot` flag is set to false.

e.g. when creating a new communication stack, the result is three new snapshots in the snapshots folder, instead of just one, as expected.

On another note, the `deleteFactoryConfiguration` seems to correctly handle the `takesnapshot` flag.

**Comment by LucaDazi** [comment]
@cdealti can you review when you have some spare time?

**Comment by cdealti** [comment]
@mmaiero can you keep this in QA/Review until every possibile api test has been performed? Can you also run JUnit tests?

**Comment by MMaiero** [comment]
@cdealti The JUnit tests are running fine with this change
