### ISSUE TITLE
Kura main process does not automatically restart

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#364]
If anything happens to the main Kura process (JVM) then the process is not being restarted.

**Comment by MMaiero** [comment]
The only possibility we see here is to install monit.
We think that if the Kura user wants to have the framework restarted, probably he will install monit by himself.

**Comment by ctron** [comment]
I can think of a lot way to resolve this. A "forever loop script". A proper systemd configuration.

**Comment by MMaiero** [comment]
This has been addressed years ago. Closing.
