### ISSUE TITLE
[API] Wrong API package versions on develop after merging the release-2.0.0 branch

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#370]
API package versions look good on the [release-2.0.0 branch](https://github.com/eclipse/kura/blob/release-2.0.0/kura/org.eclipse.kura.api/META-INF/MANIFEST.MF)

and on the [master branch](https://github.com/eclipse/kura/blob/master/kura/org.eclipse.kura.api/META-INF/MANIFEST.MF)

but not on the [develop branch](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.api/META-INF/MANIFEST.MF)

This is the [offending commit](https://github.com/eclipse/kura/commit/e1cbd9b5f81722f6f8dff9d5bab8a586d83f05b5)

@dwoodard1 can you please take a look?

**Comment by dwoodard1** [comment]
@cdealti It looks ok to me, what is the problem?

**Comment by amitjoy** [comment]
@dwoodard1 The package versions of some of the packages got increased even though I believe it shouldn't have been increased. For instance, the **_org.eclipse.kura.listener_** had a package version of **1.0.0** whereas it got increased directly to **1.0.9**. It also occurred to some of the other packages as well.

**Comment by dwoodard1** [comment]
@cdealti @amitjoy I see, I believe I know what happened. I will get this cleaned up.

**Comment by dwoodard1** [comment]
@cdealti @amitjoy Should be fixed, can you merge the PR?
