### ISSUE TITLE
Wire Graph - Apply button disabled although there is a change

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#3730]
**To Reproduce**
steps: 
- go to wire graph
- create h2dbstore component - apply
- change the table name
-> apply is disabled

**Comment by MMaiero** [comment]
Hi @mstankovic 
can you please details if this issue is from develop or existing releases?
Is it a regression?
Thanks.

**Comment by MMaiero** [comment]
Tested in my test environment using develop and seen that the apply button gets enabled once the focus is removed from the text field.
