### ISSUE TITLE
Incorrect birth message in multiple CloudSerivces

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#3767]
**Describe the bug**
When Kura is connected to two different accounts of Kapua in the same instance, the birth certificate is incomplete in one of them.

Specifically, KEYS-V1 seems to be omitted in the second connection.

**To Reproduce**
1. Create two different CloudServices with their corrsponding MqttDataTransport in the same Kura.
2. Connect both of them to the same Kapua instance but in different accounts.
3. Check the birth messages in both cases.
4. Note KEYS-V1 is not registered in one of them.

**Target Environment (please complete the following information):**
- Kura version: 5.0.1
 - OS version: Debian 9

**Additional context**
Reported initially through [gitter](https://gitter.im/eclipse/kura?at=61e6d2829a335454062bf1b5)

**Comment by nicolatimeus** [comment]
The `KEYS-V1` request handler uses the following DS reference to bind to `RequestHandlerRegistry`:

https://github.com/eclipse/kura/blob/8278c797b1efbdbcb1b2823c352655a37fa47279/kura/org.eclipse.kura.core.keystore/OSGI-INF/org.eclipse.kura.core.keystore.request.handler.keystoreRequestHandler.xml#L20

This reference is static and uses `1..1` cardinality, so it will bind to a single `RequestHandlerRegistry`instance, which one is undefined, we should change this.

**Comment by pintify** [comment]
Great, thanks!
