### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by Mahmoud-Ammar** [eclipse/kura#380]
Hello !!

Could I ask how to get in deep in the security architecture of Kura in order to analysis it ? I've looked deeply in the documentations and other resources but  security is not mentioned at all.

Any tips ??

**Comment by MMaiero** [comment]
Hi,
currently Kura provide some apis for security like:

- org.eclipse.kura.crypto
- org.eclipse.kura.security
- org.eclipse.kura.ssl

Regarding these, you can find the implementation of [ssl apis](https://github.com/eclipse/kura/tree/develop/kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/ssl) and [crypto apis](https://github.com/eclipse/kura/tree/develop/kura/org.eclipse.kura.core.crypto)

**Comment by MMaiero** [comment]
No updates since a long time. Closing it.
