### ISSUE TITLE
Add modem information in the Antenna Tab

### ISSUE THREAD

**Issue by ftoure67** [eclipse/kura#3815]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see more modem information like the Sim status, the IMSI, the LAC, CI, BAND, etc.

**Describe the solution you'd like**
I would like to see the additional modem information in the Antenna TAB.

**Describe alternatives you've considered**
It may be possible to query the modem information using tty commands but this may conflict with some commands sent by Kura

**Additional context**
No.

**Comment by MMaiero** [comment]
Closing as done.
