### ISSUE TITLE
[DOCKER] Build KO due to moquette repository jcenter.bintray.com

### ISSUE THREAD

**Issue by GizmoIchitzo** [eclipse/kura#3826]
Hello,

We cannot build Kura with docker due to moquette  repository wich is closed since several month 
https://jcenter.bintray.com

Can you update moquette dependancy to fit the last version available in other repo plz ?

**Comment by MMaiero** [comment]
Hi,
right now the issue reported is not affecting our local or remote Jenkins builds.
We will, in any case, have a look at this after Kura 5.1.0 release

**Comment by GizmoIchitzo** [comment]
Hi,

clear .m2 repo and try again your remote build. Normally, the build will fail

**Comment by MMaiero** [comment]
Yes, we usually run our builds from that state.
But I'll try that again later
