### ISSUE TITLE
Upgrade to a more recent Jetty version

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#384]
Currently Kura uses Jetty 8.1.3 ... the most recent 8.1.x version is 8.1.19 and Jetty 8.x is EOL since the beginning of the year [1]. This includes security patches.

I would recommend to at least upgrade to Jetty 8.1.19 and following up with an upgrade to Jetty 9.3.x

[1] https://webtide.com/jetty-7-and-jetty-8-end-of-life/

**Comment by MMaiero** [comment]
Closing this in favor of #460
