### ISSUE TITLE
Missing source in developer workspace

### ISSUE THREAD

**Issue by aeisma** [eclipse/kura#389]
Please build the target platform plugins for the developer workspace with source included.

[http://www.eclipse.org/downloads/download.php?file=/kura/releases/2.0.0/user_workspace_archive_2.0.0.zip] no longer contains org.eclipse.kura.api as a project, but only as a target platform plugin. Therefore the target platform plugins should contain source to support dynamic help and debugging in Eclipse.

**Comment by ctron** [comment]
I am currently working on modifying the build in order to pull in the source bundles for external dependencies and also for generating a full P2 repository at the end of the build. It will contain the source bundles as well.

In the meantime you can already use the Oomph based setup in order to have a quick way to set up a full workspace with all sources as actual projects.

**Comment by aeisma** [comment]
I managed to do the Oomph based setup for the kura 'developer' configuration, and the Kura_Emulator_OSX launch runs without errors in the console. However, when I open http://localhost:8080/kura the following error message pops up in the browser while rendering the web ui:

Error
Wed Aug 17 12:47:36 GMT+200 2016 ErrorLogger INFO: org.eclipse.kura.web.client.ui.EntryClassUi: The response could not be deserializedcom.google.gwt.user.client.rpc.IncompatibleRemoteServiceException: The response could not be deserialized
...
caused by: com.google.gwt.user.client.rpc.SerializationException: org.eclipse.kura.web.shared.model.GwtConfigParameter$GwtConfigParameterType/3795351031

The last line logged in the console is:
12:47:36,709 [qtp88461104-21] INFO  /:1947  - org.eclipse.kura.web.server.GwtComponentServiceImpl: Trying www resource2: /www/denali/C04F3693ABC0A6E8C4E2A797AA4135F9.gwt.rpc

Is something wrong with the setup? Did I miss anything?

**Comment by ctron** [comment]
I am not sure what the other "Kura Emulator" launch configurations actually do .. 

Can you try the launch configuration "Eclipse Kura Emulator (Linux)" ... You may need to make some modifications for Mac OS. If you run into troubles let me know and I try to help.

**Comment by aeisma** [comment]
You're right, the Kura_Emulator_OSX launch configuration is not correct. It selects bundle com.gwt.user-0.2.0 instead of com.gwt.user-1.0.0, as required by web2.
There are other differences, so if it is the intention to keep Kura_Emulator_OSX.launch around, clone it from the Linux version.

**Comment by ctron** [comment]
If you have a working version for Mac OS, please post it, or if you have an Eclipse CLA signed make a pull request. That would help a lot. ... For people not using Linux :wink:

**Comment by aeisma** [comment]
The launch configuration for Mac OS X is literally the same as for Linux.

Consider either:
(a) renaming "/setups/launchers/Eclipse Kura Emulator (Linux).launch" to "Eclipse Kura Emulator.launch" and dropping the OSX launch configurations, or
(b) clone "Eclipse Kura Emulator (Linux)" to "Eclipse Kura Emulator (OSX)".

Same for each of the 3 "Kura_Emulator_Linux" launch configurations:
(1) /emulator/org.eclipse.kura.emulator/src/main/resources/Kura_Emulator_Linux.launch
(2) /tools/archetype/example/src/main/resources/archetype-resources/org.eclipse.kura.emulator/src/main/resources/Kura_Emulator_Linux.launch
(3) /distrib/src/main/resources/common/Kura_Emulator_Linux.launch

B.T.W. the timestamp suggests that launch configuration (1) has been updated, and (2) and (3) not.

**Comment by ctron** [comment]
I did create a new issue for cleaning this up. I also organized for a Mac book for testing the OS X launch configuration. So I can either re-name or duplicate a tested version.
