### ISSUE TITLE
Fix javadoc for the getKuraVersion() method of the SystemService.

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#403]
Here is what we have in the http://download.eclipse.org/kura/releases/2.0.0/docs/apidocs/ right now:

String getKuraVersion()
Gets the product version for this unit. The product version is defined as the version in the release.xml file. The release.xml file is stored in /etc/kura/ and has the format: PRODUCT_NAME_release-VERSION-VERSION_NUMBER.xml For example this is a valid product name: helios_denali_release-1.2.3.xml. The version number would be 1.2.3. This would be an invalid product name: my-product-name_release-1.2.3.xml. This is because the product name has '-' characters in it. They should be '_' to be valid. So, the correct representation would be: my_product_name_release-1.2.3.xml. It's version number would be 1.2.3. The use of '-' characters should only be used immediately before the version number and the use of '.' characters should only be used immediately after the version number.
Returns:
The version number as denoted in the release.xml file.

This is correct for ESF1 but not for Kura.

**Comment by ibinshtok** [comment]
@cdealti ok

**Comment by MMaiero** [comment]
@ibinshtok Can this be closed? Thanks
