### ISSUE TITLE
All ConfigurableComponent and SelfConfiguringComponent should actually export their interfaces properly

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#408]
All services which implement ConfigurableComponent or SelfConfiguringComponent should actually register those interfaces when they register their service.

Otherwise it is not possible for the ConfigurableComponentTracker to actually track those services. Right now the ConfigurableComponentTracker falls back to just tracking all services, getting all services and testing manually. This also causes all services to be actually activated by that tracker.

**Comment by MMaiero** [comment]
@ctron This can be closed, right?

**Comment by ctron** [comment]
I am not sure about that one. Since the default behavior is still the same.

I would suggest we add a bug error message in the console if we can detect this and start a depreciation process around that. Then we can close this.

**Comment by cdealti** [comment]
@ctron @MMaiero @dwoodard1 do we agree that Kura 3.0.0 should only track services registering ConfigurableComponent or SelfConfiguringComponent?
NOTE: THIS IS A BREAKING CHANGE

**Comment by ctron** [comment]
But I think we agreed on being able to make breaking changes in Kura 3.0.0?!

**Comment by cdealti** [comment]
There are even more things that we could break. I believe we should come up with a list.

**Comment by dwoodard1** [comment]
Should we discuss what breaking changes we want to introduce next Tuesday?

**Comment by cdealti** [comment]
Closing as this is the default behavior of Kura 3.0.0.
