### ISSUE TITLE
Kura 5 docker does not restart

### ISSUE THREAD

**Issue by ganzuoni** [eclipse/kura#4162]
**Describe the bug**
A kura 5 container create with
docker create  -p 18080:8080 -p 1443:443  --name kura5 eclipse/kura
does not restart

**To Reproduce**
1. create docker as above
3. docker container start
4. docker container stop
5. docker container start
6. docker logs 
Kura is still boxed, unpacking ...
Initial Kura instance unpacked, commencing start
Starting Kura...
cp: can't stat '/opt/eclipse/kura/framework/config.ini': No such file or directory

**Expected behavior**
Kura 5 should start without errors

**Target Environment (please complete the following information):**
 - issue is present even with image 5.1.2-ubi8-x86_64
 - CentOS Linux release 7.3.1611 (Core)
 - Additional info: 

**Additional context**
kura 4.1.2 works perfectly

**Comment by salvatore-coppola** [comment]
Hi @ganzuoni .
We just tried the steps you reported and everything seems to to be working fine.
Perhaps you could provide us with more information?

**Comment by ganzuoni** [comment]
Docker version 17.12.0-ce, build c97c6d6
Strange enough
docker restart kura5 works
If I stop and the start I get filesystem corrupted
If I commit the container in a new image
docker commit kura5 kura5/failed
and the create a container with an alternative entrypoint
docker run --privileged --name kura5fail  -ti --entrypoint=/bin/bash kura5/failed
This is what I get

bash-5.1# ls -l /opt/eclipse/
total 0
drwxrwxrwx    1 root     root           172 Sep  8 20:57 kura_5.2.0_intel-up2-ubuntu-20-nn

No symlink

bash-5.1# ls -l /opt/eclipse/kura_5.2.0_intel-up2-ubuntu-20-nn/
total 0
drwxrwxrwx    1 root     root            43 Sep 15 11:07 data
drwxr-xr-x    1 root     root            22 Sep  8 20:57 kura
drwxr-xr-x    1 root     root            87 Sep 15 11:07 packages
drwxrwxrwx    1 root     root            69 Sep  8 20:56 user

No framwork directory

**Comment by ganzuoni** [comment]
A "simple" host restart made the trick....
