### ISSUE TITLE
WireAsset (Modbus) emits error just once

### ISSUE THREAD

**Issue by ganzuoni** [eclipse/kura#4181]
**Describe the bug**
A WireAsset representing a Modbus device emits payload just once

**To Reproduce**
1. Starts a modbus slave simulator
2. Create a wire graph with a timer to acquire some channels with WireAsset connected to a Logger receiver
3. tail -f kura.log
4. You can see acquisition logged
5. Stop modbus slave simulator
6. logger shows the channel acquisition error along with the stacktrace
7. next iteration in kura.log there is the stack trace only, no Logger dump of the payload

**Expected behavior**
Payload with errors emitted to the wired component at each iteration

**Target Environment (please complete the following information):**
 - Kura 5.2 docker

**Comment by MMaiero** [comment]
Hello,
I think that the error emission depends mainly by the driver used.
What driver bundle are you using?
