### ISSUE TITLE
Remove "kura-sonar" build job on HIPP

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#421]
I would suggest to remove the "kura-sonar" [1] build job on the hudson instance.

It is confusing that there is a job which is failed since 2014. While there actually is a working sonar integration on the "kura-develop" job.

[1] https://hudson.eclipse.org/kura/job/kura-sonar/

**Comment by dwoodard1** [comment]
@ctron Thanks! It was a legacy test build that needed to be deleted. It is now gone.
