### ISSUE TITLE
Wrong order of BIRTH/APPLICATION certificates for custom APP IDs registration

### ISSUE THREAD

**Issue by davide-prade** [eclipse/kura#4212]
**Describe the bug**
At every APP ID registration with `CloudServiceImpl.registerRequestHandler()` method an `APPLICATION` certificate is sent, causing a possible wrong order processing at server side.

**To Reproduce**
1. Configure a CloudService connection to a Eclipse Kapua server, and connect to it. 
2. Call in rapid sequence the `CloudServiceImpl.registerRequestHandler()` method (trough the related `RequestHandlerRegistry` of the custom component) multiple times with different application identifiers.
2. See in the `Events` tab of Eclipse Kapua Console that sometimes the order of reception/processing is different than the Kura sending order: only the `BIRTH`/`APPLICATION` certificate with the higher `Created On` timestamp is taken into account and then sometimes the last one is missing one or more APP IDs.

**Expected behavior**
Sending the `BIRTH`/`APPLICATION` certificate containing the two or more customized application identifiers should be done once, or wait for an ACK of the previous one before sending the next one, or wait for a predetermined time using a cache. 

**Additional context**
This problem occurs if application identifiers are registered after the connection has already been established.
Looking at the code for the `CloudConnectionManagerImpl` class instead, it appears that sending the `BIRTH`/`APPLICATION` certificate is inhibited when the connection has already been established and therefore Eclipse Kapua cannot be updated on any subsequent APP ID registrations.

**Comment by MMaiero** [comment]
Hello,
do you have some logs to share that show the issue?

**Comment by davide-prade** [comment]
Hi @MMaiero,
here are the relevant device events: [container_device_events.csv](https://github.com/eclipse/kura/files/9900460/container_device_events.csv)
As you can see, if you order them by the `Created On` field, the last event is missing the `USER-INTERFACE-V1` custom APP ID.

I confirm that by creating an APP ID caching mechanism in one of our custom components and publishing the certificate after 5 seconds the problem no longer occurs.

**Comment by MMaiero** [comment]
Are you seeingg this issue with only your custom component (USER-INTERFACE-V1) or also with other "native" Kura components?

**Comment by davide-prade** [comment]
This problem apparently occurs only with "non-native" APP IDs. I imagine that the native components are loaded before the connection is established due to dependencies and therefore the problem does not manifest because the APP IDs have already been collected.

**Comment by MMaiero** [comment]
The code that manages that publishing is this one: https://github.com/eclipse/kura/blob/657107fe5caa4c593995cd2e8782e99570172c62/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java#L947
Once the app registers itself to the cloud connection, it should be tracked and an app update should be published.

From that point on the app should be recorded in a map. The only point where I see a removal from that map is this one: https://github.com/eclipse/kura/blob/657107fe5caa4c593995cd2e8782e99570172c62/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java#L966
That is only called when the request handler is unregistered.

**Comment by davide-prade** [comment]
That's right, just to solve the problem of multiple sequential sending of multiple "non-native" APP IDs, I had to create three new methods, to avoid immediate sending of the certificate for each APP ID, which can cause server-side processing in the wrong order.

These are the methods in `kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/cloudconnection/request/RequestHandlerRegistry.java` interface:
```java
    public void registerRequestHandlerNotPublish(String appId, RequestHandler requestHandler) throws KuraException;
    public void publishRegisteredRequestHandlers() throws KuraException;
    public void unregisterNotPublish(String appId) throws KuraException;
```

As can be guessed, the `*NotPublish` methods simply add or remove the APP ID in/from the map and the `publishRegisteredRequestHandlers` method is called after a certain period of time and only deals with sending the certificate.

The call to these new methods, however, is currently done by us externally by one of our dedicated components and in my opinion should be included "natively" in kura.

**Comment by MMaiero** [comment]
Wouldn't be better to add a (maybe configurable) delay in the app processing? So the API stays the same and the code changes to accomodate this need?

**Comment by davide-prade** [comment]
We have multiple OSGi bundles that can load dynamically in rapid succession, and we have no control over the loading sequence and timing.

**Comment by MMaiero** [comment]
that's why I was suggesting a configurable delay to be specified in the Request Handler preferences so that the registering operation can stay the same. A separate thread can proceed on the APP/BIRTH publishing after x seconds or x seconds after the last registration events so that you can send only one message to the cloud with all your apps in it

**Comment by davide-prade** [comment]
It is not acceptable for us to delay loading our bundles, which may number in the dozens and interface directly with hardware components that need to be available to other bundles as soon as possible.

**Comment by MMaiero** [comment]
No, maybe I was not clear on my proposal: my idea would be to add a thread in CloudServiceImpl that processes the registrations in https://github.com/eclipse/kura/blob/657107fe5caa4c593995cd2e8782e99570172c62/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java#L947 and published the birth/APP update after x seconds after the last call of the method. In this way the applications can start at their pace, register themself and then the cloud service will publish the APP/BIRTH event that will be one, at that point. The applications would have not been delayed in their startup and you don't need to add new APIs making it incompatible with upstream.

**Comment by davide-prade** [comment]
Sorry, I didn't understand correctly.
Yes, that is exactly what would be needed.
I also don't understand why the APPLICATION certificate is not sent the same way in `CloudConnectionManagerImpl` and so that class should be corrected as well.

**Comment by MMaiero** [comment]
> Sorry, I didn't understand correctly.
> Yes, that is exactly what would be needed.

That would be a great contribution for the project if you are willing to partecipate to it. We would be happy to have new contributors to Eclipse Kura!

> I also don't understand why the APPLICATION certificate is not sent the same way in CloudConnectionManagerImpl and so that class should be corrected as well.

Not sure there too, it may be because of the different contract.

**Comment by davide-prade** [comment]
Thank you very much for your reply.
As soon as I have some time I will create a PR.
