### ISSUE TITLE
Possible data duplication on CloudPublisher

### ISSUE THREAD

**Issue by LucaDazi** [eclipse/kura#4292]
**Describe the bug**
The CloudPublisher can be configured to put into the KuraMessage body one of the properties received.
When this happens, the original property is left in the properties, which all end up in the list of metrics in the KuraMessage.

This leads to possible duplication of data. If a user wants to publish something in the body of the message, he probably also wants to remove that property from the metrics.

**To Reproduce**
1. Create a WireGraph with some string metric (Timer -> JavascriptFilter -> Publisher)
2. Configure the JavascriptFilter to create a "payload" Stirng metric in output
3. Configure the CloudPublisher to put the "payload" metric into the MQTT message body
4. Verify how the Publisher will publish both a "payload" metric in the metrics, and the content of "payload" in the body

**Expected behavior**
If the CloudPublisher is configured with a non-empty value in the "set.body.from.property" property, the property should not be included in the metrics of the resulting KuraMessage

**Target Environment (please complete the following information):**
 - Board: ANY
 - OS version: ANY

**Comment by pierantoniomerlino** [comment]
Closed by #4328
