### ISSUE TITLE
Unable to delete Wire Graph when component no more available

### ISSUE THREAD

**Issue by marcellorinaldo** [eclipse/kura#4305]
**Describe the bug**
Unable to delete the wire graph when Deployment Package providing the component is uninstalled.

**To Reproduce**
1. Install a DP that contains a wire component (like `wire.script.filter` or `wire.script.tools`).
2. Go into the Wire Graph and connect a new installed component to a Timer. Apply.
3. Uninstall the previously installed package.
4. Try to delete the Wire Graph. Not possible.

**Expected behavior**
The wire graph should be deletable.

**Screenshots**
N/A.

**Target Environment (please complete the following information):**
 - Raspberry Pi4
 - OS version: Linux raspberry 5.15.61-v7l+ 1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
 - Additional info: N/A.

**Additional context**
N/A.

**Comment by mattdibi** [comment]
Closed by #4310
