### ISSUE TITLE
Kura API docs show 1.0.8 for Kura 2.0.0

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#434]
Looking at [1] it shows API docs for Kura 1.0.8.

[1] http://download.eclipse.org/kura/releases/2.0.0/docs/apidocs/?d

**Comment by cdealti** [comment]
This is actually the version of the org.eclipse.kura.api bundle which, admittedly does not make much sense.

**Comment by cdealti** [comment]
The latest Javadoc released for Kura 2.1.0 shows ``Eclipse Kura 2.1.0``.
I believe this is what you want to see even if for Semantic Versioning the Kura version is irrelevant (and also the ``Bundle-Version`` of ``org.eclipse.kura.api``.
