### ISSUE TITLE
Expired certificate for Eclipse Marketplace (ssl-eclipse-marketplace)

### ISSUE THREAD

**Issue by marcomatteo** [eclipse/kura#4465]
**Describe the bug**
The Trusted Certificate in the SSLKeystore for the Eclipse Marketplace is valid until Feb 6, 2023, 12:59:59 AM.

**To Reproduce**
1. Open the Kura Packages web page
2. Go to [Eclipse Marketplace](https://marketplace.eclipse.org/content/triton-server-component-eclipse-kura-5)
3. Click the Install button of the bundle and drag&drop it in Kura
4. See the error `Failed to install deployment package`

**Expected behavior**
The _org.eclipse.kura.ai.triton.server-1.1.0.dp_ installed and listed in the Packages web page.

**Target Environment (please complete the following information):**
 - Raspberry Pi 3
 - OS version: Linux raspberrypi 6.1.19-v7+ armv7l GNU/Linux
 - Additional info: Kura 5.2.1

**Comment by salvatore-coppola** [comment]
resolved by #4250
