### ISSUE TITLE
setting a payload metric to null should throw an exception immediately

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#451]
If you set a metric to null:

`KuraPayload.addMetric("xyz", null);`

The payload is a ticking time bomb and will throw an exception when it is encoded later:

```
org.eclipse.kura.KuraInvalidMetricTypeException: Metric null value is invalid.
        at org.eclipse.kura.core.cloud.CloudPayloadProtoBufEncoderImpl.setProtoKuraMetricValue(CloudPayloadProtoBufEncoderImpl.java:166)
        at org.eclipse.kura.core.cloud.CloudPayloadProtoBufEncoderImpl.getBytes(CloudPayloadProtoBufEncoderImpl.java:66)

```

It should either:
a) be skipped when encoding later (ignored)
b) throw an exception on the 'addMetric' call

**Comment by cdealti** [comment]
@pstanton thanks. Maybe a) would be the preferred option. Option b) would require an unchecked exception for API backward compatibility and these exceptions are dangerous.

Are you going to submit a pull request?

Ciao,
  Cristiano
