### ISSUE TITLE
Password being readable in plain text in kura.properties

### ISSUE THREAD

**Issue by Yusuf-Mai-Eurotech** [eclipse/kura#455]
Noticed in kura.properties, password is in plain text and being readable anyone even he/she does not have any technical background.  Probably should be in some form of hash at the minimum

**Comment by ctron** [comment]
If you think this is a security vulnerability, please do report it to the Eclipse Security team [1]

[1] https://www.eclipse.org/security/

**Comment by MMaiero** [comment]
The passwords for ssl defined in kura.properties file are used for first boot and immediately changed by the framework.
I'm not aware of other passwords in there.

Closing for now
