### ISSUE TITLE
Clean up launch configurations

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#456]
In a freshly checkout out Kura workspace there are 26 launch configuration present.

This has to be cleaned up.

Following up #389

**Comment by cdealti** [comment]
In a freshly imported Kura 3.0.0 user workspace there are two Linux launch configurations and two OSX launch configurations. Is this OK?

![screenshot from 2017-05-26 12 29 01](https://cloud.githubusercontent.com/assets/1225835/26491258/2302b40a-420f-11e7-82ef-6ac04dd0142d.png)

**Comment by MMaiero** [comment]
It should be fixed now with the recent refactoring.
Closing for now
