### ISSUE TITLE
Question: Eclipse Kura Component is now listed as deprecated ?

### ISSUE THREAD

**Issue by SamD** [eclipse/kura#4562]
As this is now being deprecated what is the alternative? I'm just starting with Kura and have worked with Camel in the past. I was happy to see that out of the box Kura supported Camel but it looks like that is now going away ?

I can't find any recent documentation describing how to leverage latest Camel with latest Kura with the exception of the deprecated listing here : https://camel.apache.org/camel-karaf/3.20.x/kura.html

Thanks

**Comment by MMaiero** [comment]
Hi,
thanks for reaching out!
We are happy to see that there is interest in the integration between Kura and Camel. Unfortunately, the current integration is a little bit outdated, as the original contributor has not followed up with updates and the rest of the team is not knowledgeable with Camel.
It would be great to have new contributors interested in the project and that can help keeping updated the integration.

We were not aware of the deprecation reference but probably it is related to the old reference we currently have.
On our end we are continuing to test the functionality, checking that what is in the codebase is still functional.

If you are willing to refresh the integration, please feel free to reach out and maybe contribute a PR. it would be great to have new contributors in that area of the framework!

Best regards,
Matteo

**Comment by spnettec** [comment]
<img width="1907" alt="image" src="https://github.com/eclipse/kura/assets/1769060/40b32074-268c-49f5-b488-917bdc93bc20">
<img width="1908" alt="image" src="https://github.com/eclipse/kura/assets/1769060/d16f31f9-cad8-4cef-922d-e9d4618b156e">
<img width="1863" alt="image" src="https://github.com/eclipse/kura/assets/1769060/6cfc594c-c329-4139-b4c3-86ee3e66d360">
<img width="1831" alt="image" src="https://github.com/eclipse/kura/assets/1769060/02373b21-98c9-46dc-a1dc-cb58be54dcd8">


I have upgraded Camel. Unfortunately my branch is very different from the current branch and I don't have time to do the merge.
