### ISSUE TITLE
Post Eclipse Kura QA Process

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#457]
The methodology for testing and validating Eclipse Kura during a release should be made public. Comments on the format of this information are welcome.

**Comment by ctron** [comment]
Depending on the size of that document a few markdown files, checked in to GitHub, in the same repository may be fine.

I think the most important, first step, is to list what Kura is intended to support. OS, Java, architecture, …

**Comment by cdealti** [comment]
Starting with Kura 3.0.0 the QA Excel (xsls) spreadsheet will be put under version control in the Kura github repository. @markoer is my understanding correct?

**Comment by markoer** [comment]
We did discuss it, yes. The question is where to put it. Maybe /QA/ or /testing/, next to karaf/, kura/ and target-platform/? Eventually there could be automated tests there as well and/or results and other files.
