### ISSUE TITLE
Random device address cannot be connected

### ISSUE THREAD

**Issue by tohosokawa** [eclipse/kura#459]
I want to connect BLE device which has random device address.
But kura can connect only public device address.

I think that this is caused by the following fixed command.
https://github.com/eclipse/kura/blob/07a77c2d730465844f2ddcb3fe6920a046be994a/kura/org.eclipse.kura.linux.bluetooth/src/main/java/org/eclipse/kura/linux/bluetooth/util/BluetoothUtil.java#L308

`String[] command = { GATTTOOL, "-i", adapterName, "-b", address, "-I" };`

I'd like to try to add "-t random" argument. But I don't know how to build and use kura framework.

**Comment by cdealti** [comment]
@pierantoniomerlino is this supported by the new BLE API of ESF 5.1.0?

**Comment by pierantoniomerlino** [comment]
@cdealti I think so, but I haven't a BLE device with a random address to test.

**Comment by MMaiero** [comment]
@tohosokawa Could you please perform some testing with the new Kura APIs?
On how to build and execute the framework, you can find more details in the Official Kura documentation: https://eclipse.github.io/kura/

Best regards,
Matteo

**Comment by ashubhatt** [comment]
I tried with the the following apis and it is still not supporting random ble address: 
`org.eclipse.kura : org.eclipse.kura.api : 1.4.0`
`org.eclipse.kura : org.eclipse.kura.linux.bluetooth : 1.0.300`

**Comment by pierantoniomerlino** [comment]
@ashubhatt The implementation of the new API is in `org.eclipse.kura.ble.provider`, `org.eclipse.kura.ble.ibeacon.provider` and `org.eclipse.kura.ble.eddystone.provider`.
Moreover, you should use the **new** `org.eclipse.kura.example.ble.tisensortag.tinyb` example instead of the old one. 
Which device are you using?

**Comment by ashubhatt** [comment]
@pierantoniomerlino I am using SensiBLE device from [SensiEdge](https://www.sensiedge.com/sensible). I would not prefer tinyb because it is architecture dependent. I would like to keep my code as generic as possible.

**Comment by pierantoniomerlino** [comment]
@ashubhatt If you won't use tinyb, you'd use the old APIs. However, you have to modify the code to support random addresses. 
As correctly explained by @tohosokawa you'd add the "-t random" option in

https://github.com/eclipse/kura/blob/07a77c2d730465844f2ddcb3fe6920a046be994a/kura/org.eclipse.kura.linux.bluetooth/src/main/java/org/eclipse/kura/linux/bluetooth/util/BluetoothUtil.java#L308

Then, compile the bundle and copy in the target device.

**Comment by MMaiero** [comment]
Closing, as referring to old an deprecated APIs
