### ISSUE TITLE
Beaglebone install script not creating /etc/sysconfig

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#464]
The kura_install.sh script for the Beaglebone is missing a step to ensure the /etc/sysconfig directory exists. This directory is required for the firewall/iptables.

**Comment by ctron** [comment]
Shouldn't the Debian package create that?

**Comment by dwoodard1** [comment]
Kura still produces a kura_*installer.sh file as part of the build. This script can be used to install Kura without a package manager. The Debian package more or less wraps this script and provides additional dependency checking. Steps that are mandatory for Kura to be installed correctly we typically keep in these shell scripts.


On Aug 19, 2016, at 15:02, Jens Reimann <notifications@github.com<mailto:notifications@github.com>> wrote:


Shouldn't the Debian package create that?

**Comment by ctron** [comment]
Just to understand, what is the benefit of doing it that way, instead of using the Debian package manager?

**Comment by dwoodard1** [comment]
For systems that may not have package managers installed. To keep the build uniform, we create install scripts for all platforms (RPi, BBB, Intel Edison, etc.). For systems that typically have support for easily installing from DEB files (RPi, BBB), we wrap the installer in a DEB package. For those that don't (Edison), we just distribute the installer. 

This is mostly a historical artifact. The Debian packages were created shortly after the release of Kura. The script installers were in existence long before Kura released. There may be a better way of managing these, we just haven't seen it as a priority to modify the build.
