### ISSUE TITLE
CloudService.isConnected not shown in Web UI

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#465]
The Web UI currently does not show `CloudService.isConnected()`. Instead the `CloudService` is expected to reference to a `DataService` whose state is used instead.

**Comment by cdealti** [comment]
This will be addressed in #515. OK to close it?

**Comment by ctron** [comment]
So let's keep it open until this is resolved. Currently this is not mentioned in #515 as a requirement.

**Comment by cdealti** [comment]
Sure. The "CONNECTED" column in the table will call ``CloudService.isConnected()``.
The Web UI will only see ``CloudService``S.

**Comment by MMaiero** [comment]
I think that now this is solved, right @ctron?

**Comment by ctron** [comment]
@MMaiero Yes, I've seen that a few minutes ago.
