### ISSUE TITLE
There is no way to disable the default CloudServiceImpl

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#466]
When using a different implementation than `CloudServiceImpl` it is not possible to actually disable `CloudServiceImpl`.

The result is that two services with the interface `CloudService` will be registered and all default components, which only define a service dependency on `CloudService`, will just get any _random_ service.

**Comment by cdealti** [comment]
Selecting a specific CloudService is discussed in the Multiple Cloud Connection wiki page.

**Comment by ctron** [comment]
Agreed. But, for example, the ExamplePublisher dies bit make use of that. It just references the CloudService. So it becomes a 50:50 chance which service it gets.

**Comment by cdealti** [comment]
There is an issue on github to set the CloudService reference to the default one for the examples. But we did not implement it because maybe the user wants the Camel one.

**Comment by ctron** [comment]
Well I think there should be a way for the user to choose. So by configuring the ExampleProducer, not by making code changes.

Right now if you are following the path of using references you end up with just any service. If you only want to have one, then it would be fine if you switch on Camel and can _disable_ the default service. Which is currently not possible and which is the topic of this issue.

So what I am saying is, there should be a way do _disable_ the default cloud service using the UI. Or, if it is not properly configured, it should not be registered with OSGi.

But you are right, there is the problem how to work with multiple cloud services at the same time.

**Comment by ctron** [comment]
But that would only fix the issue for the ExamplePublisher. Still the issue remains with all other components which make use of the same pattern. As soon as you register a second CloudService instances it is no longer guaranteed that you receive the correct CloudService instance.

**Comment by cdealti** [comment]
I've made a proposal to configure the desired ``CloudService`` at runtime in the [Kura Multiple Connections Wiki page](https://github.com/eclipse/kura/wiki/Multiple-Cloud-Connections#selecting-a-connection-at-runtime)

**Comment by ctron** [comment]
Sounds like a good idea! I will give it a try on the branch an see what happens.

**Comment by ctron** [comment]
I just tried to implement that proposal on one of the gateway examples and it does not work.

In general it works, but when you configure a service which currently cannot be looked up, the component get disabled by the DS manager, what is expected. But then there is no more way to configure it using the Web UI.

So once you make a mistake, you cannot undo it.

**Comment by cdealti** [comment]
I think this is clearly stated in the Wiki. On the other hand you have this feature comes for free.

**Comment by ctron** [comment]
Ok, sorry. I totally overlooked that!

**Comment by cdealti** [comment]
Another idea could be to have a manager application in the UI that discovers all the components depending on a ``CloudService``, all the components providing a ``CloudService`` and updating the configuration of the consumers setting the .target property to the one of the pids of the providers.
This property should be automatically persisted so you don't need to do that at every reboot.

**Comment by ctron** [comment]
That sounds like really complex solution that will definitely break at some point.

I think there should really be a way to split up configuration vs service instance. There is no need to have a service if it cannot be or is not configured. So let the configuration service work without the need to have an actual instance of the component. Just using the metadata. Or at least allow the component to work with configuration 'optional'.

**Comment by ctron** [comment]
There seems to be another issue with the ".target" approach. When I do set the cardinality to "0..1", order be able to work with a missing reference, then setting a proper reference again seems not to activate that reference afterwards. Did you experience something like that?

**Comment by cdealti** [comment]
I believe you are exploring the dark side of the force ;) I haven't tried with the "0..1" cardinality. Are you testing with the ExamplePublisher?

**Comment by cdealti** [comment]
I think you need to specify a dynamic service injection along with cardinality 0..1 that should work

**Comment by ctron** [comment]
I was testing with one of the camel examples. But it should be the same for the example publisher.

Yes going with dynamic works. But then you really have to take care of the state and handle modifications. With static you would be stopped and started if I understood it correctly.

In the end I think that the whole ConfigurationService setup will have a hard time getting this done properly. Having the requirement of an actual service instance for configuration gives you a hard time. Which probably is also the cause for having a non-working instance of the CloudServiceImpl registered in the first time.

So for Camel I think I will just enhance the "kura-cloud" component to allow specifying a filter which then gets dynamically evaluated using a service tracker.

**Comment by cdealti** [comment]
> Yes going with dynamic works. But then you really have to take care of the state and handle modifications. With static you would be stopped and started if I understood it correctly.

Of course we prefer 1..1 static where possible. Minimum application complexity and maximum benefit from DS.

> Yes going with dynamic works. But then you really have to take care of the state and handle modifications. With static you would be stopped and started if I understood it correctly.

Exactly. it slightly defeats the advantage of using declarative services

**Comment by ctron** [comment]
I think if the ConfigurationService would be reworked to only work only metadata and configuration data from the ConfigurationAdmin that would work in most combinations.

**Comment by cdealti** [comment]
+1. Is your thinking in line with #341?

**Comment by ctron** [comment]
Re-reading 1.) in that context, yes!

**Comment by MMaiero** [comment]
@ctron Could we close this as the web ui now supports the removal of cloud services?

**Comment by ctron** [comment]
I think this is still an issue. True, the Web UI can let you configure multiple instances now.

But with every start there is still an unconfigured instance, throwing MQTT errors and providing a non-working instance.

But this is not something we should target for 2.1 anymore.

**Comment by cdealti** [comment]
@ctron if I read the first comment at the top, I'd say this is no longer an issue as the selection of the CloudService instance has been fixed where needed. Do you have any counter examples?
