### ISSUE TITLE
Question: What is the best way to update a device running Kura maintaining components and configurations?

### ISSUE THREAD

**Issue by alexcorvis84** [eclipse/kura#4701]
Hi,

I'd like to know what is the **best way to update a device running Kura** (_i.e_  version 5.1.1) to version 5.3.0 or other major version.

So, far I tried to stop Kura and install the .deb file but all the configurations I had under Cloud Connections are gone :( and my wire graph components now are red showing the following message:

![imagen](https://github.com/eclipse/kura/assets/44984326/de96c9dc-3e1a-4edc-9772-27e311ea2296)

So, I'd like to know what's the best procedure to update a device already running Kura without losing any configuration.

Thanks in advance!

**Comment by alexcorvis84** [comment]
I've checked this online [documentation](https://wiki.eclipse.org/Kura/Kura-Upgrade-Process). So far, the only one related to Kura upgrade process which seems a bit oudated ^^' but at least I have found some information that can help me...

![imagen](https://github.com/eclipse/kura/assets/44984326/b747b470-15d9-4ab1-9795-b0a80fd33c89)

The thing is, I have been able to compile the original code without errors and I have checked that the different **upgrade packages (.zip, .sh, )** have been created under the path **/kura/distrib/target.**

The _"problem"_, as far as I can see and according to the documentation above, is below:

```
For each release, a catalog will be generated of all the files in the release and their versions. For bundles, the bundle version will be used, and for other files the md5 hash will be computed. The diff between the previous and the new version will be computed by comparing this list.

Before upgrading the installer will check the currently installed version on the target by reading the kura.version value in the kura.properties file and reject the upgrade if the target release does not match. 
```

As far as I've checked, the **catalog has not been updated since [4.1.1 version](https://github.com/eclipse/kura/tree/develop/kura/distrib/RELEASE_INFO)** (?) and the upgrade packages created **expect** that **kura.version** installed on device should be 4.1.1 🙁 So I guess it won't help me as I want to update a device which is **runnning 5.1.1** to 5.2.0 version.

So, could you please kindly help me to address below questions?

- How could I generate the necessary upgrade package then? Is there any possibility?

- If so, what's is the process once the upgrade package has been created? Can it be uploaded directly through Kura UI? Should I use Kapua? Which upgrade package should I use (.zip, .sh)?

Many thanks in advance.

**Comment by MMaiero** [comment]
Hi, thanks for reaching out.
The upgrade path was contributed in the past but it is actually not maintained anymore.
Unfortunately we don't have the resources to support all those paths so, for now there is no supported upgrade process.
However, it would be great to have external contributions to the project that can re-enable that path and maintain it.

Right now the process to move from one version of Kura to the next relates to copy the snapshots and the other meaningful framework folders, perform the uninstall of the old version of Kura, install the new version and restore the previous copied data to the original location.

Best regards,
Matteo
