### ISSUE TITLE
Free subscription via CloudConnectionManager

### ISSUE THREAD

**Issue by pintify** [eclipse/kura#4713]
**Is your feature request related to a problem? Please describe.**
So far I've been using the CloudClient interface to create clients that can take advantage of DataService and MqttDataTransport functionality without the overload of Kapua topics structure and features. I've seen that the `cloud` of interfaces are marked for deprecation in favour of the `cloudconnection` interfaces. However, with the new interfaces it is not possible to make such amend to avoid the usage of `account/client/app` topic, or the parsing to KuraMessage.

**Describe the solution you'd like**
I'd like a way to implement over the DataService a way to connect to non-specific MQTT services.

**Comment by MMaiero** [comment]
Hi @pintify,
this has been a precise design decision to make the default solution less error prone.

To deal with those custom requirements, you may need to create a new cloud stack where you can define your topics and custom rules. The dataService APIs are still usable and an application on top of the dataService can leverage what you asked.

Best regards,
Matteo

**Comment by pintify** [comment]
Hi,

Ok, that makes also sense. I'll work on a custom Cloud stack. Thank you and best regards!
