### ISSUE TITLE
org.eclipse.kura.linux.net.modem.ModemDriver uses Java 7 API but has BREE of Java 6

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#473]
The bundle specifies a BREE of Java 6, however Java 7 API is being used by the source code:

https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/ModemDriver.java#L585

**Comment by cdealti** [comment]
Thanks Jens. @MMaiero shouldn't this nave been caught by jdeps?

**Comment by cdealti** [comment]
@ctron Nice catch! How did you find it?
Should be fixed by #474

**Comment by ctron** [comment]
I simply had the source code in an Eclipse IDE which had all three JDKs configured. PDE will do the validation for you.

To be honest, this was the only workspace I had configured with all three JDKs up until now.

Tycho could so some validation as well when multiple JDKs are configured [1], but I never tried it out. So I am not sure how good and easy that works,

[1] https://eclipse.org/tycho/sitedocs/tycho-compiler-plugin/compile-mojo.html#useJDK

**Comment by ctron** [comment]
Has this been merged in `develop`?

**Comment by cdealti** [comment]
Fixed on the release-2.0.1 branch that accordingly to our github flow will be merged on develop after the Kura 2.0.1 release.

________________________________
Da: Jens Reimann <notifications@github.com>
Inviato: martedì 30 agosto 2016 14.07.57
A: eclipse/kura
Cc: De Alti, Cristiano; State change
Oggetto: Re: [eclipse/kura] org.eclipse.kura.linux.net.modem.ModemDriver uses Java 7 API but has BREE of Java 6 (#473)


Has this been merged in develop?

-

**Comment by cdealti** [comment]
About the Tycho stuff above, we tried that but we have not been able to properly setup a Jenkins build. A local build works though. Se need to try it again. I believe it's important

**Comment by ctron** [comment]
I can imagine that. The easiest way is to just register all JDKs in the IDE. That way it will pop up pretty quickly.
