### ISSUE TITLE
Raspberry Pi Installation Documentation Error - Kura package name(s) changed?

### ISSUE THREAD

**Issue by Humancell** [eclipse/kura#4822]
When following the instructions here: https://eclipse.github.io/kura/docs-release-5.3/getting-started/raspberry-pi-raspberryos-quick-start/

There is an error in the naming of the Kura package in step #4.

Instructions:
``` wget http://download.eclipse.org/kura/releases/<version>/kura_<version>_raspberry-pi_installer.deb```

Actual names:
``` 
 kura_5.3.1_raspberry-pi-arm64-nn_installer.deb
 kura_5.3.1_raspberry-pi-arm64_installer.deb
 kura_5.3.1_raspberry-pi-armhf-nn_installer.deb
 kura_5.3.1_raspberry-pi-armhf_installer.deb
```

Also, there is no explanation of the differences between these packages and criteria to consider when choosing them.

1. Go to: https://eclipse.github.io/kura/docs-release-5.3/getting-started/raspberry-pi-raspberryos-quick-start/

 - Board: Raspberry Pi - All
 - OS version: All
 - Additional info:

**Comment by marcellorinaldo** [comment]
Hi @Humancell, thanks for reporting. The difference between the packages is detailed in the introductionary section: https://eclipse.github.io/kura/docs-release-5.3/getting-started/install-kura/.

For the names, we should correct the documentation to use `wget http://download.eclipse.org/kura/releases/<version>/kura_<version>_raspberry-pi-<arch>_installer.deb`.

Are you willing to make a little contribution? If so, just fork the Kura repo and open a PR agains `docs-develop` (see [CONTRIBUTING.md](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#making-your-changes)). We will then backport the changes to `docs-release-5.3`.

Thanks again for reporting.
