### ISSUE TITLE
installed modbus driver successfully  but cannot select the modbus option when create a new driver 

### ISSUE THREAD

**Issue by langlichong** [eclipse/kura#4824]
**Describe the bug**

**To Reproduce**
1. docker install kura 5.3.1
2. login and install modbus driver refs the doc: http://eclipse.github.io/kura/docs-release-5.3/kura-wires/usage-examples/modbus-application/#configure-modbus-device
3. drag the modbus link to ui: https://marketplace.eclipse.org/content/opc-ua-driver-eclipse-kura-45 
4. refresh ui 
5. goto 'Driver and Assets' menu  to create a modbus driver, but there is no modbus related options 
6. as former , installed a opc ua driver , then when create driver , then can find the opc-ua option , but still no modbus 

**Expected behavior**

**Screenshots**
![image](https://github.com/eclipse/kura/assets/11713419/d55ac4c5-641f-41d9-9bfb-7f5867c4a21f)
![image](https://github.com/eclipse/kura/assets/11713419/15218c0a-18fc-4f20-ab5e-daa9d356a031)

**Target Environment (please complete the following information):**
 - Board [e.g. Raspberry Pi 3]
 - OS version: [e.g. provide the result of `uname -a`]
 - Additional info: 

**Additional context**

**Comment by MMaiero** [comment]
Hi, sorry for the late reply.
I think there is an error in the documentation. Probably originated when we have ported the old documentation to this new format.
The Modbus protocol available in the Eclipse Kura project is just a protocol implementation that can be a dependency used by other applications running in the framework. But it does not expose itself as a driver. In fact as you can see from the name of the dp it is 'org.ecllipse.kura.protocol.modbus' while usually drivers have a name like 'org.eclipse.kura.driver.xx'.
That is the reason why you cannot see it as a driver after installed.
In the Eclipse Marketplace there are Modbus driver implementations that can be tested and expose themself directly as drivers. You may want to checkout those, to have a quick look at a possible integration between Kura and Modbus devices.

Sorry again for the error in the documentation. @salvatore-coppola will help us solve this issue in an upcoming pull request.

Please feel free to reach out if you have further questions or doubts.

Best regards,
Matteo

**Comment by salvatore-coppola** [comment]
Not an issue, unfortunately it's an error in the documentation.
