### ISSUE TITLE
Change b02bc9a7615ca559349f2b05485ea84fd80d6e77 breaks deployment of "sun.misc" bundles

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#485]
I think it was the change b02bc9a7615ca559349f2b05485ea84fd80d6e77 which does change the bundle versions of the two "sun.misc" fragments to "-SNAPSHOT", breaking the deployment.

However the Kura "distrib" scripts cannot handle non-Tycho bundles with "_SNAPSHOT". It get's converted to ".SNAPSHOT". This causes the following error during startup:

```
!ENTRY org.eclipse.osgi 4 0 2016-08-29 14:41:54.372
!MESSAGE Bundle reference:file:/opt/eclipse/kura/plugins/org.eclipse.kura.sun.misc_1.0.0-SNAPSHOT.jar@1 not found.

!ENTRY org.eclipse.osgi 4 0 2016-08-29 14:41:54.633
!MESSAGE Bundle reference:file:/opt/eclipse/kura/plugins/org.eclipse.kura.camel.sun.misc_1.0.0-SNAPSHOT.jar@3 not found.

```

**Comment by cdealti** [comment]
@dwoodard can you check if everything is OK on release-2.0.1?

**Comment by dwoodard1** [comment]
Seems to be ok on the release-2.0.1 branch:

64	RESOLVED    org.eclipse.kura.camel.sun.misc_1.0.0
	            Master=65
65	RESOLVED    org.apache.camel.camel-core_2.16.0
	            Fragments=64
66	RESOLVED    org.apache.camel.camel-core-osgi_2.16.0
67	RESOLVED    org.apache.camel.camel-kura_2.16.0
68	ACTIVE      org.eclipse.kura.camel_1.0.1

**Comment by ctron** [comment]
I don't see `org.eclipse.kura.sun.misc` in that list

**Comment by cdealti** [comment]
We will check tomorrow first thing

**Comment by dwoodard1** [comment]
Apologies, it was at the top of the list:

0	ACTIVE      org.eclipse.osgi_3.8.1.v20120830-144521
	            Fragments=2
1	ACTIVE      org.eclipse.equinox.cm_1.0.400.v20120522-1841
2	RESOLVED    org.eclipse.kura.sun.misc_1.0.0
	            Master=0

**Comment by ctron** [comment]
Ok, so that looks fine.

**Comment by MMaiero** [comment]
#452 was meant to solve that in develop. In release branch the bundles are not in -SNAPSHOT form, so the issue does not arise.
