### ISSUE TITLE
Command cloud App Null Pointer Exception

### ISSUE THREAD

**Issue by Coduz** [eclipse/kura#488]
Hi all,

I've found a problem with Kura v1.4.0. 

I'am working with the CMD-V1 application installed on Kura 1.4.0, trying to replicate the cloud management for the command. 

The problem was showing when I was missing the metric `command.command` in the message payload sent to the device and this was causing a Null pointer exception on the device and it was not responding with an error message. 

Here is the stacktrace:

> 2016-08-30 10:01:39,489 [MQTT Call: test] INFO  o.e.k.c.c.CloudServiceImpl - Message arrived on topic: $EDC/{some-account-name}/{some-client-id}/CMD-V1/EXEC/command
> 2016-08-30 10:01:39,490 [pool-1-thread-2] INFO  o.e.k.c.a.c.CommandCloudApp - EXECuting resource: command
> 2016-08-30 10:01:39,490 [pool-1-thread-2] ERROR o.e.k.c.a.c.CommandCloudApp - null command
> 2016-08-30 10:01:39,491 [pool-1-thread-2] ERROR o.e.k.c.a.c.CommandCloudApp - Error executing command {}
> java.lang.NullPointerException
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
> 	at java.lang.Runtime.exec(Runtime.java:617)
> 	at org.eclipse.kura.cloud.app.command.CommandCloudApp.createExecutionProcess(CommandCloudApp.java:352)
> 	at org.eclipse.kura.cloud.app.command.CommandCloudApp.execute(CommandCloudApp.java:205)
> 	at org.eclipse.kura.cloud.app.command.CommandCloudApp.doExec(CommandCloudApp.java:159)
> 	at org.eclipse.kura.cloud.MessageHandlerCallable.call(Cloudlet.java:294)
> 	at org.eclipse.kura.cloud.MessageHandlerCallable.call(Cloudlet.java:1)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> 2016-08-30 10:01:39,494 [pool-1-thread-2] ERROR o.e.k.c.c.CloudPayloadProtoBufEncoderImpl - During serialization, ignoring metric named: response.exception.message. The value is null.

Setting all the metrics accordingly does not lead to errors.

Regards, 

_Alberto_

**Comment by pierrepitiot** [comment]
I made the test using Rest API but I received an error message and I did not see an exception on the device. I sent an "empty" xml file (without command metric) with the curl command:
https://api-sandbox.everyware-cloud.com/v2/devices/00:60:0C:82:52:70/command.xml

and I received the following message:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error xmlns="http://eurotech.com/edc/2.0"><code>400</code><reason>Bad Request</reason><message>An illegal null value was provided for the argument deviceCommandInput.getCommand().</message></error>

I am not sure it is the same situation...

**Comment by Coduz** [comment]
Hi @pierrepitiot 

The message that you are seeing comes from EDC validation. In my case I don't receive any response from the device and then I got a timeout exception from the MqttClient.

@MMaiero: I'm trying to bring up the env to test the fix.

Regards, 

_Alberto_

**Comment by ghost** [comment]
Hello,
I'm trying to use the CMD-V1 service through mqtt but I have no idea about how build the payload. 
I'm doing a test trying to run a simple directory listing (ls -al) on my device.
I'm publishing on the topic "$EDC/[account-name]/[client-id]/CMD-V1/EXEC/command" using as payload: 

{"metrics":{"client.id":"0123456789","requester.client.id":"mqttspy","command.command":"ls -al"}}

I get no errors on kura.log and no reply.
Could someone let me know how correct the payload?
Best

**Comment by dwoodard1** [comment]
@insanefurion Thanks for your interest in Kura. For these types of questions, I would encourage you to use the Eclipse Kura mail list instead of adding to closed Issues.

There is a lot of documentation around remote management in Kura that can be found [here](http://eclipse.github.io/kura/ref/mqtt-namespace.html). The issue I see with your payload is the use of client.id instead of request.id. The payload should look something like:

```json
{
	"metrics": {
		"command.command": "pwd",
		"requester.client.id": "java-client",
		"request.id": "65e9b00f-5e87-4b45-8b06-b0f3ceb6c812"
	}
}
```

Keep in mind, if you are using plain JSON, you must make sure your CloudService tab is set to use plain JSON. Otherwise, you will need to encode your message with Google Protobufs.

![image](https://user-images.githubusercontent.com/1392274/36924391-40c7e348-1e23-11e8-8a64-5f7a15fe3069.png)
