### ISSUE TITLE
[Windows] org.eclipse.kura.windows.system bundle is installed in every distrib

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#492]
@markcullen @malikm 
...while it should only be installed on Windows related distributions.

**Comment by malikm** [comment]
Would a custom profile for target-platform to build Windows components be the right solution ?

**Comment by cdealti** [comment]
@malikm I don't think this is necessary for now. Just make sure that during the build of ``distrib`` Windows specific bundles are not copied to Linux based distribs.

**Comment by malikm** [comment]
Should be fixed by #532
