### ISSUE TITLE
[Windows] Review versions of Windows related bundles

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#493]
@malikm @markcullen 

On the develop branch:
1. the `<version>` in pom files MUST have `-SNAPSHOT`
2. the `Bundle-Version` in the bundle MANIFEST MUST have the `.qualifier`
3. update distrib/config/kura.build.properties
4. update target-platform/config/kura.target-platform.build.properties

**Comment by malikm** [comment]
Should be resolved with 8f58b7b8931c841f95daebe316568a34292557d5
