### ISSUE TITLE
SystemServiceImpl uses method from Java  7 but declares a BREE of Java 6

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#497]
org.eclipse.kura.core.system.SystemServiceImpl makes a call to  `java.net.NetworkInterface#getIndex()` [1] which is only available since Java 7.

However the bundle declares an execution environment of Java 6.

[1] http://download.java.net/jdk7/archive/b123/docs/api/java/net/NetworkInterface.html#getIndex%28%29

**Comment by cdealti** [comment]
@ctron nice catch again!
@malikm It looks like this has been added merging [the Windows port](https://github.com/eclipse/kura/commit/741220741bf613a43040afaa890f37f96ccf0c6d).

Can you please provide a patch to avoid dependencies on Java 7 runtime?

**Comment by cdealti** [comment]
@malikm Can you please sanitize this as soon as you have a chance?

**Comment by malikm** [comment]
Fixed by #533

**Comment by malikm** [comment]
Updated accordingly.

**Comment by cdealti** [comment]
Thanks Martin.
