### ISSUE TITLE
CQ for Quartz Scheduler

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#498]
http://www.quartz-scheduler.org

**Comment by dwoodard1** [comment]
@amitjoy Are you saying we need to create a CQ for the Quartz scheduler or that it is already done?

**Comment by amitjoy** [comment]
@dwoodard1 We need to create a CQ for it as the **Timer** logical block in Kura Wires is using it for extensive functionalities

**Comment by cdealti** [comment]
It's a 3.2MB jar. Quite heavy.

Cristiano

**Comment by amitjoy** [comment]
@cdealti You just have to file a CQ for quartz-2.2.3.jar (660 KB) and quartz-jobs-2.2.3.jar (34 KB).

**Comment by cdealti** [comment]
Yes, I've realized that. Of course the SimpleTimer will not need it, right?

________________________________
Da: Amit Kumar Mondal <notifications@github.com>
Inviato: sabato 3 settembre 2016 09.16.11
A: eclipse/kura
Cc: De Alti, Cristiano; Mention
Oggetto: Re: [eclipse/kura] CQ for Quartz Scheduler (#498)


@cdealti<https://github.com/cdealti> You just have to file a CQ for quartz-2.2.3.jar (660 KB) and quartz-jobs-2.2.3.jar (34 KB).

-

**Comment by amitjoy** [comment]
@cdealti We thought of extending the Timer functionalities to incorporate CRON jobs along with basic scheduling functionalities using simple seconds. This would definitely make Timer more powerful and flexible for Industrial IoT Scenarios.

**Comment by amitjoy** [comment]
@cdealti Would you kindly update this issue with the CQ reference link?

**Comment by cdealti** [comment]
CQ 12019

**Comment by cdealti** [comment]
@amitjoy do you have access to [1]?

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12019

**Comment by amitjoy** [comment]
I don't think so. I tried to use my usual username and password which I use for Eclipse but that doesn't work for IPZilla.

**Comment by cdealti** [comment]
Ok, we are required to remove from **these** sources:

https://github.com/quartz-scheduler/quartz/tree/quartz-2.2.3

all the source code not needed by:

1. https://mvnrepository.com/artifact/org.quartz-scheduler/quartz/2.2.3
2. https://mvnrepository.com/artifact/org.quartz-scheduler/quartz-jobs/2.2.3

Can you please do that? 

Hi Christiano,

I would suggest to avoid any "ahead of time" approvals - your CQ here should
only cover what you definitely need, which are the two jars that you mention
(imho it is ok to combine them in one CQ here).
But the source zip should then also only contain the sources for the classes in
these jars. So you should remove all the rest from it, specifially also all
tests etc. what is not relevant for the jars.

Regards,
Kai

**Comment by ctron** [comment]
Can't you just attach the maven source attachments?

**Comment by dwoodard1** [comment]
I can't find where they have made the source jars available for download, but the build is using the maven-source-plugin. So, if you build the project you should get the source jar. I have found source jars are the best/quickest way for Eclipse to review CQs.

**Comment by amitjoy** [comment]
Here it goes: https://repo1.maven.org/maven2/org/quartz-scheduler/quartz/2.2.3/

**Comment by amitjoy** [comment]
@cdealti @MMaiero @dwoodard1 @ctron @LucaDazi  Could you kindly assign `Kura Wires` and `CQ` labels to this issue? It would be easy to track.

**Comment by dwoodard1** [comment]
@amitjoy Thanks! Don't know why I couldn't find it.

**Comment by cdealti** [comment]
@amitjoy The Quartz CQ [1]
Is still pending waiting for the "depopulated" Quartz sources (see my comment above). Can you please prepare this package?

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12019

**Comment by amitjoy** [comment]
@cdealti The quartz sources are as follows:

http://search.maven.org/remotecontent?filepath=org/quartz-scheduler/quartz-jobs/2.2.3/quartz-jobs-2.2.3-sources.jar
http://search.maven.org/remotecontent?filepath=org/quartz-scheduler/quartz/2.2.3/quartz-2.2.3-sources.jar

**Comment by MMaiero** [comment]
@amitjoy We can close this, right?

**Comment by amitjoy** [comment]
@MMaiero Yeah you can. It has already been approved.
