### ISSUE TITLE
[Windows] Add documentation

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#502]
See
http://dev.eclipse.org/mhonarc/lists/kura-dev/msg00523.html

**Comment by cdealti** [comment]
@malikm @markcullen it should be submitted as a PR to the [Github Pages](https://github.com/eclipse/kura/tree/gh-pages) branch.

**Comment by cdealti** [comment]
Due to all these legal aspects and the lack of interest on the Windows port I propose to close this issue and remove from Kura all the Windows specific code.
@dwoodard1 @malikm @markcullen what do you think?

**Comment by markcullen** [comment]
Hi Cristiano

Have you discussed this with Marco ?

While I realise that we have not been able to make much progress with this I don’t think we should abandon the project.

Cheers

Mark

**Comment by diegovisentin** [comment]
IMO Kura needs to be fully supported on Windows 10 IoT

**Comment by cdealti** [comment]
Closing. See #637
