### ISSUE TITLE
Bump Bouncy Castle to 1.74

### ISSUE THREAD

**Issue by gnunzi** [eclipse/kura#5025]
**Is your feature request related to a problem? Please describe.**

The Bouncy Castle lib is used for encryption, e.g. in the keystore.

The version 1.7.1 is reported to have vulnerabilities, see 

- https://github.com/advisories/GHSA-wjxj-5m7g-mg7q
- https://github.com/advisories/GHSA-hr8g-6v94-x4m9

**Describe the solution you'd like**

Bump org.bouncycastle.version to 1.7.4 . Apparently this is specificied in the parameters `org.bouncycastle.version `and `org.bouncycastle.jar.version`.

**Describe alternatives you've considered**

I thought github would create a PR automatically. Maybe the pr from bot was silented or similar.

**Additional context**

I do get an automatc pr from github bot dependency to bump bc to 1.7.4, so I think this should be done in Kura as well.

**Comment by MMaiero** [comment]
Hi, thanks for reporting.
We are already looking into this.
Unfortunately, a build based on Tycho makes it difficult for the dependant to provide PRs with updated dependencies.

Best regards,
Matteo

**Comment by mattdibi** [comment]
Addressed in #5027
