### ISSUE TITLE
how config kura project in eclipse in order to  run or debug

### ISSUE THREAD

**Issue by chsunnyboy** [eclipse/kura#5035]
i do not know how to config the kura project in eclipse to make it run or debug, who knows that ?  appreciate your methods  very much

**Comment by mattdibi** [comment]
Hello there @chsunnyboy,

you might want to take a look at the Kura documentation page:
- [Running the Eclipse Kura Emulator](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/development-environment-setup/#run-the-eclipse-kura-emulator)
- [Remote debugging on target platform](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/remote-debugging-on-target-platform/)
- [Deploy and Debug Applications](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/deploy-and-debug-applications/)

Hope this helps.

**Comment by chsunnyboy** [comment]
> Hello there @chsunnyboy,
> 
> you might want to take a look at the Kura documentation page:
> 
> * [Running the Eclipse Kura Emulator](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/development-environment-setup/#run-the-eclipse-kura-emulator)
> * [Remote debugging on target platform](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/remote-debugging-on-target-platform/)
> * [Deploy and Debug Applications](https://eclipse.github.io/kura/docs-release-5.4/java-application-development/deploy-and-debug-applications/)
> 
> Hope this helps.


thanks anyway, but I have tried the two emulator below,but in the runtime there were many bundles were not resolved，and there were still many errors about import-package in the MANIFEAST.MF file  like the imgs

Eclipse Kura Emulator    
Kura_Emulator

<img width="948" alt="企业微信截图_17017598571686" src="https://github.com/eclipse/kura/assets/24762732/808dcc66-738d-4661-9266-0bce017e8c34">


<img width="593" alt="企业微信截图_17017606061711110" src="https://github.com/eclipse/kura/assets/24762732/776a56e0-960c-49ea-9535-71ce0b03cdf1">

**Comment by mattdibi** [comment]
@salvatore-coppola any thought on this?

Meanwhile I'm moving this to Discussion which is a better fit
