### ISSUE TITLE
Ability to add / remove single channels from an asset programmatically

### ISSUE THREAD

**Issue by chicco785** [eclipse/kura#5041]
**Is your feature request related to a problem? Please describe.**

I am looking for a way to use kura as a scada gateway that is easy to program in term of defining channels that are reported to the scada.

**Describe the solution you'd like**

An API (Rest or MQTT) that allows to add or remove a channel from an asset configuration.

**Describe alternatives you've considered**

Recreating the configuration every time :/

**Additional context**

**Comment by mattdibi** [comment]
Ciao @chicco785,

thanks for reaching out.

ATM we don't have a specific REST API for doing that but you need to use directly the Configuration Service (see: https://eclipse.github.io/kura/docs-release-5.4/references/rest-apis/rest-configuration-service-v2/)

**Comment by chicco785** [comment]
Hi @mattdibi

I saw the api and it is possible to update a service pid configuration, so if a service, include assets, I am able to update the whole asset configuration. (Correct me if I am wrong).

In our use case, we are sharing quite a bulk of data points from a middleware, so the json payload will be quite big as well, which is not optimal. Instead if you could update a portion of the configuration (e.g. add a channel / remove a channel) payloads will be smaller.

**Comment by mattdibi** [comment]
Unfortunately with our current ConfigurationService implementation you can do a partial update that adds properties but you cannot remove them (i.e. the provided configuration will be always be **merged** with the existing one). Therefore, in your case, you will be able **to add channels** with a partial update but you will not be able **to remove them**.. to remove them you will have to delete and recreate the asset.

Hope this helps

**Comment by chicco785** [comment]
thx @mattdibi it's a good compromise :)

**Comment by mattdibi** [comment]
Closing this as answered. Feel free to reopen if needed.
