### ISSUE TITLE
Upgrade SLF4J to 1.7.21

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#511]
Apache Camel 2.17.2 requires SLF4J 1.7.21

**Comment by ctron** [comment]
Started CQs:
* https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11943
* https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11944

**Comment by MMaiero** [comment]
I think we can close, right?

**Comment by cdealti** [comment]
Yes per #514.
