### ISSUE TITLE
Fix or remove "jdeps" build step

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#512]
It seems that the "jdeps" build step does not work as expected (see #473 and #497), however it takes quite some time during the Kura build.

So it should either be fixed or removed.

**Comment by MMaiero** [comment]
@ctron Jdeps step has the purpose to verify that the code is compliant with Java 8 compact 2 profile. Currently we need a step in our build to verify that the code is Java 6 or 7 compliant.
