### ISSUE TITLE
[Web UI] Implement Cloud Services UI

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#515]
The Web UI lacks the ability to create, configure and manage Cloud Services.
See #444 and #189 for a discussion on the requirements.

![image](https://cloud.githubusercontent.com/assets/1225835/18272119/667012b6-7436-11e6-9cbc-b06159f50c99.png)

**Comment by cdealti** [comment]
@ctron Matteo will take care of this. Please coordinate with him if you plan to work on the affected parts of the Web UI.

**Comment by pgufAtIBM** [comment]
its true, if connection to cloud (in multiple cloud support) is there, is not visible in web ui. you can see it in log file kura.log. 
currently you also cannot select which cloud service is currently active in system -> status of web ui.
I have used DataService -> autoconnect = true. Then your cloud instance connects to desired cloud (if connection is successful you can see only in your cloud platform (f. ex. Watson IoT) or in Kura log

**Comment by cdealti** [comment]
@pgufAtIBM thanks for the feedback. Do you agree on the plan to modify the Web UI as shown in the above mockup? As you can see in the mockup your WatsonIoT Cloud Service Factory is listed.

**Comment by pgufAtIBM** [comment]
I like this approach, so a user can select the cloud component, and not x services on the left side are listed.
What would be good: able to provide logging parts to web ui. So the user can see that diagnostic logs for example are published to cloud. or why a device cannot be instanciated on cloud

**Comment by MMaiero** [comment]
Closing due to #626 merging
