### ISSUE TITLE
Cannot access Web UI on VPS

### ISSUE THREAD

**Issue by devaskim** [eclipse/kura#5177]
**Describe the bug**
On my VPS with only IPv6 address I ran Kura in Docker with opened 8443 port both in iptables and Docker Compose file. But I cannot open Web UI via `http://[ipv6_adress_of_vps]:8443`, just like there is no application on this address and port. 

At the same time I can open Web UI via  `http://localhost:8443`, if I run Kura in Docker locally on my laptop.

I assume it is about network configuration options, but how can I change them without access to Web UI?

**Expected behavior**
Have access to Kura Web UI not only via `localhost` and out of the box.

**Target Environment (please complete the following information):**
 - Board: no board
 - OS version: Ubuntu 22 LTS
 - Additional info: VPS with only IPv6 address

**Comment by pierantoniomerlino** [comment]
Hi @devaskim,

the docker container provided by Kura is based on a no-network version. So, Kura does not manage the firewall/network configuration. Even if you had access to the Kura WebUi you wouldn't be able to change the configuration.

Could you please add some more informations about you setup? 
What's the output of `docker ps -a`?

**Comment by devaskim** [comment]
Hi @pierantoniomerlino 

I just do `docker compose up` for the following Docker Compose script
```
version: '3.0'
services:
  kura:
    restart: always
    image: "eclipse/kura:latest"
    container_name: kura
    ports:
      - "8443:8443"

```
Then wait some time. E.g. until see in the logs:
```
kura  | 2024-03-13T15:04:52,375 [Start Level: Equinox Container: 6d56f17f-bff8-4399-b10c-ce742136ed5f] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering SelfConfiguringComponent - org.eclipse.kura.web.Console....
kura  | 2024-03-13T15:04:52,375 [Start Level: Equinox Container: 6d56f17f-bff8-4399-b10c-ce742136ed5f] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering SelfConfiguringComponent - org.eclipse.kura.web.Console....Done
kura  | 2024-03-13T15:04:52,406 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask started.
kura  | 2024-03-13T15:04:52,406 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Delete confirmed messages...
kura  | 2024-03-13T15:04:52,420 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
```
And finally go to browser, open `http://[my_ip_v6_address]:8443` and see this

![Скриншот 13-03-2024 200733](https://github.com/eclipse/kura/assets/86909129/0794ba2d-9ab6-40ec-bee2-21faf22c6183)

Here is output of `docker compose ps -a`
```
admin@ssdnodes-den:~/kura$ docker compose ps -a
NAME      IMAGE                 COMMAND                  SERVICE   CREATED              STATUS              PORTS
kura      eclipse/kura:latest   "/usr/local/bin/kura…"   kura      About a minute ago   Up About a minute   443/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp
admin@ssdnodes-den:~/kura$ 
```
My iptables rules
```
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9100
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9000
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8883
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8443
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:postgresql
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:1883
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
```

**Comment by pierantoniomerlino** [comment]
Can you please run the container mapping the 443 port, instead of the 8443?

```
version: '3.0'
services:
  kura:
    restart: always
    image: "eclipse/kura:latest"
    container_name: kura
    ports:
      - "443:443"
```

Moreover, please connect using `https` as show [here](https://eclipse.github.io/kura/docs-release-5.4/getting-started/docker-quick-start/).

**Comment by devaskim** [comment]
Great! 
At least with `https` and `443` it works as expected, but with `https` and `8443` - no. So does Kura works only with standard https port?

I took `8443` port [from this page](https://eclipse.dev/kura/downloads.php)

![Скриншот 13-03-2024 202810](https://github.com/eclipse/kura/assets/86909129/e7a24930-726e-46f5-b153-1030f3cbac1f)

Thanks @pierantoniomerlino

**Comment by mattdibi** [comment]
> Great! At least with `https` and `443` it works as expected, but with `https` and `8443` - no. So does Kura works only with standard https port?
> 
> I took `8443` port [from this page](https://eclipse.dev/kura/downloads.php)
> 
> ![Скриншот 13-03-2024 202810](https://private-user-images.githubusercontent.com/86909129/312521782-e7a24930-726e-46f5-b153-1030f3cbac1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDQ2MTAsIm5iZiI6MTcxMDM0NDMxMCwicGF0aCI6Ii84NjkwOTEyOS8zMTI1MjE3ODItZTdhMjQ5MzAtNzI2ZS00NmY1LWIxNTMtMTAzMGYzY2JhYzFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5M2Y3N2QxZmJmMDE3NDNkMWU2MjgxZDNkZjhkYmIyZjBjNzczZGJmYjI3YTAwYzExY2U1ZWRkY2MyNjBkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMXqUSkspps7icp4TFMXG4f9zOO9n8UEH717W5sxreE)
> 
> Thanks @pierantoniomerlino

Mh... that bit of documentation is quite outdated. We should remove it.

Anyway @devaskim thanks for reporting. Closing as resolved.

**Comment by pierantoniomerlino** [comment]
@devaskim It is possible to change the standard webUI port: select the **Security** section and click on the **Http Service**. From there you can change the default port.

**Comment by devaskim** [comment]
Thanks @pierantoniomerlino
