### ISSUE TITLE
[Net] PppFactory is not a factory and its design is wrong

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#520]
`PppFactory` is used by `ModemMonitorServiceImpl` to both create new instances and return already created instances. There are several defects:
1. It's not a factory. It's more similar to the [Multiton Pattern](https://en.wikipedia.org/wiki/Multiton_pattern).
2. `obtainPppService(String iface, String port)` is misleading and error prone. Internally only the interface name, for example `ppp0` is used as the key.

The above can lead to the following scenario:
- Initially `obtainPppService(ppp0, /dev/ttyACM0)` creates a new `IModemLinkService` instance for the interface `ppp0` running on the modem serial port `/dev/ttyACM0`. This instance is tracked internally by PppFactory by the interface name `ppp0`. The monitor will spawn `pppd` on `/dev/ttyACM0`
- The modem gets reset/unplugged (for any reason). On Linux is entirely possible that the serial port device name changes for example to `/dev/ttyACM1`.
- In the next loop iteration the monitor will call `obtainPppService(ppp0, /dev/ttyACM1)` again but this will return the previous instance since the serial port name does not matter. The monitor will spawn `pppd` on `/dev/ttyACM0` which is clearly wrong.

**Comment by pierantoniomerlino** [comment]
A quick and dirty fix is to release the PppService after a modem reset:

```
modem.reset();
PppFactory.releasePppService(ifaceName);
pppSt = PppState.NOT_CONNECTED;
```

The PppService will be created again by the PppFactoy with the updated port at the next monitor run.
