### ISSUE TITLE
Warning Instead Error When Creating a Driver Without Factory

### ISSUE THREAD

**Issue by daodol** [eclipse/kura#5290]
kura 5.4.2 This issue still exists
os:mint linux 21
#3240

**Comment by MMaiero** [comment]
Hi @daodol 
thanks for reporting!

We'll have a look as soon as possible to implement this improvement.

Best regards

**Comment by MMaiero** [comment]
Hello,
just checked in Kura 5.5.0 and the issue does not appear to still be present:
![image](https://github.com/eclipse/kura/assets/10448126/35f5f0b2-12e5-4a89-a820-7f668b297523)

Marking this as closed. Please feel free to reopen if needed

**Comment by daodol** [comment]
why close?

**Comment by MMaiero** [comment]
As said in the comment, the original issue is now fixed in Kura 5.5.0. That's the reason for closing it. Feel free to reopen it if needed

**Comment by daodol** [comment]
> As said in the comment, the original issue is now fixed in Kura 5.5.0. That's the reason for closing it. Feel free to reopen it if needed

ok,sorry,I only saw the word 'still', I didn't see 'no'
