### ISSUE TITLE
Question: What is the difference between issues here and in Bugzilla? 

### ISSUE THREAD

**Issue by alisajedi** [eclipse/kura#531]
Hello

- This is not a bug report. I just have a question. I am a researcher at University of Alberta, doing research on bug assignment in Github and Bugzilla.

This project is also on Mozilla ( https://bugs.eclipse.org/bugs/buglist.cgi?component=Core&product=Kura ) and there are some issues there.

What is the difference between the bugs reported in Bugzilla and the issues reported here in Github? 
My intuition is that the issues listed in the Github repository are the ones that the developers found under development, but the bugs addressed in Bugzilla are for every user in the open source community. 
Is that true? Please correct me if I'm wrong.
Thank you.

**Comment by cdealti** [comment]
Hi,
Se used to use Bugzilla for bug tracking initially but then we migrated them to Github issues.
Github issues are intended to be used by everyone.

**Comment by alisajedi** [comment]
Thank you @cdealti .
