### ISSUE TITLE
[Legal] Missing CQs for slf4j.jdk14 1.6.4

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#535]
The [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11952) has been filed

David Woodard wrote:

> Hi Wayne,
> I can confirm that Jens is correct, we filed the CQs for SL4J API [1] and core [2], but not for the JDK binding. What is the procedure for having previous releases amended. I assume the first step will be to file the CQ for the JDK binding, but please confirm.
> 
> [1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=7850
> [2] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=7849

> Thanks,
> --Dave

Jens Reimann wrote:

> Hi,
> sorry for coming up with another CQ issue...
> While working on the upgrade to SLF4J 1.7.21 I did find two CQs for slf4j-api and slfj4-log4j12 but none > for slf4j-jdk14.
> However it is present in the downloads since version 1.4.0:
> kura_1.4.0_raspberry-pi-2/plugins/slf4j.jdk14_1.6.4.jar
> Or did I miss something?
> Cheers
> Jens

**Comment by dwoodard1** [comment]
@cdealti Unfortunately, the CQ you referenced was filed by Jens for the updated version of SLF4J-JDK. We may still need to file a CQ for the version used in previous releases.

**Comment by dwoodard1** [comment]
The CQ has been approved: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11974
 
I have reached out to Wayne to determine what needs to happen next.

**Comment by cdealti** [comment]
@dwoodard1 any updates from Wayne?

**Comment by dwoodard1** [comment]
@cdealti @waynebeaton Since the CQ was approved, we are good to go. I am closing.
