### ISSUE TITLE
Make Equinox version configurable in Windows launcher

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#537]
Extracting task from #499: Fix up the windows launcher to not hard-code the Equinox version. Allow some way to specify the Equinox version which should be started.

This should work hand in hand with the Kura build to use different Maven profiles for different Equinox versions.

**Comment by cdealti** [comment]
@ctron I believe this can be closed

**Comment by ctron** [comment]
I don't think so.

**Comment by cdealti** [comment]
There is no Windows distrib for Kura yet.
However let's keep this for a while.

**Comment by cdealti** [comment]
Due to all these legal aspects and the lack of interest on the Windows port I propose to close this issue and remove from Kura all the Windows specific code.
@dwoodard1 @malikm @markcullen what do you think?

**Comment by cdealti** [comment]
Closing. See #637
