### ISSUE TITLE
[Cloud] Required changes in CloudServiceFactory

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#539]
While working on #515 I've noticed the impossibility to relate a CloudServiceFactory instance with its cloud stacks.
In my opinion we should change that API moving its package to version 1.1.0, including a new variable named `kura.cloud.service.factory.pid` and a new method `getComponentConfigurations(String pid)`.

The `kura.cloud.service.factory.pid` will be used by the compliant cloud services instances to relate the specific instance with the constructor factory that generated it. In this way it will be possible, by searching in the cloud component properties, to map the instance with the factory.
The new UI developed to solve #515 will be able to filter the services that provide the `kura.cloud.service.factory.pid` giving them the possibility to be grouped and managed in the new "Cloud Services" section. To keep backward compatibility, the old cloud services implementations will continue to be available in the "Services" section of the web ui.

The `getComponentConfigurations(String pid)` will be useful to get the component configurations for all the components generated by the factory: the method will return a `List<ComponentConfiguration>` that, for the specified cloud service instance, will fetch the configuration of all the components of the identified cloud stack.

**Comment by ctron** [comment]
Why not simply make the requirement that every service belonging to that group has to register an additional OSGi property, like `kura.cloud.service.pid`. All services sharing the same value are grouped together.

That way you would avoid adding another method.

**Comment by MMaiero** [comment]
I've created a new branch named enh_cloudServices-separate-ui where I've implemented a first version of the cloud services Ui for web2.

It required to move the api and core packages to version 1.0.10 (snapshot) and upgrading org.eclipse.kura.cloud.factory to version 1.1.0.

At the end, the CloudServiceFactory api required the definition of a new property, KURA_CLOUD_SERVICE_FACTORY_PID and the definition of a new method getStackComponentsPids.

The getStackComponentsPids takes the pid of the cloud service and gets, from the factory, the list of pids that compose the cloud stack. The choice to add this method is related to the fact that only the factory knows how to create the stack and the final naming. This also guarantees to get the same order for every call, in a defined cloud stack (we cannot think to always have the schema cloudService-DataService-DataTransport).

Furthermore I've added few properties in some component definition files:

- **kura.ui.service.hide**: specified in a service pertaining to a cloud stack, allows the web ui to hide this service when rendering the services section;

- **kura.ui.csf.pid.default**: optional cloud factory component parameter that allows to specify a default suggested format for the pid that the user has to put in the web ui;

- **kura.ui.csf.pid.regex**: optional cloud factory component parameter that allows to specify the regex that will be used to validate the user input in the web ui.

In the web2 bundle, apart the needed changes server and client side to implement the new cloud section, I've modified ServicesUi creating an Abstract class that can be reused for other extensions and adapted GwtComponentServiceImpl.
For this last class the refactoring is still in progress and the code should be improved.

Following some screenshots of the resulting interface:
![screen1](https://cloud.githubusercontent.com/assets/10448126/18786267/60524cc2-819d-11e6-8b4d-00a3bd5deb3b.png)
![screen2](https://cloud.githubusercontent.com/assets/10448126/18786269/607653e2-819d-11e6-92c2-004dcf38e585.png)
![screen3](https://cloud.githubusercontent.com/assets/10448126/18786270/60769744-819d-11e6-8bae-66eab9c0f8ff.png)
![screen4](https://cloud.githubusercontent.com/assets/10448126/18786272/60782cbc-819d-11e6-85b9-6ed20f2eb90d.png)
![screen5](https://cloud.githubusercontent.com/assets/10448126/18786268/6074e8cc-819d-11e6-9fac-afdbc61cbd16.png)
![screen6](https://cloud.githubusercontent.com/assets/10448126/18786271/60771796-819d-11e6-9a75-27809503e5c9.png)

Please, give it a try! 
Suggestions and improvements are welcome!

**Comment by cdealti** [comment]
@pgufAtIBM Can you give it a try?

**Comment by MMaiero** [comment]
Closing since #626 was merged

**Comment by cdealti** [comment]
I've given this a try. Nice work.
A few notes:
1. Trying with another CloudService provider I've obtained as a preview by @pgufAtIBM the order of the tabs representing the configurations of the stack layers in the **Cloud Services** menu appears to be alphabetical. Not a big deal but I guess it would be better to use the order returned by ``CloudServiceFactory.getStackComponentsPids`` i.e. the leftmost should always be the highest layer of the stack.

2. In the **Status** menu, what is the difference between the **Service Status** and **Connection Status**?

**Comment by MMaiero** [comment]
@cdealti I've created PR #703 to address those issues. In particular for points 1 and 3. 
Regarding point 2 it was caused by commit  ff8000ecfbf8557184869dbf488dfb53f38e0c2f. I suppose that that duplication is not needed so, in the PR, I've removed the code.

**Comment by MMaiero** [comment]
As pointed in another issue, we are missing some integration documentation that should be published in Kura site, in order to help people to integrate their cloud services, but I think that what described in this issue is a good starting point.
