### ISSUE TITLE
Fix MQTT test credentials

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#543]
Currently the `AllCoreTests` have some hardcoded MQTT credentials pointing towards a eurotech hosted MQTT server which is not reachable anymore:

```
s_logger.info("Changing cloud credentials...");
mqttProps.put("broker-url", "mqtt://broker-sandbox.everyware-cloud.com:1883/");
mqttProps.put("topic.context.account-name", "ethdev");
mqttProps.put("username", "ethdev_broker");
mqttProps.put("password", "We!come12345");
```

This should be fixed to use some publicly available server for testing.

**Comment by ctron** [comment]
I would suggest to make this configurable, pointing to some default like "iot.eclipse.org".

**Comment by dwoodard1** [comment]
@ctron I think this can be tracked in issue #519 . I agree, making the MQTT credentials configurable is a good idea.

@cdealti Did you have a chance to look into #519? If you agree this is duplicated for no reason, I can clean it up today.

**Comment by cdealti** [comment]
@ctron if your plan is to review the existing test please hold on.
I have a local branch improving a little the mess.

**Comment by ctron** [comment]
@cdealti No, I just wanted to open a task so that it doesn't get forgotten.

**Comment by cdealti** [comment]
@ctron since we have embedded an local MQTT broker which does not require authentication I believe this can be closed for now
