### ISSUE TITLE
Web UI shows red-connector although state is CONNECTED

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#544]
Having a state of CONNECTED still shows a red connector for me:

![kura_red](https://cloud.githubusercontent.com/assets/202474/18511882/997baf0c-7a86-11e6-96cc-9fed10ef5702.png)

Reloading the page did not help.

**Comment by MMaiero** [comment]
Commit 4b9d9b979e403c824dc6131708f76374d1a1b866 broke this.
Should be solved by PR #561
