### ISSUE TITLE
[Configuration] Configuration Service may miss configuration-policy=optional components

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#547]
See #536

**Comment by MMaiero** [comment]
@cdealti Do we plan to fix this in 2.1.0 or 2.2.0?

**Comment by cdealti** [comment]
@dwoodard1 I don't know of any complains about this. Can we postpone it?

**Comment by dwoodard1** [comment]
I believe it is okay. I doubt there are many use cases of creating a ConfigurableComponent with no configuration policy.

**Comment by cdealti** [comment]
@dwoodard1  This is unlikely to be fixed with the current implementation of the ConfigurationService without creating a monster. Feel free to re-open it.
