### ISSUE TITLE
Convert textile documentation to markdown

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#549]
GitHub has deprecated textile as a markup language. Still the Kura documentation contains textile content.

GitHub sends out an e-mail every time the Kura documentation is updated that this functionality will stop working at any time.

This content should be converted to markdown, since this is the most used format in the Kura documentation right now.

Also see: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by dwoodard1** [comment]
Cleaning this up now. Should push something within the next day.

**Comment by dwoodard1** [comment]
99% Done. The textile has been removed and everything is now markdown. I still need to clean up the syntax in the namespace document, but it is a large document and will take a little longer.

**Comment by dwoodard1** [comment]
Done.
