### ISSUE TITLE
[Modbus] String evaluation returns false

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#550]
In org.eclipse.kura.protocol.modbus.ModbusProtocolDevice the following code returns always false because of the wrong string comparison. 

``` java
if(connectionConfig.getProperty("serialMode")!=null){
    m_serial485=(connectionConfig.getProperty("serialMode")==SERIAL_485);
    if(m_serial485){
        if (((gpioSwitchPin = connectionConfig.getProperty("serialGPIOswitch"))==null)
                || ((gpioRsModePin = connectionConfig.getProperty("serialGPIOrsmode"))==null))
            throw new ModbusProtocolException(ModbusProtocolErrorCode.INVALID_CONFIGURATION);
    }
}
```

However, this snippet checks if the configuration contains the gpio per tx/rx switching, but for some serial drivers we don't need them.

**Comment by pierrepitiot** [comment]
Actually this RS485 management has been made a long time ago for a specific hardware. Now we generally use system with automatic direction control and the serial port is always considered as RS232. This RS485 option should be removed.

**Comment by jakobcho** [comment]
Hi Pierrepitiot, 
I am using ReliaGate10-20 to test RS485 serial port, but always encounter TIMEOUT issue, and then I found this issue. does RS485 driver work for Kura 2.1 version?  thanks.

**Comment by pierrepitiot** [comment]
@jakobcho actually, as I explained above,  the Modbus service does not take care of the RS485 management, this is done by the RS485 service of ESF on the Reliagate 10-20 and the serial connection is considered as RS232. When you use the serial port as RS485, configure first the RS485 service then use the standard serial communication driver as you do for a RS232 connection. The RS485 service takes care of the programmation of the hardware to select automatic switching.

**Comment by jakobcho** [comment]
@pierrepitiot thanks, but I don't get you. on Reliagate 10-20 manual, we can manually configure the serial port (DB9) as RS485 mode by 
     ```
echo 1 > /sys/class/gpio/uart2-rs485/value
echo 1 > /sys/class/gpio/uart2_5-bufs/value
```
and then the (pin2, pin3) as (RX-, TX-), (pin7, pin8 ) as (RX+, TX+). 

From the current kura.protocol.modbus code, if it is RS485 mode, it will did to access those datapath if I assigne those properties as
```
prop.setProperty("serialGPIOswitch","uart2_5-bufs");
prop.setProperty("serialGPIOrsmode","uart2-rs485");
```
My current scenario is: I have a RPi3 with RS485 serial port to be connected to gateway.
(using wires to let 
RPi3's RT+ to  Reliagate 10-20's RX+ TX+, 
RPi3's RT-  to  Reliagate 10-20's RX-  TX- )
I also configure it to RS485 mode as above I mentioned, I was wondering what do you mean by "use the standard serial communication driver as you do for a RS232 connection"?  thanks

**Comment by pierantoniomerlino** [comment]
@pierrepitiot Since in the new ModbusProtocol we removed the distinction between RS485 and RS232, could we close this PR?

**Comment by pierrepitiot** [comment]
Yes, the correct Modbus service is in develop branch presently : 
https://github.com/eclipse/kura/tree/develop/kura/org.eclipse.kura.protocol.modbus
