### ISSUE TITLE
org.eclipse.kura.core.linux.executor.LinuxPid   equals method has bug?

### ISSUE THREAD

**Issue by slucx** [eclipse/kura#5506]
@Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        LinuxPid other = (LinuxPid) obj;
        return this.pid != other.pid;  // this line
    }

**Comment by mattdibi** [comment]
Hello there @slucx! Thank you for reaching out!

That's... well... yeah... that's clearly not correct. Thank you for reporting the issue!

**Comment by mattdibi** [comment]
Addressed by #5509 and #5514. @slucx Feel free to re-open this in case this is still a problem.

Thank you again for reporting this 🙏
