### ISSUE TITLE
[Modbus] Refactoring of Modbus example

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#553]
We have currently 2 projects that are Modbus examples : org.eclipse.kura.protocol.modbus.test and examples/org.eclipse.kura.demo.modbus. 

examples/org.eclipse.kura.demo.modbus is old and buggy and needs some refactoring. 

org.eclipse.kura.protocol.modbus.test is actually the old devkit program and is doing a bit more than modbus example, demonstrating the remote control of the device using MQTT. Moreover, this program has been updated and is now available in the public repository edc-examples:
https://github.com/eurotech/edc-examples/tree/master/com.eurotech.framework.edcdevkit

I propose that we keep only one Modbus example in examples directory  (after refactoring) and that we suppress the modbus.test project in kura.

Tell me what you think.

**Comment by cdealti** [comment]
Closed via #995
