### ISSUE TITLE
Add WebSocket as alternative mqtt transport

### ISSUE THREAD

**Issue by federicobaldo** [eclipse/kura#556]
As Paho introduced support for WebSocket and secure WebSocket it would be useful to have Kura support both as well.

Nowadays all the major IoT platforms provide mqtt over websocket or over secure websocket e.g. Eurotech Everyware Cloud, AWS IoT, etc.., this feature turns out to be especially useful for environments in which opening port 1883 or 8883 may be a problem. 

Additional work may be co-ordinated in the future with the Paho contributors to let websocket connections work properly even behind Http Proxy servers. (i.e. https://en.wikipedia.org/wiki/WebSocket#Proxy_traversal)

Kura should support the following new uri schemes:

 ws-URI = "ws:" "//" host [ ":" port ] / path [ "?" query ]
 wss-URI = "wss:" "//" host [ ":" port ] / path [ "?" query ]

Adding this feature would require an upgrade to the Paho library used in Kura and at least some changes in the following file, in order to allow the ws and wss uri scheme:
https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/transport/mqtt/MqttDataTransport.java

Do you guys foresee any other relevant change to be made in order to support this?

**Comment by MMaiero** [comment]
This should be addressed by PR #1037
