### ISSUE TITLE
Add SLF4J jcl-over-slf4j

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#557]
Camel AMQP requires Spring and Spring requires "Apache Commons Logging"

I think if Kura does use SLF4J is therefore also should bring in JCL over SLF4J.

**Comment by MMaiero** [comment]
@ctron could we move this to 2.2?

**Comment by ctron** [comment]
If possible I would like to add this in 2.1, otherwise I would need to distribute it with the AMQP package and the will create a clash in future versions.

I will create a PR right away.

**Comment by MMaiero** [comment]
Merging now. As discussed with @ctron, this change will be in develop branch as soon as the release of 2.1.0 will be completed.
