### ISSUE TITLE
Allow to create a Kura service via Kapua

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse/kura#5604]
**Is your feature request related to a problem? Please describe.**

As of today, there is no easy way allowing to create a Kura service remotely (e.g via Kapua).

**Describe the solution you'd like**

I’d like to be able to create a Kura service from the Kapua console. For that, I think the creation request should be handled by a Kura RequestHandler.

**Describe alternatives you've considered**
I can’t think of an alternative allowing to perform this operation from the Kapua console.

**Additional context**
https://github.com/eclipse-kura/kura/issues/3084

**Comment by mattdibi** [comment]
Hi there @reda-alaoui,

from our(Kura) side, the support is there via config, wires, rest (see [here](https://eclipse-kura.github.io/kura/docs-release-5.6/references/rest-apis/rest-configuration-service-v2/#postfactorycomponents) for factory components creation via REST API) etc. 

You might need to open this issue on the [Kapua repository](https://github.com/eclipse/kapua) for changes affecting the Kapua console.

Closing this as not related to the Kura project. Feel free to re-open this in case we might have missed something.

**Comment by reda-alaoui** [comment]
Thank you @mattdibi .
I'll take a look at the Kapua side.
