### ISSUE TITLE
Services UI not getting updated with new properties

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#562]
Any Service UI in the Web Console is not reflecting the updated changes of its properties even if I change it from the Web Console. I tried to change few properties in the Web Console and the properties are actually getting updated in OSGi but the updated properties are not shown on the respective Service UI in Web Console.

**For example**, CloudService -> device.display-name

**N.B**: The input box properties are the only ones which reflect the changes on Service UI but not the dropdown properties.

**Comment by MMaiero** [comment]
It's a regression from 2.0.1.
@cdealti I'm starting to work on it
