### ISSUE TITLE
[Configuration] ConfigurationService doesn't set properly the kura.service.pid

### ISSUE THREAD

**Issue by pierantoniomerlino** [eclipse/kura#564]
If a component has not a kura.service.pid property in the snapshot, the ConfigurationService is not able to assign the service.pid value to it. The result is that the component is not shown on the webUI.

**Comment by MMaiero** [comment]
@pierantoniomerlino Can this be closed?

**Comment by pierantoniomerlino** [comment]
@MMaiero : Yes!
