### ISSUE TITLE
Implement toString on KuraPayload

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#569]
I do think that adding a proper toString method for KuraPayload would help in various debugging scenarios.

**Comment by cdealti** [comment]
@ctron not a lot of interest about this. Can we close?

**Comment by ctron** [comment]
There is a +1 from @kartben, which is more interest than some other issues. But please, go ahead and close it.

**Comment by cdealti** [comment]
I'm trying to close some old issues. If you think it is important, can you please submit a PR. It should be backward compatible.
Note however that the KuraPayload might contain "confidential information" that might end up in the log file. I understand this could be a concern for @MMaiero ;-)
