### ISSUE TITLE
Cleanup Base64 generation in CryptoServiceImpl

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#570]
I really do think that the way base64 encoding is done in `CryptoServiceImpl` should be cleaned up.

First of all this should not be done as a service, rather using a static method. Second this should be done is simple manner, either commit to Java 8 and using the out of the box mechanism or by using Apache Commons Codec or Google Guava.

**Comment by dwoodard1** [comment]
@ctron What is the reason for using static methods over services? We do expose some static utility methods in org.eclipse.kura.core, but I find users of Kura find these harder to use as they are not exposed through the Kura API bundle. 

@MMaiero What was the reason for not using Apache Commons? It is Apache licensed, so getting a CQ approved should be no problem. I know some of this was inherited from an older code base, but I can't remember why we went with the reflection design.

**Comment by ctron** [comment]
@dwoodard1 I would reverse that question. Why use a service, registered with OSGi, using service lookup for a simple algorithm with holds no state in the service instance? Why do you need to dynamically register a service which will never really get registered or unregistered.

As an example, Java 8 goes the way. As do Google Guava and Apache Commons. I do understand that you (as Kura) want to provide an API for Base64. That is fine. Although of course you could argue whether duplicating an API is necessary.

But requiring a service lookup for simply calling a static method seems unnecessary overload to me. Also I do think that if people look for "base 64 encoding java", they will find it easier to use Apache Commons, Guava or Java 8 than a Kura specific API.

**Comment by dwoodard1** [comment]
@ctron I agree with you regarding Apache Commons/Guava, and certainly don't disagree with the additional overhead incurred by registering the OSGi Service, but this gets back to our common theme of not wanting to break backwards compatibility. For those making use of the CryptoService, they would have to update their applications to handle a new scheme. If we decide to make a release that truly breaks compatibility with previous versions, I think we could investigate this further.

**Comment by ctron** [comment]
Well I think there are three things we can do right now:

1) Clean up the implementation of the service. Use Guava, Apache Commons or Java 8 to clean up what is currently there
2) Offer an alternative, either by simply describing what to do, or provide an alternative API
3) Mark the current API as deprecated, pointing users to 2)

This will not break *anything* right now, but work into the right direction.

**Comment by MMaiero** [comment]
We used this approach for base64 in order to support java 8 compact 2 installations. The code will first try to go by javax.xml.bind.DatatypeConverter and, if not available tries to fallback to the java8 api. The reflection is limited to private methods and allowed us to have java8 code to be compiled and compliant with java 6+ machines.

We did not integrate other third party libraries in order to not overload too much of stuffs inq the project: Kura is intended to be lightweight to support the widest range of devices. Please consider that some people is complaining because Kura is becoming too heavy.

The Crypto service was originally intended to provide a set of crypto-related functionalities to users. Our idea is to extend more these APIs in order to provide more algorithm wrappings to end developers, in order to simplify their work. 
For the base64 we provide a very simple api implemented by private methods, so I don't get why we should deprecate it or provide a different API: when we will decide that we will need a third party library for that, we will simply rewrite the private wrapping, without breaking anything.

**Comment by ctron** [comment]
Simplifying a developers work would be (in order of google results):
1) `Base64.getEncoder().encodeToString(`??)` : java 8
2) `Base64.encodeBase64String(??)` : Apache Commons Codec
3) `BaseEncoding.base64().encode(??)` : Guava

Performing an OSGi service lookup and using a Kura specific API for doing base64 encoding doesn't seem to simplify anything IMHO.

Adding Guava will cost you around 2MB and will bring a whole bunch of tools developers will like, because all the things you plan in making your own API is already there. So you save time by not re-implementing that, you keep your API clean and developers can re-use what they already learned.

**Comment by amitjoy** [comment]
I completely agree with @MMaiero that the usage of Guava would burden Kura distribution. Instead, we could write utility classes for such encoding and decoding operations. Even, the CryptoService has been developed a long back and that's the current standard of such encoding and decoding. The idea is to have Kura as light as possible. And I had a long discussion with the other committers and finally thought of not using it as it would definitely make Kura distribution heavyweight. So, if we are concerned with the CryptoService not to be used in a OSGi service way, we could think of utility class to achieve the same.

**Comment by ctron** [comment]
If you don't want to invest 2MB, fine. The alternative is 278kb for Commons Codec. Or using plain Java 8. Which would reduce the code size of Kura even more since you could drop your custom implementation.

But if you really want to keep Kura small, drop the 30 MB of GWT :wink:

**Comment by amitjoy** [comment]
:smile: That would be really nice to drop GWT and have the Web Bundle developed in a more modular way. I would really want it. As we already have the implementation ready for performing encryption and decryption operations, I think we can create an utility class which provides the same functionalities. It would not be much of a work as I have already created a generic utility bundle for Kura which I would commit very soon. We can create a CryptoUtil class which can provide the same functionalities.

**Comment by ctron** [comment]
Which would already be a step into the right direction! :+1:

Still, you are re-implementing an API which is already there and proven. Or simply deprecate that functionality and upgrade to Java 8.

**Comment by amitjoy** [comment]
I would still prefer the way it is now and it still works without overwhelming Kura Distribution with more dependencies. Even the transition to Java 8 would still take time and it would not be a smooth transition though.

**Comment by ctron** [comment]
Why would a transition to Java 8 not be smooth?

**Comment by amitjoy** [comment]
I actually meant that it would take time to actually understand all the pros and cons in switching to Java 8 all of a sudden. It would definitely be beneficial in respective to enhanced programming and multicore systems. We just need to figure out if it can be easily integrated or not. I just don't want to use it as a hammer and think of everything as nails.

**Comment by dwoodard1** [comment]
This conversation seems to be going in a circle. I move we add this to the agenda for next Tuesday's call.

**Comment by ctron** [comment]
IIRC this is merged in 3.0.0
