### ISSUE TITLE
Unreadable errors in Web UI

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#572]
Causing an error in the Web UI (e.g. pressing the "Connect" button when there is configuration missing) shows an error dialog which shows an "error message" which is of no help to the user:

![kura_web_err_dlg](https://cloud.githubusercontent.com/assets/202474/18873447/cb13d36c-84bf-11e6-8c46-73d9c5c6246d.png)

**Comment by amitjoy** [comment]
The stack trace is actually obfuscated by GWT. This obfuscation is configurable through the maven plugin Web Bundle.

**Comment by ctron** [comment]
I completely understand the technical implications. But from an end user perspective this just looks broken.

**Comment by amitjoy** [comment]
Considering the user perspective, a probable solution would be to show the exception message instead of the complete stack trace.

**Comment by ctron** [comment]
A solution would be to show a proper, end user friendly message, explaining what is wrong and how to fix it. A stack trace could be added in some "collapsible" form which is hidden by default.

**Comment by MMaiero** [comment]
For 2.1.0 we can remove the stack trace. This will at least improve readability.
For 2.2.0 or later we can try to find out a better way to communicate errors to users.
