### ISSUE TITLE
build-menu script issue in MacOSX

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#579]
Detecting profiles...
Available profiles: Win64-nn beaglebone beaglebone-nn can dev-env dio.skip extra-dps intel-edison intel-edison-nn raspberry-pi raspberry-pi-2 raspberry-pi-2-nn raspberry-pi-bplus raspberry-pi-bplus-nn raspberry-pi-nn tools web web-classic
build-menu.sh: line 73: readarray: command not found

**Comment by ctron** [comment]
Oh come on .. Mac OS .. can you give the me version of bash which is present.

**Comment by amitjoy** [comment]
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by ctron** [comment]
The really know how so sell outdated software ... I will try to reproduce this

**Comment by amitjoy** [comment]
@ctron @cdealti  I think we can close this. I have tried the script in MacOSx Sierra and El Capitan. It is working as expected.
