### ISSUE TITLE
CQ for Eclipse Milo and its dependencies

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#583]
It is required for OPC-UA Driver of Kura Wires. We could at least have this driver included in Eclipse Kura.

**Comment by kartben** [comment]
fwiw you do not need a CQ for consuming other Eclipse.org projects

**Comment by amitjoy** [comment]
Eclipse Milo also requires its users to use its several other dependencies as well as it depends on them.
Such as, jOOL, Guava and so on. Do we have to file CQ for them?

**Comment by kartben** [comment]
"If your code makes indirect use of a third party library through another
Eclipse project’s code, you do not require a CQ for that library." - see
https://www.eclipse.org/projects/handbook/#ip-cq

On Fri, Sep 30, 2016 at 3:48 PM, Amit Kumar Mondal <notifications@github.com

**Comment by amitjoy** [comment]
@kartben Thanks for information. 👍

**Comment by ctron** [comment]
But please be aware of the fact that there is no release for Milo yet. So AFAIK you cannot consume it yet as a dependency in a release if Kura.

**Comment by ctron** [comment]
And you will need guava, which brings us back to the discussion on #570 ;-)

**Comment by amitjoy** [comment]
Guava is required by Eclipse Milo and that's why we need it for the OPC-UA Driver of Kura Wires. But due to the overwhelming dependencies required by Eclipse Milo, Kura Wires OPC-UA Driver would not be packaged inside Kura Distribution but it would still be in the Kura Github repository.

**Comment by ctron** [comment]
So how do you handle a car then where two components require Milo or guava?

**Comment by amitjoy** [comment]
My proposition is to have our OPC-UA driver packaged with Eclipse Milo and all its dependencies, uploaded as a reusable installable component in Eclipse Marketplace (IoT market especially). This actually doesn't require Guava or Milo to be present in the Kura target platform, instead we could package these dependencies in the OPC-UA driver bundle classpath.

**Comment by ctron** [comment]
So you want to embed Milo and guava and not export it?

**Comment by amitjoy** [comment]
Yes. That's my proposition.

**Comment by MMaiero** [comment]
Closing for now
