### ISSUE TITLE
Upload Modbus Driver to Eclipse Marketplace

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#586]
Due to the usage of j2mod library in the Modbus Driver implementation, the driver expectantly would not be approved by Eclipse for inclusion in Kura distribution. This is due to the usage of incompatible LGPL v3 license in j2mod's serial dependency - jSerialComm.

That's why my proposition is to upload the driver implementation as a deployment package to Eclipse Marketplace. I am open to suggestions as well.

**Comment by ctron** [comment]
You could use the Eclipse NeoSCADA implementation of modbus. That would give you at least modbus TCP out of the box. Modbus RTU over serial can be added by dropping in rxtx.

**Comment by amitjoy** [comment]
I have already implemented the Modbus Driver for Kura Wires. Before I start working on a complete new Modbus Driver implementation which would be Eclipse friendly, it would be better to have the implemented one uploaded to Eclipse Marketplace as a quick start. What do you think?

**Comment by cdealti** [comment]
It's available in the Eclipse Marketplace:

https://marketplace.eclipse.org/content/modbus-driver-eclipse-kura
