### ISSUE TITLE
Documentation for Eclipse Kura

### ISSUE THREAD

**Issue by msaiducar** [eclipse/kura#588]
Hi,

In the Documentation for Eclipse Kura [1], on the bottom section for 'Making Deployment Permanent', the entry should be;
`package_name=file\:/opt/eclipse/kura/kura/packages/package_filename.dp`
instead of;
`package_name=file\\:/opt/eclipse/kura/kura/packages/package_filename.dp`

[1] = http://eclipse.github.io/kura/doc/deploying-bundles.html#making-deployment-permanent

**Comment by dwoodard1** [comment]
Fixed, thanks @msaiducar
