### ISSUE TITLE
[Cloud] CloudConfigurationHandler casts to ComponentConfigurationImpl without type check

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#590]
Testing the latest build of Kura, I've found that if I try to get the device configuration from the cloud, the message arrives at the device, but is not processed and a reply is not provided. Following the log excerpts with Camel bundles working:
`2016-10-03 17:33:20,956 [Start Level Event Dispatcher] INFO  o.e.k.c.c.ConfigurationServiceImpl - Seeding updated configuration for pid: org.eclipse.kura.web.Console
2016-10-03 17:33:25,895 [pool-18-thread-1] INFO  o.e.k.n.a.NetworkConfigurationServiceImpl - postInstalledEvent() :: posting KuraNetConfigReadyEvent
2016-10-03 17:33:28,037 [MQTT Call: B8:27:EB:61:18:E2] INFO  o.e.k.c.c.CloudServiceImpl - Message arrived on topic: $EDC/ethdev/B8:27:EB:61:18:E2/CONF-V1/GET/configurations`

and these are the messages logged when Camel bundles are disabled:
`2016-10-03 17:35:52,905 [MQTT Call: B8:27:EB:61:18:E2] INFO  o.e.k.c.c.CloudServiceImpl - Message arrived on topic: $EDC/ethdev/B8:27:EB:61:18:E2/CONF-V1/GET/configurations
2016-10-03 17:35:53,049 [pool-1-thread-2] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :$EDC/#account-name/MQTT-1808215671/CONF-V1/REPLY/1475516153445-3062234502850727271, priority: 1
2016-10-03 17:35:53,058 [pool-1-thread-2] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic :$EDC/#account-name/MQTT-1808215671/CONF-V1/REPLY/1475516153445-3062234502850727271, priority: 1
2016-10-03 17:35:53,065 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: $EDC/ethdev/MQTT-1808215671/CONF-V1/REPLY/1475516153445-3062234502850727271 with QoS: 0`

I've also seen that the Camel bundles register a Cloud Application with a very (too) generic name: `myapp`
<img width="559" alt="myapp" src="https://cloud.githubusercontent.com/assets/10448126/19047239/42b5938e-89a1-11e6-9db9-01faf80d5dad.png">

**Comment by MMaiero** [comment]
@ctron Could you take a look at this issue?

**Comment by ctron** [comment]
I wasn't even aware that I was supposed to.

So tell me what should happen where, how I can test it and I can try to see what I can find out. From the initial comment I have no idea what is expected to happen in which component.

**Comment by MMaiero** [comment]
Just connect a device to, for example, EDC and try to get the device configuration from there. Then, I think, you will see what I mean ;‑)

**Comment by ctron** [comment]
How do I get the device configuration from there?

**Comment by MMaiero** [comment]
Oh, sorry, I've compressed too much. I meant: 

> request the device configuration by clicking on the configuration button, after having selected your device.

![configuration](https://cloud.githubusercontent.com/assets/10448126/19278239/d42734a8-8fdc-11e6-8aa7-22eca7ea177e.png)

**Comment by ctron** [comment]
So you mean that something is wrong in the everyware cloud? Sorry but I really don't get what the issue here is with Camel. Clicking on a connected device I get something like "The selected Device is not online or it does not support remote configuration." Although the device is shown green.

**Comment by MMaiero** [comment]
Ehm, no.
Let me try to detail you the steps I followed in order to have a common understanding of the issue:

1. Start from a freshly built Kura from develop and connect it to the cloud

2. Accessing the cloud platform and selecting the device, you will end up with something like this (you should be able to see the details in the description tab. If not, there is a problem in your setup):
![img1](https://cloud.githubusercontent.com/assets/10448126/19297879/26245d0a-9049-11e6-81eb-60b2c717c482.png)

3. Try to select the configuration tab. The cloud platform will request the configuration to the device and will be waiting for the reply.
![img6](https://cloud.githubusercontent.com/assets/10448126/19297846/dc8cef68-9048-11e6-9336-c949c05bc028.png)
 
4. The device will not reply back and, after some time, the platform will end up with an error:
![img3](https://cloud.githubusercontent.com/assets/10448126/19297857/f07f86b6-9048-11e6-8787-8d621c50ceeb.png)

5. If you try to stop Camel-related bundles (I've not tried to identify the bundle that is causing the issue):
![img4](https://cloud.githubusercontent.com/assets/10448126/19297860/fad16f80-9048-11e6-84da-103cbcc716f6.png) 

6. Trying to request again the configuration will now succeed:
![img5](https://cloud.githubusercontent.com/assets/10448126/19297867/057dee5e-9049-11e6-8bef-7b446e0ab6b3.png)

At device level, as detailed in the first post, with Camel-related bundles working the device will receive the request for configuration, but will not reply back. This is not happening if Camel-bundles are stopped.

**Comment by ctron** [comment]
So what is happening at the device level. I am pretty sure that Camel doesn't respond to such a request.

**Comment by MMaiero** [comment]
I think that org.eclipse.kura.camel.cloud.factory can be related to this issue: stopping only that bundle allows the get configuration requests to succeed.

**Comment by ctron** [comment]
So what is happening on the device side when the command is being issued?

**Comment by MMaiero** [comment]
I've not looked at the code, but maybe that bundle is a configurable component. So, it's possible that it is involved when the configuration is requested. Maybe the investigation should start from that point.

**Comment by ctron** [comment]
AFAIK the ConfigurableComponent is only a marker interface, no method is actually called.

So which component does process the request coming from the Everyware Cloud?

**Comment by cdealti** [comment]
Not to talk on behalf of @MMaiero but I think he means the ``SelfConfiguringComponent`` implemented by the [CamelManger](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.camel.cloud.factory/src/org/eclipse/kura/camel/cloud/factory/internal/CamelManager.java)

When you request the device configuration remotely, the request is handled by the [CloudConfigurationHandler](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/CloudConfigurationHandler.java).

This will call the ``ConfigurationService.getComponentConfiguration`` which eventually will call the ``CamelManger.getConfiguration`` method.

If we stop the ``camel.cloud.factory`` bundle the issue does not appear.

Hence the issue is related to the CamelManager (mayne a bug in the ConfigurationService triggered by the CamelManager) given that in Kura there are other SelfConfiguringComponents running.

**Comment by ctron** [comment]
Ah .. now I see! Thanks for explaining!

So what happens then is a call to `doGetConfigurations`? Then I would try to create a unit test which reproduces this issue.

**Comment by ctron** [comment]
This is actually a bug in the `CloudConfigurationHandler`. It takes instances of `ComponentConfiguration` and casts them to `ComponentConfigurationImpl`, which in this case doesn't work.

**Comment by MMaiero** [comment]
I think we can close this and open another issue for the ComponentConfigurationImpl cast

**Comment by ctron** [comment]
I changed the title already. Let's keep it open.

**Comment by MMaiero** [comment]
I've seen that. But, in my opinion, a clean and well documented issue is more understandable.

**Comment by ctron** [comment]
So create a new issue then, referencing this one and setting the target to 2.2.
