### ISSUE TITLE
WebUI fails completely is `PositionService` is not registered

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#599]
If there is no instance of `PositionService` registered with OSGi, then the whole Web UI fails with an "internal error".

Although the code checks for a `null` reference:

```java
PositionService positionService = ServiceLocator.getInstance().getService(PositionService.class);

if (positionService != null) {
```

The actual call to `org.eclipse.kura.web.server.util.ServiceLocator.getService(ServiceReference<T>)` will throw an exception.

**Comment by cdealti** [comment]
@ctron what is the state of this issue? If you are using Zenhub please update the fields on the left column (Pipeline, Milestone, Assignee etc) so that we can properly track the progress.

**Comment by ctron** [comment]
This one was merged already.

I don't use Zenhub.
