### ISSUE TITLE
Provide a way to adding arbitratry links to the Web UI

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#601]
There should be a way to add arbitrary links into the Web UI menu of Kura. Registering an additional servlet with the HttpService could provide additional entry points which could then be rendered by the Web UI as a simple link in the menu on the left. Maybe in a separate box.

**Comment by reda-alaoui** [comment]
Hello @MMaiero ,

Is that currently possible? If yes, how can this be done?

**Comment by MMaiero** [comment]
Hello,
I think what you are looking for is this: https://github.com/eclipse-kura/kura/tree/develop/kura/examples/org.eclipse.kura.example.web.extension

**Comment by reda-alaoui** [comment]
Thank you :heart:
