### ISSUE TITLE
Can "json 20090211" be removed?

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#603]
A few bundles declare a dependency on "json 20090211":

```xml
<groupId>org.json</groupId>
<artifactId>json</artifactId>
<version>20090211</version>
```

But to me it seems it is not used. Can it be removed?

**Comment by cdealti** [comment]
If it still builds and runs after removing it, yes!

**Comment by ctron** [comment]
Ok, then I will work on that.

**Comment by ctron** [comment]
Looks like it.

**Comment by ctron** [comment]
This affects the deployment on Karaf.
