### ISSUE TITLE
Modularize Kura by replacing switch blocks

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#608]
As @kartben and @dwoodard1 suggested in issue #552 the way Kura currently handles alternate variants of the operating system, by using big switch blocks, is not optimal. This issue should track an enhancement of following a modular approach.

**Comment by ctron** [comment]
Depending on the actual requirement his could come from either a properties file or from a custom service implementation. OSGi is made exactly for that cause.

So for example with `LinuxNamed` this could be a service which has different service implementations. Depending which target image is assembled, either existing services can be deployed or a new service can be implemented. Of course it is not necessary to always write those instances from scratch, but an abstract base class could be used which provides common methods for specific groups of Linux for example.

**Comment by kartben** [comment]
Yes, please! :-)

**Comment by MMaiero** [comment]
Great improvement has been done for Kura 4.0.0.
I'm closing this for now. We will continue on specific issues.
