### ISSUE TITLE
Can native binaries for "armv5sf" be removed?

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#611]
It looks like as if currently no target uses native binaries for `armv5sf`. Can those be removed?

**Comment by cdealti** [comment]
These libraries are needed by the ESF build. I understand this is not elegant and that using fragments, as mentioned in another issue, would be a better solution.

**Comment by ctron** [comment]
I am currently working on migrating to fragments. That is why I did find no reference to those binaries. So I wondered if they are just left over or actually in use.

**Comment by MMaiero** [comment]
@ctron We can close this, right?
