### ISSUE TITLE
Upgrade HIPP instance to a more recent version of Hudson

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#612]
I would like to upgrade the Hudson instance at Eclipse to a more recent version of Hudson.

This is "self-service" can be done by clicking a link on the developer portal at portal.eclipse.org.

Any objections?

**Comment by ctron** [comment]
It seems no longer "self-service". Opened a ticket [1]

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=505841

**Comment by MMaiero** [comment]
Ticket closed. Closing the issue
