### ISSUE TITLE
Fix Bundle-Vendor to "Eclipse Kura"

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#627]
The Eclipse Release Review guide [1] says that all OSGi bundles must have a `Bundle-Vendor` of `Eclipse <Name>`, in this case `Eclipse Kura`.

However this is currently not the case.

[1] https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews#Checklist

**Comment by waynebeaton** [comment]
+1

The Bundle-Vendor should most certainly not be an organization. The general idea is to ensure that it is obvious that the project is vendor-neutral, operating in an open and transparent manner.

**Comment by dwoodard1** [comment]
Thanks Wayne. This has been addressed and merged with #628 . It will be in the v2.1.0 release.
