### ISSUE TITLE
Add Bundle-Copyright manifest header

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#629]
We have bundles which consists of several types of files and adding copyright header to every file is a bit tedious task and sometime the files get bloated. And also sometimes, developers mistakenly forget to add the header to all the files. The files can be anything, for instance, `.xml, .js, .html, .java, .properties, .ini,` and so on. I always prefer using `Bundle-Copyright` which inherently applies to all the files residing in the bundle. So, there is actually no need to add license header explicitly. If we need to mention something more, we can add more information in the license header inside the specific file. The addition of such `Bundle-Copyright` header would eventually help to have the copyright applied to all the files inside a bundle even if you forget to add the license header to your files explicitly.

**Comment by ctron** [comment]
We can use the bundle header. But Eclipse policy requires a license header anyway.

**Comment by amitjoy** [comment]
Oh ok. I was not aware of that. I knew only about the intention behind this specific header. I believe such manifest header would still be a good practice even if we forget to add one. There exists some html files in Web Bundle in which the license header is still missing and this could have been prevented if we use this manifest header.

**Comment by ctron** [comment]
I agree, adding such a header would be a great addition.

**Comment by cdealti** [comment]
who is willing to do this?
