### ISSUE TITLE
Building of eclipse project files fails if you run it two times

### ISSUE THREAD

**Issue by djurodrljaca** [eclipse/kura#631]
Steps to reproduce the issue:
1. `git clone git@github.com:eclipse/kura.git Kura_eth`
2. `cd Kura_eth`
3. `./build-all.sh`
4. `cd kura`
5. `mvn -f manifest_pom.xml eclipse:clean && mvn -f manifest_pom.xml eclipse:eclipse`
6. `mvn -f pom_pom.xml eclipse:clean && mvn -f pom_pom.xml eclipse:eclipse`
7. `mvn -f manifest_pom.xml eclipse:clean && mvn -f manifest_pom.xml eclipse:eclipse`

The last step fails, see partial log [eclipse_project_files_failure.txt](https://github.com/eclipse/kura/files/529000/eclipse_project_files_failure.txt)

If you try to build the complete project again, it also fails:
1. `cd ..`
2. `./build-all.sh`

The last step fails, see partial log [build_failure.txt](https://github.com/eclipse/kura/files/529003/build_failure.txt)

**Comment by pierrepitiot** [comment]
Yeah! it has been a long time that I have this issue but never took time to fix it :-(

**Comment by djurodrljaca** [comment]
I originally suspected that build-all script will also fail if I run it two times in a row, but it does build without problems. So as far as I see, building eclipse project files two times to make it fail also makes the complete build fail for some reason...

**Comment by cdealti** [comment]
> mvn -f manifest_pom.xml eclipse:clean && mvn -f manifest_pom.xml eclipse:eclipse

I don't use ``eclipse:clean`` or ``eclipse:eclipse`` anymore. Is this still needed? I assume we mention it in our documentation.

**Comment by djurodrljaca** [comment]
It is still mentioned here: http://wiki.eclipse.org/Kura/Getting_Started

So is the usual way to just import "existing maven projects"?

**Comment by ctron** [comment]
This think this could be removed. I would favor to use the Eclipse installer.

I think would should point people to [1]

[1] https://wiki.eclipse.org/Kura/Getting_Started#For_the_Eclipse_Installer_based_setup_2

**Comment by MMaiero** [comment]
Hi all, is this still an issue?

**Comment by pierrepitiot** [comment]
Not for me

**Comment by MMaiero** [comment]
Ok, so closing for now
