### ISSUE TITLE
ExecCommand in org.eclipse.kura.linux.bluetooth.BluetoothAdapterImpl Index Out Of Bounds

### ISSUE THREAD

**Issue by PeterTaylor01** [eclipse/kura#635]
The method:

`public void ExecuteCmd(String ogf, String ocf, String parameter)`

In org.eclipse.kura.linux.bluetooth.BluetoothAdapterImpl gives an index out of bounds error.

It works as intended if you change the loop code from:

```
       for (int i = 0; i < cmd.length; i++) {
            cmd[i + 3] = paramArray[i];
        }
```

To:

```
     for (int i = 0; i < paramArray.length; i++) {
            cmd[i + 3] = paramArray[i];
        }
```

Thanks,
Peter

**Comment by pierantoniomerlino** [comment]
@PeterTaylor01 Thank you for reporting this bug. The issue is indeed in the loop condition. PR #713 fixes the bug.

**Comment by PeterTaylor01** [comment]
@pierantoniomerlino Thank you for resolving that.
