### ISSUE TITLE
[Windows] Use of NSIS and MinGW

### ISSUE THREAD

**Issue by malikm** [eclipse/kura#637]
The use of **NSIS** is currently not covered by a CQ. Thus it's currently not possible to distribute an NSIS-based installer from Eclipse servers.
As an alternative, WiX has been suggested, which is approved. However a setup based on WiX is not possible to build on Linux-based machines (only Windows is supported). This doesn't fulfill the initial requirement to build a complete Windows installation on Linux systems too.

Native libraries and executables for Windows are currently build using **MinGW**. This allows building those files on both Windows- and Linux-based machines. However there's no full CQ for MinGW yet, and the code produced is linked against MinGW libraries.
As an alternative, a build using Microsoft Visual Studio has been suggested. This however doesn't allow building the required binaries on Linux systems and the restriction to dynamically link against Microsoft libraries would require shipping of Microsoft Visual Studio Redistributable package with Kura.

Further discussion details can be found here: https://github.com/eclipse/kura/issues/545

**Comment by dwoodard1** [comment]
@malikm I had a chance to discuss the legal issues around NSIS at a recent Eclipse event. The question that came up, is NSIS necessary? Instead of distributing a *.exe, could we just distribute a Windows shell program? I understand some of the advantages of having the *.exe, but a quicker path to getting Kura Windows out may be the shell program.

**Comment by ctron** [comment]
A shell program for setting up Kura is quite ugly compared to the standard way of using an MSI file. So what speaks against using MSI with WIX?

**Comment by diegovisentin** [comment]
Have you already evaluated the use of GNOME msitools ? [https://wiki.gnome.org/msitools](https://wiki.gnome.org/msitools)

**Comment by cdealti** [comment]
Due to all these legal aspects and the lack of interest on the Windows port I propose to close this issue and remove from Kura all the Windows specific code.
@dwoodard1 @malikm @markcullen what do you think?

**Comment by cdealti** [comment]
Closing. Windows code will be removed
