### ISSUE TITLE
Possible bug in "LinuxUdev.c"

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#650]
At `LinuxUdev.c:121` is the following code:

``` c
//add it to the ArrayList
jboolean jbool = (*env)->CallBooleanMethod(env, objArr, mid_add, UsbDeviceObject);
if (jbool == NULL) return NULL;
```

Which results in the case that if the item could not be added to the list, the function returns, not freeing the current element and not returning the list.

Beside that the boolean type should be checked against `JNI_FALSE`.

To me it looks like a copy and paste error from the code segments above where the "if" actually makes sense:

``` c
jobject objArr = (*env)->NewObject(env, arrayClass, mid_init);
if (objArr == NULL) return NULL;
```

Still those returns will leak resources.

**Comment by pierantoniomerlino** [comment]
Closed by PR #1034
