### ISSUE TITLE
Call to "exit()" in native code

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#651]
In `LinuxUdev.c:49` is a call to `exit()` in the case `udev` cannot be initialized.

``` c
udev = udev_new();
if (!udev) {
   printf("Can't create udev\n");
   exit(1);
}
```

IMHO exiting the JVM in such a very is a very, very bad idea. I think throwing an exception should be the way to go.

**Comment by cdealti** [comment]
@pierantoniomerlino and there will be one more in tinyb
