### ISSUE TITLE
Misconfiguration of eth0 (as dhcp server) filling /var/log directory and finally crashing kura

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#664]
After a incorrect configuration applied on eth0 (enabled for LAN with a manual address 10.129.3.2 AND DHCP and NAT enabled with a pool range 172.16.0.100 - 172.16.0.110), Kura try to start dhcpd but dhcpd is failing and reporting the following error in syslog and daemon.log: 

Oct 18 23:18:53 rg-10-20 dhcpd: Internet Systems Consortium DHCP Server 4.2.4-P1
Oct 18 23:18:53 rg-10-20 dhcpd: Copyright 2004-2012 Internet Systems Consortium.
Oct 18 23:18:53 rg-10-20 dhcpd: All rights reserved.
Oct 18 23:18:53 rg-10-20 dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Oct 18 23:18:53 rg-10-20 dhcpd: bad range, address 172.16.0.100 not in subnet 10.129.3.0 netmask 255.255.255.0
Oct 18 23:18:53 rg-10-20 dhcpd: 
Oct 18 23:18:53 rg-10-20 dhcpd: If you did not get this software from ftp.isc.org, please
Oct 18 23:18:53 rg-10-20 dhcpd: get the latest from ftp.isc.org and install that before
Oct 18 23:18:53 rg-10-20 dhcpd: requesting help.
Oct 18 23:18:53 rg-10-20 dhcpd: 
Oct 18 23:18:53 rg-10-20 dhcpd: If you did get this software from ftp.isc.org and have not
Oct 18 23:18:53 rg-10-20 dhcpd: yet read the README, please read it before requesting help.
Oct 18 23:18:53 rg-10-20 dhcpd: If you intend to request help from the dhcp-server@isc.org
Oct 18 23:18:53 rg-10-20 dhcpd: mailing list, please read the section on the README about
Oct 18 23:18:53 rg-10-20 dhcpd: submitting bug reports and requests for help.
Oct 18 23:18:53 rg-10-20 dhcpd: 
Oct 18 23:18:53 rg-10-20 dhcpd: Please do not under any circumstances send requests for
Oct 18 23:18:53 rg-10-20 dhcpd: help directly to the authors of this software - please
Oct 18 23:18:53 rg-10-20 dhcpd: send them to the appropriate mailing list as described in
Oct 18 23:18:53 rg-10-20 dhcpd: the README file.
Oct 18 23:18:53 rg-10-20 dhcpd: 
Oct 18 23:18:53 rg-10-20 dhcpd: exiting.

Kura Network monitor is retrying every mn and after a few hours the log files become very large and fill all the disk space. When there is no more space left on the disk, Kura stops working until the disk is freed.

There are actually 2 issues here:
- the log files should not fill the disk. This is fixed with a correct logrotate policy
- an incorrect network configuration should not be retry forever.

**Comment by MMaiero** [comment]
@pierrepitiot Do you think this issue should be addressed in 2.1.0?

**Comment by pierrepitiot** [comment]
As the logrotate policy active on gateways currently produced is taking care of the disk filling I don't think it is urgent. We can postpone it.

**Comment by cdealti** [comment]
@ibinshtok can you take a look please?

**Comment by ibinshtok** [comment]
@cdealti yes, I am going to look at this next week when I am back from Seattle (King County)
