### ISSUE TITLE
Add Kura Wires Web Visualization Support

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#665]
This would add the visualization support to create dataflow graphs in Kura Wires using the Kura Web Console.

**Comment by amitjoy** [comment]
@cdealti @MMaiero Could you kindly assign "Kura-Wires" label to this? It needs to be tracked as this is the remaining part of Kura Wires that needs to be committed.

**Comment by amitjoy** [comment]
Fixed by #676

**Comment by dwoodard1** [comment]
@amitjoy Is there a PR referencing this issue?

**Comment by amitjoy** [comment]
Not open any more. You can close this.
