### ISSUE TITLE
Use gson instead of org.json

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#668]
I just saw that one of the new wires modules, which seems not to be in the main build, requires the "org.json" package. Now since that has been removed, with good reason, I would suggest to go with gson instead or something different which comes with OSGi support and is available from maven central out of the box.

**Comment by ctron** [comment]
The re-introduction of org.json effectively kills the Karaf compatibility.

**Comment by ctron** [comment]
As discussed today the plan is as follows:

1) Merge Kura Wires CQ
2) Replace with GSON right afterwards
3) Do this before the first milestone of 2.2.0

**Comment by amitjoy** [comment]
#749

**Comment by amitjoy** [comment]
#750

**Comment by ctron** [comment]
Going with minimal-json
