### ISSUE TITLE
[Release 2.1.0] Create release branch

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#671]
I would create the release branch from develop commit 4e88d164891a1eee2d5382be8bed960bfa8e1258.

The history up to this commit will include #552 and #626 (needed for 2.1.0) but not include #580 #622 #602 #409 (not needed for 2.1.0).

**Comment by ctron** [comment]
So that would leave out Karaf support out of 2.1. and I really do think it would be great to get this started. Beside it doesn't hurt the default Kura.

**Comment by dwoodard1** [comment]
@ctron Are you referring to this commit a8cf4f791bb40d7d4bf9211e0733830e09680fd7? If so, I don't see a clean way of including that in the release branch. It was merged after several Kura Wires commits.

**Comment by ctron** [comment]
I mean several commits after the wires commit. I don't think it hurts having Kura wires stuff in the next release. As long as it is not active and not advertised. But keeping the other commits out would mean that I have to maintain a fork of Kura for another full release cycle and always point people to my fork of Kura for demonstrations and examples. So more and more blog post and tweets will contain URLs to that forked repository. It I would really like to avoid that.

An alternative could be to cherry pick the required commits onto the release branch. It would be more work and may introduce a few bugs, but you could "cut out" wires by doing that.

**Comment by MMaiero** [comment]
@ctron Maybe I'm wrong, but the code for 2.2 will be in develop and all the changes will be there. So, why you will have to keep a separate fork of Kura? You can just point out that the code is in develop, because actually is in a development process and people can try out from there.

**Comment by ctron** [comment]
Of course you are right. The code itself will be, or probably stay, in the development branch. So there would be no need to keep the forked repository, but we would still have to live with -SNAPSHOT dependencies.

Not too bad. Let's go with that. And let's try to get all the artifacts on maven central for 2.2.

**Comment by dwoodard1** [comment]
Created.
