### ISSUE TITLE
Improve Web Interface support for mobile devices

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#672]
This would improve Web Interface usability by adding a button to the header bar that allows to toggle the left panel on devices with small screen size. This would also make the UI look more compact reducing the size of margins and paddings.

![screen shot 2016-10-24 at 17 47 32](https://cloud.githubusercontent.com/assets/8960773/19652698/1784b236-9a12-11e6-8440-fed55fc4ba9a.png)
![screen shot 2016-10-24 at 17 47 40](https://cloud.githubusercontent.com/assets/8960773/19652704/1a580e18-9a12-11e6-8c92-a57a321bce16.png)
![screen shot 2016-10-24 at 17 47 43](https://cloud.githubusercontent.com/assets/8960773/19652708/1c8816c4-9a12-11e6-9831-054afb2ee47d.png)

**Comment by ctron** [comment]
That looks great.

**Comment by ctron** [comment]
Can you provide a PR?

**Comment by MMaiero** [comment]
A PR is on the way, but it will not be available for 2.1.0

**Comment by amitjoy** [comment]
I had a conversation with @nicolatimeus and it is currently in progress. @nicolatimeus is interested to work on making Wires Composer UI compatible with the current changes. So, my speculation is that there will be a PR after the Wires Web gets integrated to develop.
