### ISSUE TITLE
CloudServiceFactory deleteConfiguration

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#673]
We are currently exposing the createConfiguration(String pid) method in the OSGi console. I know this was a temporary work around until the UI was updated. However, if it is going to remain a console command, we should also include the deleteConfiguration(String pid) in the console.

**Comment by MMaiero** [comment]
I would close this and open another issue to remove the `createConfiguration(String pid)` since now it is not needed. What do you think @dwoodard1 ?

**Comment by dwoodard1** [comment]
How would a user create a new CloudService component if they were not using the Kura web UI.

**Comment by cdealti** [comment]
@dwoodard1 how would a user configure the newly created CloudService without the Kura Web UI?

**Comment by dwoodard1** [comment]
The same way you would configure the default CloudService without a web UI. Either through uploading a snapshot or performing a remote configuration.

I think the main point is that we don't want to make the UI a requirement for using Kura (other than Kura Wires obviously). This may be another argument for a Kura REST add-on.
