### ISSUE TITLE
CQ for Kura Wires Web Integration

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#679]
#676 includes the Web Integration for Kura Wires Visualization and Factory Instance creation.

**Comment by amitjoy** [comment]
@cdealti @ctron @dwoodard1 @MMaiero Could you kindly file a CQ for the PR #676?

**Comment by amitjoy** [comment]
@cdealti Any update on the CQ filing?

**Comment by cdealti** [comment]
@amitjoy are there prerequisite CQs for #676?

**Comment by amitjoy** [comment]
The dependencies required for this CQ:

1. JointJS 0.9.9 and its transitive dependencies such as Jquery and Backbone (Already approved in a CQ #681)
2. org.json which has been readded for Wires

**Comment by cdealti** [comment]
Ah, OK. So it's just a matter of creating the CQ for this PR

**Comment by cdealti** [comment]
@dwoodard1 can you take care of doing this today?

**Comment by dwoodard1** [comment]
Yes, but I don't really have time to go over all the changes (>6000 lines of code). I assume we can address issues after the CQ is approved.

**Comment by cdealti** [comment]
I think @LucaDazi is well aware of the PR and already checked everything is OK. But he is out of office today.

**Comment by amitjoy** [comment]
@cdealti You are completely right that @LucaDazi is well aware of this PR as he also has contributed to it in my fork.

**Comment by dwoodard1** [comment]
CQ created: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12201

**Comment by amitjoy** [comment]
@ctron @cdealti Any update on this CQ?

**Comment by dwoodard1** [comment]
It is still waiting for PMC approval. We have asked Eclipse legal to focus on CQs related for the v2.1.0 release. After these are closed, we can ask for a status update on this.

**Comment by dwoodard1** [comment]
@amitjoy I spoke too soon, it looks like this is getting approved soon. Please make sure the header information is updated to be consistent with #680. I will let you know when we get the official go ahead.

**Comment by amitjoy** [comment]
@dwoodard1 The current header in #686 is as follows:

```
/*******************************************************************************
 * Copyright (c) 2016 Eurotech and/or its affiliates and others
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 *******************************************************************************/
```
I believe this has been discussed in #680.

**Comment by amitjoy** [comment]
and in modified files, it contains the first year and modification year in the header also.

```
/*******************************************************************************
 * Copyright (c) 2011, 2016 Eurotech and/or its affiliates and others
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 *******************************************************************************/
```

**Comment by dwoodard1** [comment]
Yes. Perfect. Thanks.

**Comment by dwoodard1** [comment]
The CQ has been approved, please move forward with merge.
