### ISSUE TITLE
[Legal] Update contributing.md file to specify header guidelines

### ISSUE THREAD

**Issue by MMaiero** [eclipse/kura#680]
The contributing.md file should be updated to help contributors to provide a proper header for their contributions.
The contributing.md file should define rules for 
- general structure,
- copyright years ranges,
- contributor names

that need to be placed in the contributed files.

**Comment by kartben** [comment]
maybe also use this as an opportunity to add a quick blurb on how to look at, and use ZenHub?

**Comment by kartben** [comment]
maybe also a quick blurb on how to look at and use ZenHub?

**Comment by amitjoy** [comment]
So far, Kura uses the following copyright header for its source base.

```
Copyright (c) [THE START YEAR], [THE MODIFICATION YEAR] Eurotech and/or its affiliates
 
   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html
 
  Contributors:
    Name of the First Contributor
    Name of the Second Contributor
    ...........
```

Some projects (such as JUnit5) uses the following paradigm

```
Copyright (c) [THE START YEAR]-[THE MODIFICATION YEAR] the original author or authors
 
   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html
```

So, clearly we need to have a fixed copyright header format to use in our source base.

**Comment by cdealti** [comment]
I believe this is the reference:
http://www.eclipse.org/legal/copyrightandlicensenotice.php

**Comment by amitjoy** [comment]
So I believe it would be as follows for Kura -

```
Copyright (c) [THE START YEAR], [THE MODIFICATION YEAR] [Name of the First Contributor or The Organization Name] and others
 
   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html
 
  Contributors:
    Name of the First Contributor
    Name of the Second Contributor
    ...........
```

**Comment by MMaiero** [comment]
I think we have only to reference the fact that we use the Eclipse Copyright tool. So other contributors can align on it.
We can also point out the [reference](https://wiki.eclipse.org/Development_Resources/How_to_Use_Eclipse_Copyright_Tool) for this tool and [the official description](http://www.eclipse.org/legal/copyrightandlicensenotice.php) by the Eclipse Foundation, as correctly pointed out by Cristiano

**Comment by amitjoy** [comment]
Exactly! That would be good to use Eclipse Copyright Tool or JAutodoc for specifying the copyright header in the sources. But for the existing sources, we need to specify the header and how it should be done. For example, **_Kura Wires Core_** and **_Kura Asset Model_** currently use the following copyright:

```
 Copyright (c) 2016 Eurotech and/or its affiliates

   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html

  Contributors:
    Amit Kumar Mondal (admin@amitinside.com)
```

but it needs to be changed according to Eclipse Copyright Guideline. I believe it should be as follows -

```
 Copyright (c) 2016 Amit Kumar Mondal

   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html

  Contributors:
    Amit Kumar Mondal (admin@amitinside.com)
```

and if it is changed in future revisions then it should be -

```
 Copyright (c) 2016 Amit Kumar Mondal and others

   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html

  Contributors:
    Amit Kumar Mondal (admin@amitinside.com)
    Name of the second contributor and/or Organization Name
    ........
```

**Comment by ctron** [comment]
+1 @amitjoy ... I would remove the email address though, I did that too in the past, but it clutters up the header pretty easily.

In addition I would however describe the contribution. That can be a bit vague, but just probide a hint about what was done.

**Comment by amitjoy** [comment]
@ctron I agree completely that the email address clutters up the header. My proposition would be also not to add detailed information about every change made to the source as it clutters up the header too. I can write initial contribution as the description but if every other committer starts following the similar notion to add description to the header for every change, then it would be another mess in the header. 

I am open to suggestion on how to do it in a clean way.

**Comment by MMaiero** [comment]
I agree with @amitjoy the description could make it a mess in a while and usually determines conflicts when rebasing.

**Comment by ctron** [comment]
So I agree with you, yet most core Eclipse projects follow that way. And I think the basic idea is to describe changes made in bigger context. It is not a commit message.

I think that things like fixed bugs, bigger refactoring or major extensions should be mentioned. Problematic is the first time a new legal party is added, you shoukd write something. An empty line looks strange to me.

In the end there is no real rule and I am not sure we should create one, other than, be reasonable.

**Comment by MMaiero** [comment]
@kartben As you have a clear overview between all the projects, what's your opinion on this topic?

**Comment by amitjoy** [comment]
@ctron I understand your concern. If you consider any Web Bundle source file, it had been actually modified several times that the header would have been very large. Even if we go for description like "Fixed Bug #xxx" in the header, within few months, it would be accumulated to a big mess and that's where my concern underlies.

I believe, if we follow, the natural paradigm of adding proper git commit messages, referencing the issues, it would not be necessary to add such description in the copyright header.

**Comment by ctron** [comment]
As I tried to explain, I wouldn't expect full commit messages there. More like a group of work. And maybe this is just "bugfixing". But if you do look at other Eclipse git repositories, they do it too, even core Eclipse project which are way older than Kura [1], [2].

I just do think that we should follow the way most other Eclipse project do, instead of each and every time questioning that and going a Kura-specific way.

Of course we could also go the way of just dropping the committer list completely and stick with "and others".

[1] http://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/JavaUIMessages.java?h=R4_6_maintenance
[2] http://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/codegen/TypeAnnotationCodeStream.java

**Comment by amitjoy** [comment]
@ctron For small classes containing less LoC, it would not create any problem but for classes of more than 500 LoC, I wonder that how many times that class would be modified and every time if we mention the bug in the header, it would eventually be a problem for other contributors to rebase. In Kura, the micro-service implementations, the controller classes in web bundle are huge. So, the header would also be very big if we start adding the short description of the change made to the source. 

If you see other projects such as JUnit5 [1], it doesn't add any description to the header. On the other hand, Eclipse SmartHome [2], follows a different approach. The copyright header remains same for all the sources (without any modification description) whereas the description is added in the class level javadoc.

[1] - https://github.com/junit-team/junit5
[2] - https://github.com/eclipse/smarthome

**Comment by ctron** [comment]
Again, I am *not* saying that we should put a line for every change. But for groups of changes! Bigger topics. *Not* replicate git commit messages.

And I did make the suggestion to drop this altogether.

**Comment by amitjoy** [comment]
So, in **Kura Wires** and **Kura Asset Model**, we have sources some of which have headers as follows:

```
 Copyright (c) 2016 Eurotech and/or its affiliates

   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html

  Contributors:
    Amit Kumar Mondal (admin@amitinside.com)
```

and 

```
 Copyright (c) 2016 Eurotech and/or its affiliates

   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v1.0
   which accompanies this distribution, and is available at
   http://www.eclipse.org/legal/epl-v10.html

  Contributors:
    Eurotech
    Amit Kumar Mondal (admin@amitinside.com)
```

The sources (all sources in **Kura Asset Model**) written solely by me contain only the **1st copyright header** and in **Kura Wires**, there exists sources which @LucaDazi and I worked on it together. Those sources contain the **2nd copyright header**.

In both the cases, the copyright owner is Eurotech. So, the copyright line in the header remains as it is now.

@ctron That makes sense. For group changes, we can write a small description of the change in the header. But what should we do for minor changes to the sources?

**Comment by ctron** [comment]
No, it doesn't. Either you (Amit) are the author or it is Eurotech. Both is fine, but then it must be in sync with the copyright line.

If you are counted as Eurotech staff, then the contributor is Eurotech and not you as a person.

If you (Amit) are the main author and Luca helped, the it would by "Amit and others".

This information has also to be in sync with the Eclipse IP log. So if this was wrong in the past, the IP *must* be corrected!

**Comment by amitjoy** [comment]
But according to [1], 

```
/*******************************************************************************
 * Copyright (c) {DATE} {INITIAL COPYRIGHT OWNER} {OTHER COPYRIGHT OWNERS}.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    {INITIAL AUTHOR} - initial API and implementation and/or initial documentation
 *******************************************************************************/
```

The {INITIAL COPYRIGHT OWNER} is Eurotech and {INITIAL AUTHOR} is Amit Kumar Mondal. This is what I understood from the detailed descriptions as mentioned in [1].

[1] - http://www.eclipse.org/legal/copyrightandlicensenotice.php

**Comment by ctron** [comment]
So please take into account the full document then:

>  It is good practice to list the name of the author with their employer if the latter owns the copyright. For example: "John Smith (XYZ Corp.)".

And:

>  Subsequent authors are listed on proceding lines with a short description of the contribution. If there is an associated Bugzilla report number, then it is good practice to include it here. Over time, this section actually becomes a log of the contributions. Although it could become quite lengthy in some cases, it should be maintained for two important reasons - to acknowledge the contributions of individuals (especially when their contribution is owned by their employer), and to assist with tracking the pedigree of the code (who wrote what).

Not just pick the things you like best.

**Comment by amitjoy** [comment]
@ctron +1 for the comprehensive comment.

I would prefer adding names to the sources as it would be easier to know the concerned persons for further assistance. But I am open to suggestions.

@mcarrer @cdealti @dwoodard1 @MMaiero What do you guys think?

**Comment by ctron** [comment]
So, let's follow the default of the Eclipse Foundation:

Copyright header line -> Legal entity + " and others"
Contributors -> Author (Legal Entity) + description of contributions

**Comment by MMaiero** [comment]
In [1], [2] and [3] few references taken from current mainstream projects currently under development in the Eclipse foundation. Maybe I'm wrong, but honestly I've not found a common and always applied approach.
Personally I agree on Jens' suggestion for the copyright header line.
For the Contributors line I would leave the possibility to have the author name with legal entity or only the legal entity.

Regarding the description of contributions I honestly prefer the solution in [3]: we are using a powerful tool like git so, why we shouldn't rely on the features it provides like **history** and the **blame** feature? In this way all will be automatic and we will not have to deal with refreshes and alignments of such notes that in few commits would be outdated/difficult to track.
I think that maybe we should keep in touch with Benjamin or Wayne in order to get their opinion on this topic and maybe refresh a [document](http://www.eclipse.org/legal/copyrightandlicensenotice.php) that is pretty old (2005) and not aligned with current tools/features

[1] https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.id/src/main/java/org/eclipse/smarthome/core/id/InstanceUUID.java
[2] https://github.com/eclipse/milo/blob/master/opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/DataTypeEncoding.java
[3] https://github.com/eclipse/vorto/blob/development/server/commons/src/main/java/org/eclipse/vorto/server/commons/AbstractZipFileExtractor.java

**Comment by ctron** [comment]
@MMaiero you are just pointing to IoT projects. And I think only smart home actually has a release done. Neither of them has graduated. So I don't think they are good candidates.

But looking at smart home, it would completely remove legal entities from the copyright header. For vorto it would remove the authors. So it would only be Eurotech.

Only Milo, which I think is s bad example because it is a one man show, uses the author/legal entity on the header alone.

I do like the smart home approach best. But it clearly violates the rules. But since I do find this the best approach, I already asked EMO that morning if we could go with that. Waiting for an answer.

But if that is not an option, I would say: go with the recommended default!

**Comment by ctron** [comment]
EMO pointed me towards license@eclipse.org with that question.

Btw, the referenced document is dated 2005, but still is referenced in the more recent "Project handbook" in the same way [1].

And not to forget, it is true that Kura is using Git, which can track contributions. But also the Kura repository does host code which is authored outside the Kura git repository, like the "soda comm" dependency. All information about that was lost when the code was copied over to the Kura git repository. So I still think all those points are still valid, although the last update was over 10 years ago.

So let's wait what license@eclipse.org gives as an input.

[1] https://www.eclipse.org/projects/handbook/#ip-copyright-headers

**Comment by amitjoy** [comment]
@ctron As you suggested, our proposition would be to have a copyright header as follows:

```
 Copyright (c) 2016 Eurotech and/or its affiliates and others
 
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
```

The contributors list is an optional element as it is mentioned in [1] and we believe it would be nice to not include it in the header at all.

[1] - https://www.eclipse.org/projects/handbook/#ip-copyright-headers

**Comment by ctron** [comment]
And the other document you were referring to strongly suggested to use it anyway.

My proposal was to a) wait for Eclipse License to respond and use a standard header without explicit naming, b) go with the eclipse default way, complete, not just partially.

**Comment by amitjoy** [comment]
@ctron The document [1] that you referred is the recently updated document and the other one [2] is very old. That's why I believe we can use the proposed copyright header as it doesn't create any further confusion regarding the contributors and contributions. On the other hand, the headers in all sources would be clean and identical everywhere.

[1] - https://www.eclipse.org/projects/handbook/#ip-copyright-headers
[2] - https://www.eclipse.org/legal/copyrightandlicensenotice.php

**Comment by ctron** [comment]
@amitjoy [1] actually points [2] .. so why do you think it is outdated?

**Comment by amitjoy** [comment]
The last updated date of [2] is quite old and whereas the last updated date of [1] is quite recent.

**Comment by ctron** [comment]
And since [1] points to [2] I don't think it supersedes [2].

**Comment by amitjoy** [comment]
@ctron I believe as [1] mentions that the contributors list is just an optional one then we can remove that section. The documents [1] and [2] don't even mandate developers to use the contributors list as well. It would definitely make life easier 😉.

**Comment by ctron** [comment]
So I will sum up up again ....

* [1] points to [2]
* No one supersedes the other
* Both make it optional
* Still [2] strongly recommends projects to make use of proper attribution
* [2] also gives reasons why to do it
* Using Git doesn't solve the issue when files get ripped out of the repository, then proper attribute by the use of Git is lost
* Most Eclipse projects follow that and seem to have little trouble with that

So:
* Let's wait for the feedback of Eclipse License to see if a more generic approach is possible ... "Copyright by Eclipse Kura contributors" (or something like that), no additional details
* If not, just follow the recommendation ... meaning in this case: copyright by "Eurotech", authored by "Amit (Eurotech) - Initial implementation and API"
* Or simply leave it as is ... meaning in this case: copyright by "Eurotech", authored by "Eurotech"

But if we make a change ... we need to do it for the whole project ... not just Kura Wires.

**Comment by amitjoy** [comment]
👍

**Comment by amitjoy** [comment]
@ctron Did you get any response from the Eclipse Legal Team on this regard?

**Comment by ctron** [comment]
Yes I did.

So both documents [1] and [2] are still valid. Not outdated. The way SmartHome did this is not an option.

So I would vote for letting it is as: Copyright <legal entity> and others, Contibutor: <legal entity>

**Comment by dwoodard1** [comment]
I also reached out to Eclipse Legal. The agreed upon header will be:

Copyright (c) 2016 <Company> and/or its affiliates and others

  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html

If contributors have a strong opinion on adding their Company name to the contributors list, they can via:

Contributors:
	Red Hat Inc

This highlights the fact that the contributor section is truly optional. I would like to update the contributing information and close this Issue.

**Comment by kaikreuzer** [comment]
> The way SmartHome did this is not an option.

Yeah, many thanks for pointing them to us 😛 

> Copyright (c) 2016 and/or its affiliates and others

@dwoodard1 Isn't there the initial legal entity missing?

**Comment by ctron** [comment]
I really like @MMaiero idea. I would've liked to do the same. Sorry for that.

**Comment by dwoodard1** [comment]
@kaikreuzer That was a copy/paste/markdown mishap. The legal entity was enclosed in <> which didn't show up. The legal entity absolutely needs to be there. The header would look like this:

Copyright (c) 2016 Eurotech and/or its affiliates and others

  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html

Again, the contributor section would be optional.

**Comment by kaikreuzer** [comment]
> The legal entity absolutely needs to be there.

Did license@eclipse.org come up with any legal reason WHY this needs to be there?

Btw, using

> Copyright (c) 2016 Eurotech and/or its affiliates and others

is not correct according to [2], in case a file is first created by e.g. someone from RedHat. So I would claim that your decision does not fullfil the requirements in [2] - although seeing that almost every Eclipse project handles it that way of course...

**Comment by ctron** [comment]
> Did license@eclipse.org come up with any legal reason WHY this needs to be there?

Not really. I would see "and others" the same as "respective" ...  and am waiting for an answer myself.

Yes ... so the template should not be `Copyright (c) 2016 Eurotech and/or its affiliates and others` but `Copyright (c) 2016 <Initial Copyright Holder> and others` or `Copyright (c) 2016 <Initial Copyright Holder>`

And I do think it is important since I already saw PRs from "others" marking this content as copyright by Eurotech, which is not correct IHMO. But I assumed that would be the case.

**Comment by kaikreuzer** [comment]
> marking this content as copyright by Eurotech, which is not correct IHMO.

...although this is the procedure in 95% of the Eclipse project as far as I can see.
And this was exactly the issue I tried to address with the "respective" - it would allow to have the same copyright header on all files of the project, thus making it easy to automatically check for its existence and to update e.g. the year. I don't feel it is beneficial to anyone to end up with 50 different headers, just because different people initially contributed a file (potentially copying it from some existing ones)...

**Comment by ctron** [comment]
I fully agree. And I do like the approach. No need to think about this anymore. I really had hoped to get this approved.

**Comment by dwoodard1** [comment]
@kaikreuzer The legal entity would be with respect to the original creator of the file. So, yes, if Red Hat was the initial contributor, the header would have Red Hat, Inc as the legal entity. I am not sure what you mean by "respective", do you have an example of this?

Certainly it would be ideal to have one header for all files in the project. I don't think Eclipse legal is to strict on the legal entity requirements as long as the EPL is consistent. I simply proposed a solution and they approved it.

**Comment by kaikreuzer** [comment]
>  I am not sure what you mean by "respective", do you have an example of this?

This was only referring to the [link given above](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.id/src/main/java/org/eclipse/smarthome/core/id/InstanceUUID.java#L2).

But ok, thanks for clarifying. So the decision for Kura actually IS to have different headers, depending on who first created a file.

**Comment by dwoodard1** [comment]
Yes, exactly. As you said, this is not ideal because we could have many different headers in our source code. However, this method does provide proper credit to the originator of the work. Due to the latter is why we decided to use this approach. I have not researched this, but I am hoping some of the Maven licensing plugins are "smart enough" to handle this for updating years when needed.

**Comment by cdealti** [comment]
> potentially copying it from some existing ones.
Kai, it's dangerous to use this verb here... ;)

**Comment by kaikreuzer** [comment]
Haha, you are not trying to tell me that you even write the license header letter by letter yourself ;-)

**Comment by dwoodard1** [comment]
I have updated the Kura [contributing.md file](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md). I would like to close this issue. I feel if we want to continue discussing options we should do so on a mailing list that includes the rest of the working group and Eclipse legal.

**Comment by ctron** [comment]
I think there are two typos in the change you made ... see PR #748
