### ISSUE TITLE
stopping via osgi> exit causes reboot via watchdog

### ISSUE THREAD

**Issue by pstanton** [eclipse/kura#684]
Kura 1.4.

Stopping kura via the "exit" command in the osgi console results in the machine rebooting shortly after.

I am assuming this is because the watchdog is not closed properly.

**Comment by pierrepitiot** [comment]
We just realized that there was a nasty bug in watchdog service: when the watchdog is disabled the thread is terminated before having disabled the watchdog. I will create a PR to fix it in the next release.

Concerning osgi exit command it is working like a kill and do not stop the services cleanly.You should use osgi>shutdown or call /etc/init.d/kura stop. In this case the watchdog will be disabled correctly.

**Comment by pierrepitiot** [comment]
PR #700 is fixing this bug

**Comment by pierrepitiot** [comment]
@pierantoniomerlino could you please review this PR

**Comment by MMaiero** [comment]
@pierrepitiot Can we close this now?
