### ISSUE TITLE
Document how to get services into the Cloud Services UI

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#690]
I couldn't find any documentation on how to let a CloudService instance show up in the new cloud service UI. I would expect such information:

* In the javadoc of CloudServiceFactory
* In the Wiki
* In the documentation

I think this should be fixed in 2.1 release of Kura.

**Comment by cdealti** [comment]
I've added a new section to the [Multiple Cloud Connections Wiki](https://github.com/eclipse/kura/wiki/Multiple-Cloud-Connections#web-ui-cloud-services).

If you think we should mention some Camel-specific aspects, please add your notes to the page

**Comment by cdealti** [comment]
@ctron Are you OK with closing this?
