### ISSUE TITLE
NPE when CloudService isn't configured

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#691]
I can't fully grasp the situation at the moment. But it somehow seems that the new multi-cloud-service-ui cannot handle the situation where the actual CloudService instance is not configured by the ConfigurationService. The UI runs into a NPE.

Since most methods in the Web UI are undocumented, it is hard to figure out what is expected from the different services.

**Comment by ctron** [comment]
So to me it looks a bit like as if the UI does not take into account the actual configured components. It takes the "id" of the CloudInstance instance and assumes that it has some configuration in the ConfigurationService. However as far as I understood, the new method `getStackComponentsPids` should be in charge to return the actual PIDs of what makes up the stack.

**Comment by ctron** [comment]
So when the Web UI is being built, I would expect the `getStackComponentsPids` to be called at least once. However a breakpoint being set at that methods does not get triggered.

**Comment by ctron** [comment]
I think the issue is located in the method `void selectConnection(GwtCloudConnectionEntry selection)`, where, instead of the factory id is used, it is fishing for factory ID by reading out the configuration.

I would assume that a direct get with the method `selection.getCloudFactoryPid()` should already provide the factory ID.

**Comment by MMaiero** [comment]
@ctron could you point me to an example that causes this issue? Why that component has not to be tracked by the configuration service? Thanks

**Comment by ctron** [comment]
Just use the camel cloud service factory.

**Comment by MMaiero** [comment]
ok, tomorrow I'll do some tests

**Comment by ctron** [comment]
Wednesday 😉

**Comment by MMaiero** [comment]
yes, it's time for me to go to bed :-D

**Comment by ctron** [comment]
Ok, I think this can be fixed by refactoring the Web UI 2 in way that the factory ID is discovered and not provided. `org.eclipse.kura.web.server.GwtCloudServiceImpl.findStackPidsByFactory(String, String)` could use the actual property from the service referenced instead.

I will give it a try.

**Comment by ctron** [comment]
So with the bugfix it works for me both ways. I did create a PR on the release branch.
