### ISSUE TITLE
Deprecate the use of Kura*Exception

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#714]
I would like to start a discussion around the use of Kura*Exceptions.

To me it seems this is no longer really used in Kura and I would like to suggest to (not technically) but deprecate the use of it. New functionality uses existing, standard Java exception likes NullPointerException, IOException, … instead of wrapping everything inside a Kura*Exception which actually hides the real reason.

@cdealti @MMaiero @dwoodard1 What do you think?

**Comment by amitjoy** [comment]
I am not sure if I am correct but so far according to my opinion, I believe the use of such custom exceptions are meant for specifying a segregation between lower layer and higher layer. I believe such specification on custom exceptions are required to never let the implementation specific checked or unchecked exceptions escalate to the higher layers. 

My proposition is to never throw lower level exception such as `SQLException` or `IOException` from lower layer to the business object layer as Business object layer do not have any idea on how to handle these lower level exceptions.

In such scenario, we could either, 

1. Convert the checked exception to `KuraException`, if the client of this bundle is expected to recover from such exceptional cause
2. Convert the unchecked exception to `KuraRuntimeException`, if the client of this bundle cannot do anything to recover

In either of these scenarios, the execution thread is suspended and the exception gets reported. In addition, we do not have to corrupt the business object layer with unnecessary exception handling.

If we are confident that the business object layer can take some recovery action when the checked exception occurs, we can convert it into a more meaningful checked exception and hence it is done using `KuraException` - a checked one. And if not, we could use the `KuraRuntimeException` - the unchecked one.

I am not sure if I am correct but I would be happy to learn more on this.

**Comment by ctron** [comment]
So I do think that the authors/designers/architects of Java mostly did a good job in designing exceptions over the last years. People do know what the mean and when a NullPointerException comes along, they now what to look for. There is whole bunch of well documented exceptions for different scenarios.

From what I have learned over many years is that, every now and then, with a new project, some sort of "common base exception" gets designed, with the idea of having some super cool functionality attached to it, which makes is absolutely necessary. Mostly, a field called "error code" some similar.

Now after a few years it turns out that this whole construct is not used at all as it was originally intended and that the error code is "internal error" in most of the cases. So no one expects anything from that.

In the end it turns out that the whole construct only add negative things. No one knows what is wrong when a "KuraException" is thrown and all the Java features, like catching a specific Exception type, are useless since there only is a single exception in use. In order to figure out what is wrong, one needs to inspect that exception, which may be even more troublesome, since KuraException is wrapped into a KuraException. Make the whole construct completely useless and causing more issues then is would ever solve.

Not even the Java code has trouble finding out what was wrong in the first place, also in your log files you get spammed with nested and nested exception stack frames.

And I think we arrived at the situation with Kura. No big deal, happened to all of us.

Now how to get rid of this? The simple answer is, you don't. So can clear up a few thing here and there over time. But the most important thing is that you start to use proper exceptions and drop the requirement to use those generic base exceptions. Don't technically deprecate them. That would again cause more trouble than it is worth. But use proper Java exceptions from now on. And when you write code, actually handle different types of exceptions when they occur.

**Comment by Coduz** [comment]
Hi @ctron,

you mean remove the usage of all Kura*Exception and start throwing Java exception? Or deprecate the usage of KuraException and wrap exceptions on more specific exception (i.e: KuraConfigException("Cannot find config file xyz", IOException ioe)?

_Alberto_

**Comment by ctron** [comment]
So after having a chat with @MMaiero and @cdealti we agreed on the following proposal:

1) If there is an exception in `java.**` already then it can be used or re-thrown, also on Kura APIs
2) If the author wants to make use of Kura\*Exception, then this is ok, but has to be done in specific way, using an actual error code, not just "internal error". Otherwise use a standard Java exception. If new error codes are needed, we add them when they are actually needed.
3) Project specific exception (e.g.  Paho*) should not be thrown outside of Kura APIs and must be wrapped in either a standard Java exception or a Kura exception. Of course for the latter 2) would apply.
4) A method signature must not define more than 3 different types of thrown exception types

**Comment by amitjoy** [comment]
@ctron +1

I completely agree that the `KuraErrorCode` must be enhanced with more context specific Error Codes so that the higher level application would know what the exception is.

**Comment by dwoodard1** [comment]
I believe the rules defined by @ctron will help improve error handling in Kura. Should we take the step of removing unhelpful error codes (i.e. "internal error")? Maybe this is not necessary as it could break applications using the code, but I agree these types of error codes should not be used in the Kura framework.

**Comment by ctron** [comment]
I wouldn't actually remove "internal error". But maybe place a comment that it is discouraged to use. And later on maybe even technically deprecate "internal error".

@MMaiero  @cdealti  @dwoodard1 So can be close this with the resolution of my comment above?

**Comment by MMaiero** [comment]
We can maybe open an issue only to track the effective implementation of what we decided

**Comment by ctron** [comment]
@MMaiero So is there some sort of "code style" document where this could be added?

**Comment by MMaiero** [comment]
not really. For now I would create a section in the contributing.md file. When we will have a sufficient number of directives we will eventually create a separate document

**Comment by ctron** [comment]
Ok fine .. I will prepare a PR after #731 has been merged.
