### ISSUE TITLE
Unnecessary toggles eth0 interface when wlan0 interface is disabled on Raspberry Pi.

### ISSUE THREAD

**Issue by ibinshtok** [eclipse/kura#721]
I saw this when testing release-2.1.0 on Raspberry Pi 2.

**Comment by ctron** [comment]
It looks like I am running in the same issue while testing with the 2.1 release branch. Any ideas on that one?

**Comment by ctron** [comment]
Is there a workaround?

**Comment by dwoodard1** [comment]
This has been a persistent issue in Kura for some time. I don't think we can address this before the v2.1.0 release.

**Comment by ctron** [comment]
So do we also drop support for Fedora then?

**Comment by MMaiero** [comment]
uhm, why? I tested very briefly the distribution on my raspberry pi 2 with fedberry, but I had no big issues. Or, at least, eth0 was working fine.

**Comment by ctron** [comment]
When I dropped it into Fedberry 24, then the eth0 was constantly being dropped.
