### ISSUE TITLE
Create a container image for cross compiling all Kura native code

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#722]
There should be a docker/vagrant/foobar container which can compile all Kura binaries.

IMHO this should be:
* some sort of Makefile for creating the binary container image
* some binary container image which can be uploaded to some sort of repository
* some sort of Makefile which can then be used to build/rebuild all Kura native binaries in that container with a single step

I would vote for this two step approach so that the first part (assembling a container) can be re-used and it is not necessary (but possible) to create the full cross-compiler setup.

**Comment by ctron** [comment]
The first step should be to list the cross compilers and libraries which are required.

@dwoodard1 @MMaiero @cdealti  Can you help with this?

**Comment by dwoodard1** [comment]
This is a good idea and work we started some time ago. After the v2.1.0 release, l will revive the work we have already done so we aren't starting from scratch.

**Comment by ctron** [comment]
As already posted on the mailing list, there is an experimental branch hosting a set of Dockerfiles and build scripts which can compile on RHEL7/CentOS7 (x86_64), Fedora 25 (ARMv6, ARMv7) and Ubuntu (x86 and x86_64).

However we do need a way to also target the other architectures like Yocto Linux and ARMv5 which currently cannot be re-compiled.

https://github.com/ctron/kura/tree/feature/fix_c_build_warnings_1/nativeBuild
