### ISSUE TITLE
Fix website to follow trademark guidelines

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#729]
Currently the website does not follow the Eclipse trademark guidelines at all [1].

At least in the header it should the "Eclipse Kura™ is an iot.eclipse.org" project.

[1] https://eclipse.org/legal/logo_guidelines.php

**Comment by cdealti** [comment]
@dwoodard1 do you plan to work on the web site for Kura 3.0?

**Comment by dwoodard1** [comment]
Yes, working on it now actually.

**Comment by dwoodard1** [comment]
@ctron Made a first pass at adhering to the new guidelines. Let me know if I missed something: https://www.eclipse.org/kura/

**Comment by ctron** [comment]
👍 While you are at it, I would suggest to add a link to the Eclipse Security page aka "how to report a security vulnerability" [1], as we might follow Ian's suggest and enforce this in the near future.

[1] https://www.eclipse.org/security/

**Comment by dwoodard1** [comment]
Added a link on this page: https://www.eclipse.org/kura/community.php#contributing
