### ISSUE TITLE
Unable to configure CloudService instance when component gets unregistered

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#732]
I think this is the same situation as with the `ConfigurableComponent`. If the `CloudServiceFactory` wants to create a new instance, it **must** result in the creation of a CloudService instance with OSGi, if it is usable or not. Otherwise the Mulit-Cloud-Service Web UI can no longer configure the instance in order to correct the issue.

To me it looks like the issue with `ConfigurableComponent` was just ported over to the Multi-Cloud-Service Web UI.

**Comment by ctron** [comment]
@MMaiero @cdealti I would like to have a short chat with you about this one. Since it somehow seems to me that we are replicating the mistakes of the configuration service again. And there may still be time to fix this.

**Comment by cdealti** [comment]
@ctron before opening new bugs, is this somewhat related to the latest part of the discussion of #466?
Unless this is an entirely new issue (you did not describe the use case in this PR) I believe it does not need to be addressed for 2.1.0?

**Comment by ctron** [comment]
I don't think this is related to usse #466. And I do think this should be addressed for 2.1.0. If we define and release an interface and behavior now, we will be bound to it for some time and I do think this requires a small change in `CloudServiceFactory` in order to resolve it.

Beside it could explain the issue @MMaiero encountered.

**Comment by cdealti** [comment]
Can you please prepare a live demo of what's going on before the call?

**Comment by ctron** [comment]
So the proposal is to add a method to the `CloudServiceFactory` API which allows the factory to provide a list of service PIDs for `CloudService` instances it covers. The Web UI will query the `CloudServiceFactory` instances for their services instead of finding them out by itself.

This allows each factory implementation to provide custom logic on its `CloudService` instances.
