### ISSUE TITLE
Fedora distribution fails to start up

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#737]
It seems as if the Fedora distribution fails to start up due to the linker error with `libudev.so.0`

**Comment by cdealti** [comment]
Duplicate of #321?

**Comment by ctron** [comment]
Well I would count #321 as the root of all evil. But AFAIK there should be some workaround in 2.1 which creates a symlink. Seems this workaround is not working.

The proper fix for this would have been in PR #622, but it seems not to be in the 2.1 release branch.

**Comment by cdealti** [comment]
Isn't libudev.so.0 available from any package in Fedora?
If not, cannot you add the recompiled library linking libudev.so.1 from your #622 to the 2.1 release branch?

**Comment by ctron** [comment]
No. I can do that, yes.

**Comment by ctron** [comment]
The question is just how to change the platform filter?

**Comment by cdealti** [comment]
Since we have a new ``fedorapi`` profile where ``kura.os.version`` is set to ``fedora`` I would set the filter to the one below.

```lib/linux/x86_fedora/libEurotechLinuxUdev.so; osname=Linux; processor=x86; selection-filter="(&(kura.os.version=fedora))"```

**Comment by cdealti** [comment]
@ctron Can we close this?
