### ISSUE TITLE
Unable to establish stable network connection on Fedberry

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#742]
This may be related to #721 but I am not sure.

While testing with Fedberry 24 I constantly run into issues where the network connection to the Raspberry PI is terminated and the PI is not evening pingable anymore.

I dug a bit through the Kura code and found a few locations where there are special cases for "Intel Edison", although they are more related to "systemd" instead.

Maybe there is an issue with "Network Manager", "systemd" or some other component. I am trying to track it down in this issue.

**Comment by ctron** [comment]
@ccustine Do you have any idea what could go wrong?

**Comment by MMaiero** [comment]
@ctron Any update on this? Did you have time to test what I passed you? I'm trying to push hard to close PR 720, in order to finally release, but we need some info about fedora work.

**Comment by ctron** [comment]
So I did try out your image. Installing the RPM packages you mentioned and during the startup it already lost the network connectivity.

However I did not try with the Oracle JVM. I will install it and re-try.

**Comment by ctron** [comment]
So whatever this image did. It is even worse than the Kura image. It completely disabled the network interface.

**Comment by ctron** [comment]
So using the Oracle Java JVM is falls back to the original behavior of dropping the eth0 connection every now and then

**Comment by cdealti** [comment]
@ctron @MMaiero please update with the latest findings.

**Comment by ctron** [comment]
It seems to be stable now. However I am not sure what resolved this issue.
