### ISSUE TITLE
WLAN not detected as WLAN on Fedberry

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#743]
While investigating issue #742 I recognized that the interface `wlan0` is not being detected as a wireless interface.

**Comment by ctron** [comment]
Not from my side. I am not sure how this detection really works. But if you like I can try to dig through the WLAN code stack.

**Comment by cdealti** [comment]
Yes, please (but with moderation). Please also share the logs with Matteo.

**Comment by cdealti** [comment]
@ctron ping

**Comment by ctron** [comment]
I will send you the logs via e-mail. I only found this one:

```
2016-11-24 17:43:00,337 [Component Resolve Thread (Bundle 6)] INFO  o.e.k.c.l.u.LinuxProcessUtil - executing: bluetoothd
2016-11-24 17:43:00,341 [Component Resolve Thread (Bundle 6)] ERROR o.e.k.c.u.ProcessUtil - Error waiting from SafeProcess output
java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "bluetoothd": error=2, No such file or directory
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.eclipse.kura.core.util.ProcessUtil.exec(ProcessUtil.java:57)
        at org.eclipse.kura.core.util.ProcessUtil.exec(ProcessUtil.java:40)
```

It looks like as if bluetooth is working differently on Fedora.

**Comment by cdealti** [comment]
@ctron we have temporarily run out of RPI3.  Can you please send the whole /var/log directory when wlan0 is not detected?

**Comment by ctron** [comment]
@MMaiero did have a look at it yesterday. I did send the screenshots afterwards. He didn't find anything interesting in the log files though.

**Comment by MMaiero** [comment]
@ctron Could you please send me the result of the following commands?

- `iw dev wlan0 info`

- `iwconfig wlan0`

Thanks

**Comment by ctron** [comment]
Looks like an easy problem now:

```
[root@localhost ~]# iw dev wlan0 info
-bash: iw: command not found
[root@localhost ~]# iwconfig wlan0
-bash: iwconfig: command not found
```

**Comment by ctron** [comment]
However I would expect some output like that in the Kura log file.

**Comment by MMaiero** [comment]
What fedberry image are you running?
Did you follow the instructions provided by @ccustine? https://github.com/eclipse/kura/blob/develop/kura/distrib/src/main/resources/fedorapi/README.md

**Comment by ctron** [comment]
```
fedberry-minimal-24.1-rc1.raw.xz
Linux localhost 4.4.24-400.a59ca8f.bcm2709.fc24.armv7hl #1 SMP Wed Oct 12 12:30:03 AWST 2016 armv7l armv7l armv7l GNU/Linux
```

No, but that doesn't seem to include the fix anyway:

```
dnf install -y wireless-tools
```

**Comment by ctron** [comment]
The install and a reboot did solve the issue. So I think the README should be fixed up, since there are a few things off.

**Comment by MMaiero** [comment]
So, I've just received a rpi 3, installed a fresh fedberry-minimal-24.1-rc1, executed `dnf -y install unzip psmisc tar telnet bind iptables iptables-services dhcp hostapd dos2unix wireless-tools net-tools java-1.8.0-openjdk-headless` as specified [here](https://github.com/eclipse/kura/blob/release-2.1.0/kura/distrib/src/main/resources/fedorapi/README.md) and installed kura built from the release-2.1.0 branch.

For me, everything is working:
<img width="926" alt="schermata 2016-12-02 alle 15 04 33" src="https://cloud.githubusercontent.com/assets/10448126/20836886/b0354d4e-b8a1-11e6-9877-f84623ab9cbb.png">
<img width="863" alt="schermata 2016-12-02 alle 15 04 41" src="https://cloud.githubusercontent.com/assets/10448126/20836895/c526c458-b8a1-11e6-9059-adaae52f5bc7.png"

@ctron Is it working for you?

**Comment by ctron** [comment]
See my last comment ... yes:

> The install and a reboot did solve the issue.

**Comment by MMaiero** [comment]
Oh, missed that. So I close the issue
