### ISSUE TITLE
CQ for minimal-json

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#749]
The idea is to replace `org.json` with `minimal-json` as it is very lightweight and it is used by many other eclipse projects.

The Github URL: https://github.com/ralfstx/minimal-json
The Source Code: https://github.com/ralfstx/minimal-json/releases/download/0.9.4/minimal-json-0.9.4-sources.jar

The benchmark comparison with other renowned JSON libraries: http://bit.ly/2fuGlFf

**Comment by amitjoy** [comment]
#750

**Comment by ctron** [comment]
This should be an easy piggyback.

Can we wait until the IP log for 2.1 is approved?

**Comment by amitjoy** [comment]
@ctron 👍

**Comment by dwoodard1** [comment]
The IP log for v2.1.0 has been approved: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12250

**Comment by amitjoy** [comment]
@dwoodard1 @ctron @cdealti We can go ahead in filing the CQ for minimal-json. I would try to make a pull request amending all the necessary changes for #750.

**Comment by ctron** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12262

**Comment by amitjoy** [comment]
@ctron Any update on the CQ? I believe it should not take time as it is already in Eclipse Orbit repository.

**Comment by ctron** [comment]
It should. But it is still pending. Approved by PMC though.

**Comment by ctron** [comment]
Approved.

**Comment by ctron** [comment]
Merged
