### ISSUE TITLE
Intel Edison with Networking Support

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#75]
Kura with networking support does not work properly with the latest Intel Edison image. Two issues identified thus far:

1. The installation uses the single WiFi interface to set the Edison up as a WiFi Access Point. If a client connects to the access point, the web UI (172.16.1.1:8080/kura) is not operating correctly. The services are not available to configure Kura.
2. The DataTransportService is not being activated correctly. This is likely related to item 1.

Kura: v1.3.0
Intel Edison: Linux edison 3.10.17-poky-edison+

--Dave

**Comment by cdealti** [comment]
We don't have plans to try to fix this port. It would be a good exercise for anyone willing to contribute to Kura.
