### ISSUE TITLE
[DbDataStore] defrag and checkpoint are not per-table operations

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#751]
DbDataStore exposes two methods ``defrag`` and ``checkpoint`` that act on the entire DB and not on the DB table associated with the DbDataStore.
When multiple ``DbDataStore`` instances exists (since the introduction of the multiple cloud connections feature), each ``HouseKeeperTask`` instance will periodically call ``defrag``, potentially concurrently.

**Comment by cdealti** [comment]
This will be addressed as part of the switch to the H2 Database.

**Comment by nicolatimeus** [comment]
In the H2 implementation checkpoint is performed per-database instance instead of per-table.
