### ISSUE TITLE
There should be a way to start/stop OSGi bundles from the Web UI

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#757]
Currently there is list of OSGi bundles on the Web UI, but there is no way to stop or start bundles. There should be way to stop and start OSGi bundles from the Web UI as well, like it is available from the command line.

**Comment by dwoodard1** [comment]
Agreed. This is a deprecation. We had this feature in the old UI ( <v2.0.0), but it was lost in the transition. The code can be revived from the deprecated org.eclipse.kura.web bundle.

**Comment by dwoodard1** [comment]
https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.web/src/main/java/org/eclipse/kura/web/client/device/BundlesTab.java
