### ISSUE TITLE
Modem Additions

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#76]
This was originally filed as bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461555.

Original comments from bug:

Modem addons for USB and serial devices
    Huawei USB Exxx E220, E620, E173
    Telit serial GE865
    Serial modem communication for Raspberry

Commitet at Fork https://github.com/devNbis/kura.git

**Comment by ibinshtok** [comment]
We only support Telit HE910, LE910, DE910, GE910, and CE910 modems on Eurotech platforms.
Those modems have not been tested on Raspberry Pi.

**Comment by devNbis** [comment]
Ok, but we use it and tested it in our prototype. From my point of view it's sharing the results to the community so that others don't wast time in implementing.

**Comment by dwoodard1** [comment]
@devNbis Are you still interested in contributing this to Kura? I know this is very old, we are trying to clean up some of our old, outstanding issues.
