### ISSUE TITLE
Change Housekeeping schedule from scheduleAtFixedRate to scheduleWithFixedDelay

### ISSUE THREAD

**Issue by wbowers** [eclipse/kura#767]
The DbDataStore currently schedules the Housekeeping task to run at regular intervals using scheduleAtFixedRate.  If the Housekeeping process takes longer than the configured interval (for example if there is a very large data store), the the housekeeping task is continuously running.  

It would be better to have the housekeeping task delay the configured interval after it completes.  That seems closer to the intent and allows tiem for other processing even with small housekeepig nintervals.

So changing scheduleAtFixedRate to scheduleWithFixedDelay would be better.

**Comment by MMaiero** [comment]
Closed by #969
