### ISSUE TITLE
Version problems for org.eclipse.kura.api

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#769]
Currently both `release-2.1.0` and `develop` declare version `1.0.10` for `org.eclipse.kura.api`.

However the content is actually different and the "release" branch is missing the wires additions.

This causes the problem locally when you are working with both versions that Maven will choose 1.0.10 over 1.0.10-SNAPSHOT, so the Web UI module doesn't compile anymore.

IMHO the version for `org.eclipse.kura.api` should be `1.1.0` now.

**Comment by dwoodard1** [comment]
Historically work on the develop branch stops once we have created the release branch. When we merged the release branch back to develop, we would take care of updating the develop versions. As the team grows, this may no longer work.

I am surprised Maven can't distinguish between snapshot bundles (1.0.10-SNAPSHOT) and release bundles (1.0.10), though I believe you. This should be a problem for all the bundles, not just the API bundle, correct?

Until we have a better management solution, can you just remove the Kura bundles from the local repo before building (rm -rf ~/.m2/repository/org/eclipse/kura)?

**Comment by ctron** [comment]
Well Maven can, if you use it right. The web bundle imports the Kura API like this:

```xml
		<dependency>
			<groupId>org.eclipse.kura</groupId>
			<artifactId>org.eclipse.kura.api</artifactId>
			<version>[1.0,2.0)</version>
			<scope>provided</scope>
		</dependency>
```

So Maven has the choice to use 1.0.10 or 1.0.10-SNAPSHOT. It decides for 1.0.10, because this one is released.

Now IMHO Kura API should be 1.1.0 .. because of semantic versioning. But it still got merged as is.

**Comment by dwoodard1** [comment]
I see, that is a problem. It looks like your PR addresses this. I will see if we can get this merged ASAP.
