### ISSUE TITLE
Data Service will not connect for other locale than an english one

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#77]
This bug was originally filed at: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463915.

Message from original bug:

The data service will not start up/connect once you have a non-english locale defined, since it searches for the keyword „"metric" within the output of ifconfig <interface>. Unfortunately if you have another locale configured, for example german, ifconfig returns "metrik" (german word for metric) and kura fails to parse the output and throws a runtime exception (StringIndexOutOfBoundsException) so that the data service is not available. After changing the locale with raspi-config everything worked fine.

Happened to me on a raspberry pi with raspbian installed.

Also see my blog: http://icanseedeadcats.com/2015/03/24/eclipse-iot-challenge-mqtt-communication-for-hot-desks-featuring-kura-mosquitto-and-paho-and-project-wrapup/

Below is a snippet of the stacktrace:

2015-03-21 20:39:28,330 [Component Resolve Thread (Bundle 6)] ERROR o.e.k.c.d.t.
m.MqttDataTransport - Invalid client configuration. Service will not be able to connect until the configuration is updated
java.lang.StringIndexOutOfBoundsException: String index out of range: -49
 at java.lang.String.substring(String.java:1911)
 at org.eclipse.kura.linux.net.util.LinuxNetworkUtil.getCurrentMtu(LinuxNetworkUtil.java:294)
 at org.eclipse.kura.linux.net.NetworkServiceImpl.getNetworkInterface(NetworkServiceImpl.java:439)
 at org.eclipse.kura.linux.net.NetworkServiceImpl.getNetworkInterfaces(NetworkServiceImpl.java:314)
 at org.eclipse.kura.core.system.SystemServiceImpl.getPrimaryMacAddress(SystemServiceImpl.java:377)
 at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:633)

**Comment by cdealti** [comment]
Unfortunately the textual output of a command is not an API and there is no formal specification for it.
Another example is that currently Kura is not able to parse the output of the ```ifconfig``` program of Fedora based distributions, even when the English locale is used. We have a couple of ideas on how to improve the situation but nothing scheduled in the short term.

**Comment by cdealti** [comment]
We are replacing most of the ``ifconfig`` calls with ``ip``.
This change should fix the above issue and make the Kura network stack more portable across Linux distributions.
These changes have been pushed to the ``develop`` branch.
Feedback is appreciated.

**Comment by cdealti** [comment]
I've contacted the user who originally opened the bug but I've haven't received a reply.
The situation has been improved as described above.
I'll keep the issue open postponing it to Kura 2.1.0.

**Comment by MMaiero** [comment]
Closing as for long time we had received no negative feedback. Eventually we will reopen it later.
