### ISSUE TITLE
Move Utility classes to the respective bundle

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#774]
Currently several utility classes reside in `org.eclipse.kura.core` bundle (`org.eclipse.kura.core.util` and `org.eclipse.kura.core.linux.util` packages). We can deprecate these classes and move these to `org.eclipse.kura.util` bundle.

My proposition is to move these classes to its respective utility bundle rather than putting it inside `org.eclipse.kura.core`. It is more cohesive if kept inside the utility bundle.

**Comment by ctron** [comment]
Agreed! Also I think there are more locations which we should check. Like the "web" bundle.

I would suggest though that utility functions should not have OSGi service character. If that is the case it should be in a different bundle. With API and implementation bundle.
