### ISSUE TITLE
[Testing] Unit Tests for org.eclipse.kura.core.net

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#779]
It will be submitted by @djurod.
Requires #778.

**Comment by cdealti** [comment]
@djurod can we close this?

**Comment by djurod** [comment]
Not yet, there are still some pull requests pending. PR #1089 is still open and I at least one more PR is needed to include all written tests for core.net

**Comment by cdealti** [comment]
@djurod can this be closed now?

**Comment by djurod** [comment]
No, not yet. I still have to prepare a pull request (should be the last one for core.net) with the already written tests.

**Comment by cdealti** [comment]
@markoer can you please check again with @djurod? Shall we postpone?

**Comment by markoer** [comment]
The PR waits for @ibinshtok's decision regarding invocation of getByAddress(byte[]).

**Comment by ibinshtok** [comment]
Closing this issue since associated PR#1336 was merged.
