### ISSUE TITLE
[Testing] Create unit tests for configuration service

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#782]
Add unit tests for configuration service implementation.

Test behavior of JUnit categories e.g. PublicTests (test API - or maybe all methods), PrivateTests (run only private implementation method tests), PublicOnlyTests (use only public API for setup with no private field modification).

**Comment by cdealti** [comment]
@markoer can we close this?

**Comment by markoer** [comment]
I suppose yes, once you decide what to do about #1075 (2 comments are open) and #1130 is merged.
