### ISSUE TITLE
[Kura 2.1.0] QA for the Raspberry PI 3

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#788]
http://www.eclipse.org/downloads/download.php?file=/kura/docs/qa/Kura_Test_Specification.xlsx

Assigned to @markoer.

**Comment by markoer** [comment]
NET-FW-001 test case should be updated with more specific preconditions:
* wlan0 enabled and configured for lan as in NET-WIFI-001
* set DROP policy on INPUT in firewall, otherwise all will be allowed, anyway: ```iptables --policy INPUT DROP```
