### ISSUE TITLE
Update MQTT Namespace guidelines in the online doc

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#79]
This bug was filed as: https://bugs.eclipse.org/bugs/show_bug.cgi?id=480530.

Original message:

As of Kura 1.3, the $EDC prefix is not set in stone anymore, so it would be great to update the doc so as to make it clear that the prefix is customizable.

**Comment by cdealti** [comment]
@dwoodard1 to be done just after the release.

**Comment by dwoodard1** [comment]
@cdealti Can you have someone review this? http://eclipse.github.io/kura/ref/mqtt-namespace.html
