### ISSUE TITLE
[Kura 2.1.0] QA for the Raspberry Pi Model B+ 

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#790]
http://www.eclipse.org/downloads/download.php?file=/kura/docs/qa/Kura_Test_Specification.xlsx

Assigned to @markoer

**Comment by markoer** [comment]
Cannot test on B+ as it is not available for purchase.

**Comment by cdealti** [comment]
In Italy this is still available.
However i wonder if we should drop its support (disabling the profile in the build and not publishing the installer). @dwoodard1 any thoughts?

**Comment by dwoodard1** [comment]
@cdealti I think I am ok not publishing new installers for the Raspberry Pi B and B+. I think we do need to make old installers available. I can add a section to the Kura website for downloads of previous versions.

**Comment by cdealti** [comment]
There is a validation spreadsheet in the Community site by Marko and Leonardo. Something has not been tested. Maybe we can publish them.
