### ISSUE TITLE
Switch to Tycho Java profile validation

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#792]
Since we now have a more recent Tycho version we could try to use Java profiles with the BREE.

Also see: [1]

From what I understood we would specify e.g. `JavaSE/compact2-1.8` as the BREE and Tycho would perform a validation based on that.

What do you think?

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=437923

**Comment by cdealti** [comment]
Compact2 validation has been removed in 5154e2550bd7dff99f49df6bd4ab2a0f431922a2. However, the README.md has not been updated accordingly. I guess this can be closed
