### ISSUE TITLE
[Kura 2.1.0] QA for the Intel Edison

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#795]
http://www.eclipse.org/downloads/download.php?file=/kura/docs/qa/Kura_Test_Specification.xlsx

Assigned to @markoer.

**Comment by markoer** [comment]
We didn't discuss Intel Edison yesterday. Did you discuss it with Dragan?

**Comment by cdealti** [comment]
It's lower priority (P2). Only if we have time. I'll update Dragan separately.

**Comment by markoer** [comment]
Don't know what to purchase for it to even turn on.

**Comment by cdealti** [comment]
The Intel Edison Breakout Board
http://www.intel.com/content/www/us/en/support/boards-and-kits/intel-edison-boards/intel-edison-breakout-board.html
https://www.amazon.com/Intel-Edison-Breakout-Components-EDI1BB-AL-K/dp/B00ND1KNXM

**Comment by dwoodard1** [comment]
@cdealti Where are we with the Edison? Are we doing QA?

**Comment by cdealti** [comment]
0%. Nobody is doing QA with the Edison.

**Comment by dwoodard1** [comment]
@cdealti Installed Kura and connected to cloud. All services appear to be up and running, but did not perform full QA.

**Comment by cdealti** [comment]
OK, this platform needs a maintainer.
