### ISSUE TITLE
[Kura 2.1.0] QA for the the Raspberry PI 3 and Fedberry

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#796]
http://www.eclipse.org/downloads/download.php?file=/kura/docs/qa/Kura_Test_Specification.xlsx

**Comment by ctron** [comment]
So as long as issue #742 is unsolved this is untestable

**Comment by cdealti** [comment]
@ctron Please let me know if you can take care of this task. I'll let you know later on where we can share/archive the validation spreadsheet. I would really like to have all the QA completed by the end on next week.

**Comment by dwoodard1** [comment]
@ctron This is the last KURA-2.1.0 milestone issue assigned to you. Do you have an update?

**Comment by cdealti** [comment]
@ctron Instructions are [here](https://github.com/eclipse/kura/tree/develop/kura/distrib/src/main/resources/fedorapi) and as far as I know these are correct.

About the JVM for the Fedora installer, Open JDK from Fedora package should be enough

**Comment by ctron** [comment]
Just recapping from the e-mail.

The referenced file is outdated, the better one is in the release-2.1.0 branch. However also this one is missing the "usbutils" package.
