### ISSUE TITLE
[Kura 2.1.0] Restore Javadoc generation

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#812]
There was a first refactor by me where this worked:
https://github.com/eclipse/kura/commit/242e8b969767c82ed50517d8b74dee0bb715e65e

But the change was partially reverted in this merge:
https://github.com/eclipse/kura/commit/76054e125f318865f888b98253bbbe923768d58c

**Comment by dwoodard1** [comment]
@cdealti I don't understand why those PRs are relevant. Are we sure this change didn't cause the problem: https://github.com/eclipse/kura/pull/350/commits/ef5f38e59aa621fecc774db0cd96ce13668af9b8

**Comment by dwoodard1** [comment]
Ignore my previous comment.

**Comment by cdealti** [comment]
@dwoodard1 I believe the real problem is that the pom first build deleted the target directory so deleting the site/apidocs generated by the manifest first build :-(

**Comment by dwoodard1** [comment]
@cdealti I don't think the pom first build is the problem. If I just perform the manifest_pom build, the target/site directory is deleted. If I build an individual project (ex: org.eclipse.kura.api), the site directory remains. This issue was added somewhere, as historically the API docs were pulled directly from the Hudson build server from the API bundle target/site directory.

I think your changes are good, but I am hesitant to merge as-is because it breaks the build. I will try to take a look in the morning to see if things can be cleaned up.

**Comment by cdealti** [comment]
> I don't think the pom first build is the problem. If I just perform the manifest_pom build, the target/site directory is deleted

I've just tried with develop, release-2.1.0 and the KURA_1.4.0_RELEASE and they all behave the same.
The target/site directory is populated if I limit the build to the manifest_pom.xml.

Then when I build mvn -f pom_pom.xml **clean** install the target directory is wiped out.

> This issue was added somewhere, as historically the API docs were pulled directly from the Hudson build server from the API bundle target/site directory.

Then I think something has changed in the Hudson build.

**Comment by cdealti** [comment]
@dwoodard1 we still need to move the Javadoc elsewhere before the pom_pom.xml is built, don't we?

**Comment by dwoodard1** [comment]
Yes. We could put them into a tmp directory (kura/tmp) and move them to kura/distrib/target or kura/target after the execution of pom_pom. I can give this a try unless you already have a proposed solution.

**Comment by ctron** [comment]
I ran into some additional issues with JavaDoc.

The current way Javadoc is being configured requires to early-build to "generate-sources". This is done from the main build "manifest_pom.xml". However if some task up to generate-sources (like the Web UI) requires already those dependencies, then the javadoc generation will fail with dependency resolution issues.

I would suggest to drop the default javadoc generation, at least for Kura 3.0.0, and use the Tycho Document Bundle plugin [1]

[1] https://www.eclipse.org/tycho/sitedocs-extras/tycho-document-bundle-plugin/javadoc-mojo.html

**Comment by dwoodard1** [comment]
Maybe we are making this too complicated. We just need Javadocs for the API bundle, correct? This is what we have done previously and it seemed to work okay.

**Comment by ctron** [comment]
Again, if we use the "Tycho Document Bundle plugin", then we can let it generate all Javadocs in a single run, at the end of the build for a set (or a single) P2 feature. Which we will have anyway in the end of a P2 build. That should be easy and yet cover most of the stuff we want to be public.

**Comment by dwoodard1** [comment]
@ctron @cdealti Have a look at #896 . The documentation for the Tycho bundle isn't great, but it does seem to be a good fit for our style project. Let me know what you think.

**Comment by dwoodard1** [comment]
@cdealti This is fixed on develop, I can manually create the Javadocs for the v2.1.0 release. Can we close this?

**Comment by cdealti** [comment]
OK. Thanks
