### ISSUE TITLE
Replace version ranges in Web UI project with properties from 'config.properties'

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#819]
Maven version ranges are evil [1].

The Kura Web 2 project should be refactored to use the version properties from the global `config.properties` file.

The issue which I current have is that the API bundle now got incremented to 1.2.0-SNAPSHOT. Now I know for sure that the Web UI can't work with API 1.1 or 1.0 anymore. Yet putting in a version range from 1.1 or 1.2 is impossible since Maven does not check for local artifacts (and 1.2.0-SNAPSHOT is only local for the moment) but only on remote repositories.

[1] https://nelsonmorris.net/2012/07/31/do-not-use-version-ranges-in-project-clj.html

**Comment by cdealti** [comment]
I believe this has been fixed by converting web2 to a manifest-fist project.
See #872.
