### ISSUE TITLE
Consider providing a Maven archetype for Kura bundle scaffolding

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#82]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=440544.

Original message:

I don't know what are the plans regarding a possible contribution of PDE plug-ins that would ease the creation of new Kura bundles from the Eclipse IDE, but it would be really great to have some basic tools helping in bootstrapping a Kura bundle. Maybe a Maven archetype would be even better than PDE tooling since it would virtually allow to rely on command-line only for building one's first Hello World.

I'm thinking of things like:
- setup the bundle so as it has one dummy component already configurable over ConfigAdmin (xml file in OSGI-INF/metatype/xxx is already there, component has a service.pid, etc.)
- setup the pom.xml so as the Maven project is by default belonging to a parent POM already bringing the Tycho settings, dependency to Kura target platform, etc...
- setup the bundle so as it's properly hooked up to an sl4j logger

Icing on the cake would be other archetypes (or archetype parameters) to automatically generate the plumbing for having e.g. a component hooked up to the DataService, or CloudService, etc.

ping :)
I wonder if someone in the community as done something similar already, maybe?

Hi Benjamin,

I think this is a very useful idea. Is there useful documentation on how to create these types of PDE plugins? I will to try and gauge the effort behind doing this.

Thanks,
--Dave

**Comment by dwoodard1** [comment]
List of features to include in archetype:

- Enable CI Builds
- Compatible with Tycho build
- Maven clean install should build application bundle
- Maven package for creating DP
- Include Emulator in Eclipse
- Include example unit test
- Include target platform
- Factor out parent pom

**Comment by mcarrer** [comment]
Hi David. 
   that's great!

How about keeping the interview process aligned with the maven quickstart archetype?

-Marco

[mcarrer@mcarrer-mbp] ~ % mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart 

[INFO] Generating project in Interactive mode
[INFO] Archetype [org.apache.maven.archetypes:maven-archetype-quickstart:1.1] found in catalog remote
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/archetypes/maven-archetype-quickstart/1.1/maven-archetype-quickstart-1.1.jar
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/archetypes/maven-archetype-quickstart/1.1/maven-archetype-quickstart-1.1.jar (7 KB at 5.3 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/apache/maven/archetypes/maven-archetype-quickstart/1.1/maven-archetype-quickstart-1.1.pom
Downloaded: http://repo.jenkins-ci.org/public/org/apache/maven/archetypes/maven-archetype-quickstart/1.1/maven-archetype-quickstart-1.1.pom (2 KB at 6.2 KB/sec)
Define value for property 'groupId': : MyGroup
Define value for property 'artifactId': : MyArtifact
Define value for property 'version':  1.0-SNAPSHOT: : 
Define value for property 'package':  MyGroup: : my.group     
Confirm properties configuration:
groupId: MyGroup
artifactId: MyArtifact
version: 1.0-SNAPSHOT
package: my.group
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Old (1.x) Archetype: maven-archetype-quickstart:1.1
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: MyGroup
[INFO] Parameter: packageName, Value: my.group
[INFO] Parameter: package, Value: my.group
[INFO] Parameter: artifactId, Value: MyArtifact
[INFO] Parameter: basedir, Value: /Users/mcarrer
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] project created from Old (1.x) Archetype in dir: /Users/mcarrer/MyArtifact
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.298 s
[INFO] Finished at: 2016-05-17T15:58:39+02:00
[INFO] Final Memory: 16M/245M
[INFO] ------------------------------------------------------------------------

[mcarrer@mcarrer-mbp] ~ % ls -R MyArtifact/
pom.xml  src/

MyArtifact//src:
main/ test/

MyArtifact//src/main:
java/

MyArtifact//src/main/java:
my/

MyArtifact//src/main/java/my:
group/

MyArtifact//src/main/java/my/group:
App.java

MyArtifact//src/test:
java/

MyArtifact//src/test/java:
my/

MyArtifact//src/test/java/my:
group/

MyArtifact//src/test/java/my/group:
AppTest.java

**Comment by dwoodard1** [comment]
Hello,

The interview portion is already setup that way. Let me know if you are seeing something different.

I updated the request changing the class name from KuraExample to KuraApp.

--Dave
