### ISSUE TITLE
Stopping Kura with Monit

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#83]
This bug was originally reported at https://bugs.eclipse.org/bugs/show_bug.cgi?id=450214.

Original message:

At present, when stopping Kura, the init.d script telnets into the OSGi container and stops the framework. If Monit is being used to control Kura, it will restart the framework when it detects the missing process. The init.d script should be enhanced to correctly shutdown Kura even if controlled by Monit.

--Dave

**Comment by cdealti** [comment]
I don't see the need to fix this. Just stop monit and control Kura as desired.

**Comment by hndave** [comment]
Hello 
Has anybody faced this issue with the PositionService. Most likely I am not doing something right, but can't pin point what it is.
Here is my situation.
- I have successfully added a USB GPS sensor to Raspberry Pi. I can see the GPS coordinates in the Kura Status page.- I modified the heater.xml  to include a reference to the PositionService and added the bind/unbind methods in the heater.java implementation class.- Now when i am trying to deploy the heater.dp package, i am seeing the following errors. - I can see the PositionService running, the .dp package is not able to resolve it at runtime.
Error while deploying heater.dp
!MESSAGE [SCR] Exception occurred while getting method 'setCloudService' of class org.eclipse.kura.demo.heater.Heater  Details: Problematic reference = Reference[name = CloudService, interface = org.eclipse.kura.cloud.CloudService, policy = static, cardinality = 1..1, target = null, bind = setCloudService, unbind = unsetCloudService] of service component = org.eclipse.kura.demo.heater.Heater component implementation class = org.eclipse.kura.demo.heater.Heater located in bundle with symbolic name = org.eclipse.kura.demo.heater bundle location = osgi-dp:org.eclipse.kura.demo.heater!STACK 0java.lang.NoClassDefFoundError: org/eclipse/kura/position/PositionService at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Class.java:2688) at java.lang.Class.getDeclaredMethod(Class.java:2115) at org.eclipse.equinox.internal.ds.model.ComponentReference.getMethod(ComponentReference.java:104) at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:331) at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:432) at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)

My Heater.xml file additions : 
<reference name="CloudService"              policy="static"              bind="setCloudService"                     unbind="unsetCloudService"                     cardinality="1..1"               interface="org.eclipse.kura.cloud.CloudService"/>                 <reference name="PositionService"      bind="setPositionService"      unbind="unsetPositionService"      policy="static"    cardinality="1..1"    interface="org.eclipse.kura.position.PositionService" />
MANIFEST.MF file
 
Manifest-Version: 1.0Bundle-ManifestVersion: 2Bundle-Name: org.eclipse.kura.demo.heaterBundle-SymbolicName: org.eclipse.kura.demo.heater;singleton:=trueBundle-Version: 1.0.2.qualifierBundle-Vendor: EUROTECHBundle-RequiredExecutionEnvironment: JavaSE-1.6Service-Component: OSGI-INF/*.xmlBundle-ActivationPolicy: lazyImport-Package: org.eclipse.kura.cloud; version="[1.0,2.0)", org.eclipse.kura.configuration; version="[1.0,2.0)", org.eclipse.kura.message; version="[1.0,2.0)", org.osgi.service.component;version="1.2.0", org.slf4j;version="1.6.4"Require-Bundle: org.eclipse.kura.api

Any help will be greatly appreciated.
ThanksHitesh Dave

**Comment by dwoodard1** [comment]
Hello,

Could you please open a new Issue? This issue is closed and not related to your question.

For reference, it appears you are not importing org.eclipse.kura.position in your MANIFEST.MF. Doing so should resolve your issue.

Thanks,
--Dave

**Comment by hndave** [comment]
Thanks for your quick response. I compared the manifest files of the emulator and figured out the missing entries under imported packages.
Thanks again.
Hitesh

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 18, 2016 at 9:08 AM, dwoodard1<notifications@github.com> wrote:   
Hello,

Could you please open a new Issue? This issue is closed and not related to your question.

For reference, it appears you are not importing org.eclipse.kura.position in your MANIFEST.MF. Doing so should resolve your issue.

Thanks,
--Dave
