### ISSUE TITLE
[Testing] Fix and re-enable tests

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#831]
We need to fix and re-enable existing tests recently disabled in manifest_pom.xml.
The tests occasionally pass, at least locally.
**One of the elements of unreliability is the connection to the MQTT broker**

@markoer can you start looking into this in terms of fixing them a bit before reimplementing them?

**Comment by MMaiero** [comment]
Due to the recent changes in tests, can this be closed? @cdealti @markoer @djurod

**Comment by markoer** [comment]
@cdealti added a local broker and reenabled the tests, which now usually pass. I suppose it could be closed.
