### ISSUE TITLE
[Web-UI] Invalid XSRF token exception when adding factory components

### ISSUE THREAD

**Issue by nicolatimeus** [eclipse/kura#838]
Clicking on the "+" button for adding factory components in the left panel may cause exceptions regarding invalid XSRF tokens.
This is caused by the fact that `EntryClassUi.initServicesTree()` is used in various parts of the code to refresh the services list, the problem is that this method also adds event handlers to the ui elements of the left panel.
This makes possible that when the "+" button is pressed multiple identical event handlers are triggered firing multiple concurrent rest requests that will fail due to the XSRF tokens.

**Comment by ctron** [comment]
I have seen those errors every now and then even before using the + button. So maybe this is not solely related to it.
