### ISSUE TITLE
Unable to add same open port in firewall for tcp and udp

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#84]
This bug was originally posted at https://bugs.eclipse.org/bugs/show_bug.cgi?id=459361.

Original message:

I use kura on debian (PI) and I try to open port 514 in the firewall config page for both udp and tcp.

After I add entry 514 / udp/ eth0, save, apply, all ok, I try to do the same for 514 / tcp / eth 0.

On Submit I get the error Duplicate Entry - Not adding to the list of Open Port.

Looks like primary key is wrong.

Ilya,

Can you check on this behavior?

Thanks,
--Dave

**Comment by ibinshtok** [comment]
This is fixed in the Kura 1.4.0 release.
