### ISSUE TITLE
Fix up file upload dialog

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#848]
Currently the file input is styled as `form-control`, which is not supported by bootstrap [1], [2] and renders for me as:

![screenshot from 2016-11-28 13-47-53](https://cloud.githubusercontent.com/assets/202474/20669002/0417c82a-b572-11e6-9602-d9170d1ddf7b.png)

And easy fix would be to render the input field without the `form-control` class and inside a `well`:

![screenshot from 2016-11-28 13-48-54](https://cloud.githubusercontent.com/assets/202474/20669016/17978b56-b572-11e6-906d-aa8a8c64b9ec.png)

And beside that, I really like the new look! @nicolatimeus 

[1] https://getbootstrap.com/css/#forms-controls
[2] https://getbootstrap.com/css/#inputs

**Comment by MMaiero** [comment]
@nicolatimeus  could you take a look at it? Thanks

**Comment by nicolatimeus** [comment]
Sure, I'll take a look
