### ISSUE TITLE
Concurrency problem in deployment agent service ?

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#85]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=480484.

Original Message:

Hi guys !

We faced of a serious problem with the Deployment Agent service (in all version)

Sometimes this service is blocked and don't deploy our ".dp". Last log we have from the service is : 

2015-10-23 12:59:23,389 [Component Resolve Thread (Bundle 6)] INFO  o.e.k.d.a.i.DeploymentAgent - Deploying package name io.stemys.kura.application.shopfloor at URL file:/opt/eclipse/kura/kura/packages/io.stemys.kura.application.shopfloor-0.2.0.dp

And nothing else.

When it's works we have the next log message :

2015-10-23 12:59:23,392 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - About to install package at URL file:/opt/eclipse/kura/kura/packages/io.stemys.kura.application.shopfloor-0.2.0.dp

It's really random. We look at the code to see what is between these two log messages and we think the problem come from the synchronized part on "m_instPackageUrls"

The synchronized part on a ConcurrentLinkedQueue is really necessary ? We remove it and  the problem was resolved for us.

We never saw this problem before but now that we installed Kura on a powerfull device (core i7 / 16 Gb ram / SSD / ...) we have the problem.

Thanks in advance for your job !

Hello,

It is hard to comment on this without knowing your application. I believe the synchronization block is necessary when attempting to install the deployment package. A couple of questions:

1. When you see this issue, are you also getting error in the log files (/var/log/kura.log and /var/log/kura-console.log)?
2. Do you have any potential long running processes in your bundle activate methods? This can often cause issues when activating bundles. 

Thanks,
--Dave

**Comment by cdealti** [comment]
@MMaiero: Can you please take a look?

**Comment by MMaiero** [comment]
Modified Kura code in release-1.4.0 branch, in order to try to prevent this error.
