### ISSUE TITLE
Clean up ValidationUtils vs Preconditions

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#857]
Currently there seem to be two ways of validating parameters. And existing one (ValidationUtils) and a new one introduced with the Kura Wires PR (Preconditions).

Now first of all I don't really understand why "Preconditions" is in "API" and not in the "Utils" bundle. Second I think that there should be only one. I don't see a benefit of having two in Kura.

ValidationUtils provides proper error codes, but needs a cleanup on the JavaDoc. Also maybe requires a few additional methods which are available in Preconditions.

So I would suggest that:
1) Both get merged
2) and placed in the "kura.utils" bundle instead of "kura.api"

**Comment by amitjoy** [comment]
`Preconditions` is being used by the Wires related POJOs hence it is placed in `org.eclipse.kura` top level package. We still can move it to utility bundle but in such a scenario, API would depend on utility bundle which makes it a bit unusual as the API bundle must be always the one to start first. Then the rest of the bundle.

**Comment by ctron** [comment]
Can you point me to a location in API where a dependency to utils would then be triggered?!

**Comment by ctron** [comment]
I can't find any dependency which would be introduced by that change. So I guess we can ignore this and move the classes to "utils".

**Comment by amitjoy** [comment]
In wire, type, asset and driver

**Comment by ctron** [comment]
Thanks. The only check that I see is "checkNull" .. So I would suggest to use Objects.requireNonNull in this case and move Preconditions class to "utils".

**Comment by MMaiero** [comment]
Could this be closed? For what I remember now we have dropped Preconditions and started using Objects.requireNonNull

**Comment by amitjoy** [comment]
We still need to refactor `org.eclipse.kura.core.util.ValidationUtil` as it also comprises methods as already provided by `Objects` and Kura Utility bundle (`org.eclipse.kura.util`)
