### ISSUE TITLE
a detailed exception should be thrown whenever a component is 'unresolved'

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#86]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=477275.

Original Message:

there can be many reasons for a component to fail to load, leading to it being 'unresolved'. in two examples:

1. I had a 'default' access level method named 'activate' which was not defined within the Component.xml
2. I had a private constructor

.. I had no idea at the time why the component was not loading, only after commenting out line by line did I find my mistakes.

If you are just watching the logs, it appears the platform silently ignores the componeont. Using OSGI console command 'ls' the component will appear 'unresolved' but still no detail as to what failed.

Therefore, if the component is defined via the manifest.mf or indeed, if it has a Component.xml or @Component annotation, any reason for it to fail to load should be thrown as an exception.

Hi Paul,

Sorry for the slow reply, I am trying to go through and clean up the list of bugs. For reference, this was also mentioned in this forum post [1]. 

I am not sure how much Kura can do in these situations, if you have suggestions I am happy to discuss. The intent of the Kura ConfigurationService and Kura ConfigurableComponent was to assist in managing bundle configurations. The framework does not get involved in managing the life cycles of the bundles, leaving this instead to the OSGi container. Since ConfigurationService is tracking all Components within the OSGi container, it is plausible to set up a listener for different events, but this system may become rather complex.

I think to do this correctly, we would need a new service which would use EventAdmin to track OSGi bundle messages. It wouldn't make since to throw exceptions from here, but you could certainly log useful messages. 

Let me know what you think.

[1] https://www.eclipse.org/forums/index.php/t/1070255/

Thanks,
--Dave

thanks for getting back david.

since posting this i have learnt to use the 'comp' command within the osgi terminal which gives some further information regarding why a component might be 'unresolved'.

maybe an easier solution with less re-architecting would be just to interrogate the deployment package's components via osgi after the load and log their details?

i'm assuming there is an easy way to do the equivalent of the following from within kura?

osgi> ss mydeployment
[bid] active mybundle
osgi> ls [bid]
[cid] unresolved mycomponent
osgo> comp [cid]

failing something simple like this, maybe just another developer guide document? the above has more or less resolved this issue for me, i just keep two terminals open when testing now.

let me know what you think.

**Comment by cdealti** [comment]
Can this be closed? As observed this can be done using the ```component``` command of the OSGi console.

**Comment by kartben** [comment]
+1

**Comment by dwoodard1** [comment]
Since OSGi bundle/component issues can be tracked easily using the OSGi console, this issue is being closed.
