### ISSUE TITLE
Kura's WEB bundles detection

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#861]
When Kura starts, the /var/log/kura.log contains the following:
```o.e.k.c.s.SystemServiceImpl - Kura has web interface? true```
even if web interface wasn't even built

**Comment by cdealti** [comment]
Minor thing:
 
 https://github.com/eclipse/kura/blob/release-2.1.0/kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/system/SystemServiceImpl.java#L316

Posponed

**Comment by MMaiero** [comment]
The message is maybe misleading. Probably it would be better to say "Is Kura web interface enabled?". That value is based in a property set in kura.properties file and that allows to disable the web interface if not needed. It has no relation to the fact that the web ui was built or was available.
We will change the logged message accordingly.
Thanks for finding that out.

**Comment by markoer** [comment]
Even this question implies presence of web UI. But it is still better than the existing one.

**Comment by MMaiero** [comment]
Just to complete the answer: the fact that the web bundle exists or not is not catched by Kura. What is managed by this property is that if the web bundle exists in the filesystem, the user can choose if he wants to have that bundle started or not.
