### ISSUE TITLE
[Kura 2.1.0 QA errata] Various errata

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#865]
* Device->Profile page data

It is normal for the following fields to be populated like so:
```
Model Name    Raspberry-Pi
Model ID      Raspberry-Pi
Part Number   Raspberry-Pi
Serial Number Raspberry-Pi
```

Multiple platforms behave this way.

* NET-ETH0-001 test case from #788

Test eth0: In Networking (Denali) -> Configure the eth0 interface as follows:
     Status: Enabled for LAN
     Configure: Manually
     IP Address: [some_static_address_allowed_on_your_network]
     Subnet Mask: [appropriate_mask_for_your_network]
     Then try to connect to ethernet port 0 with your browser

Likely the eth0 interface is meant instead of port 0; test description should be updated.

* NET-ETH0-003 test case from #788 instructs to
Modify eth0 status...
Configure MqttDataTransport to connect to mqtt://iot.eclipse.org:1883 broker.
Configure DataService to enable connect.auto-on-startup

The instruction is a bit misleading since there are separate pages for configuration of these parameters:
eth0 is configured under System->Network->eth0 while MqttDataTransport and DataServce are tabs under System->Cloud Services.

**Comment by cdealti** [comment]
@markoer @djurod @ctron If you are tracking test descriptions errata in your spreadsheets, I'd close this one.

**Comment by ctron** [comment]
I don't understand what you mean by that.

**Comment by cdealti** [comment]
this issue was opened to track the errata to the test descriptions.
Since then I believe @markoer has tracked down these in his spreadsheet.
Eventually we will have a new revision of the spreadsheet.

**Comment by ctron** [comment]
Well I went with the original spreadsheet. Let me know when you have a new one.

**Comment by markoer** [comment]
These are in my spreadsheet already. You may freely close the issue.

**Comment by cdealti** [comment]
yes, please mutually check your spreadsheets before opening new issues.
We will merge your spreadsheet changes in a new revision when 2.1.0 is released.

**Comment by cdealti** [comment]
@markoer If you have a change to upload your spreadsheet that would help (unless you still have concerns registering to Microsoft)

**Comment by djurod** [comment]
Just a note that the hardware information in the device profile page for BeagleBone Black (#791) is probably also problematic. Each field contains the value "beaglebone".
