### ISSUE TITLE
[Web UI] Logout missing

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#866]
While it is true that Kura web UI can be run in Incognito mode/Private window, logout functionality is something users such as myself expect from a web UI.

**Comment by cdealti** [comment]
@markoer we'll take a look after 2.1.0 is out

**Comment by cdealti** [comment]
@MMaiero can this be easily implemented?

**Comment by cdealti** [comment]
@MMaiero can this easily be implemented?

**Comment by MMaiero** [comment]
Probably. I bet it would require a session invalidation. But needs to be tested.

**Comment by MMaiero** [comment]
https://stackoverflow.com/questions/2180206/how-to-force-jetty-to-ask-for-credentials-with-basic-authentication-after-invali
