### ISSUE TITLE
Kura NN should not depend on ethtool, bind9, isc-dhcp-server, hostapd 

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#87]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=476616.

Original Message:

Unless I'm missing something, I believe the "no network" .deb package should not be depending on any networking tool, right?

Agree. 
However, just one exception, it seems that ethtool is still needed for LinuxNetworkUtil bundle to get ethernet MAC address for kura MQTT default client-id.

I am going to use this bug to track bug fixes for the *NN* installation packages. At present, not only are the networking system dependencies required, but the networking bundles are also being installed and started. This is not the correct behavior and should be corrected.

Thanks,
--Dave

**Comment by MMaiero** [comment]
This should be now fixed in Kura 1.4.0: the emulator splitting into different bundles permitted to add the net emulator bundle into kura nn. In this way we don't need to use ethtool to get the MAC address and the networking bundles are, also, not needed to have Kura dependencies satisfied.
