### ISSUE TITLE
[Kura 2.1.0 QA] eth0 DNS server configuration

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#874]
If a new DNS server is added in eth0 configuration it is expected to show up in /etc/resolv.conf file. It seems it is only stored in Kura configuration, because /etc/resolv.conf is not modified after the configuration is applied.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment]
@markoer it may take some time to update resolv.conf. Can you please recheck?

**Comment by pierantoniomerlino** [comment]
It seems that `dhcpcd5` can interfere with DNS settings (see #867). @markoer Could you please try again removing this package from the system (sudo apt-get purge dhcpcd5)?

**Comment by markoer** [comment]
Purging dhcpcd5 helps with this issue.
What I also noticed outside of test NET-ETH0-006 scope is that search domain is neither added to `/etc/resolv.conf` nor stored in Kura configuration.

And while we are at it (configuration), there are a few configuration parameters values of which are not trimmed, namely: net.interface.eth0.driver, net.interface.wlan0.firmware.version, net.interface.wlan0.wifi.capabilities, net.interface.wlan0.driver, net.interface.wlan0.driver.version.

**Comment by cdealti** [comment]
@markoer can you close this one (it was due to a running dhcpcd) and open another issue for the remaining problems. Unless they are relevant for the QA they will be addressed in 3.0.0.

**Comment by markoer** [comment]
Closing the issue.

The new ones are #923 and #924.
