### ISSUE TITLE
[Kura 2.1.0 QA] Disabling eth0 interface doesn't work properly

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#876]
Disabling the eth0 interface and apply the configuration in Kura web UI. The interface will not be disabled (still accessible over ehternet, ifconfig still shows eth0 configuration), but Kura will show it as such.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment]
@markoer It will take some time to disable eth0.
Note: Kura doesn't bring the interface down. It disables the interface by removing it's IP address.
Can you post the output of the command "ip"?

**Comment by markoer** [comment]
The interface is still up and running, even after a few minutes. Device is still accessible over eth0 without a problem.

```
# ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:b3:53:03  
          inet addr:10.XXX.XXX.XXX  Bcast:10.XXX.XXX.255  Mask:255.255.255.0
          inet6 addr: XXX/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
...
```

```
# ip addr
...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:b3:53:03 brd ff:ff:ff:ff:ff:ff
    inet 10.XXX.XXX.XXX/24 brd 10.XXX.XXX.255 scope global eth0
       valid_lft forever preferred_lft forever
...
```

**Comment by pierantoniomerlino** [comment]
@cdealti @markoer Also in this case, the issue is related to `dhcpcd5` (see #867). Please remove the package (`sudo apt-get purge dhcpcd5`) and kill the service.

**Comment by cdealti** [comment]
@markoer can you please confirm and close it?

**Comment by markoer** [comment]
Confirmed. It does take a bit more than a moment (up to ~30 s), but it works.

Closing the issue.
