### ISSUE TITLE
[Kura 2.1.0 QA] Raspberry Pi 3 nameserver

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#879]
Test case NET-ETH0-011 from #788 includes the following configuration:

On Network->eth0 DHCP & NAT page, set the following
Router Mode: DHCP and NAT
DHCP Beginning Address: 192.168.1.10
DHCP Ending Address: 192.168.1.254
DHCP Subnet Mask: 255.255.255.0
DHCP Default Lease Time: 900
DHCP Max Lease Time: 900
Pass DNS Servers through DHCP: yes

When this is applied, the test case expects the bind (named) to run. What actually happens is that named runs before and is stopped after.

Kura 2.1.0 build 12, Raspberry Pi 3, `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`

**Comment by cdealti** [comment]
@markoer it may take some time to apply the configuration and restart named. Can you please recheck waiting longer?

**Comment by markoer** [comment]
Waiting a bit longer might actually have helped. Or it might have been a result of otherwise disabled wlan0 coming back online at roughly the same time (but not in Kura).
Also switching `Pass DNS Servers through DHCP` on and off doesn't have the same effect as on wlan0 interface. With wlan0 named is started/stopped as a result of the switch.

**Comment by pierantoniomerlino** [comment]
@markoer @cdealti I wasn't able to reproduce this issue on my RPi3. Bind service is correctly restarted when a modification is done on the eth0 interface.

**Comment by cdealti** [comment]
@pierantoniomerlino thanks
@markoer the Kura netadmin can be painfully slow to bring up the intended configuration.
There are in the netadmin some monitor threads that run every 30s so you may have to wait that interval or even more before the intended network configuration is into effect.

I would try like that: apply the configuration from the Web UI, wait 60s and check the expected configuration. Would that work?

**Comment by cdealti** [comment]
@markoer ping

**Comment by markoer** [comment]
Looks like dhcpcd5 package purge (#867) influenced this as well. The change is virtually immediate, now.

I updated the prerequisites with the finding(s).

Issue may be closed.
