### ISSUE TITLE
[Kura 2.1.0 QA] Available Radio modes in wireless interface Station Mode 

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#880]
Test case NET-WIFI-003 from #788 expects Radio mode 802.11g/b to be selected in Station Mode under System->Network->wlan0->Wireless.

Only 802.11n/g/b is available and combo box is disabled.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment]
@markoer I believe it depends on how the WiFi driver reports the available modulations.
We will take a look but it's likely this is the only option on the RPI 3.

**Comment by markoer** [comment]
What is strange is that in Access Point mode 3 options are available: b, g/b, n/g/b.

**Comment by cdealti** [comment]
@MMaiero I believe our findings are that the selection is not available in Station Mode and the value is set to all the available modulations.

@markoer can you update the test description?

**Comment by cdealti** [comment]
@markoer If you have updated the test description this can be closed

**Comment by cdealti** [comment]
@markoer I'm closing this. Please reopen if you don't agree on the resolution

**Comment by markoer** [comment]
It's OK.
