### ISSUE TITLE
Invalid field validation state when switching from WAN to LAN

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#883]
In the network UI:

Pre-conditions:
* eth0 is configured for WAN with DHCP

Steps:
* Select "manual" for eth0
* Clear the "gateway" field, may already be empty
* Press save -> error, OK
* Select "LAN" for eth0
* Press save -> error -> NOT OK

The field is no longer required when the mode is switched from WAN to LAN, but the field validation is not reset.

**Comment by cdealti** [comment]
Fixed by #884.
