### ISSUE TITLE
[Kura 2.1.0 QA] Denali Configuration ExamplePublisher error descriptions

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#889]
Error messages are misleading for long, integer, short, double, float, byte: message says 'smaller', but should be 'smaller or equal' on the high limit, and 'greater' where it should be 'greater or equal' on low limit. It could otherwise specify a different (higher/lower) number (e.g. 4294967297 for long).

Test cases DEN-CONF-005 - DEN-CONF-029 from #788.

Other notes on these tests:
DEN-CONF-016 reports `For input string: "32768"` instead of expected `Value out of range. Value: 32768…`
DEN-CONF-027 mentions `Byte min -127 max 127.` which only confuses the users as those values are not allowed.
DEN-CONF-029 reports `For input string: "128"` instead of expected `Value out of range. Value: 128…`.

DEN-CONF-035 expects dirty flag on the fields. It is not visible in Firefox, Chrome or IE.

**Comment by markoer** [comment]
Retested on Kura 2.1.0 build 19.

'Normal' range error messages are now OK.

DEN-CONF-027's message is a part of the component configuration and serves as a sample of the possible metrics description, so it's also OK.

Notes regarding DEN-CONF-016 and DEN-CONF-029 still remain open (see #915).

**Comment by MMaiero** [comment]
I think this one can be closed, right @markoer?

**Comment by markoer** [comment]
Verified on PR #1189's branch. Closing the issue.
