### ISSUE TITLE
Increase Configurability of CloudService

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#89]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=481526.

Original Message:

Some users of Kura have found the static settings of the CloudService to restrictive. This bug is to track the proposal to expose more internal settings of the CloudService. Below is a listing of options to expose. Please use this bug to suggest additional options to expose or options to remove from the list.

* TOPIC_CONTROL_PREFIX - Already added via pull request: https://github.com/eclipse/kura/pull/64

* LIFECYCLE_RETAIN - Allow lifecycle messages to be retained for applications not using persistent storage.

* LIFECYCLE_PRIORITY - Specify priority of lifecycle messages.

* LIFECYCLE_QOS - Specify QOS of lifecycle messages.

Thanks,
--Dave

> * LIFECYCLE_RETAIN - Allow lifecycle messages to be retained for applications not using persistent storage.

I'm not sure this is a good idea because the broker will store the last message for each of the lifecycle messages. They are published on different topics so a connecting subscriber will receive the last birth and disconnect message in no particular order and won't be able to derive if the device is connected or not.

Also, it's difficult to reset the retain behavior because the device will have to publish an empty payload on the retained topic.

> * LIFECYCLE_PRIORITY - Specify priority of lifecycle messages.

In order to work correctly, the lifecycle messages need to be published immediately, overtaking the outstanding messages stored by the DataService.

> * LIFECYCLE_QOS - Specify QOS of lifecycle messages.
You want the lifecycle message to be published in the current MQTT session or never. If they were published with QoS > 0 and the connection is lost before they are acknowledged by the broker, either Kura or Paho will republish them on reconnect. However on reconnect a new lifecycle message, the birth certificate, will be published. For this reason we use QoS == 0 for lifecycle messages.

**Comment by cdealti** [comment]
Can we close this one? I haven't heard anything new on this topic.
