### ISSUE TITLE
[Kura 2.1.0 QA] Snapshot management in web UI

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#890]
DEN-SNAP-002 from #788 requires snapshot to be rolled back. The UI mentions possibility of a timeout after which manual refresh is necessary.

The issue is that the timeout probably didn't occur - it was definitely not indicated in any way in the UI, and the operation was rather fast - but UI data was not refreshed. ExamplePublisher's configuration remained as it was before the rollback until manual page refresh. And that happened every time I tried.

The same goes for snapshot file upload.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment]
Minor glitches. Postponed

**Comment by cdealti** [comment]
@nicolatimeus has this been improved with Kura 3?

**Comment by nicolatimeus** [comment]
No, the page refresh code is unchanged.

**Comment by MMaiero** [comment]
Related to current web ui improvements.

**Comment by markoer** [comment]
When the code is merged and build is available, I'll check it again and close.

**Comment by markoer** [comment]
Verified in 3.2.0-SNAPSHOT b1242
