### ISSUE TITLE
[Kura 2.1.0 QA] DEN-CLOCK-001 test case failures

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#892]
DEN-CLOCK-001 test from #788 is missing a rather important precondition: a working clock service configuration. It may require only a server change or possibly other changes. In the end the log should no longer display the clock synchronization issues.

The other issue is that after reboot the date is re-synched with the server.

Kura 2.1.0 build 12, Raspberry Pi 3, Raspbian GNU/Linux 8, `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`

**Comment by cdealti** [comment]
> DEN-CLOCK-001 test from #788 is missing a rather important precondition: a working clock service configuration. It may require only a server change or possibly other changes. In the end the log should no longer display the clock synchronization issues.

Do you mean the Test description needs to be updated?

> The other issue is that after reboot the date is re-synched with the server

Can you please check if ``ntpd`` is running on the RPI?

**Comment by markoer** [comment]
That's true on the first issue, yes. I'll check the second.

**Comment by cdealti** [comment]
@markoer any updates on this?

**Comment by markoer** [comment]
ntpd was indeed running. If it is disabled, the date gets set to some other date, neither one from ntp server, nor one out of one of the recent snapshots.

**Comment by cdealti** [comment]
So test DEN-CLOCK-001 passes if ntpd is disabled?
In that case I would close this, taking note of disabling ntpd in the install instructions.
Can you please track this in you revision of the validation spreadsheet?

**Comment by markoer** [comment]
In my opinion the test still does not pass. The end date (after the system boots again) should be the one set manually by `date` command, right? But it is not.

**Comment by cdealti** [comment]
In the case of the RPI I don't think the system clock is retained across reboots. This expectation may be true on platforms with an RTC battery-backed. I believe the test description has been copied from the one for gateways.

I believe this is not really an issue.

The purpose of the test is to simply check that if the Kura Clock Service has been disabled, after a reboot, the system clock is not synchronized.
Does changing the test description along these line work?

I also believe that DEN-CLOCK-002 needs to be modified

**Comment by markoer** [comment]
In this case it's OK.
I'll add this to the updated test spreadsheet.
