### ISSUE TITLE
[Kura 2.1.0 QA] Browse button alignment in Firefox

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#894]
System-Device->Command and System->Settings->Snapshots->Upload and Apply
Browse button is not properly aligned with the row:
![browse](https://cloud.githubusercontent.com/assets/22816717/20890881/e341e404-bb08-11e6-8375-3db149e2613a.png)

In Chrome and IE it's OK.

Kura 2.1.0 build 12, Firefox 43.0.1

**Comment by ctron** [comment]
I think this is already fixed on `develop`

**Comment by cdealti** [comment]
Yes

**Comment by markoer** [comment]
If the fix is planned to be merged into 2.1.0, I propose to reopen so it can be properly verified. otherwise let's rename (remove [Kura 2.1.0 QA]) and find the associated PR.

**Comment by MMaiero** [comment]
Fixed by #854

**Comment by markoer** [comment]
Thanks :)
