### ISSUE TITLE
[Kura 2.1.0 QA] Refreshing configuration in web UI

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#895]
Forms are not properly refreshed with applied data when configuration is updated.

Example:
* Procedure:
  * System-Cloud Services->DataService
  * update connect.retry-interval from 60 to 600
  * Apply
  * update disconnect.quiesce-timeout from 10 to 100
  * Reset

* Expected results:
  * connect.retry-interval is 600
  * disconnect.quiesce-timeout is 10

* Actual results:
  * connect.retry-interval is 60
  * disconnect.quiesce-timeout is 10

If I refresh the page, it's OK.

Similar to #890.

Kura 2.1.0 build 12, Raspberry Pi 3, Firefox, Chrome, IE

**Comment by cdealti** [comment]
Does this happen consistently or randomly?

**Comment by markoer** [comment]
The issue is consistent across browsers and reboots or RPi3.

**Comment by MMaiero** [comment]
@markoer Could you kindly test [this build](https://s3.amazonaws.com/kura-installers/kura_2.1.0_RC_12-12/kura_2.1.0_raspberry-pi-2-3_installer.deb) that, I think, fixes this issue?
Thanks.

If it will work, I'll merge the PR into release-2.1.0 release branch.

**Comment by markoer** [comment]
With Kura 2.1.0_RC_12-12 the result is as expected. But there is the additional confirmation dialog, which, I suppose, doesn't bother too much.

**Comment by MMaiero** [comment]
So, is it ok for you to merge the related PR?

**Comment by markoer** [comment]
As far as I am concerned, you may merge it.
