### ISSUE TITLE
[website] Images in "Solution Showcases" should be clickable

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#90]
This bug was originally filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=456781.

Original Message:

The new "Solution Showcases" section is very cool! 
It would be great if the images were clickable in addition to the text, since I believe many people are trying to click on them as a first intent.

A related suggestion would be to put the labels below the images rather than next to them, and center the text. It would probably give more white space and make it clearer which "button" goes with which label.

**Comment by cdealti** [comment]
@dwoodard1 do you think we can close this?
