### ISSUE TITLE
[Kura 2.1.0 QA] usbutils missing in fedberry README

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#900]
In the Fedberry README the RPM `usbutils` seems to be missing. Unless it is not more required.

**Comment by cdealti** [comment]
No, I think it's OK to add this dependency in the README on the release-2.1.0 branch.
Can you send a PR please?

**Comment by ctron** [comment]
A PR? Can we do this directly?

**Comment by cdealti** [comment]
Please push it directly
