### ISSUE TITLE
[Kura 2.1.0 QA] changing username/password locks out admin access

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#901]
Changing the credentials as requested in DEN-003 brings the system in a state that you can no longer log on. The newly created username/password combination does not get accepted by Kura.

**Comment by markoer** [comment]
I tested this using Kura 2.1.0 build 12 on Raspberry Pi 3 with Chrome, FF and IE without problems. Either changing password or both username and password. I did not reboot the device before trying to log back in.
Maybe something changed between the commit of that build and the one you used, just as a hint for investigation.

**Comment by cdealti** [comment]
@ctron what username/password did you use?

**Comment by ctron** [comment]
foo/bar ... foo/foo ... admin/foo ... admin/bar

**Comment by cdealti** [comment]
Nothing in the kura.log and kura-console.log?

**Comment by ctron** [comment]
No

**Comment by cdealti** [comment]
How do you logout? The test description is ambiguous...

**Comment by ctron** [comment]
I don't log out. The UI asks me so log in again. Probably because the HTTP basic auth check fails.

**Comment by cdealti** [comment]
@MMaiero any ideas?

**Comment by MMaiero** [comment]
Just tested using the latest hudson build and a build done in my computer. I've found no issues changing the access credentials. I've tested it both using raspbian and fedora and specifying different combinations of usernames and passwords
Don't know. Maybe @ctron can give me more hints on how to reproduce the issue.

**Comment by ctron** [comment]
Not really. I did install it. Started the first tests and directly ran into it.

I can try to reproduce it. If you let me know what information I should capture when it happens again, I will provide this to you.

**Comment by ctron** [comment]
I re-tried this again right now and got the system in the same state. Let me know what you want me to send or test.

**Comment by MMaiero** [comment]
ok, maybe I've found. I'll dig into it.

**Comment by MMaiero** [comment]
@ctron could you please test [this](https://s3.amazonaws.com/kura-installers/kura_2.1.0_RC_13-12/kura_2.1.0_fedorapi_installer.sh) and see if it solves your issue?

**Comment by ctron** [comment]
:+1:  this works
