### ISSUE TITLE
[Kura 2.1.0 QA] Web UI doesn update connection status

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#905]
While performing test NET-ETH0-003 and NET-ETH0-004 I noticed that the MQTT connection was established but the UI still shows "disconnected". Reloading the web page shows "connected".

**Comment by cdealti** [comment]
The "refresh" glitches of the Web UI are well known. Occasionally we have to manually refresh to see an update.

I will be better with Kura 3.0.0.

I propose to make a note in the QA validation mentioning the extra refresh and close the issue.

**Comment by MMaiero** [comment]
The icon refresh is invoked only when clicking on the status tab or refreshing the page. It is not invoked by an event. That will be changed in kura 3.0.0 (it is already in develop)
