### ISSUE TITLE
[Kura 2.1.0 QA] Unable to access Web UI - NET-WIFI-002

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#906]
When testing NET-WIFI-002 I only received "connection refused"

```
[jreimann@jreimann ~]$ telnet 172.16.1.1 80
Trying 172.16.1.1...
telnet: connect to address 172.16.1.1: Connection refused
```

**Comment by cdealti** [comment]
Can you provide the iptables output?

Have you rebooted at least once after the Kura install?

**Comment by ctron** [comment]
Yes
> Have you rebooted at least once after the Kura install?

I have to re-try this, let me know all the details that you need. So I can provide them.

**Comment by cdealti** [comment]
the ouput of ``iptables --list`` and relevant log lines in syslog, kura.log and kura-console.log.

**Comment by ctron** [comment]
I tried a few things, but I cannot reproduce it.

So we can close this an re-open if it re-appears.
