### ISSUE TITLE
Web UI shows its own WLAN for connecting

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#908]
When performing test NET-WIFI-003 you are required to select a SSID for connecting. However the dialog for selecting the SSID also shows its own SSID, which should at least be marked as its own.

**Comment by cdealti** [comment]
Do you mean its own SSID is listed in the scan results?

**Comment by ctron** [comment]
Yes

**Comment by cdealti** [comment]
Nice catch. I've never noticed this before. I guess that filtering out the self SSID is feasible but maybe not P1.

**Comment by ctron** [comment]
True.
