### ISSUE TITLE
[Kura 2.1.0 QA] SSID selection dialog too small

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#909]
The SSID selection dialog is too small and content overlaps with the background:

![kura_ssid_1](https://cloud.githubusercontent.com/assets/202474/20970680/f34fb204-bc8e-11e6-9a6f-5c0e211e634c.png)

**Comment by ctron** [comment]
Happens with:
* Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
* 54.0.2840.59 (Official Build) (64-bit)

**Comment by cdealti** [comment]
Assigned to @nicolatimeus
