### ISSUE TITLE
[Kura 2.1.0 QA] DEN-CONF-003 "publish.semanticTopic" does not exists

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#913]
The test description references to "publish.semanticTopic" which does not exists. Probably this should be changed to "publish.appTopic"

**Comment by cdealti** [comment]
Are you OK with taking a note in your QA validation spreadsheet and close this?
It's the same I've asked @markoer to do in these circumstances.

**Comment by ctron** [comment]
I think I already did that. Close it if you like.
