### ISSUE TITLE
[Web UI] Fixed fields can be edited

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#914]
By using browser console window "fixed" fields can be edited and the value actually assigned to the configuration:

```
2016-12-07 16:14:18,925 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.e.p.ExamplePublisher - Update - metric.integer.fixed: 777
```

**Comment by MMaiero** [comment]
What you mean with:

> By using browser console window

**Comment by ctron** [comment]
You simply open the browser's debug window ... Shift+Ctrl+C on Linux with Firefox

**Comment by cdealti** [comment]
@ctron it's not a QA test. Do you mind if I edit the title and postpone this?

**Comment by ctron** [comment]
Well I do think this is related to the test. The test says you should not be able to modify the value. But I am able to modify the value.

**Comment by cdealti** [comment]
Modify the value through the Web UI.
The validation is also missing in the server side.
I don't think we will be able to fix it for 2.1.0.

**Comment by ctron** [comment]
That is the problem with client side validation. You always have to do it on the server side in addition.

Of course you can re-schedule this for 3.0.0. But I would suggest adding a note to the "known issues" section in this case.

**Comment by cdealti** [comment]
Agreed. Rescheduled for 3.0.0 and attached a ``kura-sec`` label.

**Comment by cdealti** [comment]
We could **copy** [Kapua's validation code](https://github.com/eclipse/kapua/blob/develop/commons/src/main/java/org/eclipse/kapua/commons/configuration/ValueTokenizer.java#L181)
