### ISSUE TITLE
DEN-CONF-005 Wrong range limit for "long"

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#916]
In test DEN-CONF-005 the limit for "long" is -4294967296 max 4294967296.

However the 64bit Java long is actually: 9223372036854775807L to -9223372036854775808L [1]

[1] https://docs.oracle.com/javase/7/docs/api/constant-values.html#java.lang.Long.MAX_VALUE

**Comment by cdealti** [comment]
See #913

**Comment by ctron** [comment]
I don't understand how those two are related?!
