### ISSUE TITLE
[Kura 2.1.0 QA] DEN-POS-002 Position service keeps reporting old position

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#918]
When switching static position reporting from on to off on the raspberry pi on Fedberry, the old position is still shown in the status overview. Although the Raspberry Pi doesn't have a GPS device.

**Comment by cdealti** [comment]
Is there a test ID for this?
I believe the service reports the last fix. If the RPI does not have a modem there will be not new fix and the old, static position would be reported.

**Comment by ctron** [comment]
Yes, as noted in the title of this issue: DEN-POS-002

**Comment by cdealti** [comment]
So, you would expect the Web UI showed an position "Not available" instead of the old static one?

**Comment by ctron** [comment]
Yes

**Comment by cdealti** [comment]
Can you take note of this to add it to the known issues and postpone this to 3.0.0?

**Comment by ctron** [comment]
@MMaiero can you amend the know issues of your document?

**Comment by MMaiero** [comment]
done

**Comment by ctron** [comment]
So we can just re-title this one for Kura 3.0?!

**Comment by MMaiero** [comment]
For now I just modified the milestone. After the release I will rename all kura 3 issues removing the references to 2.1.0 QA

**Comment by cdealti** [comment]
@pierantoniomerlino can you take a look?
Please add a QA item to the latest QA validation spreadsheet maintained by @markoer.

**Comment by markoer** [comment]
It's in gh-pages branch under assets/qa/system-test/qa_kura.ods.

**Comment by pierantoniomerlino** [comment]
I fixed the issue regarding the GPS static position. 

However, there are a couple of issues that we have to address:
1. Each time the modem monitor fires, it emits a GPS device present event. This triggers the position service and a birth certificate is published. So, if the "republish.mqtt.birth.cert.on.gps.lock" property is set, at every monitor run a birth message is published. As a result, a lot of birth messages are publish even if the static position is enabled.
2. If the GPS device is not present, the last acquired position is published.

For the first item, IMHO we should publish the first birth message and filter the others when a static position is set. For the latter, it makes sense to publish the last acquired position and at least log that the GPS device is not present.

@ctron @cdealti what do you think?

**Comment by MMaiero** [comment]
@ctron @cdealti Can we close this since PR #1233 was merged?

**Comment by ctron** [comment]
Looking at PR #1233 I don't really understand how this could fix the issue. But if you are sure this issue is fixed, then yes you may close it.
