### ISSUE TITLE
[Kura 2.1.0 QA] NET-WIFI-001 Failed to connect to wifi

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#919]
When re-testing NET-WIFI-001 with my mobile I ran into the issue that Android cannot connect to the AP created by Kura.

**Comment by cdealti** [comment]
It may take a while to setup the AP.
Can you wait a little bit longer before connecting Android?

**Comment by ctron** [comment]
What amount of time?

**Comment by cdealti** [comment]
Well, not one hour. If after 60s you cannot connect then we have a problem

**Comment by ctron** [comment]
Ok. I will re-test this one.

**Comment by ctron** [comment]
Ok .. after waiting for maybe 5 minutes .. (coffee ... dirty water break) ... it worked.

So let's close this.
