### ISSUE TITLE
Build and test dependencies for Kura 3.0.0

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#920]
This is an issue for tracking all build and test dependencies for Kura 3.0.0

**Comment by ctron** [comment]
```
org.apache.karaf.tooling : karaf-maven-plugin : 4.0.7   - APL2  - https://karaf.apache.org/
```

**Comment by ctron** [comment]
```
docker : 1.10   - APL2  - https://docker.org
```

**Comment by dwoodard1** [comment]
@ctron Can we postpone this issue until the next release?

**Comment by ctron** [comment]
I think those should be in a build and test CQ for Kura 3.0.0, so from what I know this should be included in the IP log for Kura 3.0.0.

I would ask to you check with the Eclipse IP team or EMO if this is ok to be postponed.

**Comment by dwoodard1** [comment]
@ctron Could you create the CQ? EMO said they would try to get it reviewed quickly.

**Comment by ctron** [comment]
Giving the Kura build setup a brief check showed up to additional dependencies to me which seemed to haven been forgotten. The full request should be:

```
Kura would like to use the following dependencies as build and test dependencies, those dependencies will not be distributed in any form:

---
org.apache.karaf.tooling : karaf-maven-plugin : 4.0.7   - APL2  - https://karaf.apache.org/
docker : 1.10   - APL2  - https://docker.org
bnd-baseline-maven-plugin  : 3.4.0-SNAPSHOT - APL2 - https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin
findbugs-maven-plugin : 3.0.1 - APL2 - https://gleclaire.github.io/findbugs-maven-plugin
---
```

However, before we do a re-re-spin of the IP log, I would kindly ask you to check this as well and amend the list with any additions I did not pick up.

**Comment by cdealti** [comment]
@ctron thanks!
Please add the following build and test dependencies. They are all from the Orbit R20160520211859 drop. 
```
org.hamcrest : 1.1.0.v20090501071000 - BSD - http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/
org.hamcrest.library : 1.1.0.v20090501071000 - BSD -  http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/
org.hamcrest.text : 1.1.0.v20090501071000 - BSD - http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/
org.hamcrest.integration : 1.1.0.v201303031500 - BSD -http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/
```

**Comment by ctron** [comment]
CQ created – https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13380

**Comment by dwoodard1** [comment]
EMO stated we did not need to re-submit the IP log since these are build/test dependencies.

Anything else before I ask them to expedite the review?

**Comment by cdealti** [comment]
Not on my side. I've added what I was aware of

**Comment by cdealti** [comment]
build/test dependencies have been approved so this can be closed.
Thanks @ctron @dwoodard1.

**Comment by ctron** [comment]
I don't see any approval up until now. Could you please point me towards this.

**Comment by cdealti** [comment]
You already know it's not been approved yet ;-). I've been to enthusiast seeing a couple of +1s.

**Comment by dwoodard1** [comment]
The CQ has been approved. Closing the issue.
