### ISSUE TITLE
[Kura 2.1.0 QA enh] Non-trimmed values of configuration parameters

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#924]
There are a few configuration parameters values of which are not trimmed, namely:
* net.interface.eth0.driver
* net.interface.wlan0.driver
* net.interface.wlan0.driver.version
* net.interface.wlan0.firmware.version
* net.interface.wlan0.wifi.capabilities

How to check? Download a snapshot and open it in your favorite editor. Search e.g. for '> ' or ' <'.

Probably this is not really a problem, but may be nice to update.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment]
As this is not critical let's postpone it.
