### ISSUE TITLE
[Kura 2.1.0 QA] ExamplePublisher: changed fields don't have a dirty flag visible in the upper left corner of the field

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#934]
According to test case DEN-CONF-035 from #791 and #788

I wasn't able to see any changes in the GUI after the value was changed and focus moved out of the changed field.

Tested in Firefox, Chrome and Internet Explorer on build 12 and 15.

**Comment by cdealti** [comment]
I believe that this has been already brought up by @markoer. The dirty flag is no longer supported in the new Web UI. I cannot find the original report. @markoer do you have this tracked in your validation spreadsheet?

**Comment by markoer** [comment]
It is in my spreadsheet, but only @djurod reported it as an issue, here.

**Comment by cdealti** [comment]
So, if this is tracked in Marko's spreadsheet, it will be addressed in the new spreadsheet revision.
OK to close?

**Comment by djurod** [comment]
If this feature was removed, then I would recommend that we remove the test case (DEN-CONF-035).

**Comment by markoer** [comment]
@djurod exactly (just mark it as such for the time being)
@cdealti OK

**Comment by djurod** [comment]
I added a note that the feature was removed.

@cdealti: I think you can close the issue.

**Comment by markoer** [comment]
It turns out I actually reported this as part of #889, but hid it well.
