### ISSUE TITLE
[Kura 2.1.0 QA] Raspberry Pi 3 no-net installer

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#941]
Errors in the installation log file of Kura 2.1.0 no-net build 15 for RPi 3:
```
cp: cannot create regular file /opt/eclipse/kura/.data/.recoverDefaultConfig.sh: No such file or directory
chmod: cannot access /opt/eclipse/kura/.data/.recoverDefaultConfig.sh: No such file or directory
```

The entire directory .data/ is non-existent. I also checked .deb file/its .zip and it's already missing in there.

**Comment by MMaiero** [comment]
@markoer Could you test if the proposed PR solves your issue? Thanks

**Comment by markoer** [comment]
That seems to do the trick (at least on RPi3). I will retest when the PR is merged and a new build is available.

**Comment by MMaiero** [comment]
ok, so I'll merge.

**Comment by markoer** [comment]
Verified in Kura 2.1.0 no-net build 16, RPi3.
