### ISSUE TITLE
[Kura 2.1.0 QA] MAC Address must be lowercase

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#944]
When setting "Permitted MAC Address" in Firewall->Open Ports->New you must enter the MAC address in lower case format with `:` as a delimiter.

It would be nice if also uppercase format would be allowed, but in any case the format should be visible somewhere in the GUI (in the tooltip?).

Kura 2.1.0 build 15 on Raspberry PI 2

**Comment by cdealti** [comment]
Yes, nice to have but... for the next iteration

**Comment by cdealti** [comment]
@darionct can you please confirm this is still true?

**Comment by darionct** [comment]
Web  form accepts both lower and upper case and firewall is properly configured. However, still no info (tooltip) about the delimiter.
