### ISSUE TITLE
Clean up OSGi dependencies

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#945]
Dependencies on OSGi core and compendium APIs have to be cleaned up.

Right now Kura makes use of Equinox 3.11.1 which provides OSGi R5 for core and compendium. However in addition to Equinox there is the OSGi compendium artifact referenced in version 4.3.

This for example results in the Kura API bundle to reference both `osgi.cmpn` and `org.eclipse.equinox.io` which both provide the package `org.osgi.service.io`. The same is true for a lot of other combinations of bundles and packages throughout Kura.

**Comment by cdealti** [comment]
I don't see any references to the `org.eclipse.equinox.io`bundle in the MANIFEST.MF of the Kura bundles but in `org.eclipse.kura.protocol.modbus` and `org.eclipse.kura.core.test`. In both cases I would not be worried too much. Closing
