### ISSUE TITLE
[Kura 2.1.0 QA] NET-FW-010 Unable to verify dialog

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#951]
Testing NET-FW-010 a dialog pops up requesting me to verify if my platform supports MAC address filtering. 

However the is no explanation how to do this.

**Comment by cdealti** [comment]
Check if you have ``CONFIG_IP_NF_MATCH_MAC`` or ``CONFIG_NETFILTER_XT_MATCH_MAC`` (or like configuration) is enabled in your kernel configuration.

**Comment by ctron** [comment]
I guess this should be documented and linked somewhere.

**Comment by cdealti** [comment]
You are lucky if at least you got a popup with a message ;-)
It's difficult to document everything, the Fedberry is a new platform.
If you have a chance, check your kernel config. Maybe you can load this as a kernel module.

@markoer did this pass on Raspbian?

**Comment by ctron** [comment]
I passed. So there is no problem other than the fact that the user doesn't know what to do when the dialog appears.

**Comment by cdealti** [comment]
Can be closed? Better documentation is enough for this release?

**Comment by ctron** [comment]
Re-target for 3.0.0, maybe adding some link in the dialog pointing to some documentation.

When we are closing it we will be create a new issue when doing 3.0.0 QA, pointing to this as a duplicate.

**Comment by cdealti** [comment]
Eventually, how this passed for the Fedberry?

**Comment by ctron** [comment]
It did.

**Comment by markoer** [comment]
In the first few tries I skipped the tests following NET-FW-008, but I tested them now (on RPi3, up to 011) and they work with a minor modification of the command used in NET-FW-011.

**Comment by cdealti** [comment]
@ctron OK, but the question was: how? If it's just a matter of installing or loading a kernel module and you have taken notes on how to do this in order to later upgrade the installation documentation I believe this can be closed. I don't see any notes in your spreadsheet though.

@markoer thanks. I've seen the clarification in your spreadsheet.

**Comment by ctron** [comment]
How? I don't know. It just worked. I can't tell you any details why or why not.

**Comment by cdealti** [comment]
Jens I can see NET-FW-010 is now green on your spreadsheet and I'm not sure if you were able to recreate. I'm closing this. Please re-open if you do not agree.
