### ISSUE TITLE
[Kura 2.1.0 QA] Wrong labels in UI's DHCP&NAT configuration

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#958]
As part of NET-ETH0-011 in #788 DHCP server needs to be configured in Kura. The lease times' units used by dhcpd are seconds and are written in the config file unmodified by Kura. Therefore the labels here are incorrect ('mins' instead of 's'):
DHCP Default Lease Time (mins)
DHCP Max Lease Time (mins)

Kura 2.1.0 build 16

**Comment by cdealti** [comment]
So the right labels should be
```
DHCP Default Lease Time (s)
DHCP Max Lease Time (s)
```
Correct?

**Comment by markoer** [comment]
Correct.

**Comment by cdealti** [comment]
If you have time to submit a PR fixing this I'd be glad to merge it

**Comment by cdealti** [comment]
See #961
