### ISSUE TITLE
Kura web UI: multiple styles for representing yes/no and true/false etc.

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#960]
Enhancement in Kura web part: a style guide may be needed for representing various types of data.

1. A good example with multiple styles is the representation of yes/no values where at least 3 types can be identified in the basic installation:
* dropdown (select+options)
![yn_dropdown](https://cloud.githubusercontent.com/assets/22816717/21312991/80073898-c5ef-11e6-81eb-56792c156434.png)
* buttons (radio button with background)
![yn_button](https://cloud.githubusercontent.com/assets/22816717/21312998/88fa5746-c5ef-11e6-816c-c7822f8a8bef.png)
* radio buttons
![yn_radio](https://cloud.githubusercontent.com/assets/22816717/21313002/8d212d90-c5ef-11e6-919d-57c0326d3f40.png)

But a checkbox might work best in all these cases, otherwise the least obtrusive way are pure radio buttons (option 3).

2. Another example is a single-option select represented with combo boxes (instead of e.g. radio buttons):
![single_selection_cb](https://cloud.githubusercontent.com/assets/22816717/21313144/571d8724-c5f0-11e6-8361-1c6e0429170a.png)

Tested on Kura 2.1.0 build 16 in Chrome.

**Comment by cdealti** [comment]
@markoer are you willing to fix the remaining issues in this area (and avoid breaking the test automation)?
