### ISSUE TITLE
Add support for Bluetooth 4.2 and 5

### ISSUE THREAD

**Issue by tomislavi** [eclipse/kura#975]
Add support for devices which have Bluetooth version 4.2 or 5.

In org.eclipse.kura.linux.bluetooth.util.BluetoothUtil there is:
`// HCI version : 4.0 (0x6) or HCI version : 4.1 (0x7)`
`if (result.indexOf("0x6") >= 0 || result.indexOf("0x7") >= 0) {`

**Comment by dwoodard1** [comment]
Hello,

Sorry for the delayed response. Unfortunately, we haven’t been able to verify Kura against Bluetooth > 4.1. Until we can, we don’t feel comfortable enabling this support. May I ask what device/BLE adapter/OS you are using that is using Bluetooth > 4.1?

Thanks,
--Dave

**Comment by tomislavi** [comment]
I was playing with BLE examples in emulator on my laptop with integrated Bluetooth. That is not IoT gateway, but it would be useful for development or for learning Kura if Bluetooth worked.

HP ProBook 650 G2
Intel Dual Band Wireless-AC 8260 802.11a/b/g/n/ac (2x2) WiFi and Bluetooth® 4.2 Combo
Linux

hciconfig hci0 version

hci0:   Type: Primary  Bus: USB
        BD Address: XX:XX:XX:XX:XX:XX  ACL MTU: 1021:4  SCO MTU: 96:6
        HCI Version: 4.2 (0x8)  Revision: 0x100
        LMP Version: 4.2 (0x8)  Subversion: 0x100
        Manufacturer: Intel Corp. (2)
        
./btmgmt le on
hci0 Set Low Energy complete, settings: powered connectable discoverable bondable ssp br/edr le secure-conn

Beacon example says:
Bluetooth adapter le enabled => false

**Comment by dwoodard1** [comment]
Thanks for the information. We will check around and see what we can find in the way of > 4.1 BLE dongles. In the meantime, you could edit and compile the source code for yourself. You identified the small bit of code that needs to change. It would be great to hear your feedback on how the Beacon example worked with 4.2.

Thanks,
--Dave

**Comment by pierantoniomerlino** [comment]
FYI, [here](https://www.bluetooth.com/specifications/assigned-numbers/host-controller-interface) there are the HCI version numbers that the code should check.

**Comment by cdealti** [comment]
@tomislavi do you have feedback on this?

**Comment by cdealti** [comment]
Closing as support for Bluez 5 has been added with Kura 3.1.0.

**Comment by pierantoniomerlino** [comment]
@cdealti We didn't test any device with Bluetooth HCI 5.0. I guess that the new API will support also that version, but I've not evidence about that.

However, I think that we can close this issue for now.
