### ISSUE TITLE
Publish the source code for the JDK DIO module

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#989]
According to the Eclipse Foundation when using a GPL+CPE module the source code has to be pulished as well:

> 3. Many open source projects do not provide binaries for their GPL+CE-licensed
code. If the Eclipse project builds the executable form of the code from
source, it must provide all source and build scripts such that a third party
may attempt to re-build the distributed binary.

That is currently not true for the JDK DIO module of Eclipse Kura. Unless I have overlooked it.

**Comment by dwoodard1** [comment]
I really thought I commented on this, not sure what happened.

@LucaDazi Where do we have the JDK DIO source code?

**Comment by cdealti** [comment]
In the kura target-platform

**Comment by dwoodard1** [comment]
Where? I see the Class files, but not the source.

**Comment by cdealti** [comment]
Sorry, in the esf target-platform

**Comment by ctron** [comment]
Is there any update on this?

**Comment by dwoodard1** [comment]
I will work on this today.

**Comment by cdealti** [comment]
Closed by #1299.
