### ISSUE TITLE
Provide a Karaf feature

### ISSUE THREAD

**Issue by kartben** [eclipse/kura#99]
In order to ease the installation of Kura in a Karaf container, it would be great to add a Karaf feature definition to the repo and Maven build.
Hopefully, it's not too difficult, see eg https://github.com/eclipse/smarthome/blob/master/features/karaf/pom.xml

Having Kura available in the form of a Karaf feature would make it much easier to install it in the same OSGi container as e.g Eclipse SmartHome, or OpenDaylight

**Comment by cdealti** [comment]
@kartben @ctron Can we close this?

**Comment by ctron** [comment]
We are far away from this goal. But I still see this as a goal. So let's keep it open.

**Comment by cdealti** [comment]
Moved this to the In Progress pipeline as @ctron has started working on this and we have started looking at his work.

**Comment by cdealti** [comment]
Karaf will not be further developed or maintained. The existing code will stay as long as it does not interfere with the main Kura development.
