### ISSUE TITLE
Emulator does not start due to mandatory javax.comm dependency

### ISSUE THREAD

**Issue by amitjoy** [eclipse/kura#993]
Emulator (only tested in OSx) does not start due to mandatory dependency of `javax.comm` in API bundle. The OSGi runtime could not find any bundle exporting `javax.comm`, hence all the transitive and intransitive bundles failed to start. Just for a quick test, I have set `javax.comm` as an optional package in API bundle which resulted in successful start of the emulator.

**Comment by ctron** [comment]
Which launch configuration have you been using?

**Comment by amitjoy** [comment]
I am using OSx launch configuration. It is quite weird as I am encountering this issue quite rarely but it still exists.

**Comment by ctron** [comment]
Could you try the generic launch configuration?

**Comment by amitjoy** [comment]
You mean the Linux one?

**Comment by ctron** [comment]
No I mean the generic one.

**Comment by cdealti** [comment]
@amitjoywhat is the status of this issue?

**Comment by amitjoy** [comment]
It still exists and each and every time, I am staring Kura Emulator, I need to make `javax.comm` package `optional` in `API` manifest and then everything works. Otherwise everything fails.

**Comment by cdealti** [comment]
@amitjoy can you confirm #1349 works form you?

**Comment by MMaiero** [comment]
I would close this for now. Eventually, we will reopen it, if the issue arises again.
